### ISSUE TITLE
Can't get server to start due to errors

### ISSUE THREAD

**Issue by Intecpsp** [plamoni/SiriProxy#10]
Here is me trying to run the proxy server:

Codys-MacBook-Pro:SiriProxy cody$ sudo ruby start.rb 
Password:
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- cfpropertylist (LoadError)
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from ./siriProxy.rb:5
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from start.rb:6
Codys-MacBook-Pro:SiriProxy cody$

**Comment by plamoni** [comment]
Did you install the appropriate Ruby Gems?

**Comment by Intecpsp** [comment]
Ya, the only one I had an issue with is open-uri

**Comment by Intecpsp** [comment]
And I didn't mean to close this, idk what happened.
