### ISSUE TITLE
Certificate ca.pem is 0 byes and will not install on iPhone.

### ISSUE THREAD

**Issue by rosswaycaster** [plamoni/SiriProxy#100]
Here is the cert. log: http://pastie.org/2946131

**Comment by bikr** [comment]
I'll assume you'e doing this on Mac as I had the same issue.  Follow the original procedure to create manually and copy them into ~/.siriproxy/  and you should be fine , make sure you email the pem to yourself and install on phone.

**Comment by rosswaycaster** [comment]
Do you know where I can find instructions for the original manual procedure? I think it has been removed from the README file..

**Comment by bikr** [comment]
The readme links to the YouTube vid I think. I'll find soon and send

Sent from my iPhone

On Nov 30, 2011, at 4:19 PM, rosswaycaster
reply@reply.github.com
wrote:

**Comment by mvilrokx** [comment]
Same here, on Ubuntu

**Comment by mvilrokx** [comment]
here's that video btw: http://www.youtube.com/watch?v=_oaNbPOUCaE

**Comment by rosswaycaster** [comment]
Thanks! @mvilrokx did you get yours to work?

**Comment by mvilrokx** [comment]
Yes, following those video instructions + you have to copy the certificates (both those keyless things) to ~/.siriproxy rather than the application folder.

**Comment by plamoni** [comment]
This has been fixed in the dev branch.
