### ISSUE TITLE
siriproxy start error

### ISSUE THREAD

**Issue by poinch** [plamoni/SiriProxy#105]
hello,  i have this problem

MacBooks-Poinch:SiriProxy Poinch$ sudo ruby ./start.rb
ruby: No such file or directory -- ./start.rb (LoadError)

i have installed ruby 1.9.2 but 1.9.3 doesn't work, i have mac osx lion.

Thanks

**Comment by plamoni** [comment]
Please follow the current setup instructions carefully.
