### ISSUE TITLE
SiriProxy Start Error

### ISSUE THREAD

**Issue by KirmaanA** [plamoni/SiriProxy#106]
When I Try To Start I Receive This Error

rvmsudo siriproxy server
/Users/Kirmaan/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/pr_eventmachine.rb:402:in `open_loopbreaker': Unable to bind Loopbreaker (RuntimeError)
    from /Users/Kirmaan/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/pr_eventmachine.rb:316:in`run'
    from /Users/Kirmaan/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/pr_eventmachine.rb:64:in `run_machine'
    from /Users/Kirmaan/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run'
    from /Users/Kirmaan/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1/lib/siriproxy.rb:16:in `initialize'
    from /Users/Kirmaan/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1/lib/siriproxy/command_line.rb:96:in`new'
    from /Users/Kirmaan/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1/lib/siriproxy/command_line.rb:96:in `start_server'
    from /Users/Kirmaan/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1/lib/siriproxy/command_line.rb:85:in`run_server'
    from /Users/Kirmaan/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1/lib/siriproxy/command_line.rb:37:in `initialize'
    from /Users/Kirmaan/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1/bin/siriproxy:6:in`new'
    from /Users/Kirmaan/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1/bin/siriproxy:6:in `<top (required)>'
    from /Users/Kirmaan/.rvm/gems/ruby-1.9.3-p0/bin/siriproxy:19:in`load'
    from /Users/Kirmaan/.rvm/gems/ruby-1.9.3-p0/bin/siriproxy:19:in `<main>'

Thanks :)

**Comment by ftwhacker** [comment]
Hey :)
I had this problem but you can easy start the siriproxy next time :)
After you use "rvmsudo siriproxy server" command, next time you use it you will get this error.
Just type:
sudo killall ruby
then "rvmsudo siriproxy server" then you should start siriproxy :)

-ftwhacker

**Comment by elvisimprsntr** [comment]
closed due to inactivity
