### ISSUE TITLE
siriproxy gencerts ERROR

### ISSUE THREAD

**Issue by SONY5614** [plamoni/SiriProxy#108]
$ bash < <(curl -s https://raw.github.com/wayneeseguin/rvm/master/binscripts/rvm-installer)
$ [[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"
$ echo '[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # Load RVM function' >> ~/.bash_profile

Logout

$ sudo rvm install 1.9.3
$ rvm use 1.9.3 --default 

$ rvmsudo gem install rake bundler
$ rake install  (or $ sudo rake install)

$ mkdir ~/.siriproxy
$ cp ./config.example.yml ~/.siriproxy/config.yml
$siriproxy gencerts 
-bash: siriproxy: command not found

$ cd pkg
$  rvmsudo gem install siriproxy
Successfully installed siriproxy-0.0.1
1 gem installed
Installing ri documentation for siriproxy-0.0.1...
file 'lib' not found
Installing RDoc documentation for siriproxy-0.0.1...
file 'lib' not found

Why?

**Comment by mobzilla** [comment]
Try:

```
bundle exec siriproxy gencerts
```

**Comment by SONY5614** [comment]
I slowed the response.Sorry.

$ sudo bundle exec siriproxy gencerts
/Users/XXX/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:247:in `to_specs': Could not find bundler (>= 0) amongst [bigdecimal-1.1.0, io-console-0.3, json-1.5.4, minitest-2.5.1, rake-0.9.2.2, rdoc-3.9.4] (Gem::LoadError)
    from /Users/XXX/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:256:in`to_spec'
    from /Users/XXX/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems.rb:1210:in `gem'
    from /Users/XXX/.rvm/gems/ruby-1.9.3-p0/bin/bundle:18:in`<main>'

**Comment by plamoni** [comment]
You should not be bundling or doing a rake install as root (with "sudo"). Please follow the directions precisely.

**Comment by SONY5614** [comment]
$ bundle exec siriproxy gencerts
git://github.com/chendo/cora.git (at master) is not checked out. Please run `bundle install`

$ bundle install
Updating git://github.com/chendo/cora.git
Fetching source index for http://rubygems.org/
Using rake (0.9.2.2) 
Using libxml-ruby (2.2.2) 
Using CFPropertyList (2.0.17) 
Using cora (0.0.3) from git://github.com/chendo/cora.git (at master) 
Using eventmachine (0.12.10) 
Using uuidtools (2.1.2) 
Using siriproxy (0.0.1) from source at /Users/XXX/Desktop/SiriProxy 
Using siriproxy-example (0.0.1) from source at ./plugins/siriproxy-example 
Using bundler (1.0.21) 
Your bundle is complete! Use `bundle show [gemname]` to see where a bundled gem is installed.

$ bundle exec siriproxy gencerts
bundler: command not found: siriproxy
Install missing gem executables with `bundle install`

$ cd pkg
$ rvmsudo gem install siriproxy
Password:
Successfully installed siriproxy-0.0.1
1 gem installed
Installing ri documentation for siriproxy-0.0.1...
file 'lib' not found
Installing RDoc documentation for siriproxy-0.0.1...
file 'lib' not found

$ cd ../
$ rake install
siriproxy 0.0.1 built to pkg/siriproxy-0.0.1.gem
rake aborted!
Couldn't install gem, run `gem install /Users/XXX/Desktop/SiriProxy/pkg/siriproxy-0.0.1.gem' for more detailed output

Tasks: TOP => install
(See full trace by running task with --trace)

**Comment by RoHS2** [comment]
I'm having the same issue. Where did I go wrong?

**Comment by ingeniero2005** [comment]
Hi,i have the same problem after install rake ("rake install"). After install rake i see the next line: 

"command not found: siriproxy"

**Comment by ingeniero2005** [comment]
Hi,i have the same problem after install rake ("rake install"). After install rake i see the next line:

"command not found: siriproxy"

Someone can help me please?

**Comment by elvisimprsntr** [comment]
Who's instructions are you using?  Because no where do the sanctioned instructions tell you to perform rake install.   Follow the documented instructions.
