### ISSUE TITLE
Starting siri server error

### ISSUE THREAD

**Issue by adamrock** [plamoni/SiriProxy#109]
That error happens after i launch siri on my iphone, it justs stays on '"Starting SiriProxy on port 443.." until i launch siri on my iphone

**Comment by plamoni** [comment]
Your cents are not set up or are incorrectly located. They now need to be located in ~/.siriproxy/

**Comment by plamoni** [comment]
Certs. Not cents.

**Comment by Enophi** [comment]
How did you fix the problem ?
