### ISSUE TITLE
Can't get server started due to errors

### ISSUE THREAD

**Issue by Intecpsp** [plamoni/SiriProxy#11]
Idk what happened with the other one so I just decided to make a new one. The only gem I had trouble with was open-uri but I think I got it installed. Here is me trying to run the proxy server:

Codys-MacBook-Pro:SiriProxy cody$ sudo ruby start.rb 
Password:
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in gem_original_require': no such file to load -- cfpropertylist (LoadError)
from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:inrequire'
from ./siriProxy.rb:5
from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in gem_original_require'
from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:inrequire'
from start.rb:6
Codys-MacBook-Pro:SiriProxy cody$

**Comment by plamoni** [comment]
Make sure that the CFPropertyList gem is installed. That would be my guess
on what's causing that error.

-Pete

On Mon, Nov 21, 2011 at 12:30 PM, Intecpsp <
reply@reply.github.com

**Comment by Intecpsp** [comment]
Still no luck:

Codys-MacBook-Pro:~ cody$ pear install pearhub/CFPropertyList
pearhub/CFPropertyList is already installed and is the same as the released version 1.1.1
install failed
Codys-MacBook-Pro:~ cody$ cd Documents/SiriProxy/
Codys-MacBook-Pro:SiriProxy cody$ sudo ruby ./start.rb
Password:
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- cfpropertylist (LoadError)
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from ./siriProxy.rb:5
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from ./start.rb:6
Codys-MacBook-Pro:SiriProxy cody$

**Comment by plamoni** [comment]
Maybe capitalization? Try changing the capitalization on the require. Let
me know if that fixes it. Feel free to submit a pull request if it does~

-Pete

On Mon, Nov 21, 2011 at 12:35 PM, Intecpsp <
reply@reply.github.com

**Comment by Intecpsp** [comment]
Changing the capitalization where exactly?

**Comment by plamoni** [comment]
from

require 'cfpropertylist'

to

require 'CFPropertyList'

-Pete

On Mon, Nov 21, 2011 at 12:43 PM, Intecpsp <
reply@reply.github.com

**Comment by Intecpsp** [comment]
FFS, I'm about to give up:

Codys-MacBook-Pro:SiriProxy cody$ sudo ruby ./start.rb
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- CFPropertyList (LoadError)
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from ./siriProxy.rb:5
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from ./start.rb:6
Codys-MacBook-Pro:SiriProxy cody$

**Comment by plamoni** [comment]
Hmm... I really don't know. Sorry. Maybe someone who is more familiar with
Ruby can assist? I'm really not an expert on Ruby.

-Pete

On Mon, Nov 21, 2011 at 12:46 PM, Intecpsp <
reply@reply.github.com

**Comment by nuclearace** [comment]
I'm getting this error:

internal:lib/rubygems/custom_require:29:in `require': no such file to load -- plugins/thermostat/siriThermostat (LoadError)
    from <internal:lib/rubygems/custom_require>:29:in`require'
    from /Users/me/Desktop/SiriProxy/start.rb:2:in `<main>'

**Comment by Intecpsp** [comment]
I'll ask around, thanks for your help and for Siri Proxy!

**Comment by DouweM** [comment]
I'm getting the exact same error as @nuclearace!

**Comment by bssayeda** [comment]
I am getting that same issue as well....

**Comment by DouweM** [comment]
Could you see if it works when using `require_relative` instead of `require`?

**Comment by Intecpsp** [comment]
on the CFPropertyList?

**Comment by DouweM** [comment]
Wherever the `require` is failing.

**Comment by Intecpsp** [comment]
I changed 

require 'CFPropertyList'

to

require_relative 'CFPropertyList'

and I now get this:

Codys-MacBook-Pro:SiriProxy cody$ sudo ruby ./start.rb 
./siriProxy.rb:5: undefined method `require_relative' for main:Object (NoMethodError)
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from ./start.rb:6
Codys-MacBook-Pro:SiriProxy cody$

**Comment by bssayeda** [comment]
okay that worked...thanks a lot...

On Mon, Nov 21, 2011 at 2:12 PM, Douwe Maan <
reply@reply.github.com

> wrote:
> 
> Wherever the `require` is failing.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/plamoni/SiriProxy/issues/11#issuecomment-2819565

## 

Bilal S. Sayed Ahmad
iOS Developer
CEO & Developer of The Black NotebooK Inc
Check out our apps
here!http://itunes.apple.com/us/artist/the-black-notebook-inc/id428824153

**Comment by DouweM** [comment]
@Intecpsp Could you try updating Ruby?

**Comment by DouweM** [comment]
Note that I'm still getting a lot of require errors, even when using `require_relative`. I'm afraid I have no idea what else could be going wrong though.

**Comment by DouweM** [comment]
Adding this just below the hash bang (`#!...`) in `start.rb` gets rid of some of the require errors:

```
$: << File.dirname(__FILE__)
```

(via http://stackoverflow.com/questions/3865515/strange-inability-to-require-config-boot-after-upgrading-to-ruby-1-9-2)

**Comment by Intecpsp** [comment]
Ok, apparently I was one ruby 1.8.7 so I updated to 1.9.2 and now I get this error:

Codys-MacBook-Pro:SiriProxy cody$ sudo ruby ./start.rb 
Password:
internal:lib/rubygems/custom_require:29:in `require': no such file to load -- plugins/thermostat/siriThermostat (LoadError)
    from <internal:lib/rubygems/custom_require>:29:in`require'
    from ./start.rb:2:in `<main>'

Same as @nuclearace

**Comment by DouweM** [comment]
Tried my suggestion in the comment above yours?

**Comment by nuclearace** [comment]
I got it to work, but I had to remove the twitter tweak first.

**Comment by Intecpsp** [comment]
Which file do I add it to? siriProxy.rb?

**Comment by DouweM** [comment]
Add it to `start.rb`.

**Comment by Intecpsp** [comment]
Ok @DouweM, I added the line you posted to my start.rb and now I get this:

Codys-MacBook-Pro:SiriProxy cody$ sudo ruby ./start.rb 
/Users/cody/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': no such file to load -- uuidtools (LoadError)
    from /Users/cody/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from /Users/cody/Documents/SiriProxy/siriObjectGenerator.rb:3:in `<top (required)>'
    from <internal:lib/rubygems/custom_require>:29:in`require'
    from internal:lib/rubygems/custom_require:29:in `require'
    from /Users/cody/Documents/SiriProxy/plugins/thermostat/siriThermostat.rb:3:in`<top (required)>'
    from internal:lib/rubygems/custom_require:29:in `require'
    from <internal:lib/rubygems/custom_require>:29:in`require'
    from ./start.rb:3:in `<main>'
Codys-MacBook-Pro:SiriProxy cody$

**Comment by DouweM** [comment]
Yup, that's pretty much where I am now as well. For some reason it won't load `uuidtools`, even though I installed it using `gem install uuidtools`, and it shows up in `gem list`.

**Comment by Intecpsp** [comment]
Yup same here:

Codys-MacBook-Pro:~ cody$ gem list

**\* LOCAL GEMS ***

bundler (1.0.21 ruby)
CFPropertyList (2.0.17)
eventmachine (0.12.10)
httparty (0.8.1)
json (1.6.1)
libxml-ruby (2.2.2)
multi_json (1.0.3)
multi_xml (0.4.1)
rake (0.9.2.2, 0.9.2)
uuidtools (2.1.2)

EDIT: Just noticed open-uri wasn't on the list ('gem install open-uri' doesn't work)

**Comment by mvilrokx** [comment]
same here.

btw, you don't need an open-uri gem, it comes with ruby now, you can see by trying:

$ irb

> require 'open-uri'
>  => true

I disabled all the plugins except the test proxy one but it is still complaining on that one:

internal:lib/rubygems/custom_require:29:in `require': no such file to load -- plugins/testproxy/testproxy (LoadError)
    from <internal:lib/rubygems/custom_require>:29:in`require'
    from ./start.rb:3:in `<main>'

**Comment by MrCloud** [comment]
Same error here `no such file to load -- uuidtools (LoadError)` ... 
I'm using ruby 1.9.2 (from rvm)
gem list is fine.

**Comment by shack1108** [comment]
same here…..

sudo ruby ./start.rb
./start.rb:3: warning: variable $KCODE is no longer effective; ignored
/Users/Andrew/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in require': no such file to load -- uuidtools (LoadError)
from /Users/Andrew/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:inrequire'
from /Users/Andrew/Misc/SiriProxy/siriObjectGenerator.rb:2:in <top (required)>'
from internal:lib/rubygems/custom_require:29:inrequire'
from internal:lib/rubygems/custom_require:29:in require'
from /Users/Andrew/Misc/SiriProxy/plugins/testproxy/testproxy.rb:2:in'
from internal:lib/rubygems/custom_require:29:in require'
from internal:lib/rubygems/custom_require:29:inrequire'
from ./start.rb:5:in `'

I'm running Ruby 1.9.2, and I've re-installed uuidtools a couple of times.

**Comment by DouweM** [comment]
And same here :(

**Comment by Intecpsp** [comment]
count me in as well :(

**Comment by MrCloud** [comment]
I managed to resolve this issue, the problem was that my ruby 1.9.2 install (from rvm) was installed as a normal user.
Siri proxy has to be launched as a sudoer, and gems listed in the readme have to be installed as a sudoer to. 
It means you whould have a shared rvm installation or at least you should set rvm_path of su to your user's rvm. Consider these commands :

```sudo su
export rvm_path=/Users/#yourUsername#/.rvm/
rvm use 1.9.2

``````

then install gems as a sudoer:
```SiriProxy:⌥ master $ sudo gem install httparty
SiriProxy:⌥ master $ sudo gem install json
SiriProxy:⌥ master $ sudo gem install CFPropertyList
SiriProxy:⌥ master $ sudo gem install uuidtools
SiriProxy:⌥ master $ sudo gem install eventmachine
SiriProxy:⌥ master $ sudo gem install twitter```

I also had an issue trying to launch dnsmasq, in fact killing named once was not enough.
```SiriProxy:⌥ master $ sudo killall named
SiriProxy:⌥ master $ sudo killall named
SiriProxy:⌥ master $ sudo killall named
SiriProxy:⌥ master $ sudo killall named
SiriProxy:⌥ master $ sudo /opt/local/sbin/dnsmasq 
SiriProxy:⌥ master $ ps -Af | grep dnsmasq
SiriProxy:⌥ master $ sudo ruby ./start.rb ```
``````

**Comment by shack1108** [comment]
I did install the gems using sudo, but I will try setting the rvm_path

**Comment by DouweM** [comment]
@MrCloud I did everything you said, and I'm still getting the `uuidtools` `LoadError` :(

**Comment by MrCloud** [comment]
@DouweM 
Could you post the results of the following commands: 

 sudo su
 export rvm_path=/Users/#yourUsername#/.rvm/
 echo $rvm_path
 rvm use 1.9.2
 gem list

**Comment by DouweM** [comment]
@MrCloud
Here you go:

```
$ sudo su
sh-3.2# export rvm_path=/Users/douwemaan/.rvm/
sh-3.2# echo $rvm_path
/Users/douwemaan/.rvm/
sh-3.2# rvm use 1.9.2
Using /Users/douwemaan/.rvm/gems/ruby-1.9.2-p290
sh-3.2# gem list

*** LOCAL GEMS ***


...
uuidtools (2.1.2)
...
sh-3.2#
```

**Comment by MrCloud** [comment]
Seems good, and if you run gem-ruby-1.9.2-p290 list ?

**Comment by DouweM** [comment]
Same list of gems!

**Comment by netpro2k** [comment]
Please give the code on the refactored branch a shot. We have reworked how everything is loaded, which might help with this issue. (Note the changes in the README as well)

https://github.com/plamoni/SiriProxy/tree/refactored

**Comment by Intecpsp** [comment]
With that, I get this:

Codys-MacBook-Pro:SiriProxy cody$ rvmsudo ruby start.rb 
start.rb:3: warning: variable $KCODE is no longer effective; ignored
Starting SiriProxy on port 443..

Running? Should I remove the KCODE line?

**Comment by shack1108** [comment]
With the refactored branch, I get:

sudo ruby ./start.rb
Starting SiriProxy on port 443..
./siri_proxy.rb:27:in `initialize': Cannot start the server on port 443 - are you root, or have another process on this port already? (RuntimeError)
    from /Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`call'
    from /Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
    from /Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run'
    from ./siri_proxy.rb:18:in `initialize'
    from ./start.rb:21:in`new'
    from ./start.rb:21

I've checked using lsof -i :443, and nothing is on that port. Plus, I'm using sudo, so root shouldn't be a problem

**Comment by netpro2k** [comment]
You can safely remove it. We will likely be removing it from the mainline as well, as I think we are leaning towards supporting only ruby 1.9.

Closing this issue. Reopen if you are still having problems.

**Comment by shack1108** [comment]
Look at my comment 5 minutes ago. Unfortunately, I don't have
permission to reopen the issue.

**Comment by netpro2k** [comment]
Yep, just noticed this after I posted. This now seems like a separate issue related to #32 so discussion on this can continue there.

**Comment by shack1108** [comment]
Ok
