### ISSUE TITLE
Encryption not available on this event machine

### ISSUE THREAD

**Issue by ghost** [plamoni/SiriProxy#110]
Getting the following error after siri tries to connect

Create server for iPhone connection
terminate called after throwing an instance of 'std::runtime_error'
  what():  Encryption not available on this event-machine

Tried installing libssl-dev and reinstalled gem, ran through all install steps again and generated new certificates, but same problem.

Running on Ubuntu 11.10

Any other ideas on things to check?

**Comment by marcos69** [comment]
search the directory : gems/eventmachine-0.12.10/ext is there an ssl.o ? if not then take a look at the Makefile: remove the -DWITHOUT_SSL option, then make and make install.

**Comment by ghost** [comment]
There was already an ssl.o file, however I deleted it and made the change to the Makefile as recommended and ran make, make install. ssl.o was recreated.

Still get the same error. I tried rerunning the siriproxy bundle also

**Comment by ghost** [comment]
Fixed the issue with a clean install of Ubuntu Server
