### ISSUE TITLE
This is not really an issue but more of a how-to question

### ISSUE THREAD

**Issue by thejipster** [plamoni/SiriProxy#112]
What's the proper procedure in getting the new gem code activated?

I tried modifying the siriproxy-example.rb file and try a few different things and never can get siriproxy to recognize the new listen sections.

I tried rvmsudo gem build siriproxy-example.gemspec, then rvmsudo gem install siriproxy-example
Then I tried a few things with bundle , such as bundle update, bundle install

I then tried running rvmsudo siriproxy server and I get this error
git://github.com/chendo/cora.git (at master) is not checked out. Please run `bundle install`

ran bundle install again and still got the same error.

I finally ran siriproxy update and then ran rvmsudo siriproxy server, then the server started properly, but my changes in the plugin still weren't recognized.

Can someone please let me know what are the proper build steps after making changes?

I started with just siriproxy update and that didn't seem to work.

thanks

**Comment by Bramjetten** [comment]
What did you end up doing to fix it?

**Comment by thejipster** [comment]
The issue was that siriproxy is installed to a global location within your path.  So if you run rvmsudo siriproxy server it grabs the global siriproxy executable.  If you want to run the siriproxy code within SiriProxy dir tree you will have to evoke it with rvmsudo bin/siriproxy server.   

No special compilation besides running bin/siriproxy update if you had modified the config.yml file
