### ISSUE TITLE
rvmsudo SiriProxy server

### ISSUE THREAD

**Issue by poinch** [plamoni/SiriProxy#116]
Hello, please help me... :)

MacBooks-Poinch:SiriProxy Poinch$ rvmsudo SiriProxy server
/Users/Poinch/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems.rb:314:in `bin_path': can't find gem siriproxy ([">= 0"]) with executable siriproxy (Gem::GemNotFoundException)
    from /Users/Poinch/.rvm/gems/ruby-1.9.2-p290/bin/SiriProxy:19:in`<main>'

Different commands!!!      In the 1st i type  "SiriProxy" in the 2nd "siriproxy". But my plamoni folders that i have in the Desktop named SiriProxy

MacBooks-Poinch:SiriProxy Poinch$ rvmsudo siriproxy server
/Users/Poinch/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems.rb:314:in `bin_path': can't find gem siriproxy ([">= 0"]) with executable siriproxy (Gem::GemNotFoundException)
    from /Users/Poinch/.rvm/gems/ruby-1.9.2-p290/bin/siriproxy:19:in`<main>

Sorry for my bad english... and please help me

**Comment by plamoni** [comment]
The "siriproxy" command is case sensitive. Plase follow the instructions precisely.
