### ISSUE TITLE
SiriProxy:  "start.rb"  

### ISSUE THREAD

**Issue by Bloxin** [plamoni/SiriProxy#117]
Ok so ive seen that 90% of all these issues have to do with "start.rb"    the reason we are getting this error "No such file or directory -- start.rb (LoadError)"  is because their is no "start.rb"  in the directory or in the whole system....I already installed the bundle, Ruby, DNSMASQ ,Macports  etc..... no matter what you install at the end of the day it all comes down to "start.rb"  and since that is no where to be found then their is no way the Siri Proxy is gonna  be  up and running. Can someone please provide me a download link for the famous "start.rb" ????  please....I will gladly appreciate it.

Thanks in advance....

**Comment by plamoni** [comment]
please read the readme carefully. We no longer use start.rb and it's not included in any of the steps in the readme anymore.

This project is only a couple weeks old. It's in constant flux. Please refer to the current readme for instructions on how to get siriproxy running. Any other documentation may me out of date.
