### ISSUE TITLE
"INVALID PROFILE" after email

### ISSUE THREAD

**Issue by shameer99** [plamoni/SiriProxy#119]
after I email the ca.pem to my phone it says invalid profile. i don't know what to do

**Comment by laxman01** [comment]
same here

**Comment by rosswaycaster** [comment]
You will have to manually make your certificate.. Don't worry it's easy. http://www.youtube.com/watch?v=_oaNbPOUCaE

**Comment by plamoni** [comment]
Chances are your certificate didn't really get created (it's 0 bytes, I know the file might be there, but it's not a certificate). You need to either upgrade openssl to 1.0.x or you need to switch to the development branch of siriproxy, which has this error fixed.

**Comment by laxman01** [comment]
How do I switch to the dev branch

**Comment by shameer99** [comment]
how do i upgrade openssl?

**Comment by rosswaycaster** [comment]
http://lmgtfy.com/?q=How+to+upgrade+OpenSSL+on+Mac&l=1

**Comment by shameer99** [comment]
thanks hopefully it works

**Comment by shameer99** [comment]
i did that then i got an error 

Shameers-MacBook-Pro:SiriProxy Shameer$ siriproxy gencerts
/Users/shameer/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych.rb:154:in `parse': (/Users/shameer/.siriproxy/config.yml): couldn't parse YAML at line 12 column 6 (Psych::SyntaxError)
    from /Users/shameer/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych.rb:154:in`parse_stream'
    from /Users/shameer/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych.rb:125:in `parse'
    from /Users/shameer/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych.rb:112:in`load'
    from /Users/shameer/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych.rb:229:in `load_file'
    from /Users/shameer/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1/lib/siriproxy/command_line.rb:142:in`parse_options'
    from /Users/shameer/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1/lib/siriproxy/command_line.rb:33:in `initialize'
    from /Users/shameer/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1/bin/siriproxy:6:in`new'
    from /Users/shameer/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1/bin/siriproxy:6:in `<top (required)>'
    from /Users/shameer/.rvm/gems/ruby-1.9.3-p0/bin/siriproxy:19:in`load'
    from /Users/shameer/.rvm/gems/ruby-1.9.3-p0/bin/siriproxy:19:in `<main>'

**Comment by shameer99** [comment]
Shameers-MacBook-Pro:SiriProxy Shameer$ siriproxy gencerts
/Users/shameer/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych.rb:154:in `parse': (/Users/shameer/.siriproxy/config.yml): couldn't parse YAML at line 12 column 6 (Psych::SyntaxError)
    from /Users/shameer/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych.rb:154:in`parse_stream'
    from /Users/shameer/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych.rb:125:in `parse'
    from /Users/shameer/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych.rb:112:in`load'
    from /Users/shameer/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych.rb:229:in `load_file'
    from /Users/shameer/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1/lib/siriproxy/command_line.rb:142:in`parse_options'
    from /Users/shameer/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1/lib/siriproxy/command_line.rb:33:in `initialize'
    from /Users/shameer/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1/bin/siriproxy:6:in`new'
    from /Users/shameer/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1/bin/siriproxy:6:in `<top (required)>'
    from /Users/shameer/.rvm/gems/ruby-1.9.3-p0/bin/siriproxy:19:in`load'
    from /Users/shameer/.rvm/gems/ruby-1.9.3-p0/bin/siriproxy:19:in `<main>'
