### ISSUE TITLE
SiriProxy directory (the root of the repo) ? HELP!!!

### ISSUE THREAD

**Issue by Bloxin** [plamoni/SiriProxy#120]
Plamoni, in your instructions theirs a part where you say ...and i quote 

Set up SiriProxy

" Clone this repo locally, then navigate into the SiriProxy directory (the root of the repo) "

just exactly what do you mean (THE ROOT OF THE REPO) ???

then you say "Install SiriProxy gem (do this from your SiriProxy directory)"

so correct me if im wrong but the Siriproxy directory is not the same as the root of the repo ???

**Comment by adamoc** [comment]
From your user directory run this.

git clone -b dev git://github.com/plamoni/SiriProxy.git SiriProxy

Then:

cd SiriProxy

Now you are in the SiriProxy directory.

**Comment by Bloxin** [comment]
when i ran "git clone -b dev git://github.com/plamoni/SiriProxy.git SiriProxy" 

i got the following 

 error: unknown switch `b'
usage: git clone [options] [--] <repo> [<dir>]

**Comment by shameer99** [comment]
Google github for Mac and install. Then refresh the page for siri proxy. At the top it will say clone for Mac. Click and put it in your documents then in terminal type cd ~/Documents/SiriProxy

**Comment by Bloxin** [comment]
thx shameer99

**Comment by shameer99** [comment]
no problem
