### ISSUE TITLE
Bundler ERROR

### ISSUE THREAD

**Issue by dan122334455** [plamoni/SiriProxy#121]
When I sudo ./start.rb i get this error:

new-host-6:siriproxy root# sudo ./start.rb
./start.rb:3: warning: variable $KCODE is no longer effective; ignored
/usr/local/rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- bundler (LoadError)
    from /usr/local/rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from ./start.rb:6:in `<main>'
new-host-6:siriproxy root# 

Can you please help me?  I have been trying to work at this for about 5 days now.  It still wont work!!  I have my certificate and everything else..  If some one can answer this, I will be very thank full.  And also thank you so much plamoni for such a great "hack".  I cant wait to show my friends this once i get it up and running!  Ps: I am 15 years old, but i understand about programing and stuff.  I just can get this bundler thing to work.  I tried installing it from git and other sites and source codes...  Thanks again!

**Comment by netpro2k** [comment]
It looks like you are using an older version of siriproxy. Please update and follow the updated instructions
