### ISSUE TITLE
Rake install error

### ISSUE THREAD

**Issue by dan122334455** [plamoni/SiriProxy#122]
When i type rake install in my siriproxy folder, i get this error ( i used --trace)

new-host-6:SiriProxy Daniel$ rake install --trace
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/Users/Daniel/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2.2/lib/rake/application.rb:495:in `raw_load_rakefile'
/Users/Daniel/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2.2/lib/rake/application.rb:82:in`block in load_rakefile'
/Users/Daniel/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Users/Daniel/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2.2/lib/rake/application.rb:81:in`load_rakefile'
/Users/Daniel/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2.2/lib/rake/application.rb:65:in `block in run'
/Users/Daniel/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2.2/lib/rake/application.rb:133:in`standard_exception_handling'
/Users/Daniel/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/Users/Daniel/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2.2/bin/rake:33:in`<top (required)>'
/Users/Daniel/.rvm/gems/ruby-1.9.3-p0/bin/rake:19:in `load'
/Users/Daniel.rvm/gems/ruby-1.9.3-p0/bin/rake:19:in`<main>'

Your help is appreciated.  Thank you

**Comment by plamoni** [comment]
The error is very straightforward. You seem to be missing your Rakefile. Please make sure you properly clone the SiriProxy project.

**Comment by dan122334455** [comment]
How do you properly clone the siriproxy? Thank you so much!  I am working so hard on this and this is really holding me back.!!!!

**Comment by dan122334455** [comment]
I downloaded the git software.  Just how do you clone it locally with the software?? Thats what your supposed to do, correct?
