### ISSUE TITLE
Siri not working when running SiriProxy

### ISSUE THREAD

**Issue by rosswaycaster** [plamoni/SiriProxy#123]
When I try to use Siri she gives me an error about not being able to "take any request".
The terminal outputs this..

Starting SiriProxy on port 443..
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007fabb120b930 @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007fabb120b6d8>, @zip_stream=#Zlib::Deflate:0x007fabb120b6b0, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007fabb12ca970 @manager=#<SiriProxy::PluginManager:0x007fabb120b250 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007fabb12c65c8 @signature=4, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007fabb12c63e8>, @zip_stream=#Zlib::Deflate:0x007fabb12c63c0, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007fabb12c4cc8 @manager=#<SiriProxy::PluginManager:0x007fabb12c5cb8 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007fabb12c48b8 @signature=5, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007fabb12c4408>, @zip_stream=#Zlib::Deflate:0x007fabb12c43b8, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007fabb12c2e28 @manager=#<SiriProxy::PluginManager:0x007fabb12c3a80 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007fabb12c29a0 @signature=6, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007fabb12c2680>, @zip_stream=#Zlib::Deflate:0x007fabb12c2568, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007fabb12bf818 @manager=#<SiriProxy::PluginManager:0x007fabb12c0d58 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007fabb12bf4f8 @signature=7, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007fabb12bf1b0>, @zip_stream=#Zlib::Deflate:0x007fabb12bf188, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007fabb12bd658 @manager=#<SiriProxy::PluginManager:0x007fabb12be788 @plugins=[...]>>]

I am using my iMac as a router for my iPhone to connect to via wifi. My Mac has OpenDNS running on it and I can confirm that it works. My iPhone's wifi settings say that DNS is 10.0.2.1 like it is supposed to be. 

I can't figure out why it is spitting out this error!

Also my dnsmasq settings has this line in it..
address=/guzzoni.apple.com/10.0.2.1

Am I doing something wrong?

**Comment by rosswaycaster** [comment]
Nevermind, for some reason my computer is not communicating with guzzoni.apple.com

**Comment by sudoname** [comment]
how did you solve this issue? i am right here now and i am so close....
