### ISSUE TITLE
Error starting SiriProxy

### ISSUE THREAD

**Issue by adamoc** [plamoni/SiriProxy#124]
Any help appreciated. Thanks.

bash-3.2# rvmsudo siriproxy server
/Users/adam/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:247:in `to_specs': Could not find siriproxy (>= 0) amongst [bigdecimal-1.1.0, io-console-0.3, json-1.5.4, minitest-2.5.1, rake-0.9.2.2, rdoc-3.9.4] (Gem::LoadError)
    from /Users/adam/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:256:in`to_spec'
    from /Users/adam/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems.rb:1210:in `gem'
    from /Users/adam/.rvm/gems/ruby-1.9.3-p0/bin/siriproxy:18:in`<main>'

**Comment by mrmosconi** [comment]
Did you run this command?

rvm use 1.9.3 --default

**Comment by adamoc** [comment]
Yes. I've run that command, 1.9.3 is running. I've installed Rails as well, wasn't in the instructions but thought that might be the problem.

Still getting this error when I start SiriProxy under root.

**Comment by adamoc** [comment]
I found my problem I hadn't run this:

gem build siriproxy.gemspec
gem install siriproxy
