### ISSUE TITLE
SiriProxy gencerts

### ISSUE THREAD

**Issue by laxman01** [plamoni/SiriProxy#125]
rvm use 1.9.3:
Using /Users/Nick/.rvm/gems/ruby-1.9.3-p0

rvmsudo gem install rake bundler:
Successfully installed rake-0.9.2.2
Successfully installed bundler-1.0.21
2 gems installed
Installing ri documentation for rake-0.9.2.2...
Installing ri documentation for bundler-1.0.21...
Installing RDoc documentation for rake-0.9.2.2...
Installing RDoc documentation for bundler-1.0.21…

rake install:
siriproxy 0.0.1 built to pkg/siriproxy-0.0.1.gem
siriproxy (0.0.1) installed

mkdir ~/.siriproxy:
mkdir: /Users/Nick/.siriproxy: File exists

cp ./config.example.yml ~/.siriproxy/config.yml

siriproxy gencerts
-bash: siriproxy: command not found

what am I doing wrong to get this command not found error?



**Comment by adamoc** [comment]
You first need to clone the git. 

For the dev branch.
git clone -b dev git://github.com/plamoni/SiriProxy.git SiriProxy

Or.
git clone git://github.com/plamoni/SiriProxy.git SiriProxy

**Comment by laxman01** [comment]
ok i have cloned it but I'm still getting the same response with siriproxy gencerts
