### ISSUE TITLE
Siri not working on iPhone 4S

### ISSUE THREAD

**Issue by laxman01** [plamoni/SiriProxy#126]
when i start siriproxy server on my mac . and try to use Siri on my iPhone it says sorry I'm having trouble connecting to the network this only happens when i change the DNS to my mac ip address

**Comment by plamoni** [comment]
What IP do you have guzzoni.apple.com pointing to in your dnsmasq.conf?

**Comment by laxman01** [comment]
i went to system preferences then network then wifi then ip address

**Comment by rosswaycaster** [comment]
I am having this same problem.. When I try to use Siri she gives me an error about not being able to "take any request".
The terminal outputs this..

Starting SiriProxy on port 443..
Create server for iPhone connection
start conn #, @zip_stream=#Zlib::Deflate:0x007fabb120b6b0, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#>]
Create server for iPhone connection
start conn #, @zip_stream=#Zlib::Deflate:0x007fabb12c63c0, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#>]
Create server for iPhone connection
start conn #, @zip_stream=#Zlib::Deflate:0x007fabb12c43b8, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#>]
Create server for iPhone connection
start conn #, @zip_stream=#Zlib::Deflate:0x007fabb12c2568, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#>]
Create server for iPhone connection
start conn #, @zip_stream=#Zlib::Deflate:0x007fabb12bf188, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#>]

I am using my iMac as a router for my iPhone to connect to via wifi. My Mac has OpenDNS running on it and I can confirm that it works. My iPhone's wifi settings say that DNS is 10.0.2.1 like it is supposed to be.

I can't figure out why it is spitting out this error!

Also my dnsmasq settings has this line in it..
address=/guzzoni.apple.com/10.0.2.1

Am I doing something wrong?

**Comment by laxman01** [comment]
My terminal outputs nothing

**Comment by laxman01** [comment]
now I'm getting this 

rvmsudo siriproxy server
Starting SiriProxy on port 443..
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007f8b2301c2b8 @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007f8b2301be80>, @zip_stream=#Zlib::Deflate:0x007f8b2301bde0, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007f8b2284e068 @manager=#<SiriProxy::PluginManager:0x007f8b2301a418 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007f8b2284df00 @signature=4, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007f8b2284dd98>, @zip_stream=#Zlib::Deflate:0x007f8b2284dd70, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007f8b2284d410 @manager=#<SiriProxy::PluginManager:0x007f8b2284d988 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007f8b2284d2a8 @signature=5, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007f8b2284d140>, @zip_stream=#Zlib::Deflate:0x007f8b2284d118, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007f8b2284c790 @manager=#<SiriProxy::PluginManager:0x007f8b2284cd08 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007f8b2284c650 @signature=6, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007f8b2284c4e8>, @zip_stream=#Zlib::Deflate:0x007f8b2284c4c0, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007f8b2284a3a0 @manager=#<SiriProxy::PluginManager:0x007f8b2284c100 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007f8b2284a260 @signature=7, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007f8b2284a0f8>, @zip_stream=#Zlib::Deflate:0x007f8b2284a0d0, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007f8b228496a8 @manager=#<SiriProxy::PluginManager:0x007f8b22849cc0 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007f8b22849540 @signature=8, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007f8b228493d8>, @zip_stream=#Zlib::Deflate:0x007f8b22849388, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007f8b22848a28 @manager=#<SiriProxy::PluginManager:0x007f8b22848fa0 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007f8b228488e8 @signature=9, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007f8b22848780>, @zip_stream=#Zlib::Deflate:0x007f8b22848758, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007f8b22847d30 @manager=#<SiriProxy::PluginManager:0x007f8b22848398 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007f8b22847ba0 @signature=10, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007f8b228479c0>, @zip_stream=#Zlib::Deflate:0x007f8b22847998, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007f8b22846de0 @manager=#<SiriProxy::PluginManager:0x007f8b22847498 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007f8b22846ca0 @signature=11, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007f8b22846b10>, @zip_stream=#Zlib::Deflate:0x007f8b22846ae8, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007f8b23077c58 @manager=#<SiriProxy::PluginManager:0x007f8b2180c8d0 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007f8b23048930 @signature=12, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007f8b2301be80>, @zip_stream=#Zlib::Deflate:0x007f8b23011a48, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007f8b228842d0 @manager=#<SiriProxy::PluginManager:0x007f8b23010828 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007f8b2286f0d8 @signature=13, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007f8b2285f3b8>, @zip_stream=#Zlib::Deflate:0x007f8b2285f458, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007f8b22858d88 @manager=#<SiriProxy::PluginManager:0x007f8b2285dc98 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007f8b22859440 @signature=14, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007f8b22859d28>, @zip_stream=#Zlib::Deflate:0x007f8b22859da0, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007f8b2116e668 @manager=#<SiriProxy::PluginManager:0x007f8b2284eef0 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007f8b211626b0 @signature=15, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007f8b2115cf08>, @zip_stream=#Zlib::Deflate:0x007f8b2115dc00, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007f8b2101f7a8 @manager=#<SiriProxy::PluginManager:0x007f8b21045250 @plugins=[...]>>]
Create server for iPhone connection

**Comment by netpro2k** [comment]
The computer running siriprox should not have its dns set to your dnsmasq server, it is looping on itself. Set its DNS to something different, such as your router, isp's dns, or a public dns like google's 8.8.8.8

**Comment by laxman01** [comment]
I don't follow sorry care to go more I depth or try to use different words

**Comment by rosswaycaster** [comment]
So frustrating.

**Comment by laxman01** [comment]
Same

**Comment by rosswaycaster** [comment]
@laxman01 don't give up, I switched to a new computer and everything worked the first time. Image that! haha
P.S. Check out my first plugin! Video: http://www.youtube.com/watch?v=8Qsms2jFOdg      Source: https://github.com/rosswaycaster/SiriProxy-Facebook

**Comment by laxman01** [comment]
Thanks for the inspiration

**Comment by gotnull** [comment]
Siri opens and closes straight away for me. I think it might be a problem with dnsmasq as I can't surf the web on my iPhone if I point my DNS to my Mac IP address. Can someone confirm that you still should be able to surf the web on your iPhone even if you have the DNS of your Mac IP address?
