### ISSUE TITLE
ca.pem invalid profile

### ISSUE THREAD

**Issue by laxman01** [plamoni/SiriProxy#128]
the title says it all

**Comment by rosswaycaster** [comment]
You have to give a little more info than that.. Are you running siriproxy gencerts and the ca.pem is coming up invalid on your iPhone? If so you will have to manually make your certificate. It's easy and here is a video to do so.

http://www.youtube.com/watch?v=_oaNbPOUCaE

**Comment by laxman01** [comment]
Thanks for the help
