### ISSUE TITLE
SiriProxy Server Error

### ISSUE THREAD

**Issue by laxman01** [plamoni/SiriProxy#129]
rvmsudo siriproxy server
Starting SiriProxy on port 443..
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007f8b2301c2b8 @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007f8b2301be80>, @zip_stream=#Zlib::Deflate:0x007f8b2301bde0, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007f8b2284e068 @manager=#<SiriProxy::PluginManager:0x007f8b2301a418 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007f8b2284df00 @signature=4, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007f8b2284dd98>, @zip_stream=#Zlib::Deflate:0x007f8b2284dd70, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007f8b2284d410 @manager=#<SiriProxy::PluginManager:0x007f8b2284d988 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007f8b2284d2a8 @signature=5, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007f8b2284d140>, @zip_stream=#Zlib::Deflate:0x007f8b2284d118, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007f8b2284c790 @manager=#<SiriProxy::PluginManager:0x007f8b2284cd08 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007f8b2284c650 @signature=6, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007f8b2284c4e8>, @zip_stream=#Zlib::Deflate:0x007f8b2284c4c0, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007f8b2284a3a0 @manager=#<SiriProxy::PluginManager:0x007f8b2284c100 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007f8b2284a260 @signature=7, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007f8b2284a0f8>, @zip_stream=#Zlib::Deflate:0x007f8b2284a0d0, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007f8b228496a8 @manager=#<SiriProxy::PluginManager:0x007f8b22849cc0 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007f8b22849540 @signature=8, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007f8b228493d8>, @zip_stream=#Zlib::Deflate:0x007f8b22849388, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007f8b22848a28 @manager=#<SiriProxy::PluginManager:0x007f8b22848fa0 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007f8b228488e8 @signature=9, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007f8b22848780>, @zip_stream=#Zlib::Deflate:0x007f8b22848758, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007f8b22847d30 @manager=#<SiriProxy::PluginManager:0x007f8b22848398 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007f8b22847ba0 @signature=10, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007f8b228479c0>, @zip_stream=#Zlib::Deflate:0x007f8b22847998, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007f8b22846de0 @manager=#<SiriProxy::PluginManager:0x007f8b22847498 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007f8b22846ca0 @signature=11, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007f8b22846b10>, @zip_stream=#Zlib::Deflate:0x007f8b22846ae8, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007f8b23077c58 @manager=#<SiriProxy::PluginManager:0x007f8b2180c8d0 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007f8b23048930 @signature=12, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007f8b2301be80>, @zip_stream=#Zlib::Deflate:0x007f8b23011a48, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007f8b228842d0 @manager=#<SiriProxy::PluginManager:0x007f8b23010828 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007f8b2286f0d8 @signature=13, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007f8b2285f3b8>, @zip_stream=#Zlib::Deflate:0x007f8b2285f458, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007f8b22858d88 @manager=#<SiriProxy::PluginManager:0x007f8b2285dc98 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007f8b22859440 @signature=14, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007f8b22859d28>, @zip_stream=#Zlib::Deflate:0x007f8b22859da0, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007f8b2116e668 @manager=#<SiriProxy::PluginManager:0x007f8b2284eef0 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007f8b211626b0 @signature=15, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007f8b2115cf08>, @zip_stream=#Zlib::Deflate:0x007f8b2115dc00, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007f8b2101f7a8 @manager=#<SiriProxy::PluginManager:0x007f8b21045250 @plugins=[...]>>]
Create server for iPhone connection

**Comment by rosswaycaster** [comment]
So your terminal did start to output these errors. This is exactly what is happening to me like I described in the last thread https://github.com/plamoni/SiriProxy/issues/126

**Comment by laxman01** [comment]
Instead of putting in 10.0.2.1 try your macs internal ip address . Go to network utility then for network interface just wifi then type that ip address as DNS and in dnsmasq.conf

**Comment by rosswaycaster** [comment]
Well that is what it says my IP address is.. right?
Screenshot: http://cl.ly/2x0S3e452r0i1E0G3131

**Comment by laxman01** [comment]
Yeah your right I'm sorry I just had a problem with that so I wanted to make sure you were not making the Same
Mistake

**Comment by rosswaycaster** [comment]
Ha alright thanks for the heads up though.. Hopefully someone will know how to fix our problem

**Comment by laxman01** [comment]
Yeah it sucks cause we are soooooo close

**Comment by plamoni** [comment]
As netpro2k described in his response to issue #126, this is an issue with DNS settings, not with SiriProxy. Please only use the issues section for issues with our code, not issues with your setup.
