### ISSUE TITLE
i have errors when starting the server

### ISSUE THREAD

**Issue by DarkAleX** [plamoni/SiriProxy#13]
/Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:572:in `start_tcp_server': no acceptor (RuntimeError)
    from /Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:572:in`start_server'
    from ./siriProxy.rb:247:in `initialize'
    from /Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`call'
    from /Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
    from /Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run'
    from ./siriProxy.rb:246:in `initialize'
    from start.rb:11:in`new'
    from start.rb:11

**Comment by nuclearace** [comment]
Did you run it with sudo?

**Comment by DouweM** [comment]
Check this out: http://mrjaba.posterous.com/starttcpserver-no-acceptor-runtimeerror

**Comment by DarkAleX** [comment]
nuclearace: yes

DouweM: tried, didn't work for me :(

**Comment by DouweM** [comment]
Hmm, are you executing `start.rb` using `sudo`?

**Comment by DarkAleX** [comment]
yup

**Comment by DarkAleX** [comment]
maybe it is becouse set up DNSMASQ  with brew, and not with macport?

**Comment by szomo** [comment]
I'm getting the exact same error running "sudo ./start.rb"   everything else seems to check out ?

**Comment by szomo** [comment]
i installed mine with macports

**Comment by DouweM** [comment]
Have you guys tried this? http://blog.mattgauger.com/libraryrubygems18gemseventmachine-01210libeve

**Comment by szomo** [comment]
i run  lsof -i :4567  and nothing comes up in the list under that port.

**Comment by DouweM** [comment]
Wait, could you try `lsof -i :443`?

**Comment by DarkAleX** [comment]
it ^ didn't help me, but others can try "lsof -i :443" to see if there is something on the 443 port that running

**Comment by Intecpsp** [comment]
I had the same problem, your using ruby 1.8, update to 1.9.2 or 1.9.3

**Comment by DarkAleX** [comment]
DouweM: lol, we typed it in the same time :)

**Comment by szomo** [comment]
running  lsof -i :443

i have 4 processes running

FaceTab    193 martins    8u  IPv4 0x1b543a98      0t0  TCP 
Safari    5414 martins   13u  IPv4 0x19ed6a98      0t0  TCP 
Safari    5414 martins   24u  IPv4 0x19fc8748      0t0  TCP 
Microsoft 6915 martins   19u  IPv4 0x1a8abb98      0t0  TCP

**Comment by DarkAleX** [comment]
szomo: close these apps

**Comment by szomo** [comment]
closed them all including safari , still no dice .. 

double checked lsof on 443 to ensure it was clear ..

**Comment by DarkAleX** [comment]
fixed the last error, now i got that, lol:

start.rb:3: warning: variable $KCODE is no longer effective; ignored
/Users/Alex/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': no such file to load -- uuidtools (LoadError)
    from /Users/Alex/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from /Users/Alex/DarkAleX's Proj/Siri/SiriProxy/siriObjectGenerator.rb:2:in `<top (required)>'
    from <internal:lib/rubygems/custom_require>:29:in`require'
    from internal:lib/rubygems/custom_require:29:in `require'
    from /Users/Alex/DarkAleX's Proj/Siri/SiriProxy/plugins/testproxy/testproxy.rb:2:in`<top (required)>'
    from internal:lib/rubygems/custom_require:29:in `require'
    from <internal:lib/rubygems/custom_require>:29:in`require'
    from start.rb:5:in `<main>'

**Comment by cnaeger** [comment]
I am also getting the same error as above.

sudo ./start.rb
Password:
./start.rb:3: warning: variable $KCODE is no longer effective; ignored
/Users/chad/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- uuidtools (LoadError)
    from /Users/chad/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from /Users/chad/Downloads/plamoni-SiriProxy-bac7343/siriObjectGenerator.rb:2:in `<top (required)>'
    from /Users/chad/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from /Users/chad/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/chad/Downloads/plamoni-SiriProxy-bac7343/plugins/testproxy/testproxy.rb:2:in`<top (required)>'
    from /Users/chad/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/chad/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from ./start.rb:5:in `<main>'

**Comment by DarkAleX** [comment]
i have fixed a few errors (i think that the cause of the erros is that the new ruby version is not supporting require method)
but now i have that error: 

start.rb:4:in `<main>': undefined method`custom_require' for main:Object (NoMethodError) 

hah

**Comment by DarkAleX** [comment]
have someone an idea what should i use instead of require or custom_require?

**Comment by szomo** [comment]
I've amended mine to this and it works fine 

#!/usr/bin/env ruby
$: << File.dirname(**FILE**)

require_relative 'plugins/thermostat/siriThermostat'
require_relative 'plugins/testproxy/testproxy'

require 'tweakSiri'
require 'siriProxy'

#Also try Eliza -- though it should really not be run "before" anything else.
#Also try Twitter -- must first configure keys in siriTweet.rb
PLUGINS = [TestProxy]

proxy = SiriProxy.new(PLUGINS)

#that's it. :-)

**Comment by DarkAleX** [comment]
start.rb:2:in `<main>': uninitialized constant Object::FILE (NameError)

**Comment by MrCloud** [comment]
@DarkAleX try `__FILE__`
but it seems the last version fixes this

**Comment by DarkAleX** [comment]
gosh,
 /Users/Alex/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': no such file to load -- uuidtools (LoadError)
    from /Users/Alex/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from /Users/Alex/DarkAleX's Proj/Siri/SiriProxy/siriObjectGenerator.rb:2:in `<top (required)>'
    from <internal:lib/rubygems/custom_require>:29:in`require'
    from internal:lib/rubygems/custom_require:29:in `require'
    from /Users/Alex/DarkAleX's Proj/Siri/SiriProxy/plugins/thermostat/siriThermostat.rb:2:in`<top (required)>'
    from start.rb:4:in `require_relative'
    from start.rb:4:in`<main>'

**Comment by MrCloud** [comment]
refer to issue #11

**Comment by DarkAleX** [comment]
tried, didn't help
:(
