### ISSUE TITLE
gencerts?

### ISSUE THREAD

**Issue by ishaper** [plamoni/SiriProxy#130]
Ok the git is here! everything is a lot better now! But now I get the error when typing siriproxy gencerts

see:

apple:SiriProxy pepynhoff$ mkdir ~/.siriproxy
mkdir: /Users/pepynhoff/.siriproxy: File exists
apple:SiriProxy pepynhoff$ cp ./config.example.yml ~/.siriproxy/config.yml
apple:SiriProxy pepynhoff$ siriproxy gencerts
-bash: siriproxy: command not found

**Comment by netpro2k** [comment]
Your very first command failed, you should not continue after that. It looks like you do not have git installed.

**Comment by ishaper** [comment]
Ok the git is here! everything is a lot better now! But now I get the error when typing siriproxy gencerts 

see: 

apple:SiriProxy pepynhoff$ mkdir ~/.siriproxy
mkdir: /Users/pepynhoff/.siriproxy: File exists
apple:SiriProxy pepynhoff$ cp ./config.example.yml ~/.siriproxy/config.yml
apple:SiriProxy pepynhoff$ siriproxy gencerts 
-bash: siriproxy: command not found

**Comment by RoHS2** [comment]
I'm having the same problem. I'm using OSX, lion. What am I missing? Git is installed.
I've tried:
siriproxy gencerts
-bash: siriproxy: command not found
and tried:
~/.siriproxy gencerts
-bash: /Users/rohs/.siriproxy: is a directory

Also tried: 
~/.siriproxy/config.yml gencerts

and got
/Users/rohs/.siriproxy/config.yml: line 1: port:: command not found
/Users/rohs/.siriproxy/config.yml: line 2: log_level:: command not found
/Users/rohs/.siriproxy/config.yml: line 3: plugins:: command not found
/Users/rohs/.siriproxy/config.yml: line 6: -: command not found
/Users/rohs/.siriproxy/config.yml: line 7: path:: command not found
