### ISSUE TITLE
certificate?

### ISSUE THREAD

**Issue by ishaper** [plamoni/SiriProxy#131]
Hi guys,

I can't find my certificate to send to my iphone?

I have revealed all hidden files, but no luck! Hope you huys can help me again :P

And I got the following error:

apple:SiriProxy pepynhoff$ rvmsudo siriproxy server 
Password:

env: siriproxy: No such file or directory

apple:SiriProxy pepynhoff$ siriProxy bundle
-bash: siriProxy: command not found

apple:SiriProxy pepynhoff$ rvmsudo siriProxy server 
env: siriProxy: No such file or directory

apple:SiriProxy pepynhoff$ rvmsudo siriproxy server 
env: siriproxy: No such file or directory

Thanks!

PS: my folder is in Documents/siriproxy

**Comment by rosswaycaster** [comment]
It should be in your /.siriproxy folder either in your user folder or in Documents. Depending on where you created it. Most likely in your user's folder

**Comment by plamoni** [comment]
You seem to have having more issues than just not finding your certificate. It seems like you don't really have the background to get this up and running. This is very much an "alpha" project targeted at experienced developers. This is not an issue with the code, but an issue with your ability to follow the installation instructions. Sorry.

**Comment by ishaper** [comment]
Hi,

The old one did it just fine? 

just creating the cert is wrong:

apple:SiriProxy pepynhoff$ siriproxy gencerts
/Users/pepynhoff/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- siriproxy/command_line (LoadError)
    from /Users/pepynhoff/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from /Users/pepynhoff/.rvm/gems/ruby-1.9.3-p0/bin/siriproxy:4:in `<main>'
