### ISSUE TITLE
Is something wrong with my settings? Server won't work!

### ISSUE THREAD

**Issue by rosswaycaster** [plamoni/SiriProxy#132]
Please don't close this until this issue is resolved. This is my 3rd try at figuring this out and each time the issue is closed and I'm still having the problem.

When I try to use Siri she gives me an error about not being able to "take any request".
The terminal outputs this..

Starting SiriProxy on port 443..
Create server for iPhone connection
start conn #, @zip_stream=#Zlib::Deflate:0x007fabb120b6b0, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#>]
Create server for iPhone connection
start conn #, @zip_stream=#Zlib::Deflate:0x007fabb12c63c0, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#>]
Create server for iPhone connection
start conn #, @zip_stream=#Zlib::Deflate:0x007fabb12c43b8, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#>]
Create server for iPhone connection
start conn #, @zip_stream=#Zlib::Deflate:0x007fabb12c2568, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#>]
Create server for iPhone connection
start conn #, @zip_stream=#Zlib::Deflate:0x007fabb12bf188, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#>]

I am using my iMac as a router for my iPhone to connect to via wifi. My Mac has OpenDNS running on it and I can confirm that it works. My iPhone's wifi settings say that DNS is 10.0.2.1 like it is supposed to be.

Yeah I'm pretty sure I have done all of this correctly...

iMac Wifi Settings: http://cl.ly/423Y081N3x042N3B3o2a

Network Utility Wifi Info: http://cl.ly/3K2p2x440o1z1V3H131H

iPhone Settings: http://cl.ly/3t0l2s3E1K1f2Q1h3a45

dnsmasq.conf: http://cl.ly/2u3g0S2n0S203S1G2n2m

I can't figure out why it is spitting out this error!

Am I doing something wrong?

**Comment by netpro2k** [comment]
Sorry, trying to keep issues cleaned for actual bugs not support requests on setting up networking. 

Your settings seem correct, but it seems your proxy is still looping on itself. My guess would be that your wired connection's dns is perhaps wrong? 

Double check that everything is working correctly. Run:

```
nslookup guzzoni.apple.com
```

This should give you an Apple ip. Then run:

```
nslookup guzzoni.apple.com 127.0.0.1
```

This should give you your mac's ip.

**Comment by rosswaycaster** [comment]
@netpro2k you are right, that is what happens. @plamoni why did you close this? I think it might be a bug, because it looks like it is working DNS wise.

Ross-Waycasters-iMac-6:~ rosswaycaster$ nslookup guzzoni.apple.com
Server:     8.8.8.8
Address:    8.8.8.8#53

Non-authoritative answer:
guzzoni.apple.com   canonical name = origin.guzzoni-apple.com.akadns.net.
origin.guzzoni-apple.com.akadns.net canonical name = reg3.guzzoni-apple.com.akadns.net.
Name:   reg3.guzzoni-apple.com.akadns.net
Address: 17.174.4.14

Ross-Waycasters-iMac-6:~ rosswaycaster$ nslookup guzzoni.apple.com 127.0.0.1
Server:     127.0.0.1
Address:    127.0.0.1#53

Name:   guzzoni.apple.com
Address: 192.168.1.102

**Comment by netpro2k** [comment]
That doesnt look right, you dnsmasq config has 10.0.2.1 but it seems to be responding with 192.168.1.102 .. What machine is that?

**Comment by rosswaycaster** [comment]
Sorry that was something I was testing using my computers enthernet ip. I set the dnsmasq address back to 10.2.0.1 and it still doesn't work. But here is what terminal outputs on those test.

Ross-Waycasters-iMac-6:~ rosswaycaster$ nslookup guzzoni.apple.com
Server:     208.67.222.222
Address:    208.67.222.222#53

Non-authoritative answer:
guzzoni.apple.com   canonical name = origin.guzzoni-apple.com.akadns.net.
origin.guzzoni-apple.com.akadns.net canonical name = reg3.guzzoni-apple.com.akadns.net.
Name:   reg3.guzzoni-apple.com.akadns.net
Address: 17.174.4.14

Ross-Waycasters-iMac-6:~ rosswaycaster$ nslookup guzzoni.apple.com 127.0.0.1
Server:     127.0.0.1
Address:    127.0.0.1#53

Name:   guzzoni.apple.com
Address: 10.0.2.1

**Comment by netpro2k** [comment]
what is the dns of your wired connection set to?

**Comment by dan122334455** [comment]
I think the settings in the ipod have to be set to static.  Just try that.  Hope it helps

**Comment by rosswaycaster** [comment]
Ethernet DNS: http://cl.ly/1N0X3B3s0B2h0M19243S
  ^ It is set to OpenDNS servers that I'm guessing it is picking up from my router.

**Comment by rosswaycaster** [comment]
I removed the OpenDNS settings from my router.. now the Ethernet settings are: http://cl.ly/2n2N2S3x2V1f0Z3I2u2m

**Comment by sudoname** [comment]
i am here... everything seems right...

Abayomi:siriproxy newuser$ nslookup guzzoni.apple.com
Server:     75.75.75.75
Address:    75.75.75.75#53

Non-authoritative answer:
guzzoni.apple.com   canonical name = origin.guzzoni-apple.com.akadns.net.
origin.guzzoni-apple.com.akadns.net canonical name = reg2.guzzoni-apple.com.akadns.net.
Name:   reg2.guzzoni-apple.com.akadns.net
Address: 17.174.4.9

Abayomi:siriproxy newuser$ nslookup guzzoni.apple.com 127.0.0.1
Server:     127.0.0.1
Address:    127.0.0.1#53

Name:   guzzoni.apple.com
Address: 192.168.1.106

Abayomi:siriproxy newuser$

**Comment by JBX028** [comment]
I am here also....anybody was able to fix the issue ?

I have installed "Ping" on my iphone. I am able to ping the IP address of my server and the nslookup is similar to the one above (if we except the ip address of course). 

this is the ouput of the iphone :

PING guzzoni.apple.com (my IP address)
- Pinging host (my ip address) : icmp_seq=0
  PING guzzoni.apple.com (my IP address)
- Pinging host (my ip address) : icmp_seq=1
  No response from host

I tried to set the connection to static in the iphone but without more success

I do not know what to do next....

Thanks

**Comment by JBX028** [comment]
it's ok. I put the wrong ip address in dnsmasq.conf....
