### ISSUE TITLE
siriproxy gencerts

### ISSUE THREAD

**Issue by ishaper** [plamoni/SiriProxy#133]
I keep getting this error. when doing the siriproxy gencerts

apple:SiriProxy pepynhoff$ siriproxy gencerts
/Users/pepynhoff/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in require': cannot load such file -- siriproxy/command_line (LoadError)
from /Users/pepynhoff/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:inrequire'
from /Users/pepynhoff/.rvm/gems/ruby-1.9.3-p0/bin/siriproxy:4:in `'

**Comment by sudoname** [comment]
manually move some files around issue follow @bejaminwood at issue #98 Locations of the files are my major problem

**Comment by calvin-76** [comment]
Quand je sis les etapes pour creer un siriproxy sur:http://team-gsmcb.fr/blog/tutoriaux/lassistant-siri/siriproxy/
Error:Commande 14:siriproxy gencerts
                              commande introuvable
Aidez moi !Que faire ?
