### ISSUE TITLE
zlib(finalizer): the stream was freed prematurely.

### ISSUE THREAD

**Issue by infide** [plamoni/SiriProxy#134]
Hi 

The issue i am having is with the plex siriproxy but i hope you can still help.

When i run rvmsudo ruby ./start.rb it loads and i can use the "test siri proxy" ok but when i try and ask it to play an episode i get the following error. 

http://192.168.1.68:32400/library/sections/2/all
/Users/infide/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/open-uri.rb:346:in `open_http': 404 Not Found (OpenURI::HTTPError)
    from /Users/infide/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/open-uri.rb:775:in`buffer_open'
    from /Users/infide/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/open-uri.rb:203:in `block in open_loop'
    from /Users/infide/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/open-uri.rb:201:in`catch'
    from /Users/infide/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/open-uri.rb:201:in `open_loop'
    from /Users/infide/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/open-uri.rb:146:in`open_uri'
    from /Users/infide/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/open-uri.rb:677:in `open'
    from /Users/infide/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/open-uri.rb:33:in`open'
    from /Users/infide/siriplex/plugins/plex/plex_library.rb:18:in `xml_doc_for_path'
    from /Users/infide/siriplex/plugins/plex/plex_library.rb:23:in`all_shows'
    from /Users/infide/siriplex/plugins/plex/plex_library.rb:86:in `find_show'
    from /Users/infide/siriplex/plugins/plex/siriPlex.rb:110:in`speech_recognized'
    from /Users/infide/siriplex/tweaksiri.rb:84:in `block in speech_recognized'
    from /Users/infide/siriplex/tweaksiri.rb:83:in`each'
    from /Users/infide/siriplex/tweaksiri.rb:83:in `speech_recognized'
    from /Users/infide/siriplex/interpretSiri.rb:46:in`call'
    from /Users/infide/siriplex/interpretSiri.rb:46:in `speech_recognized'
    from /Users/infide/siriplex/siriProxy.rb:182:in`prep_received_object'
    from /Users/infide/siriplex/siriProxy.rb:102:in `process_compressed_data'
    from /Users/infide/siriplex/siriProxy.rb:72:in`receive_binary_data'
    from /Users/infide/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/em/protocols/linetext2.rb:94:in `receive_data'
    from /Users/infide/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run_machine'
    from /Users/infide/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
    from /Users/infide/siriplex/siriProxy.rb:245:in`initialize'
    from ./start.rb:17:in `new'
    from ./start.rb:17:in`<main>'
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.

Any ideas please?

**Comment by netpro2k** [comment]
For starters it looks like you are using an old version of siriproxy, so update to latest code and follow new setup instructions. After that, it seems like you have your plex server's ip set incorrectly, this is unrelated to SiriProxy and should be discussed with the plugin author (or better yet solved on your own) https://github.com/hjaltij/SiriProxy-Plex

**Comment by flash66** [comment]
See: https://github.com/hjaltij/SiriProxy-Plex/issues/4

This will correct it
