### ISSUE TITLE
rvm install 1.9.3 .... error

### ISSUE THREAD

**Issue by sudoname** [plamoni/SiriProxy#138]
anyone having this problem too?

Abayomi:~ newuser$ rvm install 1.9.3
Installing Ruby from source to: /Users/newuser/.rvm/rubies/ruby-1.9.3-p0, this may take a while depending on your cpu(s)...

ruby-1.9.3-p0 - #fetching 
ruby-1.9.3-p0 - #extracted to /Users/newuser/.rvm/src/ruby-1.9.3-p0 (already extracted)
Fetching yaml-0.1.4.tar.gz to /Users/newuser/.rvm/archives
Extracting yaml-0.1.4.tar.gz to /Users/newuser/.rvm/src
Configuring yaml in /Users/newuser/.rvm/src/yaml-0.1.4.
Compiling yaml in /Users/newuser/.rvm/src/yaml-0.1.4.
Installing yaml to /Users/newuser/.rvm/usr
ruby-1.9.3-p0 - #configuring 
ERROR: Error running ' ./configure --prefix=/Users/newuser/.rvm/rubies/ruby-1.9.3-p0 --enable-shared --disable-install-doc --with-libyaml-dir=/Users/newuser/.rvm/usr ', please read /Users/newuser/.rvm/log/ruby-1.9.3-p0/configure.log
ERROR: There has been an error while running configure. Halting the installation.

any help will be much appreciated

**Comment by elpeq** [comment]
Hi everybody, 

I have this very same problem :-( Help would be appreciated.

Thanks

**Comment by elpeq** [comment]
Sorry I forgot, I am under os x lion.

**Comment by dcinzona** [comment]
What does it say in the log?  I also had a ton of problems with RVM and Lion... but was eventually able to get it going. (I ended up having a hybrid setup on my *nix box) and can explain if it becomes relevant.

**Comment by elpeq** [comment]
In the logs it says something like that the C compiler can't be found. What's realy strange is that rvm install 1.9.2 works.
I have installed Xcode, so the C compilers are installed.
I don't know if siriProxy can work with 1.9.2

**Comment by dcinzona** [comment]
it works with 1.9.2 - BUT I was also not able to get RVM going on Lion.  I have xcode 4.2.
The problem is that xcode uses LLVM GCC and not (standard? I forget the term) GCC.

So even if you have GCC installed, it's LLVM and that doesn't work

***_EDIT**_*
it SHOULD work with 1.9.2 - but I'm not sure... when you try to build it, it will error out if it has issues with your Ruby version

**Comment by elpeq** [comment]
You say because of this LLVM it's impossible to install 1.9.3 on Lion ?

I'll give an other try this evening and if it doesn't work, I'll try to make siriProxy run with 1.9.2

**Comment by dcinzona** [comment]
the c compilers wont work with LLVM GCC - that's all I'm saying ;)

If you get it to finally compile, post back here how you did it.  It would be a great resource.

**Comment by elpeq** [comment]
Do you know why we don't have the same problem with 1.9.2 ?

**Comment by dcinzona** [comment]
I actually did have the same problem with 1.9.2 - Still running 1.8.7 on my mac :-(

(I may not be the best source for information regarding this... just giving you my personal experience)

In fact, I've tried several things to get it to compile and ended up just using a Synology Nas to compile and run the proxy server.  Works fine in linux.  May I suggest trying to use VirtualBox and Ubuntu (latest) as referenced in the video?

---

Also, just wanted to mention that I didn't really try too hard to get it to compile on my mac mostly because my end goal was to get it running on my Synology NAS.  I have it running there (manually) but am now working on getting it going as a background service

**Comment by elpeq** [comment]
I'll try a little more on Lion and if I don't manage it to work, I'll do the solution you suggest with Ubuntu.

Anyway, thanks a lot for your help.

**Comment by dcinzona** [comment]
No problem, good luck

**Comment by rckcrlr** [comment]
I had the same issue with Lion and resorted to installing gcc 4.2 from macports.  That fixed it for me.

**Comment by dcinzona** [comment]
Did that break xCode compiling?

**Comment by rckcrlr** [comment]
Sorry, couldn't tell you I haven't compiled anything in Xcode since downloading it.

**Comment by rckcrlr** [comment]
Could always move the link back after done.  Not elegant but should get the job done.

**Comment by dcinzona** [comment]
I'm installing it now and will see how it goes... GCC takes a hell of long time to compile...

**Comment by sudoname** [comment]
whats the deal?

Abayomi:siriproxy newuser$ rvmsudo siriproxy server
Starting SiriProxy on port 443..
^C/Users/newuser/.rvm/gems/ruby-1.9.2-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine': Interrupt
    from /Users/newuser/.rvm/gems/ruby-1.9.2-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run'
    from /Users/newuser/.rvm/gems/ruby-1.9.2-p0/gems/siriproxy-0.0.1/lib/siriproxy.rb:16:in `initialize'
    from /Users/newuser/.rvm/gems/ruby-1.9.2-p0/gems/siriproxy-0.0.1/lib/siriproxy/command_line.rb:96:in`new'
    from /Users/newuser/.rvm/gems/ruby-1.9.2-p0/gems/siriproxy-0.0.1/lib/siriproxy/command_line.rb:96:in `start_server'
    from /Users/newuser/.rvm/gems/ruby-1.9.2-p0/gems/siriproxy-0.0.1/lib/siriproxy/command_line.rb:85:in`run_server'
    from /Users/newuser/.rvm/gems/ruby-1.9.2-p0/gems/siriproxy-0.0.1/lib/siriproxy/command_line.rb:37:in `initialize'
    from /Users/newuser/.rvm/gems/ruby-1.9.2-p0/bin/siriproxy:6:in`new'
    from /Users/newuser/.rvm/gems/ruby-1.9.2-p0/bin/siriproxy:6:in `<main>'
Abayomi:siriproxy newuser$ rvmsudo siriproxy server
Password:
Starting SiriProxy on port 443..
^C/Users/newuser/.rvm/gems/ruby-1.9.2-p0/bin/siriproxy: Interrupt
Abayomi:siriproxy newuser$

**Comment by dcinzona** [comment]
by the way, i was able to install ruby 1.9.3 using 
rvm install 1.9.3 --with-gcc=clang

Found here: http://stackoverflow.com/questions/8259928/error-compiling-ruby-1-9-3-using-rvm-homebrew-or-macports

**Comment by dcinzona** [comment]
As for the error listed below, that error pops up for me too when I stop running the server using CTRL+c

**Comment by elpeq** [comment]
I also used the command rvm install 1.9.3 --with-gcc=clang like dcinzona, and it worked for me too !

But the I had other errors and gave up on Lion. I have installed everything in Ubuntu now, and had no major problems.

**Comment by sudoname** [comment]
use "rvm install 1.9.3 --with-gcc=clang" it seem to work everytime
