### ISSUE TITLE
Multiple SiriProxy Servers

### ISSUE THREAD

**Issue by ahajjar** [plamoni/SiriProxy#139]
Any idea if this is possible?

I'm currently running it on a FreeBSD server to be able to access it 24/7 through a VPN connection.  Though, I'm interested in running it on my mac for control of iTunes, apps, etc..  

Would it be feasible to have the initial request be handled by the first proxy (running on BSD) and if it can't handle it pass it on to the mac running SiriProxy, or if the mac is not available finally forward it onto apple's servers?

Just a thought and was thinking this would be interesting since I know not everyone is running it directly on their mac or pc.

**Comment by dcinzona** [comment]
you would need 2 DNS servers.  the first one points it to your first proxy server.  That server then is setup to look at your second DNS server, which points guzzoni.apple.com to your second proxy server.  Then that one points to your router and out.
At least, that's how it should work in my head... not sure if that's how it will actually work or how it is expected to process the response.  It also might slow down a bit.

**Comment by plamoni** [comment]
I recommend determining a way to securely, remotely control itunes. SSH would be my suggestion. Use public key authentication or host key authentication to make the connection secure and simple.

Sorry, but this isn't really an issue, so I'm closing it.
