### ISSUE TITLE
Eventmachine error!

### ISSUE THREAD

**Issue by WhizZz** [plamoni/SiriProxy#14]
Okey i install Ruby and follow all the tutorials and now then i had this:

---

Michiel-en-Maartens-iMac:Siriproxy michielenmaarten$ sudo ruby start.rb
/Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require': no such file to load -- twitter (LoadError)
from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`require'
from ./plugins/twitter/siriTweet.rb:4
from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`require'
from start.rb:5
## After removing the Twitter require i had this:

/Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:572:in `start_tcp_server': no acceptor (RuntimeError)
from /Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:572:in`start_server'
from ./siriProxy.rb:247:in `initialize'
from /Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`call'
from /Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
from /Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run'
from ./siriProxy.rb:246:in `initialize'
from start.rb:12:in`new'
## from start.rb:12

Mayby problem while installing so i reinstall it:

---

Michiel-en-Maartens-iMac:Siriproxy michielenmaarten$ sudo gem install /usr/local/src/eventmachine-0.12.10
Building native extensions. This could take a while...
Successfully installed eventmachine-0.12.10
1 gem installed
Installing ri documentation for eventmachine-0.12.10...
Installing RDoc documentation for eventmachine-0.12.10...
Could not find main page README
Could not find main page README
Could not find main page README
## Could not find main page README

restart:

---

Michiel-en-Maartens-iMac:Siriproxy michielenmaarten$ sudo ruby start.rb
/Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:572:in `start_tcp_server': no acceptor (RuntimeError)
from /Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:572:in`start_server'
from ./siriProxy.rb:247:in `initialize'
from /Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`call'
from /Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
from /Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run'
from ./siriProxy.rb:246:in `initialize'
from start.rb:12:in`new'
from start.rb:12
## Michiel-en-Maartens-iMac:Siriproxy michielenmaarten$

still the same problem =S
Do i need another eventmachine? Tis is the only version i see.
Mayby its my mac?
I have Snow Leopard 10.6.8

King regards,
WhizZz

**Comment by DouweM** [comment]
See the other two issues, both of your problems have been posted already.

**Comment by WhizZz** [comment]
okey i fixed the error!
Just reboot your mac and startup siriproxy =)
