### ISSUE TITLE
The server starts but it gets nothing

### ISSUE THREAD

**Issue by clankiPad** [plamoni/SiriProxy#141]
The server starts but it gets nothing when I do "rvmsudo siriproxy server" , I have "Starting SiriProxy on port 443.." While I was talking Siri ! HELP ME Please :)

PS: I'm French :S

**Comment by sudoname** [comment]
i had the same problem, then i closed the terminal and i redo it...i got this error

Abayomi:siriproxy newuser$ rvmsudo bin/siriproxy server
Starting SiriProxy on port 443..
/Users/newuser/siriproxy/lib/siriproxy.rb:26:in `rescue in block in initialize': Cannot start the server on port 443 - are you root, or have another process on this port already? (RuntimeError)
    from /Users/newuser/siriproxy/lib/siriproxy.rb:17:in`block in initialize'
    from /Users/newuser/.rvm/gems/ruby-1.9.2-p290/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `call'
    from /Users/newuser/.rvm/gems/ruby-1.9.2-p290/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run_machine'
    from /Users/newuser/.rvm/gems/ruby-1.9.2-p290/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
    from /Users/newuser/siriproxy/lib/siriproxy.rb:16:in`initialize'
    from /Users/newuser/siriproxy/lib/siriproxy/command_line.rb:96:in `new'
    from /Users/newuser/siriproxy/lib/siriproxy/command_line.rb:96:in`start_server'
    from /Users/newuser/siriproxy/lib/siriproxy/command_line.rb:85:in `run_server'
    from /Users/newuser/siriproxy/lib/siriproxy/command_line.rb:37:in`initialize'
    from bin/siriproxy:6:in `new'
    from bin/siriproxy:6:in`<main>'

**Comment by dcinzona** [comment]
read the readme.  You have something else running on port 443

**Comment by sudoname** [comment]
now, i killedall but it stays on "Starting SiriProxy on port 443.."for ever!

Abayomi:siriproxy newuser$ sudo lsof -i :443 | grep LISTEN
ruby      24064    root    5u  IPv4 0xffffff80158204e0      0t0  TCP *:https (LISTEN)
Abayomi:siriproxy newuser$ sudo kill -9 PID-443
kill: illegal process id: PID-443
Abayomi:siriproxy newuser$ sudo lsof -i:443
COMMAND     PID    USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
applepush    75    root   12u  IPv4 0xffffff8013fb1500      0t0  TCP 192.168.1.105:50676->nk11p01st-courier140-bz.push.apple.com:https (ESTABLISHED)
ubd         160 newuser   30u  IPv4 0xffffff800bed24e0      0t0  TCP 192.168.1.105:50252->a184-28-220-224.deploy.akamaitechnologies.com:https (CLOSED)
ruby      24064    root    5u  IPv4 0xffffff80158204e0      0t0  TCP *:https (LISTEN)
Abayomi:siriproxy newuser$ 
Last login: Mon Dec  5 07:12:06 on console
Abayomi:siriproxy newuser$ sudo killall named
Password:
No matching processes were found
Abayomi:siriproxy newuser$ sudo lsof -i :443 | grep LISTEN
Abayomi:siriproxy newuser$ sudo kill -9 PID-443
kill: illegal process id: PID-443
Abayomi:siriproxy newuser$ sudo lsof -i :443 | grep LISTEN
Abayomi:siriproxy newuser$ rvmsudo bin/siriproxy server
Starting SiriProxy on port 443..

**Comment by dcinzona** [comment]
that means it's running.  

Watch the you tube video - http://www.youtube.com/watch?v=GQXyJR6mOk0

Skip to the end.

**Comment by sudoname** [comment]
no its been like that for ever.

Abayomi:ca newuser$  sudo lsof -i :443 | grep LISTEN
Abayomi:ca newuser$ sudo lsof -i :443 | grep LISTEN
Abayomi:ca newuser$ cd /users/newuser
Abayomi:newuser newuser$ cd siriproxy
Abayomi:siriproxy newuser$  sudo lsof -i :443 | grep LISTEN
Abayomi:siriproxy newuser$ rvmsudo siriproxy server
Starting SiriProxy on port 443..

**Comment by dcinzona** [comment]
again, that means it's running.  it will be like that forever - as long as it's running.  That message is how you KNOW the server is running

**Comment by sudoname** [comment]
So what do I do from here?
Just wait 3 days? Did you use you computer ip as the phone DNs?

**Comment by dcinzona** [comment]
this is my setup (and I can verify that it works)... otherwise I wouldnt be trying to give advice.

Synology NAS running BusyBox linux, dnsmasq, siriproxy (and all dependancies) I will refer to my Synology NAS from now on as NAS.  (this is where SiriProxy runs).

I have my DHCP server set up using dnsmasq on my NAS.  This way, all devices on my home network (including those that VPN in) get the correct DNS server information and route through my NAS and dnsmasq.

When I have SiriProxy running in shell (I know it's running because of the message Starting SiriProxy on port 443..) and my device is on the home network or VPNed in, I am able to access SiriProxy.

You may want to try using an app on your iPhone to ping guzzoni.apple.com to make sure it's resolving to your internal server instead of apple's servers.  I use Scanny for iPhone

**Comment by sudoname** [comment]
So what do I do from here? Siri doesn't respond to command or is there any other way to see the. Commands on the screen?

Sorry for All the questions, I just want this to work

Thanks

**Comment by dcinzona** [comment]
Did you read my entire previous comment?  read the last sentence...

**Comment by plamoni** [comment]
dcinzona has explained this quite thoroughly enough.

**Comment by sudoname** [comment]
thanks @plamoni and @dcinzona... :)
