### ISSUE TITLE
rake install error

### ISSUE THREAD

**Issue by marktkram** [plamoni/SiriProxy#145]
pascal@test:~$ cd SiriProxy
pascal@test:~/SiriProxy$ rake install
rake aborted!
cannot load such file -- bundler/gem_tasks

(See full trace by running task with --trace)

What i've done wrong ? what i've to do better?

**Comment by slarti42uk** [comment]
Hey,

I'm getting the same thing. Followed the video through. Realised that I had only copied part of the apt-get line from the Gist. Having rectified that however the problem remains.

Will try a full fresh install...

**Comment by slarti42uk** [comment]
Ok, think I got past this. I was due to my failiure to copy/paste the entire apt-get line in my excitment! have fixed it by doing the following:

rvm pkg install zlib
rvm remove 1.9.3
rvm install 1.9.3
rvm use 1.9.3 --default #just for good measure!

Then rake install worked fine

**Comment by marktkram** [comment]
solve the issue thanks
