### ISSUE TITLE
restarting siriproxy

### ISSUE THREAD

**Issue by 7imbrook** [plamoni/SiriProxy#146]
What would be a simple way to restart the siriproxy server using siri, I want to start running this on a remote machine and cant easily restart siri proxy after updating a pluggin. Thanks

**Comment by dcinzona** [comment]
if you can update the plugin remotely, you should be able to restart siri remotely as well (SSH)
sudo killall siriproxy
sudo siriproxy server

**Comment by plamoni** [comment]
I like this idea. Leaving it open to implementation.

**Comment by rckcrlr** [comment]
I'm working on a restart update for siriproxy-appcontroller.  If we can get siriproxy under launchd control it should work.
https://github.com/rckcrlr/SiriProxy-AppController

Setting up this way would require a sudo "NOPASSWD" config for the user starting siriproxy, unless of course, you are running it as root.

**Comment by Ponyboy47** [comment]
I put in a pull request for an auto restarting code..it restarts SiriProxy after a crash of some sort..but it doesnt update siriproxy before restarting it..I could see if I can add this..so you could in theory just crash your proxy and then it would auto update and restart

**Comment by Ponyboy47** [comment]
There..I just redid my pull request.
Now you can auto restart, auto update and restart, or auto bundle and restart your proxy after it crashes

**Comment by Ponyboy47** [comment]
I just wrote a quick plugin to crash siriproxy...so that now if you update your plugin on github then say "Crash my proxy" or crash siri proxy" then your proxy will crash. And then if ur running your proxy with my auto restarting files your proxy will auto update/bundle and restart with your newly updated plugin
Here's the link to my plugin: https://github.com/Ponyboy47/siriproxy-crasher

**Comment by elvisimprsntr** [comment]
SiriProxy 0.5.0+ and Ruby 2.0.0 is more tolerant to crashing plugins, thus a restarter seems less necessary.  Closing due to age and inactivity.
