### ISSUE TITLE
Can't execute start.rb

### ISSUE THREAD

**Issue by pwax** [plamoni/SiriProxy#148]
I have everything installed and working and what not but I can't get start.rb to execute! I have no idea what the problem is but here's what shows up in terminal: 

/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- bundler (LoadError)
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from start.rb:6

this comes right after I type: sudo ruby start.rb

**Comment by dcinzona** [comment]
update to the latest version.  You should not be running start.rb anymore

**Comment by plamoni** [comment]
This is an issue with not following directions. Not an issue with the code.
