### ISSUE TITLE
I Get lost after step 3 how do you get everything to work

### ISSUE THREAD

**Issue by mdhetsko** [plamoni/SiriProxy#15]
This is very frustrating because I cannot fiure out what to do after step 3 please somebody put a walkthrough of it up please.

**Comment by plamoni** [comment]
Go on to step 4?

Which walkthrough are you following? 

I should note. This project is NOT user-friendly. It's still in its very early stages and doesn't have any real documentation or anything. It's really just a preview for use by developers who know what they're doing.

**Comment by mdhetsko** [comment]
Ok thank you I will drop it until it is more user friendly then
