### ISSUE TITLE
version of dnsmasq

### ISSUE THREAD

**Issue by JBX028** [plamoni/SiriProxy#151]
Hello,

I have a question about which version of dnsmasq is used in the very usefull video posted yesterday, on how to install siriproxy on ubuntu 11.10

I have installed virtualbox and run a fresh install of ubuntu 11.10 and was able to install everything
siriproxy is running and the certificat is sent to my iPhone.

I have a question about dnsmasq. In your video i can see that you run the following command to restart dnsmasq:

sudo /etc/init.d/sudo dnsmasq restart

With my fresh install, "restart" is not recognised and "restart" is nowhere in the man page of dnsmasq. 

When i run "sudo dnsmasq" there is no error message and looks like dnsmasq is running because if i try to run a new instance i have a message saying that the port is already used. I can also kill the process with "sudo killall dnsmasq".

Even if dnsmasq "looks" running i would like to understand why it's different on my computer. Initially version 2.57 was installed and i have upgraded the tool to 2.59 which is the last debian package available. I do not understand how dnsmasq can be different because we proceed exactly the same way. The only difference i can see is that i have choosen "French" to setup Ubuntu but for me this is not the root cause.

I am saying that because even if /etc/dnsmasq.conf is properly configured and even if i have put the ip address as a DNS in my iphone 4S, siriproxy do not capture anything and when i try to go to internet on my iphone, it's not possible anymore as soon as i have set the dns. I am wondering if dnsmasq works diffently depending on the version (of course i can ping from an other computer the ip adress of the virtualbox).

thanks for your help.

Johnny Baillargeaux (from France)

**Comment by dcinzona** [comment]
I have dnsmasq also running as my home network DHCP server.  This allows me to set the DNS server to any clients (including my iPhone).  Can you verify that guzzoni.apple.com resolves to your proxy server's IP?  You can use a program like scanny (from the app store) to do this.  I am not affiliated with the developer in any way, btw, it just happens to be the program I use.  Any "Ping" program will work though.

IF the DNS on the phone is pointing to the IP address of the ubuntu install (the proxy server), make sure you can hit it from the phone (scanny or pinging will work).

**Comment by plamoni** [comment]
The command is "sudo /etc/init.d/dnsmasq restart"

Please reserve the issues page for issues with the software, and not issues with your setup. Ask about that kind of thing in the chat room.

**Comment by plamoni** [comment]
https://gist.github.com/1428474#L20

**Comment by JBX028** [comment]
Like i said, "sudo /etc/init.d/dnsmasq restart" is not recognised and parameter "restart" is not in the man page. I just wanted to know the version of dnsmask installed in the video.
