### ISSUE TITLE
Create server for iPhone connection

### ISSUE THREAD

**Issue by FernandoGStocco** [plamoni/SiriProxy#153]
whenever I activate rvmsudo siriproxy server i get this (just want to enforce the fact that my mac's dns is NOT the one I'm pointing my iPhone to and i have iPhone correctly pointed to Mac's internal IP. screenshots: http://twitpic.com/7paouy http://twitpic.com/7paooj and http://twitpic.com/7paoj7):

mac-mini-de-paulo-neto:siriproxy Fernando.$ rvmsudo siriproxy server
Password:
Starting SiriProxy on port 443..
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007fea9227d5b0 @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007fea9227d330>, @zip_stream=#Zlib::Deflate:0x007fea9227d308, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007fea91842000 @manager=#<SiriProxy::PluginManager:0x007fea9227ccc8 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007fea91841cb8 @signature=4, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007fea918418d0>, @zip_stream=#Zlib::Deflate:0x007fea91841830, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007fea9183f530 @manager=#<SiriProxy::PluginManager:0x007fea918406d8 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007fea9183edd8 @signature=5, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007fea9183e950>, @zip_stream=#Zlib::Deflate:0x007fea9183e900, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007fea9183c948 @manager=#<SiriProxy::PluginManager:0x007fea9183dd70 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007fea9183c308 @signature=6, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007fea9183c0d8>, @zip_stream=#Zlib::Deflate:0x007fea9183c088, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007fea918399f0 @manager=#<SiriProxy::PluginManager:0x007fea9183ab70 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007fea91839248 @signature=7, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007fea91838e88>, @zip_stream=#Zlib::Deflate:0x007fea91838e60, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007fea91836b60 @manager=#<SiriProxy::PluginManager:0x007fea91837e48 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007fea91836750 @signature=8, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007fea91835e90>, @zip_stream=#Zlib::Deflate:0x007fea91835d78, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007fea91833fa0 @manager=#<SiriProxy::PluginManager:0x007fea91834ef0 @plugins=[...]>>]

**Comment by Enophi** [comment]
Exactly the same issue...

**Comment by dcinzona** [comment]
Your mac resolves guzzoni.apple.com correctly or no?
Your phone should resolve to your mac, and I think your mac needs to resolve to the real server.
Can you ping guzzoni.apple.com on both devices (and let me know what the IP's are)?

**Comment by ianb821** [comment]
Same here, any help would be great.
I can have it running perfectly using the old method which uses start.rb to start up the proxy server, but when tried to do it the new way shown in the tutorial I get that error.  I just tried reverting back to the old way and it works like a charm every time, so I'm not sure what the difference would be.

**Comment by plamoni** [comment]
We see similar output from certificate errors. If you're 100% sure your DNS is set up properly, then make sure your certificates are properly generated and the ca.pem is installed on your iPhone.

**Comment by FernandoGStocco** [comment]
As soon as I'm home I'll try pinging guzzoni.
About ca.pem, I installed on my phone the certificate created with "My Fake CA" method because there was no clear answer as to why ca.pem would be empty when generated by siriproxy gencerts.

**Comment by ianb821** [comment]
I had a similar error. When I used the SiriProxy gencerts method and sent the ca.pem to my phone as I had done before, I got an error "This profile contains no information" or something to that effect. When I checked the file, it's size was 0 bytes, so I retried with the same result. I tried using the old way of creating the 'My Fake Ca' and replacing it with the empty file, but I'm still getting the same results.

**Comment by ianb821** [comment]
I just got home and started from scratch again.  when I generated the certs, the ca.pem file was still 0 bytes, so I just went through the old method and replaced all the files in the ./siriproxy/ folder and it works fine, still not sure what was going on with the gencerts command, but it's up and running!

**Comment by sudoname** [comment]
i got this far on my mac air and i am thinking about going Ubuntu but i wanna give the certs one more try... ca.pem is 0 byte will my fake ca is 4KB. does anyone know why?
BTW my server is set up correctly, i can ping guzzoni.apple.com from both my devices and it even gives my MACs IP when i put nslookup guzzoni.apple.com 127.0.0.1 from my computer. i have narrowed it down to my certs.... so any one know what to do from here?

thanks

**Comment by muhkuh0815** [comment]
i copied the certs from ubunto to my mac, works fine

**Comment by dcinzona** [comment]
You are using the wrong version of openssl

**Comment by FernandoGStocco** [comment]
My Mac does not not resolve guzzoni.apple.com correctly. 100% packet loss

**Comment by dcinzona** [comment]
Theres your problem

**Comment by sudoname** [comment]
check your dnsmasq.conf  and make sure /address=guzzoni.apple.com/"IP" is the same as your computer IP address. if you cant "talk" to guzzoni, then this wont work. good luck

**Comment by plamoni** [comment]
sudoname: `nslookup guzzoni.apple.com 127.0.0.1` on your Mac should return the REAL address for guzzoni, not the fake one. If it returns the fake one, you'll get a loop as described above.

**Comment by sudoname** [comment]
thanks @plamoni , its been working for a long time now... my new problem is the creation of the *.rb files in the plugins. i can't get the plugins i created to work cos i can't figure out how to generate the executable files. thanks pete

**Comment by dcinzona** [comment]
where does it fail?  running siriproxy bundle will gemify the plugins.

**Comment by sudoname** [comment]
i just wrote this (to show the error i am getting) i have not looked for coding error i, i just want it to run so i can debug it. 

oh and "siriproxy-wayne" is a folder in that exact location.... Thanks

Abayomi:bin newuser$ rvm use 1.9.3-p0 --default
Using /Users/newuser/.rvm/gems/ruby-1.9.3-p0
Abayomi:bin newuser$ ./siriproxy bundle
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Fetching source index for http://rubygems.org/
Could not find gem 'siriproxy-wayne (>= 0) ruby' in source at /Users/newuser/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.3.0/plugins/Siriproxy-wayne.
Source does not contain any versions of 'siriproxy-wayne (>= 0) ruby'
Abayomi:bin newuser$

**Comment by dcinzona** [comment]
Can you share the source for the plugin or no? Specifically the gemspec 
and the config.yml

**Comment by sudoname** [comment]
this is the one i just wrote to illustrate the point 
here is the config.yml component
- name: 'Wayne'
  path: '/Users/newuser/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.3.0/plugins/Siriproxy-wayne'

gemspec
$:.push File.expand_path("../lib", **FILE**)

Gem::Specification.new do |s|
  s.name        = "siriproxy-Wayne"
  s.version     = "1.0" 
  s.author      = ["sudoname"]
  s.email       = [""]
  s.homepage    = ""
  s.summary     = %q{to hear siri talk}
  s.description = %q{siri talks! }

  s.rubyforge_project = "siriproxy-Wayne"

  s.files         = `git ls-files`.split("\n")
  s.test_files    = `git ls-files -- {test,spec,features}/*`.split("\n")
  s.executables   = `git ls-files -- bin/*`.split("\n").map{ |f| File.basename(f) }
  s.require_paths = ["lib"]

**Comment by dcinzona** [comment]
This may not be your issue, but I found that replacing:

s.files = `git ls-files`.split("\n")
s.test_files = `git ls-files -- {test,spec,features}/*`.split("\n")
s.executables = `git ls-files -- bin/*`.split("\n").map{ |f| 
File.basename(f) }
s.require_paths = ["lib"]

with:

   s.files         = `git ls-files 2> /dev/null`.split("\n")
   s.test_files    = `git ls-files -- {test,spec,features}/* 2> 
/dev/null`.split("\n")
   s.executables   = `git ls-files -- bin/* 2> 
/dev/null`.split("\n").map{ |f| File.basename(f) }
   s.require_paths = ["lib"]

allowed me to build the plugin successfully. (note the 
2>/dev/null`.split("\n")

**Comment by dcinzona** [comment]
I dont know why it decided to wrap the code...

Replace:
<code>
s.files = `git ls-files`.split("\n")
s.test_files = `git ls-files -- {test,spec,features}/*`.split("\n")
s.executables = `git ls-files -- bin/*`.split("\n").map{ |f| File.basename(f) }
s.require_paths = ["lib"] 
</code>
with:
<code>
  s.files         = `git ls-files 2> /dev/null`.split("\n")
  s.test_files    = `git ls-files -- {test,spec,features}/* 2> /dev/null`.split("\n")
  s.executables   = `git ls-files -- bin/* 2> /dev/null`.split("\n").map{ |f| File.basename(f) }
  s.require_paths = ["lib"]
</code>

**Comment by sudoname** [comment]
thanks i got that lol...
can you explain this line? 
class SiriProxy::Plugin::Wayne < SiriProxy::Plugin

thanks

**Comment by dcinzona** [comment]
I'm not a big Ruby coder but I'm going to assume that is classifying the script as s SiriProxy plugin.

I defer to those ruby devs out there.

Did the bundle work after that change?

**Comment by sudoname** [comment]
No it didn't but thanks

**Comment by dcinzona** [comment]
hmm... crappy.  Sorry man, I'd have to look at your setup to be able to troubleshoot better...
The plugin setup right now is kind of a PITA to figure out, huge learning curve, but once you get it figured out for your configuration, it's not so bad.

**Comment by pengas** [comment]
hey guys,

i'm running siri against siriproxy on a mac book air.

from my mac i can telenet to guzzoni over port 443 fine. i modified the hosts file on the iphone to route to my mac and portscan and safari both show that it works okay.

however, when i launch siri - no data is passed and siri apologizes for having trouble connecting to the network.

next step is to try this with an iphone 4s and if that doesn't work - sniff packets in the network to see what's going on...

any thoughts would be great.

cheers.

**Comment by FernandoGStocco** [comment]
@pengas have you modified com.apple.assistant.plist to talk to guzzoni.apple.com instead of cd-team's servers?

**Comment by pengas** [comment]
@FernandoGStocco no i did not. before your comment i had realized i need to add siri.cd-team.org to my /etc/hosts on the device. once i did that the server responded, though i get out the debug message:

Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007fab540a2510 @signature=13, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007fab540a2088>, @zip_stream=#Zlib::Deflate:0x007fab540a2038, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007fab5409fcc0 @manager=#<SiriProxy::PluginManager:0x007fab540a0ee0 @plugins=[...]>>]

i did reach out to /private/var/mobile/Library/Preferences/com.apple.assistant.plist and updated the hostname field.

now after reboot of both device and server siri just hangs forever and the server is not getting any requests...

when running a network utility from the device against both siri.cd-team.org and guzzoni.apple.com the siriproxy server responds...

thoughts?
