### ISSUE TITLE
Siri & Ruby

### ISSUE THREAD

**Issue by ihardyslide** [plamoni/SiriProxy#154]
Everytime I insert the Ruby command "sleep" in my plugin, Siri just 'spins' and does nothing, but in the terminal I see that it works. So my question, does Siri not fit with "sleep(seconds)"?

**Comment by mrmosconi** [comment]
Are you specifying a value? "sleep" with no parameters sleeps forever. I'm using sleep in a plugin with no problems.

**Comment by ihardyslide** [comment]
yea, i use sleep(10), for 10 seconds

**Comment by mrmosconi** [comment]
I would try "sleep 0.1" as a test. As I said, I use "sleep" in my plugin without issue.

**Comment by plamoni** [comment]
Make sure you're not sleeping your primary thread. If you want to do something after a delay, then spawn a new thread and sleep that one for a bit. We should probably spawn each listen_for into its own thread anyway, but that's probably a bit down the line.

Anyway, this seems like a ruby issue, not a SiriProxy issue.
