### ISSUE TITLE
SiriProxy Not Starting

### ISSUE THREAD

**Issue by nathreed** [plamoni/SiriProxy#155]
When i invoke rvmsudo siriproxy server, it asks for my password and then says: "Starting Siri Proxy on port 443".  It then does nothing else. I have tried this on all my machines and also on two VirtualBox machines. They were all running Ubuntu 11.10. I have spent about 10 hrs total for this since Sunday and it STILL WONT WORK. The only difference from the instructional video was that I did not install all the available updates. Will this install on plain OSX?? I tried sudo apt-get .... and it spit back: "sudo: Apt-get: command not found." Any help on either front would be greatly appreciated.

**Comment by plamoni** [comment]
If you don't know what "apt-get" is then this project might be a bit beyond your technical skill level. 

Either way, your issue is related to DNS setup. It's not a problem with the SiriProxy code, so I'm closing this issue.
