### ISSUE TITLE
Siri won't work and terminal stays at "starting SiriProxy on port 443"

### ISSUE THREAD

**Issue by dan122334455** [plamoni/SiriProxy#157]
I am very excited that I got up to this far.  I followed ever instruction exactly.  And it wont work.  I am using ubuntu to run this.  I went to properties, settings, (in the virutalcomputer) and i found that my ip address is 10.0.2.15.  It also says my dns is 192.168.1.1 .  On my iphone (4s) the wifi setting is the same as when i first signed in to it, but i just added 10.0.2.15 as the dns.  Also, on the dnsmasq.conf , i added the proper item with /10.0.2.15.  When i try to ask siri something, she say's its not connected to the internet.  Can you please help me?? i tried everyting and nothing will work. Thanks so much!

**Comment by hirakujira** [comment]
Same here.
Just shows "Starting SiriProxy on port 443.."
But cannot make iPhone connect to the proxy.

**Comment by dan122334455** [comment]
I worked so hard on getting this to work.  When i saw the starting siriproxy, my eyes opened wide with excitement.  then when nothing happend, i got so angry. lol. I spent at least 10 hours trying to figure out how to get this to work.  It took me about 30 min to install it with the virtual box.  Hopefully they fix this!  If someone knows what to do, please help!!! Thanks

**Comment by sudoname** [comment]
i had this problem too.... what version of openSSL are you using?

**Comment by nathreed** [comment]
same here--any help??
openssl version 1.0.0e-6 Sept 2011

**Comment by sudoname** [comment]
check you certs..... carets.pem is installed on your phone? Also you have o manually move some files from folders to folder... what are in your ./siriproxy, ~.rvm/gems/ruby-1.9.3.p0/bin,  ~.rvm/gems/ruby-1.9.3.p0/gem/siriproxy-0.3.0 folder?

**Comment by hirakujira** [comment]
I just reinstalled whole the SiriProxy and it fixed

**Comment by nathreed** [comment]
@hirakujira like followed the whole process from the line-by-line instructions? or just go back and cd into SiriProxy and do rake install?

**Comment by hirakujira** [comment]
@nathreed I deleted everything in "~/.rvm/gems" and restart from "rvmsudo gem install rake bundler".
By the way, I use "rvmsudo 'SiriProxy-path/bin/siriproxy server" instead of "rvmsudo siriproxy server"

**Comment by nathreed** [comment]
@sudoname 
Folder contents
.siriproxy: ca.pem, cert.log, config.yml, server.passles.crt, server.passless.key
~.rvm/gems/ruby-1.9.3.p0/bin: bundle, rake, siriproxy

**Comment by nathreed** [comment]
@hirakujira what install guide are you referencing from?? I don't see that line in plamoni's line-by-line that he used in the youtube video.

**Comment by hirakujira** [comment]
@nathreed I followed plamoni's guide. However when I got wrong, I just try some commands from the "issues" page or ask my friend.

**Comment by sudoname** [comment]
the main problem i hard was the location of the files and older version of openSSL. i upgraded openSSL to 1.0.0e and manually moved some files around and i am up and running
@nathreed i also copied all the content of the original siriproxy folder into ~.rvm/gems/ruby-1.9.3.p0/gems/siriproxy-0.3.0

**Comment by dan122334455** [comment]
what files do you move around? and where do you put them? Thanks

**Comment by sudoname** [comment]
still not working? delete the old files restart and follow these steps, it works in 
NOTE: i am still looking at how to run plugins with the files that i moved but siriproxy is up and running fine.

Create a siriproxy folder
Abayomi:siriproxy newuser$ mkdir ca
Abayomi:siriproxy newuser$ cd ca
Abayomi:ca newuser$ /system/library/openssl/misc/ca.pl -newca
        writing new private key to './demoCA/private/cakey.pem'

```
    Common Name (eg, YOUR name) []:myfakeca
```

Abayomi:ca newuser$ /system/library/openssl/misc/ca.pl -newreq

```
    Common Name (eg, YOUR name) []:guzzoni.apple.com
```

Abayomi:ca newuser$ /system/library/openssl/misc/ca.pl -sign

```
    Certificate is to be certified until Dec  7 03:05:22 2012 GMT (365 days)
```

Abayomi:ca newuser$ openssl rsa -in newkey.pem -out server.passless.key
Abayomi:ca newuser$ cp newcert.pem server.passless.crt
dont forget to move newcert.pem, server.passless.crt and server.passless.key into your ./siriproxy folder
dont forget to install ca.pem or newcert.pem on your phone

Abayomi:ca newuser$ bash < <(curl -s https://raw.github.com/wayneeseguin/rvm/master/binscripts/rvm-installer)
Abayomi:ca newuser$ [[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"
Abayomi:ca newuser$ echo '[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # Load RVM function' >> ~/.bash_profile

Abayomi:ca newuser$ cd
Abayomi:~ newuser$ rvm install 1.9.3 --with-gcc=clang
Abayomi:~ newuser$ rvm use 1.9.3-p0 --default
Abayomi:~ newuser$ cd /users/newuser/siriproxy

```
    move all the content of the original siriproxy folder(from github) into ~/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.3.0
    move the siriproxy file (without extension) in /Users/newuser/.rvm/gems/ruby-1.9.3-p0/gems/bin
```

Abayomi:siriproxy newuser$ rake install
Abayomi:siriproxy newuser$ mkdir ~/.siriproxy
Abayomi:siriproxy newuser$ rvmsudo gem install siriproxy
Abayomi:siriproxy newuser$ rake install
Abayomi:siriproxy newuser$ siriproxy gencerts
Abayomi:siriproxy newuser$ rvmsudo siriproxy bundle
Abayomi:siriproxy newuser$ rvmsudo siriproxy server
        Starting SiriProxy on port 443..
        Create server for iPhone connection
        start conn #<SiriProxy::Connection::Iphone:0x007fb9d395c6f0 @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007fb9d395c4e8>, @zip_stream=#Zlib::Deflate:0x007fb9d395c4c0, @consumed_ace=false, @name="iPhone", @ssled=false>
        [Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007fb9d3b9d2c0 @manager=#<SiriProxy::PluginManager:0x007fb9d395bf70 @plugins=[...]>>]

**Comment by dan122334455** [comment]
So I should delete every thing? Like the whole folder. Or just certain items? Thanks

**Comment by sudoname** [comment]
i deleted everything (the whole folder) and did it again ..... at this point you must have done it like 3 or 4 times anyways

**Comment by dan122334455** [comment]
Why do u have to do it more than once? Thanks

**Comment by sudoname** [comment]
you dont if you follow the instructions... and you have everything updated : openSSL, macport, use "rvm use 1.9.3 -p0 --default" etc

**Comment by dan122334455** [comment]
What I don't understand is I followed the video and instructions. Why doesn't mine work when plamonis did?

**Comment by dan122334455** [comment]
Every thing is up to date. Also I installed the virtual machin as root user. So I don't understand why it's not working

**Comment by sudoname** [comment]
same with me, follow the instructions above, it works... dont give up tho

**Comment by dan122334455** [comment]
thanks. i am trying it now. if this works, you will be my hero. lol

**Comment by dan122334455** [comment]
btw, how old are you?

**Comment by nathreed** [comment]
@dan122334455 not giving personal info. i'm pretty novice, skill-wise.

**Comment by dan122334455** [comment]
lol

**Comment by dan122334455** [comment]
the only problem is when im install it ur way is when i type /system/library/openssl/misc/ca.pl -newca  it says thats not a directory

**Comment by nathreed** [comment]
@dan122334455 are you on mac or ubuntu

**Comment by dan122334455** [comment]
im running ubuntu on a mac

**Comment by dan122334455** [comment]
he had instructions how to do it on ubuntu.  It looked quicker

**Comment by sudoname** [comment]
Really? Try /systems/library/openssl/misc/ca.pl -newca or just find where your ~/openssl/misc folder is and drag it to terminal

**Comment by dan122334455** [comment]
is there  a way you can do remote desktop share with me? like join.me ?

**Comment by dan122334455** [comment]
I solved it.  You just have to go down to devices, network adapters, bridge network, then choose wifi.  Then you have to go back to dnsmasq.conf and change to new ip address, then you have to change the dns on the iphone also.  Thanks for the help guys!

**Comment by sabanaqvi** [comment]
I'm having the same issues as you dan.  Can you be more explicit in how you are accessing the bridge network option?  Is it in OSX or Ubuntu (if Ubuntu then which version)

**Comment by dan122334455** [comment]
I'm using the newest version of Ubuntu on my Mac with virtual machine. I have instructions on YouTube. I'm on my iPhone, so I can't give link, but just go to YouTube.com/jbaybayjbaybay and look for how to set up Siri proxy. It's in the video somewhere lol. Hope this helps!

**Comment by dan122334455** [comment]
here is the link and time: http://www.youtube.com/watch?v=cTuhjTvg_pw&t=2m28s

**Comment by sabanaqvi** [comment]
Thanks, we found your video before you sent it and were able to successfully get the siriproxy server running. Your videos have been extremely helpful!!!

**Comment by dan122334455** [comment]
thanks!!! I am glad to help!
