### ISSUE TITLE
SiriProxy with an integrated, simple, ruby dns server

### ISSUE THREAD

**Issue by marcos69** [plamoni/SiriProxy#158]
Because I'm not alone with strange DNS problems, all setup done correctly, but I can't make it work on ONE computer.

I would ask if someone could integrate a small and simple ruby dns server in the siriproxy code?

The only thing that dnsmasq do is to filter out that guzzoni.apple.com entry, why could something so simple not be directly implemented in the ruby code, and also take care that no dns loops could arise?

**Comment by JBX028** [comment]
RubyDNS (http://www.oriontransfer.co.nz/gems/rubydns/index) is your friend.

**Comment by sudoname** [comment]
were you able to get a response from guzzoni and what version of openSSL are you using?

**Comment by marcos69** [comment]
@JBX028 : Not so big, just a "Simple, scrappy UDP DNS server in Ruby" -> https://gist.github.com/1425383

@sudoname : OSX 10.6.8 / ruby 1.93 / openSSL1.0.0e / ADSL Modem connected per cable to an Airport express 10.0.1.1

Mac via Airport has 10.0.1.2, Mac DNS (resolv.conf) set to 62.2.17.60 (provider DNS).
dnsmasq  --address=/guzzoni.apple.com/10.0.1.2 (is also in dnsmasq.conf)

#nslookup guzzoni.apple.com
Server:     62.2.17.60
Address:    62.2.17.60#53

Non-authoritative answer:
guzzoni.apple.com   canonical name = origin.guzzoni-apple.com.akadns.net.
origin.guzzoni-apple.com.akadns.net canonical name = reg1.guzzoni-apple.com.akadns.net.
Name:   reg1.guzzoni-apple.com.akadns.net
Address: 17.174.4.4

#nslookup guzzoni.apple.com 127.0.0.1
Server:     127.0.0.1
Address:    127.0.0.1#53

Name:   guzzoni.apple.com
Address: 10.0.1.2

a port scan give 53 (for dnsmasq) and 443 (for siriproxy).
Iphone 4S with network settings router 10.0.1.1 and DNS 10.0.1.2

#rvmsudo bin/siriproxy server
Starting SiriProxy on port 443..
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000100a71358 @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000100a88be8>, @zip_stream=#Zlib::Deflate:0x00000100a88a80, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000101191458 @manager=#<SiriProxy::PluginManager:0x00000100a876f8 @plugins=[...]>>]

Siri is not able to ...

How it worked: Running siriproxy in a virtualbox with suse11 (10.0.1.3) this ip in the dnsmasq.conf on the Mac. BUT this isn't funny...

**Comment by sudoname** [comment]
????? => ""How it worked: Running siriproxy in a virtualbox with suse11 (10.0.1.3) this ip in the dnsmasq.conf on the Mac. BUT this isn't funny..."" i dont get that but everything before that looks right ..

**Comment by JBX028** [comment]
I had issues as well with dnsmasq but it was because "NAT" was selected instead of "Bridge" on the network setting in virtual box. After the switch i was able to ping my virtual box and everything works fine.

**Comment by marcos69** [comment]
@sudoname: On my Mac I run dnsmasq which send the request to a virtual machine containing Suse Linux with the siriproxxy running and this works.
But I would like to use dnsmasq and Siriproxy together on the mac but that won't work, I don't want "2" computer for it, that's why a simple crapy DNS included in Siriproxy would be easier.

I know everything is looking right, but somewhere I got a looping dns. And I'm not alone.

**Comment by sudoname** [comment]
if i give you my line codes and instruction.... will you try it on only your Mac? it work

**Comment by marcos69** [comment]
you mean the instruction on the bottom of issue 157 ?

**Comment by marcos69** [comment]
@sudoname : How did you install openssl 1.0.0e ? I've done a macport install, renamed the old include/openssl and made a link to /opt/local/include/openssll (same with the libssl.dylib) but installing ruby 1.9.3 break with errors referring  to the include/openssl/hmac.h

**Comment by sudoname** [comment]
@marcos69 yes, it works all the time if you have the req and check the version of openssl that you have first. anything over 1.0.0 should be fine. how are you installing ruby 1.9.3?

**Comment by marcos69** [comment]
@sudoname : rvm install 1.9.3  with openssl 1.0.0e won't install, I don't think ruby 1.9.3 work with openssl 1.0.0.
Which file do you mean: "move the siriproxy file (without extension) in /Users/newuser/.rvm/gems/ruby-1.9.3-p0/gems/bin"
Because I'm stuck here: 
#rvmsudo gem install siriproxy
ERROR:  Could not find a valid gem 'siriproxy' (>= 0) in any repository
ERROR:  Possible alternatives: drbproxy

**Comment by sudoname** [comment]
there is a siriproxy file in the original plamoni folder you downloaded from githuh. Also try "rvm install 1.9.3 --with-gcc=clang" instead of  rvm install 1.9.3, it worked for me.

**Comment by sudoname** [comment]
Also make sure you use rvm use 1.9.3-p0 --default right after installing it

**Comment by ioquatix** [comment]
Hi, I just thought I'd mention that RubyDNS would be perfect for your needs =)
