### ISSUE TITLE
Spaces and SiriProxy

### ISSUE THREAD

**Issue by alastairorchard** [plamoni/SiriProxy#161]
Hi,

I had big issues installing Ruby 1.9.3 with RVM because my hdd name has a space in it.

I updated the rvm_path with a custom link that solved the problem, but when I tried Rake Install in the SiriProxy directory I get :

*\* Invoke install (first_time)
*\* Execute install
siriproxy 0.0.1 built to pkg/siriproxy-0.0.1.gem
rake aborted!
Couldn't install gem, run `gem install /Volumes/Macintosh HD2/Alastair/SiriProxy/pkg/siriproxy-0.0.1.gem' for more detailed output
/.rvm.Alastair/gems/ruby-1.9.3-p0/gems/bundler-1.0.21/lib/bundler/gem_helper.rb:57:in`install_gem'
/.rvm.Alastair/gems/ruby-1.9.3-p0/gems/bundler-1.0.21/lib/bundler/gem_helper.rb:33:in `block in install'
/.rvm.Alastair/gems/ruby-1.9.3-p0/gems/rake-0.9.2.2/lib/rake/task.rb:205:in`call'
/.rvm.Alastair/gems/ruby-1.9.3-p0/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
/.rvm.Alastair/gems/ruby-1.9.3-p0/gems/rake-0.9.2.2/lib/rake/task.rb:200:in`each'
/.rvm.Alastair/gems/ruby-1.9.3-p0/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/.rvm.Alastair/gems/ruby-1.9.3-p0/gems/rake-0.9.2.2/lib/rake/task.rb:158:in`block in invoke_with_call_chain'
/.rvm.Alastair/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/.rvm.Alastair/gems/ruby-1.9.3-p0/gems/rake-0.9.2.2/lib/rake/task.rb:151:in`invoke_with_call_chain'
/.rvm.Alastair/gems/ruby-1.9.3-p0/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/.rvm.Alastair/gems/ruby-1.9.3-p0/gems/rake-0.9.2.2/lib/rake/application.rb:116:in`invoke_task'
/.rvm.Alastair/gems/ruby-1.9.3-p0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
/.rvm.Alastair/gems/ruby-1.9.3-p0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in`each'
/.rvm.Alastair/gems/ruby-1.9.3-p0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
/.rvm.Alastair/gems/ruby-1.9.3-p0/gems/rake-0.9.2.2/lib/rake/application.rb:133:in`standard_exception_handling'
/.rvm.Alastair/gems/ruby-1.9.3-p0/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/.rvm.Alastair/gems/ruby-1.9.3-p0/gems/rake-0.9.2.2/lib/rake/application.rb:66:in`block in run'
/.rvm.Alastair/gems/ruby-1.9.3-p0/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/.rvm.Alastair/gems/ruby-1.9.3-p0/gems/rake-0.9.2.2/lib/rake/application.rb:63:in`run'
/.rvm.Alastair/gems/ruby-1.9.3-p0/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/.rvm.Alastair/gems/ruby-1.9.3-p0/bin/rake:19:in`load'
/.rvm.Alastair/gems/ruby-1.9.3-p0/bin/rake:19:in `<main>'
Tasks: TOP => install

I have a feeling that the space is the culprit again...

I managed to install the gem manually once in the pkg directory, but running the Rake install again doesn't skip the gem step, so I'm stuck.

Any ideas?

Many thanks!!

Al

**Comment by dan122334455** [comment]
download virtual box (its free) then download ubunto (its free) then install linux in virtual box (its free) then go to https://gist.github.com/1428474 Its step by step and took less than 20 min to install the proxy.  The only problem is that there is an error with port 443.  But that can just be my computer.  This way is much eaiser and faster.  There is an video on it.  http://www.youtube.com/watch?v=GQXyJR6mOk0  Hope this helps!

**Comment by sudoname** [comment]
Try "rvm install 1.9.3 --with-gcc=clang" it worked for me

**Comment by alastairorchard** [comment]
Thanks for the advice.  I got the Ubuntu version running with no problem, but I'm really interested in using this to run my Plex.  I presume that it needs to be running on the Plex server OSX machine...

Ram is already installed - it's SiriProxy that won't install... The Rake install fails...

**Comment by plamoni** [comment]
Take the suggestion of the error:

`run gem install /Volumes/Macintosh HD2/Alastair/SiriProxy/pkg/siriproxy-0.0.1.gem' for more detailed output`

**Comment by alastairorchard** [comment]
Hi Pete - appreciate the help.

If I take the advice and try to run that command then it just fails, but I can install the gem by changing to the pkg directory and doing it from there.

Problem is that once it's installed I can't move forward.  What do I do next?  If I retry rake install then it doesn't detect that the gem is already installed and skip to the next step - it just starts over and blocks at the gem install again...

Congrats on the proxy!

Al

**Comment by sudoname** [comment]
if i were you, i will start again cos it looks like you are using an old download anyway.. siriproxy-0.3.0 is been used now..
before you do that check that you have all the preq. Xcode, openssl and make sure nothing is running on port 443. good luck

**Comment by alastairorchard** [comment]
OK, I started again, and using 0.3.0 I've got right through to generating the certificates >

$ siriproxy gencerts

/.rvm.Alastair/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:247:in `to_specs': Could not find siriproxy (>= 0) amongst [bigdecimal-1.1.0, io-console-0.3, json-1.5.4, minitest-2.5.1, rake-0.9.2.2, rdoc-3.9.4] (Gem::LoadError)
    from /.rvm.Alastair/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:256:in`to_spec'
    from /.rvm.Alastair/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems.rb:1210:in `gem'
    from /.rvm.Alastair/gems/ruby-1.9.3-p0/bin/siriproxy:18:in`<main>'

I feel like an arse.  I guess I can install the certificate manually - right?

Al

**Comment by sudoname** [comment]
Try .siriproxy gencerts make sure you use 1.9.3-p0

**Comment by Marian-Lein** [comment]
Since I got a similar error, i'd port my terminal's output here:

M***s-Mac-Pro:siriproxy ml$ gem install /Users/ml/SiriProxy/pkg/siriproxy-0.3.0.gem
/usr/local/rvm/rubies/ruby-1.9.3-p0/bin/gem:4: warning: Insecure world writable dir /usr/local/rvm/gems in PATH, mode 040707
Fetching: libxml-ruby-2.2.2.gem (100%)
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied - /usr/local/rvm/gems/ruby-1.9.3-p0@SiriProxy/cache/libxml-ruby-2.2.2.gem

How do I give the installer the required permissions?!

**Comment by plamoni** [comment]
Installing gems often requires super user permissions. Try "sudo gem install ..."
