### ISSUE TITLE
Kinect as Input device

### ISSUE THREAD

**Issue by MovGP0** [plamoni/SiriProxy#162]
Would like to have Kinect as Input device for Siri. 

Kinect is listening to the user the whole time. Instead of pressing a button, kinect reacts to the keyword "xbox" - followed by a command - at any time. 

The idea is to use [kinect for windows](http://kinectforwindows.org/) with a custom keyword like "computer" and use the rest of the input for siri. 

Furthermore, because kinect supports beam tracking of the audio input, multiple users could be supported at the same time.

**Comment by JBX028** [comment]
Hello,

This is technically possible. If you look at the instructions given by Applidium (https://github.com/applidium/Cracking-Siri) you can see that if you encode any recorded sound in a speex format, you can send the sound to apple.
This is outside of what siriproxy does, but feel free to share if you are able to do that yourself.

Regards,

**Comment by plamoni** [comment]
Sorry, but we don't support or encourage the "porting" of Siri to any other hardware due to legal ambiguities.
