### ISSUE TITLE
Have issue with start proxy again? See here

### ISSUE THREAD

**Issue by ftwhacker** [plamoni/SiriProxy#164]
I maked a new tool for Mac osx, that makes you start the siriproxy again, and if you get ruby errors.
You can get ruby errors by start siriproxy once then try to start but it gives you a error then try this:
https://github.com/ftwhacker/SiriProxy-restart

Enjoy

-ftwhacker

**Comment by keshavsaharia** [comment]
I don't understand why you can't just tell people to use those shell commands, or to edit their .bash_profile. The script is 99% unnecessary, 1% redundant.

**Comment by ftwhacker** [comment]
are you using ubuntu or mac os x?

**Comment by keshavsaharia** [comment]
I don't think you understood what I meant. I'm not asking for help, I'm trying to make you aware that it is pretty pointless to make repositories that consist of a shell script within a readme file that is just a few commands mixed with print statements that glorify your name.

**Comment by ftwhacker** [comment]
I understood what you said now, but its some people that dont understand how to open the .bash_profile since its a hidden file, and some people dont know how to show hidden files so it can be necessary to someone.

~ftwhacker
