### ISSUE TITLE
Cant find ca.pem ubuntu

### ISSUE THREAD

**Issue by jdsapwell** [plamoni/SiriProxy#166]
i am unable to find ca.pem on my ubuntu virtual box.

**Comment by dan122334455** [comment]
All you have to do is cd into the directory wich i believe is .siriproxy, and then type the command "nautilus ." without quotes.  That should open it, you can also try nautilus foldername  im not sure if that will work, but the first one does.  Then once the folder is open, make a copy of that, paste it on the desktop, then open email such as hotmail, and then it is easier to find to attach. Hope this helps!

**Comment by jdsapwell** [comment]
thanks, but the best thing that worked for me was, when i was in "home" press ctrl+h and that will show the hidden .siriproxy folder with ca.pem in it.

thanks for responding

**Comment by dan122334455** [comment]
no prob

**Comment by dan122334455** [comment]
i have a question my self, is yours working? if it is can you please help me? I am stuck because all it says is siriproxy on port 443. Can you please help? I have the certificate on my 4s.
