### ISSUE TITLE
CA.PEM help!

### ISSUE THREAD

**Issue by ftwhacker** [plamoni/SiriProxy#167]
Hey :)
I installed SiriProxy and whole thing its up and running, but "ca.pem" is 0 kb so i cant send it by any email provider, its ca.pem should to be 0 kb?
What i am doing wrong?

-ftwhacker

**Comment by jdsapwell** [comment]
Sorry, I can't help with this but do you know where the actual file is saved?

**Comment by ftwhacker** [comment]
Dont mind :)
I fixed it.
I just updated SiriProxy then used siriproxy gencerts commands then its worked :)

**Comment by jdsapwell** [comment]
Ok cool, wat operating system r u using?

**Comment by ftwhacker** [comment]
i use mac osx :)
