### ISSUE TITLE
siri proxy won't start

### ISSUE THREAD

**Issue by shameer99** [plamoni/SiriProxy#169]
im not sure whats wrong. it wont work. it says 

Starting SiriProxy on port 443..

is it supposed to be 443 or something else?
help

**Comment by Skaveny** [comment]
haw u sheng the dns address in ur iphone 4s to the ip of the computer ur running dns server on?

**Comment by shameer99** [comment]
?

**Comment by Skaveny** [comment]
Change DNS settings on your iPhone 4S

To route the DNS requests to guzzoni.apple.com, we need to change the DNS settings on your iPhone 4S.

First Opens the Settings app.
Now go on and choose your Wi-Fi network in the list, if you are not already connected.
Now go on the blue arrow so you can change the DNS settings.
Note: Delete the IP in the DNS entry and adds the IP of your computer that you've used on dnsmasq. If you use the wrong IP, Siri can not connect!

**Comment by Skaveny** [comment]
this is a grate how to page http://www.funkyspacemonkey.com/install-siri-proxy

**Comment by shameer99** [comment]
Thanks works :)
