### ISSUE TITLE
Implement SiriProxy AUTH Spoofing for non iPhone 4S iDevices.

### ISSUE THREAD

**Issue by bobbyjayblack** [plamoni/SiriProxy#17]
Here is an idea for getting Siri working on other iDevices using a VPN and a modified SiriProxy.
1. Create a internet accessible VPN for yourself.
2. Use that VPN on an iPhone 4S and other iDevices you (or friends) own.
3. VPN server uses local dnsmasq, which resolves guzzoni.apple.com to your VPN server ip.
4. Whenever a iPhone 4S uses Siri, record the AUTH packet and process SpeechPacket.
5. Whenever a non iPhone 4S uses Siri, use recorded AUTH packet and process SpeechPacket.

Clarifications:
"process SpeechPacket": if Speech is recognized, perform SiriProxy action. if Speech is not recognized, forward to Apple's actual Siri Server.

Potential problems:
Recording the AUTH packet: does it change on every request or just every 24 hours?
Using recorded AUTH packet with non iPhone 4S: are the SpeechPackets encrypted with data in the AUTH packet?

Edit: I ment to have this as a potential milestone. Is it possible for non-owner's to create open milestones?

**Comment by plamoni** [comment]
While I appreciate the thought that went into this. And there are many ways to do what you suggested (your way is quite ingenious, actually). I am going to shy away from making SiriProxy into a tool used for getting Siri working on non-iPhone 4S devices.

Doing so will just risk having Apple shut the project down with their room full of lawyers. Sorry!
