### ISSUE TITLE
I started up siriproxy the first time and once i closed it and tried to reopen i get this error

### ISSUE THREAD

**Issue by ghost** [plamoni/SiriProxy#170]
granit@ubuntu:~/SiriProxy$ rvmsudo siriproxy server
[sudo] password for granit: 
Starting SiriProxy on port 443..
/home/granit/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy.rb:26:in `rescue in block in initialize': Cannot start the server on port 443 - are you root, or have another process on this port already? (RuntimeError)
    from /home/granit/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy.rb:17:in`block in initialize'
    from /home/granit/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `call'
    from /home/granit/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run_machine'
    from /home/granit/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
    from /home/granit/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy.rb:16:in`initialize'
    from /home/granit/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:96:in `new'
    from /home/granit/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:96:in`start_server'
    from /home/granit/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:85:in `run_server'
    from /home/granit/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:37:in`initialize'
    from /home/granit/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/bin/siriproxy:6:in `new'
    from /home/granit/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/bin/siriproxy:6:in`<top (required)>'
    from /home/granit/.rvm/gems/ruby-1.9.3-p0@SiriProxy/bin/siriproxy:19:in `load'
    from /home/granit/.rvm/gems/ruby-1.9.3-p0@SiriProxy/bin/siriproxy:19:in`<main>'

I have tried to killall ruby and it still doesnt work, Any help would be great

**Comment by dan122334455** [comment]
Type ps -A.  Then find the procces siriproxy. Then type sudo kill then the number next to siriproxy

**Comment by ghost** [comment]
thanks i got that fixed, i finally got it started until it says "granit@ubuntu:~/SiriProxy$ rvmsudo siriproxy server
Starting SiriProxy on port 443..
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x97ea35c @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x97ea1f4>, @zip_stream=#Zlib::Deflate:0x97ea1e0, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x9a9253c @manager=#<SiriProxy::PluginManager:0x97e9efc @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x9a92474 @signature=4, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x9a923ac>, @zip_stream=#Zlib::Deflate:0x9a92398, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x9a91e0c @manager=#<SiriProxy::PluginManager:0x9a921a4 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x9a91d58 @signature=5, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x9a91c7c>, @zip_stream=#Zlib::Deflate:0x9a91c54, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x9a916a0 @manager=#<SiriProxy::PluginManager:0x9a919e8 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x9a915b0 @signature=6, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x9a914d4>, @zip_stream=#Zlib::Deflate:0x9a914c0, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x9a90ee4 @manager=#<SiriProxy::PluginManager:0x9a91254 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x9a90e08 @signature=7, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x9a90d2c>, @zip_stream=#Zlib::Deflate:0x9a90d18, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x9a907a0 @manager=#<SiriProxy::PluginManager:0x9a90ac0 @plugins=[...]>>]

any ideas?

**Comment by dan122334455** [comment]
yea, i had that originally, just make sure you installed the ca.pem on your iphone

**Comment by dan122334455** [comment]
once you get it working, youll have so much fun!

**Comment by plamoni** [comment]
Also, this could be a DNS issue. We need to write some code to account for that and display a meaningful error.

**Comment by ghost** [comment]
thanks i did end up getting it working, i just resent the ca.pem file to my phone and it started to work.
