### ISSUE TITLE
working before now wont start.

### ISSUE THREAD

**Issue by shameer99** [plamoni/SiriProxy#171]
siri proxy was woeking before but i changed a few things and now it fails. i did do siriproxy bundle

here:
Starting SiriProxy on port 443..
/Users/shameer/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.3.0/lib/siriproxy.rb:26:in `rescue in block in initialize': Cannot start the server on port 443 - are you root, or have another process on this port already? (RuntimeError)
    from /Users/shameer/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.3.0/lib/siriproxy.rb:17:in`block in initialize'
    from /Users/shameer/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `call'
    from /Users/shameer/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run_machine'
    from /Users/shameer/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
    from /Users/shameer/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.3.0/lib/siriproxy.rb:16:in`initialize'
    from /Users/shameer/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:96:in `new'
    from /Users/shameer/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:96:in`start_server'
    from /Users/shameer/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:85:in `run_server'
    from /Users/shameer/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:37:in`initialize'
    from /Users/shameer/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.3.0/bin/siriproxy:6:in `new'
    from /Users/shameer/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.3.0/bin/siriproxy:6:in`<top (required)>'
    from /Users/shameer/.rvm/gems/ruby-1.9.3-p0/bin/siriproxy:19:in `load'
    from /Users/shameer/.rvm/gems/ruby-1.9.3-p0/bin/siriproxy:19:in`<main>'

**Comment by ghost** [comment]
type in:     ps -A
find the port number of siriproxy and then type in :   sudo kill <port #>
then try it all over again, it should work

**Comment by ftwhacker** [comment]
use my sirirestarter, https://github.com/ftwhacker/SiriProxy-restart

**Comment by shameer99** [comment]
Thanks to both
