### ISSUE TITLE
Adding Plugin errors

### ISSUE THREAD

**Issue by dan122334455** [plamoni/SiriProxy#173]
When ever i add a plug in.  I always get an that it couldnt find the gem file.  I add the downloaded plugin to plugins, then i rename it to lests say siriproxy-test .  Then i go to the conflg.yml and copy and paste your example one and i just edited it to suite mine.  Then i go to the bash file and bundle it.  then i get the couldnt find gem file.  Can you please help?  I am using ubuntu. Thanks

**Comment by dan122334455** [comment]
also, how do you make a simple plugin so you can give it custome commands?  Thanks

**Comment by TwelveK** [comment]
I'm also using Ubuntu and having the same problems. I can not install my custom plugins.
I have followed the example plugin and have no luck what so ever gives me these errors.

Could not find gem 'siriproxy-siriproxytest (>= 0) ruby' in source at ./plugins/siriproxy-test.
Source does not contain any versions of 'siriproxy-siriproxytest (>= 0) ruby'

**Comment by ftwhacker** [comment]
edit the siriproxy-siriproxytest(orwhatever).gemspec (something like that) and make it point to your information( edit the name to SiriProxyTest etc.)

**Comment by dan122334455** [comment]
can you please explain more? i renamed everthing and i still get an error

**Comment by dan122334455** [comment]
also, if i edit the siriproxy-example code to make it say something else instead of siriproxy is up and running!, it dosent say the thing i want it to say.  (i bundle after i finish)  can you please help?

**Comment by TwelveK** [comment]
My gemspec file is exactly like the siriproxy-example.gemspec except for the version, author and etc.

**Comment by dan122334455** [comment]
I keep getting this error. The path `/home/daniel/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/plugins/siriproxy-meaningoflife` does not exist.    I have it installed in the plugins folder next to example-plugin .  I also added it into the config.yml file.  HELP ME!!!! PLEASE!

**Comment by TwelveK** [comment]
I had the same error for my custom plugin witch is an edited version of the meaningoflife plugin. I installed the folder were is said it didnt exist and thats when I got my error below after I tried to the siriproxy bundle.

Could not find gem 'siriproxy-siriproxytest (>= 0) ruby' in source at ./plugins/siriproxy-test.
Source does not contain any versions of 'siriproxy-siriproxytest (>= 0) ruby'

**Comment by TwelveK** [comment]
Dan, if you are using ubuntu you will have to use or I have to use "sudo siriproxy bundle" or rvmsudo siriproxy bundle". After I enter that it says my plugin folder is in "/var/lib/gems/ruby-1.9.1/gems/siriproxy-0.3.0/plugins" thats where I had to install my plugin to get the error to go away.

**Comment by dan122334455** [comment]
now im getting this: git://github.com/vic10us/siriproxy-meaningoflife.git (at master) is not checked out. Please run 'bundle install'

**Comment by 7imbrook** [comment]
Make sure to change the name in the class to in the lib:/yourplugin.rb

**Comment by dan122334455** [comment]
Why wont this work.  I am trying to get the plug in meaning of life to work.  I downloaded it, dragged and dropped it into the plug in folder, changed the name to siriproxy-meaningoflife for all the shortcuts/folder, then in config.yml i added -name:  'MeaningOfLife'
git:  '(the git url for the source)'
path:  './plugins/siriproxy-meaningoflife'

Please help!
is there any way some one can screen share to show me? like join.me  its free..,

**Comment by dan122334455** [comment]
I realized i am only able to install files that i can install using git.  how can i install my own?

**Comment by dan122334455** [comment]
I have figured it out and made a youtube video. Hope this helps!  http://www.youtube.com/watch?v=A48SGUt_7lw
