### ISSUE TITLE
IP Control - Question/help

### ISSUE THREAD

**Issue by dansonamission** [plamoni/SiriProxy#174]
Hello, is there any way to program a Siri proxy to send hex commands to an IP address over TCP?

The board I am trying to communicate with is... 

http://www.robot-electronics.co.uk/htm/eth_rly16tech.htm

Thanks
Dan

**Comment by dcinzona** [comment]
You gotta learn ruby.  Ruby will be able to do it.

**Comment by dansonamission** [comment]
I'm learning. Any learning pointers?

Sending hex 0x65 to an IP

**Comment by dcinzona** [comment]
try http://peepcode.com/products/ruby19-i
Or the multitude of other web tutorials...

**Comment by dansonamission** [comment]
Could you post your code so we can see how your getting on.

**Comment by Alsaegh** [comment]
just wanna know ,, have you made it ?? 
or still ?? ,, cause i am doing the same thing but with this part >  Format: ![PIC32](http://media.rsdelivers.cataloguesolutions.com/LargeProductImages/R6868657-01.jpg)

I still don't know where to start and what exactly to learn ?
