### ISSUE TITLE
bundle install error

### ISSUE THREAD

**Issue by venom420x** [plamoni/SiriProxy#175]
i get this with the new SiriProxy version while executing the bundle install command

Matts-iMac:SiriProxy VeNoM$ sudo bundle install
/Users/VeNoM/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:247:in `to_specs': Could not find bundler (>= 0) amongst [CFPropertyList-2.0.17, bigdecimal-1.1.0, eventmachine-0.12.10, io-console-0.3, json-1.5.4, libxml-ruby-2.2.2, minitest-2.5.1, rake-0.9.2.2, rdoc-3.9.4, siriproxy-0.3.0, uuidtools-2.1.2] (Gem::LoadError)
    from /Users/VeNoM/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:256:in`to_spec'
    from /Users/VeNoM/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems.rb:1210:in `gem'

**Comment by ftwhacker** [comment]
try: sudo siriproxy bundle

**Comment by ghost** [comment]
try siriproxy bundle or siriproxy update or bundle install
