### ISSUE TITLE
siriproxy start problem

### ISSUE THREAD

**Issue by chrisbox** [plamoni/SiriProxy#179]
ive followed every step but when i get to the final step ' rvmsudo siriproxy server im getting this error.

chrisbox@chrisbox-VirtualBox:~/SiriProxy$ rvmsudo siriproxy server
/home/chrisbox/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych.rb:229:in `initialize': No such file or directory - /root/.siriproxy/config.yml (Errno::ENOENT)
    from /home/chrisbox/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych.rb:229:in`open'
    from /home/chrisbox/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych.rb:229:in `load_file'
    from /home/chrisbox/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:143:in`parse_options'
    from /home/chrisbox/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:33:in `initialize'
    from /home/chrisbox/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/bin/siriproxy:6:in`new'
    from /home/chrisbox/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/bin/siriproxy:6:in `<top (required)>'
    from /home/chrisbox/.rvm/gems/ruby-1.9.3-p0@SiriProxy/bin/siriproxy:19:in`load'
    from /home/chrisbox/.rvm/gems/ruby-1.9.3-p0@SiriProxy/bin/siriproxy:19:in `<main>'

thanks for any help

**Comment by dcinzona** [comment]
read the instructions.

You skipped a step.

**Comment by chrisbox** [comment]
can u please explain which one of the step ive missed?

**Comment by dcinzona** [comment]
Make .siriproxy directory:
mkdir ~/.siriproxy
Move default config file to .siriproxy (if you need to make configuration changes, do that now by editing the config.yml):
cp ./config.example.yml ~/.siriproxy/config.yml

**Comment by chrisbox** [comment]
oh Ive done that for sure....gonna run it again
 :)

**Comment by jassinm** [comment]
same problem here . seem to be a rvmsudo prob as config.yml is in user directory.
on debian and user is in sudolist
