### ISSUE TITLE
Where's the plugin page?

### ISSUE THREAD

**Issue by dan122334455** [plamoni/SiriProxy#180]
What happened to the plug in page?? Now the plug ins i have installed won't work, and the page is gone from the wiki!! What happened?!?

**Comment by dan122334455** [comment]
Edit: My plugin is still working, i just edited it by accident.... But still, where is the page?

**Comment by wesalbert** [comment]
I can't find it anymore either.

**Comment by dan122334455** [comment]
PLEASE PUT IT BACK UP!!!

**Comment by wesalbert** [comment]
Dan,
Found them....

https://github.com/plamoni     they are on the left

**Comment by dan122334455** [comment]
I dont see them.  There were like 10-20 plugins...

**Comment by wesalbert** [comment]
Really, that many? I just saw the one I was interested in. The Thermostat one.

**Comment by dan122334455** [comment]
no, he had facebook, car starter, thats what she said, twitter, controll computer, meaning of life...

**Comment by wesalbert** [comment]
Look under history
https://github.com/plamoni/SiriProxy/wiki/_history
You will have to click each one. They are there

**Comment by johngregorio** [comment]
Looks like laxman01 deleted it. Troll perhaps?

**Comment by wesalbert** [comment]
It's back up
https://github.com/plamoni/SiriProxy/wiki/Plugins
