### ISSUE TITLE
rake install error!

### ISSUE THREAD

**Issue by hikmetabi** [plamoni/SiriProxy#181]
why ?

root@emir:~/SiriProxy# rake install --trace
(in /home/emir/SiriProxy)
*\* Invoke install (first_time)
*\* Execute install
siriproxy 0.3.0 built to pkg/siriproxy-0.3.0.gem
rake aborted!
Couldn't install gem, run `gem install /home/emir/SiriProxy/pkg/siriproxy-0.3.0.gem' for more detailed output
/usr/lib/ruby/vendor_ruby/bundler/gem_helper.rb:57:in`install_gem'
/usr/lib/ruby/vendor_ruby/bundler/gem_helper.rb:33:in `install'
/usr/lib/ruby/1.8/rake.rb:636:in`call'
/usr/lib/ruby/1.8/rake.rb:636:in `execute'
/usr/lib/ruby/1.8/rake.rb:631:in`each'
/usr/lib/ruby/1.8/rake.rb:631:in `execute'
/usr/lib/ruby/1.8/rake.rb:597:in`invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/usr/lib/ruby/1.8/rake.rb:590:in`invoke_with_call_chain'
/usr/lib/ruby/1.8/rake.rb:583:in `invoke'
/usr/lib/ruby/1.8/rake.rb:2051:in`invoke_task'
/usr/lib/ruby/1.8/rake.rb:2029:in `top_level'
/usr/lib/ruby/1.8/rake.rb:2029:in`each'
/usr/lib/ruby/1.8/rake.rb:2029:in `top_level'
/usr/lib/ruby/1.8/rake.rb:2068:in`standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:2023:in `top_level'
/usr/lib/ruby/1.8/rake.rb:2001:in`run'
/usr/lib/ruby/1.8/rake.rb:2068:in `standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:1998:in`run'
/usr/bin/rake:28

**Comment by hikmetabi** [comment]
ERROR:  Error installing /home/emir/SiriProxy/pkg/siriproxy-0.3.0.gem:
    siriproxy requires Ruby version >= 1.9.2.

my ruby version is 1.8.7 and i can't update 1.9.2

error messages:
by-1.9.2-p0 - #extracting ruby-1.9.2-p0 to /usr/share/ruby-rvm/src/ruby-1.9.2-p0
ruby-1.9.2-p0 - #extracted to /usr/share/ruby-rvm/src/ruby-1.9.2-p0
Fetching yaml-0.1.4.tar.gz to /usr/share/ruby-rvm/archives
Extracting yaml-0.1.4.tar.gz to /usr/share/ruby-rvm/src
Configuring yaml in /usr/share/ruby-rvm/src/yaml-0.1.4.
Compiling yaml in /usr/share/ruby-rvm/src/yaml-0.1.4.
ERROR: Error running 'make ', please read /usr/share/ruby-rvm/log/ruby-1.9.2-p0/yaml/make.log
Installing yaml to /usr/share/ruby-rvm/usr
ERROR: Error running 'make install', please read /usr/share/ruby-rvm/log/ruby-1.9.2-p0/yaml/make.install.log
ruby-1.9.2-p0 - #configuring 
ruby-1.9.2-p0 - #compiling 
ERROR: Error running 'make ', please read /usr/share/ruby-rvm/log/ruby-1.9.2-p0/make.log
ERROR: There has been an error while running make. Halting the installation.

**Comment by mroma** [comment]
I've got the same problems.

**Comment by ghost** [comment]
idem
