### ISSUE TITLE
rake install problems

### ISSUE THREAD

**Issue by paradajoseluis** [plamoni/SiriProxy#182]
ubuntu@siri:~/SiriProxy$ rake install --trace
rake aborted!
cannot load such file -- bundler/gem_tasks
/home/joseluis/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/home/joseluis/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
/home/joseluis/SiriProxy/Rakefile:3:in `<top (required)>'
/home/joseluis/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/rake/rake_module.rb:25:in`load'
/home/joseluis/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/rake/rake_module.rb:25:in `load_rakefile'
/home/joseluis/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/rake/application.rb:501:in`raw_load_rakefile'
/home/joseluis/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/rake/application.rb:82:in `block in load_rakefile'
/home/joseluis/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/rake/application.rb:133:in`standard_exception_handling'
/home/joseluis/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/rake/application.rb:81:in `load_rakefile'
/home/joseluis/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/rake/application.rb:65:in`block in run'
/home/joseluis/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/rake/application.rb:133:in `standard_exception_handling' 
/home/joseluis/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/rake/application.rb:63:in`run' 
/home/joseluis/.rvm/rubies/ruby-1.9.3-p0/bin/rake:36:in `<main>'

what do i do?? i can't install siri proxy i did all as it said in the tutorial.. a little help

**Comment by iFredLouzada** [comment]
did you get the extra dependencies that the installation ask you to make sure you have during the install ? What system did you install siriproxy to ?

**Comment by paradajoseluis** [comment]
Yes i did install them.. And im doing this on a mac mini server with ubuntu on parallels.. The mac mini server is working with os x server.. I got all done but the problem is that rake install is not working it only marks me that error and i can get pass that i tried doind every thing again multiple times [ without eraseing what i have done i just reenter every code that was given]  what shoul i do?? Should i erase all and start from scratches?? And also i check all those files that trace mark and they all are where they should be.. The problem is that they are not executing
