### ISSUE TITLE
Edit example plugin

### ISSUE THREAD

**Issue by dansonamission** [plamoni/SiriProxy#184]
Hi, how do I load my changes that I have made to the example plugin??

Managed to do it once with a whole load of commands, as it wouldn't work at first. I just got lucky and now I can't remember what I did.

Please help.

Im running Ubuntu 11.10

Thanks

**Comment by plamoni** [comment]
`siriproxy update <dir>`

Where `<dir>` is your SiriProxy directory. NOT the plugin directory.
Your root SiriProxy directory.

-Pete

Sent from my iPhone

On Dec 12, 2011, at 7:19 AM, Dan
reply@reply.github.com
wrote:

**Comment by dansonamission** [comment]
Will 'siriproxy update' work when I'm in the directory? or must i specify the dir on the end?

**Comment by AndrewRayCode** [comment]
https://github.com/plamoni/SiriProxy/wiki/Plugin%20Developer%20Guide

Please close this ticket
