### ISSUE TITLE
Plugin Help!!!

### ISSUE THREAD

**Issue by dan122334455** [plamoni/SiriProxy#188]
When i add a plug in via path, not via git://..., i always get an error saying it cant find the file.  Then when i cd to the folder it has the error in, i add the plugin folder i download there next to the siriproxy-example.  Then when I update siriproxy in the siriproxy directory, it deletes it and moves back a folder (directory).  and i get the same error as if i didnt ever add it.  I tried bundling, siriproxy update, bundle install, gem install... Nothing works.  Please help!!

**Comment by dan122334455** [comment]
I am messing around with it and now i get an error that the cora.git is not checked out. It says to bundle install, i do, then i get the same error

**Comment by AndrewRayCode** [comment]
FYI: https://github.com/plamoni/SiriProxy/wiki/Plugin%20Developer%20Guide

The cora message happens if you do a `rake install` without doing a `siriproxy bundle` after. Please close this ticket
