### ISSUE TITLE
Add Plugin Error

### ISSUE THREAD

**Issue by SONY5614** [plamoni/SiriProxy#193]
DOWNLOAD Twitter Plugin
https://github.com/netpro2k/SiriProxy-twitter
copy SiriProxy/plugins and
~/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/plugins

add Twitter config.yml
- name: 'Twitter'

path: './plugins/siriproxy-twitter'
consumer_key: "XXXXXXXXXXXXXXXX" 
consumer_secret: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
oauth_token: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" 
oauth_token_secret: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

Save

$ cd Desktop/SiriProxy
$ siriproxy update
/Users/XXX/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych.rb:154:in `parse': (/Users/XXX/.siriproxy/config.yml): couldn't parse YAML at line 12 column 7 (Psych::SyntaxError)
    from /Users/XXX/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych.rb:154:in`parse_stream'
    from /Users/XXX/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych.rb:125:in `parse'
    from /Users/XXX/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych.rb:112:in`load'
    from /Users/XXX/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/psych.rb:229:in `load_file'
    from /Users/XXX/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:143:in`parse_options'
    from /Users/XXX/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:33:in `initialize'
    from /Users/XXX/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/bin/siriproxy:6:in`new'
    from /Users/XXX/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/bin/siriproxy:6:in `<top (required)>'
    from /Users/XXX/.rvm/gems/ruby-1.9.3-p0@SiriProxy/bin/siriproxy:19:in`load'
    from /Users/XXX/.rvm/gems/ruby-1.9.3-p0@SiriProxy/bin/siriproxy:19:in `<main>'

**Comment by SONY5614** [comment]
New Error
[Info - Plugin Manager] Processing 'Tweet test '
[Info - Plugin Manager] Processing plugin #SiriProxy::Plugin::Twitter:0x000001011c84f8
[Info - Plugin Manager] Matches (?i-mx:tweet (.+))
[Info - Plugin Manager] Applicable states:
[Info - Plugin Manager] Current state:
[Info - Plugin Manager] Matches, executing block
[Info - Plugin Manager] Say: Here is your tweet:
/Users/XXX/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/plugin_manager.rb:56:in respond': undefined methodgenerate_siri_utterance' for #SiriProxy::PluginManager:0x000001008b34d0 (NoMethodError)
from /Users/XXX/.rvm/gems/ruby-1.9.3-p0@SiriProxy/bundler/gems/cora-1edcfb9073d5/lib/cora/plugin.rb:64:in say'
from /Users/XXX/.rvm/gems/ruby-1.9.3-p0@SiriProxy/bundler/gems/SiriProxy-Twitter-ea11734bf0a9/lib/siriproxy-twitter.rb:18:inblock in class:Twitter'
from /Users/XXX/.rvm/gems/ruby-1.9.3-p0@SiriProxy/bundler/gems/cora-1edcfb9073d5/lib/cora/plugin.rb:47:in instance_exec'
from /Users/XXX/.rvm/gems/ruby-1.9.3-p0@SiriProxy/bundler/gems/cora-1edcfb9073d5/lib/cora/plugin.rb:47:inblock (2 levels) in process'
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.

**Comment by earlbalai** [comment]
Same issue here

**Comment by earlbalai** [comment]
well, top one. I haven't gotten past the yaml parse error

**Comment by blipszyc** [comment]
@earlbalai you need to make sure the spacing and alignment is correct.  Make sure there is a space between the "-" and "name" and make sure "path" or "git" line up underneath.

**Comment by earlbalai** [comment]
Got it Thank you for your help
