### ISSUE TITLE
SiriProxy out side of your WiFi network

### ISSUE THREAD

**Issue by ic0dex** [plamoni/SiriProxy#194]
Hey guys I just want to know if anyone has tried VPN/PPTP set up and if it worked, did SiriProxy connect to the server?

**Comment by muhkuh0815** [comment]
sure, np

edit: if your router doesnt support  GRE forwarding for port 47, you need to use L2TP

**Comment by dan122334455** [comment]
how would you do this?  And will it cost money to use a server, or do you create your own for free? Also, how will you do this in ubuntu?

**Comment by muhkuh0815** [comment]
no idea about ubuntu, but there is an app for that -> google -> http://lmgtfy.com/?q=ubuntu+vpn+server   :-)

you can make a pptp one with a few lines of code, l2tp should be a few lines more, but never tried it.

edit. should be absolutly free if you write the lines by yourself, if you want some gui with buttons they would probably cost some $

**Comment by dan122334455** [comment]
can you please give me the code? i dont have any clue what to even start with! and funny link....

**Comment by dcinzona** [comment]
I was able to accomplish this by using DNSMasq as my dhcp server and my DNS server.  When I VPN in, my siriproxy server (dnsmasq) assigns the IP to the vpn'ed device and the DNS settings. 
Works beautifully.

**Comment by blipszyc** [comment]
Does anyone know if I need to rerun the gencerts command after changing the port #?
