### ISSUE TITLE
Error initiating SiriProxy with required gem installed.

### ISSUE THREAD

**Issue by gotnull** [plamoni/SiriProxy#195]
I am using the following plugin:

https://github.com/toddtreece/siriproxy-arduino

I've followed the README and installed all the required gems.

I then execute: `siriproxy update` and it works just fine. It's recognising the new plugin added to my `~/.siriproxy/config.yml`

I noticed that it displayed the following after I did the update:
=== Bundling ===
Fetching source index for http://rubygems.org/
Using rake (0.9.2.2)
etc, etc

But I don't see `scrapi` listed in there. So it looks like that's the reason it's not loading the required gem when I run the server.

I then run `rvmsudo siriproxy server` as per usual.

However, when I hold the HOME button to initiate Siri I get the following error about the `scrapi` gem not being loaded.

I installed `scrapi` by executing the following command:

`gem install scrapi`

It installed correctly just like other gems I've installed in the past, so I'm not sure why it's complaining that it can't be loaded:

fulvio@fulvio-virtual-machine:~/Projects/SiriProxy$ rvmsudo siriproxy server
Starting SiriProxy on port 443..
Create server for iPhone connection
start conn #, @zip_stream=#Zlib::Deflate:0x87e059c, @consumed_ace=false, @name="iPhone", @ssled=false>
/home/fulvio/Projects/SiriProxy/plugins/siriproxy-arduino/lib/siriproxy-arduino.rb:7:in require': `cannot load such file -- scrapi (LoadError)`

**Comment by JBX028** [comment]
I have the same issue with an other gem (httparty). I have install the gem a bit differently using "rvmsudo" but like you, i can see the gem installed by executing the command "gem list"

I will probably ask the question in the chat room later today and put the answer here if i have the luck to find someone able and ready to help.

**Comment by gotnull** [comment]
@JBX028 Yeah, I can also see the gem listed and I also get the same problem with httparty, scrapi, etc.

**Comment by gotnull** [comment]
@JBX028 Did you ever get an answer about the missing gem issue?

**Comment by JBX028** [comment]
@rakusu Well there is probably a need to put new dependencies into the gemfile but based on the different plugins, i do not see the gems declared anywhere else. I had no time to go to the chat room yesterday but i will do it tonight....assuming nobody give the answers here before.

**Comment by gotnull** [comment]
Adding "scrapi" to the plugins .gemspec file fixed the missing gem issue I was having.
