### ISSUE TITLE
Gemcerts issue

### ISSUE THREAD

**Issue by LouisGhijselings** [plamoni/SiriProxy#196]
macbook-pro-15-van-louis-ghijselings-2:plamoni-SiriProxy-5ee281c louisghijselings$ rvmsudo gem install rake bundler
Password:
Successfully installed rake-0.9.2.2
Successfully installed bundler-1.0.21
2 gems installed
Installing ri documentation for rake-0.9.2.2...
Installing ri documentation for bundler-1.0.21...
Installing RDoc documentation for rake-0.9.2.2...
Installing RDoc documentation for bundler-1.0.21...
macbook-pro-15-van-louis-ghijselings-2:plamoni-SiriProxy-5ee281c louisghijselings$ rake install
siriproxy 0.3.0 built to pkg/siriproxy-0.3.0.gem
siriproxy (0.3.0) installed
macbook-pro-15-van-louis-ghijselings-2:plamoni-SiriProxy-5ee281c louisghijselings$ mkdir ~/.siriproxy
mkdir: /Users/louisghijselings/.siriproxy: File exists
macbook-pro-15-van-louis-ghijselings-2:plamoni-SiriProxy-5ee281c louisghijselings$ cp ./config.example.yml ~/.siriproxy/config.yml
macbook-pro-15-van-louis-ghijselings-2:plamoni-SiriProxy-5ee281c louisghijselings$ siriproxy gencerts
-bash: siriproxy: command not found
macbook-pro-15-van-louis-ghijselings-2:plamoni-SiriProxy-5ee281c louisghijselings$ 

This is what is got. What is going wrong here?

**Comment by James-Huffman** [comment]
make sure you have the latest version of openssl installed. i found a good site by doing a simple google search on how to do this using macports. I think the current version is 1.0.0e. Once I updated this I have had no problems with siriproxy.

**Comment by James-Huffman** [comment]
if you have macports installed simply type this, restart terminal (or your equivalent, i run a mac) and you should be good to go.

$ sudo port sync; sudo port selfupdate; sudo port install openssl

**Comment by LouisGhijselings** [comment]
No, no difference

macbook-pro-15-van-louis-ghijselings-2:~ louisghijselings$ sudo port sync
macbook-pro-15-van-louis-ghijselings-2:~ louisghijselings$ sudo port selfupdate
--->  Updating MacPorts base sources using rsync
MacPorts base version 2.0.3 installed,
MacPorts base version 2.0.3 downloaded.
--->  Updating the ports tree
--->  MacPorts base is already the latest version

The ports tree has been updated. To upgrade your installed ports, you should run
  port upgrade outdated
macbook-pro-15-van-louis-ghijselings-2:~ louisghijselings$ sudo port install openssl
--->  Computing dependencies for openssl
--->  Cleaning openssl
macbook-pro-15-van-louis-ghijselings-2:~ louisghijselings$ cd /Users/louisghijselings/Desktop/plamoni-SiriProxy-5ee281c 
macbook-pro-15-van-louis-ghijselings-2:plamoni-SiriProxy-5ee281c louisghijselings$ siriproxy gencerts
-bash: siriproxy: command not found
macbook-pro-15-van-louis-ghijselings-2:plamoni-SiriProxy-5ee281c louisghijselings$
