### ISSUE TITLE
Not working after going to new wifi

### ISSUE THREAD

**Issue by shameer99** [plamoni/SiriProxy#197]
i went to another wifi changed dns on my iphone and changed dnsmasq.config but when it starts the server my iphone doesnt connect

**Comment by plamoni** [comment]
It won't work outside your network.

On Sat, Dec 17, 2011 at 12:45 PM, shameer99 <
reply@reply.github.com

**Comment by shameer99** [comment]
Huh?!? I just figured it out myself. All I had to do is type killall
named and it works!! Maybe you read wrong I am at a friends house and
have my laptop and my phone on the same wifi

Sent from my iPhone
Muhammad Shahab
Stay Hungry Stay Foolish

On Dec 17, 2011, at 2:47 PM, Pete
reply@reply.github.com
wrote:
