### ISSUE TITLE
Issue after Starting

### ISSUE THREAD

**Issue by DasFx-zz** [plamoni/SiriProxy#198]
Hi All

After starting siriproxy and activate Siri this comes up.

Server-Security-3:bin Markus$ rvmsudo ./siriproxy server
Starting SiriProxy on port 443..
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x93a530 @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x93a468>, @zip_stream=#Zlib::Deflate:0x93a42c, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x1963e98 @manager=#<SiriProxy::PluginManager:0x93a1d4 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x1963d80 @signature=4, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x1963ca4>, @zip_stream=#Zlib::Deflate:0x1963c90, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x19623b8 @manager=#<SiriProxy::PluginManager:0x196390c @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x194cfe0 @signature=5, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x194c9b4>, @zip_stream=#Zlib::Deflate:0x194c98c, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x194bca8 @manager=#<SiriProxy::PluginManager:0x194c428 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x194bb2c @signature=6, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x194b974>, @zip_stream=#Zlib::Deflate:0x194b960,

dnsmasq ist setup with correct IP and adress ( i think so)

dig guzzoni.apple.com @10.0.0.101

; <<>> DiG 9.6.0-APPLE-P2 <<>> guzzoni.apple.com @10.0.0.101
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 29313
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;guzzoni.apple.com.     IN  A

;; ANSWER SECTION:
guzzoni.apple.com.  0   IN  A   10.0.0.101

;; Query time: 1 msec
;; SERVER: 10.0.0.101#53(10.0.0.101)
;; WHEN: Sun Dec 18 15:42:05 2011
;; MSG SIZE  rcvd: 51

 nslookup guzzoni.apple.com
Server:     10.0.0.138
Address:    10.0.0.138#53

Non-authoritative answer:
guzzoni.apple.com   canonical name = origin.guzzoni-apple.com.akadns.net.
origin.guzzoni-apple.com.akadns.net canonical name = reg1.guzzoni-apple.com.akadns.net.
Name:   reg1.guzzoni-apple.com.akadns.net
Address: 17.174.4.4

But nothing happend.

Any Hint?

**Comment by s00500** [comment]
Same Problem PLS HELP
