### ISSUE TITLE
Abort Trap

### ISSUE THREAD

**Issue by jpipas** [plamoni/SiriProxy#20]
Getting this error when trying any Siri Command:

```
Assertion failed: (e > 0), function SslContext_t, file ssl.cpp, line 162.
Abort trap
```

Wondering if it has to do with openssl ?

**Comment by plamoni** [comment]
Probably. Are there other errors leading up to it? or other log entries that look relevant? 

We sometimes see openssl errors when you accidentally loop the connection back on itself due to a DNS problem.

**Comment by jpipas** [comment]
The server output looks "normal" ... a bunch of `[Info - iPhone]` 's and some FinishSpeech - but right after this abort is thrown.

Any direction on looking into openssl to investigate a bit further?  Is there a standard log file somewhere?

**Comment by jpipas** [comment]
It was a dnsloop that was causing it... flushing cache and fixing my network did the trick... rock on :)
