### ISSUE TITLE
help needed in installing siriproxy on synology DS110j..

### ISSUE THREAD

**Issue by carthique** [plamoni/SiriProxy#200]
I am trying to run siriproxy on my synology NAS. I have setup ipkg and ruby, but "rake install" is throwing this error
HomeDisk> rake install
(in /root/SiriProxy)
rake aborted!
no such file to load -- bundler/gem_tasks
/root/SiriProxy/Rakefile:3:in `require'
(See full trace by running task with --trace)
HomeDisk> 

Please guide me with how to install siriproxy on a synology NAS. I saw dcinzona mention he has it setup successfully. Please help.

Thanks and Regards 
Karthik

**Comment by 3x3cut0r** [comment]
u have to activate rvm first:
[[ -s "/usr/local/rvm/scripts/rvm" ]] && . "/usr/local/rvm/scripts/rvm"

follow this thread: https://github.com/plamoni/SiriProxy/issues/137
i'm fighting with my ds-712+ and siriproxy too ^^
