### ISSUE TITLE
Rake Install Problem

### ISSUE THREAD

**Issue by dlabrie** [plamoni/SiriProxy#202]
Hello,

I made a fresh install of an ubuntu machine, but I'm now stuck on this error when I'm trying to execute the rake install command

root@ubuntu:/home/SiriProxy# rake install
(in /home/SiriProxy)
rake aborted!
no such file to load -- bundler/gem_tasks
/home/SiriProxy/Rakefile:3:in `require'
(See full trace by running task with --trace)
root@ubuntu:/home/SiriProxy# 

And here's the code when I do --trace

root@ubuntu:/home/SiriProxy# rake install --trace
(in /home/SiriProxy)
rake aborted!
no such file to load -- bundler/gem_tasks
/home/SiriProxy/Rakefile:3:in `require'
/home/SiriProxy/Rakefile:3
/usr/lib/ruby/1.8/rake.rb:2383:in`load'
/usr/lib/ruby/1.8/rake.rb:2383:in `raw_load_rakefile'
/usr/lib/ruby/1.8/rake.rb:2017:in`load_rakefile'
/usr/lib/ruby/1.8/rake.rb:2068:in `standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:2016:in`load_rakefile'
/usr/lib/ruby/1.8/rake.rb:2000:in `run'
/usr/lib/ruby/1.8/rake.rb:2068:in`standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:1998:in `run'
/usr/bin/rake:28
root@ubuntu:/home/SiriProxy# 

I tried to achieve the rvm use 1.9.3 --default command, but still doesn't work... :/

Any ideas ?

**Comment by shameer99** [comment]
try rvm use 1.9.3
without --default

**Comment by dlabrie** [comment]
Still not working

**Comment by shameer99** [comment]
whats the https://a248.e.akamai.net/assets.github.com/images/icons/emoji/3.png?v5

**Comment by dlabrie** [comment]
root@ubuntu:/home/dominick# cd SiriProxy/
root@ubuntu:/home/dominick/SiriProxy# rake install
(in /home/dominick/SiriProxy)
rake aborted!
no such file to load -- bundler/gem_tasks
/home/dominick/SiriProxy/Rakefile :3 :in `require'
(See full trace by running task with --trace)
root@ubuntu:/home/dominick/SiriProxy#

**Comment by shameer99** [comment]
try to killall ruby then rvm use 1.9.3 --default and then rake install

**Comment by dlabrie** [comment]
root@ubuntu:/home/dominick/SiriProxy# killall ruby
ruby: no process found
root@ubuntu:/home/dominick/SiriProxy# rvm use 1.9.3 --default
Using /usr/share/ruby-rvm/gems/ruby-1.9.3-p0
root@ubuntu:/home/dominick/SiriProxy# rake install
(in /home/dominick/SiriProxy)
rake aborted!
no such file to load -- bundler/gem_tasks
/home/dominick/SiriProxy/Rakefile: 3:in `require'
(See full trace by running task with --trace)
root@ubuntu:/home/dominick/SiriProxy#

**Comment by kartheeknagasuri** [comment]
still facing the problem? if solved please let me know how to solve this. m facing the same issue.

**Comment by dlabrie** [comment]
I'm still facing the problem....

**Comment by dlabrie** [comment]
I figured out how to fix the issue....

just do rvmsudo gem install rake bundler

**Comment by kartheeknagasuri** [comment]
Thanks for your reply. Will try and let u know the results...!
