### ISSUE TITLE
String via TCP/IP

### ISSUE THREAD

**Issue by mrcatnesta** [plamoni/SiriProxy#203]
Let me preface this with, I do not program in ruby.
All that I'm looking for is a simple way to send voice commands, as a string, (example "testing string") to an ip device (that I am familiar with programming). I will parse the string in the code for the ip device and handle it from there.

I have looked over the few examples in the plugins page that communicate with ip devices, however I haven't seen a solid example that explains how to do this. 

Please help show me the way. It will be much appreciated.

**Comment by mrcatnesta** [comment]
I am willing to pay for this small amount of code. 
OR
If someone will point me in the right direction as far as learning materials.
I really don't have the time to learn another language, but if that's what I must do.

**Comment by mrmosconi** [comment]
I do this in my plugin: https://github.com/mrmosconi/siriproxy-tivo

**Comment by mrmosconi** [comment]
Any error messages? You can decouple it from siriproxy and try running standalone to isolate the error.

**Comment by mrcatnesta** [comment]
I pulled my previous post as I have completely scraped that method of accomplishing communication with my basic stamp. I am now coming up with a new plan. I'll keep you posted, and start a new issue if I seem to venture away from ip communication. 
Thanks for the help guys!
