### ISSUE TITLE
Time of instantiation of regexes in plugin .rb files...

### ISSUE THREAD

**Issue by rlmalisz** [plamoni/SiriProxy#205]
This is probably painfully obvious to everyone else, but I am pretty new to Ruby, and am fighting my way through coding up my first plugin.  I had stuff working fairly brute-force, but was trying to get to something more extensible.  I am trying to build up regular expressions during initialization, and then use them in "listen_for" constructs.  Which works not at all.

At first, I assumed I was up against variable scoping issues, but I'm don't think that's it.  Are the regular expressions for "listen_for" getting precompiled or something?  When things die, it's obvious that the expansion of the variables in the regular expressions is basically "nil".

Is this just life, or is there a way to have these recomputed, the expressions treated as volatile....?

--Richard

**Comment by benlangfeld** [comment]
You're really going to have to provide some examples of what you're trying to achieve here. One line of code speaks a thousand words ;)

**Comment by rlmalisz** [comment]
As I attempted to eliminate scoping issues, the variables in question have been attr_accessors, instance variables, and globals.  They are currently (ugh) globals, but none of that made any difference.  

class SiriProxy::Plugin::Vera < SiriProxy::Plugin
  # attr_accessor :url
  # attr_accessor :switch_light
  # attr_accessor :set_level
  # attr_accessor :rooms
  # attr_accessor :room_regex
  # attr_accessor :current_room
  def initialize(config = {})
    $url = config["url"]
    $switch_light = config["switch_light"]
    $set_level = config["set_level"]
    # so we'll try to set up a hash of our configuration
    $rooms = {
      "office"=>{
        "name"=>"Richards office",
        "lights"=> { "overhead"=>"15" },
        "dimmers"=>{}
      },
      "studio"=>{
        "name"=>"Lindas studio",
        "lights"=>{ "overhead"=>"34" },
        "dimmers"=>{ "overhead"=>"34" }
      },
      "entry"=>{
        "name"=>"Entry hallway",
        "lights"=>{ "overhead"=>"16" },
        "dimmers"=>{ "overhead"=>"16" }
      }
    }
    # build up the room regex
    keys = $rooms.keys
    $room_regex = "("
    for key in 0...keys.length
      puts "adding #{keys[key]}"
      $room_regex += keys[key]
      $room_regex += "|"
    end
    # lose the trailing "|"
    $room_regex.chop!
    $room_regex += ")"
    $current_room = nil
    #if you have custom configuration options, process them here!
  end

In the log/dump that goes by, it's pretty clear that $room_regex has the expected value--or at least, it did when it was either an instance variable or a attr_accessor for "self"

But when we hit the very next thing in the file (when I say "current room <whatever>"), the log log shows that the expression was matched, but $room_regex evaluated to nil:

  # context setter
  listen_for /current room.*#{$room_regex}/i do |cur_room|
    $cur_room = cur_room
    say "Vera context is now #{$rooms[cur_room]["name"]}"
    request_completed
  end

I can get by this (I think) by doing a match inside the body of the listen_for, since when I've used puts to dump the $room_regex in there, it's non-nil.  I was just very surprised that "initialize" already seemed to be too late to make this work.

--Richard
