### ISSUE TITLE
Create delays between words ?

### ISSUE THREAD

**Issue by RayTrace77** [plamoni/SiriProxy#206]
Hi There,

First off, congrats to Plamoni for making this possible.

Iv'e got SiriProxy up and running successfully on a Ubuntu VM, work's fine apart from the odd occasion in which it stops at "FinishedSpeech", then have to stop it and retry.

I had heard of Ruby but never seen it until I setup SiriProxy, now learning the very few basics I wanted to create something else.

I wanted to create a delay(around 1-2 seconds) between word's that Siri says. I know Apple have done it.

If you ask Siri, "What's your favorite color", and let it get a awnser, it will start off saying:

   "My favorite color is... well, I"     <-------when it says "is..." there is like a 1 or 1.5 second pause. Is there anyway to replicate this ?

I would start out with something like this:

listen_for /testing speech delay/i do
  say "My favorite color is... well, I don't know how to say it in your language"

request_completed
end
end

but ofcourse it does not have the same delay time as the real one.

```
 NOTE:
 One thing I did notice was, the three dots "..." have a ever so slightly different sized space between each dots on the real one. Which I cant seem to replicate on my one.
```

Is there anyone who knows how to do this ?

Kind Regards,

Ray

**Comment by muhkuh0815** [comment]
try

say "My favorite color is... well, I don't know how to say it in your language", spoken: "My favorite color is, , , well, I don't know how to say it in your language"

**Comment by RayTrace77** [comment]
Wow, quick reply, thanks, will give it a shot now

**Comment by RayTrace77** [comment]
Hmm, tried that but didn't work, theres still no delay time, i've tried with   :    and  -   but no luck either, also tried with double spaces but nothing.

**Comment by muhkuh0815** [comment]
then try it with just 1   ","  in the spoken line, so you get at least the normal delay.

or try it with 2 say lines and  some sort of delay (dunno the ruby code for a pause)

**Comment by RayTrace77** [comment]
Yeah tried that yesterday but no luck,

I found the "sleep(0.9)" command which makes the entire command sleep but this cannot be injected between words(not in a way that I know of)

so if I have something like this

listen_for /keyboard/i do
  say "My favorite color is... well, I don't know how to say it in your language"
        sleep(10)
  say "Testing delay time"

request_completed
end
end

that makes the sleep command work but when you say "keyboard" it makes siri "spin" for 10 seconds before it even starts saying "My favorite colo............"

Not sure on this one.

I saw a previous post about this where Plamoni replied saying we would need to "spawn a new thread" and make that sleep but have no clue on what that is.

**Comment by RayTrace77** [comment]
Hmmm, got a slightly different problem i'm trying to overcome and it's driving me mad because I had it working yesterday.

I'm trying to get it so that when you something like "media player", it just opens a .mp3 or .wav file, then says "Ok, Playing"

I installed "mplayer", using "sudo apt-get install mplayer" which worked fine.

if I open up a terminal prompt and type something like   mplayer /home/ray/Downloads/eminem.mp3

it works and plays the file fine within terminal.

I put this into a ruby script yesterday and it worked but now it doesn't the code im using is:

listen_for /media player/i do
  say "Opening File"
    mplayer /home/ray/Downloads/eminem.mp3
  say "Playing File"

request_completed
end
end

it just comes back saying "unknown regexp options - kha (SyntaxError)

been trying for hours to get it working, muhkuh0815, don't suppose you know this one ?, or anyone else?

Kind Regards,

Ray

**Comment by mrmosconi** [comment]
Put single quotes around the path after mplayer ...
