### ISSUE TITLE
"siriproxy" command doesn't work

### ISSUE THREAD

**Issue by umbi98** [plamoni/SiriProxy#207]
when I'm going to insert the siriproxy command in my Mac, it says it doesn't exists. So, I've tried to drag in the terminal the file gen-certs where it's in the finder and it says:
Creating CA directory
Generating 'SiriProxyCA' CA request
Self-signing 'SiriProxyCA' CA
Generating guzzoni.apple.com certificate request
Generating 'SiriProxyCA' CA request
Generating guzzoni.apple.com certificate
Removing passphrase from guzzoni.apple.com key
Cleaning up...
mv: rename /tmp/newcert.pem to /Users/umbertodevito/.siriproxy/server.passless.crt: No such file or directory
mv: rename /tmp/siriCA/cacert.pem to /Users/umbertodevito/.siriproxy/ca.pem: No such file or directory
## Done! (For details on any errors, check '/Users/umbertodevito/.siriproxy/cert.log')

Please install /Users/umbertodevito/.siriproxy/ca.pem onto your phone!
(Note: You can do this by emailing the file to yourself)

If you wanna help me, I can send you cert.log file. thanks ;)

**Comment by terriblybored** [comment]
Have you installed ruby yet and followed the instructions in the readme included? It looks like your ruby install isn't working properly, as siriproxy requires ruby to run.
