### ISSUE TITLE
Grab Siri Output

### ISSUE THREAD

**Issue by ethernet8023** [plamoni/SiriProxy#209]
There seems to be no way to intercept the audio file that Siri recorded. If I'm wrong, please point me in the right direction.

**Comment by terriblybored** [comment]
It should theoretically be possible, since the decrypted audio packets do pass through your proxy.

**Comment by ethernet8023** [comment]
Good point. Do you know where in the source code it sends the audio files to guzzoni.apple.com and expects a response? I'm quite new to this, but I plan to make Siri use google's voice recognition instead.

**Comment by terriblybored** [comment]
The audio is definitely there. I'll be looking at grabbing some of it
later. It should be encoded in speex. Maybe you could look at the
original applidium files for audio. I think they built everything
there.

On 29 Dec, 2011, at 1:46 AM, aerobit
reply@reply.github.com
wrote:

**Comment by terriblybored** [comment]
Are you still working on using google's voice recognition?

**Comment by ethernet8023** [comment]
Yes, yes I am. I'm actually still thinking my way around this, because I have no idea how to make this work.

**Comment by terriblybored** [comment]
I'm starting to work on it now too. Shouldn't be that hard. The packets are being sent, and are even recorded in log.

**Comment by ethernet8023** [comment]
Yeah, the only problem is that you'd have to rewrite Siri unless you used apple's logic as well. Unless the logic is client-side, which I doubt.

**Comment by terriblybored** [comment]
I don't think the logic is client side. I was more interested in the transcription though. I can't decode the speex packets I'm capturing though. I'm looking at https://github.com/applidium/Cracking-Siri/blob/master/speexDec.m too, but I can't read objective C.

**Comment by ethernet8023** [comment]
Well, as long as you have ffmpeg, you can just ffmpeg speex to flac, then go

require 'rest_client'
require 'json'
a = FLAC file here!
r = RestClient.post 'https://www.google.com/speech-api/v1/recognize?lang=en-US', a,
                    :content_type => 'audio/x-flac; rate=16000'
if j = JSON.parse(r)
result = {j['hypotheses'].first['utterance']}
end

EDIT: This may be of interest to you... http://rubydoc.info/github/moumar/ruby-ogginfo/master/Ogg/Codecs/Speex

**Comment by terriblybored** [comment]
Have you managed to do so? I'm unable to actually do anything with my
speex data. I've extracted them from the packets and concatenated them
into a file. I believe it requires some processing before I feed it to
a decoder, as all I get are messages that it is corrupt, and a bad
output.

On 31 Dec, 2011, at 6:36 AM, aerobit
reply@reply.github.com
wrote:

**Comment by ethernet8023** [comment]
No, not yet. I'm actually learning ruby, just for this.... are you maintaining a fork of this project with google speech recognition?

**Comment by terriblybored** [comment]
No. Mine isn't for that. I'm learning ruby for this too. :)

On 31 Dec, 2011, at 6:48 AM, aerobit
reply@reply.github.com
wrote:

**Comment by ethernet8023** [comment]
It's quite hard XD How are you capturing the packets?

**Comment by terriblybored** [comment]
Modify connection.rb. Is there another way to communicate where I can attach files?

**Comment by ethernet8023** [comment]
not as far as I know. What are the exact errors you're getting? Mind posting a sample intercepted speex file? I don't have a 4s so I can't test it :C

**Comment by terriblybored** [comment]
It's just a stream of packets concatenated together. I'm not getting a
playable file after conversion. The official decoder tells me it's not
a valid speex file too (probably because the headers are thrown out)
Could we exchange emails privately? It'll be easier to send files. You
could message me in my profile.

On 31 Dec, 2011, at 7:16 AM, aerobit
reply@reply.github.com
wrote:

**Comment by ethernet8023** [comment]
I would, but it says that you have not provided an email.

**Comment by terriblybored** [comment]
Okay. Threw it out there for a while.

On 31 Dec, 2011, at 7:21 AM, aerobit
reply@reply.github.com
wrote:

**Comment by kelvl** [comment]
anyone figured this out yet? I seem to be able to extract the speech packets using sampledec from crackingSiri but i don't seem to be able to play it back. According to the docs the audio parameters are:

Audio data flows in as speex_wideband by default. You can decompress using the speex library. Managed to uncompress using the following parameters :
- framesize = 320
- packet size = 139 (For some reason the audio packets in the plist are 695 bytes long, and 695 = 139*5, so they probably cram 5 speex packets in each plist)
- sample rate is 16Khz

**Comment by terriblybored** [comment]
I've gotten playback. You need to use speex libraries to decode, and
then convert the raw result using sox (or any other tool of choice) to
something playable in any standard player.

On 8 Jan, 2012, at 5:21 PM, kelvl
reply@reply.github.com
wrote:

**Comment by kelvl** [comment]
what kind of encoding does speex libraries output? 

I have tried using 

sox -r 16000 -e XXX out.raw out.wav

but I can't seem to convert it to anything that is playable.

**Comment by terriblybored** [comment]
It should be raw. I didn't use any files from crackingSiri, as the
program written in C wasn't suitable for conversion, and I didn't
bother to try compiling the Objective C version as I wasn't using a
Mac.

On 8 Jan, 2012, at 7:43 PM, kelvl
reply@reply.github.com
wrote:

**Comment by kelvl** [comment]
would you happen to have any code that you can share that allows the extraction from Siri stream and conversion from speex to raw and subsequently to wav?

**Comment by terriblybored** [comment]
Okay. When i get back to my computer, I'll send it to your email if
theres one in your github account. Code is very messy, and was used on
a Debian system with speex libraries. It converts the audio, queries
google for a transcription, prints result to screen, and then deletes
converted audio. Uses  modified version of SiriProxy to save audio,
C++ for conversion program, and a tiny script to call commands and
cleanup. Speex packets are separated with 10 nul characters when
written to file.

On 8 Jan, 2012, at 9:17 PM, kelvl
reply@reply.github.com
wrote:

**Comment by kelvl** [comment]
That would be really helpful thank you!

**Comment by ethernet8023** [comment]
Hey terriblybored, why don't you start a fork for this? :3

**Comment by terriblybored** [comment]
My code is super messy. It's embarrassing. :( thought this was a niche
thing too.

On 9 Jan, 2012, at 9:36 AM, aerobit
reply@reply.github.com
wrote:

**Comment by ethernet8023** [comment]
Oh, we don't care what your code looks like! It'd be awesome; I'd be happy to contribute and help clean up some code :)

**Comment by terriblybored** [comment]
Pushed in if you want to look at it. I'm not exactly actively working on it though. Other things to do this year. :(

**Comment by kelvl** [comment]
When you try playing back the audio samples dumped out from Siri (the flac files for example), does it sound distorted and playing faster than real time?

**Comment by terriblybored** [comment]
Nope, I don't get any such problem. I'll look into it sometime tonight.

On 9 Jan, 2012, at 11:16 AM, Kelvin Law
reply@reply.github.com
wrote:

**Comment by terriblybored** [comment]
They feel okay to me. However, if you have such a problem, it might be due
to the decoder program. Perhaps I made an error in decoding there?

**Comment by kelvl** [comment]
Yes, you are right! I believe it has to do with how i shuttled the packets from ruby into the decoder in C. 

I modified the ruby code to export unpacked packets in hex and took some of the code from speexDec.m to decode the speex and it's working fine now. Thanks!

**Comment by osousa** [comment]
Kelvi, can you tell us how you're exporting unpacked packets in hex?

**Comment by fluentfuture** [comment]
Thanks a bunch for referring me here!

I managed to run this forked siriproxy to do sound playback.

The decoder.cpp has a bug at the very end where it writes out the frame bytes to file. Instead of:

``` c
outFile.write((char*)output, frame_size);
```

it should have been:

``` c
outFile.write((char*)output, frame_size * sizeof(spx_int16_t));
```

After changing that, the playback worked fine.

Nice job guys!
