### ISSUE TITLE
Error - undefined method `each_slice'

### ISSUE THREAD

**Issue by dadiy** [plamoni/SiriProxy#21]
So I have everything setup and can successfully get a response to Test Siri Proxy,  however as soon as I ask a standard command like what time is it? I get the following - any idea anyone?

[Info - iPhone] Object: SpeechPacket
[Info - iPhone] Object: SpeechPacket
[Info - iPhone] Object: FinishSpeech
[Info - Guzzoni] Object: SpeechRecognized
[Recognized Speech] What time is it
[Info - Guzzoni] Object: AddViews
/usr/local/lib/ruby/gems/1.8/gems/CFPropertyList-2.0.17/lib/rbBinaryCFPropertyList.rb:237:in `charset_strlen': undefined method`each_slice' for #Array:0xb7cf32f0 (NoMethodError)
        from /usr/local/lib/ruby/gems/1.8/gems/CFPropertyList-2.0.17/lib/rbBinaryCFPropertyList.rb:442:in `string_to_binary'
        from /usr/local/lib/ruby/gems/1.8/gems/CFPropertyList-2.0.17/lib/rbCFTypes.rb:40:in`to_binary'
        from /usr/local/lib/ruby/gems/1.8/gems/CFPropertyList-2.0.17/lib/rbBinaryCFPropertyList.rb:549:in `dict_to_binary'
        from /usr/local/lib/ruby/gems/1.8/gems/CFPropertyList-2.0.17/lib/rbBinaryCFPropertyList.rb:549:in`map'
        from /usr/local/lib/ruby/gems/1.8/gems/CFPropertyList-2.0.17/lib/rbBinaryCFPropertyList.rb:549:in `dict_to_binary'
        from /usr/local/lib/ruby/gems/1.8/gems/CFPropertyList-2.0.17/lib/rbCFTypes.rb:238:in`to_binary'
        from /usr/local/lib/ruby/gems/1.8/gems/CFPropertyList-2.0.17/lib/rbBinaryCFPropertyList.rb:549:in `dict_to_binary'
        from /usr/local/lib/ruby/gems/1.8/gems/CFPropertyList-2.0.17/lib/rbBinaryCFPropertyList.rb:549:in`map'
         ... 22 levels...
        from /usr/local/lib/ruby/gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
        from ./siriProxy.rb:246:in`initialize'
        from start.rb:16:in `new'
        from start.rb:16
zlib(finalizer): the stream was freed prematurely.

**Comment by plamoni** [comment]
Hmm. You get this every time?

**Comment by netpro2k** [comment]
What plugins do you have active? Does it work if you disable all of them?

**Comment by dadiy** [comment]
plamoni No I dont get this everytime,  for example I can say "Send a Text" and siri will prompt me for "who" and I'll say a name and then although it gets the name correct it then crashes.  

Only plugin currently active is the testproxy.  And the only change I needed to make in siriProxy.rb was to change 
"require 'CFPropertyList'" to "require 'cfpropertylist'"

If it helps these are the versions Im running with -
[root@xxxxx sproxy]# ruby --version
ruby 1.8.6 (2007-03-13 patchlevel 0) [i686-linux]
[root@xxxxx sproxy]# gem list

**\* LOCAL GEMS ***

boxcar_api (1.0.2)
CFPropertyList (2.0.17)
crack (0.1.8, 0.1.6)
eventmachine (0.12.10)
hashie (0.2.2)
httparty (0.8.1, 0.5.2)
json (1.6.1)
libxml-ruby (2.2.2)
multi_json (1.0.3)
multi_xml (0.4.1)
oauth (0.4.3)
rake (0.9.2.2)
twitter (0.9.8)
twurl (0.6.1)
uuidtools (2.1.2)
yajl-ruby (0.7.7)

**Comment by plamoni** [comment]
This was reported with an old version of the code. Please resubmit the issue if it's still present in the latest code (along with steps to reproduce).
