### ISSUE TITLE
SiriProxy on iPhone 4

### ISSUE THREAD

**Issue by iosdeveloper** [plamoni/SiriProxy#211]
README states

You need to be using an iPhone 4S (or have a UDID you can sub in) in order to make use of SiriProxy.

So an iPhone 4 and UDID of an iPhone 4S will work? How?

**Comment by terriblybored** [comment]
Spire with SiriProxy is broken on default install. See my reponse on:

https://github.com/plamoni/SiriProxy/issues/210

**Comment by pfruh** [comment]
You might try the fork at https://github.com/westbaer/SiriProxy

It got a commit titled "Added session caching (useful for non-Siri devices.) 5435053b0c1cfd7f76e0e82f3e99de8fc8639b14 " which seems to do exactly what you want.
