### ISSUE TITLE
How to sub the UDID for a 4s one?

### ISSUE THREAD

**Issue by edsonaj** [plamoni/SiriProxy#212]
Hi, I already have the proxy running with my iphone 4s, but I would like to test it with my old iphone 4 and my ipod touch..... Where and how should I put the 4S UDID? I tried but I was unable to find the right way to do it.

Thank you.

**Comment by iosdeveloper** [comment]
I'd be also interested in that (#211).

**Comment by pfruh** [comment]
From what i read, it SHOULD save and share the auth-token stuff automatically after a 4S connected, but i don't have to possibility to test this (as i don't have one :( )

**Comment by edsonaj** [comment]
I tried and even if the 4S is connected I got a error when trying to use other non-4s device.

**Comment by mcdull** [comment]
I have tried on my ipod touch 4g.  It never connects to the proxy. Even I've install the certificates, the SSL never established.
When I try using the 4s, it says SSL connected to Phone and Apple server with streams of data.  But Siri keep telling sorry. Still a no go.  I am not sure if it is the matter of my network DNS server being forward to the proxy machine. Is siriproxy hard code the server IP so that it will always find apple server?

**Comment by terriblybored** [comment]
Spire with SiriProxy is broken on default install. Specifically, the SSL portion isn't configured properly.
See my response on:

https://github.com/plamoni/SiriProxy/issues/210

**Comment by pfruh** [comment]
You might try the fork at https://github.com/westbaer/SiriProxy

It got a commit titled "Added session caching (useful for non-Siri devices.) 5435053b0c1cfd7f76e0e82f3e99de8fc8639b14 " which seems to do exactly what you want.

**Comment by edsonaj** [comment]
Yeah I tried the fork from westbaer and it's working like a charm. Thank you.

**Comment by ghazis** [comment]
Hi I'm sorry but I'm a noob with a lot of this....just needed some help. I got the proxy server up and running but I only have an iPad 2 and no iPhone 4s. So how do I exactly try out this fork? Do I copy paste all of the text into the command line while the server is running? Thanks in advance.

**Comment by mcdull** [comment]
You need a 4S to get authenticated.  Either own by you or any other that uses your server.

**Comment by babylon558** [comment]
OK, is the thing that automatically takes the udid from a 4s is nice, but I have a 4s udid, but can't connect the phone, I beleive you just need to sub in the udid for the keys server.passless.crt, and server.passless.key, can anyone verify this?

**Comment by mcdull** [comment]
No.. it is not the UDID matter.  The token is given by Apple server every time a 4S is connected.  There is no way for you to make it up ... yet.

**Comment by babylon558** [comment]
if apple gives out the token what data is used to authenticate that it is a 4s if not the UDID

**Comment by mcdull** [comment]
I want to know 2...
But the protocol is not broken yet.

2012/3/7 babylon558
reply@reply.github.com:
