### ISSUE TITLE
Listen on a specific IP

### ISSUE THREAD

**Issue by NeilHanlon** [plamoni/SiriProxy#214]
How can I get siriproxy to only listen on a specific IP?

I know I can change the port, but :443 is used on my machine by HTTPS.. so, how can I tell it only to listen on one IP address instead of trying to allocate all of my IPs?

Thanks,
Neil

**Comment by terriblybored** [comment]
Haven't tried modifying my own install, but have you tried looking into (base siriproxy directory)/lib/siriproxy.rb ?

Try modifying this line:

line 19: EventMachine::start_server('0.0.0.0', $APP_CONFIG.port, SiriProxy::Connection::Iphone) { |conn|

and changing 0.0.0.0 to the IP address you want it to listen on.

**Comment by plamoni** [comment]
On my setup, I use port 2000 and have internal requests (from
192.168.2.0/24) destined for 443 rerouted to 2000 by iptables. This
kills two birds with one stone: it frees up 443 for https from the
outside world and it let's me run siriproxy as an unprivileged user
(making the setup more secure).

-Pete

Sent from my iPhone

On Dec 27, 2011, at 11:14 PM, Neil Hanlon
reply@reply.github.com
wrote:

**Comment by NeilHanlon** [comment]
That's a very good idea. I'll look into that option.

**Comment by plamoni** [comment]
Maybe this will help:

https://gist.github.com/1521378

-Pete
