### ISSUE TITLE
How do u use on 3g?

### ISSUE THREAD

**Issue by shameer99** [plamoni/SiriProxy#217]
in the video pete said that u could set up a vpn to do it but how?

**Comment by Bubelbub** [comment]
http://www.ketchup-mayo-senf.de/blog/-it-howto-set-up-a-linux-server-in-vmware-for-siriproxy

Search: Setting up VPN ( optional )

**Comment by shameer99** [comment]
how about a mac?

**Comment by Bubelbub** [comment]
I think it is the same with a little Difference :/

Or try http://www.bol.ucla.edu/services/vpn/pptp/docs/macosx.html

**Comment by shameer99** [comment]
that one just connects

**Comment by Bubelbub** [comment]
Oh, Sorry :/

Use this
http://www.maclive.net/sid/132

Or here, with iPhone Informations!
http://www.macstories.net/tutorials/how-to-set-up-a-vpn-server-on-your-mac-and-access-everything-remotely-with-an-iphone/
