### ISSUE TITLE
Problems with Dnsmasq

### ISSUE THREAD

**Issue by szomo** [plamoni/SiriProxy#22]
I'm having trouble getting dnsmasq to run , the ip address is always in use. 
I have followed the instructions carefully so yes i have updated the dnsmasq.conf file

At work i've got akamai using up port 443 for some reason i can't turn it off . However on my home laptop nothing is on 443 and i still always get :

dnsmasq: failed to create listening socket for 10.0.2.1: Address already in use

I've killed processes individually ,

i've run "sudo killall named" 

I'm trying to understand what im doing wrong here , my shared connection routes 10.0.2.1 just as mentioned in the video

**Comment by hjaltij** [comment]
Not sure if this will help but I had to add this to my config. (I'm not using WiFI sharing though so not sure if it's what's causing your issues)

listen-address=10.0.1.2

Where 10.0.1.2 is the address of my mac which I intend to use as a dns server.

**Comment by MrCloud** [comment]
Look at the end of this comment
https://github.com/plamoni/SiriProxy/issues/11#issuecomment-2836295

**Comment by szomo** [comment]
So basically , you set the path of the dns to your computer ip address on the router ?

**Comment by plamoni** [comment]
dnsmasq runs on TCP/UDP port 53, not 443. 

This means that you need to make sure you don't have another nameserver running. It's likely that there's an instance of Bind running on your Mac. Go to a terminal and type `sudo killall named` and that should resolve it.

**Comment by plamoni** [comment]
Afterwards, just restart dnsmasq and it should work properly.

**Comment by szomo** [comment]
all i have in my conf file is this 

address=/guzzoni.apple.com/10.0.2.1

im sharing my ethernet to wifi ( for testing )

below is the typical dance :

$ sudo killall named
$ sudo killall named
$ sudo killall named
No matching processes were found
$ sudo /opt/local/sbin/dnsmasq

dnsmasq: failed to create listening socket for 10.0.2.1: Address already in use
$ 

BTW I really appreciate the help on this board. i would consider myself far less experienced with this kinda thing but with everyones help its getting close and i can't wait to try some stuff out with this once its working.

**Comment by MrCloud** [comment]
could you run ifconfig and post the result for en1 ?

**Comment by szomo** [comment]
en1: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
    ether 60:33:4b:25:57:a5 
    inet 10.0.2.1 netmask 0xffffff00 broadcast 10.0.2.255
    inet6 fe80::6233:4bff:fe25:57a5%en1 prefixlen 64 scopeid 0x5 
    inet 169.254.25.49 netmask 0xffff0000 broadcast 169.254.255.255
    media: autoselect
    status: active

**Comment by szomo** [comment]
still struggling with this ... 

i only managed to get dnsmasq to work on 127.0.0.1 on my home laptop after killall named a few times and killall dnsmasq to be sure. I wasn't able to test because i literally had this work on the bus to work. with no network connection. 

Also i had my airport turned off before running dnsmasq , and then ran start.rb

tested Siri "test siri proxy" and something might have happened , because siri couldnt connect to the service ( which makes sense since my laptop wasnt connected to the net ) once i turned off wifi on my phone , siri worked ... so something was intercepted... 

i just feel like i might have fluked into something that may only work on my machine and randomly.

**Comment by jarques** [comment]
I ended up installing dnsmasq using homebrew (so brew install dnsmasq), and to start it with the proper config I used this command:

sudo /usr/local/Cellar/dnsmasq/2.57/sbin/dnsmasq --address=/guzzoni.apple.com/10.0.2.1

You can easily kill it with the above killall named (or use Activity Monitor.) This worked for me, so I didn't have to mess around with config files.

I think that IP only works if you're sharing your internet connection from your Mac to your iPhone. So you're pretty much connected via LAN and sharing that connection via WiFi.
