### ISSUE TITLE
Plugin craches siriproxy

### ISSUE THREAD

**Issue by fredskronk** [plamoni/SiriProxy#220]
Hello,

Ok. I'm a bit new to all this and to Ruby and I must be doing something wrong.
When editing the example file by just changing a listen_for and the response it all works fine. But as soon as I try to remove some example code and updates the server crashes every time theirs an incoming Siri request.

 I've done som PHP and Java in my days and acording to what I have read about Ruby on the net I should have done it all right. But, ah well.

This is the file I have at the moment. 

require 'cora'
require 'siri_objects'

class SiriProxy::Plugin::whensthebuscomming < SiriProxy::Plugin
    def initialize(config)
        #if you have custom configuration options, process them here!
    end

   listen_for /Where am I/i do
       say "How should I know."

```
   request_completed
```

   end
end

Any help would be appreciated.

**Comment by fredskronk** [comment]
Seems that the orum deleted my blanks. The code is a bit better looking then that :)

**Comment by terriblybored** [comment]
Perhaps you could copy over the error message?

**Comment by terriblybored** [comment]
Oh. Just a thought. Have you remembered to update config.yml with the new name of your plugin? That could be potential source of problems.

**Comment by terriblybored** [comment]
I'm just starting to learn Ruby too, but I think I read somewhere that class names must start with an uppercase letter. That might be something to look into too.

**Comment by fredskronk** [comment]
Ah. On the move right now but I'll check that as soon as I get home. 

Is there a log where I can see errors? The ones shown in the terminal is kind of broken up.

**Comment by mcdull** [comment]
can someone please tell me the correct step to replace code and add plugin? I am so confused the steps to be made if I want to make change to the git locally. would "rake install" + "siriproxy bundle" be enough for the change?

**Comment by mcdull** [comment]
One more question, should the content in  ~/.rvm/gems folder being cleaned first?

**Comment by fredskronk** [comment]
Found this video that describes how to edit the example. It's the one I've started from. 

http://www.youtube.com/watch?v=A48SGUt_7lw

Med Vänlig Hälsning / Regards
Fredrik Jonsson

Phone: +46 (0) 70 878 26 54
É-mail: fredrik@talmaskin.se
Blog: http://www.fredskronk.se/
