### ISSUE TITLE
git://github.com/chendo/cora.git (at master) is not checked out. Please run `bundle install` 

### ISSUE THREAD

**Issue by NeilHanlon** [plamoni/SiriProxy#221]
I've looked through the FAQ and all that stuff - none of that is the issue.

It was running just fine, but now it won't run at all.

Ruby isn't running any processes, no other errors. I can run bundle install fine, I've even done a bundle update to force it, still nothing.

bundle update log:

Updating git://github.com/chendo/cora.git
Fetching source index for http://rubygems.org/
Using rake (0.9.2.2)
Using libxml-ruby (2.2.2)
Using CFPropertyList (2.0.17)
Using geocoder (1.1.0)
Using cora (0.0.4) from git://github.com/chendo/cora.git (at master)
Using eventmachine (0.12.10)
Using uuidtools (2.1.2)
Using siriproxy (0.3.0) from source at /home/neil/siriproxy/SiriProxy
Using siriproxy-example (0.0.1) from source at ./plugins/siriproxy-example
Using bundler (1.0.21)
Your bundle is updated! Use `bundle show [gemname]` to see where a bundled gem is installed.

bundle install log:

Using rake (0.9.2.2)
Using libxml-ruby (2.2.2)
Using CFPropertyList (2.0.17)
Using geocoder (1.1.0)
Using cora (0.0.4) from git://github.com/chendo/cora.git (at master)
Using eventmachine (0.12.10)
Using uuidtools (2.1.2)
Using siriproxy (0.3.0) from source at .
Using siriproxy-example (0.0.1) from source at ./plugins/siriproxy-example
Using bundler (1.0.21)
Your bundle is complete! Use `bundle show [gemname]` to see where a bundled gem is installed.

**Comment by jayb1239** [comment]
have you tried a 'rake install' & 'siriproxy bundle' from within the SiriProxy directory?

**Comment by blipszyc** [comment]
Did you try to install a plugin?  If so, make sure the spacing and text lineup exactly like the examples in the .yaml file and then run "bin/siriproxy update" again.
