### ISSUE TITLE
Writing plugins?

### ISSUE THREAD

**Issue by ghost** [plamoni/SiriProxy#223]
Where is a good place to get started learning how to write plugins or edit the existing ones?  Amazing work so far.  I'm having a lot of fun.

**Comment by Bubelbub** [comment]
Ruby is easy to learning.
You are beginner in Scripting? Programming?

http://rubylearning.com/satishtalim/tutorial.html

For the Beginning you "must" use the example Plugin.
No Copy or so!
Modify it!

If you want a new "Speech Function", copy a "listen_for" Section (from listen_for ... to "end") und edit the Section.

But how i say: first read the Tutorials about Strings and more.

If you know, what i say and what i mean, you can send my a Message.
Then i can help you by developing new, cool Plugins :)

**Comment by ghost** [comment]
Thank you, I really appreciate it.  I will definitely be contacting you soon.

**Comment by Bubelbub** [comment]
Look!
We are Public :)
Earn Money <- Comming Soon =]

-> WeSpire
http://weblogit.net

But i teach you Scripting ;)

**Comment by ghost** [comment]
I wrote a simple script to say a few quotes from movies and things like that, I had a lot of fun with that.  I would like to learn how to parse information from the web and output it.  I am looking at this Nokogiri thing and it looks cool.  I want to learn how to use it.

**Comment by Bubelbub** [comment]
I know, it is German.
But the Code is English ;)

https://github.com/muhkuh0815/SiriProxy-TV/blob/master/lib/siriproxy-tv.rb

Look at line 92, 115, 122, 124 and Final 126 - 154.
Then you have a simple XML Parser.

But don´t copy the "Programming Style".
The Code needn´t double Parsing.
But he double Parsing the Programm.

Wtf!? :D

**Comment by ghost** [comment]
http://www.youtube.com/watch?v=AZtIEC_5oVI
http://www.youtube.com/watch?v=1LbmeDA_zLY

I figured out a few things on my own :)  Tell me what you think.

**Comment by Bubelbub** [comment]
Also the first Video is .... Shit :D
I don´t know what Reddit is.

But the Second is good ;)

In Both Videos you read URL :]
It is Easy, but for Beginner:
-> Good Job <- or how i say: "Good Work" ^^

Ah, a Tip: In the Videos the Text are too large! Siri speaks and speaks.
Ask Siri "normal" Questions (like Apple Questions, no Customs!).
They answer one or two ... Lines (?).

**Comment by AndrewRayCode** [comment]
https://github.com/plamoni/SiriProxy/wiki/Plugin%20Developer%20Guide

Please close this issue

**Comment by Bubelbub** [comment]
Lol DelvarWorld :D
He must not delete all Pages from Wiki!
The Plugin Page is away, too.

Also go away.
We saved all Sites and can make it Public ...

Also why you Mean he should delete all?

**Comment by Bubelbub** [comment]
Lol Sorry.
I miss your Text :D
Or i failed to think :D

You posted the Solution ^^
