### ISSUE TITLE
Starting SiriProxy on Port 443...

### ISSUE THREAD

**Issue by brendondelgado** [plamoni/SiriProxy#224]
Everything is working fine (this is on Ubuntu 11.10), and when I type in the last command "rvmsudo siriproxy server" (no quotes), it goes through fine, but then never get's past "Starting SiriProxy on Port 443..."

I've tried for the last 3 hours to figure out what is causing it and I can't for the life of me, figure out the problem.

Anyone mind helping me out a bit? I'm so close to getting this to work! 

Thanks!

**Comment by terriblybored** [comment]
Could you paste the error?

**Comment by jayb1239** [comment]
If your getting up to "Starting SiriPRoxy on Port 443..." and it stays there and doesn't exit then it would seem that the proxy is working and running and the issue is that connections aren't getting to it

**Comment by brendondelgado** [comment]
There is no error; thats the problem. I watched the long setup video that plamoni has on youtube and followed it to a T to make sure I did everything correctly and I did, but I noticed that when he wrote "rvmsudo siriproxy server" (no quotes), it said "Starting SiriProxy on Port 443..." and then a few seconds later a bunch of other text popped up in Terminal displaying the the information that is being sent to the Siri proxy server. When I type in "rvmsdo siriproxy server" (no quotes) it just sits at "Starting SiriProxy on Port 443..." and never says anything after that. I've let it be like that for 10 minutes hoping it's just taking a while to setup, but no luck.

If it is because it's running and the connections just aren't getting to it, is there anyway I can fix this problem? I'm new to Ruby, but I'm very interested and would like to learn more.

Thanks!

**Comment by jstockton** [comment]
By chance is your iPhone using 3g instead of using your wifi?

**Comment by brendondelgado** [comment]
It's on wifi. I've also changed the DNS IP to my computer's IP in Ubuntu and still nothing. Also, when I try Siri she just says "Sorry, but I can't take requests right now."

**Comment by jayb1239** [comment]
are you using a 4 or 4s

**Comment by brendondelgado** [comment]
I'm using a 4.

**Comment by jayb1239** [comment]
do you have auth data from a 4s?

**Comment by jayb1239** [comment]
and are you using Spire on the 4

**Comment by brendondelgado** [comment]
No, but my sister and mom both have 4S's so I can easily get it. I don't exactly know how, but I can google around to figure it out and yes I'm using Spire on the iPhone 4.

**Comment by jayb1239** [comment]
for the 4 to auth against the SiriProxy then you don't require the DNS, you would need your server address in spire though prefixed with https://

you also need a certificate for the server not guzzoni.apple.com as Spire isn't trying to verify guzzoni. so therefore for the purposes of using it to link with a 4 running Spire siriproxy gencerts is rendered useless and certificates have to be generated manually

**Comment by brendondelgado** [comment]
Hmm, so I think I just manually created the certificate, but it's not there, so I dunno what I missed. I typed in the follow that another user suggested in someone else's issue that seemed similar to mine:

(use any password and information you want)
openssl genrsa -des3 -out ca.key 4096
openssl req -new -x509 -days 365 -key ca.key -out ca.crt
openssl genrsa -des3 -out server.key 4096

(enter your ip or hostname in "common name" .. important! - if you want to use an iPhone 4S use "guzzoni.apple.com")
openssl req -new -key server.key -out server.csr

openssl x509 -req -days 365 -in server.csr -CA ca.crt -CAkey ca.key -set_serial 01 -out server.passless.crt
openssl rsa -in server.key -out server.key.insecure
mv server.key server.key.secure
mv server.key.insecure server.passless.key

After typing the commands, I made sure to put in my computer IP for the common name, but the certificate is not in my SiriProxy folder nor is it in ~/.siriproxy

I think I might've missed a command, but I'm not sure which one.

Thanks for the help, by the way!

**Comment by jayb1239** [comment]
that was me that posted those instructions. the cert will be wherever you ran the commands

**Comment by brendondelgado** [comment]
Ahh, it was you lol. Strange, the cert never appeared where I ran the commands. I'll re-run them.

**Comment by jayb1239** [comment]
just do a ls from where you are and see if they're there

**Comment by brendondelgado** [comment]
It's not there and now when I try to make a new one and I type in the command "openssl genrsa -des3 -out server.key 4096" (no quotes) it works, and then when it says to enter a password I enter a password and it says: 
Verify failure
User Interface error
27796:error:0906906F:PEM routines:PEM_ASNI_write_bio:read key:pem_lib.c:334:

What did I do wrong?

**Comment by jayb1239** [comment]
run the command again that failed with a verification error, that happened to me a few times too

**Comment by brendondelgado** [comment]
Alright, I'm doing that now.

**Comment by brendondelgado** [comment]
Alright, I did all of the commands and everything went through fine, and now I've got the following files all in a folder: ca.crt, ca.key, server.csr, server.key.secure, server.passless.crt, and server.passless.key

ca.pem was not created. Did I do something wrong? Do I email ca.crt to myself and install that on my iPhone? I'm a bit confused at the moment.

**Comment by jayb1239** [comment]
use ca.crt instead of ca.pem and put the rest in ~/.siriproxy then restart the proxy

**Comment by brendondelgado** [comment]
Okay. Doing that now. I'll post back in a minute or two telling you if it worked or not. I'm hoping it does.

**Comment by brendondelgado** [comment]
Still not working. I'm back to square 1.

**Comment by brendondelgado** [comment]
Thanks for the help by the way. It was worth a shot. :)

**Comment by brendondelgado** [comment]
Should it be my computer IP that I'm putting as the common name? Or should I be putting the IP that I get from whatismyip.org in the common name?

**Comment by jayb1239** [comment]
so still no output and you are sure that there are no firewalls or anything blocking you

**Comment by brendondelgado** [comment]
No output and I don't think there are any. Let me check my router settings.

**Comment by jayb1239** [comment]
if you are setting spire to https://192.168.whatever then thats what the cert needs to be. are you running in a virtual machine by any chance

**Comment by brendondelgado** [comment]
I am. I'm running Ubuntu 11.10 in Parallels on my MacBook Air.

**Comment by brendondelgado** [comment]
Is the IP that I'm getting from my VM not the correct IP that I should be putting in the cert or in spire?

**Comment by jayb1239** [comment]
it depends are you bridging the connection so that the VM is getting its own ip from the router or is it getting one from the mac?

**Comment by jayb1239** [comment]
network needs to be set as bridged in the vm settings if its not then that would explain the lack of connectivity

**Comment by brendondelgado** [comment]
Alright, I'll look into that. I've never used Ubuntu before, so I'm very new to the OS.

**Comment by brendondelgado** [comment]
Alright, so what I need is to install VirtualBox so that I can bridge it to my network.

**Comment by jayb1239** [comment]
no, edit the VM settings in parallels and select bridged for the network type

**Comment by brendondelgado** [comment]
Yeah, I just did that, too. My IP stayed the same, I dunno if it was supposed to change, but it didn't. Anyways, I'll try starting the siriproxy again and see what it says.

**Comment by jayb1239** [comment]
try restarting the VM after setting the network bridged

**Comment by brendondelgado** [comment]
Yup, doing that now. Again, thank you for all the help and for being so patient with me. This literally is the first time I've used Ubuntu or Ruby.

**Comment by brendondelgado** [comment]
Now I have no internet connection at all in bridged mode.

**Comment by jayb1239** [comment]
have you set an ip address or set it to acquire via DHCP?

**Comment by brendondelgado** [comment]
No. I don't really know how to do that, but I'll figure it out.

**Comment by ip335i** [comment]
I'm having same issue. I'm running ubuntu and I followed the instruction to setup siriProxy and now stuck at Starting SiriProxy on Port 443...(rebooting did not help)
Running VM ubunto server, bridged and get it own dhcp ip addess from router. I pointed spire proxy to ubunto server and open Siri, and said test siri proxy and Siri not taking an request.
Guessing that is coz siriproxy is not running.. Help?

**Comment by thecodingdude** [comment]
I had this issue and I fixed it by forwarding port 443 to the internal IP.

If you see something along the lines of:

"No data received
Unable to load the web page because the server sent no data."

When you visit http://[ip]:443 then port 443 is being routed. Please make sure you ARE forwarding port 443 and then visit your IP:443.
