### ISSUE TITLE
spire with siri proxy

### ISSUE THREAD

**Issue by wen9x88** [plamoni/SiriProxy#225]
i got the siri proxy server working in ubuntu 11.10.
it show Starting SiriProxy on port 443..
the thing is how to get my iphone 4's spire work ?
i send ca.pem to my phone and install.
then i set the proxy host https://192.168.115.129,my ubuntu ip address.
and also set the wifi's dns 192.168.115.129.
but spire still not working,why ?
appreciate help
thanks

**Comment by jayb1239** [comment]
The 4 with spire installed does not require the DNS it just needs the ip of the server with a https. the CA also needs to point to your server address not guzzoni.apple.com.

**Comment by wen9x88** [comment]
how to double check the ca is point to my server address ?
i m just following the idownloadblog guide:
sudo nano /etc/dnsmasq.conf
Find the following line on approximately line 62: #address=/double-click.net/127.0.0.1
Directly beneath that line type: address=/guzzoni.apple.com/192.168.115.129

**Comment by jayb1239** [comment]
when you created the certificate did you put your server or guzzoni.apple.com in the common name

**Comment by wen9x88** [comment]
i just type siriproxy gencerts,then automatic create the certificate.
now i check it,it is guzzoni.apple.com in the common name.
in this case how to create the certificate with my server ?
thank thank

**Comment by jayb1239** [comment]
(use any password and information you want)
openssl genrsa -des3 -out ca.key 4096
openssl req -new -x509 -days 365 -key ca.key -out ca.crt
openssl genrsa -des3 -out server.key 4096

(enter your ip or hostname in "common name" .. important! - if you want to use an iPhone 4S use "guzzoni.apple.com")
openssl req -new -key server.key -out server.csr

openssl x509 -req -days 365 -in server.csr -CA ca.crt -CAkey ca.key -set_serial 01 -out server.passless.crt
openssl rsa -in server.key -out server.key.insecure
mv server.key server.key.secure
mv server.key.insecure server.passless.key

**Comment by jayb1239** [comment]
would need to be run in ~/.siriproxy

**Comment by wen9x88** [comment]
i dont understand,bro do you have any remote desktop software ?
so that you connect to my pc and help me to edit.

**Comment by wen9x88** [comment]
trying here,thanks again.
very helpfull

**Comment by wen9x88** [comment]
bro i saw a ca.crt at my home,not in .siriproxy.
can i just copy it to .siriproxy?

**Comment by coadyj** [comment]
I need some help on this issue,

firstly I set up the server to default config and was able to connect my iphone 4s and use the "test siri proxy" command
but I was getting the typical errors when I tried to connect my iphone 4

I made the changes to the siriproxy/scripts/gen_something file

I deleted another folder and reran the installation from "rake install"

Now my CN has my server IP, I reinstalled the cert on my phone, but now when I connect my iPhone 4s I get the following error

[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000001589e80 @manager=#<SiriProxy::PluginManager:0x0000000158a448 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000001589d40 @signature=8, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000001591ba8>, @zip_stream=#Zlib::Deflate:0x00000001591b80, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000001591108 @manager=#<SiriProxy::PluginManager:0x000000015916d0 @plugins=[...]>>]

**Comment by jayb1239** [comment]
Without a dual ca only the 4 or the 4s will be able to connect

**Comment by coadyj** [comment]
I saw you mentioned that in another thread, can you explain exactly how you did it?

**Comment by wen9x88** [comment]
To setup Siri proxy server must need a iPhone 4s?

**Comment by mcdull** [comment]
@wen9x88 Yes.. or one from you frd and let him/her to use your proxy in every 1 or 2 days
@coadyj Do not attempt to alter the CA name, just use the default guzzoni.apple.com.  Do the trick in DNS / VPN / host file then you can avoid using the dual CA.

**Comment by wen9x88** [comment]
One iPhone 4s can setup how many proxy server?
Example my friend iPhone 4s already setup his own proxy server,do his iPhone 4s still can borrow me to setup another proxy server?

**Comment by mcdull** [comment]
@wen9x88 countless technically.  It all depends on how apple react. It will BLACKLIST those key with too many access at the same time.. (or in different geo graphical location)

**Comment by wen9x88** [comment]
ic,because i m thinking to send the ca.crt to friend to grab iPhone 4S Siri Authentication Keys.
with that key i can create my own siri proxy server work.
by the way i m from malaysia here.
