### ISSUE TITLE
Problem with non-4S device

### ISSUE THREAD

**Issue by guillermo-moran** [plamoni/SiriProxy#228]
Alright, let me just get to the point :P 

I'm getting this issue, I've cached my iPhone 4S keys as well: 

[Warning] Non-4S device connected.
[Info - iPhone] Received Object: GetSessionCertificate
[Info - Guzzoni] Received Object: GetSessionCertificateResponse
[Info - iPhone] Received Object: CreateSessionInfoRequest
[Info - Guzzoni] Received Object: CreateSessionInfoResponse
[Info - iPhone] Received Object: CreateAssistant
[Info - iPhone] Received Object: SetAssistantData
[Info - iPhone] Received Object: SetRestrictions
[Info - iPhone] Received Object: ClearContext
[Info - iPhone] Received Object: GetAnchors
[Info - iPhone] Received Object: SetRestrictions
[Info - iPhone] Received Object: ClearContext
[Info - iPhone] Received Object: StartSpeechRequest
[Info - Guzzoni] Received Object: GetSessionCertificateResponse
[Info - Guzzoni] Received Object: SessionValidationFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - iPhone] Received Object: SetRequestOrigin
[Info - User Location] lat: , long: 
[Info - Guzzoni] Received Object: CommandFailed
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: FinishSpeech
[Info - iPhone] Received Object: CreateAssistant
[Info - iPhone] Received Object: SetAssistantData
[Info - iPhone] Received Object: GetAnchors
[Info - iPhone] Received Object: SetRestrictions
[Info - iPhone] Received Object: ClearContext
[Info - iPhone] Received Object: RestartRequest
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: GetSessionCertificateResponse
[Info - Guzzoni] Received Object: SessionValidationFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - iPhone] Received Object: CreateAssistant
[Info - iPhone] Received Object: SetAssistantData
[Info - iPhone] Received Object: GetAnchors
[Info - iPhone] Received Object: SetRestrictions
[Info - Guzzoni] Received Object: GetSessionCertificateResponse
[Info - Guzzoni] Received Object: SessionValidationFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - iPhone] Received Object: ClearContext
[Info - iPhone] Received Object: CreateAssistant
[Info - iPhone] Received Object: SetAssistantData
[Info - iPhone] Received Object: GetAnchors
[Info - iPhone] Received Object: SetRestrictions
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: GetSessionCertificateResponse
[Info - Guzzoni] Received Object: SessionValidationFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - iPhone] Received Object: ClearContext
[Info - iPhone] Received Object: CreateAssistant
[Info - iPhone] Received Object: SetAssistantData
[Info - iPhone] Received Object: GetAnchors
[Info - iPhone] Received Object: SetRestrictions
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: GetSessionCertificateResponse
[Info - Guzzoni] Received Object: SessionValidationFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed

Not sure what's up, or am I missing something? o.o

**Comment by guillermo-moran** [comment]
btw: I'm using westbaer's fork

**Comment by bexel** [comment]
Use this fork: https://github.com/fopina/SiriProxy

**Comment by earlcochran** [comment]
Did you edit com.apple.assistant.plist on your non-4S device? You need to add a few items to it for it to actually work. Check out Issue #226 or Step 3 at this link > http://methoddk.com/siriguide/

**Comment by ghost** [comment]
Thanks methoddk.

**Comment by guillermo-moran** [comment]
Awesome, works like a charm. Appreciate the help methodk :D
