### ISSUE TITLE
Can i send my Ca.crt to your Iphone 4s ?

### ISSUE THREAD

**Issue by wen9x88** [plamoni/SiriProxy#231]
i m thinking to send the ca.crt to friend to grab iPhone 4S Siri Authentication Keys,because i dont have iphone 4s. 
with that key i can create my own siri proxy server work,by the way i m from malaysia here.

**Comment by Bubelbub** [comment]
hmm!

Better is, your Friend use your Server as "DNS" Server.
Because the Cert is not really needed by this way.

And by the Way:
If your Friend install the ca.crt, he must do more than this Step!

**Comment by FineTralfazz** [comment]
Nobody is going to give you their Siri authentication key.  Find a friend who owns one or go without.
