### ISSUE TITLE
Starting SiriProxy on port 443.. 

### ISSUE THREAD

**Issue by tom1234** [plamoni/SiriProxy#232]
i have installed siriproxy in ubuntu 11.10 I'm totally new to command line in Linux, so getting it installed was a big success for. At the end i get the line Starting SiriProxy on port 443.. and nothing happens. In the instructional video starts a screen with green letters. But not here. I want to use it with Spire on my iPad 1.

I hope you can and will help me

**Comment by wen9x88** [comment]
u need iphone 4s

**Comment by tom1234** [comment]
i have the certificates of a iPhone 4s from a friend of mine. Where do i need to place this certificates?

**Comment by wen9x88** [comment]
ask your friend open and install certificates,then change the dns to your ip address.
and set spire to your ip then try siri.
after that will automatic connect to siriproxy on port 443,then the certificate also automatic come out.
no need place.

**Comment by tom1234** [comment]
but i want to use spire on my iPad. How does that work?

**Comment by wen9x88** [comment]
actually before u want to use spire on your ipad,you need to do this first.
actually i need to test it but i don have friend using iphone 4s.
