### ISSUE TITLE
Other servers

### ISSUE THREAD

**Issue by piotr-sikora-v** [plamoni/SiriProxy#233]
Hi,

There is any option to use dragon diction servers or  google's voice recognition engine ?

Best regards!

**Comment by ethernet8023** [comment]
If you want this, feel free to write it yourself :)

**Comment by JBX028** [comment]
you can indeed use the voice recognition provided by google but siri is more than a voice recognition engine, it's a real inteligent system.

http://robertbuzink.com/2011/hack-into-the-google-chrome-beta-speech-recognition-api/
