### ISSUE TITLE
rake install: no permission to write 

### ISSUE THREAD

**Issue by Fold93** [plamoni/SiriProxy#234]
Hello!
Everything works fine until i get to the step where i should type
rake install which gives me the error:

Couldn't install gem, run `gem install ....

So i did so and it tells me:

ERROR: While executing gem ... (Gem::FILEPERMISSIONERROR)
       You don't have write permissions into the /var/lib/gems/1.8 directory.

What shell I do?

Greetings

**Comment by Bubelbub** [comment]
I think you aren´t "root".
Also try

sudo gem install ....

if sudo don´t exist (Debian...)

apt-get install sudo

Then try it :)

**Comment by Fold93** [comment]
just retried the whole thing and got it working now!
