### ISSUE TITLE
sudo ruby start.rb error!!!!

### ISSUE THREAD

**Issue by ghost** [plamoni/SiriProxy#235]
/Users/Kevin/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- plugins/thermostat/siriThermostat (LoadError)
    from /Users/Kevin/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from start.rb:2:in `<main>'

HELPP ME?!!!!

**Comment by Bubelbub** [comment]
Open the File
start.rb
and remove
require 'plugins/thermostat/siriThermostat'

:)

**Comment by ghost** [comment]
now comes: -.- 
/Users/Kevin/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- plugins/testproxy/testproxy (LoadError)
    from /Users/Kevin/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from start.rb:2:in `<main>'

**Comment by Bubelbub** [comment]
Can you speak German? Or is "now comes" really english? =D

Enter the Directory, where "plugins/testproxy/testproxy" is.
Also if you use the "mayo and ketchup tutorial", then go into ~/hacks/SiriProxy

If you dont know post your Directory here -> Where you are! (example: /root/)

**Comment by ghost** [comment]
Yes i speak german xD, i've take an mistake sry :D

**Comment by Bubelbub** [comment]
Funktionierts denn jetz?

---

Works?

**Comment by ghost** [comment]
nein :-(

**Comment by ghost** [comment]
ich hab jetzt die anleitung gemacht: http://www.dfxnetwork.org/2011/12/14/siriproxy-anleitung-wie-man-ihn-unter-mac-osx-zu-laufen-bekommt/ habs mit iphone 4 gemacht.

**Comment by ghost** [comment]
habe vpn eingerichtet, was muss ich jetzt machen?

**Comment by miamirican305** [comment]
Someone help PLEASE!!! After I've grabbed my 4S keys and pasted them to AuthGrabber.rb accordingly I run rvmsudo ruby start.rb and get this: /home/raul/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- tweakSiri (LoadError)
    from /home/raul/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from siriAuth.rb:7:in `<main>'

Guys I've been on this for 4 days straight already! Wife is about to kick me out of the house even! (smh) I haven't stopped trouble shooting this problem. And To no Avail! Someone HEEEEEELP! btw: Thanks in advance! 
Also: I'm using a STANDALONE UBUNTU (Just in case you need that info)

**Comment by Bubelbub** [comment]
You must "cd" in the Directory, where is tweakSiri.

Example:
1.) find / -name tweakSiri
2.) cd /example/founded

=]

**Comment by schmooty** [comment]
Bubelbub you are my only hope!!!!

Sorry that I need this to be spoonfed to me but can you explain how to or what you mean by:

Open the file
Ruby start .rb
And remove the require Plugins / thermostat / Siri thermostat
- do you mean to open a with a text editor and only delete those words??or the whole line ?? Or how exactly. Sorry I'm so dumb about this part. I'm having the same issue as Mr pabis that you helped. Thanks so much

**Comment by Bubelbub** [comment]
SSH Console :)

**Comment by schmooty** [comment]
So I ssh a command to remove the plugin?csr's in Videos
www.tutorgig.com/v/csr's
Description: Check this video out at Hi-Res here: www.tutvid.com We will start with nothing more than a ...

**Comment by schmooty** [comment]
@ bubelbub

thanks so much for the help. now im getting this:

:/Ruby193/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.0.beta.4.1-x86-mingw32/lib/
m/connection.rb:405:in `block in start_tls': Could not find server.passless.key
for start_tls (EventMachine::FileNotFoundException)
       from C:/Ruby193/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.0.beta.4.1-x86
mingw32/lib/em/connection.rb:403:in`each'
       from C:/Ruby193/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.0.beta.4.1-x86
mingw32/lib/em/connection.rb:403:in `start_tls'
       from C:/Users/Wee-bey/Desktop/SiriProxy for Windows/siriProxy.rb:363:in
post_init'
       from C:/Ruby193/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.0.beta.4.1-x86
mingw32/lib/em/connection.rb:58:in`block in new'
       from C:/Ruby193/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.0.beta.4.1-x86
mingw32/lib/em/connection.rb:49:in `instance_eval'
       from C:/Ruby193/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.0.beta.4.1-x86
mingw32/lib/em/connection.rb:49:in`new'
       from C:/Ruby193/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.0.beta.4.1-x86
mingw32/lib/eventmachine.rb:1416:in `event_callback'
       from C:/Ruby193/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.0.beta.4.1-x86
mingw32/lib/eventmachine.rb:179:in`run_machine'
       from C:/Ruby193/lib/ruby/gems/1.9.1/gems/eventmachine-1.0.0.beta.4.1-x86
mingw32/lib/eventmachine.rb:179:in `run'
       from C:/Users/Wee-bey/Desktop/SiriProxy for Windows/siriProxy.rb:399:in
initialize'
       from start.rb:9:in`new'
       from start.rb:9:in `<main>'

pleeeeeeeeease help
