### ISSUE TITLE
How to intercept the original response from Siri

### ISSUE THREAD

**Issue by JBX028** [plamoni/SiriProxy#236]
Hi,

Any update on when it will be possible to intercept the orginal response from siri? I asked the question one month ago (issue #81) and the answer was that it should be possible soon.

Thanks

**Comment by Treenity** [comment]
go look into plugins, like the "Test Siri Proxy" is intercepting the speech, and show what the plugin want.

**Comment by JBX028** [comment]
@Treenity I am not to understand what you explain. I know how to intercept what i said and this is the purpose of any plugin working with siriproxy, but what i would like to know is if there is a possibility to intercept the original answer from siri.
When i say "hello" and if i do not have matched this patern within my plugin, siri will tell me something and this is what i would like to intercept.
