### ISSUE TITLE
where to put the 4S auth tokens?

### ISSUE THREAD

**Issue by Fold93** [plamoni/SiriProxy#237]
Hey guys!

Everything's up and running but i'm a little confused. I pulled the 4S auth tokens off my girlfrieds 4S with the help of this tutorial : http://bradstevo.blogspot.com/2011/12/guide-for-siri-authentication-keys-on.html

But what to do with them?
Or did I just missunderstand something?
Do I have to connect the 4S to SiriProxy or do i just need these tokens?

greetings from austria

**Comment by Bubelbub** [comment]
You can use this Commands.

1.) Assistant ID
echo "theid" > ~/.siriproxy/assistant_id

2.) Session Data
echo "theid" > ~/.siriproxy/session_data

3.) SpeechID
echo "theid" > ~/.siriproxy/speech_id

=]

**Comment by gotnull** [comment]
@Bubelbub Thanks for this. Great for future reference.

**Comment by Bubelbub** [comment]
If my Post is the Solution, press ------------------------------------------------------------------------------->
Close issue

=]
