### ISSUE TITLE
Unable to talk to Siri

### ISSUE THREAD

**Issue by clow00** [plamoni/SiriProxy#239]
Hello guys, i'm quite a n00b but I was able to go thru all the way using the video shown to follow all the steps.
Though, i'm having an issue (obviously hehe), everytime I open Siri, it immediately makes the sound to talk, but a second later it makes a sound informing i'm unable to talk to it.

In terminal, i got this notes:
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x000000028e6870 @signature=9, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x000000028e66b8>, @zip_stream=#Zlib::Deflate:0x000000028e6690, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x000000028e5ab0 @manager=#<SiriProxy::PluginManager:0x000000028e6208 @plugins=[...]>>]

Any idea will be really appreciated

**Comment by Fold93** [comment]
Hey there.. Got a similar issue but  get a lot more code from just 1 single push on the siri microphone..

Starting SiriProxy on port 443..
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0xa355278 @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0xa3550ac>, @zip_stream=#Zlib::Deflate:0xa355048, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x9fcfae0 @manager=#<SiriProxy::PluginManager:0xa354e04 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x9fcf7fc @signature=4, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x9fcf4f0>, @zip_stream=#Zlib::Deflate:0x9fcf4dc, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x9fce3e8 @manager=#<SiriProxy::PluginManager:0x9fcef14 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x9fce168 @signature=5, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x9fcdf24>, @zip_stream=#Zlib::Deflate:0x9fcdf10, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x9fcd3bc @manager=#<SiriProxy::PluginManager:0x9fcd894 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x9fcd2f4 @signature=6, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x9fcd1c8>, @zip_stream=#Zlib::Deflate:0x9fcd1a0, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0xa0317f4 @manager=#<SiriProxy::PluginManager:0xa031f4c @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0xa0316c8 @signature=7, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0xa031538>, @zip_stream=#Zlib::Deflate:0xa031484, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0xa030778 @manager=#<SiriProxy::PluginManager:0xa031038 @plugins=[...]>>]

(This comes up after only 1 tap onto the siri micro)

I hope someone can help us!

**Comment by max9917** [comment]
I'm having problems on this too! I wish I could have custom commands on my 4s.

**Comment by FineTralfazz** [comment]
You don't have the SSL certificate installed on your phone.

**Comment by max9917** [comment]
I installed the certificate onto my iPhone 4s.

**Comment by Fold93** [comment]
the ca.pem? yes i have :/

what ip address do i have to insert in the config file? the IP of the local machine in my normal network, the ip of the whole network(not the internal one 192.168.xxx.xxx) or, since im connecting with VPN, the ip of the computer in the vpn network?

thanks for the tipp!

**Comment by FineTralfazz** [comment]
If it's installed, I don't know what the problem is. I was getting that error too before I had the cert installed, but it went away once I did.

**Comment by FineTralfazz** [comment]
@Fold93, if you're getting that error you have the right IP, otherwise it would just stay at "Starting SiriProxy on port 443.."

**Comment by Fold93** [comment]
think so too.. but whats the problem then? 
i retried it (siriproxy gencerts, siriproxy bundle) and sent it to my iphone 4 and still the same problem. Same happened with the old cert and the 4S of my girlfriend.

**Comment by clow00** [comment]
I also installed the ca.pem in the iphone 4 but still i'm getting the same response :s

**Comment by mantas7776** [comment]
Ipod 3g same issuise

**Comment by Fold93** [comment]
Got it working with my 4s but still the same prob with the 4. Used the certificate created by the proxy and also generated my own ones with my local ip once and also my external ip. Both are not working. (i just created them, witht the openssl commands. Do i have to do something at siriproxy too?
