### ISSUE TITLE
Siri Proxy Rake install error

### ISSUE THREAD

**Issue by siriproxyusr** [plamoni/SiriProxy#240]
When i use command sudo rake install then i get this error

ty@ubuntu:~/SiriProxy$ sudo rake install
(in /home/ty/SiriProxy)
rake aborted!
no such file to load -- rubygems
/home/ty/SiriProxy/Rakefile:3:in `require'
(See full trace by running task with --trace)

Can someone help?

**Comment by FineTralfazz** [comment]
Open up a terminal and run `sudo apt-get install rubygems`.

**Comment by siriproxyusr** [comment]
Thanks, I just uninstalled then reinstalled Ubuntu a few hours ago to fix it but thanks for the help! I'm trying to setup a VPN so that I can redirect someone's else's 4s to my server without then being on my wifi. But when I setup a VPN and they put it on their 4s it didn't work, they got an error

**Comment by FineTralfazz** [comment]
It's easier just to forward the port through your router, if you know how to do that.

**Comment by siriproxyusr** [comment]
No I don't, what does that do?

**Comment by siriproxyusr** [comment]
Thanks for helping me with this, I appreciate it. My iMessage is tyrocks49@yahoo.com, it'd be easier to talk to you about this through that if you can.

**Comment by siriproxyusr** [comment]
Hey @Salax-  would you please help me with that?

**Comment by FineTralfazz** [comment]
I don't have time, sorry. You can find a lot of guides online, the most notable one being portforward.com.
