### ISSUE TITLE
configuring iPhone 4 spire,edit /etc/hosts file 

### ISSUE THREAD

**Issue by popeel2** [plamoni/SiriProxy#241]
I have SSH into my phone and apparently i need to edit /etc/hosts file to point requests for guzzoni.apple.com to my server. 
so far my host file looks like this
## 
# Host Database
# 
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
## 

127.0.0.1   localhost
255.255.255.255 broadcasthost
::1             localhost 
fe80::1%lo0 localhost
can some show me an example and explain step by step

**Comment by popeel2** [comment]
also my server is up and running fine

**Comment by popeel2** [comment]
127.0.0.1 localhost
255.255.255.255 broadcasthost
::1 localhost 
fe80::1%lo0 localhost
myddnsserver-domain guzzoni.apple.com
is what you are supposed to do.  how do i find the myddnsserver part

**Comment by FineTralfazz** [comment]
Put the IP address of your Siri proxy there.

**Comment by popeel2** [comment]
is the siri proxy ip my virtual machines ip

**Comment by dbazley** [comment]
i am having some issues when using my dymanic dns, everything works fine until i change the host file from the outside dymanig ip to my hostname at no-ip.

if i put in my outside ip address (dynamic from verizon) in the host file, siri works just fine.
but if i put in myhostname.no-ip.org, it wont connect.

any ideas?
thanks!!!

**Comment by FineTralfazz** [comment]
You need to forward the ports through your router. Google.

**Comment by dbazley** [comment]
hi thanks but i have my ports forwarded in my router.
like i said, it works when i use the dynamic ip address from verizon in the hosts file.
but it doesnt when i put the no-ip address in the host file.

thanks!!

**Comment by FineTralfazz** [comment]
Install the [no-ip DUC](http://www.no-ip.com/downloads.php).

**Comment by dbazley** [comment]
i have that installed and setup.
it has my hostname registered and showing my ip current dynamic ip.

its weird.
i am running ubuntu 11.10 in virtualbox on a windows server 2008 r2 computer.
the network connection is bridged, so the ip address for the VM is 10.0.4.108.
the router forwards the incoming connections to that ip. 10.0.4.108 tcp any -> 443.  its a westell 9100 verizon fios router.

is there a virtual box addin im missing, or that i should add?
should i install the no-ip DUC inside the VM instead of on the windows side?

thanks for your help!!

**Comment by FineTralfazz** [comment]
Doesn't matter where you install the DUC. Not sure what your problem is, as I don't have much experience with VirtualBox or Windows servers.

**Comment by mcdull** [comment]
I am not quite sure of your problem but I do guess that the hosts file does NOT support domain to domain resolution. i.e. the first part MUST be an IP address to be resolved.

**Comment by mcdull** [comment]
If you need to solve the problem. 2 solution, 1.. VPN and uses DNS override on your local DNS.  2.. build a full DNS server available to public with the custom resolution but you still need a fix IP for the DNS (only viable if you have a frd that can host that)

**Comment by gotnull** [comment]
Use DNSMASQ for this.

**Comment by dbazley** [comment]
yes i used dnsmasq, but it that does not solve the problem.
the guide has no been updated to solve my issue.  it appears that openssl needs edited as well.
http://methoddk.com/siriguide/

thanks everyone for the help.
