### ISSUE TITLE
had plamoni server working but now cant get westbaer to cache keys ?

### ISSUE THREAD

**Issue by phate1** [plamoni/SiriProxy#243]
this isnt a issue with the proxy but a mistake made by me that has ended up costing me more hours than i care to remember and no doubt showing how new i am to ubuntu but posting this to help anyone else than runs into the same problem. so i had the main plamoni proxy running for a while now and have then tried to install the westbaer fork using the guide at http://methoddk.com/siriguide/ (amazing work btw) so have no idear how to uninstall the proxy server and ended up just deleating the Siriproxy folder and starting again and eveything seemed to go smooth untill the rake install command that didnt work so skipped it and carried on server came up fine my 4s worked a treat but my 4 wouldnt have it kept cuming up with command failed and no 4s data was apearing in .siriproxy what i have now realised is i seem to be using the original proxy and not the westber (im assuming the reason the rake install command failed because i already had a siriproxy installed im just guessing tho) so i created a new account on my box and started from the begining of the guide on the new account accept left the dnsmasq stuff running on my other account no need to set it up twice and bingo 4s auth captured 4 using this info and now talking to the server perfecly hope that helps some people out they may well be a easier solution so you can just uninstall the previouse proxy and anyone with the knowlege please post that solution

**Comment by mcdull** [comment]
del the file in .rvm/gems/.... siriproxy.  You would find it easily.
and the Siriproxy folder under home and retry again.

**Comment by phate1** [comment]
I new there had to be a easy answer thanks mcdull
