### ISSUE TITLE
(Please Help) siriproxy gencert command error

### ISSUE THREAD

**Issue by devote99** [plamoni/SiriProxy#244]
I tried  to install SiriProxy on Ubuntu 11.10 Desktop but it did not work 
by following the set-up instruction guide on  https://github.com/plamoni/SiriProxy  
but I got some error when I ran siriproxy gencert command as below :

root@test-Siri:~/SiriProxy# ./bin/siriproxy gencert
./bin/siriproxy: 4:in `require': ./bin/../lib/siriproxy/command_line.rb:74: syntax error, unexpected '>' (SyntaxError)
    repl = -> prompt { print prompt; cora.process(gets.chomp!) }
                  ^
        from ./bin/siriproxy:4
root@test-Siri:~/SiriProxy#

and also happened again when I ran 

root@test-Siri:~/SiriProxy# rvmsudo /root/SiriProxy/bin/siriproxy gencert
/root/SiriProxy/bin/siriproxy: 4:in `require': /root/SiriProxy/bin/../lib/siriproxy/command_line.rb:74: syntax error, unexpected '>' (SyntaxError)
    repl = -> prompt { print prompt; cora.process(gets.chomp!) }
                  ^
        from /root/SiriProxy/bin/siriproxy: 4

Any ideas, Please help me to fix this problem 
thank you

**Comment by knightz4u** [comment]
you need to use gencerts instead of gencert

**Comment by devote99** [comment]
Thanks for your comment. :)
I changed it from gencert to gencerts , but still got same result output
Any idea? Please Help

root@test-Siri:~/SiriProxy# ./bin/siriproxy gencerts
./bin/siriproxy: 4:in `require': ./bin/../lib/siriproxy/command_line.rb:74: syntax error, unexpected '>' (SyntaxError)
    repl = -> prompt { print prompt; cora.process(gets.chomp!) }
             ^
        from ./bin/siriproxy:4
root@test-Siri:~/SiriProxy# rvmsudo /root/SiriProxy/bin/siriproxy gencerts
/root/SiriProxy/bin/siriproxy:4:in`require': /root/SiriProxy/bin/../lib/siriproxy/command_line.rb:74: syntax error, unexpected '>' (SyntaxError)
    repl = -> prompt { print prompt; cora.process(gets.chomp!) }
             ^
        from /root/SiriProxy/bin/siriproxy:4
