### ISSUE TITLE
(HELP!) rvmsudo ruby ./start.rb (HELP!)

### ISSUE THREAD

**Issue by miamirican305** [plamoni/SiriProxy#245]
Someone help PLEASE!!! After I've grabbed my 4S keys and pasted them to AuthGrabber.rb accordingly I run rvmsudo ruby start.rb and get this: /home/raul/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in require': cannot load such file -- tweakSiri (LoadError)
from /home/raul/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:inrequire'
from siriAuth.rb:7:in `'

Guys I've been on this for 4 days straight already! Wife is about to kick me out of the house even! (smh) I haven't stopped trouble shooting this problem. And To no Avail! Someone HEEEEEELP! btw: Thanks in advance!
Also: I'm using a STANDALONE UBUNTU 10.11 (Just in case you need that info)

**Comment by FineTralfazz** [comment]
Just use [this fork](https://github.com/westbaer/SiriProxy), it will automatically handle grabbing of IDs for you.

**Comment by miamirican305** [comment]
I have the ID's.... I just can't understand why the SiriAuth is not working... :( I'm a novice to UBUNTU so i'm trying to understand you. What will this link do for me? -Thanks in Advance :)

**Comment by FineTralfazz** [comment]
If you use what I linked you to, your server will automatically grab the IDs of any 4S which connects to it. That way you don't have to manually do a bunch of stuff every day when the keys expire.

**Comment by miamirican305** [comment]
I'll try it! Thanks XD Do I need to Download all the files?

**Comment by FineTralfazz** [comment]
Yes. Delete what you have now and start fresh.
