### ISSUE TITLE
 com.apple.assistant.plist help!!!

### ISSUE THREAD

**Issue by popeel2** [plamoni/SiriProxy#246]
http://imageshack.us/photo/my-images/10/capturegsg.png/
check out the link, i am not sure how to config this file

**Comment by popeel2** [comment]
by the way i am on iphone 4 trying to connect spire to my server.

**Comment by FineTralfazz** [comment]
Step 3 [here](http://methoddk.com/siriguide/).

**Comment by dlabrie** [comment]
@Salax-, Stop trolling here.

**Comment by FineTralfazz** [comment]
@do167 I'm not trolling, it's right between steps two and four. It expands if you click one of the two links.

**Comment by dlabrie** [comment]
@Salax- oh, sorry, I didn't see it

**Comment by elvisimprsntr** [comment]
closed due to inactivity. also using an unsanctioned  device
