### ISSUE TITLE
Fix for CFPropertyList (LoadError) on Debian (squeeze)

### ISSUE THREAD

**Issue by Koplimi** [plamoni/SiriProxy#25]
Running debian (squeeze) and get this error?:

/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- CFPropertyList (LoadError)
    from /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from ./siriProxy.rb:4
    from /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from ./start.rb:10

Just change the line: require 'CFPropertyList' to require 'cfpropertylist' in the siriProxy.rb file.

**Comment by netpro2k** [comment]
hmm interesting, on my system the gem seems to be named CFPropertyList ... Hopefully this sort of thing will be solved when we switch over to bundler.

**Comment by netpro2k** [comment]
This is now resolved in the refactored branch https://github.com/plamoni/SiriProxy/tree/refactored
