### ISSUE TITLE
/usr/bin/env: siriproxy: No such file or directory

### ISSUE THREAD

**Issue by knightz4u** [plamoni/SiriProxy#251]
I managed to get all the way to the point where i start the siriproxy server, i initiate the command but get the following error message.

administrator@Acer150:~/SiriProxy$ rvmsudo siriproxy server
[sudo] password for administrator: 
/usr/bin/env: siriproxy: No such file or directory
administrator@Acer150:~/SiriProxy$ 

I am on Ubunto 11.10

**Comment by FineTralfazz** [comment]
You didn't follow the directions. Go back and try again.

**Comment by bowtakwah** [comment]
Run: rake install && siriproxy bundle
Then: rvmsudo siriproxy server

If unsuccessful, output the $PATH to us: echo $PATH

**Comment by knightz4u** [comment]
I have done the rake install and it went fine, the siriproxy bundle would only work if i used ruby siriproxy bundle, the $PATH shows as below:

administrator@Acer150:~/SiriProxy$ echo $PATH
/home/administrator/.rvm/gems/ruby-1.9.3-p0@SiriProxy/bin:/home/administrator/.rvm/gems/ruby-1.9.3-p0@global/bin:/home/administrator/.rvm/rubies/ruby-1.9.3-p0/bin:/home/administrator/.rvm/bin:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games

**Comment by bowtakwah** [comment]
You missed this step:
echo '[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # Load RVM function' >> ~/.bash_profile

Then, either reopen your terminal window or run source ~/.bash_profile to make sure it takes effect.

If this doesn't work, output the .bash_profile to us: cat ~/.bash_profile

**Comment by knightz4u** [comment]
I did use that line before, anyways i ran it again and as requested i closed my terminal and reopened terminal, i still get the same error like before. my .bash_profile is below:

administrator@Acer150:~/SiriProxy$ cat ~/.bash_profile
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # Load RVM function
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # Load RVM function
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # Load RVM function
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # Load RVM function

**Comment by bowtakwah** [comment]
Search for rvm using this command: **sudo find / -name rvm**

This is what I got: Find the line with the suffix, **bin/rvm**
/usr/local/rvm
/usr/local/rvm/src/rvm
/usr/local/rvm/src/rvm/binscripts/rvm
/usr/local/rvm/src/rvm/lib/rvm
/usr/local/rvm/src/rvm/scripts/rvm
**/usr/local/rvm/bin/rvm**
/usr/local/rvm/scripts/rvm
/usr/local/rvm/lib/rvm

Then, make sure your **.bash_profile** looks like this: Of course, replace **/usr/local/rvm/bin** with what you found.

PATH=$PATH:**/usr/local/rvm/bin**
export PATH

[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # Load RVM function

**Comment by knightz4u** [comment]
I did that, still siriproxy server gives the same error, do i have to do something other than reopen the terminal?

administrator@Acer150:~/SiriProxy/bin$ cat ~/.bash_profile
PATH=$PATH:/home/administrator/.rvm/bin/rvm
export PATH

[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # Load RVM function

**Comment by bowtakwah** [comment]
So you followed what I said, reopened the terminal, and ran **rake install && siriproxy bundle** in SiriProxy before running **rvmsudo siriproxy server**?

Take out **/rvm**

**Comment by knightz4u** [comment]
Now i did all rake install && siriproxy bundle, but still the server is failing, check below:

administrator@Acer150:~/SiriProxy$ rake install
siriproxy 0.3.0 built to pkg/siriproxy-0.3.0.gem
siriproxy (0.3.0) installed
administrator@Acer150:~/SiriProxy$ siriproxy bundle
siriproxy: command not found
administrator@Acer150:~/SiriProxy$ cd bin
administrator@Acer150:~/SiriProxy/bin$ siriproxy bundle
siriproxy: command not found
administrator@Acer150:~/SiriProxy/bin$ ruby siriproxy bundle
Using rake (0.9.2.2) 
Using libxml-ruby (2.2.2) 
Using CFPropertyList (2.0.17) 
Using geocoder (1.1.0) 
Using cora (0.0.4) from git://github.com/chendo/cora.git (at master) 
Using eventmachine (0.12.10) 
Using uuidtools (2.1.2) 
Using siriproxy (0.3.0) from source at . 
Using siriproxy-example (0.0.1) from source at ./plugins/siriproxy-example 
Using bundler (1.0.21) 
Your bundle is complete! Use `bundle show [gemname]` to see where a bundled gem is installed.
administrator@Acer150:~/SiriProxy/bin$ bundle show siriproxy
/home/administrator/SiriProxy
administrator@Acer150:~/SiriProxy/bin$ rvmsudo siriproxy server
/usr/bin/env: siriproxy: No such file or directory

**Comment by bowtakwah** [comment]
I say you should restart everything.

rm -Rf ~/.rvm ~/.siriproxy
bash < <(curl -s https://raw.github.com/wayneeseguin/rvm/master/binscripts/rvm-installer)
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"
rvm install 1.9.3
rvm use 1.9.3 --default
git clone https://github.com/plamoni/SiriProxy.git
cd SiriProxy
rvmsudo gem install rake bundler
rake install
mkdir ~/.siriproxy
cp ./config.example.yml ~/.siriproxy/config.yml
siriproxy gencerts
siriproxy bundle
rvmsudo siriproxy server

This is pretty much the exact same steps I used.

**Comment by mrmosconi** [comment]
Run from the directory where siriproxy lives. Then run "rvmsudo ./siriproxy server".

**Comment by SilenceFictionxD** [comment]
Follow all of the commands from this page:
https://gist.github.com/1428474
Don't skip a command all of them are important!

**Comment by knightz4u** [comment]
Thanks @bowtakwah, restarting from beginning helped.

**Comment by evovtech** [comment]
I'm having issues on "/usr/bin/env: siriproxy: No such file or directory".

I start fresh using Virtual Box on PC with Ubuntu 11.10. I follow all the commands as per your instructions.
. All commands are OK, but after I enter "rvmsudo siriproxy server", an error msg appear "/usr/bin/env: siriproxy: No such file or directory".

Please help. Thanks.
