### ISSUE TITLE
Proxy works on LAN but not on 3G

### ISSUE THREAD

**Issue by trulow** [plamoni/SiriProxy#252]
I followed this guide to get my proxy up and running. http://methoddk.com/siriguide/
Everything works as long as I am connected to my local area network. But once I deactivate WiFi, my iPhone4 cannot connect to the Proxy. I have forwarded both ports 53 and 443 to my server. I have my DynDNS account setup and working which I know works because I use it for my VPN service. Also have the hosts file set up to forward dyndns to guzzoni. Yet I cannot for the life of me get it to work on 3G.

Any help would be greatly appreciated. Thanks!

**Comment by muhkuh0815** [comment]
maybe your router doesnt support port 53 forwarding.
try out if it works with l2tp

**Comment by trulow** [comment]
I couldn't get it to work with L2TP as well. Just to double check, I just set up a normal VPN connection on the phone and send all traffic though it? Also, do I leave Spire directed to guzzoni?

I know both ports are properly forwarding though as I am able to telnet and establish a connection using "telnet name.dyndns.org 443" with a remote computer. telnet also works with port 53.

**Comment by trulow** [comment]
Thanks guys, I was able to fix the issue with the help of methoddk (whom created the guide and updated with the info). Apparently when dealing with a dynamic IP, you need an SSL cert with two common names.  The first which directs to the dyndns account and the second which directs to guzzoni. After I made the appropriate changes, I was able to get everything up and running.

Thanks!
