### ISSUE TITLE
iphone 4S can't connect to the siriproxy

### ISSUE THREAD

**Issue by Danieliverant** [plamoni/SiriProxy#253]
I'm using this tutorial: http://www.youtube.com/watch?v=LowzAiud0dE
I'm using VirtualBox to run Ubuntu and I dont have the "spider web" in 3:18
and now I finished﻿ doing the proxy, and I installed the siri-proxy on the iPhone 4S,
and I connected to the WiFi and changed my DNS to my IP (as it shown in 13:00)
but the siri doesnt react to the "test siri proxy" or any other commend (but it does work when I change the DNS back to what it was), can you help me? I think the problem is in the WiFi in the virtual machine.
thank you! and sorry for my bad English.

**Comment by mcdull** [comment]
the spider is just to set network to bridge mode. Virtual Box should have the same option in network.  NAT mode would not work.

**Comment by Danieliverant** [comment]
I did it, still can't connect the siri to the proxy. any other help? 
BTW my computer connected to the internet with a cable, but he has a WiFi (my laptop and ipodtouch connected to him)

**Comment by mcdull** [comment]
did you see ssl connected in log?

**Comment by Danieliverant** [comment]
can you explain me what is SSL and what is the log you talking about? 
sorry for the inconvenient

**Comment by mcdull** [comment]
did you generate certificate file in ./siriproxy and import to your iphone 4s?

**Comment by Danieliverant** [comment]
if you mean the "ce" file - so yes.

**Comment by Danieliverant** [comment]
I try to use another computer, and i use the program VMware instead of VisualBox and I try to change the NAT to BRIDGE but in the BRIDGE it can't connect to the internet but in the NAT it can. what should I do?

**Comment by gotnull** [comment]
@lsd95 don't bother with anything SiriProxy related if you can't access the Internet on your device once you've pointed your DNS to your machine.

**Comment by Danieliverant** [comment]
no no, I can access to WiFi connection if my DNS is in the defult mode.
but I cant access to the VirtualBox DNS and thats why I cant use siriproxy.
