### ISSUE TITLE
SiriProxy error while using with my iPod

### ISSUE THREAD

**Issue by SilenceFictionxD** [plamoni/SiriProxy#254]
Hello everyone, recently I installed Siri Proxy on Ubuntu 11.10 on VMware everything went wall except for the last part.
I installed some plugins but they doesn't work. Nothing does. When I press the siri on my iPod touch 4G (with Spire) Siri opens and doesn't wait for voice input. It just says this:
http://img705.imageshack.us/img705/147/020c.png
And the server connects to the device and those lines appears on the server:
XXX@ubuntu:~/SiriProxy$ rvmsudo siriproxy server
Starting SiriProxy on port 443..
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x0000000177a6b8 @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000001779e20>, @zip_stream=#Zlib::Deflate:0x00000001779dd0, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::SiriIMDB:0x000000018f39b8 @manager=#<SiriProxy::PluginManager:0x00000001779600 @plugins=[...]>>, #<SiriProxy::Plugin::Example:0x00000001a72618 @manager=#<SiriProxy::PluginManager:0x00000001779600 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000001a72348 @signature=4, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000001a72168>, @zip_stream=#Zlib::Deflate:0x00000001a72140, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::SiriIMDB:0x00000001a70d90 @manager=#<SiriProxy::PluginManager:0x00000001a71c18 @plugins=[...]>>, #<SiriProxy::Plugin::Example:0x00000001a6f878 @manager=#<SiriProxy::PluginManager:0x00000001a71c18 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000001a6f468 @signature=5, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000001a6f260>, @zip_stream=#Zlib::Deflate:0x00000001a6f238, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::SiriIMDB:0x00000001a9c120 @manager=#<SiriProxy::PluginManager:0x00000001a9da48 @plugins=[...]>>, #<SiriProxy::Plugin::Example:0x00000001a9b5e0 @manager=#<SiriProxy::PluginManager:0x00000001a9da48 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000001a9b1f8 @signature=6, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000001a9afc8>, @zip_stream=#Zlib::Deflate:0x00000001a9afa0, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::SiriIMDB:0x00000001aca480 @manager=#<SiriProxy::PluginManager:0x00000001a9a848 @plugins=[...]>>, #<SiriProxy::Plugin::Example:0x00000001ac98a0 @manager=#<SiriProxy::PluginManager:0x00000001a9a848 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000001ac9558 @signature=7, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000001ac92d8>, @zip_stream=#Zlib::Deflate:0x00000001ac92b0, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::SiriIMDB:0x00000001ae0d98 @manager=#<SiriProxy::PluginManager:0x00000001ac7708 @plugins=[...]>>, #<SiriProxy::Plugin::Example:0x00000001adfcb8 @manager=#<SiriProxy::PluginManager:0x00000001ac7708 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000001adf6f0 @signature=8, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000001adf268>, @zip_stream=#Zlib::Deflate:0x00000001adf150, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::SiriIMDB:0x00000001ae6bf8 @manager=#<SiriProxy::PluginManager:0x00000001ade278 @plugins=[...]>>, #<SiriProxy::Plugin::Example:0x00000001ae6360 @manager=#<SiriProxy::PluginManager:0x00000001ade278 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000001ae6158 @signature=9, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000001ae5fa0>, @zip_stream=#Zlib::Deflate:0x00000001ae5f50, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::SiriIMDB:0x00000001ae4f10 @manager=#<SiriProxy::PluginManager:0x00000001ae5848 @plugins=[...]>>, #<SiriProxy::Plugin::Example:0x00000001ae4538 @manager=#<SiriProxy::PluginManager:0x00000001ae5848 @plugins=[...]>>]

What should I do?

**Comment by SilenceFictionxD** [comment]
Anyone?

**Comment by edsonaj** [comment]
It's a problem with a plugin.. try to remove all in config file (~/.siriproxy folder) e run it again (don't forget to bundle before).

**Comment by SilenceFictionxD** [comment]
Are you sure? It's happened also when I even didn't edit the config.
But I'll try this when ill get back from school.

**Comment by SilenceFictionxD** [comment]
Still nothing:
XXX@ubuntu:~/SiriProxy$ rvmsudo siriproxy server
Starting SiriProxy on port 443..
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000001405e10 @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000001405ca8>, @zip_stream=#Zlib::Deflate:0x00000001405c80, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: []
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000001405708 @signature=4, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000001405578>, @zip_stream=#Zlib::Deflate:0x00000001405550, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: []
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x000000013f32d8 @signature=5, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x000000013ec5f0>, @zip_stream=#Zlib::Deflate:0x000000013ec6e0, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: []
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x000000013da918 @signature=6, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x000000013d7ce0>, @zip_stream=#Zlib::Deflate:0x000000013d7dd0, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: []
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x0000000139cb68 @signature=7, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000001397f00>, @zip_stream=#Zlib::Deflate:0x000000013984f0, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: []
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000001386110 @signature=8, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000000f45c68>, @zip_stream=#Zlib::Deflate:0x00000000f45c90, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: []
Edit: I even installed new certificates on my iPod and nothing.

**Comment by delrio1110** [comment]
did you grab the keys from a 4s?

**Comment by SilenceFictionxD** [comment]
Is it so important?

**Comment by delrio1110** [comment]
Yes you need the 4s keys for this to work.

**Comment by SilenceFictionxD** [comment]
Is that the problem?
Can someone give me that keys please?

**Comment by ghjansen** [comment]
Hello friend!

Did you found a solution to your problem? I am configuring a proxy and had the same issue.
If you get something can you help me please?

Thank you!

**Comment by SilenceFictionxD** [comment]
No friend... I need some keys from iPhone 4s. Can't start the server without it...
So... I am closing this thread.
