### ISSUE TITLE
Ruby errors?

### ISSUE THREAD

**Issue by xavicr01** [plamoni/SiriProxy#255]
Hello!
After intall Siri Proxy on a clean ubuntu 11.10 virtual machine and run the server to see if its works and i get this message error:

xxx@xxx:~/SiriProxy$ rvmsudo siriproxy server
Starting SiriProxy on port 443..
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0xa53da04 @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0xa53d950>, @zip_stream=#Zlib::Deflate:0xa53d93c, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins loaded: [#<SiriProxy::Plugin::Example:0xa21c2a8 @manager=#<SiriProxy::PluginManager:0xa53d6f8 @plugins=[...]>>]
{"speech_id"=>nil, "assistant_id"=>nil, "session_data"=>nil}
[Warning] Non-4S device connected.
[Info] Found cached session data.
[Info] Found cached speech id.
[Info] Found cached assistant id.
[Info - iPhone] Received Object: LoadAssistant
/home/siriproxy/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/CFPropertyList-2.0.17/lib/rbCFPropertyList.rb:151:in `guess': Unknown class NilClass. Try using :convert_unknown_to_string if you want to use unknown object types! (CFTypeError)
    from /home/siriproxy/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/CFPropertyList-2.0.17/lib/rbCFPropertyList.rb:125:in`block in guess'
    from /home/siriproxy/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/CFPropertyList-2.0.17/lib/rbCFPropertyList.rb:123:in `each_pair'
    from /home/siriproxy/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/CFPropertyList-2.0.17/lib/rbCFPropertyList.rb:123:in`guess'
    from /home/siriproxy/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/CFPropertyList-2.0.17/lib/rbCFPropertyList.rb:125:in `block in guess'
    from /home/siriproxy/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/CFPropertyList-2.0.17/lib/rbCFPropertyList.rb:123:in`each_pair'
    from /home/siriproxy/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/CFPropertyList-2.0.17/lib/rbCFPropertyList.rb:123:in `guess'
    from /home/siriproxy/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/CFPropertyList-2.0.17/lib/rbCFPropertyList.rb:371:in`to_plist'
    from /home/siriproxy/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/connection.rb:192:in `inject_object_to_output_stream'
    from /home/siriproxy/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/connection.rb:134:in`process_compressed_data'
    from /home/siriproxy/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/connection.rb:102:in `receive_binary_data'
    from /home/siriproxy/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/em/protocols/linetext2.rb:94:in`receive_data'
    from /home/siriproxy/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/em/protocols/linetext2.rb:65:in `receive_data'
    from /home/siriproxy/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/em/protocols/linetext2.rb:65:in`receive_data'
    from /home/siriproxy/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/em/protocols/linetext2.rb:65:in `receive_data'
    from /home/siriproxy/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/em/protocols/linetext2.rb:65:in`receive_data'
    from /home/siriproxy/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/em/protocols/linetext2.rb:65:in `receive_data'
    from /home/siriproxy/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/em/protocols/linetext2.rb:65:in`receive_data'
    from /home/siriproxy/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
    from /home/siriproxy/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run'
    from /home/siriproxy/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy.rb:16:in `initialize'
    from /home/siriproxy/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:96:in`new'
    from /home/siriproxy/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:96:in `start_server'
    from /home/siriproxy/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:85:in`run_server'
    from /home/siriproxy/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:37:in `initialize'
    from /home/siriproxy/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/bin/siriproxy:6:in`new'
    from /home/siriproxy/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/bin/siriproxy:6:in `<top (required)>'
    from /home/siriproxy/.rvm/gems/ruby-1.9.3-p0@SiriProxy/bin/siriproxy:19:in`load'
    from /home/siriproxy/.rvm/gems/ruby-1.9.3-p0@SiriProxy/bin/siriproxy:19:in `<main>'

What can I do?

Thanks for your help.

**Comment by titogarrido** [comment]
Same problem here :(
