### ISSUE TITLE
Eventmachine - "Encryption not available"

### ISSUE THREAD

**Issue by mortenmoulder** [plamoni/SiriProxy#256]
When I'm running my SiriProxy on my VPS (ubuntu 11.04), I get this message:

terminate called after throwing an instance of 'std::runtime_error'
what():  Encryption not available on this event-machine

I can start the server fine by using "ruby start.rb", but right when I try to connect with Spire, that's the message I get.

I've tried stuff like reinstalling eventmachine, reinstalling ruby, reinstalling everything... I tried to reinstall libssl-dev aswell, but didn't work either. I tired to remove eventmachine and libssl-dev, then install libssl-dev and then eventmachine, still same error.

I have no idea how to fix this problem :S

**Comment by SilenceFictionxD** [comment]
Try to run Ubuntu 11.10 on VMware. Not 11.04. And then restart the whole procedure following these steps:
https://gist.github.com/1428474

**Comment by mortenmoulder** [comment]
I've successfully installed SiriProxy 3 times on 2 different laptops.
They all used Ubuntu 11.10, but I don't think that's the problem.

The VPS I bought can only get 11.04, but I shall see if I can get 11.10 :)

**Comment by SilenceFictionxD** [comment]
OK. I am having problems myself I think its related to that I don't own an iPhone 4s.
Do you own one? maybe that's the problem.

**Comment by mortenmoulder** [comment]
Unfortunately, I don't.

I have an agreement with a friend who gives me the keys, so I'm satisfied :)

**Comment by SilenceFictionxD** [comment]
Lucky you :)

**Comment by SilenceFictionxD** [comment]
And by the way this device sucks...
The only improvements from the iPhone 4 is the camera, Siri and the chipset thats all.
I call it the iPhone FOR ASS.

**Comment by mortenmoulder** [comment]
Heh, yeah :)

I had to help him install it though, but that didn't take more than 15 minutes.. Max ;)

**Comment by mortenmoulder** [comment]
Yeah true, that's too shitty.
They should come up with some better things, but let's hope they got some better improvements on design and stuff like that on the iPhone 5 when it come (if it come)

:)

**Comment by SilenceFictionxD** [comment]
Or the iPad 3.

**Comment by mortenmoulder** [comment]
Still doesn't work...
I have no idea what could be wrong :(

**Comment by mortenmoulder** [comment]
Still need to fix this issue!
Anyone know how to fix it?
