### ISSUE TITLE
Cannot start the server on port 443

### ISSUE THREAD

**Issue by attapon** [plamoni/SiriProxy#257]
After follow instruction from VDO the last command rvmsudo siriproxy server

unlucky i got this error
# 

root@ipm:~/SiriProxy# rvmsudo siriproxy server
Starting SiriProxy on port 443..
/usr/local/rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy.rb:26:in `rescue in block in initialize': Cannot start the server on port 443 - are you root, or have another process on this port already? (RuntimeError)
    from /usr/local/rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy.rb:17:in`block in initialize'
    from /usr/local/rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `call'
    from /usr/local/rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run_machine'
    from /usr/local/rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
    from /usr/local/rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy.rb:16:in`initialize'
    from /usr/local/rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:96:in `new'
    from /usr/local/rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:96:in`start_server'
    from /usr/local/rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:85:in `run_server'
    from /usr/local/rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:37:in`initialize'
    from /usr/local/rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/bin/siriproxy:6:in `new'
    from /usr/local/rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/bin/siriproxy:6:in`<top (required)>'
    from /usr/local/rvm/gems/ruby-1.9.3-p0@SiriProxy/bin/siriproxy:19:in `load'
#     from /usr/local/rvm/gems/ruby-1.9.3-p0@SiriProxy/bin/siriproxy:19:in `<main>'

i try chk by ps -A 
then found port in use but not show 443

i crop some port to show you

125 ?        00:00:00 kworker/4:2
  223 ?        00:00:00 mpt_poll_0
  224 ?        00:00:00 mpt/0
  241 ?        00:00:00 scsi_eh_4
  264 ?        00:00:00 kworker/0:3
  271 ?        00:00:00 md0_raid1
  275 ?        00:00:00 md2_raid1
  280 ?        00:00:00 md1_raid1
  293 ?        00:00:00 jbd2/md1-8
  294 ?        00:00:00 ext4-dio-unwrit
  341 ?        00:00:00 upstart-udev-br
  359 ?        00:00:00 udevd
  515 ?        00:00:00 udevd
  516 ?        00:00:00 udevd
  540 ?        00:00:00 kworker/1:2
  614 ?        00:00:00 upstart-socket-
  693 ?        00:00:00 jbd2/md2-8
  694 ?        00:00:00 ext4-dio-unwrit
  743 ?        00:00:00 kjournald
  784 ?        00:00:00 sshd
  790 ?        00:00:00 rsyslogd
  801 tty4     00:00:00 getty
# 

troubleshoot
- try reboot server (i use real web server) -> same issue
- ca.pem file can installed to my iphone 4 already, i copy ca.pem to my web server dir
- Spire installed on my iphone 4, ios 5.0.1, set Siriproxy to https://myipserver

anything els i should do
kindly help.

**Comment by attapon** [comment]
i try check netstat -nap

then got this one, i think apache2 use port 443
tcp6       0      0 :::443                  :::\*                    LISTEN      1387/apache2    

# 

root@ipm:~/SiriProxy# netstat -nap
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:9999            0.0.0.0:\*               LISTEN      784/sshd  
tcp        0      0 203.150.228.68:80       182.52.84.28:14671      SYN_RECV    -  
tcp        0      0 203.150.228.68:80       115.87.179.55:53366     SYN_RECV    -  
tcp        0      0 127.0.0.1:7634          0.0.0.0:\*               LISTEN      949/hddtemp  
tcp        0      0 203.150.228.68:53       0.0.0.0:\*               LISTEN      863/named  
tcp        0      0 127.0.0.1:53            0.0.0.0:\*               LISTEN      863/named  
tcp        0      0 0.0.0.0:22              0.0.0.0:\*               LISTEN      784/sshd  
tcp        0      0 0.0.0.0:25              0.0.0.0:\*               LISTEN      1053/master  
tcp        0      0 127.0.0.1:953           0.0.0.0:\*               LISTEN      863/named  
tcp        0      0 0.0.0.0:1723            0.0.0.0:\*               LISTEN      1070/pptpd  
tcp        0      0 0.0.0.0:3306            0.0.0.0:\*               LISTEN      858/mysqld  
tcp        0     48 203.150.228.68:22       175.145.246.26:10613    ESTABLISHED 1521/sshd: tom [pri
tcp6       0      0 :::9999                 :::\*                    LISTEN      784/sshd  
tcp6       0      0 :::80                   :::\*                    LISTEN      1387/apache2  
tcp6       0      0 :::21                   :::\*                    LISTEN      1250/proftpd: (acce
tcp6       0      0 :::53                   :::\*                    LISTEN      863/named  
tcp6       0      0 :::22                   :::\*                    LISTEN      784/sshd  
tcp6       0      0 ::1:953                 :::\*                    LISTEN      863/named  
tcp6       0      0 :::443                  :::\*                    LISTEN      1387/apache2    

# 

my question is can we change port of siriproxy to other port? and how to change it?

Thank in advance

**Comment by attapon** [comment]
ok i fixed problem about port 443 used by apache2

by changing to other port follow -> http://www.cyberciti.biz/faq/linux-apache2-change-default-port-ipbinding/

now can start Siriproxy already but still can't make siri work

what i should do about my iphone settings? T^T

**Comment by SilenceFictionxD** [comment]
You can change the port by editing the config.yml that can be found in the ~/.siriproxy folder. In the file there line there you can change the port. But first look for available ports.

**Comment by edsonaj** [comment]
You need a 4S to get the daily tokens from it and add to SiriProxy.

**Comment by bowtakwah** [comment]
When you run Siriproxy, there should be an output log. Show it to us.
