### ISSUE TITLE
No such file or directory - installed fine and installed a twitter plugin. wont restart

### ISSUE THREAD

**Issue by boyced** [plamoni/SiriProxy#258]
hi, 

installed fine and then tried to install twitter plug in... but get the following

siri@siri-HP-dc5000-SFF-PJ108UT:~$ pwd
/home/siri
siri@siri-HP-dc5000-SFF-PJ108UT:~$ cd SiriProxy
siri@siri-HP-dc5000-SFF-PJ108UT:~/SiriProxy$ cd bin
siri@siri-HP-dc5000-SFF-PJ108UT:~/SiriProxy/bin$ rvmsudo /.siriproxy server
[sudo] password for siri: 
/usr/bin/env: /.siriproxy: No such file or directory
siri@siri-HP-dc5000-SFF-PJ108UT:~/SiriProxy/bin$ /usr/local/rvm/bin/rvmsudo siriproxy server
bash: /usr/local/rvm/bin/rvmsudo: No such file or directory
siri@siri-HP-dc5000-SFF-PJ108UT:~/SiriProxy/bin$ /bin/bash
siri@siri-HP-dc5000-SFF-PJ108UT:~/SiriProxy/bin$ /usr/local/rvm/bin/rvmsudo siriproxy server
bash: /usr/local/rvm/bin/rvmsudo: No such file or directory
siri@siri-HP-dc5000-SFF-PJ108UT:~/SiriProxy/bin$

**Comment by edsonaj** [comment]
You installed the plamoni version or another fork? In my case, it's only:

cd SiriProxy
rvmsudo siriproxy server

**Comment by boyced** [comment]
the plamoni version. Strange started a new ssh session this morning and it worked fine. Albeit couldn't find the siriproxy-twitter plugin

Just wonder if installing the plugin changed an environment variable?

**Comment by boyced** [comment]
when you install a plugin do you also need to do a rake install of it? and do they go into /SiriProxy or .siriproxy ?

**Comment by edsonaj** [comment]
I only put the full file path (drag the file in the terminal and copy the path) in the config file, bundle (command siriproxy bundle) and start the server.

**Comment by boyced** [comment]
ok that fixed it, there's so many bad instructions on the web

**Comment by ghost** [comment]
It errored because you should do ./siriproxy, not /.siriproxy
