### ISSUE TITLE
Siri proxy

### ISSUE THREAD

**Issue by siriproxyusr** [plamoni/SiriProxy#259]
My friend has siriproxy up and running, it says starting on port 443 but when they change 4s dns to ip then no Internet loads and textl doesn't appear in terminal

**Comment by siriproxyusr** [comment]
@Salax who helped me last time and @plamoni ( who created it, it would be great if you could help.

**Comment by FineTralfazz** [comment]
Did you set up a DNS server with dnsmasq?
