### ISSUE TITLE
Assertion failed, file ssl.cpp, abort trap

### ISSUE THREAD

**Issue by odyc** [plamoni/SiriProxy#26]
Hi

Saw another closed issue on this, but I'm having the same exact problem, and I don't think a DNS loop
is causing my problem.

I keep on getting the same error, when I start the server everything seems to be fine (cursor is waiting
but as soon as I hit Siri on my phone I get this error:

MBP-Gery:siriproxy geryduyck$ sudo ./start.rb
Assertion failed: (e > 0), function SslContext_t, file ssl.cpp, line 162.
Abort trap
MBP-Gery:siriproxy geryduyck$

When I ping the Apple server I get this:

MBP-Gery:siriproxy geryduyck$ ping guzzoni.apple.com
PING reg1.guzzoni-apple.com.akadns.net (17.174.4.4): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
...

Although I can see the server's IP in the 17.X.X.X range, it's not responding, but that might be
the case if apple blocks access from my macbook.

I'm not familiar with dns protocols, so I don't know if I'm having problems with a DNS loop as well
or how I could fix this.

(I am connected to the internet with a fixed ethernet connection.
The connection to our router is set up by DHCP, however, our router assigns a fixed IP address to my macbook's MAC address. (in the 192.X.X.X range) I use this address as well in dsnmasq.)

thanks for any advice :-)
G

**Comment by Intyre** [comment]
I also got this error. I fixed it by creating the certificates with openssl. 

In terminal do the following.
1. openssl genrsa -des3 -out ca.key 4096
2. openssl req -new -x509 -days 365 -key ca.key -out iPhone.crt
3. openssl genrsa -des3 -out server.key 4096
4. openssl x509 -req -days 365 -in server.csr -CA iPhone.crt -CAkey ca.key -set_serial 01 -out server.passless.crt
5. openssl rsa -in server.key -out server.passless.key

Send iPhone.crt to your iPhone and copy server.passless.crt and server.passless.key to your SiriProxy directory.

I hope this helps

**Comment by macteo** [comment]
Thanks this solved my problem but I needed to a add one more step before the number 4:

```
openssl req -new -newkey rsa:4096 -nodes -keyout server.key -out server.csr
```

**Comment by odyc** [comment]
thanks for the tip, will try this today and report back if this works for me as well!

**Comment by courtenay** [comment]
Make sure you spelled the server names correctly and set up your proxy with the right server name. I had mistyped 'guzzoni' when generating the cert and saw a similar issue.

**Comment by odyc** [comment]
fixed the issue! siri proxy is up and running! :-)

thanks!!

**Comment by plamoni** [comment]
the gen_certs.zsh (and in upcoming changes, `siriproxy gencerts`) will generate certs automatically without having to mess with openssl directly. It works quite well.
