### ISSUE TITLE
SiriProxy start fail

### ISSUE THREAD

**Issue by jrdennis95** [plamoni/SiriProxy#262]
Okay, so I've tried this multiple times, and I think this might be the closest I've gotten to finishing. I'm confident (not 100% though) that my DNS settings are okay, because as I start the server and attempt to run siri, there's a response on the mac. I know that there's a connection between my mac and my iPhone 4S, but even then, as I start the server and attempt to say 'Test Siri Proxy', it closes Siri very quickly. Here's the error code I receive along with it:

Starting SiriProxy on port 443..
Create server for iPhone connection
/Users/jrdennis95/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/em/connection.rb:304:in `block in start_tls': Could not find /Users/jrdennis95/.siriproxy/server.passless.key for start_tls (EventMachine::FileNotFoundException)
    from /Users/jrdennis95/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/em/connection.rb:302:in`each'
    from /Users/jrdennis95/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/em/connection.rb:302:in `start_tls'
    from /Users/jrdennis95/Desktop/SiriProxy/lib/siriproxy/connection/iphone.rb:15:in`post_init'
    from /Users/jrdennis95/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/em/connection.rb:45:in `block in new'
    from /Users/jrdennis95/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/em/connection.rb:36:in`instance_eval'
    from /Users/jrdennis95/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/em/connection.rb:36:in `new'
    from /Users/jrdennis95/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/eventmachine.rb:1430:in`event_callback'
    from /Users/jrdennis95/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
    from /Users/jrdennis95/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run'
    from /Users/jrdennis95/Desktop/SiriProxy/lib/siriproxy.rb:16:in `initialize'
    from /Users/jrdennis95/Desktop/SiriProxy/lib/siriproxy/command_line.rb:96:in`new'
    from /Users/jrdennis95/Desktop/SiriProxy/lib/siriproxy/command_line.rb:96:in `start_server'
    from /Users/jrdennis95/Desktop/SiriProxy/lib/siriproxy/command_line.rb:85:in`run_server'
    from /Users/jrdennis95/Desktop/SiriProxy/lib/siriproxy/command_line.rb:37:in `initialize'
    from ./siriproxy:6:in`new'
    from ./siriproxy:6:in `<main>'

**Comment by FineTralfazz** [comment]
Run gen_certs.sh (can be found in your SiriProxy/scripts directory), then install the ca.pem file (in .siriproxy) on your iPhone.

**Comment by jrdennis95** [comment]
The script runs, and then it says:

mv: rename /tmp/newcert.pem to /Users/jrdennis95/.siriproxy/server.passless.crt: No such file or directory
mv: rename /tmp/siriCA/cacert.pem to /Users/jrdennis95/.siriproxy/ca.pem: No such file or directory
Done! (For details on any errors, check '/Users/jrdennis95/.siriproxy/cert.log')

is this a case of the gen_certs.sh being in the wrong place? Or do I have to manually rename these things?

**Comment by jrdennis95** [comment]
Oh it's fine :) I reinstalled ruby and rvm, and ran the script via siriproxy gencerts, and it's worked. I'll let you know whether it has an effect on the end result. Thanks :D

**Comment by jrdennis95** [comment]
Ah awesome! After about 20 tries, all I had to do was reinstall RVM and ruby, and it would work. PHEW! Thanks for your help as well :)

**Comment by schmooty** [comment]
jrdennis how did you fix this???!!!!! I am having the exact same issue and ive spent days trying to figure it out. could you explain or clarify what you mean by you ran the scripts via siri proxy gencerts?? and how exactly did you do the suggestion of  Run gen_certs.sh ??

sorry to sound so dumb. I'm word for word having your exact original problem and would do anything to get this fixed!!!!

**Comment by jrdennis95** [comment]
Hey there. Well, I used to be generating the certificate via:
mkdir ca
cd ca
/System/Library/OpenSSL/misc/CA.pl -newca
/System/Library/OpenSSL/misc/CA.pl -newreq guzzoni.apple.com
/System/Library/OpenSSL/misc/CA.pl -sign
openssl rsa -in newkey.pem -out server.passless.key 
cp newcert.pem server.passless.crt
mv server.passless.\* ../

But instead of doing that, I reinstalled RVM and Ruby, and typed siriproxy gencerts to generate the certificate. You need to have installed the siriproxy gem in order for it to generate. I didn't follow the gen_certs.sh because I remember some error appearing. I just used siriproxy gencerts. A good thing to do, is to reinstall RVM/ruby again, and try it. When you're reinstalling ruby, it might even say 'type rvm reinstall' or something like that, and you should do that. message me back with how it goes. :)
