### ISSUE TITLE
Control connection

### ISSUE THREAD

**Issue by Treenity** [plamoni/SiriProxy#265]
Hi, i there a way to control the server access with a unique identifier like UDID?

i mean it's so easy to send URL and cert to anyone that i don't want to be banned because someone find my informations, so i want to control who can connect to my server

i search a function that can control the UDID of the iPhone trying to connect

the best will be :

A allowed.udid file with a list like that :
NICKNAME - UDID - (maybe enter a ending date, after this ate the udid is blocked)

a function in the siriproxy to control connection 

search UDID into allowed.udid WHERE user.udid like udid
if result, then continue the connection
if !result block this iPhone

is it possible, does someone have worked on that already?

**Comment by plamoni** [comment]
Might be possible to use a client side ssl cert for auth. Not sure
about using udid for auth.

-Pete

Sent from my iPhone

On Jan 8, 2012, at 8:49 AM, Ronan Pozzi
reply@reply.github.com
wrote:

**Comment by Treenity** [comment]
i've done a little script, but it mess me the way to identify each iPhone :/
refid, aceid, and the authdata aren't stable and/or can be "hacked"

for the SSL way, if someone can get url + certs, it's finished

**Comment by hazardr** [comment]
Hi there... what script have you created? can you send me the script please :)

**Comment by Treenity** [comment]
script is in dev, i will release it when it will be finished, but thx for the contribution

**Comment by plamoni** [comment]
Treenity: I'm talking about using client side certs. Not sure if it's possible, but if it is, then that'd be how I'd approach this. If you're not familiar with how they work, then you have some research to do.

**Comment by Treenity** [comment]
if it's possible to do in that way, yep, i will look for it

**Comment by ic0nic** [comment]
Is there a script (yes or no)
