### ISSUE TITLE
Dnsmasq troubles.

### ISSUE THREAD

**Issue by gpscar** [plamoni/SiriProxy#266]
I have followed plamoni's instructions exactly as stated in his YouTube videos but continue to recieve the error that I cannot start it.

http://tinypic.com/r/14sfbcw/5

The following are my currently running processes in case anyone knows if one of them might be the source of my problems.

Active Memory: 1.36 GB
Free Memory: 1.63 GB
Wired Memory: 829.6 MB
Used Memory: 2.37 GB
Inactive Memory: 200.3 MB
Total VM: 215.54 GB
Number of processes: 105

PID    Process Name              User       CPU      Real Mem        Virtual Mem  
0      kernel_task               root       16.8     459.6 MB        4.43 GB  
1      launchd                   root       0.0      1.7 MB          2.34 GB  
10     kextd                     root       0.0      3.0 MB          2.33 GB  
11     UserEventAgent            root       0.0      6.0 MB          2.36 GB  
13     notifyd                   root       0.0      1.2 MB          2.34 GB  
14     opendirectoryd            root       0.0      8.6 MB          2.36 GB  
15     configd                   root       0.0      4.0 MB          2.36 GB  
16     diskarbitrationd          root       0.0      1.6 MB          2.33 GB  
17     fseventsd                 root       0.0      10.3 MB         2.74 GB  
18     syslogd                   root       0.0      880 KB          2.34 GB  
19     powerd                    root       0.0      1.7 MB          2.35 GB  
20     distnoted                 root       0.0      1.7 MB          2.33 GB  
23     securityd                 root       0.0      5.2 MB          2.35 GB  
48     awacsd                    root       0.0      9.2 MB          2.35 GB  
50     ntpd                      root       0.0      1.3 MB          2.32 GB  
52     warmd                     nobody     0.0      2.5 MB          2.34 GB  
53     usbmuxd                   _usbmuxd   0.0      3.3 MB          2.35 GB  
55     special_file_handler      root       0.0      1.3 MB          2.33 GB  
56     SystemStarter             root       0.0      840 KB          2.33 GB  
58     stackshot                 root       0.0      992 KB          2.33 GB  
60     revisiond                 root       0.0      2.0 MB          2.34 GB  
64     mtmfs                     root       0.0      4.2 MB          2.37 GB  
65     mtmd                      root       0.0      16.9 MB         2.36 GB  
66     mds                       root       0.1      119.3 MB        2.64 GB  
68     loginwindow               georgesour 0.0      19.0 MB         2.40 GB  
70     KernelEventAgent          root       0.0      844 KB          2.33 GB  
71     kdc                       root       0.0      2.2 MB          2.33 GB  
73     hidd                      root       0.1      1.6 MB          2.34 GB  
75     dynamic_pager             root       0.0      636 KB          2.32 GB  
80     autofsd                   root       0.0      1.2 MB          2.33 GB  
82     applepushserviced         root       0.0      6.2 MB          2.35 GB  
84     tcprelay                  root       0.0      396 KB          588.1 MB  
85     novacomd                  root       0.0      796 KB          596.5 MB  
86     GadgetTrakDaemon          root       0.0      3.0 MB          614.8 MB  
87     wpsd                      root       0.0      1.5 MB          599.0 MB  
88     lsd                       root       0.0      6.6 MB          617.8 MB  
92     coreservicesd             root       0.0      27.5 MB         2.39 GB  
97     netbiosd                  _netbios   0.0      1.8 MB          2.35 GB  
107    WindowServer              _windowser 9.4      78.6 MB         2.80 GB  
113    CVMServer                 root       0.0      960 KB          2.33 GB  
124    logind                    root       0.0      1.1 MB          2.33 GB  
137    launchd                   georgesour 0.0      1.3 MB          2.34 GB  
140    UserEventAgent            georgesour 0.0      18.2 MB         2.36 GB  
141    distnoted                 georgesour 0.0      3.4 MB          2.34 GB  
147    Dock                      georgesour 0.0      61.9 MB         2.45 GB  
148    talagent                  georgesour 0.0      14.8 MB         2.37 GB  
149    pboard                    georgesour 0.0      872 KB          2.32 GB  
150    SystemUIServer            georgesour 0.2      59.0 MB         2.49 GB  
151    Finder                    georgesour 0.0      107.7 MB        2.57 GB  
152    coreaudiod                _coreaudio 0.0      12.4 MB         2.34 GB  
159    fontd                     georgesour 0.0      5.4 MB          2.38 GB  
168    warmd_agent               georgesour 0.0      1.2 MB          2.34 GB  
169    ubd                       georgesour 0.0      19.1 MB         2.36 GB  
174    imagent                   georgesour 0.0      12.0 MB         2.35 GB  
179    AirPort Base Station Agen georgesour 0.0      3.1 MB          2.33 GB  
180    Seagate Storage Gauge     georgesour 0.0      2.9 MB          633.9 MB  
189    GrowlHelperApp            georgesour 0.0      23.7 MB         2.37 GB  
190    Caffeine                  georgesour 0.0      16.3 MB         2.37 GB  
192    HyperDock Helper          georgesour 0.0      59.3 MB         2.44 GB  
193    iTunes Helper             georgesour 0.0      10.0 MB         2.36 GB  
194    Jawbone Updater           georgesour 0.1      20.0 MB         702.1 MB  
195    FreeMemory                georgesour 0.0      21.8 MB         2.39 GB  
202    Dropbox                   georgesour 0.0      36.0 MB         693.4 MB  
205    PhotoStreamAgent          georgesour 0.0      20.8 MB         2.36 GB  
214    storeagent                georgesour 0.0      19.1 MB         2.36 GB  
215    GadgetTrak                root       0.0      5.3 MB          619.8 MB  
234    com.apple.dock.extra      georgesour 0.0      22.8 MB         2.38 GB  
358    AppleSpell.service        georgesour 0.0      10.1 MB         2.36 GB  
386    Little Snitch UIAgent     georgesour 0.0      9.0 MB          655.6 MB  
401    mDNSResponder             _mdnsrespo 0.0      4.2 MB          2.36 GB  
492    dnsmasq                   nobody     0.0      552 KB          2.32 GB  
514    filecoordinationd         root       0.0      1.7 MB          2.33 GB  
1352   cookied                   georgesour 0.0      2.3 MB          2.33 GB  
13912  launchd                   _spotlight 0.0      836 KB          2.34 GB  
13915  distnoted                 _spotlight 0.0      1.2 MB          2.33 GB  
13987  Terminal                  georgesour 0.0      44.0 MB         2.41 GB  
14117  iTunes                    georgesour 0.0      129.5 MB        2.52 GB  
14122  racoon                    root       0.0      2.2 MB          2.34 GB  
14124  AppleMobileDeviceHelper   georgesour 0.0      6.7 MB          616.2 MB  
14136  dbfseventsd               root       0.0      448 KB          582.7 MB  
14137  dbfseventsd               root       0.0      4.3 MB          590.7 MB  
14138  dbfseventsd               georgesour 0.0      176 KB          582.7 MB  
14166  lsboxd                    georgesour 0.0      3.1 MB          2.35 GB  
14182  DashboardClient           georgesour 0.0      48.7 MB         3.39 GB  
14183  DashboardClient           georgesour 0.0      12.4 MB         650.6 MB  
14187  mdworker                  georgesour 0.0      31.1 MB         2.37 GB  
14188  Google Chrome             georgesour 0.1      77.7 MB         891.5 MB  
14191  taskgated                 root       0.0      2.8 MB          2.35 GB  
14193  Google Chrome Worker      georgesour 0.0      23.7 MB         743.8 MB  
14194  Google Chrome Worker      georgesour 0.0      21.8 MB         743.0 MB  
14195  Google Chrome Renderer    georgesour 4.7      103.6 MB        958.7 MB  
14202  Shockwave Flash (Chrome P georgesour 5.4      75.5 MB         1.11 GB  
14203  ocspd                     root       0.0      3.9 MB          2.35 GB  
14205  Quick Look Helper         georgesour 0.0      23.5 MB         2.86 GB  
14206  mdworker                  _spotlight 0.0      12.4 MB         2.36 GB  
14208  login                     root       0.0      2.0 MB          2.33 GB  
14209  bash                      georgesour 0.0      1.9 MB          2.32 GB  
14238  VTDecoderXPCService       georgesour 0.0      26.5 MB         2.38 GB  
14283  Google Chrome Worker      georgesour 0.0      60.6 MB         817.2 MB  
14291  Google Talk NPAPI Plugin  georgesour 0.0      11.4 MB         695.6 MB  
14298  launchdadd                root       0.0      1.7 MB          2.34 GB  
14299  Activity Monitor          georgesour 12.2     53.5 MB         2.47 GB  
14301  xpchelper                 georgesour 0.0      4.4 MB          2.33 GB  
14302  activitymonitord          root       2.6      1.4 MB          2.33 GB  
14303  automountd                root       0.0      1.9 MB          2.34 GB

**Comment by plamoni** [comment]
TCP/443 is in use. Probably by a web server. Also make sure little
snitch isn't blocking the traffic.

-Pete

Sent from my iPhone

On Jan 8, 2012, at 10:04 AM, gpscar
reply@reply.github.com
wrote:

**Comment by gpscar** [comment]
I'm just not sure what could be using it. And Little Snitch isn't.
