### ISSUE TITLE
plugins...

### ISSUE THREAD

**Issue by hazardr** [plamoni/SiriProxy#267]
Hi There... I followed westbaer proxy and all works well, however, when i add plugins like from plamoni (like IMDB), the server doesnt cache iphone 4S keys anymore nor does it work...

Does plugins only work with 4S? if not, how can i install plugins on westbaer proxy?

Thanks in advance

**Comment by ghost** [comment]
It works fine to me.
I sometimes come up to that issue too - not caching my keys
What I do then is trying to use Siri on non-4S device then it caches again fine
I use westbaer's copy too

**Comment by ghost** [comment]
You might wanna try siriproxy bundle and update

**Comment by Treenity** [comment]
personally i can't cache anything with westbaer/plamony proy :/

**Comment by jaminmc** [comment]
I also had problems with the westbaer fork, so I made my own with modified code from http://www.ketchup-mayo-senf.de/blog's modified super old siriproxy. Feel free to check it out :)

**Comment by hazardr** [comment]
i see the problem... i use westbaer fork and when I add the plugins, I do siriproxy update and it updates the for to plamoni... 

it says: Installing latest code from git://github.com/plamoni/SiriProxy.git [master]

This causes problems... how can I set the proxy to update from westbaer fork when I do a siriproxy update.... the plugins, ill still download from plamoni (hopefully that will work)...

I see that plamoni's fork doesnt cache 4S keys and inturn doesnt allow 4 to work

**Comment by hazardr** [comment]
Can anyone offer assistance on the above please ...

Thanks

**Comment by edsonaj** [comment]
You don't need to update, just bundle when install new plugins.
