### ISSUE TITLE
Saving Speech into MP3?

### ISSUE THREAD

**Issue by Bubelbub** [plamoni/SiriProxy#268]
Hello "Community" of Issues, ^^

know anybody here, how i can save the Sended Speech Data to SiriProxy as MP3?

Okay, let´s start ...
Step...
1.) Saving object["properties"]["packets"] in connection.rb Line ~ 200 (Function: prep_received_object)

hmm, And more?
I know, that the Codec is "Speex_WB_Quality8".
But https://github.com/applidium/Cracking-Siri don´t help.

I hope, that anybody can help me to resolve this "Problem".

Why would i know, how i can save the Speech?
Because i would script a Google Voice API SiriProxy.
The rest of Script is easy, but ... How i decode the Data which saved in Step 1???

The Decoding is my Problem!

Yours Bubelbub :]

**Comment by osousa** [comment]
I'm looking for the same as you. I'll be watching this thread and i'll try to come up with a solution.

**Comment by janrueth** [comment]
https://github.com/Eichhoernchen/SiriServer-

check this out, I just uploaded my siri server, it decodes the speex, reencodes it to flac and uses google for recognition... however I have not implemented any interaction back to the iDevice yet... Maybe my python code helps you understand how to decode stuff works... But I think i'll stop developing it... I know to less about the siri protocol, and got no 4S to figure out correct responses to requests from the iphone

**Comment by Bubelbub** [comment]
Ha, Thank you very VERY Much!!!

You have taken me a lot of work!

And now i can implement my "Responses" to your Proxy :)
Then i have GoogleVoiceSiri.

How ever: -> Thank you <-
I think if this "Issue" has a "I Like" Button, many people would click it ^^

**Comment by janrueth** [comment]
glad you like it.

Yeah, GoogleVoiceSiri was my goal too.

However, I'm not sure you can directly use it. There is no interaction with Apple Siri Servers. Sometimes my iPhone 4 just sends requests I don't know correct answers to, like the "CreateSessionInfoRequest", I have no idea how a valid response looks like, I know its called "CreateSessionInfoResponse" but I don't know the content... If my phone sends this request I first need to connect it using plamonis proxy to apple, then it will work with mine.

What I also wanted to do was to look at the assistant creation and maybe back my server with a small database to support assistant creation and loading... but I cannot spend too much time on this at the moment, I'm kind of busy with other stuff..

**Comment by Bubelbub** [comment]
Okay, you aim the Goal and shot the Ball ^^
I´m failed to aim the Goal, xDD

And hmm, i know what you mean.
I hope the Connection with SpeechRecognizion is "perfect" to Googles Servers.
The Rest with Answers etc. i resolved.

How i said, only the Aim with "Apples Speex" to "Flac" is failed.
But when you mean, you have solved this INClUSIVE to send "Flac" to Googles Servers...
Perfectly ^^

I hope if i try the Script in few Hours, i can connect to SiriProxy, Speech to Spire and on the PC-Screen i get the Google Answer.
This is a Dream ^^ But if not, i can made my Dream true with my Essentials/Tools/Scripts.

O.k. then i wait for try it

**Comment by janrueth** [comment]
Just made some tests... It works pretty good, at least when I speak german, haven't tried english yet. The server outputs the result which google translates to the console... sometimes hard to spot because of all the other output the server does.^^

**Comment by Bubelbub** [comment]
Perfecter as Perfect.
I´m work for "WeSpire".
https://www.facebook.com/WeSpire

It is a German Projekt about Spire Services.

But when you mean:::
The server outputs the result which google translates to the console..
Then my Dream becomes true ^^
Cool :D

I think, the British/American Developers have more Know-How as we Germans ^^

**Comment by janrueth** [comment]
Ah I did not know about the existence of such a project... 

Also wenn ich euch helfen kann, sagt bescheid, wenn ihr fragen zu meinem code habt... ist recht messy... hab das während ner zugfahrt gecoded

**Comment by Bubelbub** [comment]
Das ist spitze ;)
Also ich denke das mit dem Encoden/Decoden haben Sie durch Google gefunden ^^
Aber sonst der Rest... während einer Zugfahrt...
Echt Respekt ^^

Über Github müsste ich ja Ihre Email Adresse haben.
Wenn es etwas gibt, informiere/frage ich Sie über das Github-Kontaktformular :]

Auch auf Deutsch nochmal:
Danke!
Also dass der SiriProxy aktuell wirklich das gesagte über Google ausgibt ist einfach der hammer ;)

**Comment by janrueth** [comment]
Naja wie die packets aussehen und wie es codiert ist steht ja schon in https://github.com/applidium/Cracking-Siri, ich hab mir lediglich ergooglet wie man c libraries in python nutzt und hab sogar schon nen speex prototyp bei google gefunden, der war allerdings nicht direkt nutzbar mit den apple paketen. In meinem code wird Speex -> PCM -> FLAC recodiert, man hätte auch wieder nach Speex gehen können, das verstehen die google server auch, allerdings denke ich, dass durch erneutes codieren in speex weitere sprachqualität verloren geht, also hab ich mich für flac entschlossen. 

Es darf auch von mir aus beim Du bleiben^^ so alt, dass ich ein Sie verlange bin ich noch nicht :D

**Comment by Bubelbub** [comment]
Achso...
Eichhoernchen has not provided an email address.

Geht also nicht.

Frage ich mal hier.
Da das ganze ja Python ist.
Wäre es möglich so eine Art Converter zu schreiben.
Dass ich per Ruby die gespeicherten Pakete als datei speichere, danach per SSH beispielsweise "python convert.py" eingebe und die Datei dann wieder gelesen wird, mit der Response als Inhalt?

Wenn nicht wäre auch nicht schlimm, muss ich alles auf Python umschreiben ^^

**Comment by janrueth** [comment]
Ich schreib dich mal über boerse an ^^ gerade gesehen das du da auch was gepostet hast

Klar wär das möglich... ist nur naja... nicht wirklich elegant... würde entweder meinen code einfach in ruby übersetzten, denke da wird es auch ne art ctypes library geben. Ich mag python lieber als ruby, daher python

**Comment by ghost** [comment]
Nur weiter so!
Echt Respekt!
