### ISSUE TITLE
Using SiriProxy and Spire without guzzoni

### ISSUE THREAD

**Issue by osousa** [plamoni/SiriProxy#270]
So, i have installed the server proxy, it was a bit of a pain in the ass, there were dependencies, errors, files missing, etc. etc. , but i've came up to set it functional (At least i think so).

MacBook-Pro-de-Helder-Sousa:plamoni-SiriProxy-5ee281c sousa$ telnet guzzoni.apple.com 443
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
telnet: Unable to connect to remote host
MacBook-Pro-de-Helder-Sousa:plamoni-SiriProxy-5ee281c sousa$ 

I have an iPhone 4, so i can't really connect to guzzoni, but i would like to interact with Spire and for example, Google Voice. I don't see why wouldn't this be possible, unless the sound files are compressed in a way that the Google Voice API could'nt interpret.

This is what i get everytime i use Siri, pretty useless for now. I really would like to use Spire for something if possible :)

MacBook-Pro-de-Helder-Sousa:plamoni-SiriProxy-5ee281c sousa$ rvmsudo siriproxy server
Password:
Starting SiriProxy on port 443..
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000100a4e560 @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000100a4e3f8>, @zip_stream=#Zlib::Deflate:0x00000100a4e3d0, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000100b4d060 @manager=#<SiriProxy::PluginManager:0x000001008c96e0 @plugins=[...]>>]

Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000100b4cea8 @signature=4, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000100b4cd40>, @zip_stream=#Zlib::Deflate:0x00000100b4cd18, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000100b53ed8 @manager=#<SiriProxy::PluginManager:0x00000100b4c868 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000100b53cd0 @signature=5, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000100b53af0>, @zip_stream=#Zlib::Deflate:0x00000100b53ac8, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000100b52dd0 @manager=#<SiriProxy::PluginManager:0x00000100b53500 @plugins=[...]>>]

So, the main goal would be to intersect the audio files. It's pretty hard to sniff the 443 port if not impossible, so the best approach would be to intersect using siriproxy itself, but Rubi coding is new to me. 

I know it's possible to get these audio files, a brazilian Kid done it, using dragon dictation and Siri, porting the Siri to Portuguese for the first time :)

**Comment by janrueth** [comment]
I'm creating an own siri server right now using python, I orient at this ruby server, however as I have no iPhone 4S and having no logs available, it is difficult for me to impersonate the AppleServer as I don't know valid answers to the requests the iPhone sends... 

But my idea was to use the google speech api. However without details on the answers to several request I'm kinda stuck.

So I'm not really far with the server...
