### ISSUE TITLE
Help!! My SiriProxy hangs with custom plugins...

### ISSUE THREAD

**Issue by ghost** [plamoni/SiriProxy#272]
So I've wrote a few custom plugins but for SiriProxy (grabbing scores for various sports) but I'm running into a problem.  Everytime I try to use my plugins twice in a row, I run into issues.  I'm a n00b when it comes to ruby/siri programming so I'm pretty confident that there's a problem with my code.  When I give a command the first time, i.e. hockey games, basketball games, etc., it works great. However, when I try to use any of them again, SiriProxy will take Start a Speech Request, take in speech packets, then finish speech when appropriate however it gives no response.  When I clear out of the second request (either by pressing home or the microphone) and try again it works.  Then continues to go in this pattern, works, doesn't work, works, doesn't work, etc.,  I've posted my code to my github account and was wondering if someone could take a look and tell me what I'm doing wrong and give me some pointers on how to clean up my code.  I come from a C background so all this is taking a little getting used to.  I appreciate any help I can get.  Thanks
ay00 

BTW,
I'm looking at my loops as the cause of the problem.  I think when I interrupt them by pressing the mic or home button, it's not giving a chance for the request to complete, but I could be talking out of my arse.  Just a thought.

**Comment by mrmosconi** [comment]
Sounds like you're experiencing this issue: https://github.com/plamoni/SiriProxy/issues/143

No one seems to know how to fix it, and it mysteriously affects only some people.

At least it's not your code ... :-)

**Comment by ghost** [comment]
This is definitely it!  I don't suppose any progress has been made on this front?
