### ISSUE TITLE
How can i capture everything passed to "listen_for"

### ISSUE THREAD

**Issue by JBX028** [plamoni/SiriProxy#274]
Hi,

Let's say I created a "listen_for" according this patern :

``` ruby
listen_for /(A|B|C) test (.*)/i do |capture|
```

When I print "capture" (puts capture), i can see either A or B or C depending on what i said, but I do not see what has been captured accross (.*)

How can I capture what has been passed to (.*) ?

Thanks in advance for your help

**Comment by muhkuh0815** [comment]
do |capture1|capture2| should work

**Comment by JBX028** [comment]
Thanks for your quick reply
It's indeed ok with :

``` ruby
listen_for /(A|B|C) test (.*)/i do |capture1,capture2|
```

but i cannot capture (.*) with this pattern:

``` ruby
listen_for /(A|B|C) test (D|E) (.*)/i do |capture1,capture2,capture3|
```

capture3 is always equal to nil....

Any idea ?

Thanks!

**Comment by wmacevoy** [comment]
``` ruby
listen_for /((A|B|C) test (D|E) (.*))/i do |phrase|
  # this should always work out
  if phrase =~ /(A|B|C) test (D|E) (.*)/i
    capture1=$1
    capture2=$2
    capture3=$3
    ...
  end
end
```
