### ISSUE TITLE
Alternate the example Plugin

### ISSUE THREAD

**Issue by ljbergmann** [plamoni/SiriProxy#275]
Hey i have tried to alternate the example-plugin but nothing changes! I restated the server, bundeled the server new and make the rake file in the plugin folder and boundeld the plugin new, but nothing change. what i have to do!

**Comment by edsonaj** [comment]
What have you did and what you want to do?

**Comment by ljbergmann** [comment]
First i change the answer of siri in the example-plugin, after that i use the command rake install in the example-plugin after that i bundeled the siriproxy new. that was all what i done. After a restart of the proxy there was the old answer not the new!

**Comment by edsonaj** [comment]
You don't have to rake install the plugin, just to bundle the siriproxy e start it again. Try to change the version of the plugin in the gemspec file, so when you bundle you can see if it's the new version or not, or copy the folder and create a "new" plugin, but for that you should edit de config file in the ˜/.siriproxy folder.

**Comment by ljbergmann** [comment]
i will try it thank you for your help

**Comment by ljbergmann** [comment]
i did it and change the version. when i bundel sirirproxy it is the new version but jet the plugin do not responde!

**Comment by edsonaj** [comment]
But the speech is right? Try to put a single word in the listen_for and see if it works.

**Comment by ljbergmann** [comment]
i haven´t change the listen_for ! i only change the output!

**Comment by edsonaj** [comment]
But it is giving the old output or none?

**Comment by ljbergmann** [comment]
there is no responde of the plugin
i have tested it with the siriproxy console and the iphone

**Comment by muhkuh0815** [comment]
in what directory have you changed the file ?
  /user/xxx/SiriProxy/plugins/ ...

or  user/xxx/.rvm/gems/ruby 1.9.3/gems/siriproxy 0.3.0/plugins/ ...

**Comment by ljbergmann** [comment]
In the first one

**Comment by muhkuh0815** [comment]
try to find it in the second one, but if you change it beware of siriproxy update :-)

**Comment by ljbergmann** [comment]
thanks it works

**Comment by muhkuh0815** [comment]
you can also change the path in the config.yml  to /user/xxx/SiriProxy/plugins/ ...

so it finds your already edited plugin.

**Comment by ljbergmann** [comment]
Heah that is a good idea! I have a Little Question why er have in .rvm and in the Siriproxy Folder the Same Things why it  isnt in one?

**Comment by muhkuh0815** [comment]
not sure but with the initial siriproxy release it was in  user/siriproxy, then in the latest version when gems where used it moved there, probably has to do with ruby itself or rvm ...

**Comment by ghost** [comment]
Hello you two.

I did use the westbear proxy, but I think that doesn't matter to my problem.

So, even if I change the "config.yml" in "~/.siriproxy", my "SiriProxy" would not be updated with my changed siriproxy-example.
I've changed the Version in "siriproxy-example.gemspec" and as i ran bundle in ~/SiriProxy, the command line told me it is using Version 0.0.2 of siriproxy-bundle from "./SiriProxy/Plugins/".

No matter to that message the Output didn't change to what i edited for "test siri proxy"...

Finally changes in "user/xxx/.rvm/gems/ruby 1.9.3-p0@SiriProxy0.3.0/gems/siriproxy 0.3.0/plugins/siriproxy-example/siriproxy-example.rb did" changed something after I ran "bundle" in "./SiriProxy"

So, what did or am I doing wrong?

**Comment by edsonaj** [comment]
Try to copy the plugin folder to your Documents folder for example and change the path in the config.yml file, bundle (inside ~/SiriProxy) and run it again.

**Comment by ghost** [comment]
Sry, which plugin folder to what Documents folder?

**Comment by edsonaj** [comment]
Copy any plugin folder that you have modified to any other folder on your computer and change the path in config.yml file (It should be the only plugin in the config.yml), after just bundle and test (you can also change the listen_for to something more easy to say, I used to test it with "You don't say" phrase).

Or delete both siriproxy folders and reinstall everything.

**Comment by shameer99** [comment]
same happen to me. i just go to config.yml in ~/.siriproxy and change path of siriproxy-example to actual path

**Comment by ic0nic** [comment]
start a fresh install of ubuntu 10.11 follow the instructions on https://github.com/ic0nic/The-Four-Little-Pigs-Siri-Proxy

for instructions scroll down

**Comment by AndrewRayCode** [comment]
https://github.com/plamoni/SiriProxy/wiki/Plugin%20Developer%20Guide

Please close this ticket.
