### ISSUE TITLE
Help pls :) Proxy wont show "[Warning] Non-4S device connected."

### ISSUE THREAD

**Issue by ghost** [plamoni/SiriProxy#276]
Hello there,

I've got an issue.

My SiriProxy is running fine.
I'd just read this manual and did it step by step http://methoddk.com/siriguide/

So far...

I´d enabled an pptpd-server for a friend of mine to connect to ma SiriProxy with his iPhone 4S.
This worked so far.
After I was able to see, what he is talking to Siri, and everything went fine I tried my iPhone 4, but actually it wouldn't work.

I did some research on Google and github. Sry, nothing found to help me.

The iPhone 4S was working probably, only thing screws me up is my own phone.

I'm running Windows 7, with a VM-Ware Virtual Linux-Server.
SiriProxy is up and running, "Test Siri Proxy" worked fine for the 4S.
But all I get for my iPhone 4 from SiriProxy is this:
[ INFO - GUZZONI ] Received Object : SessionValidationFailed
[ INFO - GUZZONI ] Received Object : CommandFailed

And as already mentioned:
There is no message like : [Warning] Non-4S device connected.

PS.: I used the Guide for dynamic WAN because I live in Germany :) so excuse me for my bad english...

**Comment by edsonaj** [comment]
You have to grab the keys from the 4s in order to use a non-4s. Try using the westbaer fork, it will do this for you.

**Comment by ghost** [comment]
I did the test with westbear today..

It works very fine ;) 
Thx for reply edsonaj

Can be Closed
