### ISSUE TITLE
GPL for code

### ISSUE THREAD

**Issue by sakjur** [plamoni/SiriProxy#278]
Hi!

This is not a software issue rather than a legal one.
By using CC BY-SA-NC for SiriProxy, you may or may not stop companies from ever using SiriProxy (even if they _do_ release the code back to you and credit you) - but most importantly, the CC-foundation suggests that you should use a GPL-compatible license (which CC BY-SA-NC is _not_) instead of a CC license.

See http://creativecommons.org/software and http://wiki.creativecommons.org/FAQ#Can_I_use_a_Creative_Commons_license_for_software.3F for more information.

I just wanted to make you aware about what the Creative Commons people says about using CC for code - best of luck w/ your project and if someone gives me an iPhone I might actually decide to use SiriProxy just for the fun of it :)

**EDIT:** The "issue" about companies using SiriProxy might not be an issue in your pov, but the fact that CC is not made for software could be ;)

**Comment by plamoni** [comment]
Yeah, I learned of this later. I'm really considering a change. Thank you
for the suggestion.

-Pete

On Tue, Jan 17, 2012 at 4:24 AM, Emil Tullstedt <
reply@reply.github.com

**Comment by jimmykane** [comment]
I would like that too.
