### ISSUE TITLE
How to autostart siriproxy on OSX Lion?

### ISSUE THREAD

**Issue by ntetreau** [plamoni/SiriProxy#280]
Hi, I've successfully setup siriproxy on OSX Lion.  I'd like the server to start automatically at boot.  I've install rvm in ~/.rvm and I'm currently starting the server in my Siriproxy/bin folder using "rvmsudo ./siriproxy server" .

Any idea what could be done to autostart the server?  Thanks.

**Comment by Deanmv** [comment]
Open apple script and use this script:

tell application "Terminal"
    activate
    do script "rvmsudo siriproxy server"
    do script "_password_" in window 0
end tell

where _password_ is your password (don't leave in the \* *)

Save this as an application, then in Sys Pref -> Accounts -> Login items navigate to that application to make it start on boot. 

WARNING: Your password will be shown in plain text in the terminal window on boot.

**Comment by plamoni** [comment]
You should see about port redirection of some sort. That way you can run SiriProxy as an unprivileged (read: non-root) user. This will save you from having to save your password in plaintext like this.

**Comment by Deanmv** [comment]
So you could just do:

tell application "Terminal"
activate
do script "cd ~/siriproxy/bin" (assuming you have saved it there)
do script "./siriproxy server --port 4000" in window 0
end tell

where port is anything you want it to be as 4000 could be used on your system.

**Comment by Alsaegh** [comment]
oh nice ,, can do the same thing on Ubuntu ?

**Comment by Deanmv** [comment]
Most likely, not used it on Ubuntu myself but could probably be done.
