### ISSUE TITLE
Rum SiriProxy on the iDevice

### ISSUE THREAD

**Issue by fredskronk** [plamoni/SiriProxy#283]
Hello,

I wonder if it would be possible to actually run the SirProxy on the phone itself. That would open up for devolving tweaks for the masses plus the coding would be straight forward and rather easy. 

Would love to be able to launch my tweaks into Cydia. 

Thanks,

**Comment by muhkuh0815** [comment]
there is a project called AssistantExtentions in Cydia, which uses plugins to alter siri directly on the iphone.
but till now it only works in english, and you need to write your plugins in XCode

but it looks very promising
search for it in cydia or here look here http://ae.k3a.me/
