### ISSUE TITLE
Cant do anything!!

### ISSUE THREAD

**Issue by JRIMBRI** [plamoni/SiriProxy#285]
ive had this problem for the past two days ive re did siriproxy at least 10 times. I install siriproxy via terminal in ubuntu it works and test siriproxy works aswell but when i try to bin/siriproxy update after cd SiriProxy. to install a plugin i get this error

bin/siriproxy:4:in `require': ./bin/../lib/siriproxy/command_line.rb:74: syntax error, unexpected '>' (SyntaxError)
    repl = -> prompt { print prompt; cora.process(gets.chomp!) }
             ^
    from bin/siriproxy:4

Nothing works!!

**Comment by Gobbyparts** [comment]
I'm having the exact same issue! I've followed every step down to the t, not sure what we're doing wrong. I can't even get siri proxy to start running again after I close the terminal. Do you seriously have to go through these steps every time to start it?

**Comment by JRIMBRI** [comment]
SAME IT ONLY WORKS WHEN I DO INITIAL START!!!! It's so annoying I need help

**Comment by dan122334455** [comment]
after you install, the updates ruin all the plugins...  Once you add a plugin, just type siriproxy bundle       and then type bundle install        let me know if this helps.
