### ISSUE TITLE
Unrecognized command line argument

### ISSUE THREAD

**Issue by bihlmaier** [plamoni/SiriProxy#286]
When i try to install the siriproxy.gem, it succeeds, but when i will generate the certificates with
rvm siriproxy gencerts

it says:
Unrecognized command line argument: 'siriproxy' ( see: 'rvm usage' )

Do you know how to solve this problem?

**Comment by plamoni** [comment]
Take out the "rvm" part.

-Pete

**Comment by bihlmaier** [comment]
Thanks.

But now, it says:
root@vsrv31342:/The-Three-Little-Pigs-Siri-Proxy# rake install
siriproxy 0.8b built to pkg/siriproxy-0.8b.gem
siriproxy (0.8b) installed
root@vsrv31342:/The-Three-Little-Pigs-Siri-Proxy# siriproxy gencerts
-bash: siriproxy: Command not found.
root@vsrv31342:/The-Three-Little-Pigs-Siri-Proxy#

**Comment by bihlmaier** [comment]
And when I navigate to the proxy-folder, it says:

ruby ruby-1.9.3-siriproxy is not installed.
To install do: 'rvm install ruby-1.9.3-siriproxy'

If I do this, it says:

Installing Ruby from source to: /usr/local/rvm/rubies/ruby-1.9.3-siriproxy, this may take a while depending on your cpu(s)...

ruby-1.9.3-siriproxy - #fetching 
HEAD is now at 6c02761 \* 2012-01-20
From git://github.com/ruby/ruby
- branch            ruby_1_9_3 -> FETCH_HEAD
  Already up-to-date.
  error: pathspec 'iriproxy' did not match any file(s) known to git.
  There has been an error while trying to checkout the source branch.
  Halting the installation.
  There has been an error fetching the ruby interpreter. Halting the installation.

I'm using Debian Squeeze.

**Comment by plamoni** [comment]
Haven't tried installing stuff through rvm install... The problem with it
not recongnizing the "siriproxy" command is probably because the bin
directory for RVM is not in your path.

Did you do "rvm use 1.9.3"?

-Pete

**Comment by bihlmaier** [comment]
Yeah, I did "rvm use 1.9.3 --default"

And in my Proxy-Folder is a bin folder with siriproxy

But it says permanently when navigating in proxy folder that ruby ruby-1.9.3-siriproxy is not installed

**Comment by evovtech** [comment]
I'm having issues on "/usr/bin/env: siriproxy: No such file or directory".

I start fresh using Virtual Box and VMWare on PC with Ubuntu 11.10. I follow all the commands as instructed in this link 
"https://gist.github.com/1428474". All commands are OK, but after I enter "rvmsudo siriproxy server", an error msg appear "/usr/bin/env: siriproxy: No such file or directory".

Please help. Thanks.

**Comment by notmyname4** [comment]
@evovtech Did you get this issue resolved?

SiriProxy starts right after I install, but when I reopen terminal i get "/usr/bin/env: siriproxy: No such file or directory". It was operational but I had to reinstall. I'm using the same instructions as the previous (working) installation but I have the same issue on 2 laptops.

**Comment by calvin-76** [comment]
Take out the "rvm" part. ??? don't understand 
i dont am english
