### ISSUE TITLE
UDID Whitelist

### ISSUE THREAD

**Issue by mackmgg** [plamoni/SiriProxy#287]
Is there a way to make it so only my phone works with my siri proxy? I'd like to make it so I can access it over 3G, but I don't want it to be open to anyone who knows the IP.

**Comment by ntetreau** [comment]
This might be ignorant on my part but isn't this the whole point of the certificate you install on your phone(s)?  I mean, only with the certificate will you be able to connect to your proxy server isn't?

**Comment by muhkuh0815** [comment]
as ntetreau said, you have 1. the certificate for the siriproxy server and 2. you have your VPN password for connecting to your PC over 3G.

**Comment by therealMRBK** [comment]
yeah, but what if you want to give your certificate to a friend and have to make sure, that he can't just give his certificate away to another friend, and he to his sister, and she to her girlfriend and so on. You know how it is, nobody is trustful.

Would be cool if there is a solution for that

**Comment by muhkuh0815** [comment]
simple solution, dont give friends you dont trust your vpn password :-)

**Comment by ntetreau** [comment]
Or you could regenerate the security certificates once a week and send them out only to your close friends.

**Comment by shahramsh** [comment]
but it would be great if we could limit access based on UDID,

even close friends have other close friends and etc, 

it would make much much easier if we can specify who exactly can connect.

**Comment by ic0nic** [comment]
is there a script or not

**Comment by moieza** [comment]
no idea

**Comment by mackmgg** [comment]
I haven't found a way to limit by UDID, but I've decided to just go by MAC Address instead now. The VPN won't allow someone to connect without being on the whitelist.

**Comment by moieza** [comment]
what software you use? it works on 3G?
