### ISSUE TITLE
SiriProxy server and Jailbroken 4S not working anymore?

### ISSUE THREAD

**Issue by ghost** [plamoni/SiriProxy#290]
Hello,  I was running SiriProxy on a vanilla 4S without problems but once I jailbroke the phone, I end up with :

Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0xa37ca6c @signature=4, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0xa37c7ec>, @zip_stream=#Zlib::Deflate:0xa37c7b0, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0xa37b5a4 @manager=#<SiriProxy::PluginManager:0xa37c2c4 @plugins=[...]>>]

And it just hangs.  Siri tells me that it can't do anything and to check back later.  I recently changed my hosts file and assistant .plist to point to the IP of my server and regenerated my certs, I don't know what else to do now!

**Comment by plamoni** [comment]
You need to change the common name of the "guzzoni" cert to match your
altered host name.

Check the gencerts script and alter it as appropriate.

-Pete

Sent from my iPhone

On Jan 23, 2012, at 11:15 AM, AY
reply@reply.github.com
wrote:
