### ISSUE TITLE
jailbroken 4S

### ISSUE THREAD

**Issue by ghost** [plamoni/SiriProxy#292]
now that the A5 jailbreak is out, does anyone have the power and will to make some .deb to install on jailbroken 4S that'll install an appropriate PEM and alter the /etc/hosts to point guzzoni to the right address?

**Comment by FineTralfazz** [comment]
No, because the .pem and address are unique to each user. It's a waste of time anyway, since installing the .pem and editing the /etc/hosts isn't exactly a hard thing to do.

**Comment by BenWoodford** [comment]
Interestingly, I never had to mod the PEM, I just edited my hosts.

**Comment by BenWoodford** [comment]
Scratch that, misread and it's early in the morning, forgot what extension the certificate had. ^_~

**Comment by ntetreau** [comment]
Actually, xtremD is developing SiriSwitch especially to do that:
https://github.com/plamoni/SiriProxy/issues/282#issuecomment-3629052
