### ISSUE TITLE
iPhone 4S can't get keys

### ISSUE THREAD

**Issue by bihlmaier** [plamoni/SiriProxy#294]
Hi,

Now Siri Server is running, but it doesn't get any keys from 4S.

When I connect with 4s (i have only installed ca.pem), nothing happens on terminal.
Do you know how to solve this (maybe VPN?).

System: Debian Squeeze vServer

When I connect with iPhone 4 and the same certs, it says:

start conn #<SiriProxy::Connection::Iphone:0x00000002d0a190 @signature=21, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000002d09f60>, @zip_stream=#Zlib::Deflate:0x00000002d09f38, @consumed_ace=false, @is_4S=false, @sessionValidationData=nil, @speechId=nil, @assistantId=nil, @speechId_avail=false, @assistantId_avail=false, @validationData_avail=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x000000031c5888 @manager=#<SiriProxy::PluginManager:0x000000030d9028 @plugins=[...]>>]
[Info - SiriProxy] Created a connection!
[Key - SiriProxy] No keys available in database
[Info - SiriProxy] GSM iPhone 4 connected. Using saved keys
[Info - SiriProxy] Changed header to iphone4s] 
[Info - iPhone] Received Object: CreateSessionInfoRequest
[Protection - Siriproxy] Dropping Object from iPhone] CreateSessionInfoRequest due to no validation available

So why can they connect to my proxy without certificate?

And when I connect to IP without Cert, 
this comes (see at the end, its long).

So why can they connect to my proxy without certificate?

Best regards,

Timo

---

Terminal without Certs on iPhone 4:

Create server for iPhone connection
[Info - SiriProxy] Created a connection!
[Info - iPhone] Curent connection [3]
start conn #<SiriProxy::Connection::Iphone:0x0000000327bfe8 @signature=43, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x0000000327bb38>, @zip_stream=#Zlib::Deflate:0x0000000327bae8, @consumed_ace=false, @is_4S=false, @sessionValidationData=nil, @speechId=nil, @assistantId=nil, @speechId_avail=false, @assistantId_avail=false, @validationData_avail=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000003279c98 @manager=#<SiriProxy::PluginManager:0x0000000327adf0 @plugins=[...]>>]
Create server for iPhone connection
[Info - SiriProxy] Created a connection!
[Info - iPhone] Curent connection [3]
start conn #<SiriProxy::Connection::Iphone:0x00000003279720 @signature=44, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x000000032793b0>, @zip_stream=#Zlib::Deflate:0x00000003279388, @consumed_ace=false, @is_4S=false, @sessionValidationData=nil, @speechId=nil, @assistantId=nil, @speechId_avail=false, @assistantId_avail=false, @validationData_avail=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000002b444a0 @manager=#<SiriProxy::PluginManager:0x00000002b45918 @plugins=[...]>>]
Create server for iPhone connection
[Info - SiriProxy] Created a connection!
[Info - iPhone] Curent connection [3]
start conn #<SiriProxy::Connection::Iphone:0x00000002b441a8 @signature=45, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000002b43c80>, @zip_stream=#Zlib::Deflate:0x00000002b43c08, @consumed_ace=false, @is_4S=false, @sessionValidationData=nil, @speechId=nil, @assistantId=nil, @speechId_avail=false, @assistantId_avail=false, @validationData_avail=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000002963848 @manager=#<SiriProxy::PluginManager:0x00000002b42cb8 @plugins=[...]>>]
Create server for iPhone connection
[Info - SiriProxy] Created a connection!
[Info - iPhone] Curent connection [3]
start conn #<SiriProxy::Connection::Iphone:0x000000029635c8 @signature=46, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000002963438>, @zip_stream=#Zlib::Deflate:0x00000002963410, @consumed_ace=false, @is_4S=false, @sessionValidationData=nil, @speechId=nil, @assistantId=nil, @speechId_avail=false, @assistantId_avail=false, @validationData_avail=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000002961de0 @manager=#<SiriProxy::PluginManager:0x000000029629e8 @plugins=[...]>>]
Create server for iPhone connection
[Info - SiriProxy] Created a connection!
[Info - iPhone] Curent connection [3]
start conn #<SiriProxy::Connection::Iphone:0x00000002961bb0 @signature=47, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000002961930>, @zip_stream=#Zlib::Deflate:0x000000029618b8, @consumed_ace=false, @is_4S=false, @sessionValidationData=nil, @speechId=nil, @assistantId=nil, @speechId_avail=false, @assistantId_avail=false, @validationData_avail=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000002960350 @manager=#<SiriProxy::PluginManager:0x00000002960ee0 @plugins=[...]>>]
Create server for iPhone connection
[Info - SiriProxy] Created a connection!
[Info - iPhone] Curent connection [3]
start conn #<SiriProxy::Connection::Iphone:0x00000002fbcaf0 @signature=48, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000002fbc938>, @zip_stream=#Zlib::Deflate:0x00000002fbc910, @consumed_ace=false, @is_4S=false, @sessionValidationData=nil, @speechId=nil, @assistantId=nil, @speechId_avail=false, @assistantId_avail=false, @validationData_avail=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000002fbb4c0 @manager=#<SiriProxy::PluginManager:0x00000002fbbfd8 @plugins=[...]>>]
Create server for iPhone connection
[Info - SiriProxy] Created a connection!
[Info - iPhone] Curent connection [3]
start conn #<SiriProxy::Connection::Iphone:0x00000002fbb308 @signature=49, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000002fbb060>, @zip_stream=#Zlib::Deflate:0x00000002fbb038, @consumed_ace=false, @is_4S=false, @sessionValidationData=nil, @speechId=nil, @assistantId=nil, @speechId_avail=false, @assistantId_avail=false, @validationData_avail=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000002fb9a30 @manager=#<SiriProxy::PluginManager:0x00000002fba4f8 @plugins=[...]>>]
[Info - SiriProxy] Active connections [3] Max connections [50]
[Info - SiriProxy] Active connections [3] Max connections [50]
Create server for iPhone connection
[Info - SiriProxy] Created a connection!
[Info - iPhone] Curent connection [3]
start conn #<SiriProxy::Connection::Iphone:0x00000002fb9120 @signature=52, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000002fb8f40>, @zip_stream=#Zlib::Deflate:0x00000002fb8f18, @consumed_ace=false, @is_4S=false, @sessionValidationData=nil, @speechId=nil, @assistantId=nil, @speechId_avail=false, @assistantId_avail=false, @validationData_avail=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000002859ec0 @manager=#<SiriProxy::PluginManager:0x0000000285b2c0 @plugins=[...]>>]

**Comment by FineTralfazz** [comment]
The cert doesn't stop them from connecting, it just stops them from actually using it.
