### ISSUE TITLE
Siriproxy Server not working

### ISSUE THREAD

**Issue by JonathonRaby** [plamoni/SiriProxy#295]
So I follow the guide at this site: http://f3v3r.com/2011/12/28/how-to-make-your-own-siri-spire-proxy-server-video/

I follow it step by step, just copying and pasting the commands. I get all the way through, with no errors or mess ups.

On the last step, when I type in 'rvmsudo siriproxy server' it comes back with a no such file:

jd@ubuntu:~/SiriProxy$ rvmsudo siriproxy server
[sudo] password for jd: 
/usr/bin/env: siriproxy: No such file or directory
jd@ubuntu:~/SiriProxy$ 

I had this working a few days ago, then messed it up with trying out new plug-ins, so I reinstalled ubuntu today and went to the walk through to set it up again, and every time I do, I get that error. I have tried different things, to no avail.

I really want to be able to use this siri proxy, so any help from anyone on here would be greatly appreciated. Thank you guys, have a good day.

-Jonathon

**Comment by pelletierdr** [comment]
I'm having the same issue so hopefully someone can shed some light on this.

**Comment by humour** [comment]
Try to run the same command in your home directory....essentially close terminal and open it again and run rvmsudo siriproxy server right from jd@ubuntu: instead of being in ~/Siriproxy.  I had the same issue and that ended up working for me

**Comment by JonathonRaby** [comment]
I tried what you said humour, and it still didn't work. 

jd@ubuntu:~$ rvmsudo siriproxy server
[sudo] password for jd: 
/usr/bin/env: siriproxy: No such file or directory
jd@ubuntu:~$

**Comment by pelletierdr** [comment]
I'm assuming that when I turn the server on and log in I'm in my home directory.  If I run it there I still get the No Such File or Directory Found.

**Comment by humour** [comment]
Run this command in terminal: cat ~/.bash_profile and make sure it shows the correct location of rvm which it should display this: [[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # Load RVM function then run: source ~/.bash_profile

After that try rake install then rvmsudo siriproxy server either from within ~/SiriProxy or home.
