### ISSUE TITLE
Hwo to inject and image?

### ISSUE THREAD

**Issue by benceszikora** [plamoni/SiriProxy#296]
Hi,
How can I inject an image using my plugin?

**Comment by muhkuh0815** [comment]
```
object = SiriAddViews.new
object.make_root(last_ref_id)
answer = SiriAnswer.new("blabla" , [
                SiriAnswerLine.new('blabla',"pic-url-comes-here")
            ])
object.views << SiriAnswerSnippet.new([answer])
send_object object
```

if you found a ruby gem to enlarge an png, pls let me know :-)

**Comment by ghost** [comment]
öhmmm, @muhkuh0815 kannst du mal nen siriproxy übersetzer machen? :-) ich bin neu hab den proxy von the three little pigs siri proxy, will mich mit ruby bisschen zusammenfreuden :)

**Comment by muhkuh0815** [comment]
nein eher nicht, hab grad wenig zeit, muss objective C lernen :-(

**Comment by ghost** [comment]
aso :-(

**Comment by benceszikora** [comment]
thanks :D
