### ISSUE TITLE
'No such file or directory' (solution)

### ISSUE THREAD

**Issue by davidgeppelt** [plamoni/SiriProxy#297]
I know that a few people have posted on this already, but the solutions that people submitted do not work for me. I am at the last step, about to start the server, and I get this error:

user@box:~/SiriProxy$ rvmsudo siriproxy server
[sudo] password for administrator: 
/usr/bin/env: siriproxy: No such file or directory
user@box:~/SiriProxy$

I tried following the solution given here: https://github.com/plamoni/SiriProxy/issues/251, but it did not work. I noticed that the directory for /usr/bin/env/ is not even a directory but and exacutable, or the directory is not there. I tried to add the directory by hand and just replace each 'missing file' but the terminal command sudo mkdir env, while in /usr/bin/ would not allow me to do so because it says that it already exist.

Anyone have any idea that could help me out? I believe that the problem is with the repository for the rvm (https://github.com/wayneeseguin/rvm). A few of the scripts have been updated in the last couple of days.

**Comment by davidgeppelt** [comment]
I do not know why it did not matter before, but with the help of a college I found the solution, and it is easy, real easy; the current siriproxy install commands are half sudo half not, so the commands carried out under sudo are installed under the root user, and the ones not under sudo are under the normal user. So, before starting anything login as root in terminal ("sudo su" > enter password), then carrie our all the commands but do not include "sudo", because there is no need since you are root. When you get to the final step do not start SiriProxy with the command given ("rvmsudo siriproxy server") just run "siriproxy server" while in the SiriProxy under your root user. Works like a charm.

**Comment by JonathonRaby** [comment]
I had the same 'no file or directory' problem, (I actually posted a help question just before yourself) and I thought I had noticed this, that some were in sudo some weren't. But I went back and tried putting sudo in front of all the commands it still didn't work. But when I get home tonight I will try it with starting out with 'sudo su' so I stay in root. Hopefully this works for me later.

**Comment by tpanum** [comment]
How do you install and run the RVM as root?

I tried doing it, and just grabbing it directly in /usr/local/rvm/bin ... but, then the 'rake install' won't run.

I'm on Debian.
