### ISSUE TITLE
rvmsudo siriproxy server no such directory or file

### ISSUE THREAD

**Issue by pelletierdr** [plamoni/SiriProxy#299]
I am going to say first off I'm very new to Ubuntu.  I am a Windows guy and am very unfamiliar with anything else.

I've installed Ubuntu 11.10 Server I believe and selected OpenSSH and DNS server when I installed it.  I went through all the steps and everything appeared to have gone as it should have until the very last command.  I did uninstall bind9 because it was conflicting with dnsmasq.  

When i run the rvmsudo siriproxy server command  I get a response saying that no such direcory or file exists.  I am doing this from the SiriProxy directory.  If I just type siriproxy server I get a response that says "rescue in block in initialize":  Cannot start the server on port 443 - are you root, or have another process on this port already?  (RuntimeError)

I am logged in with the account I created during the installation of Ubuntu.

Any help would be greatly appreciated as I've followed a couple different guides and this last one feels like I'm just missing one thing to get it working.

Thanks again for any help.

**Comment by pelletierdr** [comment]
I forgot to add that it is running in Virtualbox on a Windows 7 laptop.  I have not installed any video drivers or Virtualbox additions as I couldn't figure that out.

**Comment by pelletierdr** [comment]
I have a feeling it has to do with something not being write in the PATH.  Here is the output from $PATH:  -bash:  /home/administrator/.rvm/gems/ruby-1.9.3-p0@SiriProxy/bin:/home/administrator/.rvm/gems/ruby-1.9.3-p0@global/bin:/home/adminstrator/.rvm/rubies/ruby-1.9.3-p0/bin:/home/administrator/.rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:  No such file or directory

**Comment by ghost** [comment]
1.--> source /etc/profile.d/rvm.sh
2.--> rvm use 1.9.3 --default

**Comment by pelletierdr** [comment]
Got it working thanks.

**Comment by emicovi** [comment]
@pelletierdr Can you tell me all the step you did? i have the same problem when i put rvmsudo siriproxy server it says no such file or directory.. please help me!

**Comment by ghost** [comment]
1.  source /etc/profile.d/rvm.sh
2. rvm use 1.9.3 --default

**Comment by emicovi** [comment]
thanks i got it working! but if i close the terminal how can i restart the server? it says the same problem..
