### ISSUE TITLE
VPN/Dynamic DNS

### ISSUE THREAD

**Issue by hackery21** [plamoni/SiriProxy#300]
I have a No-IP account and stuff and I have a working siri server on my ubuntu(Wubi) I was wondering if and how I can make my Server accessible on other Wifi networks. Thanks

**Comment by mcdull** [comment]
other wifi network = other networks .. you either need to mod the DNS on your iphone or VPN with custom DNS server.

**Comment by TobyTech** [comment]
Step by step?

**Comment by hackery21** [comment]
mcdull,Yes how to do that. Yes Toby thanks.

**Comment by TobyTech** [comment]
I meant I would like step by step, no clue what to actually do...

**Comment by mcdull** [comment]
I cant tell you how to set up a VPN server. It has a lot more to do than you would expect without proper hardware (VPN router, for example).  I personally uses a software firewall (software router) to enable PPTP.  To mod DNS on iphone. you just need to JB it and locate the file /etc/hosts and add an DNS entry there to translate apple server to your WAN address.

**Comment by TobyTech** [comment]
I assume my WAN address would be the dyndns. In dyndns, what IP do I set the host to? Internal? External?

**Comment by hackery21** [comment]
Step By Step?

**Comment by TobyTech** [comment]
Yes hackery, thanks.

**Comment by mcdull** [comment]
I didnt reply as I think it is a spam.. The details set up (Dual Cert / Host Edit) were already described in other Issue. I guess developer do not want to see these thread again.  Having a VPN set up is not the issue of siriproxy.  So you have to find it out by yourself. In short. You only need to modify the /etc/hosts in the JBed IPhone to get DNS redirected.
