### ISSUE TITLE
start conn #<SiriProxy::Connection::Iphone:0x000000024b8578 @signature=3, @processed_headers=false

### ISSUE THREAD

**Issue by ghost** [plamoni/SiriProxy#305]
admin123@ubuntu:~/SiriProxy$ rvmsudo siriproxy server
[sudo] password for admin123: 
Starting SiriProxy on port 443..
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x000000024b8578 @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x000000024b4cc0>, @zip_stream=#Zlib::Deflate:0x000000024b4ce8, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins loaded: [#<SiriProxy::Plugin::Example:0x000000023436e8 @manager=#<SiriProxy::PluginManager:0x00000002486848 @plugins=[...]>>]

It shows this when i hold home button on my ipad 2.. Please help
Every time i press and hold home button i get like this :(
Please help me..

Thanks!

**Comment by ghost** [comment]
admin123@ubuntu:~/SiriProxy$ rvmsudo siriproxy server
[sudo] password for admin123: 
Starting SiriProxy on port 443..
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x000000024b8578 @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x000000024b4cc0>, @zip_stream=#Zlib::Deflate:0x000000024b4ce8, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins loaded: [#<SiriProxy::Plugin::Example:0x000000023436e8 @manager=#<SiriProxy::PluginManager:0x00000002486848 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x000000023435a8 @signature=4, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000002343440>, @zip_stream=#Zlib::Deflate:0x00000002343418, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins loaded: [#<SiriProxy::Plugin::Example:0x000000023429c8 @manager=#<SiriProxy::PluginManager:0x00000002343008 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000002342888 @signature=5, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000002342720>, @zip_stream=#Zlib::Deflate:0x000000023426f8, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins loaded: [#<SiriProxy::Plugin::Example:0x00000002341b90 @manager=#<SiriProxy::PluginManager:0x00000002342220 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000002341a00 @signature=6, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000002341898>, @zip_stream=#Zlib::Deflate:0x00000002341870, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins loaded: [#<SiriProxy::Plugin::Example:0x00000002340ee8 @manager=#<SiriProxy::PluginManager:0x00000002341460 @plugins=[...]>>]

**Comment by dragouf** [comment]
I have same messages here...

**Comment by ghost** [comment]
I think that i fixed it but i got a FUCKING new shit error..
Anyway to fix this just remove all SiriProxy files from your Ubuntu from Home Folder also make sure that you can see hidden folders 
then write all these commands http://www.idownloadblog.com/2011/12/09/how-to-install-siri-proxy-tutorial-video/

P.S Change command 9 to: git clone git://github.com/westbaer/SiriProxy.git

**Comment by dragouf** [comment]
for me it was because the certificat was not well signed. 
you must edit gen_certs.sh and feel with good servername.

**Comment by ghost** [comment]
I already fixed it.. But now i have too many new errors like command failed...
i got errors when i press and hold home button..
Please help me if you can.. Im working on this from more than 3 days and it didnt work till now :S

Thanks.

**Comment by dragouf** [comment]
Me it seems to work but I don't have iphone4s so I search a fork which replace apple with google for speech recognition

**Comment by ghost** [comment]
OPS i need iphone 4s to make this works ? what about this http://www.idownloadblog.com/2012/01/23/how-to-install-siri-on-ipad-2/
omg..

**Comment by ghost** [comment]
if yes.. my friend have an iphone 4s.. what should i ask him to give me to make this work.. ? i'll share it without you no problem

**Comment by ghost** [comment]
Starting SiriProxy on port 443..
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000001bd2738 @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000001bd2530>, @zip_stream=#Zlib::Deflate:0x00000001bd2508, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins loaded: [#<SiriProxy::Plugin::Example:0x000000025f0a58 @manager=#<SiriProxy::PluginManager:0x00000001bd1c20 @plugins=[...]>>]
{"speech_id"=>nil, "assistant_id"=>"", "session_data"=>""}
[Warning] Non-4S device connected.
[Info] Found cached session data.
[Info] Found cached speech id.
[Info] Found cached assistant id.
[Info - iPhone] Received Object: LoadAssistant
[Info - iPhone] Received Object: SetAssistantData
[Info - iPhone] Received Object: SetRestrictions
{"speech_id"=>nil, "assistant_id"=>"", "session_data"=>""}
[Info - iPhone] Received Object: ClearContext
[Info - iPhone] Received Object: GetAnchors
[Info - iPhone] Received Object: GetAnchors
[Info - iPhone] Received Object: SetRestrictions
[Info - iPhone] Received Object: ClearContext
[Info - iPhone] Received Object: SetRestrictions
[Info - iPhone] Received Object: ClearContext
[Info - iPhone] Received Object: StartSpeechRequest
[Info - Guzzoni] Received Object: GetSessionCertificateResponse
[Info - Guzzoni] Received Object: SessionValidationFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - iPhone] Received Object: SetRequestOrigin
[Info - User Location] lat: , long: 
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed

Please if you found how to make this works without iPhone 4s please let me know this is my email: Jo.Metallica@live.com and my twitter @boobebeshi

**Comment by dragouf** [comment]
I don't have this : 

 [Warning] Non-4S device connected.
[Info] Found cached session data.
[Info] Found cached speech id.
[Info] Found cached assistant id.
[Info - iPhone] Received Object: LoadAssistant
[Info - iPhone] Received Object: SetAssistantData
[Info - iPhone] Received Object: SetRestrictions
{"speech_id"=>nil, "assistant_id"=>"", "session_data"=>""}

But I have this :

[Info - Guzzoni] Received Object: GetSessionCertificateResponse
[Info - Guzzoni] Received Object: SessionValidationFailed

I found this fork :

https://github.com/fopina/SiriProxy

It seems to cached session key of a iphone4s device.
So you set up the proxy with this fork, generate a certificat for guzzoni.apple.com (edit gen-certs.sh) and configure the dns of your local network to let guzzoni.apple.com resolve to your siriproxy ip.
Then on this local network use siri with your iphone4s and then you can use it with your ipad.
I think it's the procedure.

and here is an other interesting doc (step 3 is for non 4s device) : http://methoddk.com/siriguide/
If you have a 4s to initialize session, tell me if it work...

It's what I just found.

**Comment by ghost** [comment]
Sorry, I didn't understand you.. I'm newbie.. Anyway please tell me if i can ask my friend to give me that certificate from his iPhone 4s without coming to my home.. Step by step please

**Comment by dragouf** [comment]
Without from your home it will be complicate because he need to set up a DNS server.

You need to let DNS server resolve guzzoni.apple.com to your siriproxy ip.
(some FAI adsl router can do that).

you need also to install the ssl certificate of your siriproxy on the iphone4s of your friend.

**Comment by ghost** [comment]
wow..  That's really hard, my friend who have the iPhone 4s is busy and he can't come to my home or give me his iPhone :S
We need to find anyone to make this without iPhone 4s.

**Comment by ghost** [comment]
Omg I found awesome way to make it without iPhone 4s ;) just give me 10-15 till I test it and if it works I'll tell you how ASAP

**Comment by dragouf** [comment]
Great, if it work it's awesome ! Can't wait! Because moreover the method with the iphone4s work only for 24h and we had to renew session after that. I think.
