### ISSUE TITLE
Rake install /rake aborted help!!!

### ISSUE THREAD

**Issue by gunner768** [plamoni/SiriProxy#307]
david@ubuntu:~/SiriProxy$ rake install
/home/david/SiriProxy/siriproxy.gemspec:16: warning: Insecure world writable dir /usr/share/ruby-rvm in PATH, mode 042777
siriproxy 0.3.0 built to pkg/siriproxy-0.3.0.gem
rake aborted!
Couldn't install gem, run `gem install /home/david/SiriProxy/pkg/siriproxy-0.3.0.gem' for more detailed output

Tasks: TOP => install
(See full trace by running task with --trace)
david@ubuntu:~/SiriProxy$

Ive ran everything a million times through and this still keeps happening!! ive only gotten it to work once a while back. HELP PLEASE!!

**Comment by briguy2485** [comment]
I have the same problem and can't get passed it

**Comment by ChaseFlorell** [comment]
Same Here.

> gollum:SiriProxy media$ rake install --trace
> /Users/media/SiriProxy/siriproxy.gemspec:16: warning: Insecure world writable dir /Users/media/.rvm/gems in PATH, mode 040777
> *\* Invoke install (first_time)
> *\* Execute install
> siriproxy 0.3.0 built to pkg/siriproxy-0.3.0.gem
> rake aborted!
> Couldn't install gem, run `gem install /Users/media/SiriProxy/pkg/siriproxy-0.3.0.gem' for more detailed output
> /Users/media/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/bundler-1.2.1/lib/bundler/gem_helper.rb:68:in`install_gem'
> /Users/media/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/bundler-1.2.1/lib/bundler/gem_helper.rb:43:in `block in install'
> /Users/media/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/rake-0.9.2.2/lib/rake/task.rb:205:in`call'
> /Users/media/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
> /Users/media/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/rake-0.9.2.2/lib/rake/task.rb:200:in`each'
> /Users/media/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
> /Users/media/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/rake-0.9.2.2/lib/rake/task.rb:158:in`block in invoke_with_call_chain'
> /Users/media/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
> /Users/media/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/rake-0.9.2.2/lib/rake/task.rb:151:in`invoke_with_call_chain'
> /Users/media/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
> /Users/media/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/rake-0.9.2.2/lib/rake/application.rb:116:in`invoke_task'
> /Users/media/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
> /Users/media/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/rake-0.9.2.2/lib/rake/application.rb:94:in`each'
> /Users/media/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
> /Users/media/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/rake-0.9.2.2/lib/rake/application.rb:133:in`standard_exception_handling'
> /Users/media/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
> /Users/media/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/rake-0.9.2.2/lib/rake/application.rb:66:in`block in run'
> /Users/media/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
> /Users/media/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/rake-0.9.2.2/lib/rake/application.rb:63:in`run'
> /Users/media/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
> /Users/media/.rvm/gems/ruby-1.9.3-p194@SiriProxy/bin/rake:19:in`load'
> /Users/media/.rvm/gems/ruby-1.9.3-p194@SiriProxy/bin/rake:19:in `<main>'
> /Users/media/.rvm/gems/ruby-1.9.3-p194@SiriProxy/bin/ruby_noexec_wrapper:14:in`eval'
> /Users/media/.rvm/gems/ruby-1.9.3-p194@SiriProxy/bin/ruby_noexec_wrapper:14:in `<main>'
> Tasks: TOP => install
> gollum:SiriProxy media$

**Comment by KyleYoung** [comment]
Thirded: the trace is the same.

**Comment by Deanmv** [comment]
Is this not because of a permissions error on a folder? e.g.  Insecure world writable dir /Users/media/.rvm/gems in PATH, mode 040777

Try running 'chmod go-w /Users/$homefolder' where $homefolder is the user 

As read here: http://stackoverflow.com/questions/6192003/insecure-world-writable-dir-users-username-in-path-mode-040777-when-running-ru

**Comment by guillaume-ro-fr** [comment]
Run the command in root is resolve my problem.
