### ISSUE TITLE
No hosts file

### ISSUE THREAD

**Issue by gunner768** [plamoni/SiriProxy#309]
HELP!! I cant find the hosts file on my iphone 4!! there is one on the iphone 4s but not on my iphone 4. There is only a hosts.equiv

**Comment by TobyTech** [comment]
Create one, and then paste this text into it:

##

# Host Database

#

# localhost is used to configure the loopback interface

# when the system is booting. Do not change this entry.

##
127.0.0.1 localhost
255.255.255.255 broadcasthost
::1 localhost 
fe80::1%lo0 localhost
