### ISSUE TITLE
How do I create SiriButtons?

### ISSUE THREAD

**Issue by thomas-s97** [plamoni/SiriProxy#311]
Hey,
do you know these cool SiriButtons showing up, if you ask "I need to hide a body!"
how do I implement these in my own plugins?

class SiriButton < SiriObject
  def initialize(text="Button Text", commands=[])
    super("Button", "com.apple.ace.assistant")
    self.text = text
    self.commands = commands
  end
end
add_property_to_class(SiriButton, :text)
add_property_to_class(SiriButton, :commands)

i found this in the lib folder... how do I add this to my plugin?

**Comment by robbederks** [comment]
I also want to know this

**Comment by Haifisch** [comment]
I would also like to know
