### ISSUE TITLE
siriproxy + siriserver

### ISSUE THREAD

**Issue by angoleiro** [plamoni/SiriProxy#312]
how do i point siriproxy to my siriserver on the same LAN? So, instead of siriproxy connecting to guzzoni.apple.com, how can i make it point to a certain ip address/?

**Comment by budi-khoirudin** [comment]
Use DNS sever or Edit Your Host file ... to pointing ...

**Comment by angoleiro** [comment]
Could you give me an example on what you mean about the host file?

**Comment by budi-khoirudin** [comment]
edit file in /etc/host , add new line <ip server> guzzoni.apple.com , see this -> https://github.com/plamoni/SiriProxy/issues/241

**Comment by angoleiro** [comment]
has anyone got this working? i haven't myself.
