### ISSUE TITLE
Question about SiriProxy over 3G

### ISSUE THREAD

**Issue by TobyTech** [plamoni/SiriProxy#313]
I am sorry if you do not allow questions not concerning issues that relate to SiriProxy itself, but here I go:

I have a MI424-WR Verizon Router. I also have SiriProxy working over local Wifi. I want to make it so I can connect to my SiriProxy over 3G and other Wifi networks. I have heard many different things, but the thing I thought was true is that:

-Have to put in hosts:  myserver.dyndns.org  guzzoni.apple.com

-For myserver.dyndns.org, I have to put in on the dyndns website that my hostname is my external IP address (WAN IP)

All of this makes sense and I have accomplished, except for this part:

-FORWARD PORT 443 ON MY ROUTER TO AN INTERNAL IP ADDRESS.  How do I do that? I have looked high and low on my Verizon CP, and have found nothing that does this. Can anyone help?

**Comment by Winter-Guerra** [comment]
Look for "Port forwarding" under your router and forward it to your internal server.

Check my previous post here for how to use Siri over 3G: https://github.com/plamoni/SiriProxy/issues/282#issuecomment-3919497
