### ISSUE TITLE
Problem in ipad 2

### ISSUE THREAD

**Issue by baptiste88** [plamoni/SiriProxy#315]
Hello i'm french and I have a problem with siriproxy. Can you help me ? 

In my Terminal is write : 

Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x9d259d4 @signature=19, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x9d2568c>, @zip_stream=#Zlib::Deflate:0x9d25600, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x9c7a890 @manager=#<SiriProxy::PluginManager:0x9e9d2bc @plugins=[...]>>]
[Info - iPhone] Received Object: LoadAssistant
[Info - iPhone] Received Object: SetAssistantData
[Info - iPhone] Received Object: SetRestrictions
[Info - iPhone] Received Object: ClearContext
[Info - iPhone] Received Object: StartSpeechRequest
[Info - iPhone] Received Object: SetRequestOrigin
[Info - User Location] lat: , long: 
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - Guzzoni] Received Object: GetSessionCertificateResponse
[Info - Guzzoni] Received Object: SessionValidationFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - iPhone] Received Object: LoadAssistant
[Info - iPhone] Received Object: SetAssistantData
[Info - iPhone] Received Object: SetRestrictions
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: GetSessionCertificateResponse
[Info - Guzzoni] Received Object: SessionValidationFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - iPhone] Received Object: ClearContext
[Info - iPhone] Received Object: LoadAssistant
[Info - iPhone] Received Object: SetAssistantData
[Info - iPhone] Received Object: SetRestrictions
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: GetSessionCertificateResponse
[Info - Guzzoni] Received Object: SessionValidationFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - iPhone] Received Object: ClearContext
[Info - iPhone] Received Object: LoadAssistant
[Info - iPhone] Received Object: SetAssistantData
[Info - iPhone] Received Object: SetRestrictions
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: CommandFailed
[Info - Guzzoni] Received Object: GetSessionCertificateResponse
[Info - Guzzoni] Received Object: SessionValidationFailed
[Info - Guzzoni] Received Object: CommandFailed

:(

Thanks

**Comment by TobyTech** [comment]
Jesus. You have to use westbaer's fork. Then, you must ask something once with Siri, so it will save your keys, which it then uses to validate the iPad and spoof it to look like a 4S for Apple's guzzoni server.

You CANNOT use Siri with an iPad without a 4S.
