### ISSUE TITLE
SiriProxy, iPhone 4, and SiriPort.Ru

### ISSUE THREAD

**Issue by venturac** [plamoni/SiriProxy#316]
Hello,

SiriPort.Ru is actually working and I configured SiriProxy as well. There is a problem however, the server will start and it will display starting server on port 443.... and stay there. No speech packets will come up or anything. However, when you say to Siri, "Test Siri Proxy", she'll say, "Siri Proxy is up and running". I'm wondering why I can't see the speech interaction going on? Any ideas? I have not tried to install any plugins yet either. Thanks for the help in advance.

Tony

**Comment by mcdull** [comment]
~.~ Are you sure you know what you are doing? SiriPort.RU uses their own server. You will see NOTHING on your proxy. And be reminded that ALL of your personal information WILL BE SENT to this Russian Server. Guest how they would use it..

**Comment by venturac** [comment]
i understand they must use their own proxy server i was just wondering why it wasn't showing on the proxy server i created for the plugins. i would think it should still show and work. when i test and say, "test siri proxy", it says, "siri proxy up and running". so i don't know whats wrong.

**Comment by mcdull** [comment]
You create plugin in YOUR proxy. But you phone never went through YOUR proxy.

**Comment by venturac** [comment]
Maybe I don't understand then. Why wouldn't it be going through my proxy. Because technically it's not going through Apple??

-----Original Message-----

**Comment by mcdull** [comment]
Technically you can use only one proxy.  Either SiriPort.RU or YOUR proxy.  If you are using their proxy, there is nothing you can do to control it. You can just leave with SiriPort.RU and let them have all of your sensitive information.  OR you set up your own proxy and uses Spire. In that case you need an IPhone4S to access the same proxy so that you can get authenticated.

**Comment by mcdull** [comment]
ar... live with.... sorry for the typo.. I get drunk now... @.@..

**Comment by TobyTech** [comment]
You must be already drunk if you thought if you were using a Russian proxy you would see the log in YOUR server. _giggle giggle_
