### ISSUE TITLE
Control access to SiriProxy server by UDID

### ISSUE THREAD

**Issue by arnomoonens** [plamoni/SiriProxy#317]
Does anyone know how to do this, so when a device connects, the server checks for the udid and checks if it is on the whitelist before it can use Siri?

Maybe I'm explaining it wrong, but I hope that you know what I mean.

These are some sites with Siri servers that use this kind of method:
http://siri.ihacksrepo.com/ (also look at the file that you get when you click on 'If you have purchased...goto: Here on your device')
http://wewantsiri.tk/
http://mysiriserver.com/
http://siritd.no-ip.org////?page=homepage
http://uhelios.com
...

**Comment by TobyTech** [comment]
That is what .crt   is for. Only devices with the certificate can connect....... That is the entire purpose of it..... 0_o

**Comment by TobyTech** [comment]
And BTW, i THINK wewantsiri.tk is a scam......
