### ISSUE TITLE
sudo ruby ./start.rb and then error , please help

### ISSUE THREAD

**Issue by rcjulienne** [plamoni/SiriProxy#32]
/Library/Ruby/Gems/1.8/gems/eventmachine-1.0.0.beta.4/lib/eventmachine.rb:516:in `start_tcp_server': no acceptor (port is in use or requires root privileges) (RuntimeError)
    from /Library/Ruby/Gems/1.8/gems/eventmachine-1.0.0.beta.4/lib/eventmachine.rb:516:in`start_server'
    from ./siriProxy.rb:246:in `initialize'
    from /Library/Ruby/Gems/1.8/gems/eventmachine-1.0.0.beta.4/lib/eventmachine.rb:179:in`call'
    from /Library/Ruby/Gems/1.8/gems/eventmachine-1.0.0.beta.4/lib/eventmachine.rb:179:in `run_machine'
    from /Library/Ruby/Gems/1.8/gems/eventmachine-1.0.0.beta.4/lib/eventmachine.rb:179:in`run'
    from ./siriProxy.rb:245:in `initialize'
    from ./start.rb:16:in`new'
    from ./start.rb:16

help me please..

**Comment by netpro2k** [comment]
It sounds like you already have something running on port 443

**Comment by rcjulienne** [comment]
How to stop or kill the something running on port 443 ? 
------Original Message------

**Comment by netpro2k** [comment]
`lsof -Pnl +M -i4 | grep LISTEN | grep 443`

Should show you what process is using the port.

**Comment by shack1108** [comment]
When I run the command "lsof -Pnl +M -i4 | grep LISTEN | grep 443" nothing comes back, yet still getting same error. :(

**Comment by DouweM** [comment]
Use the SiriProxy version on the `refactored` branch. The code is a lot better/cleaner and this problem is gone.

**Comment by shack1108** [comment]
I am using the refactored branch.

**Comment by plamoni** [comment]
fetchtennisball: You need to run the lsof command as root to see if other users are using that port.

Anyway, this is obviously an old version of the code because the latest version won't run on Ruby 1.8. Please update the code, update your Ruby, and make sure to "sudo" that "lsof" command in your hunt for other processes! :-)

**Comment by phillpafford** [comment]
I think I'm having the same issue and nothing is running on 443

apache is listening to port 80
dsnmasq is listening to port 53 ( only )
ssh is listening to port 22
mysql is listening to port 3306

Any thoughts? 

I think it's a permission issue just not sure what I need to set permissions for

**Comment by plamoni** [comment]
If you get an error regarding not being able to open a socket, you are either not root or the port is in use. If you're not root, that's a problem if you're opening the connection on any port below 1024. So unless you set SiriProxy to run on a higher port (e.g. `siriproxy server -p 2000` -- this requires that you redirect traffic from 443 to 2000 using a firewall), you need to run it using `rvmsudo siriproxy server <options>`. If you're using the latest SiriProxy (`siriproxy update`), you'll be able to (and should), de-privilege the process using `rvmsudo siriproxy server -u nobody <other opitons>`.

If you're running it as root, it's probably a problem with the port being in use. You say apache only uses 80. Are you sure of that? Apache tends to also run on port 443 (https).

**Comment by phillpafford** [comment]
Thanks! The issue was either ( or both ) Ubuntu 12.04 LTS and configuring a DNS Server during installation. I have since upgraded to Ubuntu 12.10 and followed these steps: https://gist.github.com/phillpafford/5126739
