### ISSUE TITLE
siriproxy without iphone 4s Keys

### ISSUE THREAD

**Issue by nog-apps** [plamoni/SiriProxy#320]
hi everyone,

I was wondering if it is possible to use siriproxy locally with my own plugin without iphone 4s keys?

I have a VM totally functionnal, but it really don't work for now....

I have tested with iphone 4 only :

Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x9d129ec @signature=9, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x9d12848>, @zip_stream=#Zlib::Deflate:0x9d12834, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x9d120dc @manager=#<SiriProxy::PluginManager:0x9d124ec @plugins=[...]>>]

**Comment by plamoni** [comment]
Sorry, but that won't work (easily). The iPhone 4S key is used to connect
to Apple's servers which are used to translate your words into text which
is used to process even local plugins. It's theoretically possible to
modify SiriProxy to connect to another speech-to-text service (such as
Chrome's speech API). This would mean that "normal" functions wouldn't work
(like checking the weather, taking a note, etc) and those would need to be
re-implemented through plugins. But it's a possibility.

You probably won't see that work from me unless I find time to do more work
on SiriProxy. But maybe one of the forks will implement this functionality.
Until then (unless someone has done it already), there's no real option for
using SiriProxy without an iPhone 4S.

-Pete

**Comment by nog-apps** [comment]
Thank you very much for taking time answering me! 

My pretty neighbor has the 4S so I'm working on that....Lol! 

Thank you very much for your great job and more than that, it's very nice to share it!!!

Jérémy.
