### ISSUE TITLE
Got VPN connected but now Siri proxy server has stopped working

### ISSUE THREAD

**Issue by ghazis** [plamoni/SiriProxy#321]
Hello, I was running the proxy server on a Linux box with Ubuntu 11.10. It was working perfectly fine until I setup a VPN connection. I used this guide: http://eran.sandler.co.il/2010/08/30/pptp-vpn-on-ubuntu-10-04-for-your-iphone-ipad/
Now I'm pretty sure I know why its not working and just don't know how to fix it. I have a feeling that when I connect through VPN, the ip address is different and I should be changing the DNS settings on my iPad since the ip is not the same. If that is the problem then how do I find the ip address the VPN connection is using so I can change it on the iPad. Or if that's not even the problem then what is? This has been driving me nutss. If anyone can help me out I would greatly appreciate it. Thanks.

**Comment by delrio1110** [comment]
You don't need VPN. All you need to do is create a dyndns.com account. Then log into your router or modem and enter in your user name and password. Then port forward the ip address that the Siri proxy is on to port 443 tcp. Download I file on your iPad and edit the host file to look like this (example.dyndns.org guzzoni.apple.com) then edit the com.apple.assistant.plist. Delete guzzoni.apple.com and put example.dyndns.org. Last in spire enter in https://example.dyndns.org. Let me know if you need more help. With this meathod you don't need to connect to VPN.

**Comment by ghazis** [comment]
Thank you for the response but it did not work. I did everything you said but when I try it, it doesn't go through to the server. Should I change the DNS in my wireless settings? I don't know why it's not working :(

**Comment by ghazis** [comment]
Also should I be changing anything on the Linux box that the server is running on. Oh and in your examples you kept saying "example.dyndns.org," shouldn't it be ending in .com??
