### ISSUE TITLE
Calling me the wrong name. 

### ISSUE THREAD

**Issue by BanterJSmoke** [plamoni/SiriProxy#326]
My girlfriend and I are on the same proxy that I'm running. When I use Siri she calls me by my gf's name. When I change it to my name, Siri calls my gf by my name on her phone. Any way to fix this?

**Comment by dan122334455** [comment]
deal with it.

**Comment by BanterJSmoke** [comment]
It's not a big deal. But is that how it always works? Just a slight inconvenience, especially if others join the server.

**Comment by dan122334455** [comment]
I think thats the best thing to do.  Its not worth looking for hours just so it says your name.  I think thats how it always works.  I also cant really try to fix it cause im the only one on my server.  Sorry

**Comment by Ponyboy47** [comment]
I have that issue too with my Dad and brother. We all use the same Proxy I set up and sometimes Siri will get our names mixed up...usually it only happens if one of us uses Siri soon after someone else. And even then she only gets our names wrong for one request then she gets it straightened out
