### ISSUE TITLE
Plugins Fail?

### ISSUE THREAD

**Issue by TobyTech** [plamoni/SiriProxy#328]
Hey guys, just tried adding plugins for the first time, didn't go so well... I get greeted with this lovely message.

Starting SiriProxy on port 443..
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x8fa7848 @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x8fa75b4>, @zip_stream=#Zlib::Deflate:0x8fa75a0, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
/home/siriserver3g/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/plugin_manager.rb:23:in `const_get': wrong constant name computer (NameError)
    from /home/siriserver3g/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/plugin_manager.rb:23:in`block in load_plugins'
    from /home/siriserver3g/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/plugin_manager.rb:14:in `each'
    from /home/siriserver3g/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/plugin_manager.rb:14:in`load_plugins'
    from /home/siriserver3g/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/plugin_manager.rb:8:in `initialize'
    from /home/siriserver3g/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy.rb:21:in`new'
    from /home/siriserver3g/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy.rb:21:in `block (2 levels) in initialize'
    from /home/siriserver3g/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/eventmachine.rb:1432:in`call'
    from /home/siriserver3g/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/eventmachine.rb:1432:in `event_callback'
    from /home/siriserver3g/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run_machine'
    from /home/siriserver3g/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
    from /home/siriserver3g/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy.rb:16:in`initialize'
    from /home/siriserver3g/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:96:in `new'
    from /home/siriserver3g/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:96:in`start_server'
    from /home/siriserver3g/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:85:in `run_server'
    from /home/siriserver3g/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:37:in`initialize'
    from /home/siriserver3g/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/bin/siriproxy:6:in `new'
    from /home/siriserver3g/.rvm/gems/ruby-1.9.3-p0@SiriProxy/gems/siriproxy-0.3.0/bin/siriproxy:6:in`<top (required)>'
    from /home/siriserver3g/.rvm/gems/ruby-1.9.3-p0@SiriProxy/bin/siriproxy:19:in `load'
    from /home/siriserver3g/.rvm/gems/ruby-1.9.3-p0@SiriProxy/bin/siriproxy:

**Comment by TobyTech** [comment]
Here is my plugin file:

port: 443
log_level: 1
plugins:
    # NOTE: run bundle after changing plugin configurations to update required gems

```
 - name: 'Example'
   path: './plugins/siriproxy-example'

 - name: 'computer'
   git: 'https://github.com/IMcD23/siriproxy-computer.git'

 - name: 'SiriIMDB'
   git: 'git://github.com/parm289/SiriProxy-SiriIMDB.git'

 - name: 'NHL' 
   git: 'git://github.com/ay00/SiriProxy-NHL.git'

 - name: 'Tivo'
   git: 'git://github.com/mrmosconi/siriproxy-tivo.git'
   host: '192.168.1.14'
   delay: 1.3
   short_delay: 0.3



 #- name: 'Thermostat'
#   git: 'git://github.com/plamoni/SiriProxy-Thermostat.git'
#   host: '192.168.2.71' 

# - name: 'Twitter'
#   path: './plugins/siriproxy-twitter' # path works just like specifing in gemfile 
#   consumer_key: "YOUR_KEY" 
#   consumer_secret: "YOUR_SECRET"
#   oauth_token: "YOUR_TOKEN" 
#   oauth_token_secret: "YOUR_TOKEN_SECRET"

# Note: Eliza should not be run with other plugins
# - name: 'Eliza'
#   path: './plugins/siriproxy-eliza' # path works just like specifing in gemfile 

# Below are not actual plugins, just further example of config options

# - SimplePlugin # simple syntax for plugins that are in rubygems and have no config 

# - name: 'AnotherPlugin'
#   git: 'git://github.com/netpro2k/SiriProxy-AnotherPlugin.git' # git works just like specifying in Gemfile
```

**Comment by muhkuh0815** [comment]
get rid of all the eamty lines after  Tivo, and check that there are no Tabulators, just use spaces.

config.yml is quite sensitive
