### ISSUE TITLE
MySql and SiriProxy

### ISSUE THREAD

**Issue by ianhz** [plamoni/SiriProxy#329]
Hi everyone!

Im doing a project which involves both siriproxy and mysql. Basically, Im doing a plugin for Siri which interacts with my TV, so basically I need to have a database that contains the current line up of movies and tv shows that are going to be shown in a particular week.

I have already downloaded all sorts of mysql libraries, including "gem install mysql", but when I execute the siriproxy server command, I get this :

@SiriProxy/gems/siriproxy-0.3.0/plugins/siriproxy-tv/lib/siriproxy-tv.rb:5:in `require': cannot load such file -- mysql (LoadError)

In my .rb file, I included 

require 'rubygems'
require 'mysql'

Nothing seems to work. Does anyone know how to use mysql with siriproxy??

Thanks !

**Comment by DMBearcat** [comment]
you must install libmysqlclient-16
