### ISSUE TITLE
gemset install 

### ISSUE THREAD

**Issue by ghost** [plamoni/SiriProxy#337]
Gemset '' does not exist, 'rvm gemset create ' first, or append '--create'.

does anyone know how to fix this?

**Comment by cmyk16** [comment]
are you getting that error on the step 'rvm install 1.9.3' cos i think im having that problem, i had siri proxy installed once and running correctly before but now i cant install properly on a clean ubuntu install. can any one shed some light on the situation ?

Edit: Bit weird works for me now, must been something wrong with rvm but i'm not an expert.
