### ISSUE TITLE
iPhone 4S connecting but failing to give responses

### ISSUE THREAD

**Issue by iPodHacks142** [plamoni/SiriProxy#339]
Every time i use the siri proxy with my 4S it doesnt work. Lots of code appears fast on the terminal but finished with "zlib(finalizer): the stream was freed prematurely". Can anyone help please?

**Comment by Number1** [comment]
Mine has been doing the same.  It used to work just fine but now I can never connect.

**Comment by Number1** [comment]
I started over with a new VM and everything is working normally.
