### ISSUE TITLE
[refactored] Start.rb stuck on "Starting SiriProxy on port 443.."

### ISSUE THREAD

**Issue by DouweM** [plamoni/SiriProxy#34]
I'm pretty sure I've set everything up the way it should be, but when running `rvmsudo ruby start.rb`, nothing happens after this logged message:

```
Starting SiriProxy on port 443..
```

The Example plugin has been enabled, but when telling Siri "Test Siri Proxy", she doesn't respond with "Siri Proxy is up and running!", so it appears to be SiriProxy never fully initializes and the `EventMachine::start_server` callback is never called.

Any ideas what could be up?

**Comment by netpro2k** [comment]
Does siri respond at all? If she does and you dont see any output, its likely your iPhone is not actually hitting your proxy. Make sure that your iphone's DNS is pointing to your dnsmasq server, and that dnsmasq is rerouting to your proxy server.

**Comment by courtenay** [comment]
I actually saw this too. What ruby version are you on?

**Comment by DouweM** [comment]
It wasn't working before, but it's working now. Not sure what changed, but I'm happy!

**Comment by szomo** [comment]
I'm at this point right now , i think the refactored version helped out almost everything .... 

I get dnsmasq to run ( no output which i assume the script works )  i get start.rb running and it says 

"Starting SiriProxy on port 443.." 

problem is i dont get a response when i tell siri "test siri proxy" and its my guess that i have to install the example plugin, 

when i uncomment in config.yaml 

   # - name: 'Example'
   # path: './plugins/siriproxy-example'

to 

   name: 'Example'
   path: './plugins/siriproxy-example'

bundle install throws errors

**Comment by DouweM** [comment]
You still need the "-" in front of the name-line.

—Douwe
