### ISSUE TITLE
SiriProxy not working

### ISSUE THREAD

**Issue by iPodHacks142** [plamoni/SiriProxy#341]
Here is what my terminal in ubuntu says every time i connect my 4S: 
[Info - iPhone] Received Object: LoadAssistant
[Info - iPhone] Received Object: SetRestrictions
[Info - iPhone] Received Object: ClearContext
[Info - iPhone] Received Object: StartSpeechRequest
[Info - iPhone] Received Object: SetRequestOrigin
[Info - User Location] lat: 51.886566937979545, long: -0.39569470495580567
[WhereAmI - Debug - User Location] lat: 51.886566937979545, long: -0.39569470495580567, acc: 100.0, req. pending: false
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: LoadAssistant
[Info - iPhone] Received Object: SetRestrictions
[Info - iPhone] Received Object: ClearContext
[Info - iPhone] Received Object: StartSpeechRequest
[Info - iPhone] Received Object: SetRequestOrigin
[Info - User Location] lat: 51.886566937979545, long: -0.39569470495580567
[WhereAmI - Debug - User Location] lat: 51.886566937979545, long: -0.39569470495580567, acc: 100.0, req. pending: false
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x0000001a46ec08 @signature=483, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x0000001a46eaa0>, @zip_stream=#Zlib::Deflate:0x0000001a46ea78, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x0000001a46e0a0 @manager=#<SiriProxy::PluginManager:0x0000001a46e6b8 @plugins=[...]>>, #<SiriProxy::Plugin::WhereAmI:0x0000001a46dad8 @manager=#<SiriProxy::PluginManager:0x0000001a46e6b8 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x0000001a46d510 @signature=485, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x0000001a46d3a8>, @zip_stream=#Zlib::Deflate:0x0000001a46d380, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x0000001a46c9d0 @manager=#<SiriProxy::PluginManager:0x0000001a46cfc0 @plugins=[...]>>, #<SiriProxy::Plugin::WhereAmI:0x0000001a474400 @manager=#<SiriProxy::PluginManager:0x0000001a46cfc0 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x0000001a473e60 @signature=487, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x0000001a473cf8>, @zip_stream=#Zlib::Deflate:0x0000001a473cd0, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x0000001a473320 @manager=#<SiriProxy::PluginManager:0x0000001a473910 @plugins=[...]>>, #<SiriProxy::Plugin::WhereAmI:0x0000001a472d58 @manager=#<SiriProxy::PluginManager:0x0000001a473910 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x0000001a4727b8 @signature=489, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x0000001a472650>, @zip_stream=#Zlib::Deflate:0x0000001a472628, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x0000001a471c78 @manager=#<SiriProxy::PluginManager:0x0000001a472268 @plugins=[...]>>, #<SiriProxy::Plugin::WhereAmI:0x0000001a4716b0 @manager=#<SiriProxy::PluginManager:0x0000001a472268 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x0000001a471110 @signature=491, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x0000001a470fa8>, @zip_stream=#Zlib::Deflate:0x0000001a470f80, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x0000001a4785c8 @manager=#<SiriProxy::PluginManager:0x0000001a470bc0 @plugins=[...]>>, #<SiriProxy::Plugin::WhereAmI:0x0000001a478000 @manager=#<SiriProxy::PluginManager:0x0000001a470bc0 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x0000001a4729e8 @signature=493, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x0000001a1ed1c8>, @zip_stream=#Zlib::Deflate:0x0000001a1e2c50, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x000000010fdcb8 @manager=#<SiriProxy::PluginManager:0x0000001a400b18 @plugins=[...]>>, #<SiriProxy::Plugin::WhereAmI:0x00000000c53e10 @manager=#<SiriProxy::PluginManager:0x0000001a400b18 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000000c66ee8 @signature=495, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000000c6c230>, @zip_stream=#Zlib::Deflate:0x00000000c6c1e0, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000000c6ceb0 @manager=#<SiriProxy::PluginManager:0x00000000c69b70 @plugins=[...]>>, #<SiriProxy::Plugin::WhereAmI:0x00000000c7a650 @manager=#<SiriProxy::PluginManager:0x00000000c69b70 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000000c8b810 @signature=497, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000000c8af50>, @zip_stream=#Zlib::Deflate:0x00000000c8ae88, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000000e29be0 @manager=#<SiriProxy::PluginManager:0x00000000c8d908 @plugins=[...]>>, #<SiriProxy::Plugin::WhereAmI:0x00000000e2dee8 @manager=#<SiriProxy::PluginManager:0x00000000c8d908 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000000e2ba58 @signature=499, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000000e2b580>, @zip_stream=#Zlib::Deflate:0x00000000e2b440, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000000e39dd8 @manager=#<SiriProxy::PluginManager:0x00000000e308a0 @plugins=[...]>>, #<SiriProxy::Plugin::WhereAmI:0x00000000d71180 @manager=#<SiriProxy::PluginManager:0x00000000e308a0 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000000da7370 @signature=501, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000000d8d7b8>, @zip_stream=#Zlib::Deflate:0x00000000d8d628, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000000e72e30 @manager=#<SiriProxy::PluginManager:0x00000000e41830 @plugins=[...]>>, #<SiriProxy::Plugin::WhereAmI:0x00000000ec1530 @manager=#<SiriProxy::PluginManager:0x00000000e41830 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000000eda9b8 @signature=503, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000000ed9d60>, @zip_stream=#Zlib::Deflate:0x00000000ed9d10, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000000ef5b50 @manager=#<SiriProxy::PluginManager:0x00000000ee86f8 @plugins=[...]>>, #<SiriProxy::Plugin::WhereAmI:0x00000000f0c558 @manager=#<SiriProxy::PluginManager:0x00000000ee86f8 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000000f0a3e8 @signature=505, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000000f08e80>, @zip_stream=#Zlib::Deflate:0x00000000f08e58, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000001010490 @manager=#<SiriProxy::PluginManager:0x00000000f0f618 @plugins=[...]>>, #<SiriProxy::Plugin::WhereAmI:0x000000010641a8 @manager=#<SiriProxy::PluginManager:0x00000000f0f618 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000001061e08 @signature=507, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x0000000108bde8>, @zip_stream=#Zlib::Deflate:0x0000000108b9b0, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x000000010b30c8 @manager=#<SiriProxy::PluginManager:0x0000000108a588 @plugins=[...]>>, #<SiriProxy::Plugin::WhereAmI:0x000000010b0b98 @manager=#<SiriProxy::PluginManager:0x0000000108a588 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x000000010af518 @signature=509, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x000000010dbde8>, @zip_stream=#Zlib::Deflate:0x000000010dbd98, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x000000010f22c8 @manager=#<SiriProxy::PluginManager:0x000000010da8f8 @plugins=[...]>>, #<SiriProxy::Plugin::WhereAmI:0x000000010efaf0 @manager=#<SiriProxy::PluginManager:0x000000010da8f8 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x000000010f5bf8 @signature=511, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x000000010f5928>, @zip_stream=#Zlib::Deflate:0x000000010f58d8, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x000000010fd5d8 @manager=#<SiriProxy::PluginManager:0x000000010f4ca8 @plugins=[...]>>, #<SiriProxy::Plugin::WhereAmI:0x00000001102f88 @manager=#<SiriProxy::PluginManager:0x000000010f4ca8 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000001101840 @signature=513, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000001101228>, @zip_stream=#Zlib::Deflate:0x00000001101110, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000001106bd8 @manager=#<SiriProxy::PluginManager:0x000000011004b8 @plugins=[...]>>, #<SiriProxy::Plugin::WhereAmI:0x00000001101fe8 @manager=#<SiriProxy::PluginManager:0x000000011004b8 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000000c54bd0 @signature=515, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000000c50df0>, @zip_stream=#Zlib::Deflate:0x00000000c58b18, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000000c6ee18 @manager=#<SiriProxy::PluginManager:0x00000000c6c0f0 @plugins=[...]>>, #<SiriProxy::Plugin::WhereAmI:0x00000000c76ed8 @manager=#<SiriProxy::PluginManager:0x00000000c6c0f0 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000000c859d8 @signature=517, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000000c8b590>, @zip_stream=#Zlib::Deflate:0x00000000c8b4c8, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000000e298c0 @manager=#<SiriProxy::PluginManager:0x00000000e24dc0 @plugins=[...]>>, #<SiriProxy::Plugin::WhereAmI:0x00000000e2ce30 @manager=#<SiriProxy::PluginManager:0x00000000e24dc0 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000000e32150 @signature=519, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000000e30a08>, @zip_stream=#Zlib::Deflate:0x00000000e30710, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000000e37510 @manager=#<SiriProxy::PluginManager:0x00000000e5afb0 @plugins=[...]>>, #<SiriProxy::Plugin::WhereAmI:0x00000000d8ecf8 @manager=#<SiriProxy::PluginManager:0x00000000e5afb0 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000000e74de8 @signature=521, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000000e742a8>, @zip_stream=#Zlib::Deflate:0x00000000e741e0, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000000ec7688 @manager=#<SiriProxy::PluginManager:0x00000000e99378 @plugins=[...]>>, #<SiriProxy::Plugin::WhereAmI:0x00000000ee7f50 @manager=#<SiriProxy::PluginManager:0x00000000e99378 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000000ef5d58 @signature=523, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000000ef4b10>, @zip_stream=#Zlib::Deflate:0x00000000ef49f8, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000000f11468 @manager=#<SiriProxy::PluginManager:0x00000000f0c8a0 @plugins=[...]>>, #<SiriProxy::Plugin::WhereAmI:0x00000000feb870 @manager=#<SiriProxy::PluginManager:0x00000000f0c8a0 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x000000010495b0 @signature=525, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000001064680>, @zip_stream=#Zlib::Deflate:0x00000001064478, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000001089688 @manager=#<SiriProxy::PluginManager:0x000000010628d0 @plugins=[...]>>, #<SiriProxy::Plugin::WhereAmI:0x000000010b2a88 @manager=#<SiriProxy::PluginManager:0x000000010628d0 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x000000010b0918 @signature=527, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x000000010b03a0>, @zip_stream=#Zlib::Deflate:0x000000010b0170, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x000000010d8260 @manager=#<SiriProxy::PluginManager:0x000000010dace0 @plugins=[...]>>, #<SiriProxy::Plugin::WhereAmI:0x000000010f01f8 @manager=#<SiriProxy::PluginManager:0x000000010dace0 @plugins=[...]>>]
^C/home/josh/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine': Interrupt
    from /home/josh/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run'
    from /home/josh/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy.rb:16:in `initialize'
    from /home/josh/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:96:in`new'
    from /home/josh/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:96:in `start_server'
    from /home/josh/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:85:in`run_server'
    from /home/josh/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:37:in `initialize'
    from /home/josh/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/siriproxy-0.3.0/bin/siriproxy:6:in`new'
    from /home/josh/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/siriproxy-0.3.0/bin/siriproxy:6:in `<top (required)>'
    from /home/josh/.rvm/gems/ruby-1.9.3-p194@SiriProxy/bin/siriproxy:19:in`load'
    from /home/josh/.rvm/gems/ruby-1.9.3-p194@SiriProxy/bin/siriproxy:19:in `<main>'
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.

Any ideas on how to fix this?

**Comment by nilsi** [comment]
Got the same problem! Found any solution for it?

**Comment by ianhz** [comment]
same problem here!!

**Comment by rauanargyn** [comment]
the same problem. Anyone solved it before? Please, help....
