### ISSUE TITLE
DNSmasq Error

### ISSUE THREAD

**Issue by laxman01** [plamoni/SiriProxy#342]
Hi, I'm running Ubuntu 12.04 LTS and after adding the line to DNSmasq.conf I restart DNSmasq by using this code 

sudo /etc/init.d/dnsmasq restart

This is the response it returns 
- Restarting DNS forwarder and DHCP server dnsmasq  
  dnsmasq: failed to create listening socket for port 53: Address already in use
                                                                       [fail]

I would be very thankful for anyone who responds to me.

**Comment by tobyaherbert** [comment]
Perhaps two instances of dnsmasq are running or maybe another dns server is running, i got a similar issue (as i am on mac) because bind (another dns server) is turned on by default on all new macs. Try looking in activity monitor (should be in the dashboard/search thingy) :)

**Comment by Bocameck** [comment]
I have the same issue here. Using Ubuntu 12.04 in VMWare running on Windows7.
Edit: Problem solved: Hab to uncomment "bind-interfaces" in file dnsmasq.conf

**Comment by reliablesource** [comment]
uncommenting didn't work either, said the IP was already in use
