### ISSUE TITLE
Not receiving iMessages

### ISSUE THREAD

**Issue by inetAnt** [plamoni/SiriProxy#346]
Hello,

I guess iMessage also uses guzzoni.apple.com since that when I'm playing with SiriProxy I don't receive my iMessages.

Is there any workaround with or without jailbreaking ?

Thanks.

**Comment by plamoni** [comment]
If you jailbreak, there is a plist you can change to change the server
it uses for Siri. This also requires a change to your certificate, so
you'll have to do some research on how to do that. But others have
done it. Just check around the Internet a bit.

-Pete

Sent from my iPhone

On May 26, 2012, at 3:53 AM, AntoineMeillet
reply@reply.github.com
wrote:

**Comment by inetAnt** [comment]
Thanks :)
