### ISSUE TITLE
command_line.rb:80:in ``': No such file or directory - bundle

### ISSUE THREAD

**Issue by megamalain** [plamoni/SiriProxy#350]
I'm installing siriproxy on a pogoplug as described in the instructions here: http://jamesmallen.net/2012/01/29/pogoplug-as-a-siri-proxy/

When I run siriproxy bundle I get the error:
command_line.rb:80:in ``': No such file or directory - bundle

Below is my console output. Please help.

[root@alarm bin]# ./siriproxy bundle
/root/SiriProxy/lib/siriproxy/command_line.rb:80:in ``': No such file or directory - bundle   (Errno::ENOENT)
        from /root/SiriProxy/lib/siriproxy/command_line.rb:80:in`run_bundle'
        from /root/SiriProxy/lib/siriproxy/command_line.rb:39:in `initialize'
        from ./siriproxy:6:in`new'
        from ./siriproxy:6:in `<main>'

**Comment by plamoni** [comment]
You should not be running all this as root. Running as root creates permissions issues that generally cause a big mess (along with being a monster security issue). I suggest you clean things up and try again as a non-privilaged user using `sudo` and `rvmsudo` where noted in the installation instructions.

If you're okay with this massive security hole in your computer, you can make sure that RVM is properly set up in your path (`[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"`) and that the bundler gem is properly installed (`rvmsudo gem install rake bundler`)
