### ISSUE TITLE
New Siri Subdomain in iOS 6?

### ISSUE THREAD

**Issue by tobyaherbert** [plamoni/SiriProxy#351]
Does Siri use a new subdomain in iOS 6?

I can't see any traffic on 'guzzoni.apple.com'.

I'm running iOS 6 Beta 1 (Released two days ago :)).

Does anyone know what the new domain is?

Thanks in advance...

Toby Herbert.

**Comment by tobyaherbert** [comment]
Forgot to mention i am on an iPhone 4S (obviously)

**Comment by plamoni** [comment]
Remember (and this goes to everyone), that iOS 6 is still under NDA, so
please do not discuss technical aspects of the OS publicly. We can discuss
things more once the NDA is lifted.

Until then, you're probably on your own.

Sorry,

-Pete

**Comment by tobyaherbert** [comment]
Ok thanks.
