### ISSUE TITLE
git://github.com/chendo/cora.git (at master) is not checked out. Please run `bundle install` (Bundler::GitError)

### ISSUE THREAD

**Issue by luis84** [plamoni/SiriProxy#352]
Hello, 

On ubuntu 11.10 following setup instructions exactly.  When I do rake install -- this is the error I get.

/home/zeroproxy/.rvm/gems/ruby-1.9.3-p194@global/gems/bundler-1.1.4/lib/bundler/source.rb:574:in `rescue in load_spec_files': git://github.com/chendo/cora.git (at master) is not checked out. Please run`bundle install` (Bundler::GitError)

I can fix it by doing this: bundle install 

And then repeat rake install.

This makes Siriproxy work fine.  HOWEVER, when I install plugins it happens again and during the plugin phase it is not fixable.  So I can never install a plugin all because of the above error.

What is the fix?

Thank you.

**Comment by luis84** [comment]
So. As stated above, if i Add a plugin to config.yml

and then run: siriproxy update

I get the above error again, it fails to work because of cora.git.

So I manually run the bundle install ... it finishes with no errors.

zeroproxy@zeroproxy-VirtualBox:~/SiriProxy$ siriproxy update
=== Installing latest code from git://github.com/plamoni/SiriProxy.git [master] ===
remote: Counting objects: 701, done.
remote: Compressing objects: 100% (270/270), done.
remote: Total 701 (delta 399), reused 655 (delta 365)
Receiving objects: 100% (701/701), 129.01 KiB, done.
Resolving deltas: 100% (399/399), done.
Cloning into /tmp/SiriProxy.install.4933...
=== Performing Rake Install ===
/home/zeroproxy/.rvm/gems/ruby-1.9.3-p194@global/gems/bundler-1.1.4/lib/bundler/source.rb:574:in `rescue in load_spec_files': git://github.com/chendo/cora.git (at master) is not checked out. Please run`bundle install`(Bundler::GitError)
    from /home/zeroproxy/.rvm/gems/ruby-1.9.3-p194@global/gems/bundler-1.1.4/lib/bundler/source.rb:572:in`load_spec_files'
    from /home/zeroproxy/.rvm/gems/ruby-1.9.3-p194@global/gems/bundler-1.1.4/lib/bundler/source.rb:372:in `local_specs'
    from /home/zeroproxy/.rvm/gems/ruby-1.9.3-p194@global/gems/bundler-1.1.4/lib/bundler/source.rb:557:in`specs'
    from /home/zeroproxy/.rvm/gems/ruby-1.9.3-p194@global/gems/bundler-1.1.4/lib/bundler/definition.rb:430:in `block in converge_locked_specs'
    from /home/zeroproxy/.rvm/gems/ruby-1.9.3-p194@global/gems/bundler-1.1.4/lib/bundler/definition.rb:419:in`each'
    from /home/zeroproxy/.rvm/gems/ruby-1.9.3-p194@global/gems/bundler-1.1.4/lib/bundler/definition.rb:419:in `converge_locked_specs'
    from /home/zeroproxy/.rvm/gems/ruby-1.9.3-p194@global/gems/bundler-1.1.4/lib/bundler/definition.rb:180:in`resolve'
    from /home/zeroproxy/.rvm/gems/ruby-1.9.3-p194@global/gems/bundler-1.1.4/lib/bundler/definition.rb:127:in `specs'
    from /home/zeroproxy/.rvm/gems/ruby-1.9.3-p194@global/gems/bundler-1.1.4/lib/bundler/environment.rb:27:in`specs'
    from /home/zeroproxy/.rvm/gems/ruby-1.9.3-p194@global/gems/rubygems-bundler-1.0.3/lib/rubygems-bundler/noexec.rb:41:in `candidate?'
    from /home/zeroproxy/.rvm/gems/ruby-1.9.3-p194@global/gems/rubygems-bundler-1.0.3/lib/rubygems-bundler/noexec.rb:60:in`setup'
    from /home/zeroproxy/.rvm/gems/ruby-1.9.3-p194@global/gems/rubygems-bundler-1.0.3/lib/rubygems-bundler/noexec.rb:75:in `<top (required)>'
    from /home/zeroproxy/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in`require'
    from /home/zeroproxy/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
    from /home/zeroproxy/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in`require'
    from /home/zeroproxy/.rvm/gems/ruby-1.9.3-p194@SiriProxy/bin/ruby_noexec_wrapper:9:in `<main>'

zeroproxy@zeroproxy-VirtualBox:~/SiriProxy$ bundle install
Fetching git://github.com/Swimo/SiriProxy---WhereAmI.git
remote: Counting objects: 15, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 15 (delta 2), reused 15 (delta 2)
Receiving objects: 100% (15/15), done.
Resolving deltas: 100% (2/2), done.
Fetching gem metadata from http://rubygems.org/............
Using rake (0.9.2.2) 
Using CFPropertyList (2.1.1) 
Using geocoder (1.1.2) 
Using cora (0.0.4) from git://github.com/chendo/cora.git (at master) 
Using eventmachine (0.12.10) 
Installing json (1.7.3) with native extensions 
Using uuidtools (2.1.2) 
Using siriproxy (0.3.0) from source at . 
Using siriproxy-example (0.0.1) from source at ./plugins/siriproxy-example 
Using siriproxy-whereami (0.1) from git://github.com/Swimo/SiriProxy---WhereAmI.git (at master) 
Using bundler (1.1.4) 
Your bundle is complete! Use `bundle show [gemname]` to see where a bundled gem is installed.

HOWEVER,

When I go to run SiriProxy again - zeroproxy@zeroproxy-VirtualBox:~/SiriProxy$ rvmsudo siriproxy server
git://github.com/Swimo/SiriProxy---WhereAmI.git (at master) is not checked out. Please run `bundle install`

Now my SiriProxy is broken.  Everytime I try to install a plugin.  Bundle install doesn't fix it.  Please help.

**Comment by pgib** [comment]
Try: rvmsudo bundle install, then rvmsudo bundle exec siriproxy server

**Comment by plamoni** [comment]
Actually, instead of `bundle install`, once you have SiriProxy installed, you should use `siriproxy bundle`. That should fix your problem.
