### ISSUE TITLE
Siri not working on my 3S Plx Help

### ISSUE THREAD

**Issue by louiekeung** [plamoni/SiriProxy#353]
after setting up proxy 
i trying to test 
proxy server receive some speech 
but cannot return a result 
this is the full code that the proxy displayed

iloupro@iloupro-R410:~/SiriProxy$ rvmsudo siriproxy serverStarting SiriProxy on port 443..
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x9a35a44 @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x9a35990>, @zip_stream=#Zlib::Deflate:0x9a3597c, @consumed_ace=false, @auth_data=nil, @faux=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x9a088dc @manager=#<SiriProxy::PluginManager:0x9a35760 @plugins=[...]>>]
{"speech_id"=>nil, "assistant_id"=>nil, "session_data"=>nil}
[Warning] Non-4S device connected.
[Warning] Non-4S devices cannot CreateAssistant. This device either requires proper initial configuration (refer to http://methoddk.com/siriguide/ Step 3) or the cached session expired and a new 4S needs to connect.
[Info - iPhone] Received Object: CreateAssistant
[Info - iPhone] Received Object: SetAssistantData
[Info - iPhone] Received Object: SetRestrictions
[Info - iPhone] Received Object: ClearContext
{"speech_id"=>nil, "assistant_id"=>nil, "session_data"=>nil}
[Info - iPhone] Received Object: StartSpeechRequest
[Info - Guzzoni] Received Object: GetSessionCertificateResponse
[Info - iPhone] Received Object: SetRequestOrigin
[Info - User Location] lat: , long: 
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: FinishSpeech

**Comment by plamoni** [comment]
This question is regarding an unsupported fork of SiriProxy. I do not support using SiriProxy to run Siri on unsupported devices.
