### ISSUE TITLE
Error with command: rake install

### ISSUE THREAD

**Issue by Alsaegh** [plamoni/SiriProxy#354]
I had siriproxy running on Ubuntu 11.10
but after i mad an upgrade to the lastest version of Ubuntu and follow the same steps
exactly at command 
rake install

i got this output ,,

alsaegh@ubuntu:~/SiriProxy$ rake install
/home/alsaegh/.rvm/gems/ruby-1.9.3-p194/gems/bundler-1.1.4/lib/bundler/source.rb:574:in `rescue in load_spec_files': git://github.com/chendo/cora.git (at master) is not checked out. Please run`bundle install`(Bundler::GitError)
    from /home/alsaegh/.rvm/gems/ruby-1.9.3-p194/gems/bundler-1.1.4/lib/bundler/source.rb:572:in`load_spec_files'
    from /home/alsaegh/.rvm/gems/ruby-1.9.3-p194/gems/bundler-1.1.4/lib/bundler/source.rb:372:in `local_specs'
    from /home/alsaegh/.rvm/gems/ruby-1.9.3-p194/gems/bundler-1.1.4/lib/bundler/source.rb:557:in`specs'
    from /home/alsaegh/.rvm/gems/ruby-1.9.3-p194/gems/bundler-1.1.4/lib/bundler/definition.rb:430:in `block in converge_locked_specs'
    from /home/alsaegh/.rvm/gems/ruby-1.9.3-p194/gems/bundler-1.1.4/lib/bundler/definition.rb:419:in`each'
    from /home/alsaegh/.rvm/gems/ruby-1.9.3-p194/gems/bundler-1.1.4/lib/bundler/definition.rb:419:in `converge_locked_specs'
    from /home/alsaegh/.rvm/gems/ruby-1.9.3-p194/gems/bundler-1.1.4/lib/bundler/definition.rb:180:in`resolve'
    from /home/alsaegh/.rvm/gems/ruby-1.9.3-p194/gems/bundler-1.1.4/lib/bundler/definition.rb:127:in `specs'
    from /home/alsaegh/.rvm/gems/ruby-1.9.3-p194/gems/bundler-1.1.4/lib/bundler/environment.rb:27:in`specs'
    from /home/alsaegh/.rvm/gems/ruby-1.9.3-p194@global/gems/rubygems-bundler-1.0.3/lib/rubygems-bundler/noexec.rb:41:in `candidate?'
    from /home/alsaegh/.rvm/gems/ruby-1.9.3-p194@global/gems/rubygems-bundler-1.0.3/lib/rubygems-bundler/noexec.rb:60:in`setup'
    from /home/alsaegh/.rvm/gems/ruby-1.9.3-p194@global/gems/rubygems-bundler-1.0.3/lib/rubygems-bundler/noexec.rb:75:in `<top (required)>'
    from /home/alsaegh/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in`require'
    from /home/alsaegh/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
    from /home/alsaegh/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in`require'
    from /home/alsaegh/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:9:in `<main>'

please help me fixing this problem
Thanks in advance ..

**Comment by plamoni** [comment]
Did you try running `bundle install` as suggested by the error message?

**Comment by Alsaegh** [comment]
yeah but i couldn't figure out how to get it work cause it showed me another error ,, so I did install it on new machine and got it working using other sequence of commands :

Command 01:
sudo apt-get install dnsmasq ruby build-essential openssl libreadline6 libreadline6-dev curl git-core zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-0 libsqlite3-dev sqlite3 libxml2-dev libxslt-dev autoconf libc6-dev ncurses-dev automake libtool bison subversion

Command 02:
sudo nano /etc/dnsmasq.conf
*replace the ip with current machine ip

Command 03:
sudo /etc/init.d/dnsmasq restart

Command 04:
bash < <(curl -s https://raw.github.com/wayneeseguin/rvm/master/binscripts/rvm-installer)

Command 05: 
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"

Command 06:
echo '[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # Load RVM function' >> ~/.bash_profile

Command 07:
rvm install 1.9.3

Command 08: 
rvm use 1.9.3 --default

Command 09: 
git clone git://github.com/plamoni/SiriProxy.git

Command 10:
    cd SiriProxy

Command 11:
    mkdir ~/.siriproxy

Command 12:
    cp ./config.example.yml ~/.siriproxy/config.yml

Command 13:
    bundle install

Command 14:
    rake install

Command 15:
    siriproxy gencerts 

Command 16:
    siriproxy bundle

Command 17:
    rvmsudo siriproxy server

Thank you plamoni for replying
