### ISSUE TITLE
Forward Requests To SiriServer When TLP Down Or Has No Keys?

### ISSUE THREAD

**Issue by SalmanBurhan** [plamoni/SiriProxy#357]
Is there any way to forward siriproxy requests to a SiriServer running on the same machine when there are no 4S or iPad 3 keys or when the server is down. When the server is down part is not so important to me. I really just want to know about the forwarding when no keys. Is there any way that could happen? Any ruby codes out there that could get this to work and make a pull request on it?

**Comment by plamoni** [comment]
I do not support using SiriProxy to allow use of Siri on devices not supported by Apple.

**Comment by SalmanBurhan** [comment]
I'm not, it's just the interface for ttlp. I used to use ttlp but instead I changed it to siriproxy. If u would like, I will remove the interface.

**Comment by SalmanBurhan** [comment]
Btw: I use it for my iPhone 5

**Comment by plamoni** [comment]
Sorry, wasn't clear. I don't support TLP proxy. That's a fork of this project. For questions specific to TLP, you should contact the creators of that fork.

**Comment by SalmanBurhan** [comment]
Oh ok
