### ISSUE TITLE
Problem with dnsmasq(fixed!)...READ THIS IF YOU ARE TRYING TO INSTALL SIRI PROXY ON UBUNTU 12.04!

### ISSUE THREAD

**Issue by verIzonzach** [plamoni/SiriProxy#358]
Hello all, I had a siri proxy working perfectly on my computer a few months ago. Unfortunately, the Hard Drive failed(nothing was on it but the siri proxy stuff) and all the certs and other proxy files were backed up on dropbox. On my current computer, everything seems to work however, the proxy seems to be looping and when I pinged guzzoni.apple.com it just replied with the IP address of the proxy(192.168.0.20) any ideas? The proxy isn't using its IP address as it's DNS server. Someone please help?!
SOLUTION IS BELOW!

**Comment by verIzonzach** [comment]
Ok! Fixed it! Ubuntu 12.04 comes with dnsmasq as a local lookup server by defualt so you need to do the following(make sure you don't put the quotes)....
1. Open terminal
2. Run "sudo nano /etc/NetworkManager/NetworkManager.conf"
3. Change "dns=dnsmasq" to "#dns=dnsmasq"
4. Press CRTL+X, press y, and then enter to save
5. Run "sudo restart network-manager"
6. Ping guzzoni.apple.com and it should no longer say your IP Address
If it still doesn't work(didn't for me)
1. Restart computer
2. Try again(ping guzzoni.apple.com and it shouldn't show your IP Address)
If it still doesn't work(still didn't for me)
1. Open Terminal
2. Run sudo apt-get remove --purge resolvconf
3. Press Y to remove packages!(You may get warning you should restart computer just press enter)
4. Reboot computer and try to ping guzzoni again it should now ping to the correct address!
If you can not get a Internet connection on the 4S/the 4S doesn't communicate to your proxy
1. Open terminal.
2. Run "sudo gedit /etc/dnsmasq.conf"
3. Press CRTL+i
4. Type "92" and it should go to line 92 
5. Type "listen-address=YOUR_IP_ADDRESS_HERE" make sure you put your ip adress after the "="
6. Close window(SAVE CHANGES) and go back to terminal
7. Run "sudo /etc/init.d/dnsmasq restart"
8. Test! If it does not work, then post a new issue!

**Comment by markandersonus** [comment]
Thanks! Mine worked after "Run sudo apt-get remove --purge resolvconf" and reboot. not sure if removing resov.conf is gonna break anything else (bit of a linux noob)

**Comment by reliablesource** [comment]
This did not work, running Ubuntu 12.04.2 server
