### ISSUE TITLE
SiriProxy does Nothing at all

### ISSUE THREAD

**Issue by ghost** [plamoni/SiriProxy#359]
When I start the proxy it says Starting SiriProxy on port 443... Ten nothing happens, Siri takes like 10 seconds ten responds but the SiriProxy doesn't do anything. When I go to the ip address and port on safari on my iPhone, the proxy shows the connecting to iPhone message with all the code. But it doesn't work. It was working then stopped. Please! Someone help me! D:

**Comment by shameer99** [comment]
same here but the proxy doesnt show me any code

**Comment by ghost** [comment]
Me neither. Only when I go to the ip in safari

**Comment by AndrewRayCode** [comment]
Same here, when I go to mycomputer'slanip:443 in safari on my iPhone, the server logs "start conn" blah blah, but when I run siri she does not seem to be intercepted by the proxy

**Comment by AndrewRayCode** [comment]
nevermind, worked after setting my nameserver in /etc/resolv.conf to my local lan ip per http://blog.philippklaus.de/blog/2012/02/05/install-dnsmasq-locally-on-mac-os-x-via-homebrew/

close this ticket NOOWWWWW

**Comment by plamoni** [comment]
Problems like this are always related to improper setup of DNS. It's a difficult thing to get right, and the hardest part of setting up siriproxy because it's highly dependent on your own, individual network setup. It's not an issue with the code.
