### ISSUE TITLE
Weird SpeechFailure

### ISSUE THREAD

**Issue by ianhz** [plamoni/SiriProxy#362]
Hello all,

My siriproxy+plugins were working with no problems whatsoever a couple of months ago, but now I always get the following error in the command line:

[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: FinishSpeech
[Info - Guzzoni] Received Object: AddViews
[Info - Guzzoni] Received Object: SpeechFailure

sometimes I get

[Info - iPhone] Received Object: FinishSpeech
[Info - Guzzoni] Received Object: AddViews
[Info - Guzzoni] Received Object: CommandFailed

After the FinishSpeech, my iphone stays in a loop process, about 1 min with no response, then I got the SpeechFailure.

After a certain amount of time, Siri reads a message at my iphone saying "Sorry, I didnt get that" or "Sorry, we' ve had a problem. Can you please try that again?" or some variation of those messages.

What's wrong? Can someone please help me??

Many thanks!

**Comment by plamoni** [comment]
Can you post some more detailed logs? You can do this by upping the log level using `siriproxy server --log 5` (higher number gives more logs, but 5 should be enough).
