### ISSUE TITLE
iPad 3, to soon or is it just me?

### ISSUE THREAD

**Issue by olehumborstad** [plamoni/SiriProxy#363]
Hi,

I actually bought the new iPad just for controlling the lights etc, using Siri.
I upgraded to iOS 6 with the Gold Master and have Siri legit(ish?), and working without the Proxy.

Anyways, i LOVE this project and REALLY want it to work, i'll even donate money somewhere if possible in order to fix this. I guess it's still to early since SiriProxy recognizes the iPad as an iPhone?
The code goes super fast and ends up with "Assertion 'e failed" after going through a lot of speech packets etc. but this is the last bit:

Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x962e090 @signature=1017, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x962df8c>, @zip_stream=#Zlib::Deflate:0x962df64, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x962da14 @manager=#<SiriProxy::PluginManager:0x962dd20 @plugins=[...]>>]
Create server for iPhone connection
3073308296:error:02001018:system library:fopen:Too many open files:bss_file.c:398:fopen('/home/siri/.siriproxy/server.passless.key','r')
3073308296:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:400:
3073308296:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
ruby: ssl.cpp:166: SslContext_t::SslContext_t(bool, const string&, const string&): Assertion `e > 0' failed.

Will there ever be SiriProxy on the iPad3 or did i just do something stupid elsewhere here?
I'm not buying another iPhone if this doesn't work, that's for sure.

**Comment by plamoni** [comment]
iOS6 has not officially been released yet (It goes public next week). That
being the case, anyone with access to it (including myself) is bound by a
non-disclosure agreement. Therefore, any development of SiriProxy to
support iOS6 or discussion of issues/bugs/changes/etc should be deferred
until next week when the software is publicly available.

Until then, please refrain from discussions of iOS6 on this forum.

-Pete

PS - SiriProxy is not designed to help people run Siri on devices that
Apple has not authorized for use (such as the iPhone 4). There are some
forks of the project that may assist with that. But I do not support those
projects or any efforts to circumvent Apple's device restrictions on Siri.

**Comment by olehumborstad** [comment]
I knew I was too eager getting this to work, I apologize for any inconvenience I may have caused.
I'll check back in a week when it's proper to discuss this issue.

**Comment by plamoni** [comment]
Not a problem. Have a good day!

-Pete

**Comment by olehumborstad** [comment]
Time to revisit this issue now?

**Comment by plamoni** [comment]
I'll take a look when I get a chance. But feel free to discuss issues and
bugs.

-Pete

Sent from my iPhone

On Sep 20, 2012, at 12:28 AM, whitehum notifications@github.com wrote:

Time to revisit this issue now?

—
Reply to this email directly or view it on
GitHubhttps://github.com/plamoni/SiriProxy/issues/363#issuecomment-8717181.

**Comment by olehumborstad** [comment]
Siri Proxy is up an running! Sweet :D
All i did was to re-install with Ubuntu 11.10

**Comment by ghost** [comment]
https://github.com/westbaer/SiriProxy/pull/4
