### ISSUE TITLE
ERROR on iPhone5 iOS6

### ISSUE THREAD

**Issue by chickentw** [plamoni/SiriProxy#364]
I can't sure whether this problem only in iPhone5 or iOS6 because I only have iPhone5

But the error below crash the server while I change Siri language

/Users/Doratown/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/connection.rb:104:in `has_next_object?': undefined method`[]' for nil:NilClass (NoMethodError)
    from /Users/Doratown/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/connection.rb:84:in `process_compressed_data'
    from /Users/Doratown/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/connection.rb:58:in`receive_binary_data'
    from /Users/Doratown/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/eventmachine-1.0.0/lib/em/protocols/linetext2.rb:94:in `receive_data'
    from /Users/Doratown/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in`run_machine'
    from /Users/Doratown/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run'
    from /Users/Doratown/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy.rb:16:in`initialize'
    from /Users/Doratown/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:96:in `new'
    from /Users/Doratown/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:96:in`start_server'
    from /Users/Doratown/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:85:in `run_server'
    from /Users/Doratown/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:37:in`initialize'
    from /Users/Doratown/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/siriproxy-0.3.0/bin/siriproxy:6:in `new'
    from /Users/Doratown/.rvm/gems/ruby-1.9.3-p194@SiriProxy/gems/siriproxy-0.3.0/bin/siriproxy:6:in`<top (required)>'
    from /Users/Doratown/.rvm/gems/ruby-1.9.3-p194@SiriProxy/bin/siriproxy:23:in `load'
    from /Users/Doratown/.rvm/gems/ruby-1.9.3-p194@SiriProxy/bin/siriproxy:23:in`<main>'
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.

**Comment by plamoni** [comment]
This is a bug related to a new version of the protocol. I went to go test on iOS 6 recently and found it. There's a new packet type that gets issued by the servers every once in a while that isn't parsed correctly. Download the latest version of the code to fix it (`siriproxy update`).
