### ISSUE TITLE
Problem on "rvm install 1.9.3" can't find awk command in script.

### ISSUE THREAD

**Issue by wotan0** [plamoni/SiriProxy#367]
Here's my output, after "rvm install 1.9.3"

root@nas:/home/wotan/SiriProxy# rvm install 1.9.3
ruby-1.9.3-p194 - #configure
ruby-1.9.3-p194 - #download
ruby-1.9.3-p194 - #extract
ruby-1.9.3-p194 - #validate
ruby-1.9.3-p194 - #setup
/usr/local/rvm/scripts/db: Zeile 61: awk: Kommando nicht gefunden.
/usr/local/rvm/scripts/db: Zeile 61: awk: Kommando nicht gefunden.
/usr/local/rvm/scripts/db: Zeile 61: awk: Kommando nicht gefunden.
Saving wrappers to '/usr/local/rvm/bin'.
ruby-1.9.3-p194 - #importing default gemsets (/usr/local/rvm/gemsets/)
/usr/local/rvm/scripts/db: Zeile 61: awk: Kommando nicht gefunden.
/usr/local/rvm/scripts/tools: Zeile 39: basename: Kommando nicht gefunden.

there are no more error's, but when i want to execute "rake install" i get:

root@nas:/home/wotan/SiriProxy# rake install
rake aborted!
no such file to load -- bundler/gem_tasks

(See full trace by running task with --trace)

**Comment by plamoni** [comment]
Not sure about your problems with RVM, you might make sure you have the right requirements by running `rvm requirements` and confirming you have all the dependancies.

As for your problem with bundler, you should ensure that you have bundler installed, also if you don't have RVM set up properly, a missing bundler is one of the signs. Make sure your path is set up once you've got RVM installed by using:

```
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"
```
