### ISSUE TITLE
ERROR: It seems your ruby installation is missing psych (for YAML output)

### ISSUE THREAD

**Issue by elvisimprsntr** [plamoni/SiriProxy#368]
I had SiriProxy 0.3.2 working with ruby-1.9.3-p194
After I upgraded to ruby-1.9.3-p286, I keep getting the following error message when performing 

> siriproxy bundle 
> bundle install

/usr/local/rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/yaml.rb:56:in `<top (required)>':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.

I followed the conventional suggestions for fixing the problem even though I know libyaml was installed.

> rvm pkg install libyaml
> rvm reinstall ruby-1.9.3-p286 # current ruby distro as of 2012-10-12

I still get the same error message.  SiriProxy seems to install and run even with the error.  

MY CONFIG: https://github.com/plamoni/SiriProxy/wiki/Installation-How-Tos

**Comment by plamoni** [comment]
Do you have the dev package for libyaml installed? (might be called "libyaml-dev"). I haven't seen this error, but oftentimes when I get an error about a missing library that I know is installed, it's because it requires the headers (dev version).

**Comment by elvisimprsntr** [comment]
Yes I have libyaml-dev installed.    I am considering reinstalling ruby-1.9.3-p194 to isolate.

> apt-get install libyaml-dev -y

**Comment by plamoni** [comment]
Maybe. Check for errors and warnings during the install. I had a hell of a time with getting zlib support working on my Ruby install with BackTrack 5 (a necessary component for SiriProxy). I ended up having to tell it the location of zlib using some compile flags.

**Comment by elvisimprsntr** [comment]
No errors during libyaml-dev install.   I came across this little tidbit in the /usr/local/rvm/src/ruby-1.9.3-p286/NEWS file

> - The default YAML engine is now Psych. You may downgrade to syck by setting YAML::ENGINE.yamler = 'syck'.  

Not exactly sure what this is telling me or what file I need to set this in.

In the mean time I removed and reinstalled libyaml-dev, reinstalling ruby-1.9.3-p286.  It takes so long to compile from source on an ARM plug computer.   Ugh!  

> apt-get remove libyaml-dev
> apt-get install libyaml-dev
> rvm pkg install libyaml
> rvm reinstall ruby-1.9.3-p286

**Comment by elvisimprsntr** [comment]
I installed SiriProxy 0.3.2 and ruby-1.9.3-p286 on a VM and didn't get the same error.  
I then wiped my rvm and re-installed everything on my plug computer from scratch, but continue to get the same error.

> rm -rf /usr/local/rvm 
> rvm reload

All the conventional suggestions I have found on forums don't seem to work.  One of which was what I did above.  The thing the troubles me is that I had everything working with p194.  

I am currently headed down this path.  http://collectiveidea.com/blog/archives/2011/10/31/install-ruby-193-with-libyaml-on-centos/

Any additional suggestions on resources or forums to ask questions would be greatly appreciated.    

Thanks in advance, 

Elvis

**Comment by elvisimprsntr** [comment]
a combination of the suggestions here:  http://collectiveidea.com/blog/archives/2011/10/31/install-ruby-193-with-libyaml-on-centos/   and installing and additional package required for Ubuntu 9.04 worked

> apt-get install pkg-config
