### ISSUE TITLE
SiriProxy worked once before dnsmasq, now having port issues

### ISSUE THREAD

**Issue by ghost** [plamoni/SiriProxy#370]
After a long and tedious install process, I FINALLY got SiriProxy to start. This first time it started, it worked fine; saying "Siri Proxy Test" got a response. But then I quit the process and installed dnsmasq and added the address line to its config.

Now every time I try to start SiriProxy I get this:

```
macbook:siriproxy szezulak$ rvmsudo ./bin/siriproxy server
Starting SiriProxy on port 469..
/Users/szezulak/.rvm/gems/ruby-1.9.3-p286@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:526:in `start_tcp_server': no acceptor (port is in use or requires root privileges) (RuntimeError)
    from /Users/szezulak/.rvm/gems/ruby-1.9.3-p286@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:526:in `start_server'
    from /Users/szezulak/Desktop/siriproxy/lib/siriproxy.rb:19:in `block in initialize'
    from /Users/szezulak/.rvm/gems/ruby-1.9.3-p286@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `call'
    from /Users/szezulak/.rvm/gems/ruby-1.9.3-p286@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run_machine'
    from /Users/szezulak/.rvm/gems/ruby-1.9.3-p286@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run'
    from /Users/szezulak/Desktop/siriproxy/lib/siriproxy.rb:16:in `initialize'
    from /Users/szezulak/Desktop/siriproxy/lib/siriproxy/command_line.rb:96:in `new'
    from /Users/szezulak/Desktop/siriproxy/lib/siriproxy/command_line.rb:96:in `start_server'
    from /Users/szezulak/Desktop/siriproxy/lib/siriproxy/command_line.rb:85:in `run_server'
    from /Users/szezulak/Desktop/siriproxy/lib/siriproxy/command_line.rb:37:in `initialize'
    from ./bin/siriproxy:6:in `new'
    from ./bin/siriproxy:6:in `<main>'
```

Changing the port starts the proxy successfully but the commands don't work. I'm assuming installing dnsmasq is the cause of this issue. I removed the address line from the dnsmasq config, but that did nothing.

So, a couple things:

1) Why did it work the very first time without dnsmasq? Note: the iPhone and the Mac are on the same WiFi network.
2) Why can't I start the proxy more than once on the same port?
3) What do I need to do to get it working again?

**Comment by plamoni** [comment]
1) It probably didn't. You said you said "Siri Proxy Test," however, that's not the correct thing to say. You should test using "Test Siri Proxy." This will respond with "Siri Proxy is up and running!" if everything is working well. If you didn't have your DNS poisoning set up (using dnsmasq), you were likely talking directly to Apple's servers and not using the proxy at all. If you use the word "Test" when talking to Siri, she often responds with some quip about everything looking good or something like that. You're looking specifically for a response of "Siri Proxy is up and running!"

2) This isn't a problem with SiriProxy, it's a limitation of most operating systems. Only one application can run on a given port. If you don't kill the previous process (try "sudo killall ruby"), it will prevent you from launching again. Also, some other services, like Apache (the web server used by Macs) might occupy port 443, so you might need to disable "web sharing" (look in "sharing" in your settings) before you can run SiriProxy on port 443.

It's vital you run on port 443 unless you are using something like iptables to forward traffic from port 443 to your SiriProxy server. The iPhone expects the server to be on port 443 at guzzoni.apple.com. We're using dnsmasq to trick the iPhone into thinking your SiriProxy server is guzzoni.apple.com, but it still expects it to be running on port 443.

3) Again, you probably never really had it working. My suggestion is to restart your computer (to make sure everything is shut down). Start SiriProxy on port 443. Set up dnsmasq. Make sure your iPhone is using your Mac as its DNS server. And for good measure (this sometimes helps me when it's "stuck" talking to the Apple servers), flip your phone to airplane mode for a few seconds, then re-connect to your Wi-Fi, check your DNS, and try out Siri.

You should see output on the console where you started SiriProxy. If everything is working well, the phrase "Test Siri Proxy" should yield a response of "SiriProxy is up and running!" and a bunch of output to your console. If things crash, check around on the issues pages and FAQ to see if you can work out what's going wrong.

Good luck!

**Comment by ghost** [comment]
Ah, there we go! It's working perfectly now, thanks for helping me out!

EDIT: It's also working wonderfully on my iOS 6 iPad!

**Comment by ghost** [comment]
@plamoni : After getting SiriProxy to work, I didn't touch it for several days until now.

I think at some point, after reboots or whatever, my DNS configuration changed. `sudo lsof -Pni` shows that dnsmasq is also listening on 127.0.0.1:53

```
dnsmasq   3200         nobody    3u  IPv4 0xf166d061acb3593b      0t0    UDP 192.168.0.75:53
dnsmasq   3200         nobody    4u  IPv4 0xf166d061b31be53b      0t0    TCP 192.168.0.75:53 (LISTEN)
dnsmasq   3200         nobody    5u  IPv4 0xf166d061b74dfc73      0t0    UDP 127.0.0.1:53
dnsmasq   3200         nobody    6u  IPv4 0xf166d061b16b308b      0t0    TCP 127.0.0.1:53 (LISTEN)
```

I believe this is the infamous loopback error people struggle with. In my case, I'm not even getting any output from SiriProxy, and Siri on my iDevice does not work at all (in fact, all internet access on the iDevice is broken).

I'm hoping you can help me out with this, even though I know you only technically support SiriProxy. I touched nothing in any configuration files after I followed your advice. What could be causing this?

**Comment by phillpafford** [comment]
did you ever solve this? I think I'm having the same issue

**Comment by plamoni** [comment]
Is DNSMasq running and is your iPhone using the computer running DNSMasq as it's DNS server?

**Comment by phillpafford** [comment]
I think I solved it, thanks! Needed rvmsudo to execute the command: https://gist.github.com/phillpafford/5126739
