### ISSUE TITLE
Ubuntu 12.10 (?)

### ISSUE THREAD

**Issue by mynamegoeshere** [plamoni/SiriProxy#374]
Anybody running SiriProxy on a dedicated ubuntu 12.10 machine?
How does it fair in comparison to 11.10?
More or Less stable?
Is it a b***\* to install?

**Comment by sturma** [comment]
I tried it on 12.04.1 dedicated PC, I think it's a bit more stable, no fuzz at all to install, same as 11.10.
Now I'm running TTLP siriproxy on 12.04.1 dedicated, 64-bit.

**Comment by mynamegoeshere** [comment]
Really. That's interesting. I'm having trouble installing on 12.04. Had it running in 11.10 until my hd crashed. Now I'm running 12.04 but can't get the server started. I think is might have to do with rvm. I noticed in the install video that rvm 1.9.3-p0  is being used. However when I install, it's using -p268. Could this be an issue?

Assistance is appreciated. (I miss my siri.)

**Comment by mynamegoeshere** [comment]
Well made it all the way through the install, server starts and all. (But) When I issue a command to Siri the terminal window goes into warp speed. Text is moving so fast I can't even read it. Guess I'm going to try it again from a fresh 12.04 install.

One note. I had to use 
bash -s stable < <(curl -s https://raw.github.com/wayneeseguin/rvm/master/binscripts/rvm-installer) 
to get rvm to install without errors. Notice the "stable" added to the command?

**Comment by sturma** [comment]
Sounds like a DNSmasq issue causing a loop. Can you resolve guzzoni from your server to the real IP (ping)?

**Comment by mynamegoeshere** [comment]
All is good. Very much DNSmasq causing issues. Wiped it clean and reinstalled.

Do you have to enter [[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" everytime before you start the server? For some reason, even after I echo to .bash_profile during setup, I have to set the path anytime I open a new terminal. It's weird but easy to deal with. Never had this issue before.

**Comment by sturma** [comment]
I do, yes. But it was the same with 11.10.
I've created a script which I run instead of 'rvmsudo siriproxy server', in which I execute first the RVM path and then siriproxy.
Unfortunately like you say, although .bash_profile includes it, it won't be effective.

<code>#!/bin/bash
cd /home/alex/SiriProxy
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"
rvmsudo siriproxy server
exit 0
</code>

**Comment by mynamegoeshere** [comment]
Good to know. Now I'll stop sweating it.
