### ISSUE TITLE
SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/connection.rb:148:in `has_next_object?': undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by jurgenq** [plamoni/SiriProxy#375]
I' am running SiriProxy on a mac mini with mountain lion. When I do a siri request a few seconds after the request is finished SiriProxy crashes with the following error:

[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: FinishSpeech
[Info - Guzzoni] Received Object: SpeechRecognized
[Info - Plugin Manager] Processing 'Hello '
[Info - Plugin Manager] Processing plugin #SiriProxy::Plugin::Example:0x007fe1199b76f0
[Info - Plugin Manager] No matches for 'Hello '
[Info - Guzzoni] Received Object: AddViews
[Info - Guzzoni] Received Object: RequestCompleted
[Info - iPhone] Received Object: Metrics
[Info - iPhone] Received Object: ClearContext
/Users/user1/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/connection.rb:148:in `has_next_object?': undefined method`[]' for nil:NilClass (NoMethodError)
    from /Users/user1/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/connection.rb:128:in `process_compressed_data'
    from /Users/user1/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/connection.rb:102:in`receive_binary_data'
    from /Users/user1/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/eventmachine-1.0.0/lib/em/protocols/linetext2.rb:94:in `receive_data'
    from /Users/user1/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in`run_machine'
    from /Users/user1/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run'
    from /Users/user1/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy.rb:16:in`initialize'
    from /Users/user1/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:96:in `new'
    from /Users/user1/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:96:in`start_server'
    from /Users/user1/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:85:in `run_server'
    from /Users/user1/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.0/lib/siriproxy/command_line.rb:37:in`initialize'
    from /Users/user1/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.0/bin/siriproxy:6:in `new'
    from /Users/user1/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.0/bin/siriproxy:6:in`<top (required)>'
    from /Users/user1/.rvm/gems/ruby-1.9.3-p327@SiriProxy/bin/siriproxy:23:in `load'
    from /Users/user1/.rvm/gems/ruby-1.9.3-p327@SiriProxy/bin/siriproxy:23:in`<main>'
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.

**Comment by plamoni** [comment]
This is due to a change they made to the protocol. It was fixed in https://github.com/plamoni/SiriProxy/commit/4f83a566c922be2f641f83a4ba35a52202b6c4c7. Update to the latest code and this will go away.
