### ISSUE TITLE
Variable Question

### ISSUE THREAD

**Issue by mynamegoeshere** [plamoni/SiriProxy#376]
$var1 = red
$var2 = blue

listen_for(/#{$var1}.*#{$var2}/i) { blaa }

Is the above the correct way to add a variable to a listen_for statement?

**Comment by plamoni** [comment]
This is really more of a ruby question than a SiriProxy question. `listen_for` takes a standard regular expression and a callback function, so if you construct the regex properly it should work. 

Might check here: http://www.ruby-doc.org/core-1.9.3/Regexp.html

Looks like your code should work, though. Have you tried it?
