### ISSUE TITLE
Stop Server

### ISSUE THREAD

**Issue by ghost** [plamoni/SiriProxy#380]
If you try to connect:

https://127.0.0.1:443 
https://127.0.0.1

The server will Stop, Tested on Ubuntu 12.04 (127.0.0.1 is a example)

Error:
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x824b3c0 @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x824adbc>, @zip_stream=#Zlib::Deflate:0x824ad58, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x8556ac4 @manager=#<SiriProxy::PluginManager:0x824a768 @plugins=[...]>>]
/usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/connection.rb:78:in `inflate': incorrect header check (Zlib::DataError)
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/connection.rb:78:in`process_compressed_data'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/connection.rb:58:in `receive_binary_data'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/eventmachine-1.0.0/lib/em/protocols/linetext2.rb:94:in`receive_data'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/eventmachine-1.0.0/lib/em/protocols/linetext2.rb:65:in `receive_data'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/eventmachine-1.0.0/lib/em/protocols/linetext2.rb:65:in`receive_data'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/eventmachine-1.0.0/lib/em/protocols/linetext2.rb:65:in `receive_data'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in`run_machine'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy.rb:16:in`initialize'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:96:in `new'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:96:in`start_server'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:85:in `run_server'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:37:in`initialize'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.2/bin/siriproxy:6:in `new'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.2/bin/siriproxy:6:in`<top (required)>'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/bin/siriproxy:23:in `load'
    from /usr/local/rvm/gems/ruby-1.9.3-p327@SiriProxy/bin/siriproxy:23:in`<main>'

*
Temp Fix: Stop Apache

**Comment by davidgeppelt** [comment]
Are you trying to do a loopback? If so, why?

**Comment by ghost** [comment]
No I didn't. I Just tried to check my Apache HTTPS connection

**Comment by plamoni** [comment]
SiriProxy runs on port 443 and doesn't really use HTTPS (it's a protocol similar to HTTPS, but not). It doesn't play well with HTTPS, though. So it generally just crashes. I should make it a bit more robust in that circumstance.

-Pete
