### ISSUE TITLE
Siriproxy service

### ISSUE THREAD

**Issue by maciekish** [plamoni/SiriProxy#383]
I have siriproxy up and running with my own tellstick net plugin, but it keeps closing down after a couple hours. How do i configure it as a service in the simplest way possible please? Some kind of watchdog that checks if its running?

**Comment by laxman01** [comment]
Are you still having trouble with this issue?

**Comment by maciekish** [comment]
Yes, pretty much given up on it as i have to restart it all the time.

**Comment by laxman01** [comment]
Im currently working on a GUI for siriproxy 
Features: 
Update: Updates the server
Start: Starts SiriProxy
Restart: Restarts and bundles the server
Stop: Stops the Server
Config: Replaces the config file in .siriproxy directory
![Screen Shot 2013-01-31 at 3 47 29 PM](https://f.cloud.github.com/assets/1238261/116382/7fa6260e-6bf6-11e2-995a-4028fb1275a2.png)

It would not be hard to set the program to run the restart command every hour or however long you want
just an idea

**Comment by maciekish** [comment]
Thanks, but I'm running on a headless linux box :)

**Comment by laxman01** [comment]
Damn, sorry i could not help

**Comment by plamoni** [comment]
@maciekish --- Have you tried doing an upstart script?

https://github.com/plamoni/SiriProxy#running-siriproxy-via-upstart

Sorry that SiriProxy is so crash-prone. Try updating to the latest code and it might help. Anyway, Upstart will act as a watchdog and relaunch the process if it dies. That's what I use at home. Hopefully that helps!

(PS - closing the "issue", but feel free to keep discussing)
