### ISSUE TITLE
siriproxy sqlite3

### ISSUE THREAD

**Issue by gb160** [plamoni/SiriProxy#386]
hi
working on a little project which uses siri to query a sqlite3 db.
ive installed sqlite3 gem 
ive written a .rb script that works fine from terminal ,at the top of this script is the line .....require 'sqlite3'

ive modified the example siri plugin accordingly,and added the line .......require 'sqlite3'
the server starts ok,but when pressing home button the server crashes with the line...

/Users/gav1/.siriproxy/plugins/siriproxy-example/lib/siriproxy-example.rb:5:in `require': cannot load such file -- sqlite3 (LoadError)

im hoping one of you guys will point out something obvious that im doing wrong ..... or at the worst,tell me that what im trying to accomplish isnt possible.
either way any help is greatly appreciated.
many thanks.

**Comment by AshMartian** [comment]
How did you install the gem?
What I have found is that I can only get gems that I install manually from a downloaded source. Using terminal to install gems never works for me. I also do a rake install after installing a new gem too.

Disclaimer: This is for me in my own senario with same error. I am probably wrong. And have never looked at ruby before this.

**Comment by plamoni** [comment]
I'm closing because this is a ruby question and not really a SiriProxy question. Though I think @blandman is on the right track. Feel free to continue discussion.
