### ISSUE TITLE
SIRIPROXY  -  IPHONE 5

### ISSUE THREAD

**Issue by kudox87** [plamoni/SiriProxy#387]
i can`t sure if it`s possible install siriproxy and plugins in iphone5. I use Ubuntu 12.10  I tried to send certificate  with guzzoni.apple.com but  you do a answers, and in few seconds the exits says the time has run out. if i use kryten.apple.com the server doesn`t detect the telephone. 

i use ios 6.0.1
any suggestions?

**Comment by Deanmv** [comment]
I'm using Siri Proxy 0.3.2 with iPhone 5 and iOS 6.0.1 and it works fine here.

**Comment by kudox87** [comment]
are you using kryten address??

**Comment by Deanmv** [comment]
Nope, followed the instructions on the readme and used guzzoni.

**Comment by kudox87** [comment]
i have tired to install again all. and  i say Test siri proxy. but in the terminal only put this>

Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x8b6ea10 @signature=11, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x8b6e240>, @zip_stream=#Zlib::Deflate:0x8b6e060, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x8b768a0 @manager=#<SiriProxy::PluginManager:0x8b6c544 @plugins=[...]>>]

**Comment by kudox87** [comment]
when i reinstall the certificate other thinks. processing the answer a lot of time and put 

.
.
.
.

[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x901af00 @signature=1025, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x901adfc>, @zip_stream=#Zlib::Deflate:0x901ade8, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x901a820 @manager=#<SiriProxy::PluginManager:0x901aba4 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x901a758 @signature=1026, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x901a640>, @zip_stream=#Zlib::Deflate:0x901a62c, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x901a03c @manager=#<SiriProxy::PluginManager:0x901a3fc @plugins=[...]>>]

.
.
.
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: FinishSpeech
[Info - iPhone] Received Object: LoadAssistant
[Info - iPhone] Received Object: SetRestrictions
[Info - iPhone] Received Object: ClearContext

3072747144:error:02001018:system library:fopen:Too many open files:bss_file.c:398:fopen('/home/ubuntu/.siriproxy/server.passless.key','r')
3072747144:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:400:
3072747144:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
/home/ubuntu/.rvm/gems/ruby-1.9.3-p327@SiriProxy/bin/siriproxy: ssl.cpp:166: SslContext_t::SslContext_t(bool, const string&, const string&): Assertion `e > 0' failed.
ubuntu@ubuntu:~/SiriProxy$ start conn #<SiriProxy::Connection::Iphone:0x8b6ea10 @signature=11, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x8b6e240>, @zip_stream=#Zlib::Deflate:0x8b6e060, @consumed_ace=false, @name="iPhone", @ssled=false>

**Comment by kami83** [comment]
Hi,

i am using my Iphone 5 with iOS 6.0.2 and an own siriproxy on my Linux System with DNS. This works fine in my Home-Wlan. But now i want to ask, if it is possible to connect from external with my iphone and use this siriproxy over 3G?

Thanks a lot.

Cu kami

**Comment by plamoni** [comment]
This bug has been resolved. Do a `siriproxy update` to get the fix.
