### ISSUE TITLE
Return info from python script

### ISSUE THREAD

**Issue by aframe82** [plamoni/SiriProxy#388]
Hey,

I have an opencv python script that I want to use that grabs a picture of people from my webcam, saves it and prints a bunch of webcam initiator text, that I don't want to include (but is standard when using opencv) and then 'Number of faces seen: X'.

My question is this: How can I send the text that python prints out to SiriProxy?

I want to say 'Track people' for example, and have it spit out the picture (which I'm fine with) and say 'Number of faces seen: X'.

Thanks for looking.

**Comment by plamoni** [comment]
Check here: http://tech.natemurray.com/2007/03/ruby-shell-commands.html

More of a ruby question than a SiriProxy question.
