### ISSUE TITLE
CFPropertyList error - UK iPhone 5

### ISSUE THREAD

**Issue by ghost** [plamoni/SiriProxy#390]
I've just installed siriproxy as per the instructions. 

I'm using an iPhone 5 in the UK.

Siriproxy runs ok until I activate Siri on my phone, at which point it errors out with the following:

Starting SiriProxy on port 443..
SiriProxy up and running.
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x9ea5124 @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x9ea505c>, @zip_stream=#Zlib::Deflate:0x9ea5034, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0xa3d6bac @manager=#<SiriProxy::PluginManager:0x9ea4b84 @plugins=[...]>>]
[Info - iPhone] Received Object: LoadAssistant
/home/mike/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:217:in `encode': "\xA2" on UTF-8 (Encoding::InvalidByteSequenceError)
    from /home/mike/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:217:in`charset_convert'
    from /home/mike/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:442:in `string_to_binary'
    from /home/mike/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFTypes.rb:48:in`to_binary'
    from /home/mike/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `block in dict_to_binary'
    from /home/mike/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in`map'
    from /home/mike/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `dict_to_binary'
    from /home/mike/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFTypes.rb:243:in`to_binary'
    from /home/mike/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `block in dict_to_binary'
    from /home/mike/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in`map'
    from /home/mike/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `dict_to_binary'
    from /home/mike/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFTypes.rb:243:in`to_binary'
    from /home/mike/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:70:in `to_str'
    from /home/mike/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFPropertyList.rb:363:in`to_str'
    from /home/mike/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFPropertyList.rb:398:in `to_plist'
    from /home/mike/siriproxy/SiriProxy/lib/siriproxy/connection.rb:150:in`inject_object_to_output_stream'
    from /home/mike/siriproxy/SiriProxy/lib/siriproxy/connection.rb:90:in `process_compressed_data'
    from /home/mike/siriproxy/SiriProxy/lib/siriproxy/connection.rb:58:in`receive_binary_data'
    from /home/mike/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/eventmachine-1.0.0/lib/em/protocols/linetext2.rb:94:in `receive_data'
    from /home/mike/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in`run_machine'
    from /home/mike/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run'
    from /home/mike/siriproxy/SiriProxy/lib/siriproxy.rb:16:in`initialize'
    from /home/mike/siriproxy/SiriProxy/lib/siriproxy/command_line.rb:96:in `new'
    from /home/mike/siriproxy/SiriProxy/lib/siriproxy/command_line.rb:96:in`start_server'
    from /home/mike/siriproxy/SiriProxy/lib/siriproxy/command_line.rb:85:in `run_server'
    from /home/mike/siriproxy/SiriProxy/lib/siriproxy/command_line.rb:37:in`initialize'
    from ./bin/siriproxy:6:in `new'
    from ./bin/siriproxy:6:in`<main>'
mike@vxr:~/siriproxy/SiriProxy$

**Comment by ghost** [comment]
I've just noticed the issue below appears to be the same issue. My apologies.

**Comment by plamoni** [comment]
This has been fixed in master. Do a `siriproxy update` to get the fix.
