### ISSUE TITLE
Can't "Rake Install"

### ISSUE THREAD

**Issue by Deanmv** [plamoni/SiriProxy#392]
When running rake install I get:

unknown-b8-8d-12-24-42-74:SiriProxy deanvizer$ rake install --trace
*\* Invoke install (first_time)
*\* Execute install
siriproxy 0.3.2 built to pkg/siriproxy-0.3.2.gem
rake aborted!
Couldn't install gem, run `gem install /Users/deanvizer/SiriProxy/pkg/siriproxy-0.3.2.gem' for more detailed output
/Users/deanvizer/.rvm/gems/ruby-1.9.3-p327/gems/bundler-1.2.3/lib/bundler/gem_helper.rb:68:in`install_gem'
/Users/deanvizer/.rvm/gems/ruby-1.9.3-p327/gems/bundler-1.2.3/lib/bundler/gem_helper.rb:43:in `block in install'
/Users/deanvizer/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/task.rb:228:in`call'
/Users/deanvizer/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/task.rb:228:in `block in execute'
/Users/deanvizer/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/task.rb:223:in`each'
/Users/deanvizer/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/task.rb:223:in `execute'
/Users/deanvizer/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/task.rb:166:in`block in invoke_with_call_chain'
/Users/deanvizer/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/Users/deanvizer/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/task.rb:159:in`invoke_with_call_chain'
/Users/deanvizer/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/task.rb:152:in `invoke'
/Users/deanvizer/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/application.rb:143:in`invoke_task'
/Users/deanvizer/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/application.rb:101:in `block (2 levels) in top_level'
/Users/deanvizer/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/application.rb:101:in`each'
/Users/deanvizer/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/application.rb:101:in `block in top_level'
/Users/deanvizer/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/application.rb:110:in`run_with_threads'
/Users/deanvizer/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/application.rb:95:in `top_level'
/Users/deanvizer/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/application.rb:73:in`block in run'
/Users/deanvizer/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/application.rb:160:in `standard_exception_handling'
/Users/deanvizer/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/lib/rake/application.rb:70:in`run'
/Users/deanvizer/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.3/bin/rake:33:in `<top (required)>'
/Users/deanvizer/.rvm/gems/ruby-1.9.3-p327/bin/rake:23:in`load'
/Users/deanvizer/.rvm/gems/ruby-1.9.3-p327/bin/rake:23:in `<main>'
Tasks: TOP => install
unknown-b8-8d-12-24-42-74:SiriProxy deanvizer$ 

So then doing: 

nknown-b8-8d-12-24-42-74:SiriProxy deanvizer$ gem install /Users/deanvizer/SiriProxy/pkg/siriproxy-0.3.2.gem
Fetching: CFPropertyList-2.2.0.gem (100%)
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied - /Users/deanvizer/.rvm/gems/ruby-1.9.3-p327/cache/CFPropertyList-2.2.0.gem
unknown-b8-8d-12-24-42-74:SiriProxy deanvizer$ 

Then with Sudo I get: 

nknown-b8-8d-12-24-42-74:SiriProxy deanvizer$ sudo gem install /Users/deanvizer/SiriProxy/pkg/siriproxy-0.3.2.gem
Password:
Successfully installed siriproxy-0.3.2
1 gem installed
Installing ri documentation for siriproxy-0.3.2...
file 'lib' not found
Installing RDoc documentation for siriproxy-0.3.2...
file 'lib' not found

Anyone found anything like this?

**Comment by zenwheel** [comment]
I saw that, one of the previous steps got things in the ~/.rvm directory owned as root, I just did a "sudo chown -R `whoami` ~/.rvm" to take ownership back.

**Comment by Deanmv** [comment]
Spot on, thanks @zenwheel !

**Comment by reliablesource** [comment]
Just saved me a big head ache, Thanks!

**Comment by TilBlechschmidt** [comment]
I searched hours to find a solution, thank you!
