### ISSUE TITLE
ASCII PROBLEMS FOR SPANISH SIRIPROXY

### ISSUE THREAD

**Issue by paradajoseluis** [plamoni/SiriProxy#393]
the thing is that i cannot program siri in spanish because it can not use á, é, í, ó and ú. 
if i use it in a listen command siriproxy crashes. i thing that it only uses ASCII-US and i need Extended ASCII Codes. how can i add them?
here is a reference of an ASCII chart and extended ASCII codes. http://www.asciitable.com.
thanks

**Comment by plamoni** [comment]
Probably UTF-8 would be a better path to go down than the not-really-standard "extended ASCII." SiriProxy never officially supported non-ASCII characters, but I think people are having some luck with it. Personally, I speak English and about 4 words of Spanish. So I'm not a good person to tackle this issue.

There's been discussion elsewhere on this, so you might look around. Closing the issue for the sake of cleanup.
