### ISSUE TITLE
Can not ceck /etc/sudoers for secure path!

### ISSUE THREAD

**Issue by grausof** [plamoni/SiriProxy#394]
Hi, I've installed SiriProxy on Ubuntu 12.10. Everything went well, but when I go to give the command "rvmsudo siriproxy server", I get this error message: "Can not ceck /etc/sudoers for secure path..." I leave attached the screenshot. Can you help me solve this problem? For the installation I have followed this guide: http://www.idownloadblog.com/2011/12/09/how-to-install-siri-proxy-tutorial-video/

Thanks for the HELP!

![screenshot](https://f.cloud.github.com/assets/442709/24388/d52bbbb8-4aa2-11e2-99bb-87b5790ac70c.png)

**Comment by gavros** [comment]
Did you do what the warning asked? At the prompt type>
export rvmsudo_secure_ath=1

**Comment by grausof** [comment]
OK with this command, the error no longer appears. But the proxy still does not work! After calling SIRI from iPhone, the proxy stops, returning a set of values ​​that I leave attached.
![end](https://f.cloud.github.com/assets/442709/25889/0475ae52-4afc-11e2-9688-d2a2f877d654.png)

**Comment by gavros** [comment]
Yeah thats not going to help. Look at the beginning (when you issued the siriproxy server command)
If you see this:
SiriProxy up and running.

If you see this somehwere:
/rbBinaryCFPropertyList.rb:217:in encode': "\xAB" on UTF-8 (Encoding::InvalidByteSequenceError)

Then look back at issue #389 for the fix. I have this problem however, the fix did not work for me :(

Good luck

**Comment by grausof** [comment]
OK, my problem is the same as yours. I've try the issue #389 for the fix but doesn't work!

**Comment by gavros** [comment]
Ok I think I figured it out. This is what I did.
Follow the instructions mentioned in #389 
- Change into the SiriProxy directory 
- run: "sudo vi siriproxy.gemspec" 
- Replace the line approx 4 from bottom which contains "CFPropertyList" with the below: s.add_runtime_dependency('CFPropertyList', '2.1.2') 
- stop the server 
- run > siriproxy update
- after that do a > rake install 
- start the server

**Comment by grausof** [comment]
tried, but the problem persists! :(

**Comment by pilliq** [comment]
@grausof could you paste the entire stack trace of the error you're getting?

**Comment by grausof** [comment]
This is a part of message:
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: FinishSpeech
[Info - iPhone] Received Object: LoadAssistant
[Info - iPhone] Received Object: SetRestrictions
[Info - iPhone] Received Object: ClearContext
[Info - iPhone] Received Object: SetSessionObjects
[Info - iPhone] Received Object: StartSpeechRequest
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x9c41d9c @signature=970, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x9c41bbc>, @zip_stream=#Zlib::Deflate:0x9c41b58, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x9b47450 @manager=#<SiriProxy::PluginManager:0x9c41630 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x9b472ac @signature=971, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x9b47018>, @zip_stream=#Zlib::Deflate:0x9b46fc8, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x9b463e8 @manager=#<SiriProxy::PluginManager:0x9b469b0 @plugins=[...]>>]
[Info - iPhone] Received Object: LoadAssistant
[Info - iPhone] Received Object: SetRestrictions
[Info - iPhone] Received Object: ClearContext
[Info - iPhone] Received Object: SetSessionObjects
[Info - iPhone] Received Object: StartSpeechRequest
[Info - iPhone] Received Object: SetRequestOrigin

and this:
Create server for iPhone connection
3073128072:error:02001018:system library:fopen:Too many open files:bss_file.c:398:fopen('/home/francesco/.siriproxy/server.passless.key','r')
3073128072:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:400:
3073128072:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
ruby: ssl.cpp:166: SslContext_t::SslContext_t(bool, const string&, const string&): Assertion `e > 0' failed.

**Comment by pilliq** [comment]
hmm, too many open files? Not exactly sure what the error is, but for now you can increase the max open files for the entire system by editing /etc/sysctl.conf and appending:

fs.file-max = 100000

then running:

# sysctl -p

and verifying that your settings took effect:

# cat /proc/sys/fs/file-max
(should output 100000)

then run siriproxy again and see if this resolves the problem.

**Comment by grausof** [comment]
The problem persist. The first time that i run siriproxy server, appear many messages that I pasted above. But, if i run siriproxy server the second time, notting happens and siri  responds as if there were no proxy. When i stop SiriProxy i get this message: 
Starting SiriProxy on port 443..
SiriProxy up and running.
^C/home/francesco/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run_machine': Interrupt
    from /home/francesco/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in`run'
    from /home/francesco/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy.rb:16:in `initialize'
    from /home/francesco/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:96:in`new'
    from /home/francesco/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:96:in `start_server'
    from /home/francesco/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:85:in`run_server'
    from /home/francesco/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:37:in `initialize'
    from /home/francesco/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.2/bin/siriproxy:6:in`new'
    from /home/francesco/.rvm/gems/ruby-1.9.3-p327@SiriProxy/gems/siriproxy-0.3.2/bin/siriproxy:6:in `<top (required)>'
    from /home/francesco/.rvm/gems/ruby-1.9.3-p327@SiriProxy/bin/siriproxy:23:in`load'
    from /home/francesco/.rvm/gems/ruby-1.9.3-p327@SiriProxy/bin/siriproxy:23:in `<main>'
I've also reinstalled ubuntu but I've not solved! Which OS you use, and which version of RVM?

**Comment by pilliq** [comment]
I'm using raspbian wheezy for raspberry pi with ruby 1.9.3. 

Looks like siriproxy is running fine on your machine, but requests from the iphone are not getting to your machine. Are you sure you edited /etc/dnsmasq.conf to include this line: 

address=/guzzoni.apple.com/(your_machine's_ip_address)

and that the ip address is the ip address of your ubuntu machine?

Also make sure your iphone is connected to your local network and that your machine is accessible from your iphone.

**Comment by grausof** [comment]
Ok, I solved the problem. :)  Was not due to a misconfiguration, but in the file etc/resolv.conf there was no a DNS server IP, but there was the IP of my PC. Fix: #56 :+1: Thanks for your patience.

**Comment by pilliq** [comment]
glad to help, and glad you solved it.

**Comment by JoshuaCarroll** [comment]
For future readers, please note the typo in the command given to fix the "Can not ceck /etc/sudoers for secure path..." problem.  The correct command (and what I'm sure @gavros meant to type) is:

```
export rvmsudo_secure_path=1
```
