### ISSUE TITLE
rake install fails with enclosed error

### ISSUE THREAD

**Issue by the-maldridge** [plamoni/SiriProxy#396]
ERROR:  While executing gem ... (Gem::InvalidSpecificationException)
    ["config.example.yml"] are not files

OS is kubuntu 12.04, all updates installed.

all steps prior to step two of the SiriProxy install procedure completed without error, any help is appreciated.

**Comment by plamoni** [comment]
Can you provide more contextual information? What command did you run? Where did you run it? Is there a config.example.yml nearby?

**Comment by elvisimprsntr** [comment]
closed due to inactivity
