### ISSUE TITLE
Requests timing out

### ISSUE THREAD

**Issue by jmmmm4** [plamoni/SiriProxy#397]
I've yet to find the cause (still trying to learn Ruby and debug through it!) but I've noticed the following scenario which causes siri to be unresponsive on the phone, and the siriproxy server too.

1) Siriproxy is running correctly with only example plugin configured
2) Using iPhone4S, send a request to siriproxy
3) Proxy hits Guzzoni and receives response
4) Siriproxy executes regex and executes plugin, returning successful response to the device
5) Using same iPhone, make another request for the same speech
6) Proxy fails to get response from Guzzoni and enters a wait cycle; Siri on iPhone also waits as connection is hung

This is only intermittent, but once it appears its reproducible.

7) Tapping the siri icon on the iPhone sends a CancelRequest to siriproxy
8) Making the same request again, works and siriproxy gets a successful response from Guzzoni
9) Every other request will now work

The only useful thing in the log is once siri on the device has finished sending the request, but no response has been received from siriproxy, the log shows:

"[Info - iPhone] Received Object: FinishSpeech"

In a successful state, this would be following by:

"[Info - Guzzoni] Received Object: SpeechRecognized"

Anyone else noticed similar issue? I'll try to debug later tonight/add some additional logging etc.

**Comment by Deanmv** [comment]
Duplicate of #143 ? Lot of comments on there about it.

**Comment by jmmmm4** [comment]
It is - closing the duplicate.
