### ISSUE TITLE
Problem with server start

### ISSUE THREAD

**Issue by digio-zz** [plamoni/SiriProxy#40]
when i start the server, the following error occurs on:

$ sudo ruby start.rb
start.rb:3: warning: variable $KCODE is no longer effective; ignored
/Users/pascallang/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': no such file to load -- uuidtools (LoadError)
    from /Users/pascallang/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from /Users/pascallang/SiriProxy/siriObjectGenerator.rb:2:in `<top (required)>'
    from <internal:lib/rubygems/custom_require>:29:in`require'
    from internal:lib/rubygems/custom_require:29:in `require'
    from /Users/pascallang/SiriProxy/plugins/testproxy/testproxy.rb:2:in`<top (required)>'
    from internal:lib/rubygems/custom_require:29:in `require'
    from <internal:lib/rubygems/custom_require>:29:in`require'
    from start.rb:5:in `<main>'

so i tried it with this command:

$ rvmsudo ruby start.rb
start.rb:3: warning: variable $KCODE is no longer effective; ignored
/Users/pascallang/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': /Users/pascallang/SiriProxy/siriProxy.rb:274: syntax error, unexpected $end, expecting keyword_end (SyntaxError)
    from /Users/pascallang/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from start.rb:10:in `<main>'

somebody has an idea about this problem?

**Comment by courtenay** [comment]
gem install uuidtools

did you follow the readme?

On Thu, Nov 24, 2011 at 1:38 AM, digio <
reply@reply.github.com

**Comment by digio-zz** [comment]
i have installed uuidtools

yes, i have followed the read me...

**Comment by courtenay** [comment]
try the refactor branch instead. it has a slightly different readme too.

On Thu, Nov 24, 2011 at 1:41 AM, digio <
reply@reply.github.com

**Comment by digio-zz** [comment]
I've tried and then get the second error message...

$ rvmsudo ruby start.rb
start.rb:3: warning: variable $KCODE is no longer effective; ignored
/Users/pascallang/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in require': /Users/pascallang/SiriProxy/siriProxy.rb:274: syntax error, unexpected $end, expecting keyword_end (SyntaxError)
from /Users/pascallang/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:inrequire'
from start.rb:10:in `'

**Comment by courtenay** [comment]
there's no SiriProxy in the refactor branch.  Check that out and try again

(also, looks like you edited that file. try reverting it)

On Thu, Nov 24, 2011 at 2:07 AM, digio <
reply@reply.github.com

**Comment by digio-zz** [comment]
ok i have taken the refactor branch, now comes a new error message

$ rvmsudo ruby start.rb
/Library/Ruby/Gems/1.8/gems/bundler-1.0.21/lib/bundler/runtime.rb:138: warning: Insecure world writable dir /Library/Ruby/Gems/1.8 in PATH, mode 040777
Starting SiriProxy on port 443..
./siri_proxy.rb:27:in `initialize': Cannot start the server on port 443 - are you root, or have another process on this port already? (RuntimeError)
    from /Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`call'
    from /Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
    from /Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run'
    from ./siri_proxy.rb:18:in `initialize'
    from start.rb:21:in`new'
    from start.rb:21

**Comment by courtenay** [comment]
So? Do you?

 Cannot start the server on port 443 - are you root, or have another
process on this port already? (RuntimeError)

On Thu, Nov 24, 2011 at 2:52 AM, digio <
reply@reply.github.com

**Comment by digio-zz** [comment]
It's work now!

**Comment by ewoo** [comment]
digio, what was the problem? I'm having the same issue...

**Comment by gotnull** [comment]
@digio Yes, what was the problem. I keep receiving the following error:

https://github.com/plamoni/SiriProxy/issues/163#issuecomment-3136295
