### ISSUE TITLE
Create server for iPhone connection

### ISSUE THREAD

**Issue by DanielSunDE** [plamoni/SiriProxy#401]
Hello
I have a small Problem
I do all what stand in the description.

for the dnsmasq I put the my pi ip 10.0.1.200
I installt also all the other things.

Ich I restart the dnsmasq I get:
[ ok ] Restarting DNS forwarder and DHCP server: dnsmasq.

I also copied the certificate on my German iphone 5

if I start the SiriProxy Server I get this:
Starting SiriProxy on port 443..
SiriProxy up and running.

I ohter Post i readed the normaly should come also a message like:
Create server for iPhone connection
But I dont get this notification

But if i say to Siri "Test Siri Server" Siri won't to search for it on Internet.

On my routers i forwarded the Port 443 to my pi ip.

Have any one a idea whats the Problem?

Greats Daniel

**Comment by DanielSunDE** [comment]
Ok i found my Problem i forget to change my DNS on the iPhone.

But now i get this Problem:

start conn #<SiriProxy::Connection::Iphone:0x******** @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x142c9b0>, @zip_stream=#Zlib::Deflate:0x12aaca0, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x1962030 @manager=#<SiriProxy::PluginManager:0x12a9b60 @plugins=[...]>>]
[Info - iPhone] Received Object: LoadAssistant
/home/pi/.rvm/gems/ruby-1.9.3-p362@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:217:in `encode': "\xB4" on UTF-8 (Encoding::InvalidByteSequenceError)
    from /home/pi/.rvm/gems/ruby-1.9.3-p362@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:217:in`charset_convert'
    from /home/pi/.rvm/gems/ruby-1.9.3-p362@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:442:in `string_to_binary'
    from /home/pi/.rvm/gems/ruby-1.9.3-p362@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFTypes.rb:48:in`to_binary'
    from /home/pi/.rvm/gems/ruby-1.9.3-p362@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `block in dict_to_binary'
    from /home/pi/.rvm/gems/ruby-1.9.3-p362@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in`map'
    from /home/pi/.rvm/gems/ruby-1.9.3-p362@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `dict_to_binary'
    from /home/pi/.rvm/gems/ruby-1.9.3-p362@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFTypes.rb:243:in`to_binary'
    from /home/pi/.rvm/gems/ruby-1.9.3-p362@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `block in dict_to_binary'
    from /home/pi/.rvm/gems/ruby-1.9.3-p362@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in`map'
    from /home/pi/.rvm/gems/ruby-1.9.3-p362@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `dict_to_binary'
    from /home/pi/.rvm/gems/ruby-1.9.3-p362@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFTypes.rb:243:in`to_binary'
    from /home/pi/.rvm/gems/ruby-1.9.3-p362@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:70:in `to_str'
    from /home/pi/.rvm/gems/ruby-1.9.3-p362@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFPropertyList.rb:363:in`to_str'
    from /home/pi/.rvm/gems/ruby-1.9.3-p362@SiriProxy/gems/CFPropertyList-2.2.0/lib/rbCFPropertyList.rb:398:in `to_plist'
    from /home/pi/SiriProxy/lib/siriproxy/connection.rb:150:in`inject_object_to_output_stream'
    from /home/pi/SiriProxy/lib/siriproxy/connection.rb:90:in `process_compressed_data'
    from /home/pi/SiriProxy/lib/siriproxy/connection.rb:58:in`receive_binary_data'
    from /home/pi/.rvm/gems/ruby-1.9.3-p362@SiriProxy/gems/eventmachine-1.0.0/lib/em/protocols/linetext2.rb:94:in `receive_data'
    from /home/pi/.rvm/gems/ruby-1.9.3-p362@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in`run_machine'
    from /home/pi/.rvm/gems/ruby-1.9.3-p362@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run'
    from /home/pi/SiriProxy/lib/siriproxy.rb:16:in`initialize'
    from /home/pi/SiriProxy/lib/siriproxy/command_line.rb:96:in `new'
    from /home/pi/SiriProxy/lib/siriproxy/command_line.rb:96:in`start_server'
    from /home/pi/SiriProxy/lib/siriproxy/command_line.rb:85:in `run_server'
    from /home/pi/SiriProxy/lib/siriproxy/command_line.rb:37:in`initialize'
    from /home/pi/SiriProxy/bin/siriproxy:6:in `new'
    from /home/pi/SiriProxy/bin/siriproxy:6:in`<top (required)>'
    from /home/pi/.rvm/gems/ruby-1.9.3-p362@SiriProxy/bin/siriproxy:19:in `load'
    from /home/pi/.rvm/gems/ruby-1.9.3-p362@SiriProxy/bin/siriproxy:19:in`<main>'
    from /home/pi/.rvm/gems/ruby-1.9.3-p362@SiriProxy/bin/ruby_noexec_wrapper:14:in `eval'
    from /home/pi/.rvm/gems/ruby-1.9.3-p362@SiriProxy/bin/ruby_noexec_wrapper:14:in`<main>'

**Comment by MaxHayman** [comment]
I get this as well ^^ help would be appreciated

**Comment by laxman01** [comment]
im having the same problem. please let me know if you make any progress on figuring it out.

**Comment by DanielSunDE** [comment]
Hi at first do this

Change into the SiriProxy directory
run: "sudo vi siriproxy.gemspec"
Replace the line approx 4 from bottom which contains "CFPropertyList" with the below: s.add_runtime_dependency('CFPropertyList', '2.1.2')
stop the server
run > siriproxy update
after that do a > rake install

then you have to copy the content from
SiriProxy/gems/CFPropertyList-2.1.2
to 
SiriProxy/gems/CFPropertyList-2.2.0/

after this you type
export rvmsudo_secure_path=1
and start the server

Greats Daniel

P.S. SiriProxy is a great Projekt i love it it works great :-)

**Comment by laxman01** [comment]
DanielSun81 can you please help me with my issue

https://github.com/plamoni/SiriProxy/issues/402

**Comment by plamoni** [comment]
This has been fixed in master. Upgrade using `siriproxy upgrade` to get the latest code.
