### ISSUE TITLE
SiriProxy Server Quits Immediately 

### ISSUE THREAD

**Issue by laxman01** [plamoni/SiriProxy#402]
$ dnsmasq

dnsmasq: failed to create listening socket for 192.168.1.49: Permission denied

$ sudo killall named

No matching processes were found

$ sudo port install dnsmasq
--->  Cleaning dnsmasq
--->  Scanning binaries for linking errors: 100.0%
--->  No broken files found.

$ sudo dnsmasq

dnsmasq: failed to create listening socket for 192.168.1.49: Address already in use

$ cd /Users/laxgoalie1996/Desktop/SiriProxy 

$ rvm use 1.9.3

Using /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p362

$ siriproxy bundle

Using rake (10.0.3) 
Using CFPropertyList (2.2.0) 
Using geocoder (1.1.6) 
Using cora (0.0.4) 
Using eventmachine (1.0.0) 
Using uuidtools (2.1.3) 
Using siriproxy (0.3.2) from source at . 
Using siriproxy-example (0.0.1) from source at ./plugins/siriproxy-example 
Using bundler (1.2.3) 
Your bundle is complete! Use `bundle show [gemname]` to see where a bundled gem is installed.

$ rvmsudo siriproxy server

Warning: can not check `/etc/sudoers` for `secure_path`, falling back to call via `/usr/bin/env`, this breaks rules from `/etc/sudoers`. export rvmsudo_secure_path=1 to avoid the warning.Starting SiriProxy on port 443..
SiriProxy up and running.

As soon as I open siri the server quits and this is my response

Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007ff5fb0c5b18 @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007ff5fb0c5988>, @zip_stream=#Zlib::Deflate:0x007ff5fb0c5938, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007ff5fb214aa0 @manager=#<SiriProxy::PluginManager:0x007ff5fb0c5500 @plugins=[...]>>]
[Info - iPhone] Received Object: LoadAssistant
/Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p362/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:217:in `encode': "\xC1" on UTF-8 (Encoding::InvalidByteSequenceError)
    from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p362/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:217:in`charset_convert'
    from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p362/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:442:in `string_to_binary'
    from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p362/gems/CFPropertyList-2.2.0/lib/rbCFTypes.rb:48:in`to_binary'
    from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p362/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `block in dict_to_binary'
    from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p362/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in`map'
    from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p362/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `dict_to_binary'
    from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p362/gems/CFPropertyList-2.2.0/lib/rbCFTypes.rb:243:in`to_binary'
    from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p362/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `block in dict_to_binary'
    from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p362/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in`map'
    from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p362/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `dict_to_binary'
    from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p362/gems/CFPropertyList-2.2.0/lib/rbCFTypes.rb:243:in`to_binary'
    from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p362/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:70:in `to_str'
    from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p362/gems/CFPropertyList-2.2.0/lib/rbCFPropertyList.rb:363:in`to_str'
    from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p362/gems/CFPropertyList-2.2.0/lib/rbCFPropertyList.rb:398:in `to_plist'
    from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p362/gems/siriproxy-0.3.2/lib/siriproxy/connection.rb:150:in`inject_object_to_output_stream'
    from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p362/gems/siriproxy-0.3.2/lib/siriproxy/connection.rb:90:in `process_compressed_data'
    from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p362/gems/siriproxy-0.3.2/lib/siriproxy/connection.rb:58:in`receive_binary_data'
    from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p362/gems/eventmachine-1.0.0/lib/em/protocols/linetext2.rb:94:in `receive_data'
    from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p362/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in`run_machine'
    from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p362/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run'
    from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p362/gems/siriproxy-0.3.2/lib/siriproxy.rb:16:in`initialize'
    from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p362/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:96:in `new'
    from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p362/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:96:in`start_server'
    from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p362/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:85:in `run_server'
    from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p362/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:37:in`initialize'
    from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p362/gems/siriproxy-0.3.2/bin/siriproxy:6:in `new'
    from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p362/gems/siriproxy-0.3.2/bin/siriproxy:6:in`<top (required)>'
    from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p362/bin/siriproxy:23:in `load'
    from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p362/bin/siriproxy:23:in`<main>'
zlib(finalizer): the stream was freed prematurely.

Where did i go wrong

**Comment by Deanmv** [comment]
To begin with run rvmsudo_secure_path=1

and then look at #395 for the rest, it's an error with the update of CFPropertyList to 2.2.0

**Comment by plamoni** [comment]
This problem has been resolved. Run `siriproxy update` to get the fix.
