### ISSUE TITLE
Lost Letters

### ISSUE THREAD

**Issue by TonyLianLong** [plamoni/SiriProxy#404]
Sorry,my English is bad.
 I use Siriproxy's default plugin.
 And I use Chinese.
 Lost letters.
 I say 最近好吗 it process 最好吗。
 But on iPhone,it's right.
 Just wrong on my siriproxy.
 English is all OK.
 How do I want to do？

**Comment by EricInBj** [comment]
哈哈，编码问题，修改那个plugin文件，第一行  # encoding: utf-8

**Comment by TonyLianLong** [comment]
不是编码问题……你是有坑？我修好了，删了一行

**Comment by EricInBj** [comment]
我这儿之前一样的情况，编码设置完就好

发自我的 iPhone

在 2013-1-6，19:22，"TonyLianLong" notifications@github.com 写道：

**Comment by galenzhao** [comment]
@TonyLianLong
please tell me how to fix that,
i already add the "# encoding: utf-8", but it doesnt work,

**Comment by plamoni** [comment]
I think this is fixed now. I believe it was a problem with a field in the objects being passed from guzzoni. It was saying that things were ending with a space, but they weren't really, causing it to delete characters unnecessarily. Do a `siriproxy update` and see if that resolves the issue.

**Comment by galenzhao** [comment]
@plamoni 
Hi, the console output is correct now, but still can not match Chinese characters,
in plugin:

```
listen_for /中文测试/i do
say "中文测试成功!" #say something to the user!
request_completed #always complete your request! Otherwise the phone will "spin" at the user!
end
```

console output:

```
[Info - Guzzoni] Received Object: SpeechRecognized
[Info - Plugin Manager] Processing '中文测试 '
[Info - Plugin Manager] Processing plugin #<SiriProxy::Plugin::Example:0x898a014>
[Info - Plugin Manager] No matches for '中文测试 '
[Info - Guzzoni] Received Object: AddViews
```

is it a bug or something else?

**Comment by galenzhao** [comment]
@plamoni 
it works, the match rules should delete the space

**Comment by elvisimprsntr** [comment]
fixed in latest SP
