### ISSUE TITLE
VPN Help

### ISSUE THREAD

**Issue by laxman01** [plamoni/SiriProxy#405]
I have just recently gotten SiriProxy working and would like to set up a VPN to use Siriproxy outside of my home network. I know nothing about setting up one, so I did extensive research on the topic but still do not fully understand it. I know this may be the wrong place to post this, but I don't know where else i could help with this. So what I'm asking is that if someone could help me setup up a VPN or direct me towards a tutorial or just recommend a VPN client. I also would like to not have to pay and hopefully there are free VPN clients to use. Any help with this would be greatly appreciated. Thank you.

**Comment by caseyram** [comment]
I am actually working towards that goal right now. I would suggest using Linode as they are pretty cheap for the quality of what you get. You can setup pptpd for your VPN and use dnsmasq to intercept your requests for guzzoni.apple.com. I am having some stability issues with the siriproxy install currently but do have it working on both my iphone and ipad. I am not having to change settings or have a local machine up every time I want to use it. The biggest issues is stability right now. I'm not sure what you will find that's free but if you need to use the server for other things it may help with the cost. Good Luck.

**Comment by laxman01** [comment]
Thank you for your response and I will check out linode.
