### ISSUE TITLE
Encryption not available on this event-machine

### ISSUE THREAD

**Issue by 7imbrook** [plamoni/SiriProxy#41]
When I run the server it goes to :

  Starting SiriProxy on port 443..

then once I activate siri on the iphone, siri starts then stops and the server does this:

  Create server for iPhone connection
  terminate called after throwing an instance of 'std::runtime_error'
    what():  Encryption not available on this event-machine

I have tried remaking the CAs with no luck.
Any suggestions?
Thanks

**Comment by Matoz** [comment]
I had the same problem. 

Installing libssl-dev did the trick for me.

ubuntu example: aptitude install libssl-dev 

I think I reinstalled event-machine gem again after this but not sure about this anymore.

Hope this helps.

**Comment by 7imbrook** [comment]
worked thanks
