### ISSUE TITLE
SiriProxy Server Quitting after a while

### ISSUE THREAD

**Issue by Alainbb** [plamoni/SiriProxy#411]
Hi
New SiriProxy user - running on Raspberry Pi, and working well, in general.

Two issues:

1 - After first command - the Siri icon  spins forever, I need to stop it on the iPhone and restart. Tried a fix on adding lines in the connection.rb file, but no real change.  Help please?

2 - Not knowing exactly when it happens, a few hours into the SiriProxy server running, it stops.  These are the last few lines I see in the terminal window (pasted below).  Help please?

Thanks
Alain

Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x1d3bc08 @signature=234, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x1d3b8c0>, @zip_stream=#Zlib::Deflate:0x1d3b8a8, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x1d3a480 @manager=#<SiriProxy::PluginManager:0x1d3b038 @plugins=[...]>>]
/usr/local/rvm/gems/ruby-1.9.3-p362@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/connection.rb:78:in `inflate': incorrect header check (Zlib::DataError)
    from /usr/local/rvm/gems/ruby-1.9.3-p362@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/connection.rb:78:in`process_compressed_data'
    from /usr/local/rvm/gems/ruby-1.9.3-p362@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/connection.rb:58:in `receive_binary_data'
    from /usr/local/rvm/gems/ruby-1.9.3-p362@SiriProxy/gems/eventmachine-1.0.0/lib/em/protocols/linetext2.rb:94:in`receive_data'
    from /usr/local/rvm/gems/ruby-1.9.3-p362@SiriProxy/gems/eventmachine-1.0.0/lib/em/protocols/linetext2.rb:65:in `receive_data'
    from /usr/local/rvm/gems/ruby-1.9.3-p362@SiriProxy/gems/eventmachine-1.0.0/lib/em/protocols/linetext2.rb:65:in`receive_data'
    from /usr/local/rvm/gems/ruby-1.9.3-p362@SiriProxy/gems/eventmachine-1.0.0/lib/em/protocols/linetext2.rb:65:in `receive_data'
    from /usr/local/rvm/gems/ruby-1.9.3-p362@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in`run_machine'
    from /usr/local/rvm/gems/ruby-1.9.3-p362@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run'
    from /usr/local/rvm/gems/ruby-1.9.3-p362@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy.rb:16:in`initialize'
    from /usr/local/rvm/gems/ruby-1.9.3-p362@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:96:in `new'
    from /usr/local/rvm/gems/ruby-1.9.3-p362@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:96:in`start_server'
    from /usr/local/rvm/gems/ruby-1.9.3-p362@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:85:in `run_server'
    from /usr/local/rvm/gems/ruby-1.9.3-p362@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:37:in`initialize'
    from /usr/local/rvm/gems/ruby-1.9.3-p362@SiriProxy/gems/siriproxy-0.3.2/bin/siriproxy:6:in `new'
    from /usr/local/rvm/gems/ruby-1.9.3-p362@SiriProxy/gems/siriproxy-0.3.2/bin/siriproxy:6:in`<top (required)>'
    from /usr/local/rvm/gems/ruby-1.9.3-p362@SiriProxy/bin/siriproxy:23:in `load'
    from /usr/local/rvm/gems/ruby-1.9.3-p362@SiriProxy/bin/siriproxy:23:in`<main>'
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.

**Comment by Alainbb** [comment]
Anyone?  Especially for #2 please.
Thank you!

**Comment by plamoni** [comment]
SiriProxy likes to crash. :-)

If you plan to run it full time, you should probably set up something to auto-relaunch when it dies. Consider Upstart as described here: https://github.com/plamoni/SiriProxy#running-siriproxy-via-upstart
