### ISSUE TITLE
Can't run siriproxy after logging out

### ISSUE THREAD

**Issue by Nem0oo** [plamoni/SiriProxy#412]
Hi,
I managed to install siriproxy on a debian (I could'nt on an ubuntu) by following the step listed here :
https://gist.github.com/1428474
(I had to create ~/.siriproxy/config.yml before "rake install)
The end of the process was good.

Then I tried siriproxy on my iphone and it seems my dns was wrong
https://github.com/plamoni/SiriProxy#faq

So I closed my terminal and tried to correct this.

Then when I thought I did,
I tried running the proxy again

Siriproxy server,
I had A LOT of errors, whitch I fixed by adding some path in the $PATH var.
like siriproxy no such file ...etc

Now I get thoses, 

``` sh
siri@SiriProxy:~$ siriproxy server
/home/siri/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:247:in `to_specs': Could not find siriproxy (>= 0) amongst [bigdecimal-1.1.0, bundler-1.2.3, io-console-0.3, json-1.5.4, minitest-2.5.1, rake-10.0.3, rake-0.9.2.2, rdoc-3.9.4, rubygems-bundler-1.1.0, rvm-1.11.3.5] (Gem::LoadError)   
from /home/siri/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:256:in `to_spec'    
from /home/siri/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/site_ruby/1.9.1/rubygems.rb:1231:in `gem'  
from /home/siri/.rvm/gems/ruby-1.9.3-p374@SiriProxy/bin/siriproxy:18:in `<main>'    
from /home/siri/.rvm/gems/ruby-1.9.3-p374@global/bin/ruby_noexec_wrapper:14:in `eval'   
from /home/siri/.rvm/gems/ruby-1.9.3-p374@global/bin/ruby_noexec_wrapper:14:in `<main>'
```

and I don't know how to deal with them... hope you can help

I'm sorry for my bad english, I'm french.
Thank you !

**Comment by plamoni** [comment]
When you open your terminal, run the following to get things working again:

```
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"
```
