### ISSUE TITLE
Plugin's

### ISSUE THREAD

**Issue by laxman01** [plamoni/SiriProxy#413]
http://pastebin.com/6dZxAvCH

could someone please check this plugin for me 

thank you

**Comment by Deanmv** [comment]
Is it not hosted anywhere as a repo?

**Comment by laxman01** [comment]
no i have it all on my computer i just uploaded the code to this site

**Comment by Raggyx** [comment]
have you seen the example plugin? regarding on how to ask a question in a siriproxy plugin
https://github.com/plamoni/SiriProxy/tree/master/plugins/siriproxy-example
btw every <code>listen_for /.../i do</code> has to be closed by an <code>end</code>
and the <code>if</code> statements too :)

**Comment by laxman01** [comment]
yes i have seen the example plugin but i did not see on how to ask questions on it and thank you for your help with that

**Comment by Raggyx** [comment]
<code>listen_for /quiz/i do
response = ask "Question"
if response.strip == "Answer"
#do something
end
end
</code>

use "say" to say something an use "ask" like i did to ask something

edit: see from line 65 in the file 'siriproxy-example.rb'

**Comment by laxman01** [comment]
What im trying to set up is something like flashcards.. where i would say quiz me then it would ask me a series of programed in questions for whatever class, then after the question has been asked and i have answered it myself i will say "answer" then siri will tell me the correct answer then i will say "next" and it will repeat this process with all the other questions

**Comment by laxman01** [comment]
listen_for /Quiz Me In (.*)/i do |userAction|
  userAction.strip!
if userAction == "Bio" or userAction == "Biology" or userAction == "Science" then
Say"Question"
answer = listen_for /Answer/i do
end
answer.strip!
if answer == "Answer"
say "Answer"
question = listen_for /Next/i do
end
question.strip!
if question == "Next"
say "Question"

**Comment by laxman01** [comment]
This is  currently where i'm at.

**Comment by laxman01** [comment]
listen_for /Quiz Me In (.*)/i do |userAction|
     userAction.strip!
if userAction == "Bio" or userAction == "Biology" or userAction == "Science" then
    question == ask "Question"
    question.strip!
if question == "Answer" or question == "Show me the Answer" then
    say "Answer"
request_completed
  end

the error im getting is this 

syntax error, unexpected tSTRING_BEG, expecting keyword_do or '{' or '(' (SyntaxError)
    question == ask "Question"

**Comment by laxman01** [comment]
/Users/Laxgoalie1996/Desktop/SiriProxy/plugins/siriproxy-computer/lib/siriproxy-computer.rb:569: syntax error, unexpected $end, expecting keyword_end (SyntaxError)

new error

**Comment by laxman01** [comment]
Please someone help me

**Comment by Raggyx** [comment]
question == ask "Question" is a comparison but should be an allocation
and dont forget to complete every if statement with "end"
the if statements dont have the keyword 'then'
Its very difficult to set up a good program without having basic programming knowledge

**Comment by Deanmv** [comment]
for

```
listen_for /Quiz Me In (.*)/i do |userAction|
userAction.strip!
if userAction == "Bio" or userAction == "Biology" or userAction == "Science" then
question == ask "Question"
question.strip!
if question == "Answer" or question == "Show me the Answer" then
say "Answer"
request_completed
end
```

You would need either 

```
listen_for /Quiz Me In (.*)/i do |userAction|
userAction.strip!
if userAction == "Bio" or userAction == "Biology" or userAction == "Science" then
question = ask "Question"
question.strip!
end
if question == "Answer" or question == "Show me the Answer" then
say "Answer"
request_completed
end
end
```

**Comment by laxman01** [comment]
Thank you so much for all of your help
