### ISSUE TITLE
Running Siriproxy On Two Different IP Adresses 

### ISSUE THREAD

**Issue by laxman01** [plamoni/SiriProxy#414]
Quick question. I have two houses and i have my server set up on my MacBook Pro. right now i have  siriproxy configured to work at just one of the houses. is it possible to just change the ip address in DNSmasq.conf when switching houses to get it working at both houses?

**Comment by Deanmv** [comment]
Yeah you just have to change the IP in the DNSmasq.conf to your current MacBook Pro's IP.  Also don't forget to change the DNS server on the iPhone to include the MacBook Pro.

If you want to make life easier you could set up a static IP at both houses and assign your MacBook Pro to the same address and then you wouldn't need to change anything.

**Comment by laxman01** [comment]
Very good point and would i have to change ca.pem at all? How would i set up a static IP? is that like VPN?

thank you

**Comment by Deanmv** [comment]
Shouldn't have to, i've done it before and just changed the DNS on iPhone and the DNSmasq.conf on my Macbook Pro.  As for Static IP it can normally me done through your routers, just log in and then there will be an option somewhere to reserve the address for that device.

**Comment by laxman01** [comment]
thank you for all your help

**Comment by laxman01** [comment]
Im having a little trouble with the static ip. I logged my router by going to http://192.168.1.2 then went to advance routing 
![Screen Shot 2013-01-24 at 4 51 41 PM](https://f.cloud.github.com/assets/1238261/95456/3f94a7ec-6670-11e2-8283-a5367fb827e3.png)

**Comment by Deanmv** [comment]
Google Linksys E300 static IP and it will probably come up with something, never used it before with that router so can't be certain to be honest.

**Comment by laxman01** [comment]
ok i got the static ip set up but do you know anything about setting up this plugin "interstateone / siriproxy-hue" or using resty ?
sorry to keep bothering you

**Comment by Deanmv** [comment]
Nope not used it myself as don't have a Hue to use (although would love one).  But download the zip into your siriproxy/plugins folder and then add the correct stuff into the /.siriproxy/config.yml to set it up correctly.

**Comment by laxman01** [comment]
It is such a great product but i think it is too expensive. unfortunately the set up is a little more difficult then that.
https://github.com/interstateone/siriproxy-hue.git
it uses an app called "resty" wich im unfamiliarly with.
