### ISSUE TITLE
SiriProxy Crashing

### ISSUE THREAD

**Issue by andymcblane** [plamoni/SiriProxy#417]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x966a400 @signature=880, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x9669640>, @zip_stream=#Zlib::Deflate:0x96695dc, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x968a818 @manager=#<SiriProxy::PluginManager:0x9685750 @plugins=[...]>>]

This error I'm getting even when the Server is idle.. Nothing is connecting to it..

It is connected to a DHCP network and having DNS auto pushed to all devices.

I have changed /etc/resolve.conf to have
nameserver (DNS [Same that's being pushed by DHCP])
nameserver (SAME AS ABOVE)

Yet it still crashes..
What do I do?

**Comment by Deanmv** [comment]
That is not an error, you will need to post the whole output.

**Comment by andymcblane** [comment]
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x10c2600 @signature=30, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x10c24e0>, @zip_stream=#Zlib::Deflate:0x10c24c8, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x10cc398 @manager=#<SiriProxy::PluginManager:0x10cc7b8 @plugins=[...]>>, #<SiriProxy::Plugin::Cleverbot:0x10cbf90 @manager=#<SiriProxy::PluginManager:0x10cc7b8 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x10cbe58 @signature=31, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x10cbd80>, @zip_stream=#Zlib::Deflate:0x10cbd50, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x10cb5d0 @manager=#<SiriProxy::PluginManager:0x10cba38 @plugins=[...]>>, #<SiriProxy::Plugin::Cleverbot:0x10cb228 @manager=#<SiriProxy::PluginManager:0x10cba38 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x10c8d38 @signature=34, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x10c8a20>, @zip_stream=#Zlib::Deflate:0x10c89a8, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x10d1de0 @manager=#<SiriProxy::PluginManager:0x10d29c8 @plugins=[...]>>, #<SiriProxy::Plugin::Cleverbot:0x10d1018 @manager=#<SiriProxy::PluginManager:0x10d29c8 @plugins=[...]>>]
^C/usr/local/rvm/gems/ruby-1.9.3-p362/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run_machine': Interrupt
    from /usr/local/rvm/gems/ruby-1.9.3-p362/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in`run'
    from /usr/local/rvm/gems/ruby-1.9.3-p362/gems/siriproxy-0.3.2/lib/siriproxy.rb:16:in `initialize'
    from /usr/local/rvm/gems/ruby-1.9.3-p362/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:96:in`new'
    from /usr/local/rvm/gems/ruby-1.9.3-p362/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:96:in `start_server'
    from /usr/local/rvm/gems/ruby-1.9.3-p362/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:85:in`run_server'
    from /usr/local/rvm/gems/ruby-1.9.3-p362/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:37:in `initialize'
    from /usr/local/rvm/gems/ruby-1.9.3-p362/gems/siriproxy-0.3.2/bin/siriproxy:6:in`new'
    from /usr/local/rvm/gems/ruby-1.9.3-p362/gems/siriproxy-0.3.2/bin/siriproxy:6:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-1.9.3-p362/bin/siriproxy:23:in`load'
    from /usr/local/rvm/gems/ruby-1.9.3-p362/bin/siriproxy:23:in `<main>'
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.

root@raspberrypi:~# siriproxy server
Starting SiriProxy on port 443..
SiriProxy up and running.
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x1b80550 @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x1b80238>, @zip_stream=#Zlib::Deflate:0x1b80220, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x1fef6c0 @manager=#<SiriProxy::PluginManager:0x1b7fb78 @plugins=[...]>>, #<SiriProxy::Plugin::Cleverbot:0x28b2d48 @manager=#<SiriProxy::PluginManager:0x1b7fb78 @plugins=[...]>>]

**Comment by Deanmv** [comment]
Look like you closed it with ctrl+c and then started it again?  Don't actually see an error still.

**Comment by andymcblane** [comment]
I can be a derp sometimes..

Sorry

root@raspberrypi:~# siriproxy server
Starting SiriProxy on port 443..
SiriProxy up and running.
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x1b80550 @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x1b80238>, @zip_stream=#Zlib::Deflate:0x1b80220, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x1fef6c0 @manager=#<SiriProxy::PluginManager:0x1b7fb78 @plugins=[...]>>, #<SiriProxy::Plugin::Cleverbot:0x28b2d48 @manager=#<SiriProxy::PluginManager:0x1b7fb78 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x28b2c28 @signature=4, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x28b2b50>, @zip_stream=#Zlib::Deflate:0x28b2b38, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x28b2c58 @manager=#<SiriProxy::PluginManager:0x28b28f8 @plugins=[...]>>, #<SiriProxy::Plugin::Cleverbot:0x28812d8 @manager=#<SiriProxy::PluginManager:0x28b28f8 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x2882ca0 @signature=5, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x27acbf0>, @zip_stream=#Zlib::Deflate:0x27acc80, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x261d1d0 @manager=#<SiriProxy::PluginManager:0x23cfc28 @plugins=[...]>>, #<SiriProxy::Plugin::Cleverbot:0x2332110 @manager=#<SiriProxy::PluginManager:0x23cfc28 @plugins=[...]>>]

**Comment by Deanmv** [comment]
Same thing again, that bit isn't an error it's just the iPhone connecting/keeping the connection open.

**Comment by andymcblane** [comment]
I swear I posted something else..

Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x966a400 @signature=880, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x9669640>, @zip_stream=#Zlib::Deflate:0x96695dc, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x968a818 @manager=#<SiriProxy::PluginManager:0x9685750 @plugins=[...]>>]

There we go!

Edit.. Hm. It's changing it.

**Comment by andymcblane** [comment]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x966a400 @signature=880, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x9669640>, @zip_stream=#Zlib::Deflate:0x96695dc, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x968a818 @manager=#<SiriProxy::PluginManager:0x9685750 @plugins=[...]>>]

![image](https://f.cloud.github.com/assets/3156198/100975/c1fee742-6891-11e2-84d0-708f43df3fe4.jpg)

**Comment by jgsvuden** [comment]
I have the same problem, as i understand this is an iphone opening the connection, but after that, nothing else happens... no response no speechpackets, nothing....

Can anyone help on why nothing is being sent trough, because there is clearly some kind of connection...

**Comment by plamoni** [comment]
So are you seeing a bunch of these when you open the connection followed by a crash? If so, do a `siriproxy update --branch dev` and that should resolve the issue.
