### ISSUE TITLE
Eventmachine error

### ISSUE THREAD

**Issue by laxman01** [plamoni/SiriProxy#418]
server:SiriProxy laxgoalie1996$ rvmsudo siriproxy server

Warning: can not check `/etc/sudoers` for `secure_path`, falling back to call via `/usr/bin/env`, this breaks rules from `/etc/sudoers`. export rvmsudo_secure_path=1 to avoid the warning.

Starting SiriProxy on :443..

/Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:526:in `start_tcp_server': can't convert nil into String (TypeError)
    from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:526:in`start_server'
    from /Users/laxgoalie1996/Desktop/SiriProxy/lib/siriproxy.rb:19:in `block in initialize'
    from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in`call'
    from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run_machine'
    from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in`run'
    from /Users/laxgoalie1996/Desktop/SiriProxy/lib/siriproxy.rb:16:in `initialize'
    from /Users/laxgoalie1996/Desktop/SiriProxy/lib/siriproxy/command_line.rb:96:in`new'
    from /Users/laxgoalie1996/Desktop/SiriProxy/lib/siriproxy/command_line.rb:96:in `start_server'
    from /Users/laxgoalie1996/Desktop/SiriProxy/lib/siriproxy/command_line.rb:85:in`run_server'
    from /Users/laxgoalie1996/Desktop/SiriProxy/lib/siriproxy/command_line.rb:37:in `initialize'
    from /Users/laxgoalie1996/Desktop/SiriProxy/bin/siriproxy:6:in`new'
    from /Users/laxgoalie1996/Desktop/SiriProxy/bin/siriproxy:6:in `<top (required)>'
    from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p374@SiriProxy/bin/siriproxy:19:in`load'
    from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p374@SiriProxy/bin/siriproxy:19:in `<main>'
    from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p374@SiriProxy/bin/ruby_noexec_wrapper:14:in`eval'
    from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p374@SiriProxy/bin/ruby_noexec_wrapper:14:in `<main>'
server:SiriProxy laxgoalie1996$

**Comment by Deanmv** [comment]
Not sure on that one but first run `rvmsudo_secure_path=1` to get rid of the top error if not then re-install event machine?

**Comment by laxman01** [comment]
ok that got rid of that error but i still have problem with eventmachine

**Comment by laxman01** [comment]
That was the whole output i copied everything from my terminal

**Comment by Deanmv** [comment]
Not sure, only thing I can recommend is to re-install event machine with `gem install eventmachine -v 1.0.0`

**Comment by laxman01** [comment]
Still the same error. i had the server running perfectly then i reinstalled ruby and started getting theses errors. not sure if that helps

**Comment by Deanmv** [comment]
No idea then i'm afraid.

**Comment by laxman01** [comment]
That is not reinsuring haha.

**Comment by Deanmv** [comment]
It's not all that bad. I dabble my way through most of this so i'm no where near knowing what errors are just by looking at them, hopefully someone else can chime in

**Comment by laxman01** [comment]
Right now im just praying to one day check my email and see "plamoni commented on your issue"

**Comment by laxman01** [comment]
@plamoni 

now im getting this error

Starting SiriProxy on 0.0.0.0:443..
/Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:526:in start_tcp_server': no acceptor (port is in use or requires root privileges) (RuntimeError)
from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:526:instart_server'
from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy.rb:19:in block in initialize'
from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:incall'
from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in run_machine'
from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:inrun'
from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy.rb:16:in initialize'
from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:96:innew'
from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:96:in start_server'
from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:85:inrun_server'
from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:37:in initialize'
from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/bin/siriproxy:6:innew'
from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/bin/siriproxy:6:in <top (required)>'
from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p374@SiriProxy/bin/siriproxy:23:inload'
from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p374@SiriProxy/bin/siriproxy:23:in `'
server:SiriProxy laxgoalie1996$

**Comment by TonyLianLong** [comment]
Look,your ip can't be 0.0.0.0
And your siriproxy says it is 0.0.0.0.
It says
Starting SiriProxy on 0.0.0.0:443..

**Comment by laxman01** [comment]
Yes, I fixed that but now I'm still getting the error from before

**Comment by laxman01** [comment]
@TonyLianLong  
@chendo 
@courtenay 
@netpro2k 
@plamoni 

Please help me

server:SiriProxy laxgoalie1996$ rvmsudo siriproxy server

Warning: can not check /etc/sudoers for secure_path, falling back to call via /usr/bin/env, this breaks rules from /etc/sudoers. export rvmsudo_secure_path=1 to avoid the warning.

Starting SiriProxy on :443..

/Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:526:in start_tcp_server': can't convert nil into String (TypeError)
from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:526:instart_server'
from /Users/laxgoalie1996/Desktop/SiriProxy/lib/siriproxy.rb:19:in block in initialize'
from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:incall'
from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in run_machine'
from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:inrun'
from /Users/laxgoalie1996/Desktop/SiriProxy/lib/siriproxy.rb:16:in initialize'
from /Users/laxgoalie1996/Desktop/SiriProxy/lib/siriproxy/command_line.rb:96:innew'
from /Users/laxgoalie1996/Desktop/SiriProxy/lib/siriproxy/command_line.rb:96:in start_server'
from /Users/laxgoalie1996/Desktop/SiriProxy/lib/siriproxy/command_line.rb:85:inrun_server'
from /Users/laxgoalie1996/Desktop/SiriProxy/lib/siriproxy/command_line.rb:37:in initialize'
from /Users/laxgoalie1996/Desktop/SiriProxy/bin/siriproxy:6:innew'
from /Users/laxgoalie1996/Desktop/SiriProxy/bin/siriproxy:6:in <top (required)>'
from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p374@SiriProxy/bin/siriproxy:19:inload'
from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p374@SiriProxy/bin/siriproxy:19:in <main>'
from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p374@SiriProxy/bin/ruby_noexec_wrapper:14:ineval'
from /Users/laxgoalie1996/.rvm/gems/ruby-1.9.3-p374@SiriProxy/bin/ruby_noexec_wrapper:14:in `'
server:SiriProxy laxgoalie1996$

**Comment by mpdifran** [comment]
I got this error when I ran siriproxy update. It was working fine before. Something must have changed in a recent commit to start causing this issue. Why is this issue now closed?

**Comment by laxman01** [comment]
I Closed it because I figured out what I had to do. I could help you if you are having trouble still

**Comment by mpdifran** [comment]
Sure that'd be great. I'm stuck at the crash when trying to convert nil into a string.

**Comment by laxman01** [comment]
And do you have DNSMASQ set up correctly with ca.pem installed on your phone?

**Comment by mpdifran** [comment]
I've got dnsmasq set up on my ubuntu machine, the one that's running siriProxy. The ca.pem is on my phone. I'm noticing that my local ip is not listed in front of the port, it looks like this: "Starting SiriProxy on :443.." Not sure if that's expected behaviour or not.

**Comment by laxman01** [comment]
Okay run 
"siriproxy update"
Then edit config.yml in your .siriproxy directory
The first line should be something like "listen on 0.0.0.0"
Change the "0.0.0.0" to your IP Address
Then restart SiriProxy

**Comment by mpdifran** [comment]
This is the config.yml after the update. It's the one named config.example.yml in the Siriproxy root folder, and mine in .siriproxy looks the same.

port: 443
log_level: 1
plugins:
    # NOTE: run bundle after changing plugin configurations to update required gems

```
- name: 'Example'
  path: './plugins/siriproxy-example'

# - name: 'Thermostat'
#   git: 'git://github.com/plamoni/SiriProxy-Thermostat.git'
#   host: '192.168.2.71'

# - name: 'Twitter'
#   path: './plugins/siriproxy-twitter' # path works just like specifing in gemfile
#   consumer_key: "YOUR_KEY"
#   consumer_secret: "YOUR_SECRET"
#   oauth_token: "YOUR_TOKEN"
#   oauth_token_secret: "YOUR_TOKEN_SECRET"

# Note: Eliza should not be run with other plugins
# - name: 'Eliza'
#   path: './plugins/siriproxy-eliza' # path works just like specifing in gemfile

# Below are not actual plugins, just further example of config options

# - SimplePlugin # simple syntax for plugins that are in rubygems and have no config

# - name: 'AnotherPlugin'
#   git: 'git://github.com/netpro2k/SiriProxy-AnotherPlugin.git' # git works just like specifying$
```

**Comment by laxman01** [comment]
Ok copy and paste the contents of this file to both config files
https://github.com/plamoni/SiriProxy/blob/master/config.example.yml
Then do the steps I said above

**Comment by laxman01** [comment]
For some reason the update did not grab the latest code for you

**Comment by mpdifran** [comment]
Looks like it's running now. I guess that listen line was added recently? I don't think I've updated in a while

**Comment by mpdifran** [comment]
Looks like only some files were updated in the pull. Odd.

**Comment by laxman01** [comment]
Yes it's fairly new, about 2 or 3 weeks

**Comment by laxman01** [comment]
Weird but glad to hear you got it working

**Comment by mpdifran** [comment]
Thanks for your help. :)

**Comment by laxman01** [comment]
No problem
