### ISSUE TITLE
Cant ping to guzzoni.apple.com (It's real IP)

### ISSUE THREAD

**Issue by TonyLianLong** [plamoni/SiriProxy#419]
ping guzzoni.apple.com
Pinging rd13p02sa.guzzoni-apple.com.akadns.net [17.135.65.4] has 32 bytes' data:
Time out
Time out

Like this,this IP is guzzoni's real IP.
So my SiriProxy can't work.But my iPhone can connect to siriproxy's server.
Maby Apple has a new server.
Who can help me?

**Comment by Deanmv** [comment]
There was a post of it moving in 6.1 but that is currently under NDA and even though I just tried to ping it and got the same reply, I used siri proxy with a plugin i'm developing and everything worked fine.

**Comment by plamoni** [comment]
I'm pretty sure guzzoni does not respond to pings.

You can test if it's active by doing `telnet guzzoni.apple.com 443`

It will boot you as soon as you send any data that it doesn't expect, but it will connect.
