### ISSUE TITLE
Crash after adding plugins

### ISSUE THREAD

**Issue by venom420x** [plamoni/SiriProxy#421]
I add new plugins and i edit my conf.yml file and when i start the server it crashes. here is my terminal error log when i try to use siriproxy bundle 

venoms-iMac:~ venom$ rvmsudo siriproxy bundle
Warning: can not check `/etc/sudoers` for `secure_path`, falling back to call via `/usr/bin/env`, this breaks rules from `/etc/sudoers`. export rvmsudo_secure_path=1 to avoid the warning.Password:
/Users/venom/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/1.9.1/psych.rb:203:in `parse': (/Users/venom/.siriproxy/config.yml): did not find expected '-' indicator while parsing a block collection at line 7 column 5 (Psych::SyntaxError)
    from /Users/venom/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/1.9.1/psych.rb:203:in`parse_stream'
    from /Users/venom/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/1.9.1/psych.rb:151:in `parse'
    from /Users/venom/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/1.9.1/psych.rb:127:in`load'
    from /Users/venom/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/1.9.1/psych.rb:297:in `block in load_file'
    from /Users/venom/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/1.9.1/psych.rb:297:in`open'
    from /Users/venom/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/1.9.1/psych.rb:297:in `load_file'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:143:in`parse_options'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:33:in `initialize'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/siriproxy-0.3.2/bin/siriproxy:6:in`new'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/siriproxy-0.3.2/bin/siriproxy:6:in `<top (required)>'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/bin/siriproxy:19:in`load'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/bin/siriproxy:19:in `<main>'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/bin/ruby_noexec_wrapper:14:in`eval'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/bin/ruby_noexec_wrapper:14:in `<main>' 

and here is my conf.yml

listen: 192.168.1.134
port: 443
log_level: 1
plugins:
    # NOTE: run bundle after changing plugin configurations to update required gems

```
- name: 'Example'
  path: './plugins/siriproxy-example'

 - name: 'WhereAmI'
  git: 'https://github.com/Swimo/SiriProxy---WhereAmI.git'


# - name: 'Thermostat'
#   git: 'git://github.com/plamoni/SiriProxy-Thermostat.git'
#   host: '192.168.2.71' 

# - name: 'Twitter'
#   path: './plugins/siriproxy-twitter' # path works just like specifing in gemfile 
#   consumer_key: "YOUR_KEY" 
#   consumer_secret: "YOUR_SECRET"
#   oauth_token: "YOUR_TOKEN" 
#   oauth_token_secret: "YOUR_TOKEN_SECRET"

# Note: Eliza should not be run with other plugins
# - name: 'Eliza'
#   path: './plugins/siriproxy-eliza' # path works just like specifing in gemfile 

# Below are not actual plugins, just further example of config options

# - SimplePlugin # simple syntax for plugins that are in rubygems and have no config 

# - name: 'AnotherPlugin'
#   git: 'git://github.com/netpro2k/SiriProxy-AnotherPlugin.git' # git works just like specifying in Gemfile
```

**Comment by venom420x** [comment]
Side Note. If I remove the plugin i added and just use the example plugin everything works fine.

**Comment by laxman01** [comment]
ok give me a second why i review the output

**Comment by laxman01** [comment]
This probably isn't the reason but your spacing is messed up on this line "- name: 'WhereAmI'"
so space "-name" backwards so it lines up with the first one..
like i said probably not the reason but its worth a shot

**Comment by laxman01** [comment]
if that does not fix it tell me cause i have a couple other ideas

**Comment by laxman01** [comment]
any luck?

**Comment by venom420x** [comment]
Damn, your good. That was exactly the problem. I didn't even notice the improper syntax. One last question. After i run the proxy in terminal is there a way to quit or restart it in the same window. Normally i would just close that terminal and open a new one. But i prefer some type of keyboard shortcut. xD. Thanks Again!

**Comment by laxman01** [comment]
control c 
i beleive

**Comment by laxman01** [comment]
i also created a gui for siriproxy wich makes it easy to start and stop it
![Screen Shot 2013-01-28 at 8 24 52 PM](https://f.cloud.github.com/assets/1238261/105477/b04675c0-69b2-11e2-8b43-40b6b9246932.png)

**Comment by venom420x** [comment]
Really? That Seems Like A Great Idea. Mind pming or emailing me the dmg?

**Comment by laxman01** [comment]
yeah i could do that but the only thing this is that it is configured for me like we probably have files in different locations and different names..so if you wanted to send me the list of commands that use to start up your server then i could configure it for you

**Comment by venom420x** [comment]
such as this?

venoms-iMac:~ venom$ rvmsudo siriproxy server
Warning: can not check `/etc/sudoers` for `secure_path`, falling back to call via `/usr/bin/env`, this breaks rules from `/etc/sudoers`. export rvmsudo_secure_path=1 to avoid the warning.Password:
Starting SiriProxy on 192.168.1.134:443..
SiriProxy up and running.

**Comment by venom420x** [comment]
Thanks tons in advance

**Comment by laxman01** [comment]
Oh no problem. But what I'm looking for is what you would type into a freshly
Opened terminal what commands would you type in(in order) to get the server started.

**Comment by venom420x** [comment]
thats exactly what i type in a new terminal window

**Comment by venom420x** [comment]
http://img707.imageshack.us/img707/4919/screenshot20130128at957.png

**Comment by laxman01** [comment]
Oh wow your lucky then, for some reason whenever I start up my server I have to type in like 5 commands.
And what is the path of your SiriProxy folder

**Comment by venom420x** [comment]
The Regular SiriProxy Folder Or The ./SiriProxy folder?

**Comment by laxman01** [comment]
Regular

**Comment by venom420x** [comment]
i believe if you add this in terminal it'll bind siriproxy to a single command. not positive on that though

sudo ln -s ~/.siriproxy /root/.siriproxy

**Comment by venom420x** [comment]
/Users/venom/Desktop/Developer/SiriProxy

**Comment by laxman01** [comment]
Ok thanks one sec

**Comment by venom420x** [comment]
No no no, Thank You. This Will Be Somewhat of a time server. i dislike typing in terminal i always mess something up along the line.

**Comment by laxman01** [comment]
crap sorry i fell asleep... i will get you everything tommorow i got to go to bed

**Comment by venom420x** [comment]
Take your time brother, im in no rush. still configuring apps anyway. Talk to you tomorrow mate.

**Comment by laxman01** [comment]
ok so download this file 
http://www.mediafire.com/?1d6vlkndwn086u6

 then take all three of the .sh files and drag those into your siriproxy folder then you can drag the app wherever you would like. I added another configuration where it simulates the process where you copy the config.yml folder in your siriproxy folder into your .siriproxy folder. as long as you have a config.yml in your siriproxy folder everything should go well. also dont change the names of the .sh files. i did not test this because its configured for your account but if it does not work or you have any questions feel free to ask.

**Comment by venom420x** [comment]
I'm sure it would of worked great. But apparently it requires osx 10.8 im running 10.7.5 Thanks for the great effort though man. I Appreciate it.

**Comment by venom420x** [comment]
I updated to 10.8 a few weeks back but im only running 2gb ram so it was a bit laggy :/

**Comment by laxman01** [comment]
Ok just let me know if you have any other questions

**Comment by venom420x** [comment]
Thanks man. You've been a great help

**Comment by venom420x** [comment]
Do you know of a way to run 10.8 apps on 10.7?

**Comment by laxman01** [comment]
Yes I could just change the build on the app to whatever your running

**Comment by venom420x** [comment]
Im running 10.7.5 mate. Thanks man very kind. I have xCode. and i have a
urge to learn new things. i thought maybe i could open the .app in xcode
some how and just recompile it for my version but i dont think thats
possible. Still fairly new to all this Apple Stuff. Thanks again

On Wed, Jan 30, 2013 at 10:00 PM, laxman01 notifications@github.com wrote:

> Yes I could just change the build on the app to whatever your running
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/plamoni/SiriProxy/issues/421#issuecomment-12925468.

## 

<i>Matt</i>

**Comment by laxman01** [comment]
Im fairly new to xcode as well this was my first real all i made and That could be done if I sent you the Xcode project

**Comment by venom420x** [comment]
Ah That Is True. I've mostly been learning for iOS development.

**Comment by laxman01** [comment]
That's cool, check out my new post I made called SiriProxyGUI, I added some new features.

**Comment by venom420x** [comment]
Maybe you could answer this for me, Is their a way to test my own apps on
my own phone without the simulator or a apple dev account
?

On Wed, Jan 30, 2013 at 10:16 PM, laxman01 notifications@github.com wrote:

> Im fairly new to xcode as well this was my first real all i made and That
> could be done if I sent you the Xcode project
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/plamoni/SiriProxy/issues/421#issuecomment-12925844.

## 

<i>Matt</i>

**Comment by laxman01** [comment]
I'm really not sure, I don't think you can unless you jailbreak or if you use the simulator

**Comment by venom420x** [comment]
now getting this error running siriproxy

venoms-iMac:SiriProxy venom$ rvmsudo siriproxy server
Warning: can not check `/etc/sudoers` for `secure_path`, falling back to call via `/usr/bin/env`, this breaks rules from `/etc/sudoers`. export rvmsudo_secure_path=1 to avoid the warning.git://github.com/robbederks/SiriProxy-ChuckNorris.git (at master) is not checked out. Please run `bundle install`

i run bundle install and everything says its good.

**Comment by laxman01** [comment]
Ok so its something about that plugin so run bundle install from inside that directory thenCan you show me the output of it

**Comment by venom420x** [comment]
I figured it out i have the config.yml in my siriproxy folder diffrent then
the one in .siriproxy so i copied it over re ran bundle and then it worked.

On Wed, Jan 30, 2013 at 10:50 PM, laxman01 notifications@github.com wrote:

> Ok so its something about that plugin so run bundle install from inside
> that directory thenCan you show me the output of it
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/plamoni/SiriProxy/issues/421#issuecomment-12926588.

## 

<i>Matt</i>

**Comment by laxman01** [comment]
Good to here, that's funny cause that's one of the new features I added on my app it will automatically copy your config.yml over to the .siriproxy directory

**Comment by venom420x** [comment]
thats good i upgraded to mountain lion to use the gui app but in terminal i cant even start siriproxy

venoms-iMac:SiriProxy venom$ rvmsudo siriproxy server
Warning: can not check `/etc/sudoers` for `secure_path`, falling back to call via `/usr/bin/env`, this breaks rules from `/etc/sudoers`. export rvmsudo_secure_path=1 to avoid the warning./Users/venom/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/1.9.1/net/https.rb:22:in `require': cannot load such file -- openssl (LoadError)
    from /Users/venom/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/1.9.1/net/https.rb:22:in`<top (required)>'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/geocoder-1.1.6/lib/geocoder/lookups/base.rb:2:in `require'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/geocoder-1.1.6/lib/geocoder/lookups/base.rb:2:in`<top (required)>'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/geocoder-1.1.6/lib/geocoder/lookups/google.rb:1:in `require'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/geocoder-1.1.6/lib/geocoder/lookups/google.rb:1:in`<top (required)>'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/geocoder-1.1.6/lib/geocoder/lookup.rb:80:in `require'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/geocoder-1.1.6/lib/geocoder/lookup.rb:80:in`block in <top (required)>'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/geocoder-1.1.6/lib/geocoder/lookup.rb:79:in `each'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/geocoder-1.1.6/lib/geocoder/lookup.rb:79:in`<top (required)>'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/geocoder-1.1.6/lib/geocoder.rb:7:in `require'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/geocoder-1.1.6/lib/geocoder.rb:7:in`<top (required)>'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/cora-0.0.4/lib/cora/location.rb:1:in `require'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/cora-0.0.4/lib/cora/location.rb:1:in`<top (required)>'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/cora-0.0.4/lib/cora.rb:3:in `require'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/cora-0.0.4/lib/cora.rb:3:in`<top (required)>'
    from /Users/venom/Desktop/Developer/SiriProxy/lib/siriproxy/plugin.rb:1:in `require'
    from /Users/venom/Desktop/Developer/SiriProxy/lib/siriproxy/plugin.rb:1:in`<top (required)>'
    from /Users/venom/Desktop/Developer/SiriProxy/lib/siriproxy/command_line.rb:188:in `require'
    from /Users/venom/Desktop/Developer/SiriProxy/lib/siriproxy/command_line.rb:188:in`load_code'
    from /Users/venom/Desktop/Developer/SiriProxy/lib/siriproxy/command_line.rb:84:in `run_server'
    from /Users/venom/Desktop/Developer/SiriProxy/lib/siriproxy/command_line.rb:37:in`initialize'
    from /Users/venom/Desktop/Developer/SiriProxy/bin/siriproxy:6:in `new'
    from /Users/venom/Desktop/Developer/SiriProxy/bin/siriproxy:6:in`<top (required)>'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374@SiriProxy/bin/siriproxy:19:in `load'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374@SiriProxy/bin/siriproxy:19:in`<main>'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374@SiriProxy/bin/ruby_noexec_wrapper:14:in `eval'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374@SiriProxy/bin/ruby_noexec_wrapper:14:in`<main>'

ive tried reinstall ruby and command line tools to no avail. :/

**Comment by laxman01** [comment]
where you using the GUI to start it or manually

**Comment by venom420x** [comment]
manually. This things been getting me frustrated all day. im getting this error

/Users/venom/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/1.9.1/net/https.rb:22:in `require': cannot load such file -- openssl (LoadError)
    from /Users/venom/.rvm/rubies/ruby-1.9.3-p374/lib/ruby/1.9.1/net/https.rb:22:in`<top (required)>'

so i tried reinstalling openssl also. i should of just stuck with Lion.

**Comment by laxman01** [comment]
Reinstalling OpenSSL, did that work or still the same erorr

**Comment by laxman01** [comment]
have you tried "siriproxy update"

**Comment by venom420x** [comment]
Yea. and it says it install fine. :/ im going to remove ruby and reinstall
with gcc see if that helps

On Thu, Jan 31, 2013 at 7:27 PM, laxman01 notifications@github.com wrote:

> have you tried "siriproxy update"
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/plamoni/SiriProxy/issues/421#issuecomment-12974462.

## 

<i>Matt</i>

**Comment by laxman01** [comment]
good idea. let me know how that works

**Comment by venom420x** [comment]
worked to no avail getting this error when reinstalling now

venoms-iMac:~ venom$ sudo rvm reinstall 1.9.3 --with-gcc=clang
Password:
Removing /Users/venom/.rvm/src/ruby-1.9.3-p374...
Removing /Users/venom/.rvm/rubies/ruby-1.9.3-p374...
Fetching yaml-0.1.4.tar.gz to /Users/venom/.rvm/archives
Extracting yaml to /Users/venom/.rvm/src/yaml-0.1.4
Configuring yaml in /Users/venom/.rvm/src/yaml-0.1.4.
Compiling yaml in /Users/venom/.rvm/src/yaml-0.1.4.
Installing yaml to /Users/venom/.rvm/usr
Installing Ruby from source to: /Users/venom/.rvm/rubies/ruby-1.9.3-p374,
this may take a while depending on your cpu(s)...
ruby-1.9.3-p374 - #downloading ruby-1.9.3-p374, this may take a while
depending on your connection...
ruby-1.9.3-p374 - #extracting ruby-1.9.3-p374 to
/Users/venom/.rvm/src/ruby-1.9.3-p374
ruby-1.9.3-p374 - #extracted to /Users/venom/.rvm/src/ruby-1.9.3-p374
ruby-1.9.3-p374 - #configuring
ruby-1.9.3-p374 - #compiling
Error running 'make', please read
/Users/venom/.rvm/log/ruby-1.9.3-p374/make.log
There has been an error while running make. Halting the installation.

On Thu, Jan 31, 2013 at 7:33 PM, laxman01 notifications@github.com wrote:

> good idea. let me know how that works
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/plamoni/SiriProxy/issues/421#issuecomment-12974653.

## 

<i>Matt</i>

**Comment by venom420x** [comment]
my make log

[2013-01-31 19:40:47] make
CC = clang
LD = ld
LDSHARED = clang -dynamic -bundle
CFLAGS = -O3 -ggdb -Wall -Wextra -Wno-unused-parameter -Wno-parentheses
-Wno-long-long -Wno-missing-field-initializers -Werror=pointer-arith
-Werror=write-strings -Werror=declaration-after-statement
-Werror=shorten-64-to-32 -Werror=implicit-function-declaration  -pipe
XCFLAGS = -include ruby/config.h -include ruby/missing.h
-fvisibility=hidden -DRUBY_EXPORT
CPPFLAGS = -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE
-I/Users/venom/.rvm/usr/include -I. -I.ext/include/x86_64-darwin12.2.0
-I./include -I.
DLDFLAGS = -Wl,-undefined,dynamic_lookup -Wl,-multiply_defined,suppress
-Wl,-flat_namespace
SOLIBS =
compiling main.c
compiling dmydln.c
compiling dmyencoding.c
compiling version.c
compiling dmyversion.c
compiling miniprelude.c
compiling array.c
compiling bignum.c
bignum.c:2732:26: warning: while loop has empty body [-Wempty-body]
        while (--ny && !zds[ny]); ++ny;
                                ^
bignum.c:2732:26: note: put the semicolon on a separate line to silence
this warning
1 warning generated.
compiling class.c
compiling compar.c
compiling complex.c
compiling dir.c
compiling dln_find.c
compiling enum.c
compiling enumerator.c
compiling error.c
compiling eval.c
compiling load.c
compiling proc.c
compiling file.c
compiling gc.c
gc.c:3060:1: warning: unused function 'chain_finalized_object'
[-Wunused-function]
chain_finalized_object(st_data_t key, st_data_t val, st_data_t arg)
^
1 warning generated.
compiling hash.c
compiling inits.c
compiling io.c
compiling marshal.c
compiling math.c
compiling node.c
compiling numeric.c
compiling object.c
compiling pack.c
compiling parse.c
compiling process.c
compiling random.c
compiling range.c
compiling rational.c
compiling re.c
compiling regcomp.c
compiling regenc.c
compiling regerror.c
compiling regexec.c
compiling regparse.c
regparse.c:582:15: error: implicit conversion loses integer precision:
'st_index_t' (aka 'unsigned long') to 'int' [-Werror,-Wshorten-64-to-32]
    return t->num_entries;
    ~~~~~~ ~~~^~~~~~~~~~~
1 error generated.
make: **\* [regparse.o] Error 1

On Thu, Jan 31, 2013 at 7:42 PM, Matt shorten dwelement@gmail.com wrote:

> worked to no avail getting this error when reinstalling now
> 
> venoms-iMac:~ venom$ sudo rvm reinstall 1.9.3 --with-gcc=clang
> Password:
> Removing /Users/venom/.rvm/src/ruby-1.9.3-p374...
> Removing /Users/venom/.rvm/rubies/ruby-1.9.3-p374...
> Fetching yaml-0.1.4.tar.gz to /Users/venom/.rvm/archives
> Extracting yaml to /Users/venom/.rvm/src/yaml-0.1.4
> Configuring yaml in /Users/venom/.rvm/src/yaml-0.1.4.
> Compiling yaml in /Users/venom/.rvm/src/yaml-0.1.4.
> Installing yaml to /Users/venom/.rvm/usr
> Installing Ruby from source to: /Users/venom/.rvm/rubies/ruby-1.9.3-p374,
> this may take a while depending on your cpu(s)...
> ruby-1.9.3-p374 - #downloading ruby-1.9.3-p374, this may take a while
> depending on your connection...
> ruby-1.9.3-p374 - #extracting ruby-1.9.3-p374 to
> /Users/venom/.rvm/src/ruby-1.9.3-p374
> ruby-1.9.3-p374 - #extracted to /Users/venom/.rvm/src/ruby-1.9.3-p374
> ruby-1.9.3-p374 - #configuring
> ruby-1.9.3-p374 - #compiling
> Error running 'make', please read
> /Users/venom/.rvm/log/ruby-1.9.3-p374/make.log
> There has been an error while running make. Halting the installation.
> 
> On Thu, Jan 31, 2013 at 7:33 PM, laxman01 notifications@github.comwrote:
> 
> > good idea. let me know how that works
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/plamoni/SiriProxy/issues/421#issuecomment-12974653.
> 
> ## 
> 
> <i>Matt</i>

## 

<i>Matt</i>

**Comment by laxman01** [comment]
have tried just "rvm install 1.9.3"

**Comment by venom420x** [comment]
i originally did that and it said 1.9.3 already install try rvm reinstall 1.9.3

**Comment by laxman01** [comment]
did you reinstall it ?

**Comment by laxman01** [comment]
and did you use macports to reinstall openssl ?

**Comment by venom420x** [comment]
i tried reinstalling but i got the error i posted above. telling me error running make. should i reinstall openssl before or after ruby or is the irrelevant?

**Comment by laxman01** [comment]
i would try sudo port install openssl

**Comment by laxman01** [comment]
wait run "openssl version"
tell me the response

**Comment by venom420x** [comment]
venoms-iMac:SiriProxy venom$ openssl version
OpenSSL 1.0.1c 10 May 2012

**Comment by venom420x** [comment]
when i update siriproxy everything says its fine like so

enoms-iMac:SiriProxy venom$ rvmsudo siriproxy update
Warning: can not check `/etc/sudoers` for `secure_path`, falling back to call via `/usr/bin/env`, this breaks rules from `/etc/sudoers`. export rvmsudo_secure_path=1 to avoid the warning.=== Installing latest code from git://github.com/plamoni/SiriProxy.git [master] ===
remote: Counting objects: 727, done.
remote: Compressing objects: 100% (287/287), done.
remote: Total 727 (delta 416), reused 663 (delta 373)
Receiving objects: 100% (727/727), 132.14 KiB, done.
Resolving deltas: 100% (416/416), done.
Cloning into '/tmp/SiriProxy.install.5214'...
=== Performing Rake Install ===
siriproxy 0.3.2 built to pkg/siriproxy-0.3.2.gem
siriproxy (0.3.2) installed
=== Bundling ===
Using rake (10.0.3) 
Using CFPropertyList (2.2.0) 
Using geocoder (1.1.6) 
Using cora (0.0.4) 
Using eventmachine (1.0.0) 
Using uuidtools (2.1.3) 
Using siriproxy (0.3.2) 
Using siriproxy-example (0.0.1) 
Using bundler (1.2.3) 
Your bundle is complete! Use `bundle show [gemname]` to see where a bundled gem is installed.
=== Cleaning Up ===
=== SUCCESS ===

but running rvmsudo siriproxy server just gives me that openssl error

**Comment by venom420x** [comment]
I've even tried this http://www.dinduks.com/rails-cannot-load-such-file-openssl/

**Comment by venom420x** [comment]
I'm thinking when i updated to mountain lion. Something went wrong. Maybe symlinks changed or directories of some sort

**Comment by laxman01** [comment]
You ran all those steps and still get the error

**Comment by venom420x** [comment]
I ran all those steps and then restarted the machine just for good measure and still get that error.
im stumped

**Comment by laxman01** [comment]
So still OpenSSL has not been reinstalled

**Comment by venom420x** [comment]
ok so i removed everything ruby. rvm. openssl. homebrew and gcc reinstalled everything. ran the steps from the siriproxy tutorial and now i get this error

venoms-iMac:SiriProxy venom$ rvmsudo siriproxy server
Warning: can not check `/etc/sudoers` for `secure_path`, falling back to call via `/usr/bin/env`, this breaks rules from `/etc/sudoers`. export rvmsudo_secure_path=1 to avoid the warning.Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
/Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/eventmachine-1.0.0/lib/eventmachine.rb:8:in `require': cannot load such file -- rubyeventmachine (LoadError)
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/eventmachine-1.0.0/lib/eventmachine.rb:8:in`<top (required)>'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/siriproxy-0.3.2/lib/siriproxy.rb:1:in `require'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/siriproxy-0.3.2/lib/siriproxy.rb:1:in`<top (required)>'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:183:in `require'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:183:in`load_code'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:84:in `run_server'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:37:in`initialize'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/siriproxy-0.3.2/bin/siriproxy:6:in `new'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/siriproxy-0.3.2/bin/siriproxy:6:in`<top (required)>'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/bin/siriproxy:23:in `load'
    from /Users/venom/.rvm/gems/ruby-1.9.3-p374/bin/siriproxy:23:in`<main>'

**Comment by venom420x** [comment]
running sudo gem install eventmachine --pre returned this

venoms-iMac:SiriProxy venom$ sudo gem install eventmachine --pre
Fetching: eventmachine-1.0.0.rc.4.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing eventmachine:
    ERROR: Failed to build gem native extension.

```
    /Users/venom/.rvm/rubies/ruby-1.9.3-p374/bin/ruby extconf.rb
```

checking for main() in -lssl... yes
checking for main() in -lcrypto... yes
checking for openssl/ssl.h... yes
checking for openssl/err.h... yes
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... yes
checking for inotify_init() in sys/inotify.h... no
checking for __NR_inotify_init in sys/syscall.h... no
checking for writev() in sys/uio.h... yes
checking for rb_thread_check_ints()... yes
checking for rb_time_new()... yes
checking for sys/event.h... yes
checking for sys/queue.h... yes
creating Makefile

make
compiling binder.cpp
g++: error: unrecognized command line option '-Wshorten-64-to-32'
make: **\* [binder.o] Error 1

Gem files will remain installed in /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/eventmachine-1.0.0.rc.4 for inspection.
Results logged to /Users/venom/.rvm/gems/ruby-1.9.3-p374/gems/eventmachine-1.0.0.rc.4/ext/gem_make.out

**Comment by laxman01** [comment]
I have no idea, I would make a new issue and see if anyone else know
