### ISSUE TITLE
iPhone can't connect to SiriProxy

### ISSUE THREAD

**Issue by jgsvuden** [plamoni/SiriProxy#423]
I have the following problem running SiriProxy, the server starts and up till that point everything is alright, but when i try to run Siri on my iPhone the following output gets generated and Siri does not work:

Starting SiriProxy on 192.168.192.8:443..
SiriProxy up and running.
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x18000a8 @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x17ffef8>, @zip_stream=#Zlib::Deflate:0x17ffee0, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x1ed6b90 @manager=#<SiriProxy::PluginManager:0x17ffa60 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x1ed6aa0 @signature=4, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x1ed69c8>, @zip_stream=#Zlib::Deflate:0x1ed69b0, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x1ed63c8 @manager=#<SiriProxy::PluginManager:0x1ed6740 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x1ed62c0 @signature=5, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x1ef99c0>, @zip_stream=#Zlib::Deflate:0x1ef99a8, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x1ef9390 @manager=#<SiriProxy::PluginManager:0x1ef9708 @plugins=[...]>>]

...

And this goes on and on with the same message.

Can somebody please help me and tell me what is going wrong?
BTW, this has been tested with 2 iPhones yielding the same result

**Comment by Deanmv** [comment]
See the "Using Siri causes a whole bunch of the following messages, followed by SiriProxy crashing!" section on the readme.

**Comment by plamoni** [comment]
Run `siriproxy update --branch dev` -- should resolve this issue.
