### ISSUE TITLE
SiriProxyGUI

### ISSUE THREAD

**Issue by laxman01** [plamoni/SiriProxy#424]
http://siriproxygui.blogspot.com/?view=magazine

**Comment by venom420x** [comment]
This Is A Great Idea. Automating The Process For People Who Dislike The Terminal. Great Idea, And Convient.

**Comment by laxman01** [comment]
Thank you I'm glad you appreciate it.

**Comment by laxman01** [comment]
tutorial here

http://siriproxygui.blogspot.com/?view=magazine

**Comment by Appendit** [comment]
would be cool to make a setup application for users who don't have so much knowledge of those command line commands

**Comment by laxman01** [comment]
That was going to be my next step. Thank you for the idea though.
