### ISSUE TITLE
Push form proxy to Siri

### ISSUE THREAD

**Issue by davidgeppelt** [plamoni/SiriProxy#425]
I have the Lockitron Deadbolt, and I am using it to experiment in preparation for the release of the new Lockitron. I am trying to send notifications to Siri through my proxy so that she can say "the kids are home" (or whatever) when another user unlocks the lock with their phone or key. Has anyone had any luck with, pushing information to Siri from the proxy (basically a push notification), or is it even possible?

Thanks!

**Comment by laxman01** [comment]
That is a really cool idea, I have not personally heard of anyone doing this. If I come across anything I will  let you know.

**Comment by plamoni** [comment]
It's not _really_ possible. The Siri process works like HTTP, where it
sends a request and expects responses. Also, the Siri process only lives
for a short time after the interface goes away. So pushing something when
the person isn't using Siri isn't going to happen.

HOWEVER, it's possible you might be able to hijack a use of Siri to provide
a message. So, for instance, you ask Siri how the Cubs did last night and
it tells you, then says, "by the way, you have an unread email from your
wife." Might be better than nothing.

/shrug

-Pete

On Jan 31, 2013, at 12:05 PM, laxman01 notifications@github.com wrote:

That is a really cool idea, I have not personally heard of anyone doing
this. If I come across anything I will let you know.

—
Reply to this email directly or view it on
GitHubhttps://github.com/plamoni/SiriProxy/issues/425#issuecomment-12962798.

**Comment by davidgeppelt** [comment]
But couldn't you - and I am sorry if this is a stretch - keep the TCP/IP connection open, like with APNS. I understand that it would require that the user to activate Siri initially, but as long as the line is kept (not moving from GSM to WiFi) in theory wouldn't it keep? Or would FIN cause it to dump, and if so, could you follow the end of one connection with a request from the server for another connection, if what you are saying about the Siri process living for a short time after the interface goes away. Or does the connection get dumped anyways as soon the user stops using the Siri interface?

**Comment by plamoni** [comment]
It probably won't work because it's not Siri that's closing the connection, it's that the phone is killing the application. You might be able to hold it open for a few minutes, but I imagine after 5 minutes or so the phone would kill the Siri application because it's no longer in the foreground.

And even if you send a message back, I'm not sure Siri will act on it because the application isn't active. 

But feel free to give it a try and see what happens.

Going to close because this is a bit of a theoretical conversation and not an issue. Thanks!
