### ISSUE TITLE
Stream freed prematurely

### ISSUE THREAD

**Issue by ghost** [plamoni/SiriProxy#426]
I get this error followed by a lot of lines saying zlib(finalizer): the stream was free prematurely. Error: /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:664:in `connect_server': unable to resolve server address (EventMachine::ConnectionError)
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:664:in`bind_connect'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:640:in `connect'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/connection/iphone.rb:20:in`ssl_handshake_completed'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run_machine'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in`run'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy.rb:16:in `initialize'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:96:in`new'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:96:in `start_server'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:85:in`run_server'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/command_line.rb:37:in `initialize'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/bin/siriproxy:6:in`new'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/bin/siriproxy:6:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/bin/siriproxy:23:in`load'
    from /usr/local/rvm/gems/ruby-1.9.3-p374@SiriProxy/bin/siriproxy:23:in `<main>'

I get it at the end of every command.

**Comment by venom420x** [comment]
Your DNS is probably set up in correctly.

**Comment by plamoni** [comment]
Going to go with @venom420x on this one. Check your DNS. Also consider doing a `siriproxy update --branch dev` and see if that resolves the issue.
