### ISSUE TITLE
start.rb error

### ISSUE THREAD

**Issue by ghost** [plamoni/SiriProxy#43]
rvmsudo ruby start.rb
ruby: No such file or directory -- start.rb (LoadError)

i keep getting this error even though i have the file in my plamoni folder.
also i have a problem with the dnsmasq, no matter how many times i kill the dnsmasq with sudo killall dnsmasq it continues to give me the error, im thinking that maybe its becuase of my ip but i have tried every possible ip.

sudo /opt/local/sbin/dnsmasq
Password:

dnsmasq: failed to create listening socket for 10.37.129.2: Address already in use

**Comment by courtenay** [comment]
You definitely aren't running it from the right directory. And you already
have something running on the DNS port. Maybe bind?

On Thu, Nov 24, 2011 at 1:17 PM, gdmoney13 <
reply@reply.github.com

**Comment by fiquett** [comment]
What OS are you on?

DNSMasq : Looks like you have another process using port 53. You need to find out what it is and stop it.

After you use RVM to install Ruby and the required Gems, then you can go into the directory where the "start.rb" file is located and run "ruby start.rb" from the CLI.

**Comment by ghost** [comment]
I am running on 10.6.8 snow leopard on a laptop and i have been trying to killall of the processes but as soon as i kill the processes and run dnsmasq without the error, the port gets filled up right away.

**Comment by ghost** [comment]
i think i might know what the problem is becuase when i open up the readme file it says to install rvm 1.9.2 which isnt working. i did manage to install all of the gems with the exception of open-uri. i keep getting this error when typing in rvm install 1.9.2

rvm install ruby-1.9.2-p290
Installing Ruby from source to: /usr/local/rvm/rubies/ruby-1.9.2-p290, this may take a while depending on your cpu(s)...

ruby-1.9.2-p290 - #fetching 
ruby-1.9.2-p290 - #downloading ruby-1.9.2-p290, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 8604k    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0Warning: Failed to create the file ruby-1.9.2-p290.tar.bz2
  0 8604k    0  1402    0     0    262      0  9:20:30  0:00:05  9:20:25  3230
curl: (23) Failed writing body (0 != 1402)
ERROR: There was an error, please check /usr/local/rvm/log/ruby-1.9.2-p290/_.log. Next we'll try to fetch via http.
Trying http:// URL instead.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file ruby-1.9.2-p290.tar.bz2
  0 8604k    0  1101    0     0   2169      0  1:07:42 --:--:--  1:07:42  4317
curl: (23) Failed writing body (0 != 1101)
ERROR: There was an error, please check /usr/local/rvm/log/ruby-1.9.2-p290/_.log
ERROR: There has been an error while trying to fetch the source.  
Halting the installation.
ERROR: There has been an error fetching the ruby interpreter. Halting the installation.

**Comment by fiquett** [comment]
Check out this page. It is a pretty good tutorial that some others have had good success with.

http://www.christopherirish.com/2010/08/25/how-to-install-rvm-on-ubuntu-10-04/

You may want to try installing ruby 1.9.2-head. I was able to get that version to work fine.

$ rvm install 1.9.2-head

On Thu, Nov 24, 2011 at 9:16 PM, gdmoney13 <
reply@reply.github.com

**Comment by ghost** [comment]
i did manage to install ruby 1.9.2-head but i still remain with the start.rb problem 

rvmsudo start.rb
env: start.rb: No such file or directory

im not sure what wrong becuase even when i dragged the file straight to terminal it said:

rvmsudo ruby /Users/tdedushi/Desktop/plamoni/start.rb 
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/yaml.rb:143:in `initialize': No such file or directory - config.yaml (Errno::ENOENT)
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/yaml.rb:143:in`open'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/yaml.rb:143:in `load_file'
    from /Users/tdedushi/Desktop/plamoni/start.rb:20

**Comment by courtenay** [comment]
you're not running it from the right directory, either time.

try rvmsudo ./start.rb

On Thu, Nov 24, 2011 at 7:24 PM, Granit Dedushi <
reply@reply.github.com

**Comment by ghost** [comment]
guys one last thing, i did manage to get the proxy running for a second and then got this error im not sure what it is and when i tried installing the event machine gem it didnt work either
sudo ruby start.rb
Starting SiriProxy on port 443..
./siri_proxy.rb:27:in `initialize': Cannot start the server on port 443 - are you root, or have another process on this port already? (RuntimeError)
    from /Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`call'
    from /Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
    from /Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run'
    from ./siri_proxy.rb:18:in `initialize'
    from start.rb:21:in`new'
    from start.rb:21

sudo gem install eventmachine
Building native extensions.  This could take a while...
Successfully installed eventmachine-0.12.10
1 gem installed
Installing ri documentation for eventmachine-0.12.10...
Installing RDoc documentation for eventmachine-0.12.10...
Could not find main page README
Could not find main page README
Could not find main page README
Could not find main page README
