### ISSUE TITLE
Cannot Generate Certificates

### ISSUE THREAD

**Issue by 128keaton** [plamoni/SiriProxy#431]
I have an issue much like others, but I have done everything the others have. I cannot generate the certificates for the iPhone. My error is:

A challenge password []:An optional company name []:Using configuration from /usr/local/rvm/rubies/ruby-1.9.3-p374/lib/ruby/gems/1.9.1/gems/siriproxy-0.3.2/lib/siriproxy/../../scripts/openssl.cnf
Error opening CA certificate /tmp/siriCA/cacert.pem
52604:error:02001002:system library:fopen:No such file or directory:bss_file.c:278:fopen('/tmp/siriCA/cacert.pem','r')
52604:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:280:
unable to load certificate
writing RSA key

I have reinstalled RVM and Ruby.

**Comment by laxman01** [comment]
what command are you running to get this error

**Comment by Xaywar** [comment]
https://github.com/plamoni/SiriProxy/issues/428
this worked perfectly for me

**Comment by 128keaton** [comment]
I got it to work.
