### ISSUE TITLE
iPhone is not 'detecting' SiriProxy

### ISSUE THREAD

**Issue by 128keaton** [plamoni/SiriProxy#432]
And SiriProxy is not detecting the phone either. Is there a log? I have set everything up properly. I got the certs to work. I am an iPhone 5, iOS 6.1

**Comment by 128keaton** [comment]
And it says ''Starting SiriProxy on 0.0.0.0:443"

**Comment by laxman01** [comment]
It says your IP address is 0.0.0.0 , so go into .siriproxy/config.yml and change the 0.0.0.0 to your IP address
then run siriproxy update
then start the server

**Comment by 128keaton** [comment]
I have set the DNS to the computer, but the server stays at SiriProxy up and running!

**Comment by 128keaton** [comment]
Does it have something to do with dnsmasq

**Comment by laxman01** [comment]
No,It says your IP address is 0.0.0.0 witch is impossible , so go into .siriproxy/config.yml and change the 0.0.0.0 to your IP address
then run siriproxy update
then start the server

**Comment by 128keaton** [comment]
I did that, still stays at the message. It shows my IP though

**Comment by laxman01** [comment]
and could you post what errors your seeing

**Comment by laxman01** [comment]
did you Install ~/.siriproxy/ca.pem on your phone and change the DNS setting on your phone to your IP address

**Comment by 128keaton** [comment]
No errors whatsoever. It just says:
Starting SiriProxy on 192.168.1.74:443
SiriProxy up and running.

**Comment by 128keaton** [comment]
Yes, I did and I changed the DNS setting

**Comment by laxman01** [comment]
and when you click on siri you get no response? are you sure the ip address's are the same on your phone and dnsmasq.conf?

**Comment by 128keaton** [comment]
IP address and DNSMasq? Oh the DNS and the routing. Ill check

**Comment by laxman01** [comment]
could you copy and paste the contents of DNSMASQ that you edited

**Comment by laxman01** [comment]
hmmmm that is right... what about when you run "sudo dnsmasq"

**Comment by laxman01** [comment]
hmmmm that is right... what about when you run "sudo dnsmasq"

**Comment by 128keaton** [comment]
Okay, that gave me an error. The port 53 is already being used. Ubuntu. I thought we went over this. How can I closed named

**Comment by laxman01** [comment]
this is first of me hearing this............... sudo killall named

**Comment by 128keaton** [comment]
Sorry

**Comment by 128keaton** [comment]
named: no process found

**Comment by laxman01** [comment]
hmmmmm one sec

**Comment by laxman01** [comment]
sudo lsof -i :443 | grep LISTEN
sudo lsof -i :53 | grep LISTEN

run those and see if you get any results from them... if you do paste the results in here

**Comment by 128keaton** [comment]
dnsmasq 20535 dnsmasq    5u  IPv4  72258      0t0  TCP *:domain (LISTEN)
dnsmasq 20535 dnsmasq    7u  IPv6  72260      0t0  TCP *:domain (LISTEN)
 is the second result

**Comment by 128keaton** [comment]
The first one gives me a capitol N

**Comment by laxman01** [comment]
ok so  when you try to start dnsmasq and it says its already in use by another instance of dnsamsq..
try running "sudo killall dnsmasq" a couple times then restarting dnsmasq

**Comment by 128keaton** [comment]
Ok, did that

**Comment by laxman01** [comment]
what happened when you ran sudo dnsmasq that time

**Comment by 128keaton** [comment]
nothing
It just went back to the prompt

**Comment by laxman01** [comment]
ok so thats good now dnsmasq is running on port 53 by itself. try restarting the server now

**Comment by 128keaton** [comment]
Just did, no connection still!

**Comment by 128keaton** [comment]
I did the listen command and I got this for port 53:
dnsmasq 20749 nobody    5u  IPv4  74981      0t0  TCP *:domain (LISTEN)
dnsmasq 20749 nobody    7u  IPv6  74983      0t0  TCP *:domain (LISTEN)

**Comment by laxman01** [comment]
well thats fine because only dnsmasq is running on it i just realized that it does not matter how many instances of it are running as long as its the only thing.
try running "siriproxy gencerts" and replacing the ca.pem on your phone with the new one

**Comment by 128keaton** [comment]
Not showing a connection. Hmmmm

**Comment by laxman01** [comment]
wait did you try running "siriproxy gencerts" and replacing the ca.pem on your phone with the new one

**Comment by 128keaton** [comment]
Yes.

**Comment by 128keaton** [comment]
Gonna try on ethernet now, not wifi

**Comment by 128keaton** [comment]
gonna do rake install and bundle siriproxy

**Comment by 128keaton** [comment]
AGH cannot connect to the internet on my buntu machine now

**Comment by laxman01** [comment]
Do you have your networked bridged

**Comment by 128keaton** [comment]
No. Direct ethernet, to switcher, to router.

**Comment by 128keaton** [comment]
I get an IP, but no internet access

**Comment by laxman01** [comment]
Do you have your machines set up on Windows

**Comment by 128keaton** [comment]
Mostly macs

**Comment by 128keaton** [comment]
The server is ubuntu, my laptop (which I am typing this from) is a macbook pro.

**Comment by 128keaton** [comment]
Gonna reboot my router in a sec

**Comment by laxman01** [comment]
Why don't you try setting it up on your Mac?

**Comment by 128keaton** [comment]
I have. On two.

**Comment by 128keaton** [comment]
I have a powermac which I was working on all morning.

**Comment by 128keaton** [comment]
I could not get the certs to generate properly

**Comment by laxman01** [comment]
I'm unfamiliar on what a powermac is

**Comment by 128keaton** [comment]
A PowerPC Mac Pro

**Comment by 128keaton** [comment]
Could I generate the certs on the ubuntu machine and point them to the PowerMac?

**Comment by laxman01** [comment]
go into your siriproxy directory
run rake install
run siriproxy gencerts

**Comment by 128keaton** [comment]
Okay, siriproxy, command not found

**Comment by laxman01** [comment]
i have no idea what is wrong... rake install worked ?

**Comment by 128keaton** [comment]
Yes.

**Comment by 128keaton** [comment]
Should I try sudo?

**Comment by laxman01** [comment]
i dont think that will work, im sorry i have zero experience with ubuntu and powermac. but if you ever want to try it on a mac i would try this https://github.com/plamoni/SiriProxy/issues/428

**Comment by 128keaton** [comment]
AGH!

**Comment by laxman01** [comment]
sorry if i think of anything i will let you know

**Comment by 128keaton** [comment]
/Users/user/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/../../scripts/gen_certs.sh: line 27: /Users/user/.siriproxy/cert.log: Permission denied
/Users/user/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/../../scripts/gen_certs.sh: line 45: /Users/user/.siriproxy/cert.log: Permission denied
/Users/user/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/../../scripts/gen_certs.sh: line 48: /Users/user/.siriproxy/cert.log: Permission denied
/Users/user/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/../../scripts/gen_certs.sh: line 61: /Users/user/.siriproxy/cert.log: Permission denied
/Users/user/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/../../scripts/gen_certs.sh: line 64: /Users/user/.siriproxy/cert.log: Permission denied
/Users/user/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/siriproxy-0.3.2/lib/siriproxy/../../scripts/gen_certs.sh: line 67: /Users/user/.siriproxy/cert.log: Permission denied
mv: rename /tmp/newcert.pem to /Users/user/.siriproxy/server.passless.crt: No such file or directory
mv: rename /tmp/siriCA/cacert.pem to /Users/user/.siriproxy/ca.pem: No such file or directory

Is what I get when I try to generate a vert

**Comment by laxman01** [comment]
Maybe try Sudo

**Comment by 128keaton** [comment]
Same thing

**Comment by laxman01** [comment]
Try reinstalling the siriproxy gem

**Comment by 128keaton** [comment]
I did rake install, then bundle siriproxy and it says no task

**Comment by laxman01** [comment]
i would try reinstalling everything and we can set up together step by step

**Comment by 128keaton** [comment]
Okay.

**Comment by 128keaton** [comment]
I have RVM installed, DNSMasq, and the latest ruby

**Comment by laxman01** [comment]
ok now try reinstalling siriproxy

**Comment by 128keaton** [comment]
Alrighty, gotta git it

**Comment by laxman01** [comment]
yeah and do you have internet connection on ubuntu

**Comment by 128keaton** [comment]
Nope. Hmmm. Gonna reboot

**Comment by laxman01** [comment]
ok

**Comment by 128keaton** [comment]
Ok I got it

**Comment by 128keaton** [comment]
Gitting the siriproxy

**Comment by laxman01** [comment]
sweet

**Comment by 128keaton** [comment]
Okay, gonna rake install, k?

**Comment by 128keaton** [comment]
Scratch that, gotta make the siriserver dir

**Comment by laxman01** [comment]
did you already 
rvmsudo gem install rake bundler

**Comment by 128keaton** [comment]
I did that too

**Comment by laxman01** [comment]
alright

**Comment by 128keaton** [comment]
I copied the YMLs and edited them, about to generate certificates

**Comment by 128keaton** [comment]
I need to rake install

**Comment by 128keaton** [comment]
Okay, siriproxy, command not found

**Comment by 128keaton** [comment]
Got it fixed

**Comment by 128keaton** [comment]
No, I didn't

**Comment by laxman01** [comment]
What's wrong now

**Comment by 128keaton** [comment]
Still giving me werid stuff

**Comment by 128keaton** [comment]
Gonna resume tommorrow

**Comment by 128keaton** [comment]
Back

**Comment by 128keaton** [comment]
Got it all bundled

**Comment by 128keaton** [comment]
I switched over to three little pigs and that works, but it is trying to connect to itself instead of guzzoni. Can I have some help?

**Comment by laxman01** [comment]
I can later, I'm at school now

**Comment by Deanmv** [comment]
Read: Using Siri causes a whole bunch of the following messages, followed by SiriProxy crashing!

Here: https://github.com/plamoni/SiriProxy

**Comment by laxman01** [comment]
ok so where are you at in the process and what errors are you receiving

**Comment by 128keaton** [comment]
Ok, I am in the same boat I was with siriproxy. I cannot connect to the proxy. It won't even detect it!

**Comment by 128keaton** [comment]
There is something with DNSMasq that freaks out my internet when I kill DNSMasq

**Comment by plamoni** [comment]
So it sounds like you've configured your network to point to dnsmasq for DNS (probably via a DHCP configuration). So when you bring down dnsmasq, you lose DNS service on your network (which would make it appear as if your Internet is down).

Here's my suggestion:
1. Run `siriproxy update --branch dev`. This will pull the dev branch, which should resolve the "circular connections" problem.
2. Turn on your dnsmasq.
3. Turn on Airplane mode on your phone, then turn it off again (this resets all your network connections).
4. Check your network settings on your phone (via the WiFi settings) and find the DNS server address, it should be your SiriProxy server's IP. If it's not, change it manually (I'm going to guess it is, though). 
5. Run Siri and say "Test SiriProxy" -- _hopefully_ it will respond that SiriProxy is up and running. If not, report back here.

**Comment by 128keaton** [comment]
@plamoni Thanks! I gave up on trying to run it on Ubuntu, so it runs on my PowerMac. Sometimes Ubuntu acts like s**t!
