### ISSUE TITLE
Not really an issue...

### ISSUE THREAD

**Issue by andymcblane** [plamoni/SiriProxy#433]
I would like to know how to do timer and map injection..

Also how to read 'contents' from a file..

Like I could create an excel document with different time, in different colums. I could say when am I going to TAFE next, and it reads this file and extracts the information and spits it out..

**Comment by plamoni** [comment]
Going to close because it's not really an issue. I suggest you head to a Ruby forum about opening/reading a file. As for timer and map injection, they're very hard right now so you might be out of luck there unless you've got some significant development experience.
