### ISSUE TITLE
iPhone 5, ios 6.1, not connecting to proxy

### ISSUE THREAD

**Issue by 128keaton** [plamoni/SiriProxy#434]
No errors here, just stays put after starting it. I don't think it is the certificate (maybe) but it will not connect.

**Comment by leqz** [comment]
dnsmasq issue. If you are using a vm be sure to set your network mode to bridged

**Comment by 128keaton** [comment]
I am using a standalone machine. Whenever I restart dnsmasq, it crashes my internet on my machine!

**Comment by plamoni** [comment]
What do you mean by "crashes" your internet? Can you be more specific?

**Comment by plamoni** [comment]
I'm actually going to close this thread because it looks like you have another one with lots of activity. So let's move the conversation there.
