### ISSUE TITLE
Guide to install Siryproxy on NAS Synology?

### ISSUE THREAD

**Issue by Piero87** [plamoni/SiriProxy#435]
Hello, can you please add a step by step guide to install siryproxy on a NAS Synology? I have a ds213+ and i can't understand how install it, thanks!

**Comment by lsamamig** [comment]
i want it too.. +1!!

**Comment by elvisimprsntr** [comment]
You are likely to obtain better support on the device specific forums since you are less than 0.0000001% of the SiriProxy community
