### ISSUE TITLE
SiriProxy Over 4G 

### ISSUE THREAD

**Issue by laxman01** [plamoni/SiriProxy#437]
Current Setup: SiriProxy up and running, jailbroken iPhone 4S 6.1 (with openSSH) and im running OS X Mountain Lion

Knowledge: I know some editing of the iPhones host files has to be edited along with com.apple.assistant.plist file.

Goal: SiriProxy running outside of my home network 

Please someone help me achieve this goal

**Comment by laxman01** [comment]
Anyone?

**Comment by plamoni** [comment]
It's tough to set up. Easiest\* and most secure option is a VPN. I recommend
against running siriproxy on a public connection because it has potential
security problems.

-Pete

*that's a very relative term.

On Feb 9, 2013, at 3:46 PM, laxman01 notifications@github.com wrote:

Anyone?

—
Reply to this email directly or view it on
GitHubhttps://github.com/plamoni/SiriProxy/issues/437#issuecomment-13339350..

**Comment by andymcblane** [comment]
You can actually edit your iPhone hosts file with ifile..
/private/etc/hosts
Open with text viewer
On the last line (external ip)  guzzoni.apple.com 

Then port forward 443 to your local ip of siriproxy in your modem/router. 

Edit: typos

**Comment by laxman01** [comment]
@plamoni 
Thank you for your suggestion, it is much appreciated. I have attempted VPN before I tried for about two months with no luck.https://github.com/plamoni/SiriProxy/issues/405
I would really appreciate any help I could get. I love this creation so much and the more I can use it the better.

**Comment by plamoni** [comment]
Just keep in mind that using the hosts file method is a security risk. I'm
not responsible if someone uses SP to own your box. If you are going to
make SP publicly accessible, at the very least you should not run SP as
root.

-Pete

On Feb 9, 2013, at 5:20 PM, laxman01 notifications@github.com wrote:

Thank you for your suggestion, it is much appreciated. I have attempted VPN
before I tried for about two months with no
luck.#405https://github.com/plamoni/SiriProxy/issues/405
I would really appreciate any help I could get. I love this creation so
much and the more I can use it the better.

—
Reply to this email directly or view it on
GitHubhttps://github.com/plamoni/SiriProxy/issues/437#issuecomment-13340839..

**Comment by laxman01** [comment]
Can someone please help me with either of these methods

**Comment by laxman01** [comment]
please

**Comment by andymcblane** [comment]
My comment has everything you need to do.

**Comment by laxman01** [comment]
I have edited the host file,but do i put the same ip address that i put into dnsmasq.conf, or a different one. cause right now its not working

**Comment by andymcblane** [comment]
In dnsmasq.conf you put in your internal IP address. You need to put your external IP address into your hosts file. 
Then port forward in your router 443 (default Siri port) to your local ip.

**Comment by laxman01** [comment]
okay so i have my port forwarded but i probably seem really stupid because i have no idea how to find my external ip would i just go here http://www.whatsmyip.org

**Comment by andymcblane** [comment]
Yep! That will get your external IP address

**Comment by laxman01** [comment]
awesome let me go try it with these new changes.. thank you for your help

**Comment by laxman01** [comment]
still no connection

**Comment by andymcblane** [comment]
Try toggle aeroplane mode on an off

**Comment by laxman01** [comment]
im sorry how do i go about doing that

**Comment by andymcblane** [comment]
You shouldn't need to port forward dnsmasq
In settings at the top there's a feature called aeroplane mode

**Comment by laxman01** [comment]
this is weird it is connecting to it when im on the same wifi even though i did not change the DNS field on the iPhone

**Comment by laxman01** [comment]
![Screen Shot 2013-02-12 at 8 57 22 PM](https://f.cloud.github.com/assets/1238261/151535/be15e94a-7580-11e2-9dae-0067a570431d.png)
i dont see aeroplane mode

**Comment by andymcblane** [comment]
It's working then. Turn wifi off and siriproxy will work anywhere

**Comment by laxman01** [comment]
now its not working and how come this tutorial is different

 Use iFile, ftp or ssh to edit your "/etc/hosts" file and add the following line:

YOURIP/DYNDNS guzzoni.apple.com

replace the "YOURIP/ DNYDNS" with your external ip or dyndns hostname.

You can use the same certificate you are using on your iPhone4s (guzzoni.apple.com)

In your com.apple.assistant.plist or in your spire settings put guzzoni.apple.com

Now it should connect to your siriproxy over 3g

**Comment by andymcblane** [comment]
That's exactly the same. Just different wording.

**Comment by laxman01** [comment]
ok why is this not workinngggg

**Comment by laxman01** [comment]
would editing the iphones dnsmasq.conf file work?

**Comment by andymcblane** [comment]
You do not need to worry about DNS anymore. 
Leave it blank.

**Comment by laxman01** [comment]
ok then what am i doing wrong

**Comment by andymcblane** [comment]
From what you're telling me it is. And if it isn't, explain what's happening

**Comment by laxman01** [comment]
i switch to 4g and restart the server and click on siri and see no response from siriproxy

**Comment by andymcblane** [comment]
Toggle aeroplane mode

**Comment by laxman01** [comment]
i dont see aeroplane mode.... 
![](https://f.cloud.github.com/assets/1238261/151535/be15e94a-7580-11e2-9dae-0067a570431d.png)

**Comment by andymcblane** [comment]
On your iPhone, toggle aeroplane mode.

**Comment by laxman01** [comment]
ohhhhh you mean airplane mode

**Comment by laxman01** [comment]
still no response

**Comment by andymcblane** [comment]
I feel like an idiot! Haha sorry about that. The spelling for 'airplane' is stupid.

**Comment by andymcblane** [comment]
Install a new gen_certs file

**Comment by laxman01** [comment]
Hahahha it's all good and still no response on 4g after the new certs

**Comment by plamoni** [comment]
Given that this is a bit outside what I support for SiriProxy, I'm going to go ahead and close the issue. But feel free to continue your discussion. Thanks for helping, @andymcb1!
