### ISSUE TITLE
Eventmachine on mac SL

### ISSUE THREAD

**Issue by marcos69** [plamoni/SiriProxy#44]
I have the problem on mac osx 10.6.8, that the eventmachine does not have encriptation.

But I didn't find any libssl-dev for mac, as suggested for linux user.

I also tried: sudo gem install eventmachine -- --with-ssl-dir=/Users/marc/ossl/
where in ossl I put 2 links: include (to /usr/include/openssl) and lib (to /usr/lib) ,
because I tried --with-ssl-dir=/usr/bin/openssl and got a compilation error, which let me take a look at the makefile of eventmachine: with linux include and lib are within the openssl directory but not on osx, that why the extra dir.

But it doesn't work anyway, got that "Encriptation..."

**Comment by plamoni** [comment]
Not sure what the issue is here. We mostly use OSX 10.7. 

Have you tried using MacPorts to install libssl-dev?

**Comment by marcos69** [comment]
The libssl-dev packages only contain the header and libs of the openssl, these are allready installed on osx and I did also install the openssl from MacPort, wichh contain the same header and libs as libssl-dev.

I tried it with the osx Ruby1.8 and the MacPort Ruby1.9, but I can't create any eventmachine with SSL support. The best I got is to stop the gem creating process (of eventmachine), modify the Makefile, do a make (I get an ssl.o before linking), and a gem spec command. But without "make install" it abort witth this:

sudo ruby start.rb/Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/em/connection.rb:39:in `new': undefined method`associate_callback_target' for #SiriIPhoneConnection:0x101002ce0 (NoMethodError)

But with the "make install" nothing happen after I started SiriProxy, and Sir is sorry and can't take any request.

**Comment by plamoni** [comment]
We do not support ruby 1.8. Please use 1.9.3, per the setup instructions.

-Pete

Sent from my iPhone

On Nov 27, 2011, at 2:09 AM, marcos69
reply@reply.github.com
wrote:

**Comment by marcos69** [comment]
Even with 1.9.3, same problem "Encryptation not supported by eventmachine"

**Comment by marcos69** [comment]
I found a way...

Take a look at the eventmachine-0.12.10/ext/Makefile , remove this -DWITHOUT_SSL , then make, make install.
