### ISSUE TITLE
Siri Proxy Crashes

### ISSUE THREAD

**Issue by cbuckley** [plamoni/SiriProxy#441]
Hi would appreciate some help if possible. My phone is connecting to the proxy and my proxy can connect to the apple siri servers but I get the following error

ng.Starting SiriProxy on 0.0.0.0:443..
SiriProxy up and running.
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000002347608 @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x000000023474a0>, @zip_stream=#Zlib::Deflate:0x00000002347478, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000002622eb8 @manager=#<SiriProxy::PluginManager:0x00000002346fa0 @plugins=[...]>>]
[Info - iPhone] Received Object: LoadAssistant
/home/ubuntu/.rvm/gems/ruby-1.9.3-p385/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:217:in `encode': "\xD6" followed by "\xC7" on UTF-8 (Encoding::InvalidByteSequenceError)
        from /home/ubuntu/.rvm/gems/ruby-1.9.3-p385/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:217:in`charset_convert'
        from /home/ubuntu/.rvm/gems/ruby-1.9.3-p385/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:442:in `string_to_binary'
        from /home/ubuntu/.rvm/gems/ruby-1.9.3-p385/gems/CFPropertyList-2.2.0/lib/rbCFTypes.rb:48:in`to_binary'
        from /home/ubuntu/.rvm/gems/ruby-1.9.3-p385/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `block in dict_to_binary'
        from /home/ubuntu/.rvm/gems/ruby-1.9.3-p385/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in`map'
        from /home/ubuntu/.rvm/gems/ruby-1.9.3-p385/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `dict_to_binary'
        from /home/ubuntu/.rvm/gems/ruby-1.9.3-p385/gems/CFPropertyList-2.2.0/lib/rbCFTypes.rb:243:in`to_binary'
        from /home/ubuntu/.rvm/gems/ruby-1.9.3-p385/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `block in dict_to_binary'
        from /home/ubuntu/.rvm/gems/ruby-1.9.3-p385/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in`map'
        from /home/ubuntu/.rvm/gems/ruby-1.9.3-p385/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:550:in `dict_to_binary'
        from /home/ubuntu/.rvm/gems/ruby-1.9.3-p385/gems/CFPropertyList-2.2.0/lib/rbCFTypes.rb:243:in`to_binary'
        from /home/ubuntu/.rvm/gems/ruby-1.9.3-p385/gems/CFPropertyList-2.2.0/lib/rbBinaryCFPropertyList.rb:70:in `to_str'
        from /home/ubuntu/.rvm/gems/ruby-1.9.3-p385/gems/CFPropertyList-2.2.0/lib/rbCFPropertyList.rb:363:in`to_str'
        from /home/ubuntu/.rvm/gems/ruby-1.9.3-p385/gems/CFPropertyList-2.2.0/lib/rbCFPropertyList.rb:398:in `to_plist'
        from /home/ubuntu/SiriProxy/lib/siriproxy/connection.rb:150:in`inject_object_to_output_stream'
        from /home/ubuntu/SiriProxy/lib/siriproxy/connection.rb:90:in `process_compressed_data'
        from /home/ubuntu/SiriProxy/lib/siriproxy/connection.rb:58:in`receive_binary_data'
        from /home/ubuntu/.rvm/gems/ruby-1.9.3-p385/gems/eventmachine-1.0.0/lib/em/protocols/linetext2.rb:94:in `receive_data'
        from /home/ubuntu/.rvm/gems/ruby-1.9.3-p385/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in`run_machine'
        from /home/ubuntu/.rvm/gems/ruby-1.9.3-p385/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run'
        from /home/ubuntu/SiriProxy/lib/siriproxy.rb:16:in`initialize'
        from /home/ubuntu/SiriProxy/lib/siriproxy/command_line.rb:96:in `new'
        from /home/ubuntu/SiriProxy/lib/siriproxy/command_line.rb:96:in`start_server'
        from /home/ubuntu/SiriProxy/lib/siriproxy/command_line.rb:85:in `run_server'
        from /home/ubuntu/SiriProxy/lib/siriproxy/command_line.rb:37:in`initialize'
        from /home/ubuntu/SiriProxy/bin/siriproxy:6:in `new'
        from /home/ubuntu/SiriProxy/bin/siriproxy:6:in`<top (required)>'
        from /home/ubuntu/.rvm/gems/ruby-1.9.3-p385/bin/siriproxy:19:in `load'
        from /home/ubuntu/.rvm/gems/ruby-1.9.3-p385/bin/siriproxy:19:in`<main>'
        from /home/ubuntu/.rvm/gems/ruby-1.9.3-p385/bin/ruby_noexec_wrapper:14:in `eval'
        from /home/ubuntu/.rvm/gems/ruby-1.9.3-p385/bin/ruby_noexec_wrapper:14:in`<main>'
ubuntu@ip-10-48-6-233:~/SiriProxy$

**Comment by laxman01** [comment]
ok first It says your IP address is 0.0.0.0 , so go into .siriproxy/config.yml and change the 0.0.0.0 to your IP address
then I would recommend downloading 
http://rubyforge.org/frs/download.php/76604/CFPropertyList-2.1.2.zip
Then placing the contents of that folder in the CFPropertylist 2.2.0 folder located in
/Users/your username/.rvm/gems/ruby-1.9.3-p374@SiriProxy/gems/CFPropertyList-2.2.0

**Comment by sturma** [comment]
I also had the same issue and your solution worked. Strange it only happened with mac, when following #428. I didn't have this with ubuntu

**Comment by cbuckley** [comment]
Thanks for the help. The copying CFPropertylist 2.1.2 to CFPropertylist 2.2.0 worked perfectly.

**Comment by laxman01** [comment]
No problem

**Comment by plamoni** [comment]
This is now fixed in the master branch. Feel free to do a `siriproxy update` and it will resolve the issue without the manual process.
