### ISSUE TITLE
SiriProxy installation error :(

### ISSUE THREAD

**Issue by TheKleini666** [plamoni/SiriProxy#442]
Hey,

Information:
System: Debian squeeze
Installation: Perfect.
Setting up iPhone: Perfect.

Starting SiriProxy Server: Error!

so first I tried 
"rvmsuo siriproxy server"  Result: "sudo: siriproxy: command not found"
then I tried
"rvm siriproxy server" Result: "Unrecognized command line argument: 'siriproxy' ( see: 'rvm usage' )"

then I tried starting the server using "siriproxy server" (also sudo siriproxy server) and just got the error, that the port is in use or i didn't start it with root privilegs.

After research I found out, that you only need root if the Port is < 1024, so I changed the Port in my config.yml to 1030.
Ok started the siriproxy server and BÄÄHHHM! It worked "SiriProxy up and running.".

But I want to run it on the Port 443, cause I didn't get iptables and ufw working ;(

I had a siri proxy server (Ubuntu) a year ago and everything worked perfectly, but not on my damn debian server -.-

THANKS!

**Comment by plamoni** [comment]
You need to use iptables or something like that to forward the traffic to
the right port. Check the readme.

-Pete

On Feb 9, 2013, at 4:00 PM, TheKleini666 notifications@github.com wrote:

Hey,

Information:
System: Debian squeeze
Installation: Perfect.
Setting up iPhone: Perfect.

Starting SiriProxy Server: Error!

so first I tried
"rvmsuo siriproxy server" Result: "sudo: siriproxy: command not found"
then I tried
"rvm siriproxy server" Result: "Unrecognized command line argument:
'siriproxy' ( see: 'rvm usage' )"

then I tried starting the server using "siriproxy server" (also sudo
siriproxy server) and just got the error, that the port is in use or i
didn't start it with root privilegs.

After research I found out, that you only need root if the Port is < 1024,
so I changed the Port in my config.yml to 1030.
Ok started the siriproxy server and BÄÄHHHM! It worked "SiriProxy up and
running.".

But the iPhone sends Siri commands on the Port 443 and not 1030, how can i
change that?

THANKS!

—
Reply to this email directly or view it on
GitHubhttps://github.com/plamoni/SiriProxy/issues/442..

**Comment by TheKleini666** [comment]
But how do i setup and config iptables (and ufw)?
I haven't found a turorial :(

/Edit: I' have the CA.PEM installed on my iPhone (4S 6.1) and also made my DNS Settings.
But when I talk to SIRI, she answers me without any problems (SiriProxy is not running, but dnsmaq is running)? Shouldn't it forward the traffic from SIRI to my local Server?
Dnsmaq works great, tested with another Domain and that worked without problems, so I guess guzzoni.apple.com is wrong?
Also "kryten.apple.com" and "daisy.apple.com" is not working? Is there a way to check which domains/ports are used from the iPhone? Something like ncap for iPhone?

Ok when I watch all traffic for the port 443 using "tcpdump" I see guzzoni.apple.com. So what's the problem with my dnsmaq? Everyy other domain works perfectly except guzzoni.appel.com. 

Ok, problem found!
Siri connects to guzzoni using 3G god damn!

**Comment by TheKleini666** [comment]
Ok the next problem is:
How do I setup ufw and iptables?

"ufw status" says "ufw: inactive"
When I type "ufw enable" my SSH connections closes and I can't connect to my Server anymore (not using SSH/FTP/HTTP or anything else).
So I have to restart.

**Comment by plamoni** [comment]
Please check this:

https://github.com/plamoni/SiriProxy#running-siriproxy-as-an-unprivileged-user

**Comment by TheKleini666** [comment]
Yeah, the problem was, that "nat" is not install in my kernel, so I had to modify it a bit ;)
Thanks! :)
