### ISSUE TITLE
rake install won't run unless root.

### ISSUE THREAD

**Issue by 128keaton** [plamoni/SiriProxy#443]
Here is the output from my administrator user using rake install:
*\* Invoke install (first_time)
*\* Execute install
siriproxy 0.3.2 built to pkg/siriproxy-0.3.2.gem
rake aborted!
Couldn't install gem, run `gem install /Users/keaton/SiriProxy/pkg/siriproxy-0.3.2.gem' for more detailed output
/usr/local/rvm/gems/ruby-1.9.3-p374/gems/bundler-1.2.3/lib/bundler/gem_helper.rb:68:in`install_gem'
/usr/local/rvm/gems/ruby-1.9.3-p374/gems/bundler-1.2.3/lib/bundler/gem_helper.rb:43:in `block in install'
/usr/local/rvm/gems/ruby-1.9.3-p374/gems/rake-10.0.3/lib/rake/task.rb:228:in`call'
/usr/local/rvm/gems/ruby-1.9.3-p374/gems/rake-10.0.3/lib/rake/task.rb:228:in `block in execute'
/usr/local/rvm/gems/ruby-1.9.3-p374/gems/rake-10.0.3/lib/rake/task.rb:223:in`each'
/usr/local/rvm/gems/ruby-1.9.3-p374/gems/rake-10.0.3/lib/rake/task.rb:223:in `execute'
/usr/local/rvm/gems/ruby-1.9.3-p374/gems/rake-10.0.3/lib/rake/task.rb:166:in`block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-1.9.3-p374/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/usr/local/rvm/gems/ruby-1.9.3-p374/gems/rake-10.0.3/lib/rake/task.rb:159:in`invoke_with_call_chain'
/usr/local/rvm/gems/ruby-1.9.3-p374/gems/rake-10.0.3/lib/rake/task.rb:152:in `invoke'
/usr/local/rvm/gems/ruby-1.9.3-p374/gems/rake-10.0.3/lib/rake/application.rb:143:in`invoke_task'
/usr/local/rvm/gems/ruby-1.9.3-p374/gems/rake-10.0.3/lib/rake/application.rb:101:in `block (2 levels) in top_level'
/usr/local/rvm/gems/ruby-1.9.3-p374/gems/rake-10.0.3/lib/rake/application.rb:101:in`each'
/usr/local/rvm/gems/ruby-1.9.3-p374/gems/rake-10.0.3/lib/rake/application.rb:101:in `block in top_level'
/usr/local/rvm/gems/ruby-1.9.3-p374/gems/rake-10.0.3/lib/rake/application.rb:110:in`run_with_threads'
/usr/local/rvm/gems/ruby-1.9.3-p374/gems/rake-10.0.3/lib/rake/application.rb:95:in `top_level'
/usr/local/rvm/gems/ruby-1.9.3-p374/gems/rake-10.0.3/lib/rake/application.rb:73:in`block in run'
/usr/local/rvm/gems/ruby-1.9.3-p374/gems/rake-10.0.3/lib/rake/application.rb:160:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-1.9.3-p374/gems/rake-10.0.3/lib/rake/application.rb:70:in`run'
/usr/local/rvm/gems/ruby-1.9.3-p374/gems/rake-10.0.3/bin/rake:33:in `<top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p374/bin/rake:19:in`load'
/usr/local/rvm/gems/ruby-1.9.3-p374/bin/rake:19:in `<main>'
/usr/local/rvm/gems/ruby-1.9.3-p374/bin/ruby_noexec_wrapper:14:in`eval'
/usr/local/rvm/gems/ruby-1.9.3-p374/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => install

But running it as root causes problems later.

**Comment by plamoni** [comment]
You probably ran parts of your rvm installation as root when you should have run them as an unprivileged user. You will need to reinstall rvm as an unprivileged user. It will probably complain during the install that you don't have permissions (because the places it needs to install are owned by root). So you'll need to change permissions where necessary. It's a big pain and if you're running this on a fresh install and you're not very familiar with Linux, you should probably consider just doing a fresh Linux install.

It's very important to not run any of the installation steps as root unless you're explicitly told to do so.

Sorry for the trouble!
