### ISSUE TITLE
Readme file inconsistency

### ISSUE THREAD

**Issue by Michagogo** [plamoni/SiriProxy#447]
"Clone this repo locally, then navigate into the SiriProxy directory (the root of the repo). Then follow these instructions carefully. Note that nothing needs to be (or should be) done as root until you launch the server:

Install Rake and Bundler:
rvmsudo gem install rake bundler"

It says not to do anything as root, and then the first step is done as root.

**Comment by Deanmv** [comment]
Is that not root within rvm? As its rvmsudo and not just sudo.

**Comment by Michagogo** [comment]
@Deanmv Well, considering step 8: "Start SiriProxy (must start as root because it uses a port < 1024):
    rvmsudo siriproxy server
"
I'm guessing not.

**Comment by Deanmv** [comment]
True.

**Comment by plamoni** [comment]
Sorry for the confusion. What I meant by "nothing should be done as root" is that you should not be running commands as root. There are certain commands that need elevated privileges and so need to be run with `sudo` or `rvmsudo` and those are specified.

Lots of people who are not very familiar with Linux or using a shell have wanted to install SiriProxy. I saw a lot of problems where people would switch to root to run the commands, especially if something went wrong while running the command as an unprivileged user (it seems pretty common for people to think, "Oh, that didn't work? Maybe I should run it as root!"). So I put the warning on there to scare people off from doing that, as it can be a huge pain to fix things if they get the wrong permissions.

Sorry for the confusion, but I think that if you are familiar enough with the shell to understand the contradiction, you are not really the target audience of that warning. :-)

Thanks for the input!
