### ISSUE TITLE
Just a question, nothing more.

### ISSUE THREAD

**Issue by SenseiMiaow** [plamoni/SiriProxy#448]
Where can I give up a new plugin?

I made a new one which just searches for the fist image with searched value, and display's it in Siri. Also will be more images available and random.

https://github.com/DJXFMA/SiriProxy-Image

**Comment by Deanmv** [comment]
What do you mean by give up?

**Comment by SenseiMiaow** [comment]
I mean where can I make my plugin available in the plugin list. Sorry for the mis understanding.
My english lacks a little bit. It supports multiple images now.

In here: https://github.com/plamoni/SiriProxy/wiki/Plugins

**Comment by Deanmv** [comment]
Just go on that page, hit edit in the top right and then just follow the same format as everyone else.

**Comment by SenseiMiaow** [comment]
Thanks!  Added 9gag support now to at the plugin.
