### ISSUE TITLE
rvmsudo ruby start.rb Error

### ISSUE THREAD

**Issue by SONY5614** [plamoni/SiriProxy#45]
MacBook-Pro:SiriProxy XXXX$ bundle install
Using rake (0.9.2.2) 
Using libxml-ruby (2.2.2) 
Using CFPropertyList (2.0.17) 
Using cora (0.0.2) from git://github.com/chendo/cora.git (at master) 
Using eventmachine (0.12.10) 
Using uuidtools (2.1.2) 
Using bundler (1.0.21) 
Your bundle is complete! Use `bundle show [gemname]` to see where a bundled gem is installed.
MacBook-Pro:SiriProxy XXXX$ rvmsudo ruby start.rb
Password:

/opt/local/lib/ruby/gems/1.8/bundler/gems/cora-fe8dccd79cae/lib/cora.rb:2:in `require': /opt/local/lib/ruby/gems/1.8/bundler/gems/cora-fe8dccd79cae/lib/cora/plugin.rb:11: odd number list for Hash (SyntaxError)
        block: block,
              ^
/opt/local/lib/ruby/gems/1.8/bundler/gems/cora-fe8dccd79cae/lib/cora/plugin.rb:11: syntax error, unexpected ':', expecting '}'
        block: block,
              ^
/opt/local/lib/ruby/gems/1.8/bundler/gems/cora-fe8dccd79cae/lib/cora/plugin.rb:12: syntax error, unexpected ':', expecting '='
        within_state: ([options[:within_state]].flatten)
                     ^
/opt/local/lib/ruby/gems/1.8/bundler/gems/cora-fe8dccd79cae/lib/cora/plugin.rb:13: syntax error, unexpected '}', expecting kEND
/opt/local/lib/ruby/gems/1.8/bundler/gems/cora-fe8dccd79cae/lib/cora/plugin.rb:76: syntax error, unexpected $end, expecting kEND
    from /opt/local/lib/ruby/gems/1.8/bundler/gems/cora-fe8dccd79cae/lib/cora.rb:2
    from ./siri_proxy/plugin.rb:1:in`require'
    from ./siri_proxy/plugin.rb:1
    from start.rb:17:in `require'
    from start.rb:17

**Comment by hjaltij** [comment]
Are you sure you are using Ruby 1.9.3 ?

**Comment by plamoni** [comment]
We no longer support Ruby 1.8, sorry. Switch to 1.9.3. See the readme.

-Pete

On Fri, Nov 25, 2011 at 8:44 AM, SONY5614 <
reply@reply.github.com

**Comment by SONY5614** [comment]
I'm sorry.
I did not read well.
$ rvm use 1.9.3
Do you use this command every time?
Is there a way to set the default?
(Sorry.I'm Japanese.Therefore not good at English.)

**Comment by plamoni** [comment]
No problem!

You only need to use that once. RVM will then default to 1.9.3 until you
tell it otherwise.

Good luck!

-Pete

On Fri, Nov 25, 2011 at 9:31 AM, SONY5614 <
reply@reply.github.com

**Comment by ghost** [comment]
i have an error too when trying to run siri proxy but i think mine involves eventmachine

sudo ruby start.rb
Starting SiriProxy on port 443..
./siri_proxy.rb:27:in initialize': Cannot start the server on port 443 - are you root, or have another process on this port already? (RuntimeError)
from /Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:incall'
from /Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in run_machine'
from /Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:inrun'
from ./siri_proxy.rb:18:in initialize'
from start.rb:21:innew'
from start.rb:21

sudo gem install eventmachine
Building native extensions. This could take a while...
Successfully installed eventmachine-0.12.10
1 gem installed
Installing ri documentation for eventmachine-0.12.10...
Installing RDoc documentation for eventmachine-0.12.10...
Could not find main page README
Could not find main page README
Could not find main page README
Could not find main page README

**Comment by plamoni** [comment]
use "sudorvm ruby start.rb"

If you still get the error, make sure nothing else is using TCP/443 (e.g. a
webserver or another instance of SiriProxy)

-Pete

On Fri, Nov 25, 2011 at 9:36 AM, Granit Dedushi <
reply@reply.github.com

**Comment by SONY5614** [comment]
plamoni , hjaltij

Thank you!!

**Comment by shack1108** [comment]
I am having a similar problem.

1: When I use "sudorvm ruby start.rb" that doesn't work, but "rvmsudo ruby start.rb" does.
2: Also, I have checked that nothing is using that port, I'm using rvm ruby 1.9.3, I am using sudo, and I am still getting that issue (in the code below, I blacked out my last name with Xs)

Andrew-XXXXXXXX-iMac:SiriProxy Andrew$ lsof -i :443
Andrew-XXXXXXXX-iMac:SiriProxy Andrew$ rvmsudo ruby ./start.rb
./start.rb:3: warning: variable $KCODE is no longer effective; ignored
Starting SiriProxy on port 443..
/Users/Andrew/Misc/SiriProxy/siri_proxy.rb:27:in `rescue in block in initialize': Cannot start the server on port 443 - are you root, or have another process on this port already? (RuntimeError)
    from /Users/Andrew/Misc/SiriProxy/siri_proxy.rb:19:in`block in initialize'
    from /Users/Andrew/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `call'
    from /Users/Andrew/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run_machine'
    from /Users/Andrew/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
    from /Users/Andrew/Misc/SiriProxy/siri_proxy.rb:18:in`initialize'
    from ./start.rb:21:in `new'
    from ./start.rb:21:in`<main>'
Andrew-XXXXXXXX-iMac:SiriProxy Andrew$ lsof -i :443
Andrew-XXXXXXXX-iMac:SiriProxy Andrew$

**Comment by ghost** [comment]
rvmsudo ruby start.rb hasnt worked either and i dont have anything opened so im not sure what could be running on TCP/443 is there anyway to kill or find out what process is running on TCP/443?

**Comment by shack1108** [comment]
To figure out what is running on TCP/443 use the command "lsof -i
:443", but even for me I've quit everything on that port and it still
doesn't work.

**Comment by plamoni** [comment]
Note that unless you run lsof as root, you only see processes running under
your user (e.g. you won't see your ruby process there).

Try:

sudo lsof -i :443 | grep LISTEN

This should give you anything listening on 443.

-Pete

**Comment by shack1108** [comment]
That worked!!!!! Thanks so much for your help!

**Comment by Intecpsp** [comment]
The default on mine was set to 1.9.2 even though I used 'rvm use 1.9.3'. Until I used this command 'rvm use 1.9.3 --default' then it stayed on 1.9.3. (Just thought I would throw my two cents in.)

**Comment by jgst** [comment]
I'm getting the same error as SONY. I'm using ruby 1.9.3 ...any help?

**Comment by plamoni** [comment]
Read my response, we solved SONY's problem.

-Pete

On Sat, Nov 26, 2011 at 10:04 AM, jgst <
reply@reply.github.com

**Comment by jgst** [comment]
Tried it, still getting same result

**Comment by plamoni** [comment]
Please give us some output from your console.

Thanks!

-Pete

On Sat, Nov 26, 2011 at 1:42 PM, jgst <
reply@reply.github.com

**Comment by jgst** [comment]
/opt/local/lib/ruby/gems/1.8/bundler/gems/cora-fe8dccd79cae/lib/cora.rb:2:in require': /opt/local/lib/ruby/gems/1.8/bundler/gems/cora-fe8dccd79cae/lib/cora/plugin.rb:11: odd number list for Hash (SyntaxError)
block: block,
^
/opt/local/lib/ruby/gems/1.8/bundler/gems/cora-fe8dccd79cae/lib/cora/plugin.rb:11: syntax error, unexpected ':', expecting '}'
block: block,
^
/opt/local/lib/ruby/gems/1.8/bundler/gems/cora-fe8dccd79cae/lib/cora/plugin.rb:12: syntax error, unexpected ':', expecting '='
within_state: ([options[:within_state]].flatten)
^
/opt/local/lib/ruby/gems/1.8/bundler/gems/cora-fe8dccd79cae/lib/cora/plugin.rb:13: syntax error, unexpected '}', expecting kEND
/opt/local/lib/ruby/gems/1.8/bundler/gems/cora-fe8dccd79cae/lib/cora/plugin.rb:76: syntax error, unexpected $end, expecting kEND
from /opt/local/lib/ruby/gems/1.8/bundler/gems/cora-fe8dccd79cae/lib/cora.rb:2
from ./siri_proxy/plugin.rb:1:inrequire'
from ./siri_proxy/plugin.rb:1
from start.rb:17:in `require'
from start.rb:17

**Comment by SONY5614** [comment]
Sorry.Problem occurs again.

MacBook-Pro:SiriProxy XXX$ rvm use 1.9.3
Using /Users/XXX/.rvm/gems/ruby-1.9.3-p0
MacBook-Pro:SiriProxy XXX$ bundle install
Updating git://github.com/chendo/cora.git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Fetching source index for http://rubygems.org/
Using rake (0.9.2.2) 
Using libxml-ruby (2.2.2) 
Using CFPropertyList (2.0.17) 
Using cora (0.0.3) from git://github.com/chendo/cora.git (at master) 
Using eventmachine (0.12.10) 
Using siriproxy-example (0.0.1) from source at ./plugins/siriproxy-example 
Using uuidtools (2.1.2) 
Using bundler (1.0.21) 
Your bundle is complete! Use `bundle show [gemname]` to see where a bundled gem is installed.
MacBook-Pro:SiriProxy XXX$ rvmsudo ruby start.rb
Password:
start.rb:3: warning: variable $KCODE is no longer effective; ignored
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Starting SiriProxy on port 443..

iPhone 4S "Test Siri proxy"
Sorry, I don't understand 'Test Siri proxy'.

**Comment by plamoni** [comment]
SONY: If you don't get output on your SiriProxy console when you say
something to the phone, then that means your DNS is not routing your phone
to your computer.

jgst: You need to be using ruby 1.9.3. Check the readme for instructions.

-Pete

On Sat, Nov 26, 2011 at 7:49 PM, SONY5614 <
reply@reply.github.com

**Comment by plamoni** [comment]
Please open individual issues if you're having trouble. I think everyone in here has been taken care of.

**Comment by samukbg** [comment]
Hi plamoni, i'm have the same trouble as SONY: 

$ rvmsudo ruby start.rb 
start.rb:3: warning: variable $KCODE is no longer effective; ignored
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Starting SiriProxy on port 443..

nothing happens and when i try to say 'test siri proxy' it even let me say, it says: "Sorry, i'm having trouble...". 
I've put the ip address in iPhone's DNS settings and my dnsmasq starts without any error on my mac. My Xcode is version 4.2 if this helps anyway.
Thanks for any help.
