### ISSUE TITLE
Warning during siriproxy bundle

### ISSUE THREAD

**Issue by elvisimprsntr** [plamoni/SiriProxy#451]
root@raspberrypi:~/SiriProxy# siriproxy bundle
The source :gemcutter is deprecated because HTTP requests are insecure.
Please change your source to 'https://rubygems.org' if possible, or 'http://rubygems.org' if not.
Fetching gem metadata from http://rubygems.org/..........
Fetching gem metadata from http://rubygems.org/..
Resolving dependencies...
Using rake (10.0.3) 
Using CFPropertyList (2.1.2) 
Installing geocoder (1.1.6) 
Installing cora (0.0.4) 
Using eventmachine (1.0.0) 
Using uuidtools (2.1.3) 
Using siriproxy (0.4.0) from source at /usr/local/rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/siriproxy-0.4.0 
Using siriproxy-example (0.0.1) from source at ./plugins/siriproxy-example 
Using bundler (1.2.4) 
Your bundle is complete! Use `bundle show [gemname]` to see where a bundled gem is installed.

**Comment by plamoni** [comment]
Gonna look into this.

**Comment by NeMeSiStm** [comment]
yes i can confirm this

**Comment by elvisimprsntr** [comment]
Anyone bold enough to try Ruby 2.0.0rc2?

**Comment by plamoni** [comment]
Resolved in 9c7ca9d4831139d33d420661fbfff5fe2bcbeab8.
