### ISSUE TITLE
Plugin question

### ISSUE THREAD

**Issue by NeMeSiStm** [plamoni/SiriProxy#452]
read second post!

do there exists an plugin witch let me to "open" a specified php site on a command?

like:

'sonos Bathroom play' wich opens 'http://milkyway.merkur.local/sonos/index.php?zone=bathroom&do=TogglePlayStop' on the siriproxy server

the "opening" of this page won't show anything but sends a command on my sonos player
if not. can someone help me to make one?

**Comment by NeMeSiStm** [comment]
okay. i am trying this now on my own :-)

i made a plugin for siriproxy but it dosent work.

can i request Help?

https://github.com/NeMeSiStm/SiriProxy-2url

i am using this code to open urls

  listen_for /sonos raise the Volume in the Bathroom/i do
    open("http://xyz.merkur.local/sonos/index.php?zone=Bathroom&do=VolumeUp")
    say "Volume raised."  
    request_completed
  end

but siriproxy is already crashing afther i open siri on my iphone with this mesage:

[code]
SiriProxy up and running.
Create server for iPhone connection
/home/nemesis_tm/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/siriproxy-0.4.0/lib/siriproxy/plugin_manager.rb:22:in `require': cannot load such file -- siriproxy-2url (LoadError)
    from /home/nemesis_tm/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/siriproxy-0.4.0/lib/siriproxy/plugin_manager.rb:22:in`block in load_plugins'
    from /home/nemesis_tm/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/siriproxy-0.4.0/lib/siriproxy/plugin_manager.rb:14:in `each'
    from /home/nemesis_tm/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/siriproxy-0.4.0/lib/siriproxy/plugin_manager.rb:14:in`load_plugins'
    from /home/nemesis_tm/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/siriproxy-0.4.0/lib/siriproxy/plugin_manager.rb:8:in `initialize'
    from /home/nemesis_tm/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/siriproxy-0.4.0/lib/siriproxy.rb:22:in`new'
    from /home/nemesis_tm/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/siriproxy-0.4.0/lib/siriproxy.rb:22:in `block (2 levels) in initialize'
    from /home/nemesis_tm/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:1464:in`call'
    from /home/nemesis_tm/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:1464:in `event_callback'
    from /home/nemesis_tm/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in`run_machine'
    from /home/nemesis_tm/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/eventmachine-1.0.0/lib/eventmachine.rb:187:in `run'
    from /home/nemesis_tm/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/siriproxy-0.4.0/lib/siriproxy.rb:16:in`initialize'
    from /home/nemesis_tm/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/siriproxy-0.4.0/lib/siriproxy/command_line.rb:96:in `new'
    from /home/nemesis_tm/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/siriproxy-0.4.0/lib/siriproxy/command_line.rb:96:in`start_server'
    from /home/nemesis_tm/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/siriproxy-0.4.0/lib/siriproxy/command_line.rb:85:in `run_server'
    from /home/nemesis_tm/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/siriproxy-0.4.0/lib/siriproxy/command_line.rb:37:in`initialize'
    from /home/nemesis_tm/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/siriproxy-0.4.0/bin/siriproxy:6:in `new'
    from /home/nemesis_tm/.rvm/gems/ruby-1.9.3-p385@SiriProxy/gems/siriproxy-0.4.0/bin/siriproxy:6:in`<top (required)>'
    from /home/nemesis_tm/.rvm/gems/ruby-1.9.3-p385@SiriProxy/bin/siriproxy:23:in `load'
    from /home/nemesis_tm/.rvm/gems/ruby-1.9.3-p385@SiriProxy/bin/siriproxy:23:in`<main>'
nemesis_tm@linux-server:~/SiriProxy$ 
[/code]

suggesions?

**Comment by plamoni** [comment]
Looks like a problem with your config.yml file. Can you post it?

**Comment by NeMeSiStm** [comment]
-   - name: '2url'
-     git: 'git://github.com/NeMeSiStm/SiriProxy-2url.git'

sorry for closing and reopening....

**Comment by plamoni** [comment]
Can you post your config to a gist? (http://gist.github.com)

**Comment by NeMeSiStm** [comment]
https://gist.github.com/NeMeSiStm/4975075

ps.: i copied the example plugin and renamed it. added my 4 lines of code. nothing else :-)

**Comment by NeMeSiStm** [comment]
solved. filenaming was wrong
