### ISSUE TITLE
Caught in an endless spin!

### ISSUE THREAD

**Issue by ianperrin** [plamoni/SiriProxy#454]
Hi 

I'm experiencing the dreaded endless spinning on my device when using SiriProxy with my plugin.

I believe that the `request_completed` line is included, so are there any other known issues which might cause this to happen?

Would anyone be up for a little code review to help be determine where I am going wrong?

The plugin can be found here: https://github.com/ianperrin/siriproxy-lwrf/ and the related issue here: ianperrin/siriproxy-lwrf#1

Many thanks

Ian

**Comment by Deanmv** [comment]
Line 86 `request_completed` seems to be in a weird place? Try it at line 91?

**Comment by plamoni** [comment]
Closing this because it's not really an "issue"... Feel free to continue discussion.
