### ISSUE TITLE
Siriproxy over 3g (help for all)

### ISSUE THREAD

**Issue by massinegro204** [plamoni/SiriProxy#456]
Hi, I would like to create a guide for all like me, who want to use siriproxy on 3 g networks 
I saw that esoste not any effective guide to getting this on vpn. I have fully working siriproxy on my wifi network at 192.168.1.106 (static address of my wifi) I saw that I must set the iphone hosts file by adding at the end 

example.dindns.org guzzoni.apple.com(or should I insert a black type vpn vpn account ?) 

I have edited the file appleassistant file adding 
Hostname example.dyndns.org
now the problem you get when imposted the vpn (example.dyndns.org)on my Mac. This sets his ip to 192.168.1.100. but I don't know how to go forward. I would like to configure everything to then create a guide for all users, I need your help, I would ask you to correct my steps to get everything working. How can I do?

**Comment by plamoni** [comment]
You seem to be trying to make use of two different approaches to this problem: VPN and /etc/hosts + public service availability... You should stick with one of the two options. I think VPN is a better solution because it's far more secure and doesn't require you to jailbreak. Though it does route all your data through your home network (hope it's fast enough!).

If you do decide to write a guide, put it in the wiki. That'd be useful. Closing this "issue" for now because it's not really an issue. But feel free to continue discussion.

**Comment by massinegro204** [comment]
hello I wanted to thank you for answering, I know that maybe you're a busy but I would ask you if you want to give me a hand to make this guide to all the others (as it is the only issue under treated and explained),  I would a hand to you to be able to score all suula guide in order to put an end to this issue. I beg you to help me again. thanks
ok to be clear to all

iphone no jailbreak

1) create a network vpn solution (more secure)

the network vpn must be dyndns.org or for example vpn.vpnreactor?

2) solution

iphone jailbreak

edit the etc / hosts (with ifile)

adding at the end

(External ip) guzzoni.apple.com

or

example.dyndns.org guzzoni.apple.com

com.apple.assistant the file must be modified by adding the string?

<key> Hostname </ key>
<string> http://example.dyndns.org </ string>

There are another file to edit?

last question:

I used the command

rvmsudo. / siriproxy gencerts

to create my certificate

I read around that I have to follow these commands to create the certificate
 
genrsa openssl-des3-out ca.key 4096
openssl req-new-x509-days 365-key ca.key-out ca.crt
genrsa openssl-des3-out server.key 4096

(Enter your ip or hostname in "common name" .. important! - If you want to use an iPhone 4S use "guzzoni.apple.com")
openssl req-new-key server.key-out server.crt

openssl x509-req-days 365-in server.crt-CA ca.crt-cakey ca.key-01-set_serial out server.passless.crt
openssl rsa-in server.key-out server.key.insecure
mv server.key server.key.secure
mv server.key.insecure server.passless.key

 it is a good ?
