### ISSUE TITLE
how can i open a url by siriproxy?

### ISSUE THREAD

**Issue by NeMeSiStm** [plamoni/SiriProxy#457]
okay. i am gettin slowly crazy on this :-)

how can i open a url in my plugin? not on the iphone. it should be opened once on the siriproxy (so send a php command)

tryed a lot of things so far, last was

connection = Net::HTTP.new("http://192.168.11.50/sonos/index.php?zone=Badezimmer&do=Play")
connection.start

please help!

**Comment by laxman01** [comment]
Have you tried using osascript

**Comment by NeMeSiStm** [comment]
no, how would that look like?

**Comment by laxman01** [comment]
Tell application "Safari" to open "URL"

I think 
One sec

**Comment by laxman01** [comment]
osascript tell application "Safari" to open location "url"

**Comment by laxman01** [comment]
Try that

**Comment by NeMeSiStm** [comment]
yes but my SiriProxy is running on ubuntu there is no safari :/

**Comment by laxman01** [comment]
Oh sorry I have no idea how to do it on Ubuntu

**Comment by NeMeSiStm** [comment]
got it! i use the following:

@response = Net::HTTP.get(URI.parse("url"))

i don't know if i am using this command in the "right" way. but i does what i want :+1:
