### ISSUE TITLE
How to show images in answer but without Wolfram Alpha frame?

### ISSUE THREAD

**Issue by tommyd75** [plamoni/SiriProxy#458]
How do we get the answer to come back without the Wolfram Alpha paper style frame?
Is there any way to do this, so it just displays the image only?
Here is what I'm using....

listen_for /Show me the rear door camera/i do
   say "Here's the rear door camera" #say something to the user!
  object = SiriAddViews.new
  object.make_root(last_ref_id)
  answer = SiriAnswer.new("Rear Door Camera", [SiriAnswerLine.new('logo','http://192.168.1.1/cam1.jpg')])
  object.views << SiriAnswerSnippet.new([answer])
  send_object object
  request_completed 
end

**Comment by elvisimprsntr** [comment]
i have not seen anyone with a method that does not include the WA frame.
