### ISSUE TITLE
not updating addons

### ISSUE THREAD

**Issue by NeMeSiStm** [plamoni/SiriProxy#460]
Hello, i am working on a addon. but siriproxy update isn't updating my plugins. (Plugin is named siriproxy-whut)

https://gist.github.com/NeMeSiStm/5020717

the plugin is now on version 0.1.1 but the update command is still using 0.1.0

**Comment by Deanmv** [comment]
It will be dependent on the location in the config.yml file.

**Comment by NeMeSiStm** [comment]
my config.yml file:

https://gist.github.com/NeMeSiStm/fc35665796c9740fe0bb

**Comment by Deanmv** [comment]
Sounds stupid but have you pushed the updates to github? If not point it to he local folder in the config file.

**Comment by NeMeSiStm** [comment]
i think i "made" everything right. 
https://github.com/NeMeSiStm/SiriProxy-Whut
shows actual version. (0.1.2)

i don't know if thats something special but i am using the raspberrypi build. But it is still using the Master branch SiriProxy installation. the first installation worked well.

**Comment by elvisimprsntr** [comment]
Did you check the local copy the plugin gemspec file is still 0.1.0?

**Comment by elvisimprsntr** [comment]
closed due to inactivity
