### ISSUE TITLE
siriproxy not responding to test..  crashed

### ISSUE THREAD

**Issue by jrsphoto** [plamoni/SiriProxy#462]
first things first,  I'm on an iphone 5 with the latest ios. I have the key on my phone.  SiriProxy Server is on Ubuntu 12.10.  DNS is handled by my pfsense firewall's DNSForwarder..  seems to work. 

I see all kinds of traffic go by on the screen then an error and server crashes. ... something like this:

[Info - iPhone] Received Object: FinishSpeech
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: FinishSpeech
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: FinishSpeech
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: FinishSpeech
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: FinishSpeech
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: FinishSpeech
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: FinishSpeech
Create server for iPhone connection
140359570044576:error:02001018:system library:fopen:Too many open files:bss_file.c:398:fopen('/home/john/.siriproxy/server.passless.key','r')
140359570044576:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:400:
140359570044576:error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib:ssl_rsa.c:648:
ruby: ssl.cpp:166: SslContext_t::SslContext_t(bool, const string&, const string&): Assertion `e > 0' failed.

I've been playing with it for a few hours now and I have never been able to get siriproxy to respond any of the queries..  I did try 'siriproxy console' and that works as expected..

I also noticed that if I stop the server and restart it, I have to shut wifi off on my phone and turn it back on (I may just be able to renew the DHCP lease but its easier to just toggle wifi)

I'm stumped

-John

**Comment by jrsphoto** [comment]
I've been looking into this a bit more today and here is what I suspect.  I think:  dnsforward from my PFSENSE firewall is forwarding requests to my siriproxy server ubuntu 12.10 box.  I see these messages (among others) when my phone connects:

[Info - Plugin Manager] Plugins loaded: [#<SiriProxy::Plugin::Example:0x00000001978960 @manager=#<SiriProxy::PluginManager:0x0000000195ead8 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x000000019c74c0 @signature=817, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x000000019ce428>, @zip_stream=#Zlib::Deflate:0x000000019ce338, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins loaded: [#<SiriProxy::Plugin::Example:0x00000001a41b80 @manager=#<SiriProxy::PluginManager:0x000000019fb7c0 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000001a5d880 @signature=819, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000001a64838>, @zip_stream=#Zlib::Deflate:0x00000001a647e8, @consumed_ace=false, @name="iPhone", @ssled=false>

I then did some looking and ubuntu 12.04 and 12.10 both have dnsmasq installed by default.  Others may as well but I didn't look beyond 12.04.  With 12.10, dnsmasq has no config fie and instead passed everything through dbus (which admittedly I know nothing about).  It seems like I can turn off dnsmasq by commenting out the dns=dnsmasq line from /etc/NetworkManager/NetworkManager.conf file.  I tried this but the results are exactly the same.  No response from my SiriProxy  when I say, "Test Siri Proxy" but rather from apples servers...  I'll look more into this later.

**Comment by plamoni** [comment]
I think this is a DNS issue. Try updating to the latest code and see if that fixes the problem: `siriproxy update`. It should help. If not, report back.

**Comment by elvisimprsntr** [comment]
closed due to inactivity
