### ISSUE TITLE
Ruby 1.9.3-p392 Warnings

### ISSUE THREAD

**Issue by elvisimprsntr** [plamoni/SiriProxy#463]
I performed a clean install of RVM, Ruby, and SiriProxy which flagged the following warnings.  (NOTE: I did not get these same warnings when performing a clean install with p385) 

root@raspberrypi:~/SiriProxy# rake install
siriproxy 0.4.1 built to pkg/siriproxy-0.4.1.gem.
rake aborted!
Couldn't install gem, run `gem install /root/SiriProxy/pkg/siriproxy-0.4.1.gem' for more detailed output
/usr/local/rvm/gems/ruby-1.9.3-p392@global/gems/bundler-1.3.0/lib/bundler/gem_helper.rb:68:in`install_gem'
/usr/local/rvm/gems/ruby-1.9.3-p392@global/gems/bundler-1.3.0/lib/bundler/gem_helper.rb:43:in `block in install'
/usr/local/rvm/gems/ruby-1.9.3-p392@global/bin/ruby_noexec_wrapper:14:in`eval'
/usr/local/rvm/gems/ruby-1.9.3-p392@global/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => install
(See full trace by running task with --trace)

root@raspberrypi:~/SiriProxy# gem install /root/SiriProxy/pkg/siriproxy-0.4.1.gem
Fetching: CFPropertyList-2.1.2.gem (100%)
Fetching: eventmachine-1.0.0.gem (100%)
Building native extensions.  This could take a while...
Fetching: uuidtools-2.1.3.gem (100%)
Successfully installed CFPropertyList-2.1.2
Successfully installed eventmachine-1.0.0
Successfully installed uuidtools-2.1.3
Successfully installed siriproxy-0.4.1
4 gems installed
Installing ri documentation for CFPropertyList-2.1.2...
Installing ri documentation for eventmachine-1.0.0...
Installing ri documentation for uuidtools-2.1.3...
Installing ri documentation for siriproxy-0.4.1...
Installing RDoc documentation for CFPropertyList-2.1.2...
Installing RDoc documentation for eventmachine-1.0.0...
Installing RDoc documentation for uuidtools-2.1.3...
Installing RDoc documentation for siriproxy-0.4.1...
root@raspberrypi:~/SiriProxy#

**Comment by plamoni** [comment]
Hmm.. Looks like it worked when you did the `gem install`... Not sure what happened there.
