### ISSUE TITLE
Ruby 2.0.0-p0 SiriProxy will not install

### ISSUE THREAD

**Issue by elvisimprsntr** [plamoni/SiriProxy#464]
Performed a clean install of RVM, Ruby, and attempted SiriProxy

NOTE: Two new packages are required for 2.0.0: apt-get install libgdbm-dev libffi-dev -y

root@raspberrypi:~# rvm use 2.0.0 --default
Using /usr/local/rvm/gems/ruby-2.0.0-p0
root@raspberrypi:~# pwd
/root
root@raspberrypi:~# git clone git://github.com/plamoni/SiriProxy.git
Cloning into 'SiriProxy'...
remote: Counting objects: 859, done.
remote: Compressing objects: 100% (324/324), done.
remote: Total 859 (delta 512), reused 789 (delta 465)
Receiving objects: 100% (859/859), 149.12 KiB, done.
Resolving deltas: 100% (512/512), done.
root@raspberrypi:~# cd SiriProxy/
 ==============================================================================
 = NOTICE                                                                     =
 ==============================================================================
 = RVM has encountered a new or modified .rvmrc file in the current directory =
 = This is a shell script and therefore may contain any shell commands.       =
 =                                                                            =
 = Examine the contents of this file carefully to be sure the contents are    =
 = safe before trusting it! ( Choose v[iew] below to view the contents )      =
 ==============================================================================
Do you wish to trust this .rvmrc file? (/root/SiriProxy/.rvmrc)
y[es], n[o], v[iew], c[ancel]> y
ruby-1.9.3-p392 is not installed.
To install do: 'rvm install ruby-1.9.3-p392'

**Comment by plamoni** [comment]
I haven't tried using Ruby 2.0.0 with SiriProxy yet. I will need to work on that when I get some time. For now, you'll need to use ruby 1.9.3.

**Comment by plamoni** [comment]
Tested with 2.0.0 and it works fine. You can go ahead and delete that `.rvmrc` file and it will quit complaining about the ruby version.
