### ISSUE TITLE
Strange errors with 'cora'

### ISSUE THREAD

**Issue by ghost** [plamoni/SiriProxy#47]
Good evening,

I've tried to install SiriProxy on my Mac as described here but I'm experiencing several problems. What i tried to do was to start SiriProxy with rvmsudo but iit returned this one:

noname:SiriProxy philipp$ rvmsudo ruby start.rb
Password:
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
/Users/philipp/Downloads/SiriProxy/cora/ruby/1.8/bundler/gems/cora-05db5f19f374/lib/cora.rb:2:in `require': /Users/philipp/Downloads/SiriProxy/cora/ruby/1.8/bundler/gems/cora-05db5f19f374/lib/cora/plugin.rb:11: odd number list for Hash (SyntaxError)
        block: block,
              ^
/Users/philipp/Downloads/SiriProxy/cora/ruby/1.8/bundler/gems/cora-05db5f19f374/lib/cora/plugin.rb:11: syntax error, unexpected ':', expecting '}'
        block: block,
              ^
/Users/philipp/Downloads/SiriProxy/cora/ruby/1.8/bundler/gems/cora-05db5f19f374/lib/cora/plugin.rb:12: syntax error, unexpected ':', expecting '='
        within_state: ([options[:within_state]].flatten)
                     ^
/Users/philipp/Downloads/SiriProxy/cora/ruby/1.8/bundler/gems/cora-05db5f19f374/lib/cora/plugin.rb:13: syntax error, unexpected '}', expecting kEND
/Users/philipp/Downloads/SiriProxy/cora/ruby/1.8/bundler/gems/cora-05db5f19f374/lib/cora/plugin.rb:61: syntax error, unexpected ':', expecting ')'
    manager.respond(question, prompt_for_response: true)
                                                  ^
/Users/philipp/Downloads/SiriProxy/cora/ruby/1.8/bundler/gems/cora-05db5f19f374/lib/cora/plugin.rb:78: syntax error, unexpected $end, expecting kEND
    from /Users/philipp/Downloads/SiriProxy/cora/ruby/1.8/bundler/gems/cora-05db5f19f374/lib/cora.rb:2
    from ./siri_proxy/plugin.rb:1:in`require'
    from ./siri_proxy/plugin.rb:1
    from start.rb:17:in `require'
    from start.rb:17
noname:SiriProxy philipp$ 

Can anybode help me?

**Comment by plamoni** [comment]
We no longer support Ruby 1.8, sorry. Switch to 1.9.3.

-Pete

Sent from my iPhone

On Nov 25, 2011, at 12:45 PM, Eliminatrix
reply@reply.github.com
wrote:
