### ISSUE TITLE
Installing plugins

### ISSUE THREAD

**Issue by matthewwatson70** [plamoni/SiriProxy#470]
Can someone tell me how to install new plugins on mac

**Comment by plamoni** [comment]
Same way as on a Linux machine: Modify your `config.yml`. There are plenty of examples in the comments of the `config.yml`, just find a plugin you like (check the [Wiki](https://github.com/plamoni/SiriProxy/wiki/Plugins)) and modify your `config.yml`... Generally the plugins will give instructions for installation in their `README.md`.
