### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by matthewwatson70** [plamoni/SiriProxy#471]
rvmsudo siriproxy server
/Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.4.4/lib/siriproxy/plugin_manager.rb:23:in `const_get': wrong constant name computer (NameError)
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.4.4/lib/siriproxy/plugin_manager.rb:23:in`block in load_plugins'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.4.4/lib/siriproxy/plugin_manager.rb:14:in `each'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.4.4/lib/siriproxy/plugin_manager.rb:14:in`load_plugins'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.4.4/lib/siriproxy/plugin_manager.rb:8:in `initialize'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.4.4/lib/siriproxy/command_line.rb:207:in`new'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.4.4/lib/siriproxy/command_line.rb:207:in `init_plugins'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.4.4/lib/siriproxy/command_line.rb:88:in`run_server'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.4.4/lib/siriproxy/command_line.rb:39:in `initialize'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.4.4/bin/siriproxy:6:in`new'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.4.4/bin/siriproxy:6:in `<top (required)>'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/bin/siriproxy:19:in`load'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/bin/siriproxy:19:in `<main>'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/bin/ruby_noexec_wrapper:14:in`eval'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/bin/ruby_noexec_wrapper:14:in `<main>'

**Comment by plamoni** [comment]
Looks like a problem with your `config.yml`. Can you post your `config.yml` as a [gist](http://gist.github.com/)?

**Comment by matthewwatson70** [comment]
```
listen: 0.0.0.0
port: 443
log_level: 1
plugins:
    # NOTE: run bundle after changing plugin configurations to update required gems

    - name: 'Example'
      path: './plugins/siriproxy-example' 

    - name: 'computer'
      git: 'git://github.com/IMcD23/siriproxy-computer.git'


         # - name: 'Thermostat'
    #   git: 'git://github.com/plamoni/SiriProxy-Thermostat.git'
    #   host: '192.168.2.71' 

    # - name: 'Twitter'
    #   path: './plugins/siriproxy-twitter' # path works just like specifing in gemfile 
    #   consumer_key: "YOUR_KEY" 
    #   consumer_secret: "YOUR_SECRET"
    #   oauth_token: "YOUR_TOKEN" 
    #   oauth_token_secret: "YOUR_TOKEN_SECRET"

    # Note: Eliza should not be run with other plugins
    # - name: 'Eliza'
    #   path: './plugins/siriproxy-eliza' # path works just like specifing in gemfile 

    # Below are not actual plugins, just further example of config options

    # - SimplePlugin # simple syntax for plugins that are in rubygems and have no config 

    # - name: 'AnotherPlugin'
    #   git: 'git://github.com/netpro2k/SiriProxy-AnotherPlugin.git' # git works just like specifying in Gemfile
```

**Comment by Raggyx** [comment]
Hey
You have to capitalize the plugin class name "Computer" (case sensitive)

**Comment by matthewwatson70** [comment]
Is anything wrong with this config.yml 

```
listen: 0.0.0.0
port: 443
log_level: 1
plugins:
    # NOTE: run bundle after changing plugin configurations to update required gems

    - name: 'Example'
      path: './plugins/siriproxy-example' 

    - name: 'Computer'
      git: 'git://github.com/IMcD23/siriproxy-computer.git'
```

**Comment by Raggyx** [comment]
now it looks like everything is correct

**Comment by matthewwatson70** [comment]
i get errors when starting 

```
Starting SiriProxy on 0.0.0.0:443..
/Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/eventmachine-1.0.3/lib/eventmachine.rb:526:in `start_tcp_server': no acceptor (port is in use or requires root privileges) (RuntimeError)
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/eventmachine-1.0.3/lib/eventmachine.rb:526:in `start_server'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.4.4/lib/siriproxy.rb:20:in `block in initialize'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `call'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.4.4/lib/siriproxy.rb:16:in `initialize'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.4.4/lib/siriproxy/command_line.rb:100:in `new'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.4.4/lib/siriproxy/command_line.rb:100:in `start_server'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.4.4/lib/siriproxy/command_line.rb:89:in `run_server'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.4.4/lib/siriproxy/command_line.rb:39:in `initialize'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.4.4/bin/siriproxy:6:in `new'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.4.4/bin/siriproxy:6:in `<top (required)>'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/bin/siriproxy:19:in `load'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/bin/siriproxy:19:in `<main>'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/bin/ruby_noexec_wrapper:14:in `eval'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/bin/ruby_noexec_wrapper:14:in `<main>'
```

**Comment by Raggyx** [comment]
this is because you didnt set the ip (listen: 0.0.0.0)
you could install the siriproxy from jimmykane https://github.com/jimmykane/The-Three-Little-Pigs-Siri-Proxy
which is more recent

**Comment by plamoni** [comment]
Actually, it's because you're not running as root. Do the following:

Update SiriProxy: 

```
siriproxy update
```

Then run SiriProxy like so:

```
rvmsudo siriproxy server -u nobody
```

You can alternatively add `user: nobody` to the top of your `config.yml` and just run `rvmsudo siriproxy server`

**Comment by matthewwatson70** [comment]
i did that and i got this 

```
    [Info - Configuration] Loading plugins -- If any fail to load, run `siriproxy bundle` (not `bundle install`) to resolve.
    [Info - Server] Starting SiriProxy on 0.0.0.0:443...
    /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/eventmachine-1.0.3/lib/eventmachine.rb:526:in `start_tcp_server': no acceptor (port is in use or requires root privileges) (RuntimeError)
        from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/eventmachine-1.0.3/lib/eventmachine.rb:526:in `start_server'
        from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.5.2/lib/siriproxy.rb:28:in `block in initialize'
        from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `call'
        from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
        from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
        from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.5.2/lib/siriproxy.rb:17:in `initialize'
        from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.5.2/lib/siriproxy/command_line.rb:106:in `new'
        from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.5.2/lib/siriproxy/command_line.rb:106:in `start_server'
        from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.5.2/lib/siriproxy/command_line.rb:90:in `run_server'
        from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.5.2/lib/siriproxy/command_line.rb:39:in `initialize'
        from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.5.2/bin/siriproxy:6:in `new'
        from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.5.2/bin/siriproxy:6:in `<top (required)>'
        from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/bin/siriproxy:19:in `load'
        from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/bin/siriproxy:19:in `<main>'
        from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/bin/ruby_noexec_wrapper:14:in `eval'
        from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/bin/ruby_noexec_wrapper:14:in `<main>'
```

**Comment by matthewwatson70** [comment]
Here is my config.yml

https://gist.github.com/matthewwatson70/197d9130475905b71ffd

**Comment by plamoni** [comment]
If you're running using `rvmsudo` and still getting the `no acceptor` error, it's probably because something (Apache? maybe some other web server?) is using port 443.

If you're running on a Mac (which seems to be the case), make sure "Web Sharing" is off in the "Sharing" section of your System tools.

**Comment by plamoni** [comment]
You can also try switching to another port if you want to be sure it's a port conflict. Run `rvmsudo siriproxy server -p 444` and see if it starts up properly. If so, then you need to disable whatever is using port 443. If that still fails, then there's something else at work, but I don't think it will fail.

**Comment by matthewwatson70** [comment]
ok it starts how do i find out whats on port 443

**Comment by plamoni** [comment]
I think you can do it with `sudo lsof -i`, but I can't remember exactly how. My guess is that it's apache.

**Comment by matthewwatson70** [comment]
ok i did that where do i look for the port

**Comment by plamoni** [comment]
Look for something that's listening on `:https` or `:443`. It's probably called `httpd` (which is Apache). As I said, if you're on a Mac and you're running Web Sharing, it might be using up port 443. So just disable Web Sharing.

**Comment by matthewwatson70** [comment]
i used the sudo lsof -i :443 | grep LISTEN command and i got this.

ruby      1866        nobody    7u  IPv4 0x51ac9090f24cba2d      0t0  TCP *:https (LISTEN) 

Then i try sudo killall ruby and it says no matching processes were found

**Comment by plamoni** [comment]
You can `sudo kill -9 1866`... That will work...

**Comment by matthewwatson70** [comment]
Thank you so much !!!

**Comment by plamoni** [comment]
Did that solve your issue?

**Comment by matthewwatson70** [comment]
it worked one time then the second time i tried to start it i got 

rvmsudo siriproxy server
[Info - Configuration] Loading plugins -- If any fail to load, run `siriproxy bundle` (not `bundle install`) to resolve.
[Notice - Server] ======================= WARNING: Running as root =============================
[Notice - Server] You should use -l or the config.yml to specify and non-root user to run under
[Notice - Server] Running the server as root is dangerous.
[Notice - Server] ==============================================================================
[Info - Server] Starting SiriProxy on 0.0.0.0:443...
/Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/eventmachine-1.0.3/lib/eventmachine.rb:526:in `start_tcp_server': no acceptor (port is in use or requires root privileges) (RuntimeError)
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/eventmachine-1.0.3/lib/eventmachine.rb:526:in`start_server'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.5.2/lib/siriproxy.rb:28:in `block in initialize'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in`call'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in`run'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.5.2/lib/siriproxy.rb:17:in `initialize'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.5.2/lib/siriproxy/command_line.rb:106:in`new'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.5.2/lib/siriproxy/command_line.rb:106:in `start_server'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.5.2/lib/siriproxy/command_line.rb:90:in`run_server'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.5.2/lib/siriproxy/command_line.rb:39:in `initialize'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.5.2/bin/siriproxy:6:in`new'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.5.2/bin/siriproxy:6:in `<top (required)>'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/bin/siriproxy:19:in`load'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/bin/siriproxy:19:in `<main>'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/bin/ruby_noexec_wrapper:14:in`eval'
    from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/bin/ruby_noexec_wrapper:14:in `<main>' 

i got the error again and i tried the lsof command and it said nothing was running on port 443. Is it safe to use ruby 2.0.0-po with siriproxy

**Comment by plamoni** [comment]
You're running two copies at once. You must kill the first before starting
the second.

-Pete

On Mar 11, 2013, at 10:40 PM, matthewwatson70 notifications@github.com
wrote:

it worked one time then the second time i tried to start it i got

rvmsudo siriproxy server
[Info - Configuration] Loading plugins -- If any fail to load, run siriproxy
bundle (not bundle install) to resolve.

# [Notice - Server] ======================= WARNING: Running as root

[Notice - Server] You should use -l or the config.yml to specify and
non-root user to run under
[Notice - Server] Running the server as root is dangerous.

# [Notice - Server]

[Info - Server] Starting SiriProxy on 0.0.0.0:443...
/Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/eventmachine-1.0.3/lib/eventmachine.rb:526:in
start_tcp_server': no acceptor (port is in use or requires root privileges)
(RuntimeError)
from
/Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/eventmachine-1.0.3/lib/eventmachine.rb:526:in
start_server'
from
/Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.5.2/lib/siriproxy.rb:28:in
block in initialize'
from
/Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in
call'
from
/Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in
run_machine'
from
/Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in
run'
from
/Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.5.2/lib/siriproxy.rb:17:in
initialize'
from
/Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.5.2/lib/siriproxy/command_line.rb:106:in
new'
from
/Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.5.2/lib/siriproxy/command_line.rb:106:in
start_server'
from
/Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.5.2/lib/siriproxy/command_line.rb:90:in
run_server'
from
/Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.5.2/lib/siriproxy/command_line.rb:39:in
initialize'
from
/Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.5.2/bin/siriproxy:6:in
new'
from
/Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/gems/siriproxy-0.5.2/bin/siriproxy:6:in
<top (required)>'
from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/bin/siriproxy:19:inload'
from /Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/bin/siriproxy:19:in
<main>'
from
/Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/bin/ruby_noexec_wrapper:14:in
eval'
from
/Users/MatthewWatson/.rvm/gems/ruby-1.9.3-p385/bin/ruby_noexec_wrapper:14:in
`'

i got the error again and i tried the lsof command and it said nothing was
running on port 443. Is it safe to use ruby 2.0.0-po with siriproxy

—
Reply to this email directly or view it on
GitHubhttps://github.com/plamoni/SiriProxy/issues/471#issuecomment-14759484
.

**Comment by matthewwatson70** [comment]
can you kill it by just closing the terminal and kill the process when it asks you

**Comment by matthewwatson70** [comment]
nevermind i got it i did sudo killall siriproxy and it works. Is it safe to use ruby 2.0.0 with siriproxy

**Comment by matthewwatson70** [comment]
can you give me instructions on how to vpn the server so i can use siriproxy on 3G

**Comment by plamoni** [comment]
1) I wouldn't count on that. Use `Ctrl-C`
2) That also kind of works
3) I'd rather not, I try not to encourage that sort of thing. If you can figure it out, go for it, but there are security implications you need to understand before opening things up to a wider area.

**Comment by matthewwatson70** [comment]
ok thanks
