### ISSUE TITLE
gem install siriproxy warnings

### ISSUE THREAD

**Issue by elvisimprsntr** [plamoni/SiriProxy#473]
I get the following errors when installing siriproxy using the new method.  Duplicated the problem on two different installations.  Obviously not a specific siriproxy problem, but maybe use the options to not install docs

http://charles.lescampeurs.org/2008/11/21/install-gem-without-documentation

oot@raspberrypi:~# gem install siriproxy
Fetching: CFPropertyList-2.1.2.gem (100%)
Successfully installed CFPropertyList-2.1.2
Fetching: eventmachine-1.0.3.gem (100%)
Building native extensions.  This could take a while...
Successfully installed eventmachine-1.0.3
Fetching: uuidtools-2.1.3.gem (100%)
Successfully installed uuidtools-2.1.3
Fetching: geocoder-1.1.6.gem (100%)
Successfully installed geocoder-1.1.6
Fetching: cora-0.0.4.gem (100%)
Successfully installed cora-0.0.4
Fetching: rainbow-1.1.4.gem (100%)
Successfully installed rainbow-1.1.4
Fetching: rexec-1.5.1.gem (100%)
Successfully installed rexec-1.5.1
Fetching: rubydns-0.5.4.gem (100%)
Successfully installed rubydns-0.5.4
Fetching: siriproxy-0.5.2.gem (100%)
Successfully installed siriproxy-0.5.2
Parsing documentation for CFPropertyList-2.1.2
**unable to convert "\xD1" from ASCII-8BIT to UTF-8 for lib/lala.plist, skipping** 
Installing ri documentation for CFPropertyList-2.1.2
Parsing documentation for eventmachine-1.0.3
**unable to convert "\xC0" from ASCII-8BIT to UTF-8 for lib/fastfilereaderext.so, skipping** 
**unable to convert "\xF4" from ASCII-8BIT to UTF-8 for lib/rubyeventmachine.so, skipping** 
Installing ri documentation for eventmachine-1.0.3
Parsing documentation for uuidtools-2.1.3
Installing ri documentation for uuidtools-2.1.3
Parsing documentation for geocoder-1.1.6
Installing ri documentation for geocoder-1.1.6
Parsing documentation for cora-0.0.4
Installing ri documentation for cora-0.0.4
Parsing documentation for rainbow-1.1.4
Installing ri documentation for rainbow-1.1.4
Parsing documentation for rexec-1.5.1
Installing ri documentation for rexec-1.5.1
Parsing documentation for rubydns-0.5.4
Installing ri documentation for rubydns-0.5.4
Parsing documentation for siriproxy-0.5.2
Installing ri documentation for siriproxy-0.5.2
9 gems installed
root@raspberrypi:~#

**Comment by plamoni** [comment]
Does the install actually work? These looks more like warnings than errors.

**Comment by elvisimprsntr** [comment]
Yes it works.  The link provides tip how to configure your gem to not install docs or specify from a command line.

**Comment by elvisimprsntr** [comment]
not a problem specifically with siriproxy
