### ISSUE TITLE
DNS server is not running yet...

### ISSUE THREAD

**Issue by psihacker** [plamoni/SiriProxy#475]
Hi, 

i´m trying to install siriproxy 0.5.0 on a fresh ubuntu 12.10. (i´m new to linux ;-)
I already have it running under OSX but wanted it inside a VM (Fusion; bridged mode). 

When i start i only get: 

rvmsudo siriproxy server -d 192.168.1.15
...
...
DNS server is not running yet, waiting 1 second...
Either you´re not root or tcp/udp port 53 is in use. DNS Server is disabled
Siriproxy up and running.

What´s the problem?

**Comment by Deanmv** [comment]
`Either you´re not root or tcp/udp port 53 is in use.`

You are root (as you used rvmsudo) so port 53 is in use!

**Comment by elvisimprsntr** [comment]
Check to see if you have dnsmasq running.  

'ps -ef | grep -i dnsmasq'

If you do turn it off

'sh /etc/init.d/dnsmasq stop'

If you launch SiriProxy without a problem, then remove dnsmasq 

'apt-get purge dnsmasq'.

**Comment by psihacker** [comment]
@deanmv
i knew this would happen ;-) 
@elvis 
thx! i'll try tonight!

**Comment by elvisimprsntr** [comment]
If its not dnsmasq then you might have unintentionally selected DNS server when you set up Ubuntu.  

Tips to find out what process is using the port. 
http://www.cyberciti.biz/faq/what-process-has-open-linux-port/

**Comment by plamoni** [comment]
You can also try `sudo lsof -i :53 | grep LISTEN` -- that will tell you what, if anything, is listed on port 53.

**Comment by psihacker** [comment]
thanks!
here some more infos

ps -ef | grep -i dnsmasq
nobody    1614   770  0 19:23 ?        00:00:00 /usr/sbin/dnsmasq --no-resolv --keep-in-foreground --no-hosts --bind-interfaces --pid-file=/var/run/sendsigs.omit.d/network-manager.dnsmasq.pid --listen-address=127.0.1.1 --conf-file=/var/run/nm-dns-dnsmasq.conf --cache-size=0 --proxy-dnssec --enable-dbus=org.freedesktop.NetworkManager.dnsmasq --conf-dir=/etc/NetworkManager/dnsmasq.d
1000     23993  2120  0 20:27 pts/1    00:00:00 grep --color=auto -i dnsmasq

sudo lsof -i :53 | grep LISTEN
dnsmasq 1614 nobody    5u  IPv4  10585      0t0  TCP ubuntu-dO:domain (LISTEN)

so i guess dnsmasq is running? 

sh /etc/init.d/dnsmasq stop
sh: 0: Can't open /etc/init.d/dnsmasq

**Comment by plamoni** [comment]
```
sudo kill 1614
```

You probably want to disable dnsmasq from starting on boot. That's a bit out of scope for this forum, though. Unless anyone knows off the top of their head and wants to share.

**Comment by elvisimprsntr** [comment]
Uninstall dnsmasq the remove the config files

'apt-get purge dnsmasq'

**Comment by elvisimprsntr** [comment]
Did you point your iOS device DNS entry to your SP server and install the ca.pem file on your iOS device?

Also Siri is know to leak over the cell data connection.  Turn it off.   It may take. Few launch attempts to connect to SiriProxy the first time.

**Comment by psihacker** [comment]
my fault! i already deleted the post ;-) i used the old ca.pem (from my osx installation - doh!)

getting some error while starting.. but IT WORKS =) 
big thx to all helpers! and...

i <3 siriproxy!

**Comment by elvisimprsntr** [comment]
Congrats.  I've never has 100% success installing and running everything as a user.  Always seems to be a lot easier as root even though Pete doesn't recommend it.
