### ISSUE TITLE
403 Forbiden

### ISSUE THREAD

**Issue by JBX028** [plamoni/SiriProxy#48]
Hi,

First of all, thanks a lot for this awesom project. 

I did the setting for my windows based PC and even if i can see the trafic with Siri i have an issue.
Once the sentence is recognised, siri loop without ending.

On my iPhone, when the DNS is set, i cannot go to any web page (403 forbiden). This is the reason why ? do you know how to fix the issue (wrong certificat ?)

FYI, i created a script to let my Karotz via his TTS api (http://dev.karotz.com/) to repeat what Siri is saying.

Thanks in advance

Johnny Baillargeaux (from France)

**Comment by plamoni** [comment]
Sounds like your DNS isn't set up right. I'd look into debugging that.
Sounds like it's routing all domains to your computer or something.

-Pete

On Fri, Nov 25, 2011 at 4:19 PM, JBX028 <
reply@reply.github.com

**Comment by JBX028** [comment]
Thanks for your quick reply.

I uses the followinf dns : http://pastebin.com/RmnvxvHu
And looks like the proxy is running because i can see the trafic.

I will anyway investigate in that direction.

Bye

**Comment by netpro2k** [comment]
Sounds like your dnsmasq config is wrong. What does your config file look like?

On Nov 25, 2011, at 5:19 PM, JBX028
reply@reply.github.com
wrote:

**Comment by plamoni** [comment]
We don't support people using alternate methods for DNS. Sorry, you're on your own on this one.
