### ISSUE TITLE
Error after starting siriproxy

### ISSUE THREAD

**Issue by lchansen** [plamoni/SiriProxy#481]
Got siriproxy server running, but right when i activate siri on my iPhone 5, this error appears:
I'm fairly new to this, so im not sure whats going on

E, [2013-03-14T12:53:31.476242 #2151] ERROR -- : Exception thrown while processing st14p06sa.guzzoni-apple.com.akadns.net Resolv::DNS::Resource::IN::A!
E, [2013-03-14T12:53:31.476393 #2151] ERROR -- : NoMethodError: undefined method `respond!' for #<MatchData "guzzoni-apple.com">
E, [2013-03-14T12:53:31.476495 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.2/lib/siriproxy/dns.rb:57:in`block (2 levels) in run'
E, [2013-03-14T12:53:31.476547 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/server.rb:61:in `[]'
E, [2013-03-14T12:53:31.476583 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/server.rb:61:in`call'
E, [2013-03-14T12:53:31.476616 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/server.rb:166:in `block (2 levels) in process'
E, [2013-03-14T12:53:31.476650 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/server.rb:164:in`catch'
E, [2013-03-14T12:53:31.476682 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/server.rb:164:in `block in process'
E, [2013-03-14T12:53:31.476716 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/server.rb:161:in`each'
E, [2013-03-14T12:53:31.476748 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/server.rb:161:in `process'
E, [2013-03-14T12:53:31.476781 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/transaction.rb:76:in`process'
E, [2013-03-14T12:53:31.476814 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/server.rb:230:in `block (2 levels) in process_query'
E, [2013-03-14T12:53:31.476847 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/server.rb:238:in`call'
E, [2013-03-14T12:53:31.476879 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/server.rb:238:in `process_query'
E, [2013-03-14T12:53:31.476911 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/handler.rb:41:in`process'
E, [2013-03-14T12:53:31.476944 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/handler.rb:66:in `receive_data'
E, [2013-03-14T12:53:31.476978 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in`run_machine'
E, [2013-03-14T12:53:31.477011 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
E, [2013-03-14T12:53:31.477044 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.2/lib/siriproxy.rb:17:in`initialize'
E, [2013-03-14T12:53:31.477077 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.2/lib/siriproxy/command_line.rb:106:in `new'
E, [2013-03-14T12:53:31.477109 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.2/lib/siriproxy/command_line.rb:106:in`start_server'
E, [2013-03-14T12:53:31.477141 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.2/lib/siriproxy/command_line.rb:90:in `run_server'
E, [2013-03-14T12:53:31.477174 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.2/lib/siriproxy/command_line.rb:39:in`initialize'
E, [2013-03-14T12:53:31.477206 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.2/bin/siriproxy:6:in `new'
E, [2013-03-14T12:53:31.477238 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.2/bin/siriproxy:6:in`<top (required)>'
E, [2013-03-14T12:53:31.477270 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/bin/siriproxy:19:in `load'
E, [2013-03-14T12:53:31.477302 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/bin/siriproxy:19:in`<main>'
E, [2013-03-14T12:53:31.477333 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/bin/ruby_noexec_wrapper:14:in `eval'
E, [2013-03-14T12:53:31.477364 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/bin/ruby_noexec_wrapper:14:in`<main>'
E, [2013-03-14T12:53:32.500724 #2151] ERROR -- : Exception thrown while processing st14p06sa.guzzoni-apple.com.akadns.net Resolv::DNS::Resource::IN::A!
E, [2013-03-14T12:53:32.500850 #2151] ERROR -- : NoMethodError: undefined method `respond!' for #<MatchData "guzzoni-apple.com">
E, [2013-03-14T12:53:32.501005 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.2/lib/siriproxy/dns.rb:57:in`block (2 levels) in run'
E, [2013-03-14T12:53:32.501069 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/server.rb:61:in `[]'
E, [2013-03-14T12:53:32.501156 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/server.rb:61:in`call'
E, [2013-03-14T12:53:32.501242 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/server.rb:166:in `block (2 levels) in process'
E, [2013-03-14T12:53:32.501319 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/server.rb:164:in`catch'
E, [2013-03-14T12:53:32.501394 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/server.rb:164:in `block in process'
E, [2013-03-14T12:53:32.501469 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/server.rb:161:in`each'
E, [2013-03-14T12:53:32.501546 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/server.rb:161:in `process'
E, [2013-03-14T12:53:32.501619 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/transaction.rb:76:in`process'
E, [2013-03-14T12:53:32.501693 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/server.rb:230:in `block (2 levels) in process_query'
E, [2013-03-14T12:53:32.501766 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/server.rb:238:in`call'
E, [2013-03-14T12:53:32.501839 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/server.rb:238:in `process_query'
E, [2013-03-14T12:53:32.501911 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/handler.rb:41:in`process'
E, [2013-03-14T12:53:32.501985 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/handler.rb:66:in `receive_data'
E, [2013-03-14T12:53:32.502058 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in`run_machine'
E, [2013-03-14T12:53:32.502129 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
E, [2013-03-14T12:53:32.502201 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.2/lib/siriproxy.rb:17:in`initialize'
E, [2013-03-14T12:53:32.502272 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.2/lib/siriproxy/command_line.rb:106:in `new'
E, [2013-03-14T12:53:32.502345 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.2/lib/siriproxy/command_line.rb:106:in`start_server'
E, [2013-03-14T12:53:32.502453 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.2/lib/siriproxy/command_line.rb:90:in `run_server'
E, [2013-03-14T12:53:32.502527 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.2/lib/siriproxy/command_line.rb:39:in`initialize'
E, [2013-03-14T12:53:32.502600 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.2/bin/siriproxy:6:in `new'
E, [2013-03-14T12:53:32.502672 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.2/bin/siriproxy:6:in`<top (required)>'
E, [2013-03-14T12:53:32.502744 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/bin/siriproxy:19:in `load'
E, [2013-03-14T12:53:32.502815 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/bin/siriproxy:19:in`<main>'
E, [2013-03-14T12:53:32.502887 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/bin/ruby_noexec_wrapper:14:in `eval'
E, [2013-03-14T12:53:32.502958 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/bin/ruby_noexec_wrapper:14:in`<main>'
E, [2013-03-14T12:53:35.510293 #2151] ERROR -- : Exception thrown while processing st14p06sa.guzzoni-apple.com.akadns.net Resolv::DNS::Resource::IN::A!
E, [2013-03-14T12:53:35.510465 #2151] ERROR -- : NoMethodError: undefined method `respond!' for #<MatchData "guzzoni-apple.com">
E, [2013-03-14T12:53:35.510625 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.2/lib/siriproxy/dns.rb:57:in`block (2 levels) in run'
E, [2013-03-14T12:53:35.510688 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/server.rb:61:in `[]'
E, [2013-03-14T12:53:35.510774 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/server.rb:61:in`call'
E, [2013-03-14T12:53:35.510852 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/server.rb:166:in `block (2 levels) in process'
E, [2013-03-14T12:53:35.510928 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/server.rb:164:in`catch'
E, [2013-03-14T12:53:35.511002 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/server.rb:164:in `block in process'
E, [2013-03-14T12:53:35.511078 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/server.rb:161:in`each'
E, [2013-03-14T12:53:35.511154 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/server.rb:161:in `process'
E, [2013-03-14T12:53:35.511230 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/transaction.rb:76:in`process'
E, [2013-03-14T12:53:35.511306 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/server.rb:230:in `block (2 levels) in process_query'
E, [2013-03-14T12:53:35.511378 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/server.rb:238:in`call'
E, [2013-03-14T12:53:35.511450 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/server.rb:238:in `process_query'
E, [2013-03-14T12:53:35.511522 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/handler.rb:41:in`process'
E, [2013-03-14T12:53:35.511596 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/rubydns-0.6.0/lib/rubydns/handler.rb:66:in `receive_data'
E, [2013-03-14T12:53:35.511667 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in`run_machine'
E, [2013-03-14T12:53:35.511741 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
E, [2013-03-14T12:53:35.511814 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.2/lib/siriproxy.rb:17:in`initialize'
E, [2013-03-14T12:53:35.511886 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.2/lib/siriproxy/command_line.rb:106:in `new'
E, [2013-03-14T12:53:35.511959 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.2/lib/siriproxy/command_line.rb:106:in`start_server'
E, [2013-03-14T12:53:35.512031 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.2/lib/siriproxy/command_line.rb:90:in `run_server'
E, [2013-03-14T12:53:35.512104 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.2/lib/siriproxy/command_line.rb:39:in`initialize'
E, [2013-03-14T12:53:35.512176 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.2/bin/siriproxy:6:in `new'
E, [2013-03-14T12:53:35.512247 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.2/bin/siriproxy:6:in`<top (required)>'
E, [2013-03-14T12:53:35.512320 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/bin/siriproxy:19:in `load'
E, [2013-03-14T12:53:35.512392 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/bin/siriproxy:19:in`<main>'
E, [2013-03-14T12:53:35.512465 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/bin/ruby_noexec_wrapper:14:in `eval'
E, [2013-03-14T12:53:35.512538 #2151] ERROR -- : /home/lucas/.rvm/gems/ruby-2.0.0-p0/bin/ruby_noexec_wrapper:14:in`<main>'

**Comment by elvisimprsntr** [comment]
migrate to SP 0.5.3.   perform `siriproxy update` from 0.5.2
