### ISSUE TITLE
Up and running (but not working)

### ISSUE THREAD

**Issue by psihacker** [plamoni/SiriProxy#482]
Hi, 

i already had siriproxy perfectly running under osx. then i changed to ubuntu inside a VM and got it running (thx for help). now i realized that i want back to osx (application starting...) BUT siriproxy doesn´t respond. 

starting with: rvmsudo siriproxy server it seems to run. 
(no error, just the secure_path and root warning) 

Starting SiriProxy on 192.168.1.222:443 (ip is ok)
Siriproxy is up and running

The ca.pem is "installed" on my phone and dns pointing to 192.168.1.222
Phone is in Fligh-mode with WLAN on

any chance to find out what´s wrong?

rvmsudo siriproxy update ->
(...)
Using siriproxy (0.5.2) from source at /Users/derOptiker/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.2 
Using siriproxy-example (0.0.1) from source at ./plugins/siriproxy-example 
Your bundle is complete!

rvmsudo siriproxy bundle -> 
(...)
Using siriproxy (0.5.2) from source at . 
Using siriproxy-example (0.0.1) from source at ./plugins/siriproxy-example 
Your bundle is complete!

i installed with a old tutorial with dnsmasq - 

sudo lsof -i :53 | grep LISTEN 

dnsmasq 109 nobody    4u  IPv4 0x7d67dbe31bece5db      0t0  TCP localhost:domain (LISTEN)
dnsmasq 109 nobody    6u  IPv6 0x7d67dbe31cfce87b      0t0  TCP [fe80:5::2a37:37ff:fe11:820f]:domain (LISTEN)
dnsmasq 109 nobody    8u  IPv6 0x7d67dbe31cfce49b      0t0  TCP localhost:domain (LISTEN)
dnsmasq 109 nobody   10u  IPv6 0x7d67dbe31cfce0bb      0t0  TCP localhost:domain (LISTEN)

help! =)

**Comment by elvisimprsntr** [comment]
DNSMASQ is obsolete with SP 0.5.2 and will cause conflicts.  

`apt-get purge dnsmasq` and use the new methods in Pete's instructions.

Also, I've not had 100% success using the update method.  I've always performed clean installs from scratch.

**Comment by psihacker** [comment]
how to get apt-get working on osx?
or.. maybe anybody has a working installation tutorial for SP 0.5.2 on OSX?

i killed dnsmasq and get: 

[Info - Server] Starting SiriProxy on 192.168.1.222:443...
[Info - Server] DNS server is not running yet, waiting 1 second...
[Error - Server] DNS Error: no datagram socket
[Error - Server] DNS Server has crashed. Terminating SiriProxy

**Comment by Deanmv** [comment]
You don't need dnsmasq at all. 

Just follow the instructions here: https://github.com/plamoni/SiriProxy and they work.

**Comment by psihacker** [comment]
ok.. and how to uninstall it (MAC OSX 10.8)?
when i try to sudo kill it - it comes back

**Comment by elvisimprsntr** [comment]
Sorry, my assumption was you were running Linux.   You are on your own with regard to Mac OSX.  Might I suggest you consider installing a VM (virtualbox.org) + Ubuntu.  It will make your life a lot easier if you are using the same OS as everyone else.

**Comment by psihacker** [comment]
"i already had siriproxy perfectly running under osx. then i changed to ubuntu inside a VM and got it running (thx for help). now i realized that i want back to osx (application starting...) BUT siriproxy doesn´t respond."

**Comment by psihacker** [comment]
ok.. just went back to a old SP version and it worked again
restarted the mac and now: 

siriproxy server
/Users/name/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems.rb:317:in `bin_path': can't find gem siriproxy ([">= 0"]) with executable siriproxy (Gem::GemNotFoundException)
    from /Users/name/.rvm/gems/ruby-1.9.3-p392@SiriProxy/bin/siriproxy:23:in`<main>'

i did:rvm use 2.0.0 --default
Using /Users/name/.rvm/gems/ruby-2.0.0-p0

rvmsudo siriproxy server
Warning: can not check `/etc/sudoers` for `secure_path`, falling back to call via `/usr/bin/env`, this breaks rules from `/etc/sudoers`. export rvmsudo_secure_path=1 to avoid the warning.WARN: Unresolved specs during Gem::Specification.reset:
      rake (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
[Info - Configuration] Loading plugins -- If any fail to load, run `siriproxy bundle` (not `bundle install`) to resolve.
[Notice - Server] ======================= WARNING: Running as root =============================
[Notice - Server] You should use -l or the config.yml to specify and non-root user to run under
[Notice - Server] Running the server as root is dangerous.
[Notice - Server] ==============================================================================
[Info - Server] Starting SiriProxy on 192.168.1.222:443...
[Info - Server] SiriProxy up and running.

but nothing happens :(

**Comment by plamoni** [comment]
Dnsmasq is not needed on any OS anymore. But you can use it if you really
want. It doesn't hurt, it's just hard to get set up right. I recommend
getting rid of Dnsmasq (or at least turning it off). How you do that
depends on how you installed it. Once it's off or gone, follow the install
directions in the readme.

-Pete

On Mar 15, 2013, at 7:13 AM, psihacker notifications@github.com wrote:

anyone knows if dnsmasq is needed under osx? maybe i should use a old SP
version?

—
Reply to this email directly or view it on
GitHubhttps://github.com/plamoni/SiriProxy/issues/482#issuecomment-14962672
.

**Comment by psihacker** [comment]
just updated my last post... 

i´ve installed dnsmasq with sudo port install dnsmasq
i´ve tried to uninstall with sudo port -fp uninstall installed
--->  Deactivating dnsmasq @2.65_0
--->  Cleaning dnsmasq
--->  Uninstalling dnsmasq @2.65_0
--->  Cleaning dnsmasq

but after that it´s still running - when i kill it it comes back. 
i really want to get it running before the weekend but going crazy for beeing such a noob..

**Comment by psihacker** [comment]
YEAH! it´s gone.. but :(

Info - Server] Starting SiriProxy on 192.168.1.222:443...
[Info - Server] DNS Server started, tainting 'guzzoni.apple.com' with 192.168.1.222
[Info - Server] DNS server is not running yet, waiting 1 second...
[Info - Server] SiriProxy up and running.

now.. first this when speeching:
E, [2013-03-15T15:48:21.369163 #1679] ERROR -- : Exception thrown while processing guzzoni.apple.com Resolv::DNS::Resource::IN::A!
E, [2013-03-15T15:48:21.369384 #1679] ERROR -- : NoMethodError: undefined method `respond!' for #<MatchData "guzzoni.apple.com">
E, [2013-03-15T15:48:21.369537 #1679] ERROR -- : /Users/user/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.2/lib/siriproxy/dns.rb:57:in`block (2 levels) in run'

after a SP update & bundle nothing happens again

**Comment by elvisimprsntr** [comment]
That might be a different issue.  https://github.com/plamoni/SiriProxy/issues/483

**Comment by psihacker** [comment]
YEAHHHH! Siri is talking again =)
thx a lot elvisimprsntr plamoni & deanmv!

**Comment by asmithdub** [comment]
I'm having similar issues... 

$ rvmsudo siriproxy server
Warning: can not check `/etc/sudoers` for `secure_path`, falling back to call via `/usr/bin/env`, this breaks rules from `/etc/sudoers`. export rvmsudo_secure_path=1 to avoid the warning.[Info - Configuration] Loading plugins -- If any fail to load, run `siriproxy bundle` (not `bundle install`) to resolve.
[Notice - Server] ======================= WARNING: Running as root =============================
[Notice - Server] You should use -l or the config.yml to specify and non-root user to run under
[Notice - Server] Running the server as root is dangerous.
[Notice - Server] ==============================================================================
[Info - Server] Starting SiriProxy on 10.0.0.2:443...
[Info - Server] SiriProxy up and running.

Thats it... 

Uninstalled dnsmasq. Killed it. 

But still noting. 

Any ideas?

**Comment by elvisimprsntr** [comment]
You are having a different issue which depends on how you installed RVM/Ruby/SP

```
Warning: can not check /etc/sudoers for secure_path, falling back to call via /usr/bin/env, this breaks rules from /etc/sudoers. export rvmsudo_secure_path=1 to avoid the warning
```

export rvmsudo_secure_path=1

**Comment by asmithdub** [comment]
Thanks for that. 

I followed the new instructions for 0.5.0.

**Comment by asmithdub** [comment]
Ok, so made some progress, but now getting these errors:

[Notice - Server] ======================= WARNING: Running as root =============================
[Notice - Server] You should use -l or the config.yml to specify and non-root user to run under
[Notice - Server] Running the server as root is dangerous.
[Notice - Server] ==============================================================================
[Info - Server] Starting SiriProxy on 0.0.0.0:443...
[Info - Server] DNS Server started, tainting 'guzzoni.apple.com' with 10.0.0.2
[Info - Server] SiriProxy up and running.
E, [2013-03-17T17:22:27.066506 #55907] ERROR -- : Exception thrown while processing guzzoni.apple.com Resolv::DNS::Resource::IN::A!
E, [2013-03-17T17:22:27.066840 #55907] ERROR -- : NoMethodError: undefined method `respond!' for #<MatchData "guzzoni.apple.com">
E, [2013-03-17T17:22:27.066971 #55907] ERROR -- : /Users/adamsmith/.rvm/gems/ruby-1.9.3-p392/gems/siriproxy-0.5.2/lib/siriproxy/dns.rb:57:in`block (2 levels) in run'
E, [2013-03-17T17:22:27.067168 #55907] ERROR -- : /Users/adamsmith/.rvm/gems/ruby-1.9.3-p392/gems/rubydns-0.6.0/lib/rubydns/server.rb:61:in `[]'
E, [2013-03-17T17:22:27.067240 #55907] ERROR -- : /Users/adamsmith/.rvm/gems/ruby-1.9.3-p392/gems/rubydns-0.6.0/lib/rubydns/server.rb:61:in`call'
E, [2013-03-17T17:22:27.067304 #55907] ERROR -- : /Users/adamsmith/.rvm/gems/ruby-1.9.3-p392/gems/rubydns-0.6.0/lib/rubydns/server.rb:166:in `block (2 levels) in process'
E, [2013-03-17T17:22:27.067565 #55907] ERROR -- : /Users/adamsmith/.rvm/gems/ruby-1.9.3-p392/gems/rubydns-0.6.0/lib/rubydns/server.rb:164:in`catch'
E, [2013-03-17T17:22:27.067708 #55907] ERROR -- : /Users/adamsmith/.rvm/gems/ruby-1.9.3-p392/gems/rubydns-0.6.0/lib/rubydns/server.rb:164:in `block in process'
E, [2013-03-17T17:22:27.067839 #55907] ERROR -- : /Users/adamsmith/.rvm/gems/ruby-1.9.3-p392/gems/rubydns-0.6.0/lib/rubydns/server.rb:161:in`each'
E, [2013-03-17T17:22:27.068040 #55907] ERROR -- : /Users/adamsmith/.rvm/gems/ruby-1.9.3-p392/gems/rubydns-0.6.0/lib/rubydns/server.rb:161:in `process'
E, [2013-03-17T17:22:27.068213 #55907] ERROR -- : /Users/adamsmith/.rvm/gems/ruby-1.9.3-p392/gems/rubydns-0.6.0/lib/rubydns/transaction.rb:76:in`process'
E, [2013-03-17T17:22:27.068376 #55907] ERROR -- : /Users/adamsmith/.rvm/gems/ruby-1.9.3-p392/gems/rubydns-0.6.0/lib/rubydns/server.rb:230:in `block (2 levels) in process_query'
E, [2013-03-17T17:22:27.068539 #55907] ERROR -- : /Users/adamsmith/.rvm/gems/ruby-1.9.3-p392/gems/rubydns-0.6.0/lib/rubydns/server.rb:238:in`call'
E, [2013-03-17T17:22:27.068704 #55907] ERROR -- : /Users/adamsmith/.rvm/gems/ruby-1.9.3-p392/gems/rubydns-0.6.0/lib/rubydns/server.rb:238:in `process_query'
E, [2013-03-17T17:22:27.068938 #55907] ERROR -- : /Users/adamsmith/.rvm/gems/ruby-1.9.3-p392/gems/rubydns-0.6.0/lib/rubydns/handler.rb:41:in`process'
E, [2013-03-17T17:22:27.069041 #55907] ERROR -- : /Users/adamsmith/.rvm/gems/ruby-1.9.3-p392/gems/rubydns-0.6.0/lib/rubydns/handler.rb:66:in `receive_data'
E, [2013-03-17T17:22:27.069275 #55907] ERROR -- : /Users/adamsmith/.rvm/gems/ruby-1.9.3-p392/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in`run_machine'
E, [2013-03-17T17:22:27.069440 #55907] ERROR -- : /Users/adamsmith/.rvm/gems/ruby-1.9.3-p392/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
E, [2013-03-17T17:22:27.069600 #55907] ERROR -- : /Users/adamsmith/.rvm/gems/ruby-1.9.3-p392/gems/siriproxy-0.5.2/lib/siriproxy.rb:17:in`initialize'
E, [2013-03-17T17:22:27.069764 #55907] ERROR -- : /Users/adamsmith/.rvm/gems/ruby-1.9.3-p392/gems/siriproxy-0.5.2/lib/siriproxy/command_line.rb:106:in `new'
E, [2013-03-17T17:22:27.069940 #55907] ERROR -- : /Users/adamsmith/.rvm/gems/ruby-1.9.3-p392/gems/siriproxy-0.5.2/lib/siriproxy/command_line.rb:106:in`start_server'
E, [2013-03-17T17:22:27.070085 #55907] ERROR -- : /Users/adamsmith/.rvm/gems/ruby-1.9.3-p392/gems/siriproxy-0.5.2/lib/siriproxy/command_line.rb:90:in `run_server'
E, [2013-03-17T17:22:27.070246 #55907] ERROR -- : /Users/adamsmith/.rvm/gems/ruby-1.9.3-p392/gems/siriproxy-0.5.2/lib/siriproxy/command_line.rb:39:in`initialize'
E, [2013-03-17T17:22:27.070406 #55907] ERROR -- : /Users/adamsmith/.rvm/gems/ruby-1.9.3-p392/gems/siriproxy-0.5.2/bin/siriproxy:6:in `new'
E, [2013-03-17T17:22:27.070567 #55907] ERROR -- : /Users/adamsmith/.rvm/gems/ruby-1.9.3-p392/gems/siriproxy-0.5.2/bin/siriproxy:6:in`<top (required)>'
E, [2013-03-17T17:22:27.070745 #55907] ERROR -- : /Users/adamsmith/.rvm/gems/ruby-1.9.3-p392/bin/siriproxy:23:in `load'
E, [2013-03-17T17:22:27.070893 #55907] ERROR -- : /Users/adamsmith/.rvm/gems/ruby-1.9.3-p392/bin/siriproxy:23:in`<main>'

Any ideas on this?

**Comment by asmithdub** [comment]
its sorted - was the DNS.rb file. 

Thanks

**Comment by elvisimprsntr** [comment]
Are you using in iPhone 4S or 5?
