### ISSUE TITLE
RubyDNS gem version

### ISSUE THREAD

**Issue by fabianorosa1** [plamoni/SiriProxy#486]
Hi, when I run the command "siryproxy update", it's download the version 0.6.0 of RubyDNS gem, and it's throw a exception in SiriProxy when run it!

I think you have to put the version "0.5.4" in siriproxy.gemspec file:

s.add_runtime_dependency "rubydns", "=0.5.4"

I did it and solve for me!

**Comment by suhajdab** [comment]
I've changed the siriproxy.gemspec, but when I execute `siriproxy bundle` it shows 0.6.0.
So I tried `gem install --version '= 0.5.4' rubydns`, but again, when I ran `siriproxy bundle`, it installed 0.6.0. :(

**Comment by elvisimprsntr** [comment]
fixed in SP 0.5.3.  perform `sirproxy update` from 0.5.2 to fix.
