### ISSUE TITLE
plugin issue

### ISSUE THREAD

**Issue by matthewwatson70** [plamoni/SiriProxy#487]
can someone please tell me how to fix this issue when i run rvmsudo siriproxy update

git://github.com/Swimo/SiriProxy---WhereAmI.git
Fetching git://github.com/JoshuaCarroll/SiriProxy-DirectRemote/
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Could not find gem 'siriproxy-directtv (>= 0) ruby' in
git://github.com/JoshuaCarroll/SiriProxy-DirectRemote/ (at master).
Source does not contain any versions of 'siriproxy-directtv (>= 0) ruby'

**Comment by lupinglade** [comment]
Looks like you have specified a non-existsant gem in your config.yml for siriproxy. Maybe its not spelled/named correctly? Looks like the repository is named differently.

**Comment by elvisimprsntr** [comment]
closed due to inactivity
