### ISSUE TITLE
Some weird errors, any help?

### ISSUE THREAD

**Issue by ian-mcdowell** [plamoni/SiriProxy#49]
I installed everything according to the guide and youtube videos. I am getting some long errors once I run the script and open siri on my 4S.

Running 10.7.2 on a Mac Pro.

The following is the results of running the program...

http://pastebin.com/fgPNve0B

**Comment by ian-mcdowell** [comment]
Figured this out. The server computer must not use the DNS you set up for the iPhone XD

**Comment by netpro2k** [comment]
Looks like you are using ruby 1.8. As per the readme, install rvm, and
ruby 1.9.3.

On Nov 26, 2011, at 2:00 AM, IMcD23
reply@reply.github.com
wrote:
