### ISSUE TITLE
Connection loop DNS issue

### ISSUE THREAD

**Issue by trouty00** [plamoni/SiriProxy#490]
just installed on a ubuntu box and having a looking issue and connections go up and up until siriproxy crashes and reboots.

I suspect a DNS issue as
root@UbuntuDesk:~# nslookup guzzoni.apple.com
Server:         127.0.0.1
Address:        127.0.0.1#53

Name:   guzzoni.apple.com
Address: 192.168.1.147

This is what I get when I start up
root@UbuntuDesk:~# sh StartServer.sh
- Stopping DNS forwarder and DHCP server dnsmasq                                                                                                                                             [ OK ]
  named: no process found
- Starting DNS forwarder and DHCP server dnsmasq                                                                                                                                             [ OK ]
  Starting Server
  WARN: Unresolved specs during Gem::Specification.reset:
    i18n (>= 0.4.0)
  WARN: Clearing out unresolved specs.
  Please report a bug if this causes problems.

[Info - SiriProxy] Uptime [5] Active connections [2] Max connections [50]

[Info - SiriProxy] Uptime [15] Active connections [2] Max connections [50]
[Info - SiriProxy] Uptime [20] Active connections [2] Max connections [50]
[Info - SiriProxy] Uptime [25] Active connections [2] Max connections [50]
[Info - SiriProxy] Uptime [30] Active connections [2] Max connections [50]

then as soon as I try to use siri on my iphone 4s i get the following.
any thoughts

  connection
[Info - SiriProxy] Created a connection!
[Info - Plugin Manager] Plugins loaded: [#<SiriProxy::Plugin::Example:0x0000000256d680 @manager=#<SiriProxy::PluginManager:0x00000002565390 @person="", @plugins=[...]>>]
[Info - SiriProxy] Created a connection!
Create server for iPhone connection
[Info - SiriProxy] Created a connection!
[Info - Plugin Manager] Plugins loaded: [#<SiriProxy::Plugin::Example:0x00000002708760 @manager=#<SiriProxy::PluginManager:0x0000000257f240 @person="", @plugins=[...]>>]
[Info - SiriProxy] Created a connection!
Create server for iPhone connection
[Info - SiriProxy] Created a connection!
[Info - Plugin Manager] Plugins loaded: [#<SiriProxy::Plugin::Example:0x00000002981578 @manager=#<SiriProxy::PluginManager:0x00000002897c98 @person="", @plugins=[...]>>]
[Info - SiriProxy] Created a connection!
Create server for iPhone connection
[Info - SiriProxy] Created a connection!
[Info - Plugin Manager] Plugins loaded: [#<SiriProxy::Plugin::Example:0x00000002d26ca0 @manager=#<SiriProxy::PluginManager:0x00000002a38a70 @person="", @plugins=[...]>>]
[Info - SiriProxy] Created a connection!
Create server for iPhone connection
[Info - SiriProxy] Created a connection!
[Info - Plugin Manager] Plugins loaded: [#<SiriProxy::Plugin::Example:0x00000002d86128 @manager=#<SiriProxy::PluginManager:0x00000002d33798 @person="", @plugins=[...]>>]
[Info - SiriProxy] Created a connection!
Create server for iPhone connection
[Info - SiriProxy] Created a connection!
[Info - Plugin Manager] Plugins loaded: [#<SiriProxy::Plugin::Example:0x00000002cc4f78 @manager=#<SiriProxy::PluginManager:0x00000002cbe830 @person="", @plugins=[...]>>]
[Info - SiriProxy] Created a connection!
Create server for iPhone connection
[Info - SiriProxy] Created a connection!
[Info - Plugin Manager] Plugins loaded: [#<SiriProxy::Plugin::Example:0x00000002e8c3d8 @manager=#<SiriProxy::PluginManager:0x00000002e1ea68 @person="", @plugins=[...]>>]
[Info - SiriProxy] Created a connection!
Create server for iPhone connection
[Info - SiriProxy] Created a connection!
[Info - Plugin Manager] Plugins loaded: [#<SiriProxy::Plugin::Example:0x00000002edcc20 @manager=#<SiriProxy::PluginManager:0x00000002ede390 @person="", @plugins=[...]>>]
[Info - SiriProxy] Created a connection!
Create server for iPhone connection
[Info - SiriProxy] Created a connection!
[Info - Plugin Manager] Plugins loaded: [#<SiriProxy::Plugin::Example:0x00000002ee25a8 @manager=#<SiriProxy::PluginManager:0x00000002edad08 @person="", @plugins=[...]>>]
[Info - SiriProxy] Created a connection!
Create server for iPhone connection
[Info - SiriProxy] Created a connection!
[Info - Plugin Manager] Plugins loaded: [#<SiriProxy::Plugin::Example:0x00000002ee8a48 @manager=#<SiriProxy::PluginManager:0x00000002ee9c40 @person="", @plugins=[...]>>]
[Info - SiriProxy] Created a connection!
Create server for iPhone connection
[Info - SiriProxy] Created a connection!
[Info - Plugin Manager] Plugins loaded: [#<SiriProxy::Plugin::Example:0x00000002547fe8 @manager=#<SiriProxy::PluginManager:0x0000000253c3a0 @person="", @plugins=[...]>>]
[Info - SiriProxy] Created a connection!
Create server for iPhone connection
[Info - SiriProxy] Created a connection!
[Info - Plugin Manager] Plugins loaded: [#<SiriProxy::Plugin::Example:0x0000000255b3e0 @manager=#<SiriProxy::PluginManager:0x0000000254e410 @person="", @plugins=[...]>>]
[Info - SiriProxy] Created a connection!
Create server for iPhone connection
[Info - SiriProxy] Created a connection!
[Info - Plugin Manager] Plugins loaded: [#<SiriProxy::Plugin::Example:0x00000002572270 @manager=#<SiriProxy::PluginManager:0x0000000256d298 @person="", @plugins=[...]>>]
[Info - SiriProxy] Created a connection!
Create server for iPhone connection
[Info - SiriProxy] Created a connection!
[Info - Plugin Manager] Plugins loaded: [#<SiriProxy::Plugin::Example:0x0000000287b160 @manager=#<SiriProxy::PluginManager:0x0000000278b368 @person="", @plugins=[...]>>]
[Info - SiriProxy] Created a connection!
Create server for iPhone connection
[Info - SiriProxy] Created a connection!
[Info - Plugin Manager] Plugins loaded: [#<SiriProxy::Plugin::Example:0x0000000285a668 @manager=#<SiriProxy::PluginManager:0x00000002c13958 @person="", @plugins=[...]>>]
[Info - SiriProxy] Created a connection!
Create server for iPhone connection
[Info - SiriProxy] Created a connection!
[Info - Plugin Manager] Plugins loaded: [#<SiriProxy::Plugin::Example:0x00000002d8cdc0 @manager=#<SiriProxy::PluginManager:0x00000002d31dd0 @person="", @plugins=[...]>>]
[Info - SiriProxy] Created a connection!
Create server for iPhone connection
[Info - SiriProxy] Created a connection!
[Info - Plugin Manager] Plugins loaded: [#<SiriProxy::Plugin::Example:0x00000002d09240 @manager=#<SiriProxy::PluginManager:0x00000002cc5360 @person="", @plugins=[...]>>]
[Info - SiriProxy] Created a connection!
Create server for iPhone connection
[Info - SiriProxy] Created a connection!
[Info - Plugin Manager] Plugins loaded: [#<SiriProxy::Plugin::Example:0x00000002e89430 @manager=#<SiriProxy::PluginManager:0x00000002e86cd0 @person="", @plugins=[...]>>]
[Info - iPhone] Received Object: SetRequestOrigin (group: com.apple.ace.system)
[Key -  iPhone] Recieved Object Using: Key id [0] and Instance Keyload[]
[Info - User Location] lat: 50.833063360049984, long: -0.1781332298490064
[Info - Forwarding object to Guzzoni] SetRequestOrigin
[Info - iPhone] Received Object: StartSpeechRequest (group: com.apple.ace.speech)
[Key -  iPhone] Recieved Object Using: Key id [0] and Instance Keyload[]
[Info - Forwarding object to Guzzoni] StartSpeechRequest
[Info - iPhone] Received Object: SetRequestOrigin (group: com.apple.ace.system)
[Key -  iPhone] Recieved Object Using: Key id [0] and Instance Keyload[]
[Info - User Location] lat: 50.833063360049984, long: -0.1781332298490064
[Info - Forwarding object to Guzzoni] SetRequestOrigin
[Info - iPhone] Received Object: SetAlertContext (group: com.apple.ace.system)
[Key -  iPhone] Recieved Object Using: Key id [0] and Instance Keyload[]
[Info - Forwarding object to Guzzoni] SetAlertContext
[Info - iPhone] Received Object: StartSpeechRequest (group: com.apple.ace.speech)
[Key -  iPhone] Recieved Object Using: Key id [0] and Instance Keyload[]
[Info - Forwarding object to Guzzoni] StartSpeechRequest
[Info - iPhone] Received Object: SetRequestOrigin (group: com.apple.ace.system)
[Key -  iPhone] Recieved Object Using: Key id [0] and Instance Keyload[]
[Info - User Location] lat: 50.833063360049984, long: -0.1781332298490064
[Info - Forwarding object to Guzzoni] SetRequestOrigin
[Info - SiriProxy] Created a connection!
Create server for iPhone connection
[Info - SiriProxy] Created a connection!
[Info - Plugin Manager] Plugins loaded: [#<SiriProxy::Plugin::Example:0x00000002cf7a40 @manager=#<SiriProxy::PluginManager:0x00000002cf1118 @person="", @plugins=[...]>>]
[Info - iPhone] Received Object: SetBackgroundContext (group: com.apple.ace.system)
[Key -  iPhone] Recieved Object Using: Key id [0] and Instance Keyload[]
[Info - Forwarding object to Guzzoni] SetBackgroundContext
[Info - iPhone] Received Object: SetAlertContext (group: com.apple.ace.system)
[Key -  iPhone] Recieved Object Using: Key id [0] and Instance Keyload[]
[Info - Forwarding object to Guzzoni] SetAlertContext
[Info - iPhone] Received Object: StartSpeechRequest (group: com.apple.ace.speech)
[Key -  iPhone] Recieved Object Using: Key id [0] and Instance Keyload[]
[Info - Forwarding object to Guzzoni] StartSpeechRequest
[Info - iPhone] Received Object: SetRequestOrigin (group: com.apple.ace.system)
[Key -  iPhone] Recieved Object Using: Key id [0] and Instance Keyload[]
[Info - User Location] lat: 50.833063360049984, long: -0.1781332298490064
[Info - Forwarding object to Guzzoni] SetRequestOrigin
[Info - iPhone] Received Object: ClearContext (group: com.apple.ace.system)
[Key -  iPhone] Recieved Object Using: Key id [0] and Instance Keyload[]
[Info - Forwarding object to Guzzoni] ClearContext
[Info - iPhone] Received Object: SetBackgroundContext (group: com.apple.ace.system)
[Key -  iPhone] Recieved Object Using: Key id [0] and Instance Keyload[]
[Info - Forwarding object to Guzzoni] SetBackgroundContext
[Info - iPhone] Received Object: SetAlertContext (group: com.apple.ace.system)
[Key -  iPhone] Recieved Object Using: Key id [0] and Instance Keyload[]
[Info - Forwarding object to Guzzoni] SetAlertContext
[Info - iPhone] Received Object: StartSpeechRequest (group: com.apple.ace.speech)
[Key -  iPhone] Recieved Object Using: Key id [0] and Instance Keyload[]
[Info - Forwarding object to Guzzoni] StartSpeechRequest
[Info - iPhone] Received Object: SetRequestOrigin (group: com.apple.ace.system)
[Key -  iPhone] Recieved Object Using: Key id [0] and Instance Keyload[]
[Info - User Location] lat: 50.833063360049984, long: -0.1781332298490064
[Info - Forwarding object to Guzzoni] SetRequestOrigin
[Info - iPhone] Received Object: SetRestrictions (group: com.apple.ace.system)
[Key -  iPhone] Recieved Object Using: Key id [0] and Instance Keyload[]
[Info - Forwarding object to Guzzoni] SetRestrictions
[Info - iPhone] Received Object: ClearContext (group: com.apple.ace.system)
[Key -  iPhone] Recieved Object Using: Key id [0] and Instance Keyload[]
[Info - Forwarding object to Guzzoni] ClearContext
[Info - iPhone] Received Object: SetBackgroundContext (group: com.apple.ace.system)
[Key -  iPhone] Recieved Object Using: Key id [0] and Instance Keyload[]
[Info - Forwarding object to Guzzoni] SetBackgroundContext
[Info - iPhone] Received Object: SetAlertContext (group: com.apple.ace.system)
[Key -  iPhone] Recieved Object Using: Key id [0] and Instance Keyload[]
[Info - Forwarding object to Guzzoni] SetAlertContext
[Info - iPhone] Received Object: StartSpeechRequest (group: com.apple.ace.speech)
[Key -  iPhone] Recieved Object Using: Key id [0] and Instance Keyload[]
[Info - Forwarding object to Guzzoni] StartSpeechRequest
[Info - iPhone] Received Object: SetRequestOrigin (group: com.apple.ace.system)
[Key -  iPhone] Recieved Object Using: Key id [0] and Instance Keyload[]
[Info - User Location] lat: 50.833063360049984, long: -0.1781332298490064
[Info - Forwarding object to Guzzoni] SetRequestOrigin
[Info - SiriProxy] Created a connection!
[Info -  SiriProxy] using iPhone 4S validationData and saving it
[Info - SiriProxy] Duplicate Validation Data. Key NOT saved
[Info - SiriProxy] Recieved token
# <KeyStatistics:0x00000003d68aa0

 @id=3,
 @key_id=2,
 @total_finishspeech_requests=0,
 @total_tokens_recieved=1988>

**Comment by elvisimprsntr** [comment]
have you migrated to siriproxy 0.5.3 which doesn't require dnsmasq?

**Comment by elvisimprsntr** [comment]
closed due to inactivity
