### ISSUE TITLE
ruby-1.9.3-p392 is not installed.

### ISSUE THREAD

**Issue by Fkhan411** [plamoni/SiriProxy#493]
Hey guys,

I'm new at this. can someone please help me out this issue.
I followed Pete's installation guide.
After i clone git://github.com/plamoni/SiriProxy.git 
and Cd into SiriProxy 
I get this Notice.
# faisa@faisa-ubuntu:~$ cd SiriProxy
# = NOTICE                                                                     =

= RVM has encountered a new or modified .rvmrc file in the current directory =
= This is a shell script and therefore may contain any shell commands.       =
=                                                                            =
= Examine the contents of this file carefully to be sure the contents are    =
# = safe before trusting it! ( Choose v[iew] below to view the contents )      =

Do you wish to trust this .rvmrc file? (/home/faisa/SiriProxy/.rvmrc)
y[es], n[o], v[iew], c[ancel]> Y
ruby-1.9.3-p392 is not installed.
To install do: 'rvm install ruby-1.9.3-p392'

After I enter Y 
this is what i get although

 ruby-1.9.3-p392 is not installed.
To install do: 'rvm install ruby-1.9.3-p392'

 i installed ruby 2.0.0 and made it default by using these two commands

rvm install 2.0.0

and 
rvm use 2.0.0 -- default

please help.

**Comment by elvisimprsntr** [comment]
i believe this issue was resolved some time ago.  use the latest siriproxy.
