### ISSUE TITLE
Siri on iPad Mini

### ISSUE THREAD

**Issue by evasuarez22** [plamoni/SiriProxy#494]
I am thinking about buy an iPad mini, and I want to know if this Siri proxy will run with this device and if  there are people that have tried it.

Thanks

**Comment by DE-CaTeR** [comment]
Siri uses on every iDevice the same Protocol. I use Siri Proxy with an iPad3. Siri Proxy calles it iPhone, but Siris is Siri. So I think it will run with an iPad mini.
The Protocol is the same!

**Comment by Deanmv** [comment]
Any device that uses Siri is capable of using SiriProxy.

**Comment by elvisimprsntr** [comment]
concur
