### ISSUE TITLE
German characters

### ISSUE THREAD

**Issue by muhkuh0815** [plamoni/SiriProxy#50]
German special characters like Ä Ö Ü seems to crash the Siriproxy.

i have no idea if thats something you can fix, but would be nice if it works.

and my second question. is there a possibility to  "listen_for"  2 or more seperate words ?

i would like to listen for  e.g.  "Johnny" and "cook" in one sentense

so i can ask for   "can Johnny cook" or  "is Johnny able to cook" 

sorry for my bad english, and keep up your great work
very appreciated
Greetings from Austria
Michael

**Comment by plamoni** [comment]
I'll look into the special character crashing thing.

As for listening for two words:

https://github.com/plamoni/SiriProxy-Thermostat/blob/master/lib/siriproxy-thermostat.rb#L12-13

That's how I do it. You can probably figure a better way.

-Pete

On Sat, Nov 26, 2011 at 12:45 PM, muhkuh0815 <
reply@reply.github.com

**Comment by muhkuh0815** [comment]
Thank you, works perfect.

**Comment by plamoni** [comment]
Chendo: this one is all you. Mostly because I'm too lazy to fix. Get with me in chat if you want to discuss.

**Comment by muhkuh0815** [comment]
heres the error message i get when anywhere in the siriproxy-example file is a  Ä Ö Ü or ß character.
hope it helps

plugin_manager.rb:22:in `require': /Users/xxx/SiriProxy/plugins/siriproxy-example/lib/siriproxy-example.rb:49: invalid multibyte char (US-ASCII) (SyntaxError)
/Users/xxx/SiriProxy/plugins/siriproxy-example/lib/siriproxy-example.rb:49: syntax error, unexpected tIDENTIFIER, expecting keyword_end

**Comment by Matoz** [comment]
I had problems with ÜÄÖ too.

Seems to be a file encoding problem. I was able to work around this by converting and editing the file in UTF-8. Before uploading to my Dreamplug (Ubuntu) I change the encoding to ANSI (not converting). I´m editing my file with Notepad++ on Windows.

I am not sure why this works. Perhaps someone else can clarify this.

**Comment by kalbasit** [comment]
it seems that the encoding is not UTF-8, it should be solved by simply adding

``` ruby
# -*- encoding: utf-8 -*-
```

at the top of all ruby files even the plugins

/cc @plamoni @netpro2k @chendo

**Comment by kalbasit** [comment]
It might be also a good idea to add

``` ruby
# Make sure we are running UTF-8
Encoding.default_external = 'utf-8'
```

in the `lib/siriproxy.rb` file to ensure all externally open files (if any) are being opened in UTF-8 mode

**Comment by zobi** [comment]
Same problem with french character like : éèà ... 
thanks ;)

**Comment by kalbasit** [comment]
@zobi could you try the patch in #113 ?

**Comment by zobi** [comment]
i try to put :
Encoding.default_external = 'utf-8'
on all my .rb file but it didn't work :/

**Comment by kalbasit** [comment]
Not Encoding.default_external = 'utf8' but this as the **first line** of each `.rb` file

``` ruby
# -*- encoding: utf-8 -*-
```

Just apply [this patch](https://github.com/eMxyzptlk/SiriProxy/commit/739b0cefb3e60b94514123c010820a1d51c99dfb.patch)

``` bash
curl -o- https://github.com/eMxyzptlk/SiriProxy/commit/739b0cefb3e60b94514123c010820a1d51c99dfb.patch | patch -Np1
```

**Comment by zobi** [comment]
Ho great it works like a charm !!
Thanks you very much for this patch ;)

**Comment by Doriginal** [comment]
hello,
 I have the same problem with the characters in French é î à ...
 How to apply your patch, because as I lanche he asks me things and I'm lost
:(

 thank you

**Comment by elvisimprsntr** [comment]
seems like this was fixed by adding encoding utf-8 to plugins.
