### ISSUE TITLE
[Info - Guzzoni] Got invalid data (non-ACE protocol?), terminating the connection.

### ISSUE THREAD

**Issue by lazybensch** [plamoni/SiriProxy#501]
Hi folks, I recently pulled the siriproxy project since i think it is a great match for me (who wants to start contributing to open source projects). Currently I m trying to set up everything and came along this strange, kind of randomly appearing, error:

When I speak to Siri the Speechpackets get uploaded to Guzzoni, recognized and my siriproxy receives the correct string representation. BUT when Guzzoni tries to send me the actual answer, siriproxy doesn't seem to understand it (sometimes)

[Info - Guzzoni] Got invalid data (non-ACE protocol?), terminating the connection.

Strangely enough this is not always the case. For example when I say "Test" i will receive the correct answer in 9 out of 10 times. When i say "Time" however, it works hardly 1 out of 10 times, mostly i get this (non-ACE protocol?) error.

here is how it looks on log_level 1

mac-mini:SiriProxy Chris$ sudo ./bin/siriproxy server -d 192.168.178.29 -u nobody
[Notice - Configuration] ==================== Important Configuration Notice ==========================
[Notice - Configuration] '/Users/Chris/.siriproxy/config.yml' not found. Using '/Users/Chris/Documents/SiriProxy/config.example.yml'
[Notice - Configuration] 
[Notice - Configuration] Remove this message by copying '/Users/Chris/Documents/SiriProxy/config.example.yml' into '~/.siriproxy/'
[Notice - Configuration] ==============================================================================
[Info - Configuration] Loading plugins -- If any fail to load, run `siriproxy bundle` (not `bundle install`) to resolve.
siriproxy-example
[Info - Server] Starting SiriProxy on 0.0.0.0:443...
start of run method
[Info - Server] DNS server is not running yet, waiting 1 second...
[Info - Server] DNS Server started, tainting 'guzzoni.apple.com' with 192.168.178.29
[Info - Server] SiriProxy up and running.
siriproxy-example
[Error] Failed to load plugin: Example
[Info - Plugin Manager] Plugins loaded: 
[Info - iPhone] Received Object: LoadAssistant
[Info - iPhone] Received Object: SetRestrictions
[Info - iPhone] Received Object: ClearContext
[Info - iPhone] Received Object: SetSessionObjects
[Info - Guzzoni] Received Object: AssistantLoaded
[Info - iPhone] Received Object: SetAlertContext
[Info - iPhone] Received Object: StartSpeechRequest
[Info - iPhone] Received Object: SetRequestOrigin
[Info - iPhone] Received Object: SpeechPacket
[Info - Guzzoni] Received Object: SetConnectionHeader
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: FinishSpeech
[Info - Guzzoni] Received Object: SpeechRecognized
[Info - Plugin Manager] Processing 'Where am I'
[Info - Plugin Manager] No matches for 'Where am I'
[Info - Guzzoni] Received Object: GetRequestOrigin
[Info - iPhone] Received Object: SetRequestOrigin
[Info - Guzzoni] Got invalid data (non-ACE protocol?), terminating the connection.

and this is how it looks when everything works:

[Error] Failed to load plugin: Example
[Info - Plugin Manager] Plugins loaded: 
[Info - iPhone] Received Object: LoadAssistant
[Info - iPhone] Received Object: SetRestrictions
[Info - iPhone] Received Object: SetSessionObjects
[Info - Guzzoni] Received Object: AssistantLoaded
[Info - iPhone] Received Object: ClearContext
[Info - iPhone] Received Object: SetAlertContext
[Info - iPhone] Received Object: SetRestrictions
[Info - iPhone] Received Object: ClearContext
[Info - iPhone] Received Object: SetAlertContext
[Info - iPhone] Received Object: StartSpeechRequest
[Info - iPhone] Received Object: SetRequestOrigin
[Info - Guzzoni] Received Object: SetConnectionHeader
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: FinishSpeech
[Info - Guzzoni] Received Object: SpeechRecognized
[Info - Plugin Manager] Processing 'Test'
[Info - Plugin Manager] No matches for 'Test'
[Info - Guzzoni] Received Object: AddViews
[Info - Guzzoni] Received Object: RequestComp

I know that the example plugin does not get loaded but i think this is an unrelated error i maybe will address in a different issue.

Hopefully I am not to dumb right now and someone can help me or had the same problem.

Have a great day!
Ben

**Comment by elvisimprsntr** [comment]
Ben,

the example plugin crashing is the problem.  If you happen to get a response from siri its from apple and not siriproxy.  Is there any particular reason you are not launching SiriProxy using `rvmsudo siriproxy server -d ###.###.###.###` method?

Elvis

**Comment by lazybensch** [comment]
Hi elvis.

Unfortunately I'm fairly new to git and when i follow the instructions on the documentation and installing the siriproxy gem i had trouble to version-controll the project. Also I found (but I'm sure that's my fault somehow) that if I install the gem it is not the latest version of the project. There were a few bugs fixed in the repository which were still in the gem.

For that reason i pulled the project from git in my own directory, because now i'm able to pull, grep and everything. But not having the gem means I cannot run siriproxy so I'm running the actual script in the bin directory.

Is this causing the trouble with the plugin?

Ben

**Comment by plamoni** [comment]
The gem version of SiriProxy is behind the repo version. In the future, I will try to make sure a version is pretty stable before pushing it to rubygems.

I'm not sure exactly how you got things set up and I'm not really much of a Ruby expert (go figure). I would suggest going to a clean directory somewhere (e.g. `~/src/`) and then cloning the repo (`git clone git@github.com:plamoni/SiriProxy.git`) and then doing `siriproxy update` with the directory (e.g. `siriproxy update ~/src/SiriProxy`). If you don't have `siriproxy update` available, you might try reinstalling from rubygems.

**Comment by elvisimprsntr** [comment]
perform `siriproxy update` to get 0.5.4 which will hopefully provide some information why the plugin failed to load.

**Comment by elvisimprsntr** [comment]
Pete pushed 0.5.4 as a gem.   

`gem uninstall siriproxy -v 0.5.2`
`gem uninstall siriproxy -v 0.5.3`
`gem install siriproxy -v 0.5.4`

**Comment by elvisimprsntr** [comment]
closed due to inactivity
