### ISSUE TITLE
SiriProxy server crashing

### ISSUE THREAD

**Issue by Deschtex** [plamoni/SiriProxy#504]
Hey,

I've just installed SiriProxy on my Raspberry PI following the instructions given here in the project page, as well as other tutorials. I first downloaded the Raspbian image with SiriProxy pre-installed (from elvisimprsntr), but had no luck getting it to work. I am running SiriProxy 0.5.3 (updated from 0.5.2 with siriproxy update) and each time I start it and activate Siri on my phone it crashes and throws the error:

/usr/local/rvm/gems/ruby-2.0.0-p0/gems/eventmachine-1.0.3/lib/em/connection.rb:411:in `block in start_tls': Could not find /root/.siriproxy/server.passless.key for start_tls (EventMachine::FileNotFoundException)

[...]

Also when I Ctrl+C the running server this error occurs:

/usr/local/rvm/gems/ruby-2.0.0-p0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine': Interrupt
    from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in`run' 

[...]

I tried a clean install of Raspbian and installed SiriProxy from scratch, but with the same result. Also, both server.passless.key and server.passless.crt exist in ~/.siriproxy/.

What should config.yml look like? Should the "listen: 0.0.0.0" setting be changed to my internal server ip? What's the difference from the "server_ip: x.x.x.x" setting, which is commented out? This is what it looks like when I'm starting it:

[Info - Server] Starting SiriProxy on 0.0.0.0:443...
[Info - Server] DNS server is not running yet, waiting 1 second...
[Info - Server] DNS Server started, tainting 'guzzoni.apple.com' with 192.168.0.8
[Info - Server] SiriProxy up and running.

Help much appreciated

/Pierre

**Comment by Deanmv** [comment]
The error is `Could not find /root/.siriproxy/server.passless.key` so you need to check that gencerts was run correctly and that that file exists.

Also yes you need to change the 0.0.0.0 to the IP of the device that it is running on.

**Comment by elvisimprsntr** [comment]
Drop the -u option

Elvis

**Comment by Deschtex** [comment]
The file exists as seen here:

root@raspberrypi:~/.siriproxy# ls
ca.pem  cert.log  config.yml  server.passless.crt  server.passless.key

And even with the listen setting set to my internal IP, it does not work

**Comment by Deschtex** [comment]
Wow, thanks Elvis. That did the work. What about the discouraging warning about not running it as root then?
