### ISSUE TITLE
problem with rvm instalation and bash

### ISSUE THREAD

**Issue by bogaskilop** [plamoni/SiriProxy#505]
Hello i try  to install this siriproxy  on raspian  and i'm stuck with 2 point of readme 

i already make . ~/.bashrc

and after that I cant open any program like top or mc or vi ( only this opening after i hit enter again )

root@raspberrypi:~# top
'term': unknown terminal type.
root@raspberrypi:~#
root@raspberrypi:~# mc
Unknown terminal: term
Check the TERM environment variable.
Also make sure that the terminal is defined in the terminfo database.
Alternatively, set the TERMCAP environment variable to the desired
termcap entry.
root@raspberrypi:~#

when i run rvm install:

root@raspberrypi:~# rvm install 2.0.0
tput: unknown terminal "term"
tput: unknown terminal "term"
tput: unknown terminal "term"
tput: unknown terminal "term"
tput: unknown terminal "term"
tput: unknown terminal "term"
tput: unknown terminal "term"
tput: unknown terminal "term"
tput: unknown terminal "term"
tput: unknown terminal "term"
tput: unknown terminal "term"
tput: unknown terminal "term"
tput: unknown terminal "term"
tput: unknown terminal "term"
tput: unknown terminal "term"
Searching for binary rubies, this might take some time.
No binary rubies available for: debian/7.0/armv6l/ruby-2.0.0-p0.
Continuing with compilation. Please read 'rvm mount' to get more information on binary rubies.
Installing requirements for debian, might require sudo password.
Skipping `apt-get update` make sure your system is up to date.
RVM autolibs is now configured with mode '2' => 'check and stop if missing',
please run `rvm autolibs enable` to let RVM do it's job or run and read `rvm autolibs [help]`
or visit https://rvm.io/rvm/autolibs for more information.
Installing Ruby from source to: /usr/local/rvm/rubies/ruby-2.0.0-p0, this may take a while depending on your cpu(s)...
ruby-2.0.0-p0 - #downloading ruby-2.0.0-p0, this may take a while depending on your connection...
tput: unknown terminal "term"
tput: unknown terminal "term"
tput: unknown terminal "term"
tput: unknown terminal "term"
tput: unknown terminal "term"
###### ################################################################## 100,0%

ruby-2.0.0-p0 - #extracting ruby-2.0.0-p0 to /usr/local/rvm/src/ruby-2.0.0-p0
ruby-2.0.0-p0 - #extracted to /usr/local/rvm/src/ruby-2.0.0-p0
tput: unknown terminal "term"
tput: unknown terminal "term"
tput: unknown terminal "term"
tput: unknown terminal "term"
tput: unknown terminal "term"

ruby-2.0.0-p0 - #configuring..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

root@raspberrypi:~# rvm use 2.0.0 --default
tput: unknown terminal "term"
tput: unknown terminal "term"
tput: unknown terminal "term"
tput: unknown terminal "term"
tput: unknown terminal "term"
Using /usr/local/rvm/gems/ruby-2.0.0-p0

**Comment by elvisimprsntr** [comment]
This is not a problem with SiriProxy, but with your setup.  

`Check the TERM environment variable.
Also make sure that the terminal is defined in the terminfo database.
Alternatively, set the TERMCAP environment variable to the desired
termcap entry.`

**Comment by bogaskilop** [comment]
till i waited for your replay   i downloaded your img file  and siri starts up :) 
but i do not have iPhone now to test it so  i try with android phone and siriuos ! android siri client  but when i connect i see in console that it is conected but client on phone hangs :(  

root@raspberrypi:~/.siriproxy# siriproxy server -l config.yml.org
WARN: Unresolved specs during Gem::Specification.reset:
      rake (>= 0)
      rubydns (~> 0.6.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
[Info - Configuration] Loading plugins -- If any fail to load, run `siriproxy bundle` (not `bundle install`) to resolve.
[Notice - Server] ======================= WARNING: Running as root =============================
[Notice - Server] You should use -l or the config.yml to specify and non-root user to run under
[Notice - Server] Running the server as root is dangerous.
[Notice - Server] ==============================================================================
[Info - Server] Starting SiriProxy on 0.0.0.0:443...
[Info - Server] SiriProxy up and running.
[Info - Guzzoni] Starting conneciton #<SiriProxy::Connection::Iphone:0xbdcdb0 @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0xbdcae0 @dictionaries={}>, @zip_stream=#Zlib::Deflate:0xbdcab0, @consumed_ace=false, @name="iPhone", @upstream_dns=["8.8.8.8", "8.8.4.4"], @ssled=false>

and thats all   also i do not know if i nee to put this ca.pem in my phone but when i try to open it or install i cant do it  :( 

and sirious not provide any support  for siri proxy :( 

http://www.siriclient.com/

**Comment by elvisimprsntr** [comment]
Sorry, but you are better off finding a native voice assistant on Android and figuring out how to intercept the protocol.    I'm going to close this issue since it is not specific to siriproxy using a sanctioned apple device.
