### ISSUE TITLE
HOW I CAN....

### ISSUE THREAD

**Issue by HaTe87** [plamoni/SiriProxy#506]
how i can call in siriproxy a custom programm created with python ??

**Comment by eugeene** [comment]
do you mean http://tech.natemurray.com/2007/03/ruby-shell-commands.html ?

**Comment by HaTe87** [comment]
no...
i will create a program with python and who i can call it in siriproxy-example.rb?

**Comment by elvisimprsntr** [comment]
Since your question is not specific to siriproxy, I suggest you search for similar questions at stackoverflow.  

http://stackoverflow.com/questions/3679501/calling-python-from-ruby
