### ISSUE TITLE
"ignoring" the config.yml file

### ISSUE THREAD

**Issue by eugeene** [plamoni/SiriProxy#507]
when i copy the config.example.yml to ~/.siriproxy/config.yml and then do

rvmsudo siriproxy server -d myip -u myuser

siriproxy still searches for the /root/.siriproxy/config.yml not the one in myuser folder

after copying it to root's folder - everything starts ok

am I doing something wrong?

raspberry pi wirh raspbian wheezy

**Comment by Deanmv** [comment]
You need to rename config.example.yml to config.yml when you move it.

Then run `rvmsudo siriproxy bundle` and all should be ok.

**Comment by eugeene** [comment]
yes, I renamed the file but still having this:

[Notice - Configuration] ==================== Important Configuration Notice ==========================
[Notice - Configuration] '/root/.siriproxy/config.yml' not found. Using '/home/pi/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.2/config.example.yml'

it's totally ignoring the ~/.siriproxy/config.yml

**Comment by elvisimprsntr** [comment]
try dropping the -u option

Elvis

On Apr 10, 2013, at 7:14 AM, Robin Martinez notifications@github.com wrote:

yes, I renamed the file but still having this:

[Notice - Configuration] ==================== Important Configuration Notice ==========================
[Notice - Configuration] '/root/.siriproxy/config.yml' not found. Using '/home/pi/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.2/config.example.yml'

it's totally ignoring the ~/.siriproxy/con

fig.yml

**Comment by eugeene** [comment]
thank you, but, unfortunately, no luck and still having the same err... :/

**Comment by elvisimprsntr** [comment]
look for a directory or file permission issue
Elvis

On Apr 10, 2013, at 7:22 AM, Robin Martinez notifications@github.com wrote:

thank you, but, unfortunately, no luck and still having the same err... :/

**Comment by eugeene** [comment]
pi@raspi ~/.siriproxy $ ls -la
total 12
drwxr-xr-x  2 pi pi 4096 Apr 10 13:24 .
drwxr-xr-x 15 pi pi 4096 Apr 10 13:23 ..
-rw-r--r--  1 pi pi 1380 Apr 10 13:25 config.yml

so I think everything should be ok? :/

**Comment by elvisimprsntr** [comment]
not enough info.  back up a directory and look at the permission on the .siriproxy folder

did you install siriproxy yourself or are you using my SD card image?

how did you install rvm, ruby, siriproxy, i.e. as root, as a user, sudo?

Elvis

On Apr 10, 2013, at 7:47 AM, Robin Martinez notifications@github.com wrote:

pi@raspi ~/.siriproxy $ ls -la
total 12
drwxr-xr-x 2 pi pi 4096 Apr 10 13:24 .
drwxr-xr-x 15 pi pi 4096 Apr 10 13:23 ..
-rw-r--r-- 1 pi pi 1380 Apr 10 13:25 config.yml

so I think everything should be ok? :/

**Comment by eugeene** [comment]
drwxr-xr-x  2 pi   pi    4096 Apr 10 13:24 .siriproxy

i installed it via these instructions: https://github.com/plamoni/SiriProxy

the thing is, that everything is working okay (haven't tested with a phone yet), it's just searching the config file in root's directory instead my own home dir.

btw. thank you for helping

**Comment by elvisimprsntr** [comment]
I've never had complete trouble free installation with everything installed as a user.  Thus I install everything as root.  

http://sourceforge.net/p/siriproxyrpi/wiki/Home/

Elvis

On Apr 10, 2013, at 7:57 AM, Robin Martinez notifications@github.com wrote:

drwxr-xr-x 2 pi pi 4096 Apr 10 13:24 .siriproxy

i installed it via these instructions: https://github.com/plamoni/SiriProxy

the thing is, that everything is working okay (haven't tested with a phone yet), it's just searching the config file in root's directory instead my own home dir.

btw. thank you for helping

**Comment by eugeene** [comment]
I'll check on that! Thank you for your help. Will inform you later how did it go...

**Comment by elvisimprsntr** [comment]
closed due to inactivity
