### ISSUE TITLE
SiriProxy in Spanish

### ISSUE THREAD

**Issue by dflechas** [plamoni/SiriProxy#509]
Thanks Plamoni, your Set-up Instructions works perfectly!!! The only issue is that i always have to set Siri´s Language to English to make the plugin starts, then switch to spanish. Is there any way to solve this?

Thanks

dflechas

**Comment by franklindee** [comment]
hi does it work in your language?
thank you

**Comment by dflechas** [comment]
It works perfectly!!!

Enviado desde mi iPhone
