### ISSUE TITLE
Only "tamper" when hear keyword.

### ISSUE THREAD

**Issue by mcristina422** [plamoni/SiriProxy#51]
edit

**Comment by plamoni** [comment]
This can be easily done with `listen_for /iPhone (command)/ do |command|`. Anyway, it's not an issue either way. :-)

**Comment by plamoni** [comment]
You should find a way to do that programmatically. It shouldn't be too hard. Just override listen_for if you need to. At the very least, make the prefix a variable so you can modify/add/remove it as needed. This is a basic programming question, not an issue with our code. Sorry. Hit up Google if you need more help with how to program in Ruby.
