### ISSUE TITLE
My plugin doesn't load, but siriproxy doesn't say why

### ISSUE THREAD

**Issue by iamleeg** [plamoni/SiriProxy#510]
Using the latest master:

> $  siriproxy update .
> […]
> Using siriproxy-my-plugin (0.0.1) from source at /absolute/path/to/siriproxy-my-plugin
> Your bundle is complete!
> Use `bundle show [gemname]` to see where a bundled gem is installed.
> === SUCCESS ===
> 
> $ rvmsudo siriproxy server -d 192.168.0.5 -u nobody -l 1000
> […]
> [Error] Failed to load plugin: my-plugin
> […]

There's no backtrace and no other information about why this plugin didn't load, and I'm far from being a ruby expert so it's hard for me to diagnose without any assistance.

Would it be possible to add more helpful diagnostics on plugin failure (and, in the meantime, does anyone have any hints regarding why a bundled and configured plugin would fail to load?)

**Comment by iamleeg** [comment]
Having logged the exception message (see the pull in #511), I see this:

> [Error] Failed to load plugin: my-plugin reason: wrong constant name my-plugin

Where do I go from there?

**Comment by iamleeg** [comment]
OK, sorry for talking to myself in your issue tracker :-). You're not allowed to call a plugin `my-plugin`, it needs to be capitalised and have no punctuation like MyPlugin. Could I please request that the additional diagnostic logging still be integrated to help diagnose that?

**Comment by elvisimprsntr** [comment]
Those naming conventions are not unique to SiriProxy.  They are particular to Ruby itself.  I suggest you pick of a good Ruby book or watch some Ruby tutorials on YouTube.

**Comment by iamleeg** [comment]
Sure, I appreciate that the error was due to my config file being non-conformant: although it _is_ particular to SiriProxy in that SiriProxy chooses to interpret plugin names as ruby constants, not as strings (another natural choice for names). But it'd still be great to be told _how_ I messed up.

**Comment by elvisimprsntr** [comment]
I'll look at your pull request and bounce off Pete

Elvis

**Comment by elvisimprsntr** [comment]
fixed with pull request #511
