### ISSUE TITLE
Siriproxy don't update localy for example editing

### ISSUE THREAD

**Issue by HaTe87** [plamoni/SiriProxy#513]
hi.
i have edited my siriproxy-example.rb , when i try to update siriproxy i recived that:
root@raspberrypi:~# siriproxy update .
=== Installing from '.' ===
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/usr/local/rvm/gems/ruby-2.0.0-p0/gems/rake-10.0.4/lib/rake/application.rb:584:in `raw_load_rakefile'
/usr/local/rvm/gems/ruby-2.0.0-p0/gems/rake-10.0.4/lib/rake/application.rb:89:in`block in load_rakefile'
/usr/local/rvm/gems/ruby-2.0.0-p0/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.0.0-p0/gems/rake-10.0.4/lib/rake/application.rb:88:in`load_rakefile'
/usr/local/rvm/gems/ruby-2.0.0-p0/gems/rake-10.0.4/lib/rake/application.rb:72:in `block in run'
/usr/local/rvm/gems/ruby-2.0.0-p0/gems/rake-10.0.4/lib/rake/application.rb:160:in`standard_exception_handling'
/usr/local/rvm/gems/ruby-2.0.0-p0/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
/usr/local/rvm/gems/ruby-2.0.0-p0/bin/ruby_noexec_wrapper:14:in`eval'
/usr/local/rvm/gems/ruby-2.0.0-p0/bin/ruby_noexec_wrapper:14:in `<main>'
(See full trace by running task with --trace)

do i  something wrong?

**Comment by elvisimprsntr** [comment]
try dropping the `.`
also copy the siriproxy.example.yml file to /root/.siriproxy/config.yml if you haven't already.

**Comment by HaTe87** [comment]
nothing... same error... and now siriproxy don't work..i think there's some problem with the 0.5.4 release

**Comment by elvisimprsntr** [comment]
no problem with 0.5.4 here.  siriproxy installation can very easily get messed up if one types commands out of order, in an incorrect directory, or incorrect commands.  Unfortunately, not knowing exactly what commands you have typed, it is difficult to determine exactly what is messed up.  

my recommendation for you is to 
1. reformat the SD card
2. write the image
3. perform `siriproxy update` or `gem install siriproxy -v 0.5.4`

then confirm siriproxy working before starting to modify things.   I think you are making more difficult than it really is.

**Comment by elvisimprsntr** [comment]
also you are much better off not messing with the example plugin and simply adding your own.  this one provides the basic minimum set of files to get started.  

https://github.com/elvisimprsntr/siriproxy-rpi

**Comment by HaTe87** [comment]
i change " siri proxy up and running " into " siri proxy attivo".
i try to reinstall totaly but the problem is the same.and now the proxy dosen't wor..it's freezed on siri proxy up and running and don't do nothing

**Comment by elvisimprsntr** [comment]
simply telling me "it don't work" does not provide enough information to help you.  

the message `siriproxy up and running` is where it will stop until you launch siri on the device.   if you do not see any packets, then you don't have your device configured correctly or you don't have either dnsmasq configured or you did not use the -d option when starting siriproxy.  also turn off cellular data and toggle airplane mode off for 5 seconds as it is known that siri will leak over the cellular connection if on.  you also need to make sure you have a matched set of certificates between the phone and siriproxy.   this is all in the instructions.  also, like i said before lets get siriproxy working WITHOUT modifications.

**Comment by HaTe87** [comment]
i have reinstalled the image on the sd from 0 and now the server is runnong , but if i run update . it still return me :
root@raspberrypi:~# siriproxy update .
=== Installing from '.' ===
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/usr/local/rvm/gems/ruby-2.0.0-p0/gems/rake-10.0.4/lib/rake/application.rb:584:in `raw_load_rakefile'
/usr/local/rvm/gems/ruby-2.0.0-p0/gems/rake-10.0.4/lib/rake/application.rb:89:in`block in load_rakefile'
/usr/local/rvm/gems/ruby-2.0.0-p0/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.0.0-p0/gems/rake-10.0.4/lib/rake/application.rb:88:in`load_rakefile'
/usr/local/rvm/gems/ruby-2.0.0-p0/gems/rake-10.0.4/lib/rake/application.rb:72:in `block in run'
/usr/local/rvm/gems/ruby-2.0.0-p0/gems/rake-10.0.4/lib/rake/application.rb:160:in`standard_exception_handling'
/usr/local/rvm/gems/ruby-2.0.0-p0/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
/usr/local/rvm/gems/ruby-2.0.0-p0/bin/ruby_noexec_wrapper:14:in`eval'
/usr/local/rvm/gems/ruby-2.0.0-p0/bin/ruby_noexec_wrapper:14:in `<main>'
(See full trace by running task with --trace)

and i have already copy the siriproxy.example.yml file to /root/.siriproxy/config.yml

**Comment by elvisimprsntr** [comment]
as i mentioned before don't use the "."

**Comment by HaTe87** [comment]
without the "." it dosen't apply the change to my example.rb

**Comment by elvisimprsntr** [comment]
because the `siriproxy update` command is to update the version of siriproxy itself.  
type `siriproxy -v` to confirm it is configured for 0.5.4.  

again, get siriproxy working first before you start messing with files.   if you do not want to follow  my advice and continue to flail around I will no longer be able to help you.

**Comment by HaTe87** [comment]
if i do gem install siriproxy -v 0.5.4 the proxy work fine without any modification

**Comment by elvisimprsntr** [comment]
good!  then it's not a problem with siriproxy or the SD card image.  now that we have that out of the way, what exactly are you trying to do?
1. what complete path and filename are you trying to modify?
2. what changes did you make?
3. did you run `siriproxy bundle` after making the changes?
4. did the changes persist?
5. have you tried `siriproxy console`?

**Comment by elvisimprsntr** [comment]
i just made changes to the
`/usr/local/rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/plugins/siriproxy-example/lib/siriproxy-example.rb`
and performed
`siriproxy bundle`
and the changes took

**Comment by elvisimprsntr** [comment]
again, if you want to write your own or use other plugins, modifying the siriproxy-example.rb file is not the correct way to do it.

**Comment by elvisimprsntr** [comment]
i'm going to close this one since it is neither a problem with siriproxy or the RPi SD card image.
