### ISSUE TITLE
SOLVED: geocoder 1.1.7 gem bug (require rack/utils)

### ISSUE THREAD

**Issue by elvisimprsntr** [plamoni/SiriProxy#514]
We are currently looking into a new dependency compatibility issue with cora and geocoder.   Geocoder released 1.1.7 gem today which is causing problems. Please stand by...

Affected users:
1. new installations
2. siriproxy update/bundle which results in installing geocoder 1.1.7

Symptoms are as follows:
`root@raspberrypi:~# siriproxy server
WARN: Unresolved specs during Gem::Specification.reset:
      geocoder (>= 0)
      rake (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
[Info - Configuration] Loading plugins -- If any fail to load, run`siriproxy bundle`(not`bundle install`) to resolve.
/usr/local/rvm/gems/ruby-2.0.0-p0/gems/geocoder-1.1.7/lib/geocoder/lookups/esri.rb:3:in`require': cannot load such file -- rack/utils (LoadError)
    from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/geocoder-1.1.7/lib/geocoder/lookups/esri.rb:3:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/geocoder-1.1.7/lib/geocoder/lookup.rb:82:in`require'
    from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/geocoder-1.1.7/lib/geocoder/lookup.rb:82:in `block in <top (required)>'
    from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/geocoder-1.1.7/lib/geocoder/lookup.rb:81:in`each'
    from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/geocoder-1.1.7/lib/geocoder/lookup.rb:81:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/geocoder-1.1.7/lib/geocoder.rb:7:in`require'
    from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/geocoder-1.1.7/lib/geocoder.rb:7:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/cora-0.0.4/lib/cora/location.rb:1:in`require'
    from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/cora-0.0.4/lib/cora/location.rb:1:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/cora-0.0.4/lib/cora.rb:3:in`require'
    from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/cora-0.0.4/lib/cora.rb:3:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/lib/siriproxy/plugin.rb:1:in`require'
    from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/lib/siriproxy/plugin.rb:1:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/lib/siriproxy/command_line.rb:225:in`require'
    from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/lib/siriproxy/command_line.rb:225:in `load_code'
    from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/lib/siriproxy/command_line.rb:88:in`run_server'
    from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/lib/siriproxy/command_line.rb:39:in `initialize'
    from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/bin/siriproxy:6:in`new'
    from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/bin/siriproxy:6:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-2.0.0-p0/bin/siriproxy:23:in`load'
    from /usr/local/rvm/gems/ruby-2.0.0-p0/bin/siriproxy:23:in `<main>'
    from /usr/local/rvm/gems/ruby-2.0.0-p0/bin/ruby_noexec_wrapper:14:in`eval'
    from /usr/local/rvm/gems/ruby-2.0.0-p0/bin/ruby_noexec_wrapper:14:in `<main>'`

**Comment by elvisimprsntr** [comment]
problem isolated to a bug in geocoder 1.1.7.         Leaving open until new geocoder gem is pushed

see the steps to correct  until new gem is available.
https://github.com/alexreisner/geocoder/issues/446

**Comment by alexreisner** [comment]
@elvisimprsntr I just released Geocoder version 1.1.8 which should resolve this issue. Sorry about that!

**Comment by elvisimprsntr** [comment]
@alexreisner Gracias!  Confirmed geocoder 1.1.8 works with SiriProxy.   I'm going to leave this open for awhile to minimize duplicates.
