### ISSUE TITLE
Problem with siriproxy bundle

### ISSUE THREAD

**Issue by evasuarez22** [plamoni/SiriProxy#515]
I have working the siri proxy, but when I try to execute siriproxy bundle I have this error:

ERROR: Gem bundler is not installed, run `gem install bundler` first.

So, next I try gem install bundler, and It seems to install it:

Successfully installed bundler-1.3.5
Parsing documentation for bundler-1.3.5
1 gem installed

Then, I try siriproxy bundle and I have the same error. Can you help me, please?

**Comment by elvisimprsntr** [comment]
1. What OS are you installing on? 
2. Linux, macos, windows
3. What instructions did you use to install everything?
4. provide link
5. How did you install ruby and SiriProxy?
6. root or user
7. gem or clone 
8. What commands do you use to launch SiriProxy?
9. Did you test SiriProxy before making any modifications?

**Comment by evasuarez22** [comment]
I use Ubuntu 12 running on Virtual Box, and I have use to install SiriProxy and Ruby the instructions given at the plamoni's site:

https://github.com/plamoni/SiriProxy

So now I have Ruby 2.0.0 and SiriProxy 0.5.4.
I'm root and I use gems, to launch SiriProxy I use the next command:

rvmsudo siriproxy server -d XXX.XXX.XXX.XXX -u nobody

I tested Siriproxy before making modifications and all was ok. Also SiriProxy works fine with my modifications.

Thanks

**Comment by elvisimprsntr** [comment]
`I tested Siriproxy before making modifications and all was ok. Also SiriProxy works fine with my modifications.`

Sounds like you solved your own problem.  Thanks for updating.
