### ISSUE TITLE
Errors in event machine, Initialize, start servedr....

### ISSUE THREAD

**Issue by Dageek4590** [plamoni/SiriProxy#516]
Ok so I installed a fresh copy of Ubuntu server 12.10. I ran thorugh the setup instructions for siriproxy and installed ca on my phone. everything worked great untl i held the home button and my phone hit the sirproxy server. I got a ton of errors. Now I searched and followed every suggestion i could find on the forums and around the web. I am running latest code 0.5.4. I have reinstalled the os several times and started from scratch only to be met with the same problems. Below is a screen shot of the console:

![siriError](https://f.cloud.github.com/assets/4257561/426468/dca6bb42-adc9-11e2-8122-0c1dff9fae2e.PNG)

**Comment by elvisimprsntr** [comment]
1. Post the list of dependencies when you perform siriproxy bundle
2. Did you make any changes to the example plugin or add new plugins?
3. Post the output beginning from the command you type to launch siriproxy.

**Comment by Dageek4590** [comment]
I did not change anything or install any other plugins. As for posting whats in the window I am running it in esxi vmware and am yet to figure out how to copy and paste. If ya got teamviewer I would be happy to let ya in

**Comment by Dageek4590** [comment]
Well after all that mess I got it working. I think but am not 100% positive that it was this:
When I bundled I was using rvmsudo siriproxy bundle. This last time for some reason I just typed siriproxy bundle, then started the server and it all worked.

My mistake. Thank you though.
