### ISSUE TITLE
Call my custon python program in Siriproxy

### ISSUE THREAD

**Issue by HaTe87** [plamoni/SiriProxy#518]
Hi, 
i have installed Rupy to call a python program in ruby on my SiriProxy , but when i try to callback my program ( /root/p.py) i recived an error and i'm not able to understand it.
i have put :
require 'rupy'
and
  listen_for /movimento/i do
    say "Vado!" #say something to the user!
    request_completed #
    RubyPython.start # start the Python interpreter
    cPickle = RubyPython.import("cPickle")
    puts cPickle.dumps("Testing RubyPython.").rubify
    RubyPython.stop # stop the Python interpreter
    end
in siriproxy-example.rb
but if i dont' put # before require the proxy dosen't work 
if i put the # i recived
[Info - iPhone] Received Object: FinishSpeech
[Info - Guzzoni] Received Object: SpeechRecognized
[Info - Plugin Manager] Processing 'Movimento'
[Info - Plugin Manager] Processing plugin Example
[Info - Plugin Manager] Matches (?i-mx:movimento)
[Info - Plugin Manager] Applicable states: 
[Info - Plugin Manager] Current state: 
[Info - Plugin Manager] Matches, executing block
[Info - Plugin Manager] Say: Vado!
[Info - Plugin Manager] Sending Request Completed
[Info - Plugin Manager] Plugin Crashed: uninitialized constant SiriProxy::Plugin::Example::RubyPython
can anyone help me?

**Comment by elvisimprsntr** [comment]
This issues tracker is for problems with SiriProxy itself, not an open forum for how to program in Ruby.  I suggest you seek a Ruby specific forum for your question, ie stackoverflow.  Regardless, if it were me I would change cPickle variable to all lower case, ie. cpickle
