### ISSUE TITLE
Gemfile?

### ISSUE THREAD

**Issue by ishaper** [plamoni/SiriProxy#52]
Hi,

I have done everything according the readme but I am stuck on this:

hoff$ rvm use 1.9.3

Using /Users/hoff/.rvm/gems/ruby-1.9.3-p0

iShaper:~ hoff$ gem install bundler

/Users/hoff/.rvm/rubies/ruby-1.9.3-p0/bin/gem:4: warning: Insecure world writable dir /usr/local in PATH, mode 040777
Successfully installed bundler-1.0.21

1 gem installed

Installing ri documentation for bundler-1.0.21...

Installing RDoc documentation for bundler-1.0.21...

iShaper:~ pepynhoff$ bundle install

Could not locate Gemfile

-- Can someone help me with this? I really don't know what to do!

**Comment by netpro2k** [comment]
you need to run `bundle install` from the SiriProxy directory

**Comment by ishaper** [comment]
Thanks it worked!
