### ISSUE TITLE
siriproxy iphone 5 

### ISSUE THREAD

**Issue by franklindee** [plamoni/SiriProxy#522]
hi all,
do you know if i can set it in the italian language?

i would like to start the project of domotic home with siri in italian do you know if is possible?
it goes automatically in the phone language and i need to change the command code in italian
thank you

**Comment by pippolino** [comment]
You do not have to change the language of Siri. Siri will interpret your commands which then pass to siriproxy. Your plugin will have the rule and in accordance with these rules will perform the actions. These rules may be in Italian or other languages​​. For example:

``` ruby
listen_for /turn on tv/ i do
```

or

``` ruby
listen_for /accendi tv/ i do
```
