### ISSUE TITLE
can'T get my siriproxy work

### ISSUE THREAD

**Issue by karlbarre** [plamoni/SiriProxy#523]
I can't figure what's wrong with my instalation, did everything as written and still get somme error like this:

karlbarre@ubuntu:~$ rvmsudo siriproxy server -d 192.158.0.105 -u nobodyWarning: can not check `/etc/sudoers` for `secure_path`, falling back to call via `/usr/bin/env`, this breaks rules from `/etc/sudoers`. export rvmsudo_secure_path=1 to avoid the warning.[sudo] password for karlbarre: 
WARN: Unresolved specs during Gem::Specification.reset:
      rake (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
[Notice - Configuration] ==================== Important Configuration Notice ==========================
[Notice - Configuration] '/home/karlbarre/.siriproxy/config.yml' not found. Using '/home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/config.example.yml'
[Notice - Configuration] 
[Notice - Configuration] Remove this message by copying '/home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/config.example.yml' into '~/.siriproxy/'
[Notice - Configuration] ==============================================================================
[Info - Configuration] Loading plugins -- If any fail to load, run `siriproxy bundle` (not `bundle install`) to resolve.
[Info - Server] Starting SiriProxy on 0.0.0.0:443...
[Info - Server] DNS server is not running yet, waiting 1 second...
[Error - Server] Either you're not root or tcp/udp port 53 is in use. DNS server is disabled
[Info - Server] SiriProxy up and running.
^C/home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine': Interrupt
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in`run'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/lib/siriproxy.rb:17:in `initialize'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/lib/siriproxy/command_line.rb:106:in`new'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/lib/siriproxy/command_line.rb:106:in `start_server'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/lib/siriproxy/command_line.rb:90:in`run_server'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/lib/siriproxy/command_line.rb:39:in `initialize'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/bin/siriproxy:6:in`new'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/bin/siriproxy:6:in `<top (required)>'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/bin/siriproxy:23:in`load'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/bin/siriproxy:23:in `<main>'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/bin/ruby_noexec_wrapper:14:in`eval'

what did I do wrong ? it was a fresh instal and took the ip adress of my virtual machine

thx a lot for your help, working on a projet and trying to install a siriproxy for months

**Comment by elvisimprsntr** [comment]
the error message is in the log output
type `export rvmsudo_secure_path=1`

**Comment by karlbarre** [comment]
still get this :+1: 

karlbarre@ubuntu:~$ export rvmsudo_secure_path=1
karlbarre@ubuntu:~$ rvmsudo siriproxy server -d 192.168.0.106 -u karlbarre[sudo] password for karlbarre: 
[Notice - Configuration] ==================== Important Configuration Notice ==========================
[Notice - Configuration] '/home/karlbarre/.siriproxy/config.yml' not found. Using '/home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/config.example.yml'
[Notice - Configuration] 
[Notice - Configuration] Remove this message by copying '/home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/config.example.yml' into '~/.siriproxy/'
[Notice - Configuration] ==============================================================================
[Info - Configuration] Loading plugins -- If any fail to load, run `siriproxy bundle` (not `bundle install`) to resolve.
[Info - Server] Starting SiriProxy on 0.0.0.0:443...
/home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/eventmachine-1.0.3/lib/eventmachine.rb:526:in `start_tcp_server': no acceptor (port is in use or requires root privileges) (RuntimeError)
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/eventmachine-1.0.3/lib/eventmachine.rb:526:in`start_server'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/lib/siriproxy.rb:28:in `block in initialize'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in`call'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in`run'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/lib/siriproxy.rb:17:in `initialize'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/lib/siriproxy/command_line.rb:106:in`new'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/lib/siriproxy/command_line.rb:106:in `start_server'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/lib/siriproxy/command_line.rb:90:in`run_server'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/lib/siriproxy/command_line.rb:39:in `initialize'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/bin/siriproxy:6:in`new'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/bin/siriproxy:6:in `<top (required)>'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/bin/siriproxy:23:in`load'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/bin/siriproxy:23:in `<main>'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/bin/ruby_noexec_wrapper:14:in`eval'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/bin/ruby_noexec_wrapper:14:in `<main>'
karlbarre@ubuntu:~$ 

how can i resolve this ?

thank you very much for your help,

**Comment by elvisimprsntr** [comment]
Try dropping the -u option 

Elvis

**Comment by karlbarre** [comment]
karlbarre@ubuntu:~$ rvmsudo siriproxy server -d 192.168.0.106
[Notice - Configuration] ==================== Important Configuration Notice ==========================
[Notice - Configuration] '/home/karlbarre/.siriproxy/config.yml' not found. Using '/home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/config.example.yml'
[Notice - Configuration] 
[Notice - Configuration] Remove this message by copying '/home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/config.example.yml' into '~/.siriproxy/'
[Notice - Configuration] ==============================================================================
[Info - Configuration] Loading plugins -- If any fail to load, run `siriproxy bundle` (not `bundle install`) to resolve.
[Notice - Server] ======================= WARNING: Running as root =============================
[Notice - Server] You should use -l or the config.yml to specify and non-root user to run under
[Notice - Server] Running the server as root is dangerous.
[Notice - Server] ==============================================================================
[Info - Server] Starting SiriProxy on 0.0.0.0:443...
/home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/eventmachine-1.0.3/lib/eventmachine.rb:526:in `start_tcp_server': no acceptor (port is in use or requires root privileges) (RuntimeError)
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/eventmachine-1.0.3/lib/eventmachine.rb:526:in`start_server'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/lib/siriproxy.rb:28:in `block in initialize'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in`call'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in`run'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/lib/siriproxy.rb:17:in `initialize'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/lib/siriproxy/command_line.rb:106:in`new'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/lib/siriproxy/command_line.rb:106:in `start_server'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/lib/siriproxy/command_line.rb:90:in`run_server'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/lib/siriproxy/command_line.rb:39:in `initialize'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/bin/siriproxy:6:in`new'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/bin/siriproxy:6:in `<top (required)>'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/bin/siriproxy:23:in`load'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/bin/siriproxy:23:in `<main>'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/bin/ruby_noexec_wrapper:14:in`eval'
    from /home/karlbarre/.rvm/gems/ruby-2.0.0-p0/bin/ruby_noexec_wrapper:14:in `<main>'
karlbarre@ubuntu:~$ 

getting that. is that part a problem 
[Info - Server] Starting SiriProxy on 0.0.0.0:443...
/home/karlbarre/.rvm/gems/ruby-2.0.0-p0/gems/eventmachine-1.0.3/lib/eventmachine.rb:526:in `start_tcp_server': no acceptor (port is in use or requires root privileges) (RuntimeError)

?? don't know how to fix it

thx again

**Comment by karlbarre** [comment]
just made it work while looking at issue Issue #475

**Comment by karlbarre** [comment]
w can i make it permanently work ? i have been using that to make it work

dnsmasq 1153 nobody    5u  IPv4  10011      0t0  TCP ubuntu:domain (LISTEN)
karlbarre@ubuntu:~$ sudo kill 1153

**Comment by elvisimprsntr** [comment]
You need to uninstall dnsmasq
`apt-get purge dnsmasq`

You need to use dnsmasq or specify the -d option for SiriProxy, not both. 

Elvis
