### ISSUE TITLE
How to output multiple "say" commands and dont hide the first ones

### ISSUE THREAD

**Issue by shakaraba** [plamoni/SiriProxy#525]
Hi,

when i put this:

listen_for /hello/i do
  say "Hello"
  say "123"
  say "Goodbye"
  request_completed
end

It output the three commands to the iPhone, but the two first are hidden very quickly.

If i put a request_completed after each say, it will only execute the first say.

I want to display each message in a separate box and display all of them as seen in this video (0:28):

http://www.youtube.com/watch?v=W7D6lyqdlMc

Any clue in how to achieve this?

Thanks!

**Comment by hey101** [comment]
I took their example for the test map and modified it. I don't know if this is the best way but it definitely works:

  listen_for /hello/i do
    add_views = SiriAddViews.new
    add_views.make_root(last_ref_id)
    utterance = SiriAssistantUtteranceView.new("How are you?")
    utterance2 = SiriAssistantUtteranceView.new("Doing good")
    add_views.views << utterance
    add_views.views << utterance2

```
send_object add_views #send_object takes a hash or a SiriObject object
request_completed
```

  end

**Comment by elvisimprsntr** [comment]
Glad you found a method

**Comment by shakaraba** [comment]
Works perfectly, 

thanks!
