### ISSUE TITLE
SiriProxy Started but nothing happens

### ISSUE THREAD

**Issue by hey101** [plamoni/SiriProxy#526]
I followed the install guide here: http://www.modernhoot.com/157/how-to-install-siriproxy-on-ubuntu-12-10/

I got the siriproxy up and running, but on my iPhone 5 it does nothing. I turned airplane mode on and wifi on. I set the dns in the iphone settings and when I tell siri something, it will eventually say that it cannot take any requests right now. If I open safari and go to the computer ip and port only one line of code appears below siriproxy up and running and that is:
[Info - Plugin Manager] Plugins loaded: Example

Nothing else happens. A blank page in safari is loaded and that is it. Any ideas on what may have gone wrong or something that I may need to change?

This is all that I see:
hey101@ubuntu:~$ rvmsudo siriproxy server
WARN: Unresolved specs during Gem::Specification.reset:
      rake (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
[Info - Configuration] Loading plugins -- If any fail to load, run `siriproxy bundle` (not `bundle install`) to resolve.
[Notice - Server] ======================= WARNING: Running as root =============================
[Notice - Server] You should use -l or the config.yml to specify and non-root user to run under
[Notice - Server] Running the server as root is dangerous.
[Notice - Server] ==============================================================================
[Info - Server] Starting SiriProxy on 192.168.1.46:443...
[Info - Server] SiriProxy up and running.
[Info - Plugin Manager] Plugins loaded: Example

**Comment by elvisimprsntr** [comment]
1. Those instructions are a bit out if date.  SiriProxy version is 0.5.4. Hopefully you caught that. 
2. I assume you installed the ca.pem file on your phone. 
3. You need to use dnsmasq or specify the -d option when launching SiriProxy. 
4. When your phone connects the first time it may take a bit longer and might require a couple of attempts.   Be patient.

**Comment by hey101** [comment]
I did notice the version difference and I did install the ca.pem. When I use the -d option, do I use googles DNS or the ip of the computer? As to being patient and trying a couple of times, I have tried 15 times each with both the google dns and using my own ip. Each time I still get the same response of siri cant respond.

**Comment by hey101** [comment]
I dont know what I just did but it started working... Thanks

**Comment by elvisimprsntr** [comment]
You need to use the IP address of your host computer.  

Elvis
