### ISSUE TITLE
Send iMessage

### ISSUE THREAD

**Issue by davidvasandani** [plamoni/SiriProxy#527]
Is it possible to send an SMS/iMessage via a SiriProxy plugin? My GoogleFu is turning up zilch.

**Comment by elvisimprsntr** [comment]
Yes.  Look at the plugins page or google search

**Comment by davidvasandani** [comment]
Elvis I swear by all my internet karma that I tried. Can you maybe point me in the right direction or a better place to ask this question. Here is a video of Siri opening my roof https://www.dropbox.com/s/un2yj9pn7n1i4sd/IMG_0112.MOV

**Comment by elvisimprsntr** [comment]
Since Siri already supports sending SMS messages I think it's not necessary for a SiriProxy plugin.

**Comment by davidvasandani** [comment]
I wanted to pull data from the Internet and then wanted the ability to send that data via iMessage. An example would be "Siri, send 100 cat pictures to Travis" and using a cat picture api 100 cats are returned to the iPhone and then sends as an iMessage. I Googled for hours and found not a single reference to this.
—

**Comment by elvisimprsntr** [comment]
While it sounds funny you are spamming.  Ethically I can't help you with that.   But good luck.

**Comment by davidvasandani** [comment]
How about "Siri, text Travis the latest Apple stock." I just thought my last example was funnier.

**Comment by elvisimprsntr** [comment]
https://github.com/Ponyboy47/siriproxy-googlevoice

**Comment by elvisimprsntr** [comment]
http://blog.revathskumar.com/2012/02/how-to-use-sendsms-gem.html?m=1

**Comment by davidvasandani** [comment]
These are good ways to send SMS's via Google Voice and way2sms.com. I'm looking for a way to send an SMS/iMessage via the iPhone itself. I understand what you meant when you said the iPhone already does this and it would be duplicating functionality but I'm looking for the ability to build the content of the text message via information on the internet. Two more examples, "Text Jenny a picture of a rose." or "Text Jerry my current location".
