### ISSUE TITLE
Port 53 DNS disable

### ISSUE THREAD

**Issue by ingeniero2005** [plamoni/SiriProxy#529]
Hi, i have a problem i buy a raspberrypi but when i try to install siriproxy that show the next error: port 53 in use DNS disable. Im not use a PC i only use a raspberry pi card. I follow all the instructions in the https://github.com/plamoni/SiriProxy but nothing. I try yo use the netstat, ps -ef | grep -i dnsmasq only of with sudo and raspberry pi say that this command not exist. What can i do please. !!!

**Comment by elvisimprsntr** [comment]
1. You need to have root permissions to open port 53.  Use rvmsudo
2. Or you are using both dnsmasq and are specifying the -d option.  Use only one.

**Comment by ingeniero2005** [comment]
Hi, i try the 2 forms and nothing.

First: i use rvmsudo and nothing, the same error appear
Second: i use the -d option without dnsmasq and nothing

That Form and nothing:

rvmsudo siriproxy server -d 192.168.1.106 -u nobody

**Comment by elvisimprsntr** [comment]
Post the log output starting with the command.

**Comment by ingeniero2005** [comment]
Either you´re not root or tcp/udp port 53 is in use. DNS Server is disabled

**Comment by elvisimprsntr** [comment]
Drop the -u option

**Comment by ingeniero2005** [comment]
the same problem without -u option....

**Comment by elvisimprsntr** [comment]
Are you getting the export warning message?

`export rvmsudo_secure_path=1`

Elvis

**Comment by elvisimprsntr** [comment]
You might try using my RPi SD card image with SiriProxy pre installed.

**Comment by ingeniero2005** [comment]
I buy a RPi SD Card but nothing....i have the same problem because i try with many posibilies. Sorry

**Comment by ingeniero2005** [comment]
What can be the problem

**Comment by ingeniero2005** [comment]
Elvis i use your RPi SD Card image

**Comment by ingeniero2005** [comment]
all the work and the problems I've had is working with your image, so you you can help me

**Comment by elvisimprsntr** [comment]
Again it's is difficult to help you without the full output log messages and not knowing what other commands you have typed when flailing around searching for a fix.  Unfortunately this is an all too common mistake. 

At this point, your options are:
1. Perform a clean install from scratch. 
2. Try my SD card image.  

As I have stated numerous times before and on may forums, I have the most luck installing and running everything as root.

**Comment by elvisimprsntr** [comment]
As I have repeatedly asked for but you won't provide, post the FULL output log NOT just what you think is important.

**Comment by ingeniero2005** [comment]
Why the netstat and other commands not work in RPi?

**Comment by ingeniero2005** [comment]
ps -ef | grep -i dnsmasq

The RPi say that the command not exist???, why

**Comment by elvisimprsntr** [comment]
how are your accessing the command line?  A console window, a terminal session, or SSH/putty from another machine?

**Comment by ingeniero2005** [comment]
Thanks Elvis i give you a resume:

I buy a Raspberry pi, an adapter, and 8 GB SD (10).
The first thing that i made was to download your SD image in my PC and copy that file in the SD.
Then i connected the keyboard (USB), Mouse (USB), Ethernet and the HDMI to the Raspberry.
I connected the other side of the HDMI cable to my TV.

I connected then the power to the Raspberry. In my TV i see the BIOS for first time and i made follow steps:
1. I expanded the memory
2. I enable the SSH
3. I Upgrade the Bios

Reboot the System and log me with "pi" and "Raspberry"

After i follow your instructions: https://github.com/plamoni/SiriProxy step by step
 (I don't modify the dnsmasq because in the instructions you Don't say nothing about that)

I Don't have errors in the siriproxy instalation.

When i run the siriproxy thr error appear: port 53 is in use and DNS desable.

I only work in my TV, no use a PC or aterminal session. I Don't know much about Linux but is important install the siriproxy. I hope you help. 

Thanks

**Comment by elvisimprsntr** [comment]
Let me address various concerns...
1. Not all SD cards work with the RPi, especially class 10, but if you have it working no need to change now.
2. My SD card image already has RVM, Ruby, and SiriProxy installed.  http://sourceforge.net/projects/siriproxyrpi/  You used the SD card image from http://www.raspberrypi.org/downloads  
3.  You followed Plamoni's instructions, not mine.  
4. You logged in as user pi, which my SD card image does not have.
5. I am guessing you logged in at the console prompt, which may not set up all the RVM, Ruby, and SiriProxy environment variables.  I recommend using you install putty on your Windows machine, and open an SSH session to your RPi.  http://www.chiark.greenend.org.uk/~sgtatham/putty/download.html  You only need the putty.exe  
6. Since you are new to Linux, I recommend you do a little reading or at least download the quick reference card.   http://www.debian.org/doc/user-manuals#refcard
7. I personally have never had completely trouble free installation and operation installing RVM, Ruby, and SiriProxy as a user account.   Thus, my SD card image has everything installed as root.  

How you proceed from here is up to you.

**Comment by ingeniero2005** [comment]
I have a question, if i work in the RPi (1 and 2 in yours concerns) i Don't understand because i need window with putty. Then:
1. I need take out the SD?
2. Install putty in win?
3. What made..

Sorry, im new in that.

**Comment by elvisimprsntr** [comment]
1. Boot your RPi with what every image you use with SSH enabled.
2. I assumed you are a Windows user since you admitted you are new to Linux.  Putty will allow to you open a terminal window connection to your RPi without the need to connect a monitor, keyboard, or mouse directly to the RPi,  Commonly referred to as a headless system.   Putty also allow you to scroll thru the window, copy, and paste text from the siriproxy log output.  If you are Mac OS user then all you need is the SSH command in a Mac OS command window.

**Comment by ingeniero2005** [comment]
Please can you explain me with more details, my english is not very golf and i am new in Linux. Rihanna for your patient.

**Comment by elvisimprsntr** [comment]
1. You have (or had) a SD card with a bootable image already on it.  
2. Boot the RPi (leave the monitor connected so you can see the boot process)
3. FInd the IP address your router assigned to you RPi or login to the console problem and type `hostname -I`
4. Install putty on your Windows PC.
5. Launch putty and use the username, password, and IP address of the RPi to open a terminal session to your RPi.
6. Now you can type commands as if you were at a keyboard connected directly to the RPi.

**Comment by ingeniero2005** [comment]
Then i have that work with the SD in my PC and install putty for control the raspberry?

**Comment by ingeniero2005** [comment]
Ahhh ok, how is the user and password in your SD image?

**Comment by elvisimprsntr** [comment]
read the instructions page for my SD card image on sourceforge.

**Comment by ingeniero2005** [comment]
In your page you Don't say nothing about the user and password?. Not need?

**Comment by elvisimprsntr** [comment]
Install SiriProxy on a SD card.
a. Download the SD image and follow the instructions to write to a SD card (>4GB): http://elinux.org/RPi_Easy_SD_Card_Setup NOTE: Read the Release News page for the default login credentials: https://sourceforge.net/p/siriproxyrpi/news/ 
b. Or, you can follow my instructions: https://gist.github.com/elvisimprsntr/4409751

**Comment by elvisimprsntr** [comment]
http://sourceforge.net/p/siriproxyrpi/news/2013/03/release-2013-03-22/

**Comment by ingeniero2005** [comment]
Hi Elvis, sorry, pleasei have two questions.

First: i don understand what its the user and password in your SD image.
Second: this link How can i use? http://sourceforge.net/p/siriproxyrpi/news/2013/03/release-2013-03-22/

**Comment by ingeniero2005** [comment]
Thanks

**Comment by elvisimprsntr** [comment]
Click on read more

Elvis

**Comment by ingeniero2005** [comment]
Read more?

User is Root and password siriproxy?

Or im in a mistake

**Comment by elvisimprsntr** [comment]
Yes

Elvis

**Comment by ingeniero2005** [comment]
A question, i need configure my router with a DD-WRT or that is not neccesary.

**Comment by elvisimprsntr** [comment]
Optional.  

You will have manually set the DNS entry on your phone to point to your SiriProxy server. 

Elvis

**Comment by ingeniero2005** [comment]
I have a Dlink Dir 300 and need use port forwarding to use the siriproxy?. In that moment o use the port forwarding to the 53 and 443 with the IP of Raspberry (192.168.1.106)

**Comment by elvisimprsntr** [comment]
Generally opening up ports is a bad idea.  I have read reports of other people trying to use port forwarding to use SiriProxy behind their router with not much success.  I use DD-WRT open source router firmware for a number of reasons, in particular to perform a transparent DNS redirect and VPN access.  Use at your own risk.

**Comment by ingeniero2005** [comment]
Elvis i try to download your image but is impossible, after 2 minutes the download stop, i try in diferents PCs and networks. You have a mirror o solution?. Thanks

**Comment by elvisimprsntr** [comment]
Sourceforge puts my file on 15-20 mirrors all over the world.  I have no control of which mirror it will download from, but generally it will be the closet one to you.   Sourceforge does on rare occasions have problems serving files.

**Comment by elvisimprsntr** [comment]
Over 4500 downloads to date and you are the only one who has reported a problem.

**Comment by ingeniero2005** [comment]
You have a other direction of secure mirror?

**Comment by elvisimprsntr** [comment]
As I mentioned over 4500 downloads you are the only one who has reported a problem.

**Comment by ingeniero2005** [comment]
Ok, sorry i can download the SD image, but please Don't angry was only a question.

**Comment by elvisimprsntr** [comment]
Just trying to point out to you there are other reasons why the problem might be occurring and try to avoid jumping to conclusions. 

Elvis

**Comment by ingeniero2005** [comment]
Ok, no problem, respect to the DD-WRT, i  use a port forwarding, this not work for use a siriproxy. Exist another for that not use a DD-WRT?

**Comment by elvisimprsntr** [comment]
The only way I know of or have read others successfully using SiriProxy from outside a LAN is thru a VPN.  How you choose to configure a VPN server on your local LAN is up to you.  I use dd-wrt 

Elvis

**Comment by ingeniero2005** [comment]
Elvis, if i only need the siriproxy in a LAN, need work with dd-wrt?

**Comment by elvisimprsntr** [comment]
If you don't need to access your SiriProxy server from outside of your local network the you don't need a VPN. You simply change the DNS entry  on your iOS device to point to your SiriProxy server. 

Elvis

**Comment by ingeniero2005** [comment]
Ok, when i login into raspberry pi what is the first thing or command that i make

**Comment by elvisimprsntr** [comment]
you really need to learn to read and follow the instructions on your own.  this issue has already been closed.
