### ISSUE TITLE
bundle install failed Help

### ISSUE THREAD

**Issue by johnnytai4** [plamoni/SiriProxy#53]
HsiangTaiteki-Mac:siriproxy HsiangTai$ bundle install
Fetching git://github.com/chendo/cora.git
sh: git: command not found
Git error: command `git clone 'git://github.com/chendo/cora.git' "/Users/HsiangTai/.rvm/gems/ruby-1.9.3-p0/cache/bundler/git/cora-e7aa6b357e86be8b6f2707576ceb77632f2c12aa" --bare --no-hardlinks` in directory /Users/HsiangTai/SiriProxy has failed.

and when i run rvmsudo ruby start.rb it show up this below and tell me to install bundle install but i just had problem

HsiangTaiteki-Mac:siriproxy HsiangTai$ rvmsudo ruby start.rb
start.rb:3: warning: variable $KCODE is no longer effective; ignored
git://github.com/chendo/cora.git (at master) is not checked out. Please run `bundle install`

**Comment by plamoni** [comment]
You need git installed in order to use SiriProxy.

**Comment by johnnytai4** [comment]
how to install git?

**Comment by plamoni** [comment]
If you don't know how to install Git and you can't figure it out for yourself using Google (or GitHub), you're not going to have an easy time getting SiriProxy running. Sorry, the Issues page is not meant for helping people ill-equipped to get this very-pre-alpha software running.
