### ISSUE TITLE
Siriproxy new message and don't accept iphone

### ISSUE THREAD

**Issue by HaTe87** [plamoni/SiriProxy#531]
hello
for a few days not used my siriproxy ...
Today I start with my strange surprise is not responding,
restart and nothing, I realize that there is a strange message:
oot@raspberrypi:~# siriproxy server
WARN: Unresolved specs during Gem::Specification.reset:
      rake (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
[Info - Configuration] Loading plugins -- If any fail to load, run `siriproxy bundle` (not `bundle install`) to resolve.
/usr/local/rvm/gems/ruby-2.0.0-p195/gems/blankslate-3.1.2/lib/blankslate.rb:51: warning: undefining `object_id' may cause serious problems

could this be?

**Comment by elvisimprsntr** [comment]
I personally have not tested with ruby 2.0.0-p195.  I don't think SiriProxy uses the gem which is causing the error.  Are you using a plugin that uses that ruby gem? It could be the gem pushed an update which has a bug.  Check with gem author.  

Elvis

**Comment by HaTe87** [comment]
no nothing plugin... and 3 day ago works fine

**Comment by elvisimprsntr** [comment]
What did you do between when it was working and when it stopped? 

Elvis

**Comment by HaTe87** [comment]
the raspberry was shout down for everyday

**Comment by elvisimprsntr** [comment]
If all you did was reboot, then something might be corrupted on your SD card.
