### ISSUE TITLE
Install Problems with Installation on Mac OS 10.6.8

### ISSUE THREAD

**Issue by neomorph77** [plamoni/SiriProxy#532]
hi everybody,

I installed everything as described. When I start the siriproxy it comes up, but when I "Ctrl + C" I see the following message. I dont know how to fix it. Can anybody help me?

[Info - Configuration] Loading plugins -- If any fail to load, run `siriproxy bundle` (not `bundle install`) to resolve.
[Info - Server] Starting SiriProxy on 0.0.0.0:443...
[Info - Server] SiriProxy up and running.
^C/Users/morpheus/.rvm/gems/ruby-1.9.3-p429@SiriProxy/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine': Interrupt
    from /Users/morpheus/.rvm/gems/ruby-1.9.3-p429@SiriProxy/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in`run'
    from /Users/morpheus/siriproxy/lib/siriproxy.rb:17:in `initialize'
    from /Users/morpheus/siriproxy/lib/siriproxy/command_line.rb:106:in`new'
    from /Users/morpheus/siriproxy/lib/siriproxy/command_line.rb:106:in `start_server'
    from /Users/morpheus/siriproxy/lib/siriproxy/command_line.rb:90:in`run_server'
    from /Users/morpheus/siriproxy/lib/siriproxy/command_line.rb:39:in `initialize'
    from ./siriproxy:6:in`new'
    from ./siriproxy:6:in `<main>'

Thanks for any help.

neo

**Comment by elvisimprsntr** [comment]
Those messages are induced when you perform a ctrl-c and are expected. 

Elvis
