### ISSUE TITLE
Command via Siri to stop the server

### ISSUE THREAD

**Issue by hey101** [plamoni/SiriProxy#534]
The way that I have siriproxy running at bootup on my raspberry pi, causes the entire boot process to freeze. As weird as that really is, it works. Anyhow the only way to continue the boot process is by ssh from another computer and killing the siriproxy process. I thought about making my life easier by making a siri command to kill the proccess using system("sudo killall siriproxy").
I have tried several variations of that command and the only thing that happens is the plugin crashes but it does not stop the server. Is there a way to stop the server by a command from inside a plugin?

**Comment by elvisimprsntr** [comment]
How are you launching SiriProxy at boot?   I've not had any problems using my method. http://www.youtube.com/watch?v=0z6uKw8Zaas

**Comment by hey101** [comment]
I'm using that exact method. I attached an image below. It stops immediately at starting siriproxy. I can still use siriproxy or even ssh into the raspberry pi. 

Edit: 
Apparently attaching an image to github from my iPhone didn't work. Here you go:
![image](https://f.cloud.github.com/assets/4505956/592953/dc64a4a6-ca29-11e2-9a62-ada032eb52d2.jpeg)

**Comment by elvisimprsntr** [comment]
Did you make any tweaks to the file? Which one are you using.  The one with logging enables or the background daemon version?

**Comment by elvisimprsntr** [comment]
What error messages do  you get when manually launching SiriProxy?

**Comment by hey101** [comment]
I made no tweaks to the file and I am using the logging one. When I manually launch siriproxy it works fine and there are no errors from my memory.

**Comment by elvisimprsntr** [comment]
Use the one without logging.  

Elvis

**Comment by elvisimprsntr** [comment]
The logging one is only meant for temporary diagnostics.

**Comment by hey101** [comment]
I changed to the normal one instead of the logging one and it works. Thank you!
