### ISSUE TITLE
Lan IP

### ISSUE THREAD

**Issue by ingeniero2005** [plamoni/SiriProxy#535]
Hi,  i have a question, mi router assign the 192.168.1.108 to my RPi, i see in the instructions that i use that IP.

Instructios...
# If you want to define a static IP on the RPi, find out what address your router assigned to your RPi.

ifconfig
# Edit the network settings to use a STATIC IP address.
# NOTE: To make it easy use the same settings your router assigned to your RPi.

vim /etc/network/interfaces
# Comment out the DHCP entry. Make the STATIC entry look something like this:
# NOTE: Tweak the address for your STATIC IP address.

auto eth0
iface eth0 inet static
address 192.168.69.97
netmask 255.255.255.0
broadcast 192.168.69.255
network 192.168.69.0
gateway 192.168.69.1
dns-nameservers 8.8.8.8 8.8.4.4

then i dont know in what of the before lines i need reemplace the IP 192.168.1.108 and which commans use to made effective the changes. Thanks. Sorry i dont undestand that point

**Comment by ingeniero2005** [comment]
i dont know because the system show a big letter, i only copy and paste instructios.... :s

**Comment by elvisimprsntr** [comment]
Did you read the header in the file and the comments in the instructions?   The instructions assume the user has some basic Linux and editor knowledge.  If you don't I suggest you read up a bit or use some google searches.     How are you going to learn anything on your own if someone always gives you the answers? 

Elvis
