### ISSUE TITLE
command problem

### ISSUE THREAD

**Issue by ingeniero2005** [plamoni/SiriProxy#536]
Hi, that questios is because when i run this command 

[[ -s "/etc/profile.d/rvm.sh" ]] && . "/etc/profile.d/rvm.sh"

The Raspebberry say that this command is not found:

root@raspberrypi:~# [[ -s "/etc/profile.d/rvm.sh" ]] && . "/etc/profile.d/rvm.sh"
-bash: __rvm_fix_path_from_gem_path: command not found

Thanks

**Comment by elvisimprsntr** [comment]
Look like you decided to install everything from scratch.   Including RVM.   Looking at the RVM repo there has been some recent activity.  I suggest you post you question against the RVM repo.    git://github.com/wayneeseguin

**Comment by ingeniero2005** [comment]
Is not necesary install RVM frontera scrach with your SD image (i can skip this command, or i can skip the RVM install) i refer to if in your SD image are install the RVM, Thanks

**Comment by elvisimprsntr** [comment]
Everything is pre-installed on my SD card image.    http://sourceforge.net/p/siriproxyrpi/news/2013/03/release-2013-03-22/

Configuration summary:
- Raspbian Wheezy - Kernel 3.6.11+
- Ruby 2.0.0-p0
- SiriProxy 0.5.2
- DHCP by default
- SSH, SAMBA, and APACHE2 installed
- AVAHI and DNSSD libraries for Zeroconf (aka Bonjour) service discovery

The only thing you need to do is update siriproxy from 0.5.2 to 0.5.4:
`siriproxy update`
or
`gem install siriproxy`

If you have already tried to update RVM, which seems to causing the problem above, you need write my SD card image from scratch.

**Comment by ingeniero2005** [comment]
In a few worlds, i download the SD image, update is update siriproxy (if i want), install gem siriproxy (if i want), change the IP and go to the  (# Generate the certificates) in your instructions and not make the /.siriproxy directory.?

**Comment by elvisimprsntr** [comment]
1. write the SD image
2. Put SD card in RPi and boot.
3. `siriproxy update` # required
4. `siriproxy gencerts` # required
5. you can skip the IP address temporally.  Get siriproxy working first.
6. installed the new ca.pem on your iOS device
7. update he WiFi DNS entry on your iOS device to the IP address of the RPi
   7.1 disable cellular data on your iOS device
   7.2 toggle airplane mode off for 5 seconds
8. `siriproxy server -d xxx.xxx.xxx.xxx` # xxx = IP address of your RPi 
9. lauch siri on your iOS device
10. ask `test siri proxy`
11. you should get response `siriproxy up and running`

**Comment by ingeniero2005** [comment]
Ok Elvis i make that and i say you. My Siri is in spanish then i change the speaking configuration to english and i say in english "test Siriproxy"

**Comment by ingeniero2005** [comment]
Thanks
