### ISSUE TITLE
ISY 99i

### ISSUE THREAD

**Issue by ingeniero2005** [plamoni/SiriProxy#537]
Hi, thanks Elvis, Siri is Up, know how install the ISY 99i plugins. Thanks again

**Comment by elvisimprsntr** [comment]
There are may forks of the isy99i plugin.  Some are stale, some include thermostat and dimmer control, some have been tested and work with ruby 2.0.0 and latest SiriProxy.   It all depends on what features you want and how much effort you want to program yourself.    My ISY plugin does not include thermostat and dimmer control, required a bit of manual set up, but works with latest ruby and SiriProxy.   My goal is to eventually make it selfs aware but working 60-80 hours a week at my day job has not allowed me to work on it much lately.

**Comment by ingeniero2005** [comment]
How you recommend, i only need control light on/off, channels (Since in his video), some basic.

**Comment by ingeniero2005** [comment]
Can i use the information of your link (https://github.com/elvisimprsntr/siriproxy-isy99i) only the instructions to install a plugins or how can i do? Thanks

**Comment by elvisimprsntr** [comment]
yes follow my instructions.

**Comment by elvisimprsntr** [comment]
you will need to copy the default config.yml file (read warning message when you manually launch siriproxy) then add to config.yml file for isy plugin per instructions.

**Comment by ingeniero2005** [comment]
All?, because in that you speak to install a siriproxy and that step work now.

**Comment by ingeniero2005** [comment]
I can make that:
- Create a plugins directory

mkdir ~/plugins
cd ~/plugins/
- Get the latest repo
  git clone git://github.com/elvisimprsntr/siriproxy-isy99i
- Add the example configuration to the master config.yml
  cat siriproxy-isy99i/config-info.yml >> ~/.siriproxy/config.yml
- Edit the config.yml as required. Note: Make sure to line up the column spacing.
  vim ~/.siriproxy/config.yml
- Edit the isyconfig.rb as you wish. Note: Repeat all the following steps if you make additional changes.
  vim siriproxy-isy99i/lib/isyconfig.rb
- Edit the plugin as you wish. Note: Repeat all the following steps if you make additional changes.
  vim siriproxy-isy99i/lib/siriproxy-isy99i.rb

Question: run bundle or is not necesary because the siriproxy run ir bundle is necesary to use ISY-99i plugins. Thanks.

**Comment by elvisimprsntr** [comment]
Copy the config.yml file to the ~/.siriproxy folder. (Read the warming message when you launch SiriProxy where to copy the file from.  You need to perform this step first)

Then perform steps to add ISY plugin, including siriproxy bundle

**Comment by ingeniero2005** [comment]
When you say (Read the warming message when you launch SiriProxy where to copy the file from) what you referrer.

**Comment by ingeniero2005** [comment]
Exist some problems with this warning, what i do after warning?

**Comment by ingeniero2005** [comment]
How step have make first

**Comment by ingeniero2005** [comment]
You can explain me step by step, sorry i don want damage the work with siriproxy. Thanks

**Comment by elvisimprsntr** [comment]
When you manually launch SiriProxy what go the log read?

**Comment by elvisimprsntr** [comment]
`cp /home/pi/.rvm/gems/ruby-2.0.0-pXXX/gems/siriproxy-0.5.4/config.example.yml ~/.siriproxy/config.yml`

Replace XXX with ruby patch version you are using.

**Comment by elvisimprsntr** [comment]
Correction.  The copy path is different.

**Comment by elvisimprsntr** [comment]
I think the path is

`cp /use/local/rvm/gems/ruby-2.0.0-pXXX/gems/siriproxy-0.5.4/config.example.yml ~/.siriproxy/config.yml`

**Comment by elvisimprsntr** [comment]
`cp /user/local/rvm/gems/ruby-2.0.0-pXXX/gems/siriproxy-0.5.4/config.example.yml ~/.siriproxy/config.yml`

**Comment by elvisimprsntr** [comment]
Then test Siriproxy before adding ISY plugin.

**Comment by ingeniero2005** [comment]
Elvis, when you say "launch manually" is when i run this comand: siriproxy server -d 192.168.1.108,?
Where i see the log read?

**Comment by elvisimprsntr** [comment]
Yes

Elvis

**Comment by ingeniero2005** [comment]
And where found the log (log read) and what i do with this log

**Comment by elvisimprsntr** [comment]
Read the messages echoed to the screen.

**Comment by ingeniero2005** [comment]
I see many information, what line

**Comment by elvisimprsntr** [comment]
You are making this a lot more complicated than it really is.   You are not thinking about what you are doing or following the provided instructions very well, or using the information SiriProxy is telling you.

**Comment by ingeniero2005** [comment]
:(

**Comment by elvisimprsntr** [comment]
I am trying to help you help yourself.  I cannot provide you guidance every time you are not sure what to do next.   Read the instructions, output logs, etc and try to problem solve yourself.  You will learn more in the end and become more self sufficient.

**Comment by ingeniero2005** [comment]
I try but for example this line "cp /user/local/rvm/gems/ruby-2.0.0-pXXX/gems/siriproxy-0.5.4/config.example.yml ~/.siriproxy/config.yml" o don't see in your instructions and i dont knw with is ths rugby path versión

**Comment by elvisimprsntr** [comment]
The reason it's not in my instructions is because SiriProxy tells you want to do in the output messages which you are not reading or understanding.   I suggest you download the Debian quick reference card and read some Linux basic command line instructions, as a suggest in my sd card instructions.   http://www.debian.org/doc/user-manuals#refcard

**Comment by elvisimprsntr** [comment]
Do you get a message that reads like this?

`[Notice - Configuration] ==================== Important Configuration Notice ==========================
[Notice - Configuration] '/root/.siriproxy/config.yml' not found. Using '/usr/local/rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/config.example.yml'
[Notice - Configuration] 
[Notice - Configuration] Remove this message by copying '/usr/local/rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/config.example.yml' into '~/.siriproxy/'
[Notice - Configuration] ==============================================================================`

What do think it is try to tell you to do?

**Comment by ingeniero2005** [comment]
Im sorry for don't understand, i try to follow the instruction (i search in the issue a and internet), i only ask patience because i want to learn, i know that you know much about of this topic and sometimes you can be angry for a much question.

**Comment by elvisimprsntr** [comment]
not angry, but disappointed.  

post your siriproxy log output

**Comment by ingeniero2005** [comment]
Ok then i go to run siriproxy server and send you the log output for begin. Good :)

**Comment by elvisimprsntr** [comment]
http://sourceforge.net/p/siriproxyrpi/news/2013/06/release-2013-06-02/

**Comment by ingeniero2005** [comment]
Elvis, that is the log of my siriproxy

root@raspberrypi:~# siriproxy server -d 192.168.1.108
WARN: Unresolved specs during Gem::Specification.reset:
      uuidtools (>= 0)
      geocoder (>= 0)
      rake (>= 0)
      rubydns (~> 0.6.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
[Notice - Configuration] ==================== Important Configuration Notice ==========================
[Notice - Configuration] '/root/.siriproxy/config.yml' not found. Using '/usr/local/rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/config.example.yml'
[Notice - Configuration]
[Notice - Configuration] Remove this message by copying '/usr/local/rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/config.example.yml' into '~/.siriproxy/'
[Notice - Configuration] ==============================================================================
[Info - Configuration] Loading plugins -- If any fail to load, run `siriproxy bundle` (not `bundle install`) to resolve.
[Notice - Server] ======================= WARNING: Running as root =============================
[Notice - Server] You should use -l or the config.yml to specify and non-root user to run under
[Notice - Server] Running the server as root is dangerous.
[Notice - Server] ==============================================================================
[Info - Server] Starting SiriProxy on 0.0.0.0:443...
[Info - Server] DNS server is not running yet, waiting 1 second...
[Info - Server] DNS Server started, tainting 'guzzoni.apple.com' with 192.168.1.108
[Info - Server] SiriProxy up and running.

What is the next step, make that step by step for i can search and learn, please.

Thanks
