### ISSUE TITLE
Problem installing plugin

### ISSUE THREAD

**Issue by jasonehines** [plamoni/SiriProxy#538]
I'm having a problem installing plugins. Every one I've tried gives me a message "could not find gem 'siriproxy-[plugin name](> =0) ruby' in the gems available on this machine."  

I'm running this on a Rasberry Pi and followed the instructions for the Pi install and the proxy is working. 

I'm not very familiar with ruby so I have no idea what the actual problem is. Anyone know what I doing wrong?

**Comment by elvisimprsntr** [comment]
1. did you copy the default config.yml file to the ~/.siriproxy folder?
2. how did you add the plugin?  what path?
3. did you update the config.yml file?
4. did you run siriproxy bundle?

my first guess is number 4

**Comment by jasonehines** [comment]
1. 
   my config.yml file: 

isten: 192.168.1.5
port: 443
log_level: 1

upstream_dns: [192.168.1.2]

server_ip: 192.168.1.5
user: nobody

plugins:
- name: 'ChuckNoris'
  path: './plugins/SiriProxy-ChuckNorris'
- name: 'iJokes'
  git: 'git://github.com/SalmanBurhan/siriproxy-iJokes.git'

I cloned the Chuck Norris one to see if local plugins would work, it did not.
1. see above
2. I'm not sure what you mean by update the config.yml file (other than editing it to add the plugins)
3. this is the output from 'siriproxy bundle':

root@incrediblepbx:~# siriproxy bundle
/usr/local/rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/psych.rb:205:in `parse': (/root/.siriproxy/config.yml): did not find expected key while parsing a block mapping at line 1 column 1 (Psych::SyntaxError)
    from /usr/local/rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/psych.rb:205:in`parse_stream'
    from /usr/local/rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/psych.rb:153:in `parse'
    from /usr/local/rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/psych.rb:129:in`load'
    from /usr/local/rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/psych.rb:299:in `block in load_file'
    from /usr/local/rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/psych.rb:299:in`open'
    from /usr/local/rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/psych.rb:299:in `load_file'
    from /usr/local/rvm/gems/ruby-2.0.0-p195/gems/siriproxy-0.5.4/lib/siriproxy/command_line.rb:167:in`parse_options'
    from /usr/local/rvm/gems/ruby-2.0.0-p195/gems/siriproxy-0.5.4/lib/siriproxy/command_line.rb:35:in `initialize'
    from /usr/local/rvm/gems/ruby-2.0.0-p195/gems/siriproxy-0.5.4/bin/siriproxy:6:in`new'
    from /usr/local/rvm/gems/ruby-2.0.0-p195/gems/siriproxy-0.5.4/bin/siriproxy:6:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-2.0.0-p195/bin/siriproxy:23:in`load'
    from /usr/local/rvm/gems/ruby-2.0.0-p195/bin/siriproxy:23:in `<main>'
    from /usr/local/rvm/gems/ruby-2.0.0-p195/bin/ruby_noexec_wrapper:14:in`eval'
    from /usr/local/rvm/gems/ruby-2.0.0-p195/bin/ruby_noexec_wrapper:14:in `<main>'

Any ideas?

**Comment by jasonehines** [comment]
I guess the markdown function turned my list into two lists, the second "1" should be "2, etc." Looks like it reformatted my config.yml paste also.

I'll go find out how markdown works and repost it.

**Comment by elvisimprsntr** [comment]
1. double check the columns for the new entries in the config.yml file.   if they do not line up with other entries you will get those errors.

**Comment by jasonehines** [comment]
This is what I'm getting now:

root@incrediblepbx:~/.siriproxy# siriproxy server
WARN: Unresolved specs during Gem::Specification.reset:
      rake (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
[Info - Configuration] Loading plugins -- If any fail to load, run `siriproxy bundle` (not `bundle install`) to resolve.
git://github.com/SalmanBurhan/siriproxy-iJokes.git (at master) is not checked out. Please run `bundle install`
root@incrediblepbx:~/.siriproxy# siriproxy bundle
[Info - Configuration] Loading plugins -- If any fail to load, run `siriproxy bundle` (not `bundle install`) to resolve.
Updating git://github.com/SalmanBurhan/siriproxy-iJokes.git
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Could not find gem 'siriproxy-ijokes (>= 0) ruby' in git://github.com/SalmanBurhan/siriproxy-iJokes.git (at master).
Source does not contain any versions of 'siriproxy-ijokes (>= 0) ruby'

**Comment by elvisimprsntr** [comment]
I'm guessing the owner of the repo did not actually push a gem.   If it were me I would manually clone the repo to a  local plugins directory and change the config.yml file to use the path method instead of git.    

Personally I prefer my jokes plugin better.

**Comment by jasonehines** [comment]
I was mostly using it just to test the plugins.

Hopefully I'm doing this right:

```
root@incrediblepbx:~/.siriproxy/plugins# git clone https://github.com/SalmanBurhan/siriproxy-iJokes.git
Cloning into 'siriproxy-iJokes'...
remote: Counting objects: 14, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 14 (delta 2), reused 13 (delta 1)
Unpacking objects: 100% (14/14), done.
```

This is plugins part of the config:

```
plugins:
- name: 'iJokes'
  path: './plugins/siriproxy-iJokes'
```

This is what I get when running siriproxy bundle:

```
root@incrediblepbx:~/.siriproxy# siriproxy bundle
[Info - Configuration] Loading plugins -- If any fail to load, run `siriproxy bundle` (not `bundle install`) to resolve.
The path `/usr/local/rvm/gems/ruby-2.0.0-p195/gems/siriproxy-0.5.4/plugins/siriproxy-iJokes` does not exist.
root@incrediblepbx:~/.siriproxy# 
```

**Comment by elvisimprsntr** [comment]
You have two options 
1. Use one of my plugins as an example how to clone and configure to a local plugins directory. Note the "~" prefix on the path.  
2. Update the config.yml file to explicitly define the full path where the plugin is located.
