### ISSUE TITLE
Strating SrirProxy Problem

### ISSUE THREAD

**Issue by johnnytai4** [plamoni/SiriProxy#54]
HsiangTaiteki-Mac:SiriProxy HsiangTai$ rvmsudo ruby start.rb
start.rb:3: warning: variable $KCODE is no longer effective; ignored
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Starting SiriProxy on port 443..

anyone know what happen to it?

**Comment by muhkuh0815** [comment]
thats exactly how mine looks, but i dont care because it works perfectly :-)

**Comment by plamoni** [comment]
Those errors are known. We're working I'm getting rid of them. They
don't hurt anything. You're running fine!

-Pete

Sent from my iPhone

On Nov 27, 2011, at 3:29 AM, johnnytai4
reply@reply.github.com
wrote:

**Comment by johnnytai4** [comment]
ok now i got it running SiriProxy but why is my iphone siri didn't work right?

**Comment by netpro2k** [comment]
You likely have your iPhone dns settings or dnsmasq improperly configured

**Comment by ishaper** [comment]
how to configure the iphone dns settings??

**Comment by plamoni** [comment]
http://www.youtube.com/watch?v=a9gO4L0U59s

**Comment by johnnytai4** [comment]
I did what's on the video but it still won't work, it might be I install the Siri GUI wrong?

**Comment by plamoni** [comment]
You're using an iPhone 4? Not a 4S?

-Pete

On Sun, Nov 27, 2011 at 6:10 PM, johnnytai4 <
reply@reply.github.com

**Comment by johnnytai4** [comment]
I'm using iPhone 4 , I install the Siri on iphone4 when I open Siri on iPhone it didn't have the "what can I help you with" is that normal?

**Comment by plamoni** [comment]
We do not support running Siri on a non-iPhone 4S.
