### ISSUE TITLE
ISY 99i Log Siriproxy

### ISSUE THREAD

**Issue by ingeniero2005** [plamoni/SiriProxy#541]
ingeniero2005 commented an hour ago 
Elvis, that is the log of my siriproxy

root@raspberrypi:~# siriproxy server -d 192.168.1.108
WARN: Unresolved specs during Gem::Specification.reset:
uuidtools (>= 0)
geocoder (>= 0)
rake (>= 0)
rubydns (~> 0.6.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
[Notice - Configuration] ==================== Important Configuration Notice ==========================
[Notice - Configuration] '/root/.siriproxy/config.yml' not found. Using '/usr/local/rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/config.example.yml'
[Notice - Configuration]
[Notice - Configuration] Remove this message by copying '/usr/local/rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/config.example.yml' into '~/.siriproxy/'
[Notice - Configuration] ==============================================================================
[Info - Configuration] Loading plugins -- If any fail to load, run siriproxy bundle (not bundle install) to resolve.
[Notice - Server] ======================= WARNING: Running as root =============================
[Notice - Server] You should use -l or the config.yml to specify and non-root user to run under
[Notice - Server] Running the server as root is dangerous.
[Notice - Server] ==============================================================================
[Info - Server] Starting SiriProxy on 0.0.0.0:443...
[Info - Server] DNS server is not running yet, waiting 1 second...
[Info - Server] DNS Server started, tainting 'guzzoni.apple.com' with 192.168.1.108
[Info - Server] SiriProxy up and running.

What is the next step, make that step by step for i can search and learn, please.

Thanks

**Comment by ingeniero2005** [comment]
What is the next step to install Isy99i plugin, you can see the log that you said me. Thanks

**Comment by elvisimprsntr** [comment]
1. Update to the new SD card image: http://sourceforge.net/p/siriproxyrpi/news/2013/06/release-2013-06-02/
2. Follow the instructions to install ISY plugin: https://github.com/elvisimprsntr/siriproxy-isy99i#installation-new-for-siriproxy-050

**Comment by ingeniero2005** [comment]
Elvis i follow yours instructions but when i run siriproxy that appear:

root@raspberrypi:~# siriproxy server -d192.168.1.108
/usr/local/rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/ostruct.rb:90:in `initialize': undefined method`each_pair' for #Array:0x1ab6a40 (NoMethodError)
        from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/lib/siriproxy/command_line.rb:167:in `new'
        from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/lib/siriproxy/command_line.rb:167:in`parse_options'
        from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/lib/siriproxy/command_line.rb:35:in `initialize'
        from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/bin/siriproxy:6:in`new'
        from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/bin/siriproxy:6:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.0.0-p0/bin/siriproxy:23:in`load'
        from /usr/local/rvm/gems/ruby-2.0.0-p0/bin/siriproxy:23:in `<main>'
root@raspberrypi:~#

**Comment by ingeniero2005** [comment]
Elvis i follow yours instructions but when i run siriproxy that appear:

root@raspberrypi:~# siriproxy server -d 192.168.1.108
/usr/local/rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/ostruct.rb:90:in initialize': undefined methodeach_pair' for #Array:0x1ab6a40 (NoMethodError)
from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/lib/siriproxy/command_line.rb:167:in new'
from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/lib/siriproxy/command_line.rb:167:inparse_options'
from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/lib/siriproxy/command_line.rb:35:in initialize'
from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/bin/siriproxy:6:innew'
from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/siriproxy-0.5.4/bin/siriproxy:6:in <top (required)>'
from /usr/local/rvm/gems/ruby-2.0.0-p0/bin/siriproxy:23:inload'
from /usr/local/rvm/gems/ruby-2.0.0-p0/bin/siriproxy:23:in `'
root@raspberrypi:~#

**Comment by elvisimprsntr** [comment]
There is no reason to post your question twice.  

You didn't follow step one of my previous post.

**Comment by ingeniero2005** [comment]
Sorry for the twice. Elvis because you know that i Don't follow your steps. I follow all the steps.

**Comment by ingeniero2005** [comment]
How command use to update: raspbian, Ruby, ssh, samba.
How command use to install avahi, dnssd libraries

Please help me

**Comment by ingeniero2005** [comment]
When i write: .bash_profile appear command not found

**Comment by ingeniero2005** [comment]
I write:

"2013-05-25-wheezy-raspbian update" and say command not found
"Ruby 2.0.0-p195 update" and say command not found

All The same with the others updates

**Comment by elvisimprsntr** [comment]
Please tell you are not serious.    If you are serious then I can't afford the time to help.  If you are not serious then I cant afford the time to help.  

Elvis

**Comment by ingeniero2005** [comment]
Because serius. I need your help really, i try write the commands but the ststem say that not found these commans, i try to search in internet the updstes but i Don't see nothing, is very serius a need your help for install ISY 99i plugin. Please

**Comment by ingeniero2005** [comment]
Elvis i want to install the ISY 99i plugins with your image, is the only form that siriproxy run, if i use the update not work, please help me

**Comment by elvisimprsntr** [comment]
One last try to help.  

Upgrade to new image
1. Download the write the new sd card image
2. Install sd card in RPi and boot 
3. Login, generate new certificates, and install ca.pem on your iOS device. 
5. Set DNS entry on your iOS device
6. Turn off cellular data. Toggle airplane mode off for 5 seconds.  
7. Launch SiriProxy on RPi 
8. Launch Siri on your device and test

Install ISY plugin 
1. Follow the instructions from link in previous post.  
2. You will need to edit one of the file for your Insteon devices and scenes.

**Comment by ingeniero2005** [comment]
OK, i try ti install the siriproxy and ISY 99i plugins, i only have a question, is not necesario install RVM?

**Comment by ingeniero2005** [comment]
Ahh Ok this is in the part b of your instructions

**Comment by ingeniero2005** [comment]
Then the ISY plugins not work with your image

**Comment by elvisimprsntr** [comment]
RVM, Ruby, SiriProxy are already installed on my sd card image.   That what pre-installed means.   

Elvis

**Comment by elvisimprsntr** [comment]
You are not getting my message.   

Elvis

**Comment by elvisimprsntr** [comment]
1. Download the new SD card image: http://sourceforge.net/p/siriproxyrpi/news/2013/06/release-2013-06-02/
2. Follow the instructions to install ISY plugin: https://github.com/elvisimprsntr/siriproxy-isy99i#installation-new-for-siriproxy-050

**Comment by ingeniero2005** [comment]
Yes, for me is more difficult because i Don't understand and write more english. Sorry i try understand you and follow yours instructions.

**Comment by ingeniero2005** [comment]
About the second part, i try to search in internet how update or install "Ruby 2.0.0-p195" but nothing, can you say me please how install Ruby 2.0.0-p195. Thanks

**Comment by ingeniero2005** [comment]
I try to understand, sorry for that but i am bad for english, you say that go to "http://sourceforge.net/p/siriproxyrpi/news/2013/06/release-2013-06-02/" in the "file" tab and download your last image wich have all the updates and after follow your instructions to install ISY plugins

**Comment by ingeniero2005** [comment]
Is all rigth Elvus :)

**Comment by ingeniero2005** [comment]
Elvis, sorry

**Comment by elvisimprsntr** [comment]
Now that you downloaded the latest image you need to follow the instructions, same as you did for the last sd card image, to write to a sd card.

http://sourceforge.net/p/siriproxyrpi/wiki/Home/

**Comment by ingeniero2005** [comment]
Hi Elvis iam  follow the instruction, in that moment i install bundle, after of continue with the instructios i want to know if is necesary this: 

Set up RVM and Ruby 2.0.0 "Run (Ref: https://github.com/plamoni/SiriProxy#set-up-instructions)"
because in your image you have Ruby "Run (Ref: https://github.com/plamoni/SiriProxy#set-up-instructions)"

skip this step?

Thanks

**Comment by elvisimprsntr** [comment]
Skip

**Comment by ingeniero2005** [comment]
Thanks Elvis, i have siriproxi server server running, when i say say "test siri proxy" that respond, i modify the plugins isy 99i files but not happend nothing. i reemplaze the user, password, isteon directions including the spaces with (%20) but the ligth not turn on. what can be the problem. Thanks

**Comment by elvisimprsntr** [comment]
i assume you followed the instructions for the ISY plugin.
1. did you updated the isyconfig.rb fle for your ISY scenes and Insteon device IDs?
2. did you run `siriproxy bundle`
3. what does your siriproxy output log look like,  did it say it loaded the ISY plugin?

**Comment by elvisimprsntr** [comment]
1. what version of the ISY firmware are you using?

**Comment by ingeniero2005** [comment]
I use the last version and yes i run the siriproxy bundle.
In what files i have reemplace the user, password and IP Elvis

Thanks

**Comment by ingeniero2005** [comment]
I update the device ID (i try with only one)

**Comment by ingeniero2005** [comment]
And i run Siri proxy with:

Siriproxy server -d 192.168.1.108

**Comment by ingeniero2005** [comment]
In the config.yml i edit the IP, user and password of the ISY
In the isyconfig.rb i only edit the 

@nodeId["doorbell"]= "/rest/nodes/1C%207%2049%202" in wich i reemplace the name and ID for the name and ID of my insteon light and the same form in 

@inputSt["doorbell"]= "/rest/status/1C%207%2049%201" 

The siriproxy-isy99i.rb i Don't modify because i only want to try the comprobate if when i say (on ring dorbell) my light work

I Don't made more changes, missing one?

Thanks Elvis

**Comment by elvisimprsntr** [comment]
Give it a try

**Comment by ingeniero2005** [comment]
I try that but nothing....

**Comment by elvisimprsntr** [comment]
Have you tried using the SiriProxy console ?

`siriproxy console -d xxx.xxx.xxx.xxx`

Then type the text you would normally speak

**Comment by ingeniero2005** [comment]
Elvis you know where find more information about how program siri because i Don't understand how modify     siriproxy-isy99i.rb with my phrases, and questions

**Comment by ingeniero2005** [comment]
My ISY have a port 85, can i put this dirección in the configuration IP:

192.168.1.108:85 ?

**Comment by elvisimprsntr** [comment]
Why are you using port 85?

**Comment by elvisimprsntr** [comment]
SiriProxy and the plugins are written in ruby language.  You will have to learn how to program in ruby on your own.   They are many ruby resources on the Internet.

**Comment by ingeniero2005** [comment]
Respect to the port, im work with the port 85 because i was many troubles with the port 80 in the ISY, then can reemplace the IP with 192.168.1.108:85?

Respect to the siriproxy lenguaje, i want to now some link where teach Ruby with Siri not only Ruby

**Comment by elvisimprsntr** [comment]
You are completely on your own using port 85.  You need to learn how to use google search to find ruby programming resources.

**Comment by elvisimprsntr** [comment]
Look here https://github.com/plamoni/SiriProxy/wiki/Plugin%20Developer%20Guide

**Comment by ingeniero2005** [comment]
Yes im aire that i use the port 85

**Comment by ingeniero2005** [comment]
Yes Im sure that i use the port 85

**Comment by ingeniero2005** [comment]
Answer to his question, yes, i am sure that the port in the ISY is 85

**Comment by ingeniero2005** [comment]
Can you reply please?

**Comment by ingeniero2005** [comment]
Elvis van i made for the question
