### ISSUE TITLE
Processing default Siri reaction after catching any speech input

### ISSUE THREAD

**Issue by mxmzb** [plamoni/SiriProxy#544]
I'm wondering, if one can process default behavior of Siri after having matched up with a speech input.

This is especially interesting when You try to dynamically catch voice inputs, like with `listen_for /\A(.*)\z/i do |speech|` to analyze the input with some algorithm or other software component. So if nothing is being found, it would be great to tell the proxy plugin that it should proceed with the default Siri reaction (e.g. creating a contact or something).
Is that possible somehow?

**Comment by elvisimprsntr** [comment]
SiriProxy works on the basis of matching the text of converted voice

**Comment by elvisimprsntr** [comment]
... packets.  If siriproxy does not find a match based on the regex expressions you define, sirproxy simply passes on the default Siri response.   Does that not meet your needs?

**Comment by mxmzb** [comment]
Yes, so far so good. But I'm catching _all_ voice inputs (see the regex I use above). I afterwards send the input, whatever it is, to some other, more advanced engine which is going to analyze the speech string. Though, it can be that the voice input does not make any sense particularly for that engine. So at this point I'm stuck, because the SiriProxy plugin has matched anyway the voice input, but still it seems not to be the thing I could work with, so maybe there is a default routine for that input.

Concrete example: "What time is it?" would be perfectly answered by Siri by default. I catch that input, analyse it and notice that I have no use for this input. So I want to return (or forward) back to the default action.

**Comment by elvisimprsntr** [comment]
The reason you match all speech is because your regex expression is too generic.    You have two options:
1. Define more specific regex expressions 
2. Provide some context in the regex expressions like a word that much be spoke in conjunction with your generic expression.

**Comment by mxmzb** [comment]
Yes, the Regex is pretty much as generic as possible. It is in fact my intention to match everything with the regex. Because I want to analyze the speech not in the Siri-Proxy Plugin but externally (so I consciously don't want to go with 1. or 2.). That's why I'm asking if I can hook somehow into the default routine again.

**Comment by elvisimprsntr** [comment]
Not that I am aware of.
