### ISSUE TITLE
Problem updating my siriproxy because of multi_json 

### ISSUE THREAD

**Issue by MatthiasTesting** [plamoni/SiriProxy#545]
Hello,

i tried updating my siriproxy today. But it seems like multi_json has been update because i got following issue.

siriproxy 0.5.4 built to pkg/siriproxy-0.5.4.gem.
siriproxy (0.5.4) installed.
=== Bundling ===
[Info - Configuration] Loading plugins -- If any fail to load, run `siriproxy bundle` (not `bundle install`) to resolve.
Updating git://github.com/MatthiasTesting/siriproxy-learning.git
Fetching gem metadata from https://rubygems.org/.......
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Using rake (10.0.4)
Using CFPropertyList (2.1.2)
Using i18n (0.6.4)
Bundler::GemspecError: Could not read gem at /home/ubuntu/.rvm/gems/ruby-2.0.0-p0/cache/multi_json-1.7.7.gem. It may be corrupted.
An error occurred while installing multi_json (1.7.7), and Bundler cannot
continue.
Make sure that `gem install multi_json -v '1.7.7'` succeeds before bundling.
=== SUCCESS ===

Has someone else the same prob and knows how to fix it? 

Thanks,

Matt

**Comment by elvisimprsntr** [comment]
Did you try the command the error message suggested?

gem install multi_json -v '1.7.7'

**Comment by MatthiasTesting** [comment]
I did, but it changed nothing.

**Comment by elvisimprsntr** [comment]
it's possible the repo owner pushed a a corrupted new gem or the gem is corrupted on your system.

gem uninstall multi_json -v '1.7.7' 
gem install multi_json -v '1.7.5'
siriproxy bundle

**Comment by elvisimprsntr** [comment]
closed due to inactivity
