### ISSUE TITLE
Set State Question

### ISSUE THREAD

**Issue by GadgetAddict** [plamoni/SiriProxy#547]
I'm new to all of this; but so far have it all set up, working, and tweaking plugins... it's very cool and very FUN.  Thank you to Elvis and Pete for providing so much online.
Can you tell me what is Set state; as I am not understanding the description.  Is it the same as just having siri ask another question?  what's an example?

Thank you,
Michael

PS, if this was the wrong place for this; I ask for your pardon as I'm a newb. Good thing, I take feedback well.

**Comment by elvisimprsntr** [comment]
set_state in the example plugin is merely an example of variable manipulation.   Nothing more.
