### ISSUE TITLE
DNS server not starting (0.5.4)

### ISSUE THREAD

**Issue by upd8er** [plamoni/SiriProxy#548]
Every time I start the siriproxy server with

```
rvmsudo siriproxy server -d 192.168.0.109 -u nobody
```

I get a message saying

```
[Error - Server] Either you're not root or tcp/udp port 53 is in use. 
DNS server is disabled
[Info - Server] Starting SiriProxy on 0.0.0.0:443...
[Info - Server] SiriProxy up and running.
```

Then I try saying "test siri proxy" on my iPhone 4S (I have the certificate installed and my dns is pointed to the computer with siriproxy) and nothing happens.  Not even in the terminal where it says siriproxy up and running.  I am running ubuntu 13.04 (raring ringtail).  I don't have dnsmasq. How should I fix this?

**Comment by elvisimprsntr** [comment]
Try dropping the -u option.

**Comment by elvisimprsntr** [comment]
Also are you sure you didn't unintentionally installed dnsmasq when you selected various options to setup Ubuntu ?

**Comment by elvisimprsntr** [comment]
type netstat -an

look for port 53.  if there is a process already occupying port 53, you need to remove that process

**Comment by upd8er** [comment]
@elvisimprsntr 
I have already checked to see if dnsmasq was installed and it said it wasn't.  Nothing was running on port 53. I tried dropping the -u and it still did the same thing... what do I do now?

**Comment by elvisimprsntr** [comment]
Post the entire output log beginning with the command you used to launch SiriProxy, including the command prompt.

**Comment by upd8er** [comment]
jessewallace@jesse-ubuntu-desktop:~$ rvmsudo siriproxy server -d 192.168.0.109 -u nobody
Warning: can not check `/etc/sudoers` for `secure_path`, falling back to call via `/usr/bin/env`, this breaks rules from `/etc/sudoers`. Run:

```
export rvmsudo_secure_path=1
```

to avoid the warning, put it in shell initialization file to make it persistent.

In case there is no `secure_path` in `/etc/sudoers`. Run:

```
export rvmsudo_secure_path=0
```

to avoid the warning, put it in shell initialization file to make it persistent.
[sudo] password for jessewallace: 
WARN: Unresolved specs during Gem::Specification.reset:
      rake (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
[Info - Configuration] Loading plugins -- If any fail to load, run `siriproxy bundle` (not `bundle install`) to resolve.
[Error - Server] Either you're not root or tcp/udp port 53 is in use. DNS server is disabled[Info - Server] Starting SiriProxy on 0.0.0.0:443...

**Comment by freshestf** [comment]
Sounds similar to what I just went through.

As Elvis said, you need to make sure no other processes are using port 53 and 443: sudo lsof -i :53

If you find processes using those ports, kill them (using the pid from above): sudo kill pid

The get rid of the Warning execute: export rvmsudo_secure_path=1

Then try starting SiriProxy again. If you're still having trouble, post the output from the following three commands:

sudo lsof -i :53 
sudo lsof -i :443
ps -ef | grep -i dnsmasq

**Comment by upd8er** [comment]
Thank you this solved my problem.  For some reason I apparently had dnsmasq installed but it didn't tell me that when I had checked.  I just killed the process and started it up and it still had the thing about the export rvmsudo_secure_path=0 but it hasn't effected how the server started as far as I can tell. 

Thanks Again! - Upd8er
