### ISSUE TITLE
Help getting DNS Server running

### ISSUE THREAD

**Issue by freshestf** [plamoni/SiriProxy#549]
I'm pretty sure the problem is that port 53 is already used, but I'm wondering if there's a way to make SiriProxy use a different port instead of making my other process(es) use another port. I changed port 443 to 7073 to avoid conflict, but I didn't see where I could change 53. If I can't use a port other than 53, what options do I have to do to get this working?

I'm running on an Ubuntu 12.04 server and followed this guide: http://www.modernhoot.com/157/how-to-install-siriproxy-on-ubuntu-12-10/ up to step 8.

Server:~$ rvmsudo siriproxy server -d 192.168.1.4

Warning: can not check `/etc/sudoers` for `secure_path`, falling back to call via `/usr/bin/env`, this breaks rules from `/etc/sudoers`. Run:

```
export rvmsudo_secure_path=1
```

to avoid the warning, put it in shell initialization file to make it persistent.

In case there is no `secure_path` in `/etc/sudoers`. Run:

```
export rvmsudo_secure_path=0
```

to avoid the warning, put it in shell initialization file to make it persistent.
[Info - Configuration] Loading plugins -- If any fail to load, run `siriproxy bundle` (not `bundle install`) to resolve.
[Error - Server] Either you're not root or tcp/udp port 53 is in use. DNS server is disabled
[Notice - Server] ======================= WARNING: Running as root =============================
[Notice - Server] You should use -l or the config.yml to specify and non-root user to run under
[Notice - Server] Running the server as root is dangerous.
[Notice - Server] ==============================================================================
[Info - Server] Starting SiriProxy on 192.168.1.4:7073...
[Info - Server] SiriProxy up and running.

Server:~$ sudo lsof -i :53
COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
Plex    1345 plex   24u  IPv4   8842      0t0  UDP Server.local:46258-> Wireless_Broadband_Router.home:domain
named   1560 bind   20u  IPv6  11264      0t0  TCP *:domain (LISTEN)
named   1560 bind   21u  IPv4  11271      0t0  TCP localhost:domain (LISTEN)
named   1560 bind   22u  IPv4  11273      0t0  TCP Server.local:domain (LISTEN)
named   1560 bind  512u  IPv6  11263      0t0  UDP *:domain
named   1560 bind  513u  IPv4  11268      0t0  UDP localhost:domain
named   1560 bind  514u  IPv4  11272      0t0  UDP Server.local:domain
named   1560 bind  515u  IPv4  66762      0t0  UDP Server.local:domain

Server:~$ ps -ef | grep -i dnsmasq
1000      5130 32319  0 22:47 pts/1    00:00:00 grep -i dnsmasq

**Comment by freshestf** [comment]
I've made a little progress.

I found that port 53 was being used by bind9. I killed the process (sudo kill 1560) to see if it broke anything but everything seemed to work fine so I just went ahead and removed it (sudo apt-get remove bind9). That cleared up port 53 so no conflict should occur now.

I executed export rvmsudo_secure_path=1 as suggested by the warning and now I only get the running as root warning when starting SiriProxy which I'm not concerned with. However, it still doesn't seem to work. I've set my iPhone DNS to 192.168.1.4 and disabled data (so it strictly uses WiFi). When I say "Test Siri Proxy" nothing shows up in my terminal and Siri doesn't give me the expected response.

Server:~$ rvmsudo siriproxy server -d 192.168.1.4
[Info - Configuration] Loading plugins -- If any fail to load, run `siriproxy bundle` (not `bundle install`) to resolve.
[Info - Server] DNS Server started, tainting 'guzzoni.apple.com' with 192.168.1.4
[Notice - Server] ======================= WARNING: Running as root =============================
[Notice - Server] You should use -l or the config.yml to specify and non-root user to run under
[Notice - Server] Running the server as root is dangerous.
[Notice - Server] ==============================================================================
[Info - Server] Starting SiriProxy on 192.168.1.4:7073...
[Info - Server] SiriProxy up and running.

Any ideas as to what I should check next?

**Comment by elvisimprsntr** [comment]
try using port 53 now that you eliminated the conflict?

**Comment by freshestf** [comment]
Try using port 53 where? I thought SiriProxy used ports 53 AND 443 by
default. Am I wrong and it only uses the single port specified in the
config.yml file?

**Comment by elvisimprsntr** [comment]
sorry meant to say use port 443.   base on your last post you are using 7073

**Comment by freshestf** [comment]
Yes, I changed 443 to 7073 to avoid conflict with apache2 (which uses 443).
Is it required that port 443 is used with SiriProxy?

**Comment by freshestf** [comment]
Must be it is required to use 443. I changed the apache2 port and set
SiriProxy to 443 and it works now. Thanks.

**Comment by elvisimprsntr** [comment]
I haven't tried it, but here is some info for changing the port number.  http://code.google.com/p/heatmiser-wifi/wiki/InstallationSiriProxyHints
