### ISSUE TITLE
cora

### ISSUE THREAD

**Issue by Avanzat** [plamoni/SiriProxy#55]
Hi,

new to ruby so this is mayby an easy one?

rvmsudo ruby start.rb

git://github.com/chendo/cora.git (at master) is not checked out. Please run `bundle install`

I have installed cora to but it doesn't work

Cheers!

**Comment by netpro2k** [comment]
did you run `bundle install` (not as root)?

**Comment by Avanzat** [comment]
Hi,

no i did'nt run as root. Hav tried it now and got this instead:

/Library/Ruby/Gems/1.8/bundler/gems/cora-0c97a4821da7/lib/cora.rb:2:in
`require':
/Library/Ruby/Gems/1.8/bundler/gems/cora-0c97a4821da7/lib/cora/plugin.rb:15:
odd number list for Hash (SyntaxError)
        block: block,
              ^
/Library/Ruby/Gems/1.8/bundler/gems/cora-0c97a4821da7/lib/cora/plugin.rb:15:
syntax error, unexpected ':', expecting '}'
        block: block,
              ^
/Library/Ruby/Gems/1.8/bundler/gems/cora-0c97a4821da7/lib/cora/plugin.rb:16:
syntax error, unexpected ':', expecting '='
        within_state: ([options[:within_state]].flatten)
                     ^
/Library/Ruby/Gems/1.8/bundler/gems/cora-0c97a4821da7/lib/cora/plugin.rb:17:
syntax error, unexpected '}', expecting kEND
/Library/Ruby/Gems/1.8/bundler/gems/cora-0c97a4821da7/lib/cora/plugin.rb:65:
syntax error, unexpected ':', expecting ')'
    manager.respond(question, prompt_for_response: true)
                                                  ^
/Library/Ruby/Gems/1.8/bundler/gems/cora-0c97a4821da7/lib/cora/plugin.rb:73:
odd number list for Hash
... options = {unmatched_message: "I'm sorry, I didn't understa...
                              ^
/Library/Ruby/Gems/1.8/bundler/gems/cora-0c97a4821da7/lib/cora/plugin.rb:73:
syntax error, unexpected ':', expecting '}'
... options = {unmatched_message: "I'm sorry, I didn't understa...
                              ^
/Library/Ruby/Gems/1.8/bundler/gems/cora-0c97a4821da7/lib/cora/plugin.rb:73:
syntax error, unexpected '}', expecting kEND
...y, I didn't understand that."}, &block)
                              ^
    from /Library/Ruby/Gems/1.8/bundler/gems/cora-0c97a4821da7/lib/cora.rb:2
    from ./siri_proxy/plugin.rb:1:in`require'
    from ./siri_proxy/plugin.rb:1
    from start.rb:17:in `require'
    from start.rb:17

Cheers

On Sun, Nov 27, 2011 at 5:22 PM, Dominick D'Aniello <
reply@reply.github.com

**Comment by sbaumgarten** [comment]
I have the same issue

**Comment by netpro2k** [comment]
Avanzat you are running on ruby 1.8, you must install ruby 1.9.3 via rvm, please have a look at the README

**Comment by Avanzat** [comment]
Hi,

I did so two times but it didn't work! Have I missed someting?

/A

On Sun, Nov 27, 2011 at 8:45 PM, Dominick D'Aniello <
reply@reply.github.com

**Comment by netpro2k** [comment]
Perhaps you didn't `rvm use 1.9.3` ?

**Comment by Avanzat** [comment]
Yes, I did!

I always keep track of my installations! But I'm new to ruby so maybe I've overlooked something?

**Comment by netpro2k** [comment]
what do you get if you run `which ruby`?

**Comment by Avanzat** [comment]
Sorry, havn't got time to dig deeper in this issue. I think it have to do with the installation. I installed ruby as a regular user but when I fire it up I'm running as root. I think this is the issue. I'll look deeper into it in the weekend!

Cheers
