### ISSUE TITLE
Certificate install on IOS 6.1.4 fails

### ISSUE THREAD

**Issue by whitto** [plamoni/SiriProxy#554]
I have SiriProxy runnig  fine but recently I've found that I cannot install the ca.pem certificate on IOS 6.1.4. devices.  (iPhone 5  btw)

The exact same cert works as expected on IOS 6.1.3. iPad 4th gen,  and all works fine.

Does anyone else have issues with cert install failing on 6.1.4 devices?

regards
whitto

**Comment by elvisimprsntr** [comment]
I've not had problems installing certificates on iPhone 5 iOS 6.1.4, so I would have to say no. I would suspect a bad cert.   Try generating new certs if you haven't already, rebooting the phone, then install the new cert.

**Comment by whitto** [comment]
Yeah that's what I thought so I forwarded the same email to my ipad and it worked fine. So I'm inclined to believe the cert is fine.

I will try on my wife's 6.1.4 phone and report my finding 

Regards 
Craig

**Comment by whitto** [comment]
Yeah seems to work fine on another 6.1.4 iPhone I had access to.

At this point I think I'll wipe the phone and start again. Still no idea why it fails

Regards
Craig

**Comment by elvisimprsntr** [comment]
One thought...  Make sure you have a passcode set.

**Comment by whitto** [comment]
Tried that truck too,  no luck. I see a full wipe and rebuild in my future.

Thanks
Craig
