### ISSUE TITLE
SiriProxy 0.5.4 - Not respond to Siri command

### ISSUE THREAD

**Issue by spawnrider** [plamoni/SiriProxy#555]
The SiriProxy received data but doesn't respond to my commands.

Log : 
[root@MACHINE .siriproxy]# rvmsudo siriproxy server -d XXX.XXX.XXX.XXX  -l DEBUG
[Info - Configuration] Loading plugins -- If any fail to load, run `siriproxy bundle` (not `bundle install`) to resolve.
[Notice - Server] ======================= WARNING: Running as root =============================
[Notice - Server] You should use -l or the config.yml to specify and non-root user to run under
[Notice - Server] Running the server as root is dangerous.
[Notice - Server] ==============================================================================
[Info - Server] Starting SiriProxy on 0.0.0.0:443...
[Info - Server] DNS server is not running yet, waiting 1 second...
[Info - Server] DNS Server started, tainting 'guzzoni.apple.com' with XXX.XXX.XXX.XXX
[Info - Server] SiriProxy up and running.
[Info - Guzzoni] Starting conneciton #<SiriProxy::Connection::Iphone:0x0000000828da90 @signature=5, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x0000000828d950>, @zip_stream=#Zlib::Deflate:0x0000000828d888, @consumed_ace=false, @name="iPhone", @upstream_dns=["XXX.XXX.XXX.XXX", "XXX.XXX.XXX.XXX", "XXX.XXX.XXX.XXX"], @ssled=false>
[Info - User Location] lat: XX.XX, long: X.XX
/usr/local/rvm/gems/ruby-1.9.3-p385@SiriProxy/bin/ruby_noexec_wrapper: Interrupt
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.

Anyone can help me ?

**Comment by elvisimprsntr** [comment]
First I recommend stepping up to Ruby 2.0.0 latest patch sets.

**Comment by spawnrider** [comment]
Passing from Ruby 1.9.3 to 2.0.0-rc2 solved the issue.
Thanks !

**Comment by elvisimprsntr** [comment]
RC2 is not the current version.   Check the ruby-lang.org site for latest.
