### ISSUE TITLE
Updates and stuff; need help

### ISSUE THREAD

**Issue by andymcblane** [plamoni/SiriProxy#559]
upon running "siriproxy update ."
I get this error:

pi@raspberrypi:~$ siriproxy update .
=== Installing from '.' ===
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/home/pi/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `eval'
/home/pi/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in`<main>'
(See full trace by running task with --trace)

When running "rake install"
I get this error : 

pi@raspberrypi:~$ rake install
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/home/pi/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `eval'
/home/pi/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in`<main>'
(See full trace by running task with --trace)

When running" rvmsudo siriproxy server -d 192.168.0.191 -u nobody"
I get this:
[Notice - Configuration] ==================== Important Configuration Notice ==========================
[Notice - Configuration] '/root/.siriproxy/config.yml' not found. Using '/home/pi/.rvm/gems/ruby-2.0.0-p247/gems/siriproxy-0.5.4/config.example.yml'
[Notice - Configuration]
[Notice - Configuration] Remove this message by copying '/home/pi/.rvm/gems/ruby-2.0.0-p247/gems/siriproxy-0.5.4/config.example.yml' into '~/.siriproxy/'
[Notice - Configuration] ==============================================================================
[Info - Configuration] Loading plugins -- If any fail to load, run `siriproxy bundle` (not `bundle install`) to resolve.
[Info - Server] Starting SiriProxy on 0.0.0.0:443...
[Info - Server] DNS server is not running yet, waiting 1 second...
[Info - Server] DNS Server started, tainting 'guzzoni.apple.com' with 192.168.0.191
[Info - Server] SiriProxy up and running.

I have created the config.yml but (AFAIK) siriproxy doesn't know about the change because I cannot do "siriproxy update ."

Any help would be awesome

Andy

**Comment by elvisimprsntr** [comment]
who's instructions are you using, because the sanctioned instructions do not require you to perform siriproxy update.  siriproxy should be installed as a gem.  if you already have siriproxy 0.5.4 gem installed, that is the current release

**Comment by elvisimprsntr** [comment]
the config.yml file in your case, needs to reside in the /home/pi/.siriproxy folder.

**Comment by andymcblane** [comment]
listen: 192.168.0.191
port: 443
log_level: 1
plugins:
- name: 'Example'
  path: './plugins/siriproxy-example'

That's in my config.yml

pi@raspberrypi:~/.siriproxy$ ls
ca.pem  cert.log  config.example.yml  config.yml  server.passless.crt  server.passless.key

Was following instructions on
https://github.com/plamoni/SiriProxy

**Comment by elvisimprsntr** [comment]
your config.yml file is incorrect.    you are missing information and  it appears the example plugin lines are not in the correct column.  https://github.com/plamoni/SiriProxy/blob/master/config.example.yml

**Comment by elvisimprsntr** [comment]
once you have a correctly formatted config.yml with all the content, run `sirirpoxy bundle`

**Comment by andymcblane** [comment]
After fixing my config.yml and running siriproxy bundle I get this

[Notice - Configuration] ==================== Important Configuration Notice ==========================
[Notice - Configuration] '/root/.siriproxy/config.yml' not found. Using '/home/pi/.rvm/gems/ruby-2.0.0-p247/gems/siriproxy-0.5.4/config.example.yml'
[Notice - Configuration]
[Notice - Configuration] Remove this message by copying '/home/pi/.rvm/gems/ruby-2.0.0-p247/gems/siriproxy-0.5.4/config.example.yml' into '~/.siriproxy/'
[Notice - Configuration] ==============================================================================
[Info - Configuration] Loading plugins -- If any fail to load, run `siriproxy bundle` (not `bundle install`) to resolve.
[Notice - Server] ======================= WARNING: Running as root =============================
[Notice - Server] You should use -l or the config.yml to specify and non-root user to run under
[Notice - Server] Running the server as root is dangerous.
[Notice - Server] ==============================================================================
[Info - Server] Starting SiriProxy on 0.0.0.0:443...
[Info - Server] DNS server is not running yet, waiting 1 second...
[Info - Server] DNS Server started, tainting 'guzzoni.apple.com' with 192.168.0.191
[Info - Server] SiriProxy up and running.
/home/pi/.rvm/gems/ruby-2.0.0-p247/gems/eventmachine-1.0.3/lib/em/connection.rb:411:in `block in start_tls': Could not find /root/.siriproxy/server.passless.key for start_tls (EventMachine::FileNotFoundException)
        from /home/pi/.rvm/gems/ruby-2.0.0-p247/gems/eventmachine-1.0.3/lib/em/connection.rb:409:in`each'
        from /home/pi/.rvm/gems/ruby-2.0.0-p247/gems/eventmachine-1.0.3/lib/em/connection.rb:409:in `start_tls'
        from /home/pi/.rvm/gems/ruby-2.0.0-p247/gems/siriproxy-0.5.4/lib/siriproxy/connection/iphone.rb:15:in`post_init'
        from /home/pi/.rvm/gems/ruby-2.0.0-p247/gems/eventmachine-1.0.3/lib/em/connection.rb:58:in `block in new'
        from /home/pi/.rvm/gems/ruby-2.0.0-p247/gems/eventmachine-1.0.3/lib/em/connection.rb:49:in`instance_eval'
        from /home/pi/.rvm/gems/ruby-2.0.0-p247/gems/eventmachine-1.0.3/lib/em/connection.rb:49:in `new'
        from /home/pi/.rvm/gems/ruby-2.0.0-p247/gems/eventmachine-1.0.3/lib/eventmachine.rb:1467:in`event_callback'
        from /home/pi/.rvm/gems/ruby-2.0.0-p247/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
        from /home/pi/.rvm/gems/ruby-2.0.0-p247/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in`run'
        from /home/pi/.rvm/gems/ruby-2.0.0-p247/gems/siriproxy-0.5.4/lib/siriproxy.rb:17:in `initialize'
        from /home/pi/.rvm/gems/ruby-2.0.0-p247/gems/siriproxy-0.5.4/lib/siriproxy/command_line.rb:106:in`new'
        from /home/pi/.rvm/gems/ruby-2.0.0-p247/gems/siriproxy-0.5.4/lib/siriproxy/command_line.rb:106:in `start_server'
        from /home/pi/.rvm/gems/ruby-2.0.0-p247/gems/siriproxy-0.5.4/lib/siriproxy/command_line.rb:90:in`run_server'
        from /home/pi/.rvm/gems/ruby-2.0.0-p247/gems/siriproxy-0.5.4/lib/siriproxy/command_line.rb:39:in `initialize'
        from /home/pi/.rvm/gems/ruby-2.0.0-p247/gems/siriproxy-0.5.4/bin/siriproxy:6:in`new'
        from /home/pi/.rvm/gems/ruby-2.0.0-p247/gems/siriproxy-0.5.4/bin/siriproxy:6:in `<top (required)>'
        from /home/pi/.rvm/gems/ruby-2.0.0-p247/bin/siriproxy:23:in`load'
        from /home/pi/.rvm/gems/ruby-2.0.0-p247/bin/siriproxy:23:in `<main>'

**Comment by elvisimprsntr** [comment]
These types of errors are precisely why I install and run everything as root on the RPi.    Use my SD Card image if you are not already.  http://sourceforge.net/p/siriproxyrpi/wiki/Home/

If you want to continue to use your installation, your options are:
- Create a copy of your /home/pi/.siriproxy folder in the /root/ path.  Unfortunately this means you will need log in as root, which the image from the raspberrypi.org site does not have a root password by default.  
  
  To create a root password, logged in as user:pi type `sudo passwd`
  Then log out and log back in as root
  Then copy the folder and contents: `cp -r /home/pi/.siriproxy /root/`
- Or, create a symbolic link to from the /root folder:  
  `cd /root`  
  `ln -s /home/pi/.siriproxy .siriproxy`
