### ISSUE TITLE
SiriProxy up and running...

### ISSUE THREAD

**Issue by FluffyWolfers** [plamoni/SiriProxy#561]
Nothing happens. I've looked EVERYWHERE and I've tried everything and it doesn't work. I start the server, point my dns servers to it (or I vpn into it), and it just doesn't work. I've tried to ping guzzoni.apple.com to see if it returned my local machine but it didn't. I have an iPhone 4S - iOS 6.1.3. Any help would be awesome! Thanks!

**Comment by elvisimprsntr** [comment]
It might help if you provide more details
1. Host OS distro
2. What version of RVM and Ruby
2.1 Who's instructions did you use to install and how did you install (user or root)
3. What command did you use to launch SiriProxy
4. Provide the output log
5. Did you turn off cellular data and toggle airplane mode off for 5 seconds

**Comment by elvisimprsntr** [comment]
1. How are you redirecting guzzoni.apple.com

**Comment by FluffyWolfers** [comment]
1. Ubuntu 12.04
2. Ruby 2.0.0 RVM 1.22.9 (stable)
   2.1. I used the new SiriProxy 0.5 tutorial by plamoni (I did it with user, not root)
3. I run this each time: "siriproxy bundle" and then "rvmsudo siriproxy server -d 192.168.13.162 -u nobody"
4. It prints this when I run it: http://pastebin.com/uqGAyFR4
5. Yes I did
6. I'm using dnsmasq, but I tried it without it and it still doesn't work.

**Comment by elvisimprsntr** [comment]
No need to open a duplicate ticket...

New questions/suggestions:
1. I assume you generated certificates and installed the ca.pem file on your iOS device
2. Did you change the DNS entry on your iOS device to the IP address of your server running SiriProxy? 
3. When using DNSMasq do not use the -d option.  When using the -d option make sure to kill the DNSMasq daemon. 
4. Leave cellular data off
