### ISSUE TITLE
SiriProxy up and running...

### ISSUE THREAD

**Issue by FluffyWolfers** [plamoni/SiriProxy#562]
Nothing happens. I've looked EVERYWHERE and I've tried everything and it doesn't work. I start the server, point my dns servers to it (or I vpn into it), and it just doesn't work. I've tried to ping guzzoni.apple.com to see if it returned my local machine but it didn't. I have an iPhone 4S - iOS 6.1.3. Any help would be awesome! Thanks!
- I'm using Ubuntu 12.04 (EDIT - I just upgraded to Ubuntu 12.10.)
- Versions: Ruby 2.0.0 RVM 1.22.9 (stable) 2.1. I used the new SiriProxy 0.5 tutorial by plamoni (I did it with user, not root)
- I run this each time: "siriproxy bundle" and then "rvmsudo siriproxy server -d 192.168.13.162 -u nobody"
- It prints this when I run it: http://pastebin.com/uqGAyFR4
- I did turn off network on my phone for at least 5 seconds.
- I'm using dnsmasq, but I tried it without it and it still doesn't work. (EDIT - I am no longer using dnsmasq. I took it away.)

**Comment by elvisimprsntr** [comment]
Duplicate
