### ISSUE TITLE
[SOLVED] RPi: [Plugins loaded: Example] whenever I open Siri

### ISSUE THREAD

**Issue by brysonreece** [plamoni/SiriProxy#564]
Downloaded Wheezy yesterday and followed instructions to set up SiriProxy and ran into this error. I figured I missed a step or something setting it up, so I downloaded the pre-made RPi SiriProxy image, installed it using the guide, and went on my way.
- I've already installed ca.pem
- I've set my RPi IP as Static on my router
- I've changed the DNS settings in iOS WiFi settings
  and pretty much anything else I've been able to think of.

Here's the output of "siriproxy server -d 192.168.254.11" :

> WARN: Unresolved specs during Gem::Specification.reset:
>       rake (>= 0)
> WARN: Clearing out unresolved specs.
> Please report a bug if this causes problems.
> [Info - Configuration] Loading plugins -- If any fail to load, run `siriproxy bundle` (not `bundle install`) to resolve.
> [Notice - Server] ======================= WARNING: Running as root =============================
> [Notice - Server] You should use -l or the config.yml to specify and non-root user to run under
> [Notice - Server] Running the server as root is dangerous.
> [Notice - Server] ==============================================================================
> [Info - Server] Starting SiriProxy on 0.0.0.0:443...
> [Info - Server] DNS server is not running yet, waiting 1 second...
> [Info - Server] DNS Server started, tainting 'guzzoni.apple.com' with 192.168.254.11
> [Info - Server] SiriProxy up and running.

After I open Siri on my iPhone, which is NOT jailbroken, I get:

> [Info - Plugin Manager] Plugins loaded: Example
> [Info - Plugin Manager] Plugins loaded: Example
> [Info - Plugin Manager] Plugins loaded: Example
> [Info - Plugin Manager] Plugins loaded: Example
> [Info - Plugin Manager] Plugins loaded: Example
> [Info - Plugin Manager] Plugins loaded: Example...

continuously looping.

Any ideas?

**Comment by monoxgas** [comment]
The looping issue with plugin loading was a known issue for us in siriproxy. We rewrote some of the code to stop if from happening. Tonight I'll hop and check to see what was changed and send you the related code. Does the proxy still function properly even though the plugins keep getting reloaded?

**Comment by monoxgas** [comment]
Here is the related lines from siriproxy.rb from the lib folder:

``` ruby
        listen_addr = $APP_CONFIG.listen || "0.0.0.0"
        puts "[Info - Server] Starting SiriProxy on #{listen_addr}:#{$APP_CONFIG.port}..."
        #Initialize the plugins and store the manager so they don't reload constantly
        manager = SiriProxy::PluginManager.new()
        manager.plugins.each_with_index do |plugin, i|
            if plugin.respond_to?('plugin_init')                                                                     
                $APP_CONFIG.plugins[i]['init'] = plugin.plugin_init
            end
        end
        EventMachine::start_server(listen_addr, $APP_CONFIG.port, SiriProxy::Connection::Iphone, $APP_CONFIG.upstream_dns) { |conn|
          puts "[Info - Guzzoni] Starting conneciton #{conn.inspect}" if $LOG_LEVEL < 1
          conn.plugin_manager = manager
          conn.plugin_manager.iphone_conn = conn
        }
```

And the code from command_line.rb:

``` ruby
def run_server(subcommand='start')
    load_code
    #init_plugins
    start_server
    # @todo: support for forking server into bg and start/stop/restart
    # subcommand ||= 'start'
    # case subcommand
    # when 'start'    then start_server
    # when 'stop'     then stop_server
    # when 'restart'  then restart_server
    # end
end
```

That should resolve the issues with the plugins reloading constantly. Good luck with the project!

**Comment by elvisimprsntr** [comment]
@brysonreece Are you running iOS 6 or 7?  SiriProxy doesn't work with iOS 7 yet.

**Comment by brysonreece** [comment]
@monoxgas I understand, but what exactly do I need to change? Oh, and no. The proxy isn't working as far as I can tell. I don't seem to be receiving any speech packets. Whenever I say "Test Siri Proxy" or any other inquiry, Siri says she can't answer any questions right now.

@elvisimprsntr I've tried both. Neither seem to work. Both result in the plugin looping.

**Comment by brysonreece** [comment]
@monoxgas I figured out what you meant. I edited those two files and it works now! For any future readers, the files are found in 

"/usr/local/rvm/gems/ruby-2.0.0-p195/gems/siriproxy-0.5.4/lib" 

and 

"/usr/local/rvm/gems/ruby-2.0.0-p195/gems/siriproxy-0.5.4/lib/siriproxy"

**Comment by monoxgas** [comment]
Glad you got it fixed! iOS7 isn't supported right now through siriproxy, so make sure you are using 6. If it still isn't working for you there,then something else is wrong.In order to help we will need all the details of your setup. I don't have the list right now, but I'm sure you can find the required information on another issue thread.

**Comment by brysonreece** [comment]
The only problem I've having now is that I can only say a few commands before I have to restart the server because the mic won't stop spinning.

**Comment by monoxgas** [comment]
Try turning your log level up in the config.yml, then re-running the server. Watch the individual packets and look for any errors with the connection between the iphone or guzonni when you see the lock up occur. We had ported an old plugin over to the new siriproxy 0.5 and had issues with bad/dropped packets due to some of the code in our plugin. (It seemed like unrelated code until we commented it)

**Comment by harald-billstein** [comment]
My pi stopped working, same error as above. Thought i did something wrong so i re-installed the server using this guide: http://sourceforge.net/p/siriproxyrpi/wiki/Home/ but still have same error. 

It did work a week ago. Im using ios6.

UPDATE!!
found the problem!

in the guide it says:

Install SiriProxy ca.pem certificate file on your iOS device.
a. Use the existing /root/.siriproxy/ca.pem file.
b. Or, generate a new certificate file.

I picked "A", that generated the error described  above. When trying to make my own cert it started to work again!

**Comment by elvisimprsntr** [comment]
@maxtolla glad you got it working.   I'll stop providing certs in the next SD card image.

**Comment by fideladio** [comment]
@elvisimprsntr Ok,  so we are here, I need to edit the siriproxy.rb and command_line.rb?
add those lines or rewrite the whole thing?

**Comment by elvisimprsntr** [comment]
I've never encountered the problem, thus I have never had to perform any if the suggested solutions.   Apparently the solutions work for some people, but I can't comment on the validity of the recommendations.

**Comment by monoxgas** [comment]
To comment on the solution I posted above, the related code/functions
should be found and replaced with the code I posted, not the entire file. I
highly recommend reading and comparing the code to understand the changes
first before messing with things.

Once again, the plugins reloading constantly should not interfere with
siriproxy's functions, we only found that it fills up the console output
and probably hogs memory.

**Comment by bachoo786** [comment]
@elvisimprsntr sorry for this out of topic question but I was wondering if we could use BIND as a DNS forwarder in rpi for siriproxy? The trouble is I do not want to change my iOS wifi settings i.e. DNS to match my rpi ip address because my iPad looses internet connection and wont connect to the internet unless I change the DNS settings to the original ones.

I played around with dnsmasq and like everyone has been getting “[Error - Server] Either you're not root or tcp/udp port 53 is in use. DNS server is disabled" siriproxy doesn’t work unless I change the iOS wifi settings (which gives me internet issues on my iPad) and remove dnsmasq from my pi.

Can you help please?

**Comment by elvisimprsntr** [comment]
You can try to enter multiple IP addresses in the DNS entry on your device.   List the RPi first and the original  second.   Separate the IP addresses with commas.  

E

**Comment by bachoo786** [comment]
Thanks Elvis ! that does solve the problem. 

I have made siriproxy to start from boot according to your instructions and it does start from boot but I am having trouble with “wiringpi” as it doesn’t switch on the light when siriproxy is made to start from boot. It only works when I kill the process and manually input “siriproxy server -d 192.168.0.6” and then wiringpi works and switches on the led.

Can you please advise on this issue? how can I resolve it? 

Thanks

**Comment by elvisimprsntr** [comment]
1. I don't have any familiarity with "wiringpi"  
   Does siriproxy respond to "test siri proxy" correctly when using the init.d script?
2. My init.d script runs siriproxy as root unless you changed it.  
   What account did you use to manually launch siriproxy vs. install wiringpi (perl, ruby gem, root, user, etc)?    It could be a permission or path issue.

**Comment by bachoo786** [comment]
1. Siriproxy does respond to test siri proxy regardless of when siriproxy starts from boot or when manual launched i.e. “siriproxy server -d 192.168.0.6” I am not sure what you mean by “when using init.d script”
2. I haven’t changed anything I just followed your instructions for starting siriproxy from boot, like I had mentioned from my previous post everything works with siriproxy i.e. “how warm is my pi”, “test siriproxy” etc.

I use root to launch siriproxy and when I had installed wiringpi. I just installed your image file on my pi to run siriproxy. 

NB: I am kinda new to linux.

Any help would be appreciated Elvis.

Many thanks.

**Comment by elvisimprsntr** [comment]
1. OK, since we have established that siriproxy works upon boot or manually launched, then it is not an issue with siriproxy, my SD cad image, or my instructions to automatically launch siriproxy upon boot. 
2. Your best method for help with wiringpi is to search the RPi forums or post a new question.  http://www.raspberrypi.org/phpBB3/ since this thread is for siriproxy only.
