### ISSUE TITLE
Catch multiple words in track name (iTunes plugin)

### ISSUE THREAD

**Issue by perfaram** [plamoni/SiriProxy#565]
Hi !
I'm trying to write a SiriProxy plugin that handles launching a specific track in iTunes (none of the plugins allow it). I'm pretty new to it, but here's what I wrote : 

``` ruby
listen_for /Play track ([a-z,]*) on my Mac/i do |track|
    say "Currently playing : #{track}"
    system("osascript -e 'tell application \"iTunes\" to play track \"#{track}\"'");
    request_completed
  end
```

So here's the problem is that it doesn't handle track name with multiple words, e.g when I say "Play track _Long Way_ on my Mac", SiriProxy tells me that there is "No matches". But when I say "Play track _Radio_ on my Mac", it's OK.

As I said, I'm pretty new to Ruby, so I think this is a small stupid mistake.

Thanks for your help !

**Comment by elvisimprsntr** [comment]
Ruby uses regular expressions (regex) which is standard for many scripting and programming languages, and some text editors.  

http://www.regular-expressions.info/ruby.html

You need to modify your regex in the listen_for line.  /play track (.*)/i 

I intentionally dropped the "on my Mac"   If you say it, it will be captured as part of the track name.   There are regex expression methods to make it optional, but are a bit more complicated than I have time to explain typing on my phone.

**Comment by perfaram** [comment]
It helped me a lot, _merci beaucoup_ !
