### ISSUE TITLE
siriproxy on vpn

### ISSUE THREAD

**Issue by HaTe87** [plamoni/SiriProxy#568]
hello to all
I followed the instructions and it works great ... siriproxy
now I have to take the next step:
I installed on a server vpn Pi and this also works, facts on the iphone I read that I'm connected to 192.168.xx.xx (local ip del Pi on which also runs the proxy) ...
but if I say "test siri proxy" proxy does not work.
I do not see even pass packets on promt
you have ideas on where there is a bug?

**Comment by elvisimprsntr** [comment]
This is not a bug with siriproxy.  You should review your VPN configuration, routing tables, etc., or posting your question on the RPi forums instead of here.  I suggest the following resources:
1. RPi VPN - http://www.raspberrypi.org/phpBB3/viewtopic.php?f=36&t=46961
2. DD-WRT VPN - http://www.youtube.com/watch?v=N97Xg2IovTA

**Comment by HaTe87** [comment]
on my router i'm not able to do DD-WRT VPN it's a wag320n

2013/11/11 Elvis notifications@github.com

**Comment by HaTe87** [comment]
i don't need to use dd-wrt because i'm using dnsmasq ( and the ip of pi
like dns )
and for my vpn connection i use that
http://raspberrypihelp.net/tutorials/21-pptp-vpn-server-raspberry-pi

2013/11/11 Elvis notifications@github.com

**Comment by elvisimprsntr** [comment]
I didn't say you had to use anything. I was merely offering a suggestion.  Sorry you can't run ddwrt on your router.   It really is the easiest way to perform the DNS redirect and VPN.  It eliminates the need to change any of the DNS settings on your iOS device, and the need to run dnsmasq or RubyDNS.

**Comment by HaTe87** [comment]
But if i use dnsmasq with VPN must to run?!

Inviato da iPhone

Il giorno 12/nov/2013, alle ore 15:18, Elvis notifications@github.com ha scritto:
