### ISSUE TITLE
[Documentation Request] How to setup local DNS server

### ISSUE THREAD

**Issue by coneybeare** [plamoni/SiriProxy#57]
I think that a common network setup amongst early adopter Mac enthusiasts would be an Airport Extreme and a Mac machine. Could you be more detailed on how to route the local DNS traffic to your local SiriProxy server? And how to let non Siri traffic pass through?

**Comment by plamoni** [comment]
This isn't really an "issue." We don't have time to train people in network architecture. This project is really only for experts right now. Sorry. If you figure it out and record a video, I'd be happy to post a link to it on the wiki.
