### ISSUE TITLE
open_uri problem

### ISSUE THREAD

**Issue by muhkuh0815** [plamoni/SiriProxy#59]
sry to bother you again. not sure if its a problem with siriproxy at all.

i have an mac snow leopard, rvm and ruby 1.9.3

if i try to put the   require 'open_uri'  in your siriproxy-example.rb  i get an open_uri loaderror
same with the Hockeyscore plugin

but if i make a new ruby testfile with just

require 'open-uri'
html = open('http://www.google.de/search?q=ruby').read
html_links = html.scan(/<h3 class="r">.+?<\/h3>/)
html_links.each do |link|
  link_url = link[/href="(.+?)"/,1]
  puts link_url
end

it works perfect.

i tried some google search, gem install und bundle install's but as open_uri should be standard with ruby
do i have to put it in some gem or gemspec files ? or is my ruby path f##ked up ?

any clues would be great

**Comment by netpro2k** [comment]
You need to include any runtime dependancies your plugin has in its gemspec and rerun bundle or they will not be pulled in to the environment. Also if you are running siriproxy as root be sure to use rvmsudo
