### ISSUE TITLE
Swapping udid

### ISSUE THREAD

**Issue by treason** [plamoni/SiriProxy#6]
My wife has a 4s. Given that I have her UDID, how can I make the proxy server use her ID? TIA

**Comment by plamoni** [comment]
Unfortunately, I've had a bit of a change of heart today on that. I'm not going to provide code to allow that to be done. If you can do the code yourself, then go for it. But I won't be adding that functionality to my version. Sorry! I don't want to get on Apple's bad side.

**Comment by treason** [comment]
Well that's a shame. I can probably get it going on my own but was hoping to save a couple hours. Thanks anyways
