### ISSUE TITLE
Strange Error

### ISSUE THREAD

**Issue by rwintle** [plamoni/SiriProxy#60]
I am installed, Proxy appears to start correctly.  As soon as I key Siri, a TON of text scrolls by.  Eventually Siri times out and I get this:

[Info - iPhone] Received Object: SetRestrictions
[Info - iPhone] Received Object: ClearContext
[Info - iPhone] Received Object: StartSpeechRequest
[Info - iPhone] Received Object: SetRequestOrigin
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: SpeechPacket
[Info - iPhone] Received Object: FinishSpeech
Create server for iPhone connection
ruby: ssl.cpp:162: SslContext_t::SslContext_t(bool, const std::string&, const std::string&): Assertion `e > 0' failed.
/home/rwintle/.rvm/bin/rvmsudo: line 46: 30964 Aborted                 sudo /usr/bin/env rvm_dump_environment_flag="0" rvm_bin_path="/home/rwintle/.rvm/bin" rvm_clang_flag="0" GEM_HOME="/home/rwintle/.rvm/gems/ruby-1.9.3-p0" IRBRC="/home/rwintle/.rvm/rubies/ruby-1.9.3-p0/.irbrc" MY_RUBY_HOME="/home/rwintle/.rvm/rubies/ruby-1.9.3-p0" rvm_verbose_flag="0" rvm_path="/home/rwintle/.rvm" rvm_debug_flag="0" rvm_prefix="/home/rwintle" PATH="/home/rwintle/.rvm/gems/ruby-1.9.3-p0/bin:/home/rwintle/.rvm/gems/ruby-1.9.3-p0@global/bin:/home/rwintle/.rvm/rubies/ruby-1.9.3-p0/bin:/home/rwintle/.rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games" rvm_version="1.9.2" GEM_PATH="/home/rwintle/.rvm/gems/ruby-1.9.3-p0:/home/rwintle/.rvm/gems/ruby-1.9.3-p0@global" rvm_reload_flag="0" RUBY_VERSION="ruby-1.9.3-p0" ruby start.rb
rwintle@media:~/SiriProxy$

Any thoughts?  I'm stumped :-)

Thanks!

**Comment by plamoni** [comment]
Regenerate your ssl certs and try again.

-Pete

Sent from my iPhone

On Nov 27, 2011, at 2:06 PM, rwintle
reply@reply.github.com
wrote:

**Comment by rwintle** [comment]
I regenerated using the new zsh script.  If I use a bogus profile on my iphone (generated from another machine), Siri does not connect at all.

**Comment by rwintle** [comment]
I found an issue with the script as it did not use the name "guzzoni".  So I generated manually.  Now as soon as I call SIRI, I get this:

rwintle@media:~/SiriProxy$ rvmsudo ruby start.rb
start.rb:3: warning: variable $KCODE is no longer effective; ignored
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Starting SiriProxy on port 443..
Create server for iPhone connection
ruby: ssl.cpp:167: SslContext_t::SslContext_t(bool, const std::string&, const std::string&): Assertion `e > 0' failed.
/home/rwintle/.rvm/bin/rvmsudo: line 46: 31546 Aborted                 sudo /usr/bin/env rvm_dump_environment_flag="0" rvm_bin_path="/home/rwintle/.rvm/bin" rvm_clang_flag="0" GEM_HOME="/home/rwintle/.rvm/gems/ruby-1.9.3-p0" IRBRC="/home/rwintle/.rvm/rubies/ruby-1.9.3-p0/.irbrc" MY_RUBY_HOME="/home/rwintle/.rvm/rubies/ruby-1.9.3-p0" rvm_verbose_flag="0" rvm_path="/home/rwintle/.rvm" rvm_debug_flag="0" rvm_prefix="/home/rwintle" PATH="/home/rwintle/.rvm/gems/ruby-1.9.3-p0/bin:/home/rwintle/.rvm/gems/ruby-1.9.3-p0@global/bin:/home/rwintle/.rvm/rubies/ruby-1.9.3-p0/bin:/home/rwintle/.rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games" rvm_version="1.9.2" GEM_PATH="/home/rwintle/.rvm/gems/ruby-1.9.3-p0:/home/rwintle/.rvm/gems/ruby-1.9.3-p0@global" rvm_reload_flag="0" RUBY_VERSION="ruby-1.9.3-p0" ruby start.rb

This seems similar to having a bad cert?

**Comment by plamoni** [comment]
The script does use guzzoni... otherwise it wouldn't work for anyone. Nto
sure what you mean by "generated manually," but it really does look like
you've got a messed up cert there. You need to read the output from the
script carefully and figure out what's wrong with it. This is not a simple
task and there are no straightforward instructions on how to fix things.
That's one of the many reasons why this project is really geared towards
experts in programming and network architecture at the moment.

We're working on making it more user friendly, but that's a low priority
right now, so I'm not sure if you'll be able to get up and running in the
near future.

-Pete

On Sun, Nov 27, 2011 at 4:26 PM, rwintle <
reply@reply.github.com

**Comment by rwintle** [comment]
Just and FYI, but, default the script uses "SiriProxy"  I change it to Guzzoni:

# Feel free to change any of these defaults

countryName="UK"
stateOrProvinceName="England"
localityName=""
organizationName="Siri Proxy"
organizationalUnitName=""
commonName="guzzoni.apple.com"
emailAddress=""

By manual, I mean the method you outline in your video and directions.  

Are you saying the script uses guzzoni when the common name variable is set to SiriProxy?

**Comment by plamoni** [comment]
You have to read ALL the code in the script before claiming that it doesn't
work... not just the start. :-)

https://github.com/plamoni/SiriProxy/blob/master/gen_certs.zsh#L26

You have to scoot over to the right a bit and read carefully. The code is
easier to read in my revised version of the script:

https://github.com/plamoni/SiriProxy/blob/gemify/scripts/gen_certs.sh#L52

But the effect is the same.

-Pete

On Sun, Nov 27, 2011 at 8:49 PM, rwintle <
reply@reply.github.com

**Comment by rwintle** [comment]
Sorry about that :-)

I did find one thing interesting.  It turns out my .rnd file in my home dir was owned by root and not writeable.  I fixed that and generated a new key.  The results are different but still fail.

I do appreciate you spending the time to look at this.  I'll continue to look it over and see if there is something odd I am doing:

Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x00000016b3a090 @signature=1017, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x00000016b39f28>, @zip_stream=#Zlib::Deflate:0x00000016b39f00, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x00000016b39370 @manager=#<SiriProxy::PluginManager:0x00000016b39b68 @plugins=[...]>>, #<SiriProxy::Plugin::Thermostat:0x00000016b49658 @host="192.168.2.71", @manager=#<SiriProxy::PluginManager:0x00000016b39b68 @plugins=[...]>>]

[Info - iPhone] Received Object: CreateSessionInfoRequest
[Info - iPhone] Received Object: CreateSessionInfoRequest
Create server for iPhone connection
ruby: ssl.cpp:162: SslContext_t::SslContext_t(bool, const std::string&, const std::string&): Assertion `e > 0' failed.
/home/rwintle/.rvm/bin/rvmsudo: line 46: 32200 Aborted                 sudo /usr/bin/env rvm_dump_environment_flag="0" rvm_bin_path="/home/rwintle/.rvm/bin" rvm_clang_flag="0" GEM_HOME="/home/rwintle/.rvm/gems/ruby-1.9.3-p0" IRBRC="/home/rwintle/.rvm/rubies/ruby-1.9.3-p0/.irbrc" MY_RUBY_HOME="/home/rwintle/.rvm/rubies/ruby-1.9.3-p0" rvm_verbose_flag="0" rvm_path="/home/rwintle/.rvm" rvm_debug_flag="0" rvm_prefix="/home/rwintle" PATH="/home/rwintle/.rvm/gems/ruby-1.9.3-p0/bin:/home/rwintle/.rvm/gems/ruby-1.9.3-p0@global/bin:/home/rwintle/.rvm/rubies/ruby-1.9.3-p0/bin:/home/rwintle/.rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games" rvm_version="1.9.2" GEM_PATH="/home/rwintle/.rvm/gems/ruby-1.9.3-p0:/home/rwintle/.rvm/gems/ruby-1.9.3-p0@global" rvm_reload_flag="0" RUBY_VERSION="ruby-1.9.3-p0" ruby start.rb
rwintle@media:~/SiriProxy$

**Comment by plamoni** [comment]
Try switching to the gemify branch and using "siriproxy gencerts"

It's much less prone to error.

Read the readme on the gemify branch for installation info.

-Pete

On Sun, Nov 27, 2011 at 9:10 PM, rwintle <
reply@reply.github.com

**Comment by rwintle** [comment]
Ok, I switched over to the new branch:

The install is much easier :-)

One issue.  Whenever I run siriproxy for any of the install process (gencerts, bundle, rvmsudo siriproxy server), or even just "siriproxy" by itself, I get the same error:

$ siriproxy
/Users/rwintle/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require': cannot load such file -- siriproxy/command_line (LoadError)
    from /Users/rwintle/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in`require'
    from /Users/rwintle/.rvm/gems/ruby-1.9.3-p0/gems/siriproxy-0.0.1/bin/siriproxy:4:in `<top (required)>'
    from /Users/rwintle/.rvm/gems/ruby-1.9.3-p0/bin/siriproxy:19:in`load'
    from /Users/rwintle/.rvm/gems/ruby-1.9.3-p0/bin/siriproxy:19:in `<main>'

It would appear that a require statement is failing to locate the file within the existing loadpath or any gems?

**Comment by plamoni** [comment]
There is another issue open regarding the most recent report. Check ther for more info.
