### ISSUE TITLE
start siri

### ISSUE THREAD

**Issue by ishaper** [plamoni/SiriProxy#61]
Hi guys,

I worked things out. And everything is ok:

in terminal is stays on:

iShaper-Network:SiryProxy pepynhoff$ rvmsudo ruby start.rb
Password:
start.rb:3: warning: variable $KCODE is no longer effective; ignored
/Users/pepynhoff/Desktop/SiryProxy/plugins/siriproxy-example/siriproxy-example.gemspec:15: warning: Insecure world writable dir /usr/local in PATH, mode 040777
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Starting SiriProxy on port 443..

And I connected the iphone to my home wifi, but its not working when i say test siri proxy?

Could someone help me please?

**Comment by Angrychipmunk** [comment]
well for he git repo issue try running "git init" and see if that clears that up

**Comment by venom420x** [comment]
make sure you have dnsmasq running to the computer you hav ruby set up on

**Comment by plamoni** [comment]
That should be "sudo lsof -i :443 | grep LISTEN" (that's a "|", not an
"l"... it's <shift>-"\").

-Pete

On Sun, Nov 27, 2011 at 2:31 PM, ishaper <
reply@reply.github.com
