### ISSUE TITLE
Starting Error

### ISSUE THREAD

**Issue by Angrychipmunk** [plamoni/SiriProxy#62]
Nicholas-Youngs-MacBook-Pro:siri2 nickyoung$ sudo ruby start.rb
start.rb:3: warning: variable $KCODE is no longer effective; ignored
/Users/nickyoung/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': no such file to load -- bundler (LoadError)
    from /Users/nickyoung/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from start.rb:6:in `<main>'
Nicholas-Youngs-MacBook-Pro:siri2 nickyoung$ 

i get that error, i tried reinstalling ruby didn't work.

Any ideas?

**Comment by Extman** [comment]
Did you solve the problem??

**Comment by Angrychipmunk** [comment]
Yes, i do not know how but i did
