### ISSUE TITLE
rvmsudo ruby start.rb ERROR

### ISSUE THREAD

**Issue by jrdennis95** [plamoni/SiriProxy#64]
Hi guys, I'm really enjoying finding out what's wrong and trying to fix it :D... here goes..

After I run rvmsudo ruby start.rb, this error appears:

start.rb:3: warning: variable $KCODE is no longer effective; ignored
/Users/jrdennis95/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- bundler (LoadError)
    from /Users/jrdennis95/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from start.rb:6:in `<main>'

I'm on ruby 1.9.3, and I've set it to default. I'm really wondering what's the error. Thank you! :)

**Comment by plamoni** [comment]
You need to install the bundled gem.

gem install bundler

-Pete

Sent from my iPhone

On Nov 28, 2011, at 8:29 AM, jrdennis95
reply@reply.github.com
wrote:

**Comment by jrdennis95** [comment]
I installed it, and then put in rvmsudo ruby start.rb again and it came out with this:

start.rb:3: warning: variable $KCODE is no longer effective; ignored
/Users/jrdennis95/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- bundler (LoadError)
    from /Users/jrdennis95/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from start.rb:6:in `<main>'

which is the same as before :o

**Comment by brianantonelli** [comment]
Have you tried `sudo bundle install`

**Comment by jrdennis95** [comment]
sudo bundle install gives this:

/Users/jrdennis95/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:247:in `to_specs': Could not find bundler (>= 0) amongst [bigdecimal-1.1.0, io-console-0.3, json-1.5.4, minitest-2.5.1, rake-0.9.2.2, rdoc-3.9.4] (Gem::LoadError)
    from /Users/jrdennis95/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:256:in`to_spec'
    from /Users/jrdennis95/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems.rb:1210:in `gem'
    from /Users/jrdennis95/.rvm/gems/ruby-1.9.3-p0/bin/bundle:18:in`<main>'

Normal bundle install installs them normally.

**Comment by brianantonelli** [comment]
typo on my part, it should be bundler:

`sudo bundle install`

**Comment by jrdennis95** [comment]
if I type sudo bundler install it says the command isn't found. I'm assuming it can't find the bundler file installed in ruby, but I wonder why..

**Comment by kalbasit** [comment]
Try

``` bash
rvm use system
sudo gem install bundler
sudo bundle install
```

rvm use system give you access to the system's ruby, if you do not intend to do so, then do not use sudo when installing gems

**Comment by kalbasit** [comment]
Actually try this instead (I haven't used SiriProxy myself, but this should do it)

``` bash
rvm use 1.9.3
gem install bundler
bundle install
rvmsudo ruby start.rb
```
