### ISSUE TITLE
Expose Location Info to Plugins

### ISSUE THREAD

**Issue by mannkind** [plamoni/SiriProxy#67]
Previously, the "legacy" code allowed plugins access to the location information (well, in a roundabout way), but the new code doesn't that I can see.

I noticed that someone made a small modification to the new code to expose location information the plugins. 

https://github.com/simonmaddox/SiriProxy/commit/5133fca82532061e806e862e174b087505fc1ea3

Please consider merging the commit or doing something similar so that plugins have access to the location information.

Thanks!

**Comment by plamoni** [comment]
We're working on it. Thanks for the encouragement!!

-Pete

Sent from my iPhone

On Nov 28, 2011, at 12:43 PM, Dustin Brewer
reply@reply.github.com
wrote:

**Comment by netpro2k** [comment]
This could be a good place to discuss best way to surface it. I would think plugins should both be able to retrieve last location as well as trigger a new location request
