### ISSUE TITLE
Start.rb Error

### ISSUE THREAD

**Issue by KirmaanA** [plamoni/SiriProxy#69]
When i start Siriproxy This Is What Happens 

rvmsudo ruby start.rb
start.rb:3: warning: variable $KCODE is no longer effective; ignored
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Starting SiriProxy on port 443..

Its Also Stuck On "Starting SiriProxy on port 443..'

Please Help, Thanks

**Comment by netpro2k** [comment]
the git errors are expected on master, and have been fixed in the gemify branch. In any case they are harmless. You are not stuck, there should not be any output after "Starting SiriProxy on port 443" until you invoke siri
