### ISSUE TITLE
Bundler Issue

### ISSUE THREAD

**Issue by KirmaanA** [plamoni/SiriProxy#70]
When I Attempt To Run "Bundle Install" This Is What Comes Out 

sudo bundle install
/Users/Kirmaan/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:247:in `to_specs': Could not find bundler (>= 0) amongst [bigdecimal-1.1.0, io-console-0.3, json-1.5.4, minitest-2.5.1, rake-0.9.2.2, rdoc-3.9.4] (Gem::LoadError)
    from /Users/Kirmaan/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:256:in`to_spec'
    from /Users/Kirmaan/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems.rb:1210:in `gem'
    from /Users/Kirmaan/.rvm/gems/ruby-1.9.3-p0/bin/bundle:18:in`<main>'

Thannks

**Comment by KirmaanA** [comment]
Hi, I Got That Working But Now I Get This Error

rvmsudo bundle install
Password:
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Fetching git://github.com/chendo/cora.git
remote: Counting objects: 202, done.
remote: Compressing objects: 100% (146/146), done.
remote: Total 202 (delta 85), reused 162 (delta 45)
Receiving objects: 100% (202/202), 21.26 KiB, done.
Resolving deltas: 100% (85/85), done.
ssh: Could not resolve hostname /Users/Kirmaan/Desktop/SiriProxy/git: nodename nor servname provided, or not known
fatal: The remote end hung up unexpectedly
Git error: command `git clone --no-checkout "/Users/Kirmaan/Desktop/SiriProxy/git:/github.com/netpro2k/SiriProxy-AnotherPlugin.git/ruby/1.9.1/cache/bundler/git/cora-e7aa6b357e86be8b6f2707576ceb77632f2c12aa" "/Users/Kirmaan/Desktop/SiriProxy/git:/github.com/netpro2k/SiriProxy-AnotherPlugin.git/ruby/1.9.1/bundler/gems/cora-1aac57f0f6d5"` in directory /Users/Kirmaan/Desktop/SiriProxy has failed.
If this error persists you could try removing the cache directory '/Users/Kirmaan/Desktop/SiriProxy/git:/github.com/netpro2k/SiriProxy-AnotherPlugin.git/ruby/1.9.1/cache/bundler/git/cora-e7aa6b357e86be8b6f2707576ceb77632f2c12aa'

Thanks

**Comment by netpro2k** [comment]
It looks like something is wrong with your Config.yml, looks like its trying to load twitter plugin via path instead of git

**Comment by Extman** [comment]
How did you solve the first problem?

**Comment by KirmaanA** [comment]
I just changed the config.yml
