### ISSUE TITLE
Running Error

### ISSUE THREAD

**Issue by JordanCrosby** [plamoni/SiriProxy#71]
imac:Siri djcrosby101$ rvmsudo ruby start.rb
start.rb:3: warning: variable $KCODE is no longer effective; ignored
/Users/djcrosby101/Siri/plugins/siriproxy-example/siriproxy-example.gemspec:15: warning: Insecure world writable dir /Users in PATH, mode 040777
Starting SiriProxy on port 443..
/Users/djcrosby101/Siri/siri_proxy.rb:26:in `rescue in block in initialize': Cannot start the server on port 443 - are you root, or have another process on this port already? (RuntimeError)
    from /Users/djcrosby101/Siri/siri_proxy.rb:17:in`block in initialize'
    from /Users/djcrosby101/.rvm/gems/ruby-1.9.2-p290/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `call'
    from /Users/djcrosby101/.rvm/gems/ruby-1.9.2-p290/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run_machine'
    from /Users/djcrosby101/.rvm/gems/ruby-1.9.2-p290/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
    from /Users/djcrosby101/Siri/siri_proxy.rb:16:in`initialize'
    from start.rb:22:in `new'
    from start.rb:22:in`<main>'

Can anybody help ?

**Comment by netpro2k** [comment]
As the error says, you have another process using port 443, you need to close this first before running siriproxy.
