### ISSUE TITLE
start.rb:3: warning

### ISSUE THREAD

**Issue by JordanCrosby** [plamoni/SiriProxy#73]
start.rb:3: warning: variable $KCODE is no longer effective; ignored
/Users/djcrosby101/Siri/plugins/siriproxy-example/siriproxy-example.gemspec:15: warning: Insecure world writable dir /Users in PATH, mode 040777
Starting SiriProxy on port 443..

can anybody help ?

**Comment by netpro2k** [comment]
The first warning is expected (it has been fixed in gemify branch)
The second is because your permissions on the SiriProxy folder are too liberal (set to 777) . This should not effect siriproxy functioning and is not an issue with siriproxy.

**Comment by JordanCrosby** [comment]
I have changed the chmod and still nothing happening
