### ISSUE TITLE
Start.rb

### ISSUE THREAD

**Issue by lwalsh** [plamoni/SiriProxy#74]
EDIT

/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- bundler (LoadError)
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from start.rb:6

This is my error.

when I follow the path given there is a custom_require.rb
There is no :31

**Comment by netpro2k** [comment]
you should install ruby through rvm as stated in the readme.
