### ISSUE TITLE
Event Machine Error

### ISSUE THREAD

**Issue by KirmaanA** [plamoni/SiriProxy#76]
Okay When I Start SiriServer (start.rb) This Is What Comes Out

sudo ruby /Users/Kirmaan/Desktop/SiriProxy/start.rb 
/Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require': no such file to load -- eventmachine (LoadError)
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`require'
    from /Users/Kirmaan/Desktop/SiriProxy/siri_proxy.rb:1
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`require'
    from /Users/Kirmaan/Desktop/SiriProxy/start.rb:12

**Comment by KirmaanA** [comment]
Okay Ive Fixed That But Now This Is My Problem

rvmsudo /Users/Kirmaan/Desktop/SiriProxy/start.rb 
/Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require': no such file to load -- cora (LoadError)
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`require'
    from /Users/Kirmaan/Desktop/SiriProxy/siri_proxy/plugin.rb:1
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in`require'
    from /Users/Kirmaan/Desktop/SiriProxy/start.rb:17

**Comment by netpro2k** [comment]
You appear to be running on ruby 1.8, please use rvm to install and use ruby 1.9.3
