### ISSUE TITLE
rake install issue.

### ISSUE THREAD

**Issue by James-Huffman** [plamoni/SiriProxy#77]
Had a problem with the previous version (few hours ago) where the gencert script didn't work and spat out something about not being able to load the command_line (load failed)

now won't complete command "rake install"

jamesmbp:SiriProxy jameshuffma$ rake install
rake aborted!
Don't know how to build task 'install'

(See full trace by running task with --trace)
jamesmbp:SiriProxy jameshuffma$

**Comment by James-Huffman** [comment]
Also to note this is only a problem with the gemify variant of the proxy. I had problems with the root version, but I think the issues I had were related to the recent siri outages.

**Comment by James-Huffman** [comment]
Here's what I'm getting for rake install —trace

jamesmbp:SiriProxy jameshuffma$ rake install --trace
rake aborted!
Don't know how to build task 'install'
/Users/jameshuffma/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2.2/lib/rake/task_manager.rb:49:in `[]'
/Users/jameshuffma/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2.2/lib/rake/application.rb:115:in`invoke_task'
/Users/jameshuffma/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
/Users/jameshuffma/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in`each'
/Users/jameshuffma/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
/Users/jameshuffma/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2.2/lib/rake/application.rb:133:in`standard_exception_handling'
/Users/jameshuffma/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/Users/jameshuffma/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2.2/lib/rake/application.rb:66:in`block in run'
/Users/jameshuffma/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Users/jameshuffma/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2.2/lib/rake/application.rb:63:in`run'
/Users/jameshuffma/.rvm/gems/ruby-1.9.3-p0/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/Users/jameshuffma/.rvm/gems/ruby-1.9.3-p0/bin/rake:19:in`load'
/Users/jameshuffma/.rvm/gems/ruby-1.9.3-p0/bin/rake:19:in `<main>'
jamesmbp:SiriProxy jameshuffma$

**Comment by netpro2k** [comment]
sounds like something is up with your rake file.. Try pulling down the code again.
