### ISSUE TITLE
Start.rb

### ISSUE THREAD

**Issue by lwalsh** [plamoni/SiriProxy#78]
This is my current error. 
Can someone shed some light on why I am not getting past this?

I notice the YAML mentioned below.
But if I save config.yaml I get an error to save it as .yml

Macintosh-5:SiriProxy macbookpro$ rvmsudo ruby start.rb
start.rb:3: warning: variable $KCODE is no longer effective; ignored
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Starting SiriProxy on port 443..
/Users/macbookpro/Desktop/SiriProxy/siri_proxy.rb:26:in `rescue in block in initialize': Cannot start the server on port 443 - are you root, or have another process on this port already? (RuntimeError)
    from /Users/macbookpro/Desktop/SiriProxy/siri_proxy.rb:17:in`block in initialize'
    from /Users/macbookpro/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `call'
    from /Users/macbookpro/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run_machine'
    from /Users/macbookpro/.rvm/gems/ruby-1.9.3-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
    from /Users/macbookpro/Desktop/SiriProxy/siri_proxy.rb:16:in`initialize'
    from start.rb:22:in `new'
    from start.rb:22:in`<main>'

THANKS!

**Comment by venom420x** [comment]
its supposed to be config.yml not yaml and there is something using port 443 most common is other instances of ruby running from opening and closing the start.rb in terminal. try

sudo killall ruby

and then rvmsudo ruby start.rb after you set the name of the config file of course
