### ISSUE TITLE
Connection Issues

### ISSUE THREAD

**Issue by ahajjar** [plamoni/SiriProxy#79]
So I've gone through and properly installed the SiriProxy in an Ubuntu 10.10 installation.  When I attempt "Test Siri Proxy" it seems that I'm receiving speech packets and it goes in an endless loop and finally aborts with the following message:

Create server for iPhone connection
ruby: ssl.cpp:162: SslContext_t::SslContext_t(bool, const std::string&, const std::string&): Assertion `e > 0' failed.
/home/ahajjar/.rvm/bin/rvmsudo: line 46: 24774 Aborted                 sudo /usr/bin/env rvm_dump_environment_flag="0" rvm_bin_path="/home/ahajjar/.rvm/bin" rvm_clang_flag="0" GEM_HOME="/home/ahajjar/.rvm/gems/ruby-1.9.3-p0" IRBRC="/home/ahajjar/.rvm/rubies/ruby-1.9.3-p0/.irbrc" MY_RUBY_HOME="/home/ahajjar/.rvm/rubies/ruby-1.9.3-p0" rvm_verbose_flag="0" rvm_path="/home/ahajjar/.rvm" rvm_debug_flag="0" rvm_prefix="/home/ahajjar" rvm_trace_flag="0" PATH="/home/ahajjar/.rvm/gems/ruby-1.9.3-p0/bin:/home/ahajjar/.rvm/gems/ruby-1.9.3-p0@global/bin:/home/ahajjar/.rvm/rubies/ruby-1.9.3-p0/bin:/home/ahajjar/.rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games" rvm_version="1.10.0-pre" GEM_PATH="/home/ahajjar/.rvm/gems/ruby-1.9.3-p0:/home/ahajjar/.rvm/gems/ruby-1.9.3-p0@global" rvm_reload_flag="0" RUBY_VERSION="ruby-1.9.3-p0" ruby start.rb

Any suggestions?

**Comment by netpro2k** [comment]
The computer running siriproxy should not be using dnsmasq for dns, or it will loop back on itself. Use a different dns server for that computer.

**Comment by ahajjar** [comment]
Thanks for the quick response, that did the trick.
