### ISSUE TITLE
Can bind be used instead?

### ISSUE THREAD

**Issue by thejipster** [plamoni/SiriProxy#80]
All you are trying to do is resolve guzzoni.apple.com to point to the IP address where SiriProxy is running right ?  
I tried making a subdomain guzzoni.apple.com and put the pertinent SOA, NS, A record information.  Nslookup guzzoni.apple.com returns the IP address of the SiriProxy server, however, my iPhone continues to say that it is having problems connecting to the network.

**Comment by thejipster** [comment]
I see the the Siriproxy logs, but the phone keeps saying "Sorry I don't have a network connection"

Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0xfdfd2cc @signature=25, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x123adf178>, @zip_stream=#Zlib::Deflate:0x12fsfsdf, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#SiriProxy::Plugin::Example:xcsxasd@manager=#<SiriProxy::PluginManager:1231232321@plugins=[...]>]

**Comment by James-Huffman** [comment]
I'm having the same issue. On the one hand I thought this was related to the siri outages the last few days, however siri works fine for me over 3G some of the time. Not sure what the issue here is. It looks like the server is doing its job and sending the request to the guzzoni servers, but apple's servers never send back the transcribed text. Sometimes they do respond, but it ends up being several minutes later. May just have to wait it out til the siri servers are back to normal. Have to remember this is a beta. these things do happen.

**Comment by thejipster** [comment]
I partially solved my issue. I had imported the ca cert into my iPhone 4 and not my 4s.   Doh.   

But maybe Siri was having issues last night like you said because I see the voice packer logs increment but I see no return from siri with the text response.  After a while the proxy crashes.

**Comment by netpro2k** [comment]
make sure the proxy can still resolve the real guzzoni.apple.com or it wont be able to get through. As in, machine with proxy running should not be pointing to your modified dns server (be that bind, or dnsmasq)

**Comment by thejipster** [comment]
Ok. Thanks for pointing that out!!  I'll update my resolv.conf and test it out later.   Next thing is to learn ruby.

**Comment by thejipster** [comment]
I got this to work. I then try to update the siriproxy-example.rb file under/plugins/siriproxy-example/lib to test adding some additional commands to listen for, but I can't seem to get Siriproxy to recognize it.
I issued a siriporxy update as well as a gem build siriproxy.gemspec
What am I missing?
