### ISSUE TITLE
Need clarification...

### ISSUE THREAD

**Issue by JBX028** [plamoni/SiriProxy#81]
Because I still have issue on how to properly install siriproxy, I am not able to answer simple questions myself.

Could you confirm (or not) if it is possible to create a plugin that will just intercept any answers given by siri. If i am not wrong, what the proxy does is to intercept the sentence recognised (voice recognition) but not the standard answer given by Siri? i would like to use the standard siri answer to do something else with. It is possible with the current version of siriproxy ?

Also, could you clarify a little bit the whole process. Let's say i said "Hello Siri", and imagine that i do not manage this syntax within my script, does it mean that because i do not manage an answer for this pattern, Siri will not say anything, OR does it mean that if a sentence is not managed by the script, the standard siri mecanism will take the relay ?

Sorry for all those questions but what i would like to do is to manage some interactions and let siri give the standard answer for the rest and refering to my first question, i would like to intercept all the answers given by siri (standard or created by me ->not a pb).

Thanks,
Johnny Baillargeaux (France)

**Comment by ghost** [comment]
I do not know that answer to your first question but as far as the 2nd it would be sent to apple's servers if your script doesn't have a match.

**Comment by JBX028** [comment]
ok make sense. It mean that our script works on top of the standard functionnality and we don't have to stop the ruby siri server to switch to the standard interaction.

Anybody for the first question ? Are we able to capture standard answer given by siri ?

Thanks,
Johnny Baillargeaux

**Comment by netpro2k** [comment]
If you ened to intercept the original response from Siri, your plugin would be implemented as what we are calling a "Filter" - Support for filters is coming soon.
