### ISSUE TITLE
`rescue in block in initialize': Cannot start the server on port 433

### ISSUE THREAD

**Issue by LouisGhijselings** [plamoni/SiriProxy#82]
Hello,

I'm having a problem setting up the siri proxy server.

this is what it said:

macbook-pro-15-van-louis-ghijselings-2:SiriProxy louisghijselings$ rvmsudo ruby start.rb
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Starting SiriProxy on port 443..
/Users/louisghijselings/Desktop/SiriProxy/siri_proxy.rb:26:in `rescue in block in initialize': Cannot start the server on port 443 - are you root, or have another process on this port already? (RuntimeError)
    from /Users/louisghijselings/Desktop/SiriProxy/siri_proxy.rb:17:in`block in initialize'
    from /Users/louisghijselings/.rvm/gems/ruby-1.9.2-p290/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `call'
    from /Users/louisghijselings/.rvm/gems/ruby-1.9.2-p290/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run_machine'
    from /Users/louisghijselings/.rvm/gems/ruby-1.9.2-p290/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
    from /Users/louisghijselings/Desktop/SiriProxy/siri_proxy.rb:16:in`initialize'
    from start.rb:21:in `new'
    from start.rb:21:in`<main>'
macbook-pro-15-van-louis-ghijselings-2:SiriProxy louisghijselings$ 

I've encountered this issue here already but with them it was solved.

When i check what is running on port 433 it gives me this

macbook-pro-15-van-louis-ghijselings-2:SiriProxy louisghijselings$ sudo lsof -i :443 | grep LISTEN
Password:
ruby        313             root    6u  IPv4 0xffffff8012835160      0t0  TCP *:https (LISTEN)
macbook-pro-15-van-louis-ghijselings-2:SiriProxy louisghijselings$ sudo lsof -i:433
macbook-pro-15-van-louis-ghijselings-2:SiriProxy louisghijselings$ 

So it appears there is nothing open at port 433. What is going wrong here?

**Comment by ghost** [comment]
If you look closely at your statement you will find your issues

sudo lsof -i :443 | grep LISTEN is showing you that PID 313 is running on 443 - ruby

your second command
sudo lsof -i:433

is showing you nothing because SiriProxy is not running on 433 it is 443

Run this:
sudo kill -9 PID-NUMBER

and try again

**Comment by LouisGhijselings** [comment]
ok got it running now i guess :D

macbook-pro-15-van-louis-ghijselings-2:SiriProxy louisghijselings$ cd /Users/louisghijselings/Desktop/SiriProxy 
macbook-pro-15-van-louis-ghijselings-2:SiriProxy louisghijselings$ sudo lsof -i :443 | grep LISTEN
ruby      34140             root    6u  IPv4 0xffffff8010331fa0      0t0  TCP *:https (LISTEN)
macbook-pro-15-van-louis-ghijselings-2:SiriProxy louisghijselings$  sudo kill -9 34140
macbook-pro-15-van-louis-ghijselings-2:SiriProxy louisghijselings$ rvmsudo ruby start.rb
Starting SiriProxy on port 443..

But now when i say "test siri proxy" to siri, she answers: sorry i don't understand "test siri proxy"
Also nothing apears on my screen. I have created a fake CA and uploaded it on my iphone 4s. DNSMASQ is up and running and "adress=/guzzoni.apple.com/10.0.1.2" is added to the DNSMASQ.conf file.

**Comment by netpro2k** [comment]
you need to point your iphone's dns at your dnsmasq server or it will not go through the proxy
