### ISSUE TITLE
start.rb cannot find bundler

### ISSUE THREAD

**Issue by Extman** [plamoni/SiriProxy#83]
Hi,
I've got this problem, when trying to start the server:

$ sudo ruby start.rb  
start.rb:5: warning: variable $KCODE is no longer effective; ignored
start.rb:8:in `require_relative': cannot load such file -- /Users/parsaamini/SiriProxy/bundler (LoadError)
    from start.rb:8:in`<main>'

I know, many others had this problem but i didn't find any solution that worked. I would be really glad if someone could help me.

**Comment by Extman** [comment]
In start.rb I had changed 
require 'bundler'    to    require_relative 'bundler'

Before I did this I got this error:

$ sudo ruby start.rb
start.rb:5: warning: variable $KCODE is no longer effective; ignored
/Users/parsaamini/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- bundler (LoadError)
    from /Users/parsaamini/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from start.rb:8:in `<main>'

**Comment by netpro2k** [comment]
use rvmsudo not sudo

**Comment by Extman** [comment]
Also with rvmsudo it doesn't work

**Comment by netpro2k** [comment]
The code has changed a lot, try pulling down the latest copy and following the latest instructions
