### ISSUE TITLE
Get input

### ISSUE THREAD

**Issue by ghost** [plamoni/SiriProxy#84]
First off great work on this project.

2nd: Are there forums anywhere for this project instead of using the issues section to post questions or an IRC channel?

last my question:

how would I go about getting a users input without having to be something specific?
Example: 
listen_for /Connect to _could be one or multiple words here_/i do

I want to listen for the words Connect to and grab anything that comes after that.

Thanks

**Comment by brianantonelli** [comment]
You can split the phrase on spaces to get all of the individual words.

```
parts = phrase.split
parts.each do |part|
  puts part
end
```

**Comment by ghost** [comment]
I think i'm stuck on how to start the process. I don't know the best way _i'm sure the other parts of my code needs major cleanup but i'll worry about that once I have everything done I want it to do_

I was looking at another plugin and notice this below which says it should intercept it but I have not luck there. I even removed everything and just put in a say "test" but it does nothing.

```
def speech_recognized(object, connection, phrase)
if phrase.match(/Connect to (.+)/i)
first, *rest = phrase.split("Connect to ")
    say "#{rest}" #test
end
request_completed
end
```

Second I was looking at something like this but wasn't sure how to complete it

```
listen_for /Connect to ???/i do
first, *rest = ???.split("Connect to ")
say "#{rest}" #testing
request_completed
end   
```

**Comment by brianantonelli** [comment]
You don't need to use `speech_recognized`. You should be able to just do

```
listen_for /connect to (.*)/ do |phrase|
    parts = phrase.split
    word_one = parts[0]
    word_two = parts[1]
    say "your first word was #{word_one} and your second was #{word_two}"
    request_completed
end
```

And test it by saying "Connect to the future"

**Comment by ghost** [comment]
Ah I see much thanks
