### ISSUE TITLE
Is someone working on tests?

### ISSUE THREAD

**Issue by kalbasit** [plamoni/SiriProxy#85]
Hey guys,

Great work on the proxy, really useful, but I noticed the code is untested, is anyone currently working on tests? I was thinking of writing specs but I do not want to re-invent the wheel if someone is already working on that

Wael

**Comment by netpro2k** [comment]
would love some help writing tests. Right now only cora has a small set of integration tests. If you know your way around rspec a set of tests for siriproxy would be very handy. I started working on a spec at the pluginmanager level, but I am also fairly new to rspec. It would be great to have a spec on the full stack, mocking only the sockets (we were thinking perhaps using the vcr gem, or similar network mocking lib). Would be happy to discuss more on irc

**Comment by kalbasit** [comment]
I'm actually quite familiar with RSpec (use it on daily basis) see my open source projects https://github.com/TechnoGate

The only problem I have is that I do not own an iPhone 4S at the moment and from reading the code I would only need two fixtures files, a request and a response (in binary form) would you be able to send me those fixtures ?

I'll PM you if I would need something else and I can start working on specs on the Weekend, this gives me time to release [Vimius](https://github.com/TechnoGate/vimius)

**Comment by netpro2k** [comment]
Unfortunately part of the binary data includes the unique identifier for the phone in question, so it is to sensitive to share/store in repo. I think best would be to have fixtures at the decoded object level (or perhaps the gziped decoded object level) as this would avoid the sensitive information, ssl handshake, etc. Its not quite  a full integration test, but covers the main aspects of the code that will actually be frequently modified.

**Comment by kalbasit** [comment]
Yes that will do fine

## 

Wael Nasreddine
Sent from my iPhone

On Nov 29, 2011, at 18:34, Dominick D'Aniello
reply@reply.github.com
wrote:

**Comment by netpro2k** [comment]
Great. If you have time please drop by irc channel (#siriproxy on freenode)  later and we can discuss further.

**Comment by kalbasit** [comment]
Ok will do in an hour, I'm on my way home (BTW I have great plans for
the project in mind we'll talk soon)

## 

Wael Nasreddine
Sent from my iPhone

On Nov 29, 2011, at 18:45, Dominick D'Aniello
reply@reply.github.com
wrote:
