### ISSUE TITLE
Siri shuts down instantly with siri proxy

### ISSUE THREAD

**Issue by LouisGhijselings** [plamoni/SiriProxy#87]
Now i got my connection with my macbook up and going another problem occurs. When i want to use siri, she instantly shuts down and is saying: "i'm really sorry about this, i cant take requests right now"

and this is showing at my terminal display

Starting SiriProxy on port 443..
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007f9233309ef0 @signature=3, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007f9233309bd0>, @zip_stream=#Zlib::Deflate:0x007f9233309ba8, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007f923306c990 @manager=#<SiriProxy::PluginManager:0x007f92333094f0 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007f923306a758 @signature=4, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007f92330678f0>, @zip_stream=#Zlib::Deflate:0x007f92330678c8, @consumed_ace=false, @name="iPhone", @ssled=false>
[Info - Plugin Manager] Plugins laoded: [#<SiriProxy::Plugin::Example:0x007f9233065cf8 @manager=#<SiriProxy::PluginManager:0x007f9233066c48 @plugins=[...]>>]
Create server for iPhone connection
start conn #<SiriProxy::Connection::Iphone:0x007f9233065870 @signature=5, @processed_headers=false, @output_buffer="", @input_buffer="", @unzipped_input="", @unzipped_output="", @unzip_stream=#<Zlib::Inflate:0x007f9233065668>, @zip_stream=#Zlib::Deflate:0x007f9233065618, @consumed_ace=false, @name="iPhone", @ssled=false>

i can't make anything out of it

**Comment by netpro2k** [comment]
Your siirproxy box has its dns set to dnsmasq, it needs to be able to resolve guzzoni

**Comment by LouisGhijselings** [comment]
I am sorry but i am not following here. What do you mean exactly with that answer? I am new into all this

**Comment by LouisGhijselings** [comment]
Changing the DNS servers on my computer to those of openDNS did not
work. Or did you mean something else?

2011/11/30 Dominick D'Aniello
reply@reply.github.com:

**Comment by netpro2k** [comment]
That is what I meant. Your computer needs to be pointing to a normal dns, and your iphone should be pointing to dnsmasq. After changing this you are getting the same error?

**Comment by LouisGhijselings** [comment]
And the dns addresses of openDNS are not good? Because at first on my
computer I had no specific dns (the list of dns in network preferences
was empty) and the siri proxy gave me this loop then. So I tried
changing the DNS on my computer to those of opendns, but this gave me
the same error,no changes, every time i press the siri button this
piece of code posted yesterday shows again

The dns on my iphone is set to 10.0.1.2 which is my computers ip
address(and also the address I gave in into dnsmasq.config
(address=/guzzoni.apple.com/10.0.1.2) )

2011/11/30 Dominick D'Aniello
reply@reply.github.com:

**Comment by rosswaycaster** [comment]
I am having this exact same problem.. Any advice? I feel like I am so close to getting this to work!

**Comment by Enophi** [comment]
Me too, exactly the same
