### ISSUE TITLE
No Reponse from server

### ISSUE THREAD

**Issue by samukbg** [plamoni/SiriProxy#90]
Hi plamoni, i'm have the same trouble as SONY:

$ rvmsudo ruby start.rb 
start.rb:3: warning: variable $KCODE is no longer effective; ignored
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Starting SiriProxy on port 443..

nothing happens and when i try to say 'test siri proxy' it even let me say, it says: "Sorry, i'm having trouble...". 
I've put the ip address in iPhone's DNS settings and my dnsmasq starts without any error on my mac. My Xcode is version 4.2 if this helps anyway.
Thanks for any help.

**Comment by ghost** [comment]
did you configure dnsmasq correctly?

**Comment by netpro2k** [comment]
This is an issue either with iphone dns or dnsmasq settings

**Comment by samukbg** [comment]
it just work on iPhone 4s right? Never mind, i'm on iPhone 4. Thank you btw.
