### ISSUE TITLE
can't find config.yml

### ISSUE THREAD

**Issue by shameer99** [plamoni/SiriProxy#91]
in step 7 it says to edit config.yml what is that file and where can i find it thanks

**Comment by netpro2k** [comment]
you need to create it. An example config file is included in the repo as config.example.yml

**Comment by shameer99** [comment]
thanks it looks completely different as to when i tried and failed. gonna try again

**Comment by benblamey** [comment]
I think the message needs to be changed:

"Initialization complete! Please review and modify the auto-generated
'config.yml' file to ensure it contains the root directories to all
of the installed Rubies you want enhanced by the DevKit."

You're saying there is no file called config.yml - I call that confusing!
