### ISSUE TITLE
How to setup Bind

### ISSUE THREAD

**Issue by JBX028** [plamoni/SiriProxy#93]
Hello,

This definitively not an issue but i do not know how to post my request. I am using windows and not MacOS. I have successfully installed ruby and the required gems and everything works fine when i run the proxy. 

Unfortunately dnsmasq is not compatible with windows but i know that bind provide pretty much the same functionnalities but to be honest i am lost with the documentation.

Does anybody did the setting with bind instead of dnsmasq ? if yes a short explanation on how to properly setup the .conf file would be great appreciate.

Worth case scenario, i will setup a linux virtualbox image but because the ruby part works fine, it would be good to try to let the whole process working on windows.

Thanks in advance

Johnny Baillargeaux (France)

**Comment by plamoni** [comment]
This is not a bind support forum and we don't provide support for SiriProxy on Windows (or even on any other OS at this time). I suggest you check Google for info on using Bind (it's not easy). And if you don't know enough about DNS to figure out (with help from Google) the basic structure of what needs to be done, then you probably aren't qualified to be running SiriProxy yet.

Again, this project is not for general consumption. It's in a very early pre-alpha stage of development and we really don't have time to get everyone up and running manually, sorry.
