### ISSUE TITLE
Cora Error

### ISSUE THREAD

**Issue by KirmaanA** [plamoni/SiriProxy#97]
I Have Run It On The New Ruby And It Still Returns These Errors

/Users/Kirmaan/Desktop/SiriProxy/start.rb 
Password:
/Users/Kirmaan/Desktop/SiriProxy/start.rb:3: warning: variable $KCODE is no longer effective; ignored
/Users/Kirmaan/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- cora (LoadError)
    from /Users/Kirmaan/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from /Users/Kirmaan/Desktop/SiriProxy/siri_proxy/plugin.rb:1:in `<top (required)>'
    from /Users/Kirmaan/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from /Users/Kirmaan/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/Kirmaan/Desktop/SiriProxy/start.rb:17:in`<main>'

**Comment by kalbasit** [comment]
from what I see, you are not using the latest additions to the master branch, please try updating first

**Comment by KirmaanA** [comment]
Updating What ?

**Comment by kalbasit** [comment]
SiriProxy just run git pull in While in SiriProxy folder and follow the Readme

## 

Wael Nasreddine
Sent from my iPhone

On Nov 30, 2011, at 17:14, KirmaanA
reply@reply.github.com
wrote:

**Comment by KirmaanA** [comment]
Thanks For All The Help So Far, But When I Run That it Doesn't Work

Kirmaan-Aboobakers-MacBook-Air:SiriProxy Kirmaan$ git pull
fatal: Not a git repository (or any of the parent directories): .git

**Comment by kalbasit** [comment]
The just delete the entire SiriProxy folder and follow the readme from start

## 

Wael Nasreddine
Sent from my iPhone

On Nov 30, 2011, at 17:54, KirmaanA
reply@reply.github.com
wrote:

**Comment by plamoni** [comment]
This is not an issue with the code. Please visit the IRC chat or other resources for assistance in getting up and running.
