### ISSUE TITLE
siriproxy gencerts

### ISSUE THREAD

**Issue by delrio1110** [plamoni/SiriProxy#99]
i get the following error when I try to run the siriproxy gencerts

David-Hernandezs-iMac:siriproxy2 dhernandez1110$ siriproxy gencerts
/Users/dhernandez1110/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems.rb:314:in `bin_path': can't find gem siriproxy ([">= 0"]) with executable siriproxy (Gem::GemNotFoundException)
    from /Users/dhernandez1110/.rvm/gems/ruby-1.9.3-p0/bin/siriproxy:19:in`<main>'

**Comment by Taruga** [comment]
I'm having the following problem:

taruga:SiriProxy taruga$ siriproxy gencerts
mv: rename /tmp/newcert.pem to /Users/taruga/.siriproxy/server.passless.crt: No such file or directory
Creating CA directory
Generating 'SiriProxyCA' CA request
Self-signing 'SiriProxyCA' CA
Generating guzzoni.apple.com certificate request
Generating 'SiriProxyCA' CA request
Generating guzzoni.apple.com certificate
Removing passphrase from guzzoni.apple.com key
Cleaning up...

## Done! (For details on any errors, check '/Users/taruga/.siriproxy/cert.log')

Please install /Users/taruga/.siriproxy/ca.pem onto your phone!
(Note: You can do this by emailing the file to yourself)

---

And the generated ca.pem file is zero bytes !!!

**Comment by delrio1110** [comment]
it states that "bin_path': can't find gem siriproxy"

**Comment by Taruga** [comment]
delrio1110 , did you clone the repo ? (   git clone https://github.com/plamoni/SiriProxy.git   )

**Comment by delrio1110** [comment]
Yes

**Comment by plamoni** [comment]
This error has been fixed in the dev branch.

**Comment by delrio1110** [comment]
do i need to reinstall everything again because im getting the same error when i run
sh-3.2# siriproxy gencerts
/Users/dhernandez1110/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems.rb:314:in `bin_path': can't find gem siriproxy ([">= 0"]) with executable siriproxy (Gem::GemNotFoundException)
    from /Users/dhernandez1110/.rvm/gems/ruby-1.9.3-p0/bin/siriproxy:19:in`<main>'

and i clonesd the dev files?

**Comment by ghost** [comment]
Having the exact same problem with:

bin_path': can't find gem siriproxy ([">= 0"]) with executable siriproxy (Gem::GemNotFoundException)
from /Users/dhernandez1110/.rvm/gems/ruby-1.9.3-p0/bin/siriproxy:19:in'

But I downloaded SiriProxy today! (31/12) so maybe i did something wrong or it hasn't been fixed in the dev branch
